NE591-008 C++17 Codebase: InLab5 Class Reference
InLab5 Class Reference
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution, with pivoting.
#include <inlab5.h>
Public Member Functions
InLab5 (CommandLineArgs args)
Constructor for the inlab5 class.
void execute ()
Executes the project.
Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (MyBLAS::OutputVector &outputs, MyBLAS::InputMatrices &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void preRun (MyBLAS::OutputVector &output, MyBLAS::InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (MyBLAS::OutputVector &output, MyBLAS::InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
Private Member Functions
void initialize ()
Initializes the project.
void timedRun ()
Executes the project and measures the execution time.
Private Attributes
CommandLineArgs cmdArgs
Parser terminal
MyBLAS::OutputVector outputs
Detailed Description
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution, with pivoting.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
InLab5()
InLab5::InLab5 (CommandLineArgs args) inline explicit
Constructor for the inlab5 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab5::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >.
{
         Canvas canvas;
         printJuliaSet<__float128>(canvas, -0.8, 0.156, 300); //"o█■"
         std::cout << "\t\t\tJulia set at (-0.8, 0.156), 300 iterations\n";
         return {
             .ProjectName = "InLab 05",
             .ProjectDescription = "Linear equations with permutation matrix, forward, back substitution",
             .SubmissionDate = "09/22/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
execute()
void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::execute () inline inherited
Executes the project.
                    {
         initialize();
         timedRun();
     }
getTerminal()
Parser Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getTerminal () const inline inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::initialize () inline private inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::postRun (MyBLAS::OutputVector & output, MyBLAS::InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::preRun (MyBLAS::OutputVector & output, MyBLAS::InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void InLab5::run (MyBLAS::OutputVector & outputs, MyBLAS::InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution, with pivoting
Parameters
outputs The output vector
inputs The input matrices
values The variable map
Implements Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >.
{
         // PAx = Pb, or LUx = P
         const auto b = inputs.constants;
         const auto LU = inputs.LU;
         const auto P = inputs.permutation;
         const auto Pb = P * b;
         const MyBLAS::Vector y = MyBLAS::forwardSubstitution<long double>(LU, Pb);
         const MyBLAS::Vector x = MyBLAS::backwardSubstitution<long double>(LU, y);
         nlohmann::json results;
         outputs.solution = x;
         outputs.toJSON(results["outputs"]);
         if (!values.count("quiet")) {
             const auto precision = getTerminal().getCurrentPrecision();
             std::cout << "Permuted constants Pb = P * b:\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << Pb;
             Parser::printLine();
             std::cout << "Intermediate vector y = inv(L) * b:\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << y;
             Parser::printLine();
             std::cout << "Solution vector (x):\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << x;
             Parser::printLine();
         }
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References CommandLine< InputType >::getCurrentPrecision(), Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >::getTerminal(), process::inputs, Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >::outputs, CommandLine< InLab6Inputs >::printLine(), MyBLAS::Output::solution, MyBLAS::Output::toJSON(), writeJSON(), x, and y.
timedRun()
void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::timedRun () inline private inherited
Executes the project and measures the execution time.
 { run(outputs, terminal.getInputs(), terminal.getArguments()); }
Field Documentation
cmdArgs
CommandLineArgs Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::cmdArgs private inherited
outputs
MyBLAS::OutputVector Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::outputs private inherited
terminal
Parser Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::terminal private inherited
The documentation for this class was generated from the following file:
src/labs/inlab5/inlab5.h