NE591-008 C++17 Codebase: MyLinearSolvingMethod::Solution< T > Struct Template Reference
MyLinearSolvingMethod::Solution< T > Struct Template Reference
Structure that represents the solution of the linear solver.
#include <LinearSolver.h>
Public Member Functions
Solution (MyBLAS::Vector< T > &initial)
Solution (size_t size)
Solution ()=default
MyBLAS::Vector< T > getResidual (MyBLAS::Matrix< T > a) const
T getMaxResidual (MyBLAS::Matrix< T > a, MyBLAS::Vector< T > b) const
void toJSON (nlohmann::json &jsonMap) const
Converts the output parameters to a JSON object.
Data Fields
MyLinearSolvingMethod::Type method
bool converged = false
size_t iterations = std::numeric_limits<size_t>::quiet_NaN()
T iterative_error = std::numeric_limits<T>::quiet_NaN()
MyBLAS::Vector< T > x {}
Friends
std::ostream & operator<< (std::ostream &os, const Solution &solution)
Overloaded stream insertion operator to print the summary statistics.
Detailed Description
template<typename T>
struct MyLinearSolvingMethod::Solution< T >
Structure that represents the solution of the linear solver.
Template Parameters
T The type of the elements in the matrix/vector.
Constructor & Destructor Documentation
Solution() [1/3]
template<typename T > MyLinearSolvingMethod::Solution< T >::Solution (MyBLAS::Vector< T > & initial) inline explicit
 { x = initial; }
Solution() [2/3]
template<typename T > MyLinearSolvingMethod::Solution< T >::Solution (size_t size) inline explicit
 { x = MyBLAS::Vector<T>(size, 0); }
Solution() [3/3]
template<typename T > MyLinearSolvingMethod::Solution< T >::Solution () default
Member Function Documentation
getMaxResidual()
template<typename T > T MyLinearSolvingMethod::Solution< T >::getMaxResidual (MyBLAS::Matrix< T > a, MyBLAS::Vector< T > b) const inline
{
         return MyBLAS::Stats::max<T>(MyBLAS::Stats::abs(b - getResidual(a)));
     }
References MyBLAS::Stats::abs().
getResidual()
template<typename T > MyBLAS::Vector<T> MyLinearSolvingMethod::Solution< T >::getResidual (MyBLAS::Matrix< T > a) const inline
 { return a * x; }
References x.
toJSON()
template<typename T > void MyLinearSolvingMethod::Solution< T >::toJSON (nlohmann::json & jsonMap) const inline
Converts the output parameters to a JSON object.
Parameters
jsonMap The JSON object to which the output parameters are added.
{
         jsonMap["converged"] = converged;
         jsonMap["iterations"]["actual"] = iterations;
         jsonMap["iterative-error"]["actual"] = iterative_error;
         jsonMap["solution"] = x.getData();
     }
References postprocess::converged, postprocess::iterations, postprocess::iterative_error, and x.
Friends And Related Function Documentation
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const Solution< T > & solution) friend
Overloaded stream insertion operator to print the summary statistics.
Parameters
os The output stream.
summary The summary statistics to print.
Returns
The output stream.
{
         auto precision = std::cout.precision() ;
         const std::string key = MyLinearSolvingMethod::TypeKey(solution.method);
         const auto width = static_cast<int>(2 + static_cast<std::streamsize>(10));
         os << std::setprecision(2) << std::setw(width) << std::setfill(' ') << std::scientific;
         os << ":::::: Converged       : " << (solution.converged ? "Yes" : "No")<<std::endl;
         os << ":::::: Iterations      : " << solution.iterations<<std::endl;
         os << ":::::: Iterative Error : " << solution.iterative_error<<std::endl;
         os << std::setprecision(static_cast<int>(precision));
         return os;
     }
Field Documentation
converged
template<typename T > bool MyLinearSolvingMethod::Solution< T >::converged = false
Referenced by MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applySOR(), and MyRelaxationMethod::applySSOR().
iterations
template<typename T > size_t MyLinearSolvingMethod::Solution< T >::iterations = std::numeric_limits<size_t>::quiet_NaN()
Referenced by MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applySOR(), and MyRelaxationMethod::applySSOR().
iterative_error
template<typename T > T MyLinearSolvingMethod::Solution< T >::iterative_error = std::numeric_limits<T>::quiet_NaN()
Referenced by MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applySOR(), and MyRelaxationMethod::applySSOR().
method
template<typename T > MyLinearSolvingMethod::Type MyLinearSolvingMethod::Solution< T >::method
x
template<typename T > MyBLAS::Vector<T> MyLinearSolvingMethod::Solution< T >::x {}
Referenced by MyBLAS::LUP::applyLUP(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applySOR(), and MyRelaxationMethod::applySSOR().
The documentation for this struct was generated from the following file:
src/utils/math/LinearSolver.h