NE591-008 C++17 Codebase: MyBLAS::LazyMatrix< DataType > Class Template Reference
MyBLAS::LazyMatrix< DataType > Class Template Reference
A matrix that lazily computes its values.
#include <LazyMatrix.h>
Data Structures
class ConstProxy
A helper class to provide a proxy for const access to a row of the LazyMatrix.
class Proxy
A helper class to provide a proxy for non-const access to a row of the LazyMatrix.
Public Types
using Generator = std::function< DataType(size_t, size_t)>
Type alias for the generator function.
Public Member Functions
LazyMatrix (size_t rows=0, size_t cols=0, Generator generator=nullptr)
Constructor for the LazyMatrix class.
LazyMatrix (const MyBLAS::Matrix< DataType > &matrix)
Constructor for the LazyMatrix class that accepts a Matrix object.
LazyMatrix (MyBLAS::Matrix< DataType > &matrix)
Constructor for the LazyMatrix class that accepts a non-const reference to a Matrix object.
virtual size_t getAllocatedBytes (bool actual=false) const
Returns the number of bytes allocated by the LazyMatrix.
virtual size_t getRows () const
Returns the number of rows in the matrix.
virtual size_t getCols () const
Returns the number of columns in the matrix.
virtual DataType operator() (size_t row, size_t col) const
Computes and returns the value at the specified row and column.
virtual ~LazyMatrix ()
Destructor for the LazyMatrix class.
LazyMatrix (const LazyMatrix &other)
Copy constructor for the LazyMatrix class.
LazyMatrix (const LazyMatrix &&other) noexcept
Move constructor for the LazyMatrix class.
LazyMatrix & operator= (const LazyMatrix &other)
Copy assignment operator for the LazyMatrix class.
LazyMatrix operator+ (DataType scalar) const
Overload of the addition operator for adding a scalar to a LazyMatrix.
LazyMatrix operator- (DataType scalar) const
Overload of the subtraction operator for subtracting a scalar from a LazyMatrix.
LazyMatrix operator* (DataType scalar) const
Overload of the multiplication operator for multiplying a LazyMatrix by a scalar.
LazyMatrix operator/ (DataType scalar) const
Overload of the division operator for dividing a LazyMatrix by a scalar.
LazyMatrix operator- () const
Overload of the unary negation operator for a LazyMatrix.
LazyMatrix & operator+= (LazyMatrix const &b)
Overload of the addition assignment operator for adding a LazyMatrix to the current matrix.
LazyMatrix & operator-= (LazyMatrix const &b)
Overload of the subtraction assignment operator for subtracting a LazyMatrix from the current matrix.
LazyMatrix & operator*= (LazyMatrix const &b)
Overload of the multiplication assignment operator for multiplying a LazyMatrix with the current matrix.
LazyMatrix & operator/= (LazyMatrix const &b)
Overload of the division assignment operator for dividing the current matrix by a LazyMatrix.
LazyMatrix & operator+= (DataType scalar)
Overload of the addition assignment operator for adding a scalar to the current matrix.
LazyMatrix & operator-= (DataType scalar)
Overload of the subtraction assignment operator for subtracting a scalar from the current matrix.
LazyMatrix & operator*= (DataType scalar)
Overload of the multiplication assignment operator for multiplying the current matrix by a scalar.
LazyMatrix & operator/= (DataType scalar)
Overload of the division assignment operator for dividing the current matrix by a scalar.
LazyVector< DataType > asRowVector () const
Returns a LazyVector representing the matrix in row-major order.
LazyVector< DataType > asColumnVector () const
Returns a LazyVector representing the matrix in column-major order.
Proxy operator[] (size_t row)
Overload of the [] operator for non-const access to a row of the LazyMatrix.
ConstProxy operator[] (size_t row) const
Overload of the [] operator for const access to a row of the LazyMatrix.
Protected Member Functions
void setRows (size_t rows)
Setter for the number of rows in the LazyMatrix.
void setCols (size_t cols)
Setter for the number of columns in the LazyMatrix.
void setGenerator (const Generator &generator)
Setter for the generator function of the LazyMatrix.
Private Attributes
size_t rows_ {}
The number of rows in the LazyMatrix.
size_t cols_ {}
The number of columns in the LazyMatrix.
Generator generator_
The generator function that computes the values of the LazyMatrix.
std::shared_ptr< MyBLAS::Matrix< DataType > > matrix_
A shared pointer to the memory backed matrix.
Friends
LazyMatrix operator* (MyBLAS::Matrix< DataType > const &a, LazyMatrix const &b)
Overload of the multiplication operator for multiplying a MyBLAS::Matrix and a LazyMatrix.
LazyMatrix operator* (LazyMatrix const &a, MyBLAS::Matrix< DataType > const &b)
Overload of the multiplication operator for multiplying a LazyMatrix and a MyBLAS::Matrix.
LazyMatrix operator* (LazyMatrix const &a, LazyMatrix const &b)
Overload of the multiplication operator for multiplying two LazyMatrix objects.
MyBLAS::Vector< DataType > operator* (LazyMatrix const &a, MyBLAS::Vector< DataType > const &b)
Overload of the multiplication operator for multiplying a LazyMatrix and a MyBLAS::Vector.
LazyVector< DataType > operator* (LazyMatrix const &a, LazyVector< DataType > const &b)
Overload of the multiplication operator for multiplying a LazyMatrix and a LazyVector.
LazyMatrix operator+ (MyBLAS::Matrix< DataType > const &a, LazyMatrix const &b)
Overload of the addition operator for adding a MyBLAS::Matrix and a LazyMatrix.
LazyMatrix operator+ (LazyMatrix const &a, MyBLAS::Matrix< DataType > const &b)
Overload of the addition operator for adding a LazyMatrix and a MyBLAS::Matrix.
LazyMatrix operator+ (LazyMatrix const &a, LazyMatrix const &b)
Overload of the addition operator for adding two LazyMatrix objects.
LazyMatrix operator- (MyBLAS::Matrix< DataType > const &a, LazyMatrix const &b)
Overload of the subtraction operator for subtracting a LazyMatrix from a MyBLAS::Matrix.
LazyMatrix operator- (LazyMatrix const &a, MyBLAS::Matrix< DataType > const &b)
Overload of the subtraction operator for subtracting a MyBLAS::Matrix from a LazyMatrix.
LazyMatrix operator- (LazyMatrix const &a, LazyMatrix const &b)
Overload of the subtraction operator for subtracting one LazyMatrix from another.
LazyMatrix operator== (MyBLAS::Matrix< DataType > const &a, LazyMatrix const &b)
Overload of the equality operator for comparing a MyBLAS::Matrix and a LazyMatrix.
LazyMatrix operator== (LazyMatrix const &a, MyBLAS::Matrix< DataType > const &b)
Overload of the equality operator for comparing a LazyMatrix and a MyBLAS::Matrix.
LazyMatrix operator== (LazyMatrix const &a, LazyMatrix const &b)
Overload of the equality operator for comparing two LazyMatrix objects.
LazyMatrix operator!= (MyBLAS::Matrix< DataType > const &a, LazyMatrix const &b)
Overload of the inequality operator for comparing a MyBLAS::Matrix and a LazyMatrix.
LazyMatrix operator!= (LazyMatrix const &a, MyBLAS::Matrix< DataType > const &b)
Overload of the inequality operator for comparing a LazyMatrix and a MyBLAS::Matrix.
LazyMatrix operator!= (LazyMatrix const &a, LazyMatrix const &b)
Overload of the inequality operator for comparing two LazyMatrix objects.
LazyMatrix< bool > equal (LazyMatrix const &a, LazyMatrix const &b)
Function to compare two LazyMatrix objects for element-wise equality.
bool allElementsEqual (LazyMatrix const &a, LazyMatrix const &b)
Function to compare two LazyMatrix objects for equality.
Detailed Description
template<typename DataType>
class MyBLAS::LazyMatrix< DataType >
A matrix that lazily computes its values.
This class represents a matrix whose values are computed on-the-fly each time they're accessed. The computation is defined by a generator function provided at construction time.
Note: This implementation does not cache computed values. Even though we're using the lazy evaluation pattern here, we've made the choice to ignore caching of computed values for simplicity and to save memory. This could be less efficient if the computation is expensive and the same values are accessed multiple times. The choice between this approach and caching computed values depends on the specific requirements of your application.
Member Typedef Documentation
Generator
template<typename DataType > using MyBLAS::LazyMatrix< DataType >::Generator = std::function<DataType(size_t, size_t)>
Type alias for the generator function.
The generator function takes two size_t parameters (representing the row and column indices) and returns a value of the DataType.
Constructor & Destructor Documentation
LazyMatrix() [1/5]
template<typename DataType > MyBLAS::LazyMatrix< DataType >::LazyMatrix (size_t rows = 0, size_t cols = 0, Generator generator = nullptr) inline explicit
Constructor for the LazyMatrix class.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
generator The generator function used to compute the values of the matrix.
         : rows_(rows), cols_(cols), generator_(std::move(generator)) {
         ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
     }
Referenced by MyBLAS::LazyMatrix< DataType >::operator*(), MyBLAS::LazyMatrix< DataType >::operator+(), MyBLAS::LazyMatrix< DataType >::operator-(), and MyBLAS::LazyMatrix< DataType >::operator/().
LazyMatrix() [2/5]
template<typename DataType > MyBLAS::LazyMatrix< DataType >::LazyMatrix (const MyBLAS::Matrix< DataType > & matrix) inline explicit
Constructor for the LazyMatrix class that accepts a Matrix object.
Parameters
matrix The Matrix object to initialize the LazyMatrix with. The generator function is set to access the elements of the given matrix.
         : rows_(matrix.getRows()), cols_(matrix.getCols()), matrix_(std::make_shared<MyBLAS::Matrix<DataType>>(matrix)) {
         generator_ = [matrix](size_t i, size_t j) { return matrix(i, j); };
         ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
LazyMatrix() [3/5]
template<typename DataType > MyBLAS::LazyMatrix< DataType >::LazyMatrix (MyBLAS::Matrix< DataType > & matrix) inline explicit
Constructor for the LazyMatrix class that accepts a non-const reference to a Matrix object.
Parameters
matrix The Matrix object to initialize the LazyMatrix with. The generator function is set to access the elements of the given matrix.
         : rows_(matrix.getRows()), cols_(matrix.getCols()), matrix_(std::make_shared<MyBLAS::Matrix<DataType>>(matrix)) {
         generator_ = [matrix](size_t i, size_t j) { return matrix(i, j); };
         ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
~LazyMatrix()
template<typename DataType > virtual MyBLAS::LazyMatrix< DataType >::~LazyMatrix () inline virtual
Destructor for the LazyMatrix class.
{
         ResourceMonitor<LazyMatrix<DataType>>::unregisterInstance(this);
     }
LazyMatrix() [4/5]
template<typename DataType > MyBLAS::LazyMatrix< DataType >::LazyMatrix (const LazyMatrix< DataType > & other) inline
Copy constructor for the LazyMatrix class.
Parameters
other The LazyMatrix object to be copied.
                                         : rows_(other.rows_), cols_(other.cols_), generator_(other.generator_) {
         ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
     }
LazyMatrix() [5/5]
template<typename DataType > MyBLAS::LazyMatrix< DataType >::LazyMatrix (const LazyMatrix< DataType > && other) inline noexcept
Move constructor for the LazyMatrix class.
Parameters
other The LazyMatrix object to be copied.
         : rows_(other.rows_), cols_(other.cols_), generator_(std::move(other.generator_)), matrix_(std::move(other.matrix_)) {
         other.rows_ = 0;
         other.cols_ = 0;
         other.generator_ = nullptr;
         other.matrix_ = nullptr;
         ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
     }
Member Function Documentation
asColumnVector()
template<typename DataType > LazyVector<DataType> MyBLAS::LazyMatrix< DataType >::asColumnVector () const inline
Returns a LazyVector representing the matrix in column-major order.
Returns
A LazyVector with elements in column-major order.
{
         size_t totalElements = rows_ * cols_;
         return LazyVector<DataType>(totalElements, [this](size_t idx) {
             size_t row = idx % rows_; // Modulo operation to find the row index
             size_t col = idx / rows_; // Integer division to find the column index
             return this->operator()(row, col);
         });
     }
References MyBLAS::LazyMatrix< DataType >::cols_, MyBLAS::LazyMatrix< DataType >::operator()(), process::row, and MyBLAS::LazyMatrix< DataType >::rows_.
asRowVector()
template<typename DataType > LazyVector<DataType> MyBLAS::LazyMatrix< DataType >::asRowVector () const inline
Returns a LazyVector representing the matrix in row-major order.
Returns
A LazyVector with elements in row-major order.
{
         size_t totalElements = rows_ * cols_;
         return LazyVector<DataType>(totalElements, [this](size_t idx) {
             size_t row = idx / cols_; // Integer division to find the row index
             size_t col = idx % cols_; // Modulo operation to find the column index
             return this->operator()(row, col);
         });
     }
References MyBLAS::LazyMatrix< DataType >::cols_, MyBLAS::LazyMatrix< DataType >::operator()(), process::row, and MyBLAS::LazyMatrix< DataType >::rows_.
Referenced by FluxCalculationTests< T >::getSources().
getAllocatedBytes()
template<typename DataType > virtual size_t MyBLAS::LazyMatrix< DataType >::getAllocatedBytes (bool actual = false) const inline virtual
Returns the number of bytes allocated by the LazyMatrix.
Parameters
actual If true, calculates the actual allocated bytes, otherwise returns the size of the LazyMatrix object.
Returns
The number of bytes allocated by the LazyMatrix.
Reimplemented in MyPhysics::Diffusion::Matrix< T >.
{
         return sizeof(*this);
     }
getCols()
template<typename DataType > virtual size_t MyBLAS::LazyMatrix< DataType >::getCols () const inline virtual
Returns the number of columns in the matrix.
Returns
The number of columns in the matrix.
Reimplemented in MyPhysics::Diffusion::Matrix< T >.
 { return cols_; }
References MyBLAS::LazyMatrix< DataType >::cols_.
Referenced by MyBLAS::LazyMatrix< DataType >::operator*(), MyBLAS::LazyMatrix< DataType >::operator+(), MyBLAS::LazyMatrix< DataType >::operator-(), MyBLAS::LazyMatrix< DataType >::operator/(), and MyBLAS::TYPED_TEST().
getRows()
template<typename DataType > virtual size_t MyBLAS::LazyMatrix< DataType >::getRows () const inline virtual
Returns the number of rows in the matrix.
Returns
The number of rows in the matrix.
Reimplemented in MyPhysics::Diffusion::Matrix< T >.
 { return rows_; }
References MyBLAS::LazyMatrix< DataType >::rows_.
Referenced by MyBLAS::LazyMatrix< DataType >::operator*(), MyBLAS::LazyMatrix< DataType >::operator+(), MyBLAS::LazyMatrix< DataType >::operator-(), MyBLAS::LazyMatrix< DataType >::operator/(), and MyBLAS::TYPED_TEST().
operator()()
template<typename DataType > virtual DataType MyBLAS::LazyMatrix< DataType >::operator() (size_t row, size_t col) const inline virtual
Computes and returns the value at the specified row and column.
Parameters
row The row index.
col The column index.
Returns
The computed value at the specified row and column.
{
         return generator_(row, col);
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and process::row.
Referenced by MyBLAS::LazyMatrix< DataType >::asColumnVector(), and MyBLAS::LazyMatrix< DataType >::asRowVector().
operator*()
template<typename DataType > LazyMatrix MyBLAS::LazyMatrix< DataType >::operator* (DataType scalar) const inline
Overload of the multiplication operator for multiplying a LazyMatrix by a scalar.
This function performs element-wise multiplication between a LazyMatrix and a scalar.
Template Parameters
DataType The type of data contained in the matrix and the scalar.
Parameters
scalar The scalar to multiply the matrix by.
Returns
A LazyMatrix that represents the result of the multiplication.
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) * scalar; });
     }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and MyBLAS::LazyMatrix< DataType >::LazyMatrix().
operator*=() [1/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator*= (DataType scalar) inline
Overload of the multiplication assignment operator for multiplying the current matrix by a scalar.
This function performs element-wise multiplication between the current matrix and a scalar.
Parameters
scalar The scalar to be multiplied.
Returns
A reference to the current matrix which now represents the result of the multiplication.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) * scalar; };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator*=() [2/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator*= (LazyMatrix< DataType > const & b) inline
Overload of the multiplication assignment operator for multiplying a LazyMatrix with the current matrix.
This function performs element-wise multiplication between the current matrix and another LazyMatrix.
Parameters
b A constant reference to the LazyMatrix to be multiplied.
Returns
A reference to the current matrix which now represents the result of the multiplication.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) * b(i, j); };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator+()
template<typename DataType > LazyMatrix MyBLAS::LazyMatrix< DataType >::operator+ (DataType scalar) const inline
Overload of the addition operator for adding a scalar to a LazyMatrix.
This function performs element-wise addition between a LazyMatrix and a scalar.
Template Parameters
DataType The type of data contained in the matrix and the scalar.
Parameters
scalar The scalar to be added to the matrix.
Returns
A LazyMatrix that represents the result of the addition.
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) + scalar; });
     }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and MyBLAS::LazyMatrix< DataType >::LazyMatrix().
operator+=() [1/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator+= (DataType scalar) inline
Overload of the addition assignment operator for adding a scalar to the current matrix.
This function performs element-wise addition between the current matrix and a scalar.
Parameters
scalar The scalar to be added.
Returns
A reference to the current matrix which now represents the result of the addition.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) + scalar; };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator+=() [2/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator+= (LazyMatrix< DataType > const & b) inline
Overload of the addition assignment operator for adding a LazyMatrix to the current matrix.
This function performs element-wise addition between the current matrix and another LazyMatrix.
Parameters
b A constant reference to the LazyMatrix to be added.
Returns
A reference to the current matrix which now represents the result of the addition.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) + b(i, j); };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator-() [1/2]
template<typename DataType > LazyMatrix MyBLAS::LazyMatrix< DataType >::operator- () const inline
Overload of the unary negation operator for a LazyMatrix.
This function performs element-wise negation on a LazyMatrix.
Returns
A LazyMatrix that represents the result of the negation.
{
         return LazyMatrix(getRows(), getCols(), [this](size_t i, size_t j) { return -(*this)(i, j); });
     }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and MyBLAS::LazyMatrix< DataType >::LazyMatrix().
operator-() [2/2]
template<typename DataType > LazyMatrix MyBLAS::LazyMatrix< DataType >::operator- (DataType scalar) const inline
Overload of the subtraction operator for subtracting a scalar from a LazyMatrix.
This function performs element-wise subtraction between a LazyMatrix and a scalar.
Template Parameters
DataType The type of data contained in the matrix and the scalar.
Parameters
scalar The scalar to be subtracted from the matrix.
Returns
A LazyMatrix that represents the result of the subtraction.
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) - scalar; });
     }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and MyBLAS::LazyMatrix< DataType >::LazyMatrix().
operator-=() [1/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator-= (DataType scalar) inline
Overload of the subtraction assignment operator for subtracting a scalar from the current matrix.
This function performs element-wise subtraction between the current matrix and a scalar.
Parameters
scalar The scalar to be subtracted.
Returns
A reference to the current matrix which now represents the result of the subtraction.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) - scalar; };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator-=() [2/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator-= (LazyMatrix< DataType > const & b) inline
Overload of the subtraction assignment operator for subtracting a LazyMatrix from the current matrix.
This function performs element-wise subtraction between the current matrix and another LazyMatrix.
Parameters
b A constant reference to the LazyMatrix to be subtracted.
Returns
A reference to the current matrix which now represents the result of the subtraction.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) - b(i, j); };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator/()
template<typename DataType > LazyMatrix MyBLAS::LazyMatrix< DataType >::operator/ (DataType scalar) const inline
Overload of the division operator for dividing a LazyMatrix by a scalar.
This function performs element-wise division between a LazyMatrix and a scalar.
Template Parameters
DataType The type of data contained in the matrix and the scalar.
Parameters
scalar The scalar to divide the matrix by.
Returns
A LazyMatrix that represents the result of the division.
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) / scalar; });
     }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and MyBLAS::LazyMatrix< DataType >::LazyMatrix().
operator/=() [1/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator/= (DataType scalar) inline
Overload of the division assignment operator for dividing the current matrix by a scalar.
This function performs element-wise division between the current matrix and a scalar.
Parameters
scalar The scalar to be divided by.
Returns
A reference to the current matrix which now represents the result of the division.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) / scalar; };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator/=() [2/2]
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator/= (LazyMatrix< DataType > const & b) inline
Overload of the division assignment operator for dividing the current matrix by a LazyMatrix.
This function performs element-wise division between the current matrix and another LazyMatrix.
Parameters
b A constant reference to the LazyMatrix to be divided by.
Returns
A reference to the current matrix which now represents the result of the division.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) / b(i, j); };
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::generator_, and i.
operator=()
template<typename DataType > LazyMatrix& MyBLAS::LazyMatrix< DataType >::operator= (const LazyMatrix< DataType > & other) inline
Copy assignment operator for the LazyMatrix class.
Parameters
other The LazyMatrix object to be copied.
Returns
A reference to the current object.
{
         if (this != &other) {
             rows_ = other.rows_;
             cols_ = other.cols_;
             generator_ = other.generator_;
             matrix_ = other.matrix_;
             ResourceMonitor<LazyMatrix<DataType>>::registerInstance(this);
         }
         return *this;
     }
References MyBLAS::LazyMatrix< DataType >::cols_, MyBLAS::LazyMatrix< DataType >::generator_, MyBLAS::LazyMatrix< DataType >::matrix_, and MyBLAS::LazyMatrix< DataType >::rows_.
operator[]() [1/2]
template<typename DataType > Proxy MyBLAS::LazyMatrix< DataType >::operator[] (size_t row) inline
Overload of the [] operator for non-const access to a row of the LazyMatrix.
Parameters
row The index of the row to access.
Returns
A Proxy object representing the row at the given index.
{
         return Proxy(*this, row);
     }
References process::row.
operator[]() [2/2]
template<typename DataType > ConstProxy MyBLAS::LazyMatrix< DataType >::operator[] (size_t row) const inline
Overload of the [] operator for const access to a row of the LazyMatrix.
Parameters
row The index of the row to access.
Returns
A ConstProxy object representing the row at the given index.
{
         return ConstProxy(*this, row);
     }
References process::row.
setCols()
template<typename DataType > void MyBLAS::LazyMatrix< DataType >::setCols (size_t cols) inline protected
Setter for the number of columns in the LazyMatrix.
Parameters
cols The new number of columns.
 { cols_ = cols; }
References MyBLAS::LazyMatrix< DataType >::cols_.
setGenerator()
template<typename DataType > void MyBLAS::LazyMatrix< DataType >::setGenerator (const Generator & generator) inline protected
Setter for the generator function of the LazyMatrix.
Parameters
generator The new generator function.
 { generator_ = generator; }
References MyBLAS::LazyMatrix< DataType >::generator_.
setRows()
template<typename DataType > void MyBLAS::LazyMatrix< DataType >::setRows (size_t rows) inline protected
Setter for the number of rows in the LazyMatrix.
Parameters
rows The new number of rows.
 { rows_ = rows; }
References MyBLAS::LazyMatrix< DataType >::rows_.
Friends And Related Function Documentation
allElementsEqual
template<typename DataType > bool allElementsEqual (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Function to compare two LazyMatrix objects for equality.
This function checks if all elements in the two input matrices are equal.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A boolean value indicating whether all elements in the two input matrices are equal.
{
         if (a.getRows() != b.getRows() || a.getCols() != b.getCols()) {
             return false;
         }
         auto eq = equal(a, b);
         for (size_t i = 0; i < eq.getRows(); ++i) {
             for (size_t j = 0; j < eq.getCols(); ++j) {
                 if (!eq(i, j)) {
                     return false;
                 }
             }
         }
         return true;
     }
equal
template<typename DataType > LazyMatrix<bool> equal (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Function to compare two LazyMatrix objects for element-wise equality.
This function generates a new LazyMatrix of boolean values, where each element represents the equality of the corresponding elements in the input matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix of boolean values, where each element represents the equality of the corresponding elements in the input matrices.
{
         auto binary_op = [](DataType const& x, DataType const& y) { return x == y; };
         ElementwiseExpression<bool, LazyMatrix, LazyMatrix, decltype(binary_op)> expr(a, b, binary_op);
         return LazyMatrix<bool>(a.getRows(), a.getCols(), [expr](size_t i, size_t j) { return expr(i, j); });
     }
operator!= [1/3]
template<typename DataType > LazyMatrix operator!= (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the inequality operator for comparing two LazyMatrix objects.
This function performs element-wise comparison between two LazyMatrix objects.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return x != y; };
         return ElementwiseExpression<DataType, LazyMatrix, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator!= [2/3]
template<typename DataType > LazyMatrix operator!= (LazyMatrix< DataType > const & a, MyBLAS::Matrix< DataType > const & b) friend
Overload of the inequality operator for comparing a LazyMatrix and a MyBLAS::Matrix.
This function performs element-wise comparison between a LazyMatrix and a MyBLAS::Matrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Matrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return y != x; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(b, a, op);
     }
operator!= [3/3]
template<typename DataType > LazyMatrix operator!= (MyBLAS::Matrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the inequality operator for comparing a MyBLAS::Matrix and a LazyMatrix.
This function performs element-wise comparison between a MyBLAS::Matrix and a LazyMatrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the MyBLAS::Matrix.
b A constant reference to the LazyMatrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return x != y; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator* [1/5]
template<typename DataType > LazyMatrix operator* (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the multiplication operator for multiplying two LazyMatrix objects.
This function performs matrix-matrix multiplication between two LazyMatrix objects.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix that represents the result of the multiplication.
{
         return ContainerExpression<LazyMatrix, LazyMatrix, DataType>::multiplyMatrixMatrixType2(a, b);
     }
operator* [2/5]
template<typename DataType > LazyVector<DataType> operator* (LazyMatrix< DataType > const & a, LazyVector< DataType > const & b) friend
Overload of the multiplication operator for multiplying a LazyMatrix and a LazyVector.
This function performs matrix-vector multiplication between a LazyMatrix and a LazyVector.
Template Parameters
DataType The type of data contained in the matrix and the vector.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the LazyVector.
Returns
A LazyVector that represents the result of the multiplication.
{
         return MatrixVectorExpression<LazyMatrix, LazyVector, DataType>::multiplyMatrixVector(a, b);
     }
operator* [3/5]
template<typename DataType > LazyMatrix operator* (LazyMatrix< DataType > const & a, MyBLAS::Matrix< DataType > const & b) friend
Overload of the multiplication operator for multiplying a LazyMatrix and a MyBLAS::Matrix.
This function performs matrix-matrix multiplication between a LazyMatrix and a MyBLAS::Matrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Matrix.
Returns
A LazyMatrix that represents the result of the multiplication.
{
         return ContainerExpression<LazyMatrix, MyBLAS::Matrix, DataType>::multiplyMatrixMatrixType1(a, b);
     }
operator* [4/5]
template<typename DataType > MyBLAS::Vector<DataType> operator* (LazyMatrix< DataType > const & a, MyBLAS::Vector< DataType > const & b) friend
Overload of the multiplication operator for multiplying a LazyMatrix and a MyBLAS::Vector.
This function performs matrix-vector multiplication between a LazyMatrix and a MyBLAS::Vector.
Template Parameters
DataType The type of data contained in the matrix and the vector.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Vector.
Returns
A MyBLAS::Vector that represents the result of the multiplication.
{
         return MatrixVectorExpression<LazyMatrix, MyBLAS::Vector, DataType>::multiplyMatrixVector(a, b);
     }
operator* [5/5]
template<typename DataType > LazyMatrix operator* (MyBLAS::Matrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the multiplication operator for multiplying a MyBLAS::Matrix and a LazyMatrix.
This function performs matrix-matrix multiplication between a MyBLAS::Matrix and a LazyMatrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the MyBLAS::Matrix.
b A constant reference to the LazyMatrix.
Returns
A LazyMatrix that represents the result of the multiplication.
{
         return ContainerExpression<MyBLAS::Matrix, LazyMatrix, DataType>::multiplyMatrixMatrixType2(a, b);
     }
operator+ [1/3]
template<typename DataType > LazyMatrix operator+ (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the addition operator for adding two LazyMatrix objects.
This function performs element-wise addition between two LazyMatrix objects.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix that represents the result of the addition.
{
         auto op = [](DataType const& x, DataType const& y) { return x + y; };
         return ElementwiseExpression<DataType, LazyMatrix, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator+ [2/3]
template<typename DataType > LazyMatrix operator+ (LazyMatrix< DataType > const & a, MyBLAS::Matrix< DataType > const & b) friend
Overload of the addition operator for adding a LazyMatrix and a MyBLAS::Matrix.
This function performs element-wise addition between a LazyMatrix and a MyBLAS::Matrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Matrix.
Returns
A LazyMatrix that represents the result of the addition.
{
         auto op = [](DataType const& x, DataType const& y) { return y + x; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(b, a, op);
     }
operator+ [3/3]
template<typename DataType > LazyMatrix operator+ (MyBLAS::Matrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the addition operator for adding a MyBLAS::Matrix and a LazyMatrix.
This function performs element-wise addition between a MyBLAS::Matrix and a LazyMatrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the MyBLAS::Matrix.
b A constant reference to the LazyMatrix.
Returns
A LazyMatrix that represents the result of the addition.
{
         auto op = [](DataType const& x, DataType const& y) { return x + y; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator- [1/3]
template<typename DataType > LazyMatrix operator- (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the subtraction operator for subtracting one LazyMatrix from another.
This function performs element-wise subtraction between two LazyMatrix objects.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix that represents the result of the subtraction.
{
         auto op = [](DataType const& x, DataType const& y) { return x - y; };
         return ElementwiseExpression<DataType, LazyMatrix, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator- [2/3]
template<typename DataType > LazyMatrix operator- (LazyMatrix< DataType > const & a, MyBLAS::Matrix< DataType > const & b) friend
Overload of the subtraction operator for subtracting a MyBLAS::Matrix from a LazyMatrix.
This function performs element-wise subtraction between a LazyMatrix and a MyBLAS::Matrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Matrix.
Returns
A LazyMatrix that represents the result of the subtraction.
{
         auto op = [](DataType const& x, DataType const& y) { return y - x; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(b, a, op);
     }
operator- [3/3]
template<typename DataType > LazyMatrix operator- (MyBLAS::Matrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the subtraction operator for subtracting a LazyMatrix from a MyBLAS::Matrix.
This function performs element-wise subtraction between a MyBLAS::Matrix and a LazyMatrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the MyBLAS::Matrix.
b A constant reference to the LazyMatrix.
Returns
A LazyMatrix that represents the result of the subtraction.
{
         auto op = [](DataType const& x, DataType const& y) { return x - y; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator== [1/3]
template<typename DataType > LazyMatrix operator== (LazyMatrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the equality operator for comparing two LazyMatrix objects.
This function performs element-wise comparison between two LazyMatrix objects.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the first LazyMatrix.
b A constant reference to the second LazyMatrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return x == y; };
         return ElementwiseExpression<DataType, LazyMatrix, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
operator== [2/3]
template<typename DataType > LazyMatrix operator== (LazyMatrix< DataType > const & a, MyBLAS::Matrix< DataType > const & b) friend
Overload of the equality operator for comparing a LazyMatrix and a MyBLAS::Matrix.
This function performs element-wise comparison between a LazyMatrix and a MyBLAS::Matrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the LazyMatrix.
b A constant reference to the MyBLAS::Matrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return y == x; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(b, a, op);
     }
operator== [3/3]
template<typename DataType > LazyMatrix operator== (MyBLAS::Matrix< DataType > const & a, LazyMatrix< DataType > const & b) friend
Overload of the equality operator for comparing a MyBLAS::Matrix and a LazyMatrix.
This function performs element-wise comparison between a MyBLAS::Matrix and a LazyMatrix.
Template Parameters
DataType The type of data contained in the matrices.
Parameters
a A constant reference to the MyBLAS::Matrix.
b A constant reference to the LazyMatrix.
Returns
A LazyMatrix that represents the result of the comparison.
{
         auto op = [](DataType const& x, DataType const& y) { return x == y; };
         return ElementwiseExpression<DataType, MyBLAS::Matrix<DataType>, LazyMatrix, decltype(op)>::matrix(a, b, op);
     }
Field Documentation
cols_
template<typename DataType > size_t MyBLAS::LazyMatrix< DataType >::cols_ {} private
The number of columns in the LazyMatrix.
Referenced by MyBLAS::LazyMatrix< DataType >::asColumnVector(), MyBLAS::LazyMatrix< DataType >::asRowVector(), MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::operator=(), and MyBLAS::LazyMatrix< DataType >::setCols().
generator_
template<typename DataType > Generator MyBLAS::LazyMatrix< DataType >::generator_ private
The generator function that computes the values of the LazyMatrix.
Referenced by MyBLAS::LazyMatrix< DataType >::LazyMatrix(), MyBLAS::LazyMatrix< DataType >::operator()(), MyBLAS::LazyMatrix< DataType >::operator*=(), MyBLAS::LazyMatrix< DataType >::operator+=(), MyBLAS::LazyMatrix< DataType >::operator-=(), MyBLAS::LazyMatrix< DataType >::operator/=(), MyBLAS::LazyMatrix< DataType >::operator=(), and MyBLAS::LazyMatrix< DataType >::setGenerator().
matrix_
template<typename DataType > std::shared_ptr<MyBLAS::Matrix<DataType> > MyBLAS::LazyMatrix< DataType >::matrix_ private
A shared pointer to the memory backed matrix.
Referenced by MyBLAS::LazyMatrix< DataType >::operator=().
rows_
template<typename DataType > size_t MyBLAS::LazyMatrix< DataType >::rows_ {} private
The number of rows in the LazyMatrix.
Referenced by MyBLAS::LazyMatrix< DataType >::asColumnVector(), MyBLAS::LazyMatrix< DataType >::asRowVector(), MyBLAS::LazyMatrix< DataType >::getRows(), MyBLAS::LazyMatrix< DataType >::operator=(), and MyBLAS::LazyMatrix< DataType >::setRows().
The documentation for this class was generated from the following file:
src/utils/math/blas/matrix/LazyMatrix.h