NE591-008 C++17 Codebase: InLab3 Class Reference
InLab3 Class Reference
A class for performing numerical integration using Composite Newton-Cotes Formulas.
#include <inlab3.h>
Public Member Functions
InLab3 (CommandLineArgs args)
Constructor for the InLab3 class.
void execute ()
Executes the project.
Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
Builds the header information for the project.
void run (Dictionary &outputs, NewtonCotesInputs &inputs, boost::program_options::variables_map &values) override
Runs the numerical integration using Composite Newton-Cotes Formulas.
virtual void preRun (Dictionary &output, NewtonCotesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (Dictionary &output, NewtonCotesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
Private Member Functions
void initialize ()
Initializes the project.
void timedRun ()
Executes the project and measures the execution time.
Private Attributes
CommandLineArgs cmdArgs
Parser terminal
Dictionary outputs
Detailed Description
A class for performing numerical integration using Composite Newton-Cotes Formulas.
This class is derived from the Project class and implements the numerical integration using Composite Newton-Cotes Formulas. It takes command line arguments, parses the inputs, performs the integration, and outputs the results.
Constructor & Destructor Documentation
InLab3()
InLab3::InLab3 (CommandLineArgs args) inline explicit
Constructor for the InLab3 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab3::buildHeaderInfo () inline override protected virtual
Builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< NewtonCotesInputs, Parser, Dictionary >.
{
         return {
                 .ProjectName = "InLab 03",
                 .ProjectDescription = "Numerical Integration using Composite Newton-Cotes Formulas",
                 .SubmissionDate = "09/08/2023",
                 .StudentName = "Arjun Earthperson",
                 .HeaderArt = R"(
                     .                                            .
          *   .                  .              .        .   *          .
       .         .                     .       .           .      .        .
             o                             .                   .
              .              .                  .           .
               0     .
                      .          .                 ,                ,    ,
      .          \          .                         .
           .      \   ,
        .          o     .                 .                   .            .
          .         \                 ,             .                .
                    #\##\#      .                              .        .
                  #  #O##\###                .                        .
        .        #*#  #\##\###                       .                     ,
             .   ##*#  #\##\##               .                     .
           .      ##*#  #o##\#         .                             ,       .
               .     *#  #\#     .                    .             .          ,
                           \          .                         .
     ____^/\___^--____/\____O______________/\/\---/\___________---______________
        /\^   ^  ^    ^                  ^^ ^  '\ ^          ^       ---
              --           -            --  -      -         ---  __       ^
        --  __                      ___--  ^  ^                         --  __
 )",
         };
     }
References HeaderInfo::ProjectName.
execute()
void Project< NewtonCotesInputs , Parser , Dictionary >::execute () inline inherited
Executes the project.
                    {
         initialize();
         timedRun();
     }
getTerminal()
Parser Project< NewtonCotesInputs , Parser , Dictionary >::getTerminal () const inline inherited
Returns the terminal.
Returns
The terminal.
{
         return terminal;
     }
initialize()
void Project< NewtonCotesInputs , Parser , Dictionary >::initialize () inline private inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::postRun (Dictionary & output, NewtonCotesInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::preRun (Dictionary & output, NewtonCotesInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void InLab3::run (Dictionary & outputs, NewtonCotesInputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
Runs the numerical integration using Composite Newton-Cotes Formulas.
Parameters
outputs Dictionary object to store the outputs
inputs NewtonCotesInputs object containing the parsed inputs
values Boost program_options variables_map containing command line arguments
Implements Project< NewtonCotesInputs, Parser, Dictionary >.
{
         // declare the JSON object and file
         nlohmann::json JSONFile;
         // write the inputs to file
         nlohmann::json inputsJSON;
         inputs.toJSON(inputsJSON);
         JSONFile["inputs"] = inputsJSON;
         nlohmann::json outputsJSON;
         std::vector<NewtonCotesOutputs> computeOutputs;
         const auto precision = values["precision"].as<int>();
         std::cout<<std::setw(40)<<"Outputs\n";
         Parser::printLine();
         if (inputs.integral_types.count(RULE_COMPOSITE_TRAPEZOIDAL)) {
             NewtonCotesOutputs output1;
             fillUsingTrapezoidal(output1, inputs);
             computeOutputs.push_back(output1);
             nlohmann::json json1;
             output1.toJSON(json1);
             outputsJSON[ruleKey(RULE_COMPOSITE_TRAPEZOIDAL)] = json1;
             std::cout << "Integral over [a,b] using trapezoidal rule: "<<std::setprecision(precision)<<output1.integral<<std::endl;
             Parser::printLine();
         }
         if (inputs.integral_types.count(RULE_COMPOSITE_SIMPSONS)) {
             NewtonCotesOutputs output2;
             fillUsingSimpsons(output2, inputs);
             computeOutputs.push_back(output2);
             nlohmann::json json2;
             output2.toJSON(json2);
             outputsJSON[ruleKey(RULE_COMPOSITE_SIMPSONS)] = json2;
             std::cout << "Integral over [a,b] using Simpson's rule:   "<<std::setprecision(precision)<<output2.integral<<std::endl;
             Parser::printLine();
         }
         if (inputs.integral_types.count(RULE_GAUSSIAN_QUADRATURE)) {
             NewtonCotesOutputs output3;
             fillUsingGaussianQuadratures(output3, inputs);
             computeOutputs.push_back(output3);
             //nlohmann::json json3;
             //output3.toJSON(json3);
             //outputsJSON[ruleKey(RULE_GAUSSIAN_QUADRATURE)] = json3;
             Parser::printLine();
         }
         // create the outputs object
         JSONFile["outputs"] = outputsJSON;
         writeJSON(values["output-json"].as<std::string>(), JSONFile);
     }
References fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), Output::integral, Input::integral_types, CommandLine< InLab6Inputs >::printLine(), RULE_COMPOSITE_SIMPSONS, RULE_COMPOSITE_TRAPEZOIDAL, RULE_GAUSSIAN_QUADRATURE, ruleKey(), Input::toJSON(), Output::toJSON(), and writeJSON().
timedRun()
void Project< NewtonCotesInputs , Parser , Dictionary >::timedRun () inline private inherited
Executes the project and measures the execution time.
                     {
         run(outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
cmdArgs
CommandLineArgs Project< NewtonCotesInputs , Parser , Dictionary >::cmdArgs private inherited
outputs
Dictionary Project< NewtonCotesInputs , Parser , Dictionary >::outputs private inherited
terminal
Parser Project< NewtonCotesInputs , Parser , Dictionary >::terminal private inherited
The documentation for this class was generated from the following file:
src/labs/inlab3/inlab3.h