NE591-008 C++17 Codebase: src/labs/inlab1/Compute.h File Reference
Compute.h File Reference
Compute methods for inlab1 in NE591-008.
#include <cmath>
#include <iostream>
#include "CommandLine.h"
Data Structures
struct Factorial
Struct to hold factorial data.
struct Output
Struct to hold variables for Taylor Series.
Typedefs
typedef struct Output TaylorSeriesVariables
Struct to hold variables for Taylor Series.
Functions
long double naive_factorial (const size_t N)
Function to compute factorial in a naive way.
long double my_sisd_sin (TaylorSeriesVariables &vars)
Function to compute sine using a recursive, iterative taylor series discretization approach.
long double my_naive_sin (const long double x, long double prev_threshold, long double target_threshold, long double sum, size_t n, size_t N)
Function to compute sine in a naive way.
long double my_sin (const long double angle, const size_t iterations, const long double convergence_threshold)
Function to compute sine.
Variables
static TaylorSeriesVariables mySineVars {}
Detailed Description
Compute methods for inlab1 in NE591-008.
Author
Arjun Earthperson
Date
08/30/2023
Definition in file Compute.h.
Data Structure Documentation
Factorial
struct Factorial
Struct to hold factorial data.
Data Fields
size_t n
long double value
Typedef Documentation
TaylorSeriesVariables
typedef struct Output TaylorSeriesVariables
Struct to hold variables for Taylor Series.
Function Documentation
my_naive_sin()
long double my_naive_sin (const long double x, long double prev_threshold, long double target_threshold, long double sum, size_t n, size_t N)
Function to compute sine in a naive way.
Parameters
x The angle in radians.
prev_threshold The previous threshold.
target_threshold The target threshold.
sum The running sum.
n The current iteration.
N The maximum number of iterations.
Returns
The computed sine value.
{
     // terminate since we are over the iteration limit
     if (n > N) {
         return sum;
     }
     // terminate since we have converged
     if (prev_threshold <= target_threshold) {
         return sum;
     }
     // n<=N && (ce > e)
     const long double direction = ((n % 2) == 0) ? 1.0f : -1.0f;   // positive if n is even, negative if n is odd.
     const auto two_n_plus_1 = static_cast<long double>(2 * n + 1); // (2n+1)
     const long double x_power_two_n_plus_1 = pow(x, two_n_plus_1); // x^(2n+1)
     const long double current_factorial = naive_factorial(static_cast<size_t>(two_n_plus_1)); // (2n+1) * prev_factorial
     const long double current_threshold = x_power_two_n_plus_1 / current_factorial;
     const long double accumulated = sum + direction * current_threshold;
     return my_naive_sin(x, current_threshold, target_threshold, accumulated, ++n, N);
 }
References n, naive_factorial(), MyBLAS::Stats::sum(), and x.
my_sin()
long double my_sin (const long double angle, const size_t iterations, const long double convergence_threshold)
Function to compute sine.
Parameters
angle The angle in radians.
iterations The maximum number of iterations.
convergence_threshold The convergence threshold.
Returns
The computed sine value.
{
     mySineVars.running_sum = 0.0f;
     mySineVars.previous_factorial = 1.0f;
     mySineVars.current_threshold = INFINITY;
     mySineVars.target_threshold = convergence_threshold;
     mySineVars.x = angle;
     mySineVars.n = 0;
     mySineVars.N = iterations;
     return my_sisd_sin(mySineVars);
     //    return my_naive_sin(mySineVars.x, mySineVars.current_threshold, mySineVars.target_threshold,
     //    mySineVars.running_sum, mySineVars.n, mySineVars.N);
 }
References Output::current_threshold, my_sisd_sin(), mySineVars, Output::n, Output::N, Output::previous_factorial, Output::running_sum, Output::target_threshold, and Output::x.
Referenced by InLab1::run().
my_sisd_sin()
long double my_sisd_sin (TaylorSeriesVariables & vars)
Function to compute sine using a recursive, iterative taylor series discretization approach.
Parameters
vars The variables for Taylor Series.
Returns
The computed sine value.
{
     // terminate since we are over the iteration limit
     if (vars.n > vars.N) {
         return vars.running_sum;
     }
     // terminate since we have converged
     if (abs(vars.current_threshold) <= vars.target_threshold) {
         return vars.running_sum;
     }
     // n<=N && (ce > e)
     const long double direction = ((vars.n % 2) == 0) ? 1.0f : -1.0f;   // positive if n is even, negative if n is odd.
     const auto two_n_plus_1 = static_cast<long double>(2 * vars.n + 1); // (2n+1)
     const long double x_power_two_n_plus_1 = pow(vars.x, two_n_plus_1); // x^(2n+1)
     const long double current_factorial = naive_factorial(static_cast<size_t>(two_n_plus_1)); // (2n+1) * prev_factorial
     const long double current_threshold = x_power_two_n_plus_1 / current_factorial;
     const long double accumulated = vars.running_sum + direction * current_threshold;
     vars.current_threshold = current_threshold;
     vars.running_sum = accumulated;
     (vars.n)++;
     return my_sisd_sin(vars);
 }
References MyBLAS::Stats::abs(), Output::current_threshold, Output::n, Output::N, naive_factorial(), Output::running_sum, Output::target_threshold, and Output::x.
Referenced by my_sin().
naive_factorial()
long double naive_factorial (const size_t N)
Function to compute factorial in a naive way.
Parameters
N The number to compute factorial of.
Returns
The computed factorial.
{
     long double accumulator = 1.0f;
     for (auto n = N; n >= 1; n--) {
         accumulator *= static_cast<long double>(n);
     }
     return accumulator;
 }
References n.
Referenced by my_naive_sin(), and my_sisd_sin().
Variable Documentation
mySineVars
TaylorSeriesVariables mySineVars {} static
Referenced by my_sin(), and InLab1::run().