NE591-008 C++17 Codebase: MatrixVectorExpression< MatrixType, VectorType, T > Class Template Reference
MatrixVectorExpression< MatrixType, VectorType, T > Class Template Reference
Represents an expression for the element-wise multiplication of a matrix and a vector.
#include <MatrixVectorExpression.h>
Public Member Functions
MatrixVectorExpression (const MatrixType< T > &matrix, const VectorType< T > &vector)
Constructs a MatrixVectorExpression with a matrix and a vector.
T operator() (size_t i) const
Computes the element-wise multiplication of the matrix and vector for a specific row.
Static Public Member Functions
static VectorType< T > multiplyMatrixVector (const MatrixType< T > &a, const VectorType< T > &b)
Performs element-wise matrix-vector multiplication.
Private Attributes
const MatrixType< T > & matrix_
The matrix for element-wise multiplication.
const VectorType< T > & vector_
The vector for element-wise multiplication.
Detailed Description
template<template< typename > class MatrixType, template< typename > class VectorType, typename T>
class MatrixVectorExpression< MatrixType, VectorType, T >
Represents an expression for the element-wise multiplication of a matrix and a vector.
This class defines an expression for the element-wise multiplication of a matrix and a vector. It can be used to perform element-wise multiplication without explicitly creating a new matrix.
Template Parameters
MatrixType The template class representing the matrix type.
VectorType The template class representing the vector type.
T The data type of the elements.
Constructor & Destructor Documentation
MatrixVectorExpression()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MatrixVectorExpression< MatrixType, VectorType, T >::MatrixVectorExpression (const MatrixType< T > & matrix, const VectorType< T > & vector) inline
Constructs a MatrixVectorExpression with a matrix and a vector.
Parameters
matrix The matrix for the element-wise multiplication.
vector The vector for the element-wise multiplication.
         : matrix_(matrix), vector_(vector) {}
Member Function Documentation
multiplyMatrixVector()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > static VectorType<T> MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector (const MatrixType< T > & a, const VectorType< T > & b) inline static
Performs element-wise matrix-vector multiplication.
Parameters
a The matrix for multiplication.
b The vector for multiplication.
Returns
A VectorType containing the result of the element-wise multiplication.
{
         MatrixVectorExpression expr(a, b);
         VectorType result = VectorType<T>(a.getRows(), [expr](size_t i) { return expr(i); });
         return result;
     }
References MyBLAS::Matrix< T >::getRows(), and i.
Referenced by Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingSOR(), Compute::usingSymmetricGaussSeidel(), and Compute::usingSymmetricSOR().
operator()()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > T MatrixVectorExpression< MatrixType, VectorType, T >::operator() (size_t i) const inline
Computes the element-wise multiplication of the matrix and vector for a specific row.
Parameters
i The index of the row to compute the result for.
Returns
The result of element-wise multiplication for the given row.
{
         T result = 0;
         for (size_t j = 0; j < matrix_.getCols(); ++j) {
             result += matrix_(i, j) * vector_[j];
         }
         return result;
     }
References i, MatrixVectorExpression< MatrixType, VectorType, T >::matrix_, and MatrixVectorExpression< MatrixType, VectorType, T >::vector_.
Field Documentation
matrix_
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > const MatrixType<T>& MatrixVectorExpression< MatrixType, VectorType, T >::matrix_ private
The matrix for element-wise multiplication.
Referenced by MatrixVectorExpression< MatrixType, VectorType, T >::operator()().
vector_
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > const VectorType<T>& MatrixVectorExpression< MatrixType, VectorType, T >::vector_ private
The vector for element-wise multiplication.
Referenced by MatrixVectorExpression< MatrixType, VectorType, T >::operator()().
The documentation for this class was generated from the following file:
src/utils/math/blas/vector/MatrixVectorExpression.h