NE591-008 C++17 Codebase: MyBLAS::Stats Namespace Reference
MyBLAS::Stats Namespace Reference
A namespace for statistical functions and structures.
Data Structures
struct Summary
A structure to hold the summary statistics of a vector or matrix.
Functions
template<typename T >
T min (const Vector< T > &v)
Function to find the minimum value in a vector.
template<typename T >
T max (const Vector< T > &v)
Function to find the maximum value in a vector.
template<typename T >
Vector< T > abs (const Vector< T > &a)
Function to find the absolute value of each element in a vector.
template<typename T >
Matrix< T > abs (const Matrix< T > &a)
Function to find the absolute value of each element in a matrix.
template<typename T >
T sum (const MyBLAS::Vector< T > &v)
Function to find the sum of all elements in a vector.
template<typename T >
T mean (const MyBLAS::Vector< T > &v)
Function to find the mean value of a vector.
template<typename T >
T variance (const MyBLAS::Vector< T > &v)
Function to find the variance of a vector.
template<typename T >
T std (const MyBLAS::Vector< T > &v)
Function to find the standard deviation of a vector.
template<typename T >
T percentile (Vector< T > v, long double p)
Function to find the p-th percentile of a vector.
template<typename T >
T median (Vector< T > v)
Function to find the median of a vector.
Detailed Description
A namespace for statistical functions and structures.
Function Documentation
abs() [1/2]
template<typename T > Matrix<T> MyBLAS::Stats::abs (const Matrix< T > & a)
Function to find the absolute value of each element in a matrix.
Template Parameters
T The type of the elements in the matrix.
Parameters
a The matrix.
Returns
A matrix with the absolute value of each element.
{
     Matrix<T> result(a.getRows(), a.getCols(), 0);
     for (size_t i = 0; i < a.getRows(); ++i) {
         for (size_t j = 0; j < a.getCols(); ++j) {
             result[i][j] = fabsl(a[i][j]);
         }
     }
     return result;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
abs() [2/2]
template<typename T > Vector<T> MyBLAS::Stats::abs (const Vector< T > & a)
Function to find the absolute value of each element in a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
a The vector.
Returns
A vector with the absolute value of each element.
{
     Vector<T> result(a.size(), 0);
     for (size_t i = 0; i < a.size(); ++i) {
         result[i] = fabsl(a[i]);
     }
     return result;
 }
References i, and MyBLAS::Vector< T >::size().
Referenced by Output::getMaxResidual(), MyBLAS::Solver::Solution< T >::getMaxResidual(), Output::max_residual(), OutLab4::run(), OutLab5::run(), Project1::run(), and Output::toJSON().
max()
template<typename T > T MyBLAS::Stats::max (const Vector< T > & v)
Function to find the maximum value in a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The maximum value.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     auto data = v.getData();
     if (data.empty()) {
         return std::numeric_limits<T>::quiet_NaN();
     }
     return *std::max_element(data.begin(), data.end());
 }
References data, and MyBLAS::Vector< T >::getData().
Referenced by MyBLAS::AbsoluteMaxResidual(), absoluteValueFailsGreaterThan1Check(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), failsExclusiveRangeCheck(), failsInclusiveRangeCheck(), Random::generate_lazy_vector(), Random::generate_matrix(), Random::generate_one(), Random::generate_vector(), getGrays256bitANSI(), printJuliaSet(), Profiler< FunctionType >::summarize(), MyBLAS::TEST_F(), and MyBLAS::TYPED_TEST().
mean()
template<typename T > T MyBLAS::Stats::mean (const MyBLAS::Vector< T > & v)
Function to find the mean value of a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The mean value.
{
     return MyBLAS::Stats::sum(v) / static_cast<T>(v.getData().size());
 }
References MyBLAS::Vector< T >::getData(), and sum().
Referenced by Profiler< FunctionType >::summarize(), and variance().
median()
template<typename T > T MyBLAS::Stats::median (Vector< T > v)
Function to find the median of a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The median.
                       {
     return percentile(v, 50);
 }
References percentile().
Referenced by Profiler< FunctionType >::summarize().
min()
template<typename T > T MyBLAS::Stats::min (const Vector< T > & v)
Function to find the minimum value in a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The minimum value.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     auto data = v.getData();
     if (data.empty()) {
         return NAN;
     }
     return *std::min_element(data.begin(), data.end());
 }
References data, and MyBLAS::Vector< T >::getData().
Referenced by MyBLAS::AbsoluteMaxResidual(), failsExclusiveRangeCheck(), failsInclusiveRangeCheck(), failsNaturalNumberCheck(), failsWholeNumberCheck(), fillLagrangePolys(), Random::generate_lazy_vector(), Random::generate_matrix(), Random::generate_one(), Random::generate_vector(), getGrays256bitANSI(), getLagrangePoly(), MyBLAS::L2(), printJuliaSet(), Profiler< FunctionType >::summarize(), MyBLAS::TEST_F(), and MyBLAS::TYPED_TEST().
percentile()
template<typename T > T MyBLAS::Stats::percentile (Vector< T > v, long double p)
Function to find the p-th percentile of a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
p The percentile to find.
Returns
The p-th percentile.
{
     auto data = v.getData();
     if (p < 0 || p > 100) {
         throw std::invalid_argument("Percentile must be between 0 and 100");
     }
     long double rank = (p / static_cast<long double>(100)) * (data.size() - static_cast<long double>(1));
     auto index = static_cast<size_t>(rank);
     long double fractional = rank - index;
     if (data.size() == 1) {
         return data[0];
     }
     std::nth_element(data.begin(), data.begin() + index, data.end());
     T val = data[index];
     if (fractional == 0 || index + 1 == data.size()) {
         return val;
     }
     std::nth_element(data.begin(), data.begin() + index + 1, data.end());
     return val + fractional * (data[index + 1] - val);
 }
References data, and MyBLAS::Vector< T >::getData().
Referenced by median(), and Profiler< FunctionType >::summarize().
std()
template<typename T > T MyBLAS::Stats::std (const MyBLAS::Vector< T > & v)
Function to find the standard deviation of a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The standard deviation.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     return std::sqrt(MyBLAS::Stats::variance(v));
 }
References variance().
Referenced by formatMeanStd(), and Profiler< FunctionType >::summarize().
sum()
template<typename T > T MyBLAS::Stats::sum (const MyBLAS::Vector< T > & v)
Function to find the sum of all elements in a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The sum of all elements.
{
     auto data = v.getData();
     return std::accumulate(data.begin(), data.end(), static_cast<T>(0));
 }
References data, and MyBLAS::Vector< T >::getData().
Referenced by MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), MyBLAS::backwardSubstitution(), MyBLAS::LU::doolittleFactorize(), MyBLAS::doolittleFactorizeLU(), fillUsingSimpsons(), MyBLAS::forwardSubstitution(), ResourceMonitor< T >::getMaxBytesEver(), MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), mean(), my_naive_sin(), MyBLAS::norm(), InLab10::run(), Project1::run(), Profiler< FunctionType >::summarize(), and variance().
variance()
template<typename T > T MyBLAS::Stats::variance (const MyBLAS::Vector< T > & v)
Function to find the variance of a vector.
Template Parameters
T The type of the elements in the vector.
Parameters
v The vector.
Returns
The variance.
{
     T m = MyBLAS::Stats::mean(v);
     T sum = static_cast<T>(0);
     auto data = v.getData();
     std::for_each(data.begin(), data.end(), [&](long double x) { sum += (x - m) * (x - m); });
     return sum / data.size();
 }
References data, MyBLAS::Vector< T >::getData(), m, mean(), sum(), and x.
Referenced by std(), and Profiler< FunctionType >::summarize().