NE591-008 C++17 Codebase: InLab2 Class Reference
InLab2 Class Reference
#include <inlab2.h>
Public Member Functions
InLab2 (CommandLineArgs args)
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
LagrangePolynomialInputs & getInputs ()
Returns the input data.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
Builds the header information.
void run (Dictionary &output, Input &inputs, boost::program_options::variables_map &values) override
This function is responsible for the main logic of the program.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (Dictionary &output, LagrangePolynomialInputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (Dictionary &output, LagrangePolynomialInputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Holds the command line arguments.
Parser terminal
An instance of CommandLineParserType which is used to parse command line arguments.
Dictionary _outputs
Holds the output data of the project.
Detailed Description
Constructor & Destructor Documentation
InLab2()
InLab2::InLab2 (CommandLineArgs args) inline explicit
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab2::buildHeaderInfo () inline override protected virtual
Builds the header information.
Returns
The header information.
Implements Project< LagrangePolynomialInputs, Parser, Dictionary >.
{
         return {
             .ProjectName = "InLab 02",
             .ProjectDescription = "I/O Setup for Lagrange Interpolating Polynomials",
             .SubmissionDate = "09/01/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = R"(
          @\_______/@
         @|XXXXXXXX |
        @ |X||    X |
       @  |X||    X |
      @   |XXXXXXXX |
     @    |X||    X |             V
    @     |X||   .X |
   @      |X||.  .X |                      V
  @      |%XXXXXXXX%||
 @       |X||  . . X||
         |X||   .. X||                               @     @
         |X||  .   X||.                              ||====%
         |X|| .    X|| .                             ||    %
         |X||.     X||   .                           ||====%
        |XXXXXXXXXXXX||     .                        ||    %
        |XXXXXXXXXXXX||         .                 .  ||====% .
        |XX|        X||                .        .    ||    %  .
        |XX|        X||                   .          ||====%   .
        |XX|        X||              .          .    ||    %     .
        |XX|======= X||============================+ || .. %  ........
 ===== /            X||                              ||    %
                    X||           /)                 ||    %
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 )",
         };
     }
References HeaderInfo::ProjectName.
execute()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::finalize () inline protected virtual inherited
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
getInputs()
LagrangePolynomialInputs & Project< LagrangePolynomialInputs , Parser , Dictionary >::getInputs () inline inherited
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
getProfiler() [1/3]
auto Project< LagrangePolynomialInputs , Parser , Dictionary >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< LagrangePolynomialInputs , Parser , Dictionary >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< LagrangePolynomialInputs , Parser , Dictionary >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< LagrangePolynomialInputs , Parser , Dictionary >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
postRun()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::postRun (Dictionary & output, LagrangePolynomialInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::preRun (Dictionary & output, LagrangePolynomialInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void InLab2::run (Dictionary & output, Input & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function is responsible for the main logic of the program.
Parameters
values A map of variables parsed from the command line arguments.
The run() function creates an InputParams object and populates it with the appropriate values from the command line arguments.
After that, it creates an output map and populates it with the indices, uniform interval, Lagrange interpolated samples, and interpolation error samples.
If the "use-fx-function" command line argument is present, it also calculates the interpolation errors and adds them to the output map.
Finally, it writes the output map to a CSV file specified by the "output-csv" command line argument.
Reimplemented from Project< LagrangePolynomialInputs, Parser, Dictionary >.
{
         // create indices 1 -> m
         std::vector<size_t> indexVector(inputs.m);
         std::iota(indexVector.begin(), indexVector.end(), 1);
         output.emplace("i", asStringVector(indexVector));
         // uniform interval over [a,b]
         const auto xMinMax = std::minmax_element(inputs.xData.begin(), inputs.xData.end());
         auto uniformXiInterval = std::vector<long double>(inputs.m, 0);
         fill_linspace(uniformXiInterval, *xMinMax.first, *xMinMax.second, inputs.m);
         output.emplace("x(i)", asStringVector(uniformXiInterval));
         // Lagrange interpolated samples L[x(i)]
         auto lagrangePolynomials = std::vector<long double>(inputs.m, 0);
         fillLagrangePolys(lagrangePolynomials, uniformXiInterval, inputs.xData, inputs.fxData);
         output.emplace("L(x)", asStringVector(lagrangePolynomials));
         // Interpolation error samples E[L(x)-f(x)]
         if (values.count("use-fx-function")) {
             auto functionAtX = std::vector<long double>(inputs.m, 0);
             fillInterpolationError(functionAtX, lagrangePolynomials, inputs.fxData);
             output.emplace("f(x)", asStringVector(lagrangePolynomials));
             auto interpolationErrors = std::vector<long double>(inputs.m, 0);
             fillInterpolationError(interpolationErrors, lagrangePolynomials, inputs.fxData);
             output.emplace("E(x)", asStringVector(lagrangePolynomials));
         }
         writeCSV(values["output-csv"].as<std::string>(), output, {"i", "x(i)", "L(x)", "f(x)", "E(x)"});
     }
References asStringVector(), fill_linspace(), fillInterpolationError(), fillLagrangePolys(), process::inputs, and writeCSV().
timedRun()
virtual void Project< LagrangePolynomialInputs , Parser , Dictionary >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
_outputs
Dictionary Project< LagrangePolynomialInputs , Parser , Dictionary >::_outputs protected inherited
Holds the output data of the project.
cmdArgs
CommandLineArgs Project< LagrangePolynomialInputs , Parser , Dictionary >::cmdArgs protected inherited
Holds the command line arguments.
terminal
Parser Project< LagrangePolynomialInputs , Parser , Dictionary >::terminal protected inherited
An instance of CommandLineParserType which is used to parse command line arguments.
The documentation for this class was generated from the following file:
src/labs/inlab2/inlab2.h