NE591-008 C++17 Codebase: src/project/project1/tests/LUMatrixTests.cpp File Reference
LUMatrixTests.cpp File Reference
MISSING!
#include "math/blas/BLAS.h"
#include "math/factorization/LU.h"
#include <gtest/gtest.h>
Data Structures
class FactorizeValidLUMatrixTest
class FactorizeInvalidLUMatrixTest
Functions
TEST_P (FactorizeValidLUMatrixTest, FactorizesValidLowerMatrix)
TEST_P (FactorizeValidLUMatrixTest, FactorizesValidUpperMatrix)
INSTANTIATE_TEST_SUITE_P (InputValues, FactorizeValidLUMatrixTest, ::testing::Values(MyBLAS::Matrix< long double >{{1.0, 1.0, 2.0}, {2.0, 4.0, 7.0}, {3.0, 7.0, 15.0}}, MyBLAS::Matrix< long double >{ {2.0, 7.0, 1.0, 4.0}, {3.0, -2.0, 0.0, 3.0}, {1.0, 5.0, 3.0, 5.0}, {1.0, 2.0, 3.0, 2.0}, }, MyBLAS::Matrix< long double >{{2.0, 7.0, 1.0}, {3.0, -2.0, 0.0}, {1.0, 5.0, 3.0}}, MyBLAS::Matrix< long double >{ {1.0, 2.0, 3.0, 4.0}, {2.0, 3.0, 4.0, 1.0}, {3.0, 4.0, 1.0, 2.0}, {4.0, 1.0, 2.0, 3.0}}))
TEST_P (FactorizeInvalidLUMatrixTest, FactorizesInvalidLowerMatrix)
TEST_P (FactorizeInvalidLUMatrixTest, FactorizesInvalidUpperMatrix)
INSTANTIATE_TEST_SUITE_P (InputValues, FactorizeInvalidLUMatrixTest, ::testing::Values(MyBLAS::Matrix< long double >{{1.0, 2.0, 3.0, 4.0, 5.0}, {2.0, 3.0, 4.0, 5.0, 1.0}, {3.0, 4.0, 5.0, 1.0, 2.0}, {4.0, 5.0, 1.0, 2.0, 3.0}, {5.0, 1.0, 2.0, 3.0, 4.0}}, MyBLAS::Matrix< long double >{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, MyBLAS::Matrix< long double >{{1.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}))
Detailed Description
MISSING!
Definition in file LUMatrixTests.cpp.
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/2]
INSTANTIATE_TEST_SUITE_P (InputValues , FactorizeInvalidLUMatrixTest , ::testing::Values(MyBLAS::Matrix< long double >{{1.0, 2.0, 3.0, 4.0, 5.0}, {2.0, 3.0, 4.0, 5.0, 1.0}, {3.0, 4.0, 5.0, 1.0, 2.0}, {4.0, 5.0, 1.0, 2.0, 3.0}, {5.0, 1.0, 2.0, 3.0, 4.0}}, MyBLAS::Matrix< long double >{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, MyBLAS::Matrix< long double >{{1.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}))
INSTANTIATE_TEST_SUITE_P() [2/2]
INSTANTIATE_TEST_SUITE_P (InputValues , FactorizeValidLUMatrixTest , ::testing::Values(MyBLAS::Matrix< long double >{{1.0, 1.0, 2.0}, {2.0, 4.0, 7.0}, {3.0, 7.0, 15.0}}, MyBLAS::Matrix< long double >{ {2.0, 7.0, 1.0, 4.0}, {3.0, -2.0, 0.0, 3.0}, {1.0, 5.0, 3.0, 5.0}, {1.0, 2.0, 3.0, 2.0}, }, MyBLAS::Matrix< long double >{{2.0, 7.0, 1.0}, {3.0, -2.0, 0.0}, {1.0, 5.0, 3.0}}, MyBLAS::Matrix< long double >{ {1.0, 2.0, 3.0, 4.0}, {2.0, 3.0, 4.0, 1.0}, {3.0, 4.0, 1.0, 2.0}, {4.0, 1.0, 2.0, 3.0}}))
TEST_P() [1/4]
TEST_P (FactorizeInvalidLUMatrixTest , FactorizesInvalidLowerMatrix)
{
     MyBLAS::Matrix<long double> A, L, U;
     A = GetParam();
     L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     MyBLAS::LU::factorize<long double>(L, U, A);
     EXPECT_FALSE(MyBLAS::isUnitLowerTriangularMatrix(L)) << "L: " << std::endl << L << std::endl;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isUnitLowerTriangularMatrix(), and L().
TEST_P() [2/4]
TEST_P (FactorizeInvalidLUMatrixTest , FactorizesInvalidUpperMatrix)
{
     MyBLAS::Matrix<long double> A, L, U;
     A = GetParam();
     L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     MyBLAS::LU::factorize<long double>(L, U, A);
     EXPECT_FALSE(MyBLAS::isUpperTriangularMatrix(U)) << "U: " << std::endl << U << std::endl;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isUpperTriangularMatrix(), and L().
TEST_P() [3/4]
TEST_P (FactorizeValidLUMatrixTest , FactorizesValidLowerMatrix)
{
     MyBLAS::Matrix<long double> A, L, U;
     A = GetParam();
     L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     MyBLAS::LU::factorize<long double>(L, U, A);
     EXPECT_TRUE(MyBLAS::isUnitLowerTriangularMatrix(L)) << "L: " << std::endl << L << std::endl;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isUnitLowerTriangularMatrix(), and L().
TEST_P() [4/4]
TEST_P (FactorizeValidLUMatrixTest , FactorizesValidUpperMatrix)
{
     MyBLAS::Matrix<long double> A, L, U;
     A = GetParam();
     L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
     MyBLAS::LU::factorize<long double>(L, U, A);
     EXPECT_TRUE(MyBLAS::isUpperTriangularMatrix(U)) << "U: " << std::endl << U << std::endl;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isUpperTriangularMatrix(), and L().