NE591-008 C++17 Codebase: MPICommandLine< InputType > Class Template Reference
MPICommandLine< InputType > Class Template Reference abstract
#include <MPICommandLine.h>
Public Member Functions
MPICommandLine ()=default
MPICommandLine (const HeaderInfo &headerInfo, const CommandLineArgs &args)
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InputType & getInputs ()
Method to get the inputs.
Static Public Member Functions
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
Protected Member Functions
virtual void buildInputArguments (boost::program_options::options_description &inputArguments)=0
virtual void printInputArguments (boost::program_options::variables_map &values)=0
virtual void performInputArgumentsCheck (boost::program_options::variables_map &values)=0
virtual void buildInputs (InputType &ToFill, boost::program_options::variables_map &values)=0
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
Static Protected Member Functions
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
Protected Attributes
boost::program_options::variables_map variablesMap
bool initialized = false
CommandLineArgs cmdArgs
InputType inputs = InputType()
HeaderInfo header
Detailed Description
template<typename InputType>
class MPICommandLine< InputType >
Constructor & Destructor Documentation
MPICommandLine() [1/2]
template<typename InputType > MPICommandLine< InputType >::MPICommandLine () default
MPICommandLine() [2/2]
template<typename InputType > MPICommandLine< InputType >::MPICommandLine (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline
 : CommandLine<InputType>(headerInfo, args) {}
Member Function Documentation
buildGenerics()
template<typename InputType > static boost::program_options::options_description CommandLine< InputType >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
References ProfilerHelper::buildCommandlineOptions().
buildInputArguments()
template<typename InputType > virtual void CommandLine< InputType >::buildInputArguments (boost::program_options::options_description & inputArguments) protected pure virtual inherited
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
buildInputs()
template<typename InputType > virtual void CommandLine< InputType >::buildInputs (InputType & ToFill, boost::program_options::variables_map & values) protected pure virtual inherited
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
getArguments()
template<typename InputType > boost::program_options::variables_map& CommandLine< InputType >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
References CommandLine< InputType >::initialize(), CommandLine< InputType >::initialized, and CommandLine< InputType >::variablesMap.
getCmdArgs()
template<typename InputType > const CommandLineArgs& CommandLine< InputType >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
TODO:: DOCUMENT
 { return cmdArgs; }
References CommandLine< InputType >::cmdArgs.
getCurrentPrecision()
template<typename InputType > int CommandLine< InputType >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
References CommandLine< InputType >::variablesMap.
Referenced by InLab5::run(), OutLab4::run(), InLab4::run(), and OutLab5::run().
getInputs()
template<typename InputType > InputType& CommandLine< InputType >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return inputs;
     }
References CommandLine< InputType >::initialize(), CommandLine< InputType >::initialized, and CommandLine< InputType >::inputs.
initialize()
template<typename InputType > virtual void CommandLine< InputType >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
Referenced by CommandLine< InputType >::getArguments(), and CommandLine< InputType >::getInputs().
performInputArgumentsCheck()
template<typename InputType > virtual void CommandLine< InputType >::performInputArgumentsCheck (boost::program_options::variables_map & values) protected pure virtual inherited
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
printCompileConfigs()
template<typename InputType > static void CommandLine< InputType >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printHeader()
template<typename InputType > static void CommandLine< InputType >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
References HeaderInfo::HeaderArt, HeaderInfo::ProjectDescription, HeaderInfo::ProjectName, HeaderInfo::StudentName, and HeaderInfo::SubmissionDate.
printInputArguments()
template<typename InputType > virtual void CommandLine< InputType >::printInputArguments (boost::program_options::variables_map & values) protected pure virtual inherited
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
printLine()
template<typename InputType > static void CommandLine< InputType >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
Referenced by Parser::buildInputs(), and Parser::printInputArguments().
printPrecisionInformation()
template<typename InputType > void CommandLine< InputType >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
setPrecision()
template<typename InputType > void CommandLine< InputType >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
References replace(), and CommandLine< InputType >::variablesMap.
Field Documentation
cmdArgs
template<typename InputType > CommandLineArgs CommandLine< InputType >::cmdArgs protected inherited
Referenced by CommandLine< InputType >::CommandLine(), and CommandLine< InputType >::getCmdArgs().
header
template<typename InputType > HeaderInfo CommandLine< InputType >::header protected inherited
Referenced by CommandLine< InputType >::CommandLine().
initialized
template<typename InputType > bool CommandLine< InputType >::initialized = false protected inherited
Referenced by CommandLine< InputType >::CommandLine(), CommandLine< InputType >::getArguments(), and CommandLine< InputType >::getInputs().
inputs
template<typename InputType > InputType CommandLine< InputType >::inputs = InputType() protected inherited
Referenced by CommandLine< InputType >::getInputs().
variablesMap
template<typename InputType > boost::program_options::variables_map CommandLine< InputType >::variablesMap protected inherited
Referenced by CommandLine< InputType >::CommandLine(), CommandLine< InputType >::getArguments(), CommandLine< InputType >::getCurrentPrecision(), and CommandLine< InputType >::setPrecision().
The documentation for this class was generated from the following file:
src/utils/MPICommandLine.h