NE591-008 C++17 Codebase: InLab6 Class Reference
InLab6 Class Reference
This class is a child of the Project class.
#include <inlab6.h>
Public Member Functions
InLab6 (CommandLineArgs args)
Constructor for the outlab5 class.
void execute ()
Executes the project.
Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (InLab6Outputs &outputs, InLab6Inputs &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void preRun (InLab6Outputs &output, InLab6Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (InLab6Outputs &output, InLab6Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Static Protected Member Functions
static void printResults (InLab6Outputs &results)
This function prints the results of the computation.
Private Member Functions
void initialize ()
Initializes the project.
void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
Private Attributes
CommandLineArgs cmdArgs
Parser terminal
InLab6Outputs outputs
Detailed Description
This class is a child of the Project class.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
InLab6()
InLab6::InLab6 (CommandLineArgs args) inline explicit
Constructor for the outlab5 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab6::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< InLab6Inputs, Parser, InLab6Outputs >.
{
         Canvas canvas;
         auto x = -0.292;
         auto y = -0.66;
         auto iterations = 200;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         canvas.tone_map.growth_rate = 0.3;
         printJuliaSet<__float128>(canvas, x, y, iterations); //"o█■"
         std::cout << "Julia set at (" << x << "," << y << "), " << iterations << " iterations\n";
         return {
             .ProjectName = "NE591: InLab 06",
             .ProjectDescription = "Solving a system of linear equations using the Point Jacobi method",
             .SubmissionDate = "09/29/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
References CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
void Project< InLab6Inputs , Parser , InLab6Outputs >::execute () inline inherited
Executes the project.
                    {
         initialize();
         timedRun();
     }
getProfiler() [1/3]
auto Project< InLab6Inputs , Parser , InLab6Outputs >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< InLab6Inputs , Parser , InLab6Outputs >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< InLab6Inputs , Parser , InLab6Outputs >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
Parser Project< InLab6Inputs , Parser , InLab6Outputs >::getTerminal () const inline inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
void Project< InLab6Inputs , Parser , InLab6Outputs >::initialize () inline private inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< InLab6Inputs , Parser , InLab6Outputs >::postRun (InLab6Outputs & output, InLab6Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< InLab6Inputs , Parser , InLab6Outputs >::preRun (InLab6Outputs & output, InLab6Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
printResults()
static void InLab6::printResults (InLab6Outputs & results) inline static protected
This function prints the results of the computation.
Parameters
results The results of the computation.
{
         std::cout << "\ttotal iterations          : " << (results.solution.iterations) << std::endl;
         std::cout << "\tconverged                 : " << (results.solution.converged ? "Yes" : "No") << std::endl;
         std::cout << "\titerative error           : " << (results.solution.iterative_error) << std::endl;
         std::cout << "\tabsolute maximum residual : " << (results.getMaxResidual()) << std::endl;
         std::cout << "\texecution time (ns)       : " << (results.execution_time) << std::endl;
         std::cout << "\texecution time (ms)       : " << (results.execution_time / 1.0e6) << std::endl;
         std::cout << "\texecution time (s)        : " << (results.execution_time / 1.0e9) << std::endl;
     }
References Output::execution_time, Output::getMaxResidual(), and Output::solution.
Referenced by run().
run()
void InLab6::run (InLab6Outputs & outputs, InLab6Inputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution.
Parameters
outputs The output vector
inputs The input matrices
values The variable map
Implements Project< InLab6Inputs, Parser, InLab6Outputs >.
{
         nlohmann::json results;
         inputs.toJSON(results["inputs"]);
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_POINT_JACOBI)) {
             InLab6Outputs pointJacobiResults(inputs);
             Compute::usingPointJacobi(pointJacobiResults, inputs);
             pointJacobiResults.toJSON(
                 results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_POINT_JACOBI)]);
             Parser::printLine();
             std::cout << "Point Seidel Method Results" << std::endl;
             Parser::printLine();
             printResults(pointJacobiResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL)) {
             Parser::printLine();
             std::cout << "Gauss Seidel not implemented yet." << std::endl;
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_SOR)) {
             Parser::printLine();
             std::cout << "Successive over-relaxation (SOR) not implemented yet." << std::endl;
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_SSOR)) {
             Parser::printLine();
             std::cout << "Symmetric Successive over-relaxation (SOR) not implemented yet." << std::endl;
         }
         Parser::printLine();
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References process::inputs, METHOD_GAUSS_SEIDEL, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SSOR, CommandLine< InLab6Inputs >::printLine(), printResults(), Output::toJSON(), MyRelaxationMethod::TypeKey(), Compute::usingPointJacobi(), and writeJSON().
timedRun()
void Project< InLab6Inputs , Parser , InLab6Outputs >::timedRun () inline private inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(outputs, terminal.getInputs(), terminal.getArguments());
         run(outputs, terminal.getInputs(), terminal.getArguments());
         postRun(outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
cmdArgs
CommandLineArgs Project< InLab6Inputs , Parser , InLab6Outputs >::cmdArgs private inherited
outputs
InLab6Outputs Project< InLab6Inputs , Parser , InLab6Outputs >::outputs private inherited
terminal
Parser Project< InLab6Inputs , Parser , InLab6Outputs >::terminal private inherited
The documentation for this class was generated from the following file:
src/labs/inlab6/inlab6.h