var annotated_dup =
[
    [ "MyBLAS", "d2/d6e/namespaceMyBLAS.html", [
      [ "Stats", "dd/df5/namespaceMyBLAS_1_1Stats.html", [
        [ "Summary", "dc/da4/structMyBLAS_1_1Stats_1_1Summary.html", "dc/da4/structMyBLAS_1_1Stats_1_1Summary" ]
      ] ],
      [ "Input", "d7/dd6/structMyBLAS_1_1Input.html", "d7/dd6/structMyBLAS_1_1Input" ],
      [ "Output", "d9/d29/structMyBLAS_1_1Output.html", "d9/d29/structMyBLAS_1_1Output" ],
      [ "ContainerExpression", "d5/d49/classMyBLAS_1_1ContainerExpression.html", "d5/d49/classMyBLAS_1_1ContainerExpression" ],
      [ "ElementwiseExpression", "df/d63/classMyBLAS_1_1ElementwiseExpression.html", "df/d63/classMyBLAS_1_1ElementwiseExpression" ],
      [ "LazyMatrix", "d0/d28/classMyBLAS_1_1LazyMatrix.html", "d0/d28/classMyBLAS_1_1LazyMatrix" ],
      [ "Matrix", "d0/d27/classMyBLAS_1_1Matrix.html", "d0/d27/classMyBLAS_1_1Matrix" ],
      [ "Vector", "d4/d4d/classMyBLAS_1_1Vector.html", "d4/d4d/classMyBLAS_1_1Vector" ],
      [ "MatrixExpressionTests", "de/d99/classMyBLAS_1_1MatrixExpressionTests.html", null ],
      [ "VectorExpressionTests", "de/d3a/classMyBLAS_1_1VectorExpressionTests.html", null ],
      [ "LazyMatrixTests", "d6/d09/classMyBLAS_1_1LazyMatrixTests.html", "d6/d09/classMyBLAS_1_1LazyMatrixTests" ],
      [ "LazyVectorTests", "dd/d30/classMyBLAS_1_1LazyVectorTests.html", "dd/d30/classMyBLAS_1_1LazyVectorTests" ],
      [ "BaseMatrixTests", "d5/d8a/classMyBLAS_1_1BaseMatrixTests.html", "d5/d8a/classMyBLAS_1_1BaseMatrixTests" ],
      [ "MatrixMemoryAllocationTests", "d3/da2/classMyBLAS_1_1MatrixMemoryAllocationTests.html", "d3/da2/classMyBLAS_1_1MatrixMemoryAllocationTests" ],
      [ "PerformanceMatrixTests", "db/d15/classMyBLAS_1_1PerformanceMatrixTests.html", null ],
      [ "MatrixUtilityTests", "d0/d16/classMyBLAS_1_1MatrixUtilityTests.html", null ],
      [ "VectorTests", "d8/db9/classMyBLAS_1_1VectorTests.html", null ],
      [ "VectorMemoryAllocationTests", "da/d69/classMyBLAS_1_1VectorMemoryAllocationTests.html", "da/d69/classMyBLAS_1_1VectorMemoryAllocationTests" ],
      [ "PerformanceVectorTests", "d3/d8d/classMyBLAS_1_1PerformanceVectorTests.html", null ],
      [ "VectorUtilityTests", "dd/dfd/classMyBLAS_1_1VectorUtilityTests.html", null ],
      [ "LazyVector", "d6/d07/classMyBLAS_1_1LazyVector.html", "d6/d07/classMyBLAS_1_1LazyVector" ],
      [ "VectorExpression", "dd/dc2/classMyBLAS_1_1VectorExpression.html", "dd/dc2/classMyBLAS_1_1VectorExpression" ]
    ] ],
    [ "MyFactorizationMethod", "d1/d18/namespaceMyFactorizationMethod.html", [
      [ "Parameters", "de/dbb/structMyFactorizationMethod_1_1Parameters.html", "de/dbb/structMyFactorizationMethod_1_1Parameters" ]
    ] ],
    [ "MyLinearSolvingMethod", "de/d18/namespaceMyLinearSolvingMethod.html", [
      [ "Parameters", "de/d18/namespaceMyLinearSolvingMethod.html#d8/d53/structMyLinearSolvingMethod_1_1Parameters", "de/d18/namespaceMyLinearSolvingMethod_d8/d53/structMyLinearSolvingMethod_1_1Parameters_dup" ],
      [ "Solution", "de/d83/structMyLinearSolvingMethod_1_1Solution.html", "de/d83/structMyLinearSolvingMethod_1_1Solution" ]
    ] ],
    [ "MyPhysics", null, [
      [ "Diffusion", "d2/d71/namespaceMyPhysics_1_1Diffusion.html", [
        [ "Constants", "da/dff/structMyPhysics_1_1Diffusion_1_1Constants.html", "da/dff/structMyPhysics_1_1Diffusion_1_1Constants" ],
        [ "Matrix", "d0/d87/classMyPhysics_1_1Diffusion_1_1Matrix.html", "d0/d87/classMyPhysics_1_1Diffusion_1_1Matrix" ],
        [ "Params", "d6/d0c/structMyPhysics_1_1Diffusion_1_1Params.html", "d6/d0c/structMyPhysics_1_1Diffusion_1_1Params" ]
      ] ]
    ] ],
    [ "ArgsPrintMatrix", "d7/d12/structArgsPrintMatrix.html", "d7/d12/structArgsPrintMatrix" ],
    [ "CanvasType", "db/df1/Helpers_8h.html#de/d8a/structCanvasType", "db/df1/Helpers_8h_de/d8a/structCanvasType" ],
    [ "CommandLine", "dd/d02/classCommandLine.html", "dd/d02/classCommandLine" ],
    [ "CommandLineArgs", "d9/d41/CommandLine_8h.html#de/d26/structCommandLineArgs", "d9/d41/CommandLine_8h_de/d26/structCommandLineArgs" ],
    [ "ConcatTypeLists", "d8/d75/namespace_3globalScope_4.html#da/d9c/structConcatTypeLists", null ],
    [ "ConcatTypeLists<::testing::Types< Ts1... >, ::testing::Types< Ts2... > >", "d2/da0/TestedTypes_8h.html#d1/d97/structConcatTypeLists_3_1_1testing_1_1Types_3_01Ts1_8_8_8_01_4_00_01_1_1testing_1_1Types_3_01Ts2_8_8_8_01_4_01_4", "d2/da0/TestedTypes_8h_d1/d97/structConcatTypeLists_3_1_1testing_1_1Types_3_01Ts1_8_8_8_01_4_00_01_1_1testing_1_1Types_3_01Ts2_8_8_8_01_4_01_4" ],
    [ "DiffusionConstantsValidTest", "dd/d10/classDiffusionConstantsValidTest.html", "dd/d10/classDiffusionConstantsValidTest" ],
    [ "DiffusionMatrixTests", "dc/dff/classDiffusionMatrixTests.html", null ],
    [ "DiffusionParamsTest", "d5/d15/classDiffusionParamsTest.html", "d5/d15/classDiffusionParamsTest" ],
    [ "DiffusionParamsValidTest", "d1/d6a/classDiffusionParamsValidTest.html", "d1/d6a/classDiffusionParamsValidTest" ],
    [ "Factorial", "d7/d64/labs_2inlab1_2Compute_8h.html#de/de5/structFactorial", "d7/d64/labs_2inlab1_2Compute_8h_de/de5/structFactorial" ],
    [ "FactorizeInvalidLUMatrixTest", "d7/df1/classFactorizeInvalidLUMatrixTest.html", "d7/df1/classFactorizeInvalidLUMatrixTest" ],
    [ "FactorizeValidLUMatrixTest", "d1/dd7/classFactorizeValidLUMatrixTest.html", "d1/dd7/classFactorizeValidLUMatrixTest" ],
    [ "HeaderInfo", "d9/d41/CommandLine_8h.html#d3/db0/structHeaderInfo", "d9/d41/CommandLine_8h_d3/db0/structHeaderInfo" ],
    [ "InLab1", "dd/d40/classInLab1.html", "dd/d40/classInLab1" ],
    [ "InLab10", "d9/d0e/classInLab10.html", "d9/d0e/classInLab10" ],
    [ "InLab10MatrixTests", "d4/db5/classInLab10MatrixTests.html", "d4/db5/classInLab10MatrixTests" ],
    [ "InLab2", "d4/d63/classInLab2.html", "d4/d63/classInLab2" ],
    [ "InLab3", "d1/d1f/classInLab3.html", "d1/d1f/classInLab3" ],
    [ "InLab4", "dc/d9f/classInLab4.html", "dc/d9f/classInLab4" ],
    [ "InLab5", "d8/deb/classInLab5.html", "d8/deb/classInLab5" ],
    [ "InLab6", "d1/d8c/classInLab6.html", "d1/d8c/classInLab6" ],
    [ "Input", "d4/dae/structInput.html", "d4/dae/structInput" ],
    [ "Map", "da/ddc/structMap.html", "da/ddc/structMap" ],
    [ "MatrixBuildArgs", "d5/d65/labs_2outlab1_2Compute_8h.html#d8/dd7/structMatrixBuildArgs", "d5/d65/labs_2outlab1_2Compute_8h_d8/dd7/structMatrixBuildArgs" ],
    [ "MatrixTypesImpl", "d8/d75/namespace_3globalScope_4.html#d4/d7f/structMatrixTypesImpl", null ],
    [ "MatrixTypesImpl< MatrixType, ::testing::Types< Ts... > >", "d2/da0/TestedTypes_8h.html#d4/d0c/structMatrixTypesImpl_3_01MatrixType_00_01_1_1testing_1_1Types_3_01Ts_8_8_8_01_4_01_4", "d2/da0/TestedTypes_8h_d4/d0c/structMatrixTypesImpl_3_01MatrixType_00_01_1_1testing_1_1Types_3_01Ts_8_8_8_01_4_01_4" ],
    [ "MatrixVectorExpression", "d4/d68/classMatrixVectorExpression.html", "d4/d68/classMatrixVectorExpression" ],
    [ "MatrixVectorTests", "d3/dab/classMatrixVectorTests.html", null ],
    [ "MPIProject", "d0/df0/classMPIProject.html", "d0/df0/classMPIProject" ],
    [ "OutLab1", "dd/df3/classOutLab1.html", "dd/df3/classOutLab1" ],
    [ "OutLab3", "da/df0/classOutLab3.html", "da/df0/classOutLab3" ],
    [ "OutLab4", "d8/d5b/classOutLab4.html", "d8/d5b/classOutLab4" ],
    [ "OutLab5", "d3/d1d/classOutLab5.html", "d3/d1d/classOutLab5" ],
    [ "OutLab6", "d0/d4c/classOutLab6.html", "d0/d4c/classOutLab6" ],
    [ "OutLab7", "d3/d49/classOutLab7.html", "d3/d49/classOutLab7" ],
    [ "Output", "df/df1/structOutput.html", "df/df1/structOutput" ],
    [ "Outputs", "db/d86/structOutputs.html", "db/d86/structOutputs" ],
    [ "Parser", "d0/d40/classParser.html", "d0/d40/classParser" ],
    [ "Profiler", "dd/d0e/classProfiler.html", "dd/d0e/classProfiler" ],
    [ "Project", "db/d91/classProject.html", "db/d91/classProject" ],
    [ "Project1", "d8/ddb/classProject1.html", "d8/ddb/classProject1" ],
    [ "Project2", "dd/db5/classProject2.html", "dd/db5/classProject2" ],
    [ "Project3", "dd/dfb/classProject3.html", "dd/dfb/classProject3" ],
    [ "ResourceMonitor", "d1/d7c/classResourceMonitor.html", "d1/d7c/classResourceMonitor" ],
    [ "SolverInputs", "d8/d75/namespace_3globalScope_4.html#dc/db7/structSolverInputs", null ],
    [ "Stopwatch", "de/def/classStopwatch.html", "de/def/classStopwatch" ],
    [ "ToneMap", "db/df1/Helpers_8h.html#d1/db0/structToneMap", "db/df1/Helpers_8h_d1/db0/structToneMap" ],
    [ "TypeList", "d2/da0/TestedTypes_8h.html#db/d0b/structTypeList", null ]
];