NE591-008 C++17 Codebase: src/labs/outlab1/Compute.h File Reference
Compute.h File Reference
Compute methods for outlab1 in NE591-008.
#include <cmath>
#include <iostream>
#include "CommandLine.h"
#include "Parser.h"
Data Structures
struct MatrixBuildArgs
struct ArgsPrintMatrix
A struct to hold the arguments for the printMatrix function.
Typedefs
typedef struct MatrixBuildArgs MatrixBuildArgs
typedef struct ArgsPrintMatrix ArgsPrintMatrix
Functions
static long double elementFromA (const MatrixBuildArgs &args)
Computes the value of an element in matrix A.
static long double elementFromB (const MatrixBuildArgs &args)
Computes the value of an element in matrix B.
static long double elementFromC (const MatrixBuildArgs &args)
Computes the value of an element in matrix C.
static long double elementFromD (const MatrixBuildArgs &args)
Computes the value of an element in matrix D.
static long double elementFromF (const MatrixBuildArgs &args)
Computes the value of an element in matrix F.
static long double elementFromE (const MatrixBuildArgs &args)
Computes the value of an element in matrix E.
static void printMatrix (const ArgsPrintMatrix &args, const std::string &title)
This function prints a matrix with a given title.
Detailed Description
Compute methods for outlab1 in NE591-008.
Author
Arjun Earthperson
Date
09/01/2023
Definition in file Compute.h.
Data Structure Documentation
MatrixBuildArgs
struct MatrixBuildArgs
Data Fields
size_t idx_col
size_t idx_row
MatrixConstructParams & inputParams
Typedef Documentation
ArgsPrintMatrix
typedef struct ArgsPrintMatrix ArgsPrintMatrix
MatrixBuildArgs
typedef struct MatrixBuildArgs MatrixBuildArgs
Function Documentation
elementFromA()
static long double elementFromA (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix A.
This function computes the value of an element in matrix A based on its row and column indices. If the row index is equal to the column index, the value is 1.0. Otherwise, the value is 0.5.
Parameters
args A struct containing the row and column indices of the element.
Returns
The computed value of the element.
{
     return (args.idx_col == args.idx_row) ? 1.0f : 0.5f;
 }
References MatrixBuildArgs::idx_col, and MatrixBuildArgs::idx_row.
Referenced by elementFromC(), elementFromD(), elementFromE(), and OutLab1::run().
elementFromB()
static long double elementFromB (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix B.
This function computes the value of an element in matrix B based on its row and column indices. If the row index is greater than the column index, the value is 0.75. Otherwise, the value is 0.25.
Parameters
args A struct containing the row and column indices of the element.
Returns
The computed value of the element.
{
     return (args.idx_row > args.idx_col) ? 0.75f : 0.25f;
 }
References MatrixBuildArgs::idx_col, and MatrixBuildArgs::idx_row.
Referenced by elementFromC(), and OutLab1::run().
elementFromC()
static long double elementFromC (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix C.
This function computes the value of an element in matrix C by adding the corresponding values from matrices A and B.
Parameters
args A struct containing the row and column indices of the element.
Returns
The computed value of the element.
{
     return elementFromA(args) + elementFromB(args);
 }
References elementFromA(), and elementFromB().
Referenced by OutLab1::run().
elementFromD()
static long double elementFromD (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix D.
This function computes the value of an element in matrix D by multiplying the corresponding value from matrix A by a constant k.
Parameters
args A struct containing the row and column indices of the element and the constant k.
Returns
The computed value of the element.
{
     return args.inputParams.k * elementFromA(args);
 }
References elementFromA(), MatrixBuildArgs::inputParams, and Input::k.
Referenced by OutLab1::run().
elementFromE()
static long double elementFromE (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix E.
This function calculates the value of an element in matrix E by summing up the product of corresponding elements from matrix A and matrix F for all columns from 1 to N. The indices of the element in matrix E are provided through the MatrixBuildArgs structure.
Parameters
args A MatrixBuildArgs structure containing the row and column indices of the element in matrix E, and the input parameters required for the computation.
Returns
The computed value of the element in matrix E.
Note
The computation involves a loop that runs from 1 to N (inclusive), where N is a parameter provided in the inputParams member of the MatrixBuildArgs structure. For each iteration, the function constructs new MatrixBuildArgs structures for evaluating elements from matrix A and matrix F, multiplies these elements, and adds the product to an accumulator. The final value of the accumulator is returned as the result.
{
     long double accumulator = 0.0f;
     // loop n -> N
     for (size_t n = 1; n <= args.inputParams.N; n++) {
         // build args for evaluating element A(m,n)
         const MatrixBuildArgs argA = {
             .idx_row = args.idx_row,
             .idx_col = n,
             .inputParams = args.inputParams,
         };
         const long double a_mxn = elementFromA(argA);
         // build args for evaluating element F(n,j)
         const MatrixBuildArgs argF = {
             .idx_row = n,
             .idx_col = args.idx_col,
             .inputParams = args.inputParams,
         };
         const long double f_nxj = elementFromF(argF);
         const long double product = a_mxn * f_nxj;
         accumulator += product;
     }
     return accumulator;
 }
References elementFromA(), elementFromF(), MatrixBuildArgs::idx_col, MatrixBuildArgs::idx_row, MatrixBuildArgs::inputParams, Input::N, and n.
Referenced by OutLab1::run().
elementFromF()
static long double elementFromF (const MatrixBuildArgs & args) inline static
Computes the value of an element in matrix F.
This function calculates the value of an element in matrix F using the formula 1/(row index + column index). The row and column indices are assumed to start from 1.
Parameters
args A MatrixBuildArgs struct containing the row and column indices for the element to be computed.
Returns
The computed value of the element in matrix F.
{
     return 1.0f / (static_cast<long double>(args.idx_row + args.idx_col));
 }
References MatrixBuildArgs::idx_col, and MatrixBuildArgs::idx_row.
Referenced by elementFromE(), and OutLab1::run().
printMatrix()
static void printMatrix (const ArgsPrintMatrix & args, const std::string & title) static
This function prints a matrix with a given title.
The function loops over the rows and columns of the matrix, evaluates the value of each element using the provided evaluation function, and then prints the value. The matrix is printed row by row, with each element having two decimal points. A newline is printed at the end of each row. The title of the matrix is printed before the matrix itself.
Parameters
args A struct of type ArgsPrintMatrix, which contains the following fields:
start_row: The index of the first row of the matrix to be printed.
start_col: The index of the first column of the matrix to be printed.
num_rows: The number of rows in the matrix.
num_cols: The number of columns in the matrix.
inputParams: A reference to an InputParams object, which contains parameters to be used in the evaluation of the matrix elements.
evaluate: A pointer to a function that takes a MatrixBuildArgs object and returns a long double. This function is used to evaluate the value of each element in the matrix.
title A string that contains the title of the matrix. This title is printed before the matrix itself.
Returns
void
{
     // print the title
     std::cout << std::endl << title << std::endl << std::endl;
     // loop over rows
     for (auto idx_row = args.start_row; idx_row <= args.num_rows; idx_row++) {
         // loop over columns
         for (auto idx_col = args.start_col; idx_col <= args.num_cols;
              idx_col++) {
             // construct a new variable in the hope that the compiler will
             // unfold this loop and vectorize the evaluate op.
             auto points = MatrixBuildArgs{
                 .idx_row = idx_row,
                 .idx_col = idx_col,
                 .inputParams = args.inputParams,
             };
             // get the element value
             const auto value = args.evaluate(points);
             // print two decimal points
             std::printf("%.2Lf  ", value);
         }
         // newline at end of columns
         std::cout << std::endl;
     }
     // padding
     std::cout << std::endl;
 }
References ArgsPrintMatrix::evaluate, MatrixBuildArgs::idx_row, ArgsPrintMatrix::inputParams, ArgsPrintMatrix::num_cols, ArgsPrintMatrix::num_rows, points, ArgsPrintMatrix::start_col, ArgsPrintMatrix::start_row, and title().
Referenced by OutLab1::run().