NE591-008 C++17 Codebase: MyBLAS::Vector< T > Class Template Reference
MyBLAS::Vector< T > Class Template Reference
Class representing a vector of T values. This class represents a vector of elements of type T. It provides various operations for working with vectors.
#include <Vector.h>
Public Member Functions
size_t getAllocatedBytes (bool actual=false) const
Vector ()
Default constructor. Initializes an empty column vector.
~Vector ()
Vector (const Vector &other)
Vector (std::vector< T > &_data, bool _isRow)
Constructor that initializes the vector with a given vector and row/column indicator.
Vector (std::vector< T > _data, bool _isRow)
Constructor that initializes the vector with a given vector and row/column indicator.
Vector (std::vector< T > &_data)
Constructor that initializes the vector with a given vector. The vector is assumed to be a column vector.
Vector (std::vector< T > _data)
Constructor that initializes the vector with a given vector. The vector is assumed to be a column vector.
Vector (size_t size, const T initial=0, bool _isRow=false)
Parameterized constructor that initializes the vector with a given size, initial value, and row/column indicator.
Vector (size_t size, std::function< T(size_t)> func)
Constructor that initializes the vector with a given size and a lambda function.
Vector (std::initializer_list< T > initList, bool _isRow=false)
Constructor that initializes the vector with an initializer list.
Vector (LazyVector< T > &vector, bool _isRow=false)
Constructor that initializes the vector with a LazyVector and a row/column indicator.
Vector (LazyVector< T > vector, bool _isRow=false)
Constructor that initializes the vector with a LazyVector and a row/column indicator.
template<typename U >
Vector (const Vector< U > &other)
template<class VectorType >
Vector (VectorType vector)
Vector & operator= (const Vector &other)
Vector & operator= (Vector &&other) noexcept
const std::vector< T > & getData () const
Getter for the vector data.
std::vector< T > & getData ()
Getter for the vector data.
size_t size () const
Getter for the size of the vector.
bool isRowVector () const
Returns whether this vector is a row vector.
T & operator[] (const size_t idx)
Overloaded operator[] to access individual elements of the vector.
const T & operator[] (const size_t idx) const
Overloaded operator[] to access individual elements of the vector (const version).
bool operator== (const Vector &rhs) const
Overloaded operator== to check for equality between two vectors.
bool operator!= (const Vector &rhs) const
Overloaded operator!= to check for inequality between two vectors.
Vector operator+ (const Vector &rhs) const
Overloaded operator+ to add two vectors.
Vector operator- (const Vector &rhs) const
Overloaded operator- to subtract two vectors.
T operator* (const Vector &rhs) const
Overloaded operator* to multiply two vectors (dot product).
Vector< T > operator* (const T &scalar) const
Overloaded operator* to multiply a vector with a scalar.
Vector< T > operator/ (const T &scalar) const
Overloaded operator/ to divide a vector by a scalar.
Vector< T > operator+ (const T &scalar) const
Overloaded operator+ to add a scalar to a vector.
Vector< T > operator- (const T &scalar) const
Overloaded operator- to subtract a scalar from a vector.
Protected Attributes
std::vector< T > data
Vector representing the vector data.
bool isRow
Boolean indicating whether the vector is a row vector.
Friends
std::ostream & operator<< (std::ostream &os, const Vector &m)
Overloaded operator<< to print the vector to an output stream.
Detailed Description
template<typename T>
class MyBLAS::Vector< T >
Class representing a vector of T values. This class represents a vector of elements of type T. It provides various operations for working with vectors.
Template Parameters
T The data type of the vector elements.
Constructor & Destructor Documentation
Vector() [1/13]
template<typename T > MyBLAS::Vector< T >::Vector () inline
Default constructor. Initializes an empty column vector.
              : isRow(false) {
         // ResourceMonitor<Vector<T>>::registerInstance(this);
     }
~Vector()
template<typename T > MyBLAS::Vector< T >::~Vector () inline
               {
         ResourceMonitor<Vector<T>>::unregisterInstance(this);
     }
Vector() [2/13]
template<typename T > MyBLAS::Vector< T >::Vector (const Vector< T > & other) inline
                                 : data(other.data), isRow(other.isRow) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [3/13]
template<typename T > MyBLAS::Vector< T >::Vector (std::vector< T > & _data, bool _isRow) inline explicit
Constructor that initializes the vector with a given vector and row/column indicator.
Parameters
_data Vector to initialize the vector with.
_isRow Boolean indicating whether the vector is a row vector.
                                                       : data(_data), isRow(_isRow) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [4/13]
template<typename T > MyBLAS::Vector< T >::Vector (std::vector< T > _data, bool _isRow) inline explicit
Constructor that initializes the vector with a given vector and row/column indicator.
Parameters
_data Vector to initialize the vector with.
_isRow Boolean indicating whether the vector is a row vector.
                                                      : data(std::move(_data)), isRow(_isRow) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [5/13]
template<typename T > MyBLAS::Vector< T >::Vector (std::vector< T > & _data) inline explicit
Constructor that initializes the vector with a given vector. The vector is assumed to be a column vector.
Parameters
_data Vector to initialize the vector with.
                                          : data(_data), isRow(false) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [6/13]
template<typename T > MyBLAS::Vector< T >::Vector (std::vector< T > _data) inline explicit
Constructor that initializes the vector with a given vector. The vector is assumed to be a column vector.
Parameters
_data Vector to initialize the vector with.
                                         : data(_data), isRow(false) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [7/13]
template<typename T > MyBLAS::Vector< T >::Vector (size_t size, const T initial = 0, bool _isRow = false) inline explicit
Parameterized constructor that initializes the vector with a given size, initial value, and row/column indicator.
Parameters
size Size of the vector.
initial Initial value for all elements in the vector.
_isRow Boolean indicating whether the vector is a row vector.
                                                                            : data(size, initial), isRow(_isRow) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [8/13]
template<typename T > MyBLAS::Vector< T >::Vector (size_t size, std::function< T(size_t)> func) inline explicit
Constructor that initializes the vector with a given size and a lambda function.
Parameters
size Size of the vector.
func Lambda function to generate the elements of the vector.
                                                               : data(size), isRow(false) {
         for (size_t i = 0; i < size; i++) {
             data[i] = func(i);
         }
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
Vector() [9/13]
template<typename T > MyBLAS::Vector< T >::Vector (std::initializer_list< T > initList, bool _isRow = false) inline
Constructor that initializes the vector with an initializer list.
Parameters
initList Initializer list to initialize the vector with.
_isRow Boolean indicating whether the vector is a row vector (default is false).
                                                                  : data(initList), isRow(_isRow) {
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
Vector() [10/13]
template<typename T > MyBLAS::Vector< T >::Vector (LazyVector< T > & vector, bool _isRow = false) inline explicit
Constructor that initializes the vector with a LazyVector and a row/column indicator.
Parameters
vector The LazyVector to initialize the vector with.
_isRow Boolean indicating whether the vector is a row vector.
                                                                : data(vector.size()), isRow(_isRow) {
         for (size_t i = 0; i < vector.size(); i++) {
             data[i] = vector[i];
         }
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::LazyVector< DataType >::size().
Vector() [11/13]
template<typename T > MyBLAS::Vector< T >::Vector (LazyVector< T > vector, bool _isRow = false) inline explicit
Constructor that initializes the vector with a LazyVector and a row/column indicator.
Parameters
vector The LazyVector to initialize the vector with.
_isRow Boolean indicating whether the vector is a row vector.
                                                               : data(vector.size()), isRow(_isRow) {
         for (size_t i = 0; i < vector.size(); i++) {
             data[i] = vector[i];
         }
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::LazyVector< DataType >::size().
Vector() [12/13]
template<typename T > template<typename U > MyBLAS::Vector< T >::Vector (const Vector< U > & other) inline explicit
{
         data.resize(other.size());
         for (size_t i = 0; i < other.size(); ++i) {
             data[i] = static_cast<T>(other[i]);
         }
         isRow = other.isRowVector(); // Assuming Vector<U> has a method isRowVector()
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
References MyBLAS::Vector< T >::data, i, MyBLAS::Vector< T >::isRow, MyBLAS::Vector< T >::isRowVector(), and MyBLAS::Vector< T >::size().
Vector() [13/13]
template<typename T > template<class VectorType > MyBLAS::Vector< T >::Vector (VectorType vector) inline explicit
{
         data.resize(vector.size());
         for (size_t i = 0; i < vector.size(); ++i) {
             data[i] = vector[i];
         }
         isRow = vector.isRowVector(); // Assuming VectorType has a method isRowVector()
         ResourceMonitor<Vector<T>>::registerInstance(this);
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::isRow.
Member Function Documentation
getAllocatedBytes()
template<typename T > size_t MyBLAS::Vector< T >::getAllocatedBytes (bool actual = false) const inline
{
         auto nItems = actual ? data.size() : data.capacity();
         assert(nItems >= size());
         size_t byteCount = 0;
         // count all the elements
         byteCount += nItems * (sizeof(T) > 0.0 ? sizeof(T) : 1);
         // Memory used by this object itself.
         byteCount += sizeof(*this);
         return byteCount;
     }
References MyBLAS::Vector< T >::data, and MyBLAS::Vector< T >::size().
getData() [1/2]
template<typename T > std::vector<T>& MyBLAS::Vector< T >::getData () inline
Getter for the vector data.
Returns
reference to the vector data.
 { return data; }
References MyBLAS::Vector< T >::data.
getData() [2/2]
template<typename T > const std::vector<T>& MyBLAS::Vector< T >::getData () const inline
Getter for the vector data.
Returns
Const reference to the vector data.
 { return data; }
References MyBLAS::Vector< T >::data.
Referenced by MyBLAS::Stats::max(), MyBLAS::Stats::mean(), MyBLAS::Stats::min(), MyBLAS::Stats::percentile(), Input::serialize(), MyBLAS::Stats::sum(), Profiler< FunctionType >::summarize(), Input::toJSON(), Output::toJSON(), MyBLAS::Input::toJSON(), MyBLAS::Output::toJSON(), and MyBLAS::Stats::variance().
isRowVector()
template<typename T > bool MyBLAS::Vector< T >::isRowVector () const inline
Returns whether this vector is a row vector.
Returns
true if row vector, false otherwise
{
         return isRow;
     }
References MyBLAS::Vector< T >::isRow.
Referenced by MyBLAS::Vector< T >::Vector().
operator!=()
template<typename T > bool MyBLAS::Vector< T >::operator!= (const Vector< T > & rhs) const inline
Overloaded operator!= to check for inequality between two vectors.
Parameters
rhs Vector to compare with the current vector.
Returns
Boolean indicating whether the two vectors are not equal.
{
         return !(*this==rhs);
     }
operator*() [1/2]
template<typename T > Vector<T> MyBLAS::Vector< T >::operator* (const T & scalar) const inline
Overloaded operator* to multiply a vector with a scalar.
Parameters
scalar Scalar to multiply with the vector.
Returns
Resultant vector after multiplication.
{
         Vector<T> result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = data[i] * scalar;
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator*() [2/2]
template<typename T > T MyBLAS::Vector< T >::operator* (const Vector< T > & rhs) const inline
Overloaded operator* to multiply two vectors (dot product).
Parameters
rhs Vector to multiply with the current vector.
Returns
Resultant scalar after multiplication.
{
         assert(data.size() == rhs.size());
         T result = 0;
         for (size_t i = 0; i < size(); ++i) {
             result += this->data[i] * rhs.data[i];
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator+() [1/2]
template<typename T > Vector<T> MyBLAS::Vector< T >::operator+ (const T & scalar) const inline
Overloaded operator+ to add a scalar to a vector.
Parameters
scalar Scalar to add to the vector.
Returns
Resultant vector after addition.
{
         Vector<T> result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = data[i] + scalar;
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator+() [2/2]
template<typename T > Vector MyBLAS::Vector< T >::operator+ (const Vector< T > & rhs) const inline
Overloaded operator+ to add two vectors.
Parameters
rhs Vector to add to the current vector.
Returns
Resultant vector after addition.
{
         assert(data.size() == rhs.size());
         Vector result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = this->data[i] + rhs.data[i];
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator-() [1/2]
template<typename T > Vector<T> MyBLAS::Vector< T >::operator- (const T & scalar) const inline
Overloaded operator- to subtract a scalar from a vector.
Parameters
scalar Scalar to subtract from the vector.
Returns
Resultant vector after subtraction.
{
         Vector<T> result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = data[i] - scalar;
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator-() [2/2]
template<typename T > Vector MyBLAS::Vector< T >::operator- (const Vector< T > & rhs) const inline
Overloaded operator- to subtract two vectors.
Parameters
rhs Vector to subtract from the current vector.
Returns
Resultant vector after subtraction.
{
         assert(data.size() == rhs.size());
         Vector result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = this->data[i] - rhs.data[i];
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator/()
template<typename T > Vector<T> MyBLAS::Vector< T >::operator/ (const T & scalar) const inline
Overloaded operator/ to divide a vector by a scalar.
Parameters
scalar Scalar to divide the vector by.
Returns
Resultant vector after division.
{
         assert(scalar != 0);
         Vector<T> result(size(), 0);
         for (size_t i = 0; i < size(); ++i) {
             result[i] = data[i] / scalar;
         }
         return result;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator=() [1/2]
template<typename T > Vector& MyBLAS::Vector< T >::operator= (const Vector< T > & other) inline
{
         if (this != &other) {
             data = other.data;
             isRow = other.isRow;
         }
         return *this;
     }
References MyBLAS::Vector< T >::data, and MyBLAS::Vector< T >::isRow.
operator=() [2/2]
template<typename T > Vector& MyBLAS::Vector< T >::operator= (Vector< T > && other) inline noexcept
{
         if (this != &other) {
             data = std::move(other.data);
             isRow = other.isRow;
             // Since we've moved from 'other', we may want to reset its state as appropriate
             other.isRow = false; // or true, depending on what you consider a default state
         }
         return *this;
     }
References MyBLAS::Vector< T >::data, and MyBLAS::Vector< T >::isRow.
operator==()
template<typename T > bool MyBLAS::Vector< T >::operator== (const Vector< T > & rhs) const inline
Overloaded operator== to check for equality between two vectors.
Parameters
rhs Vector to compare with the current vector.
Returns
Boolean indicating whether the two vectors are equal.
Note
When dealing with floating-point numbers, due to precision issues, two vectors that are theoretically equal may not be exactly equal. In such cases, it might be more appropriate to check if the difference between the vectors is below a certain tolerance, rather than checking for exact equality.
{
         if (data.size() != rhs.size()) {
             return false;
         }
         for (size_t i = 0; i < size(); ++i) {
             if (this->data[i] != rhs.data[i]) {
                 return false;
             }
         }
         return true;
     }
References MyBLAS::Vector< T >::data, i, and MyBLAS::Vector< T >::size().
operator[]() [1/2]
template<typename T > T& MyBLAS::Vector< T >::operator[] (const size_t idx) inline
Overloaded operator[] to access individual elements of the vector.
Parameters
idx Index of the element to access.
Returns
Reference to the element at the given index.
 { return data[idx]; }
References MyBLAS::Vector< T >::data.
operator[]() [2/2]
template<typename T > const T& MyBLAS::Vector< T >::operator[] (const size_t idx) const inline
Overloaded operator[] to access individual elements of the vector (const version).
Parameters
idx Index of the element to access.
Returns
Const reference to the element at the given index.
 { return data[idx]; }
References MyBLAS::Vector< T >::data.
size()
template<typename T > size_t MyBLAS::Vector< T >::size () const inline
Getter for the size of the vector.
Returns
Size of the vector.
 { return data.size(); }
References MyBLAS::Vector< T >::data.
Referenced by MyBLAS::Stats::abs(), MyBLAS::AbsoluteMaxResidual(), Parser::buildInputs(), MyBLAS::cast(), MyBLAS::Vector< T >::getAllocatedBytes(), MyBLAS::L2(), MyBLAS::norm(), MyBLAS::Vector< T >::operator*(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Vector< T >::operator+(), MyBLAS::Vector< T >::operator-(), MyBLAS::Vector< T >::operator/(), MyBLAS::Vector< T >::operator==(), MyBLAS::TYPED_TEST(), and MyBLAS::Vector< T >::Vector().
Friends And Related Function Documentation
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const Vector< T > & m) friend
Overloaded operator<< to print the vector to an output stream.
Parameters
os Output stream to print the vector to.
m Vector to print.
Returns
Reference to the output stream.
{
         const auto width = static_cast<int>(std::cout.precision() + static_cast<std::streamsize>(10));
         for (size_t i = 0; i < m.size(); ++i) {
             os << std::setw(width) << std::setfill(' ') << std::scientific << static_cast<long double>(m[i]);
         }
         os << '\n';
         return os;
     }
Field Documentation
data
template<typename T > std::vector<T> MyBLAS::Vector< T >::data protected
Vector representing the vector data.
Referenced by MyBLAS::Vector< T >::getAllocatedBytes(), MyBLAS::Vector< T >::getData(), MyBLAS::Vector< T >::operator*(), MyBLAS::Vector< T >::operator+(), MyBLAS::Vector< T >::operator-(), MyBLAS::Vector< T >::operator/(), MyBLAS::Vector< T >::operator=(), MyBLAS::Vector< T >::operator==(), MyBLAS::Vector< T >::operator[](), MyBLAS::Vector< T >::size(), and MyBLAS::Vector< T >::Vector().
isRow
template<typename T > bool MyBLAS::Vector< T >::isRow protected
Boolean indicating whether the vector is a row vector.
Referenced by MyBLAS::Vector< T >::isRowVector(), MyBLAS::Vector< T >::operator=(), and MyBLAS::Vector< T >::Vector().
The documentation for this class was generated from the following files:
src/utils/math/blas/matrix/Matrix.h
src/utils/math/blas/vector/Vector.h