NE591-008 C++17 Codebase: FluxCalculationTests< T > Class Template Reference
FluxCalculationTests< T > Class Template Reference
Test fixture for testing the flux calculations.
Protected Member Functions
MyBLAS::LazyVector< T > getSources (MyPhysics::Diffusion::Params< T > &p)
Detailed Description
template<typename T>
class FluxCalculationTests< T >
Test fixture for testing the flux calculations.
Template Parameters
T The floating-point type to be used for testing.
Member Function Documentation
getSources()
template<typename T > MyBLAS::LazyVector<T> FluxCalculationTests< T >::getSources (MyPhysics::Diffusion::Params< T > & p) inline protected
{
         return MyBLAS::LazyMatrix<T>(p.getM(), p.getN(), [](){
             return 1;
         }).asRowVector();
     }
References MyBLAS::LazyMatrix< DataType >::asRowVector(), MyPhysics::Diffusion::Params< FloatType >::getM(), and MyPhysics::Diffusion::Params< FloatType >::getN().
The documentation for this class was generated from the following file:
src/utils/physics/diffusion/tests/FluxCalculationTests.cpp