NE591-008 C++17 Codebase: Project1 Class Reference
Project1 Class Reference
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
#include <project1.h>
Public Member Functions
Project1 (CommandLineArgs args)
Constructor for the project1 class.
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
SolverInputs & getInputs ()
Returns the input data.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (SolverOutputs &output, SolverInputs &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (SolverOutputs &output, SolverInputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (SolverOutputs &output, SolverInputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Holds the command line arguments.
Parser terminal
An instance of CommandLineParserType which is used to parse command line arguments.
SolverOutputs _outputs
Holds the output data of the project.
Detailed Description
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
Project1()
Project1::Project1 (CommandLineArgs args) inline explicit
Constructor for the project1 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo Project1::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< SolverInputs, Parser, SolverOutputs >.
{
         Canvas canvas;
         auto x = -0.172;
         auto y = -0.66;
         size_t iterations = 2000;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         printJuliaSet<__float128>(canvas, x, y, iterations); //"o█■"
         return {
             .ProjectName = "NE591: Project Milestone 1",
             .ProjectDescription = "Serial Neutron Diffusion Code",
             .SubmissionDate = "09/29/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
References postprocess::iterations, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
virtual void Project< SolverInputs , Parser , SolverOutputs >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< SolverInputs , Parser , SolverOutputs >::finalize () inline protected virtual inherited
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
getInputs()
SolverInputs & Project< SolverInputs , Parser , SolverOutputs >::getInputs () inline inherited
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
getProfiler() [1/3]
auto Project< SolverInputs , Parser , SolverOutputs >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< SolverInputs , Parser , SolverOutputs >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< SolverInputs , Parser , SolverOutputs >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< SolverInputs , Parser , SolverOutputs >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< SolverInputs , Parser , SolverOutputs >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
postRun()
virtual void Project< SolverInputs , Parser , SolverOutputs >::postRun (SolverOutputs & output, SolverInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< SolverInputs , Parser , SolverOutputs >::preRun (SolverOutputs & output, SolverInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void Project1::run (SolverOutputs & output, SolverInputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution.
Parameters
output The output vector
inputs The input matrices
values The variable map
1. Read input parameters: Read the values of 𝑎, 𝑏, 𝑚, 𝑛, 𝐷, and Σₐ from an input file. Also,
read the non-uniformly distributed fixed source 𝑞(𝑖,𝑗) for 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛 from the input
file.
2. Calculate mesh spacings: Compute the mesh spacings 𝛿 and 𝛾 using the formulas 𝛿 = 𝑎/(𝑚+1) and 𝛾 =
𝑏/(𝑛+1).
3. Initialize the matrix and right-hand-side vector: Create an 𝑚×𝑛 matrix A and an 𝑚×𝑛 right-hand-side
vector B. Initialize all elements of A and B to zero.
4. Fill the matrix A and vector B: Loop through all the nodes 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛, and fill the
matrix A and vector B using the given equation:
       −D((φ(i+1,j) - 2φ(i,j) + φ(i-1,j))/δ² + (φ(i,j+1) - 2φ(i,j) + φ(i,j-1))/γ²) + Σₐφ(i,j) = q(i,j)
Note that the boundary conditions are already taken into account as the fluxes at the boundaries are zero.
5. Solve the linear system: Solve the linear system A * 𝜙 = B using LU factorization with pivoting.
The solution vector 𝜙 will contain the scalar fluxes at each node 𝑖, 𝑗, where 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛.
6. Output the results: Write the scalar fluxes 𝜙(𝑖,𝑗) for 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛 to an output file.
Reimplemented from Project< SolverInputs, Parser, SolverOutputs >.
{
         /**
             1. Read input parameters: Read the values of 𝑎, 𝑏, 𝑚, 𝑛, 𝐷, and Σₐ from an input file. Also,
             read the non-uniformly distributed fixed source 𝑞(𝑖,𝑗) for 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛 from the input
         file.
             2. Calculate mesh spacings: Compute the mesh spacings 𝛿 and 𝛾 using the formulas 𝛿 = 𝑎/(𝑚+1) and 𝛾 =
         𝑏/(𝑛+1).
             3. Initialize the matrix and right-hand-side vector: Create an 𝑚×𝑛 matrix A and an 𝑚×𝑛 right-hand-side
             vector B. Initialize all elements of A and B to zero.
             4. Fill the matrix A and vector B: Loop through all the nodes 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛, and fill the
             matrix A and vector B using the given equation:
                    −D((φ(i+1,j) - 2φ(i,j) + φ(i-1,j))/δ² + (φ(i,j+1) - 2φ(i,j) + φ(i,j-1))/γ²) + Σₐφ(i,j) = q(i,j)
             Note that the boundary conditions are already taken into account as the fluxes at the boundaries are zero.
             5. Solve the linear system: Solve the linear system A * 𝜙 = B using LU factorization with pivoting.
             The solution vector 𝜙 will contain the scalar fluxes at each node 𝑖, 𝑗, where 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛.
             6. Output the results: Write the scalar fluxes 𝜙(𝑖,𝑗) for 𝑖 = 1, … , 𝑚 and 𝑗 = 1, … , 𝑛 to an output file.
         **/
         auto profiler1 = getProfiler([&]() {
             // Your arbitrary block of code here
             int sum = 0;
             for (int i = 0; i < 1000000; ++i) {
                 sum += i;
             }
         }, 100, 0, "profiler1"); // Run the block 100 times
         profiler1.run();
         const bool quietMode = values.count("quiet");
         std::vector<Stopwatch<Nanoseconds>> clocks = std::vector<Stopwatch<Nanoseconds>>(5);
         std::vector<long double> durations = std::vector<long double>(5);
         nlohmann::json profiler;
         IntermediateResults intermediates;
         auto profiler2 = getProfiler([&]() {
             intermediates = initialize_diffusion_matrix_and_vector<long double>(inputs.m, inputs.n);
             naive_fill_diffusion_matrix_and_vector(inputs, intermediates);
         }, 100, 0, "profiler1"); // Run the block 100 times
         clocks[0].restart();
         profiler2.run();
         clocks[0].click();
         // Step 1. Initialize matrices
         durations[0] = static_cast<long double>(clocks[0].duration().count()) / 100.0;
         profiler["exclusive"]["initialize_and_fill"] = durations[0];
         profiler["cumulative"]["initialize_and_fill"] = durations[0];
         std::cout<<profiler2;
         if (!quietMode) {
             Parser::printLine();
             std::cout << "Diffusion Matrix A: \n";
             Parser::printLine();
             std::cout << intermediates.diffusion_matrix_A;
             Parser::printLine();
             std::cout << "Right Hand Side Vector B: \n";
             Parser::printLine();
             std::cout << intermediates.right_hand_side_vector_B;
         }
         durations[1] = static_cast<long double>(clocks[1].duration().count());
         profiler["exclusive"]["lup_factorize"] = durations[1];
         profiler["cumulative"]["lup_factorize"] = durations[1] + durations[0];
         MyBLAS::Vector<long double> b, Pb, y, phi;
         clocks[2].restart();
         {
             b = intermediates.right_hand_side_vector_B;
             Pb = intermediates.P * intermediates.right_hand_side_vector_B;
             y = MyBLAS::forwardSubstitution(intermediates.L, Pb);
             phi = MyBLAS::backwardSubstitution(intermediates.U, y);
         }
         clocks[2].click();
         durations[2] = static_cast<long double>(clocks[2].duration().count());
         profiler["exclusive"]["fb_substitution"] = durations[2];
         profiler["cumulative"]["fb_substitution"] = durations[2] + durations[1] + durations[0];
         profiler["exclusive"]["solve_linear_system"] = durations[2] + durations[1];
         profiler["cumulative"]["solve_linear_system"] = durations[2] + durations[1] + durations[0];
         MyBLAS::Vector<long double> b_prime, r;
         long double maxResidual;
         clocks[3].restart();
         {
             // compute fluxes
             fill_fluxes(phi, inputs, output);
             b_prime = intermediates.diffusion_matrix_A * phi;
             r = b - b_prime;
             output.residual = r;
             output.solution = phi;
             maxResidual = MyBLAS::Stats::max<long double>(MyBLAS::Stats::abs(r));
         }
         clocks[3].click();
         durations[3] = static_cast<long double>(clocks[3].duration().count());
         profiler["exclusive"]["residuals"] = durations[3];
         profiler["cumulative"]["residuals"] = durations[3] + durations[2] + durations[1] + durations[0];
         if (!values.count("quiet")) {
             Parser::printLine();
             std::cout << "Lower Triangular Matrix (L):\n";
             Parser::printLine();
             std::cout << intermediates.L;
             Parser::printLine();
             std::cout << "Upper Triangular Matrix (U):\n";
             Parser::printLine();
             std::cout << intermediates.U;
             Parser::printLine();
             std::cout << "Permutation Matrix (P):\n";
             Parser::printLine();
             std::cout << intermediates.P;
             Parser::printLine();
             std::cout << "Permuted constants (Pb = P * b):\n";
             Parser::printLine();
             std::cout << Pb;
             Parser::printLine();
             std::cout << "Intermediate vector (y), where (Ly = Pb):\n";
             Parser::printLine();
             std::cout << y;
             Parser::printLine();
             std::cout << "Solution vector (x, phi), where (Ux = y):\n";
             Parser::printLine();
             std::cout << phi;
             Parser::printLine();
             Parser::printLine();
             std::cout << "Computed flux 𝜙(𝑖,𝑗): \n";
             Parser::printLine();
             std::cout << output.fluxes;
             Parser::printLine();
             std::cout << "Residual vector (r = b - Ax) :\n";
             Parser::printLine();
             std::cout << r;
             Parser::printLine();
             std::cout << "Max Residual abs(r): ";
             std::cout << std::setprecision(max_precision) << maxResidual << std::endl;
             Parser::printLine();
         }
         clocks[4].restart();
         {
             // write json
             if (values.count("output-results-json")) {
                 nlohmann::json results;
                 inputs.toJSON(results["inputs"]);
                 output.toJSON(results["outputs"]);
                 writeJSON(values["output-results-json"].as<std::string>(), results);
             }
             if (values.count("output-flux-csv")) {
                 writeCSVMatrixNoHeaders(values["output-flux-csv"].as<std::string>(), output.fluxes);
             }
         }
         clocks[4].click();
         durations[4] = static_cast<long double>(clocks[4].duration().count());
         profiler["exclusive"]["post-process"] = durations[4];
         profiler["cumulative"]["post-process"] =
             durations[4] + durations[3] + durations[2] + durations[1] + durations[0];
         profiler["total"] = durations[4] + durations[3] + durations[2] + durations[1] + durations[0];
         profiler["problem_size"] = inputs.m * inputs.n;
         writeJSON("profile_" + std::to_string(inputs.m) + "x" + std::to_string(inputs.n) + ".json", profiler);
     }
References MyBLAS::Stats::abs(), MyBLAS::backwardSubstitution(), Map::diffusion_matrix_A, fill_fluxes(), Output::fluxes, MyBLAS::forwardSubstitution(), Project< SolverInputs, Parser, SolverOutputs >::getProfiler(), i, process::inputs, Map::L, max_precision, naive_fill_diffusion_matrix_and_vector(), Map::P, CommandLine< InLab6Inputs >::printLine(), Output::residual, Map::right_hand_side_vector_B, Output::solution, MyBLAS::Stats::sum(), Output::toJSON(), Map::U, writeCSVMatrixNoHeaders(), writeJSON(), and y.
timedRun()
virtual void Project< SolverInputs , Parser , SolverOutputs >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
_outputs
SolverOutputs Project< SolverInputs , Parser , SolverOutputs >::_outputs protected inherited
Holds the output data of the project.
cmdArgs
CommandLineArgs Project< SolverInputs , Parser , SolverOutputs >::cmdArgs protected inherited
Holds the command line arguments.
terminal
Parser Project< SolverInputs , Parser , SolverOutputs >::terminal protected inherited
An instance of CommandLineParserType which is used to parse command line arguments.
The documentation for this class was generated from the following file:
src/project/project1/project1.h