NE591-008 C++17 Codebase: src/utils/physics/diffusion/tests/DiffusionParamsTests.cpp File Reference
DiffusionParamsTests.cpp File Reference
The purpose of these tests is to ensure the correct functionality of the DiffusionParams class, which is part of a physics simulation library. The DiffusionParams class is responsible for storing and manipulating the parameters related to the diffusion process in a physical system. The tests are designed to verify the correctness of the class's methods, including constructors, setters, getters, and the output operator. They also check the class's ability to handle invalid and edge-case _inputs, such as zero, negative, and non-finite values.
#include "physics/diffusion/DiffusionParams.h"
#include <gtest/gtest.h>
Data Structures
class DiffusionParamsValidTest
A test fixture class for valid DiffusionParams.
class DiffusionParamsTest
A test fixture class for DiffusionParams.
Macros
#define TOLERANCE 1e-14
#define FLOAT_TYPE long double
Functions
static bool isClose (FLOAT_TYPE a, FLOAT_TYPE b, FLOAT_TYPE tolerance=TOLERANCE)
TEST_P (DiffusionParamsValidTest, ParameterizedConstructor)
Test for the parameterized constructor of DiffusionParams.
TEST_P (DiffusionParamsValidTest, SettersAndGetters)
Test for the setters and getters of DiffusionParams.
TEST_P (DiffusionParamsValidTest, OutputOperator)
Test for the output operator of DiffusionParams.
INSTANTIATE_TEST_SUITE_P (InputValues, DiffusionParamsValidTest, ::testing::Values(MyPhysics::Diffusion::Params< FLOAT_TYPE >(100.4, 78.5f, 5, 5, 1.3029, 1e-4, sources_), MyPhysics::Diffusion::Params< FLOAT_TYPE >(100.4, 78.5f, 5, 5, 1.3029, 1e-4, sources_)))
Instantiate the test suite for valid DiffusionParams.
TEST_F (DiffusionParamsTest, DefaultConstructor)
Test for the default constructor of DiffusionParams.
TEST_F (DiffusionParamsTest, ParameterizedConstructor)
Test for the parameterized constructor of DiffusionParams.
TEST_F (DiffusionParamsTest, SettersAndGetters)
Test for the setters and getters of DiffusionParams.
TEST_F (DiffusionParamsTest, InvalidInputs)
Test for invalid _inputs to DiffusionParams.
TEST_F (DiffusionParamsTest, NegativeInputs)
Test for negative _inputs to DiffusionParams.
TEST_F (DiffusionParamsTest, NonFiniteInputs)
Test for non-finite _inputs to DiffusionParams.
TEST_F (DiffusionParamsTest, OutputOperator)
Test for the output operator of DiffusionParams.
Variables
MyBLAS::Matrix< FLOAT_TYPE > sources_
Detailed Description
The purpose of these tests is to ensure the correct functionality of the DiffusionParams class, which is part of a physics simulation library. The DiffusionParams class is responsible for storing and manipulating the parameters related to the diffusion process in a physical system. The tests are designed to verify the correctness of the class's methods, including constructors, setters, getters, and the output operator. They also check the class's ability to handle invalid and edge-case _inputs, such as zero, negative, and non-finite values.
Author
Arjun Earthperson
Date
10/13/2023
The tests cover a wide range of scenarios to ensure comprehensive code coverage. The tests for the default and parameterized constructors verify that the class correctly initializes its member variables. The tests for the setters and getters ensure that these methods correctly modify and retrieve the class's member variables. The tests for invalid, negative, and non-finite _inputs check that the class correctly throws exceptions when given these types of _inputs. The test for the output operator verifies that this operator correctly formats a string representation of a DiffusionParams object. The parameterized tests, instantiated with a variety of valid _inputs, ensure that the class behaves correctly under different conditions. Overall, these tests provide a thorough examination of the DiffusionParams class's functionality.
Definition in file DiffusionParamsTests.cpp.
Macro Definition Documentation
FLOAT_TYPE
#define FLOAT_TYPE long double
TOLERANCE
#define TOLERANCE 1e-14
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (InputValues , DiffusionParamsValidTest , ::testing::Values(MyPhysics::Diffusion::Params< FLOAT_TYPE >(100.4, 78.5f, 5, 5, 1.3029, 1e-4, sources_), MyPhysics::Diffusion::Params< FLOAT_TYPE >(100.4, 78.5f, 5, 5, 1.3029, 1e-4, sources_)))
Instantiate the test suite for valid DiffusionParams.
isClose()
static bool isClose (FLOAT_TYPE a, FLOAT_TYPE b, FLOAT_TYPE tolerance = TOLERANCE) static
{
     return std::abs(a - b) < tolerance;
 }
References MyBLAS::Stats::abs().
Referenced by TEST_F(), and TEST_P().
TEST_F() [1/7]
TEST_F (DiffusionParamsTest , DefaultConstructor)
Test for the default constructor of DiffusionParams.
{
     EXPECT_EQ(params.getA(), 1);
     EXPECT_EQ(params.getB(), 1);
     EXPECT_EQ(params.getM(), 1);
     EXPECT_EQ(params.getN(), 1);
     EXPECT_EQ(params.getDelta(), 1);
     EXPECT_EQ(params.getGamma(), 1);
     EXPECT_EQ(params.getDiffusionCoefficient(), 0.0f);
     EXPECT_EQ(params.getMacroscopicRemovalCrossSection(), 0.0f);
 }
TEST_F() [2/7]
TEST_F (DiffusionParamsTest , InvalidInputs)
Test for invalid _inputs to DiffusionParams.
{
     EXPECT_THROW(params.setA(0), std::invalid_argument);
     EXPECT_THROW(params.setB(0), std::invalid_argument);
     EXPECT_THROW(params.setM(0), std::invalid_argument);
     EXPECT_THROW(params.setN(0), std::invalid_argument);
     EXPECT_THROW(params.setDiffusionCoefficient(0), std::invalid_argument);
     EXPECT_THROW(params.setMacroscopicRemovalCrossSection(0), std::invalid_argument);
     MyBLAS::Matrix<FLOAT_TYPE> sources = {{1.0f, 2.0f, 3.0f}, {4.0f, 5.0f, 6.0f}};
     EXPECT_THROW(params.setSources(sources), std::invalid_argument);
 }
TEST_F() [3/7]
TEST_F (DiffusionParamsTest , NegativeInputs)
Test for negative _inputs to DiffusionParams.
{
     EXPECT_THROW(params.setA(-1), std::invalid_argument);
     EXPECT_THROW(params.setB(-1), std::invalid_argument);
     EXPECT_THROW(params.setDiffusionCoefficient(-1), std::invalid_argument);
     EXPECT_THROW(params.setMacroscopicRemovalCrossSection(-1), std::invalid_argument);
 }
TEST_F() [4/7]
TEST_F (DiffusionParamsTest , NonFiniteInputs)
Test for non-finite _inputs to DiffusionParams.
{
     EXPECT_THROW(params.setA(std::numeric_limits<FLOAT_TYPE>::infinity()), std::invalid_argument);
     EXPECT_THROW(params.setB(std::numeric_limits<FLOAT_TYPE>::infinity()), std::invalid_argument);
     EXPECT_THROW(params.setDiffusionCoefficient(std::numeric_limits<FLOAT_TYPE>::infinity()), std::invalid_argument);
     EXPECT_THROW(params.setMacroscopicRemovalCrossSection(std::numeric_limits<FLOAT_TYPE>::infinity()), std::invalid_argument);
     EXPECT_THROW(params.setA(std::numeric_limits<FLOAT_TYPE>::quiet_NaN()), std::invalid_argument);
     EXPECT_THROW(params.setB(std::numeric_limits<FLOAT_TYPE>::quiet_NaN()), std::invalid_argument);
     EXPECT_THROW(params.setDiffusionCoefficient(std::numeric_limits<FLOAT_TYPE>::quiet_NaN()), std::invalid_argument);
     EXPECT_THROW(params.setMacroscopicRemovalCrossSection(std::numeric_limits<FLOAT_TYPE>::quiet_NaN()), std::invalid_argument);
 }
TEST_F() [5/7]
TEST_F (DiffusionParamsTest , OutputOperator)
Test for the output operator of DiffusionParams.
{
     MyBLAS::Matrix<FLOAT_TYPE> sources = {{1.0f, 2.0f}, {3.0f, 4.0f}};
     params.setA(2.0f).setB(3.0f).setM(2).setN(2).setDiffusionCoefficient(0.5f).setMacroscopicRemovalCrossSection(0.6f).setSources(sources);
     std::ostringstream os;
     os << params;
     EXPECT_EQ(os.str(), "a: 2 b: 3 m: 2 n: 2 delta: 0.666667 gamma: 1 diff_coeff: 0.5 cross_section: 0.6");
 }
TEST_F() [6/7]
TEST_F (DiffusionParamsTest , ParameterizedConstructor)
Test for the parameterized constructor of DiffusionParams.
{
     MyBLAS::Matrix<FLOAT_TYPE> sources = {{1.0f, 2.0f}, {3.0f, 4.0f}};
     MyPhysics::Diffusion::Params<FLOAT_TYPE> params2(2.0f, 3.0f, 2, 2, 0.5f, 0.6f, sources);
     EXPECT_EQ(params2.getA(), 2.0f);
     EXPECT_EQ(params2.getB(), 3.0f);
     EXPECT_EQ(params2.getM(), 2);
     EXPECT_EQ(params2.getN(), 2);
     EXPECT_TRUE(isClose(params2.getDelta(), 2.0f / 3.0f, 1e-6));
     EXPECT_TRUE(isClose(params2.getGamma(), 3.0f / 3.0f, 1e-6));
     EXPECT_EQ(params2.getDiffusionCoefficient(), 0.5f);
     EXPECT_EQ(params2.getMacroscopicRemovalCrossSection(), 0.6f);
     EXPECT_EQ(params2.getSources(), sources);
 }
References MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::getN(), MyPhysics::Diffusion::Params< FloatType >::getSources(), and isClose().
TEST_F() [7/7]
TEST_F (DiffusionParamsTest , SettersAndGetters)
Test for the setters and getters of DiffusionParams.
{
     MyBLAS::Matrix<FLOAT_TYPE> sources = {{1.0f, 2.0f}, {3.0f, 4.0f}};
     params.setA(2.0f).setB(3.0f).setM(2).setN(2).setDiffusionCoefficient(0.5f).setMacroscopicRemovalCrossSection(0.6f).setSources(sources);
     EXPECT_EQ(params.getA(), 2.0f);
     EXPECT_EQ(params.getB(), 3.0f);
     EXPECT_EQ(params.getM(), 2);
     EXPECT_EQ(params.getN(), 2);
     EXPECT_TRUE(isClose(params.getDelta(), 2.0f / 3.0f, 1e-6));
     EXPECT_TRUE(isClose(params.getGamma(), 3.0f / 3.0f, 1e-6));
     EXPECT_EQ(params.getDiffusionCoefficient(), 0.5f);
     EXPECT_EQ(params.getMacroscopicRemovalCrossSection(), 0.6f);
     EXPECT_EQ(params.getSources(), sources);
 }
References isClose().
TEST_P() [1/3]
TEST_P (DiffusionParamsValidTest , OutputOperator)
Test for the output operator of DiffusionParams.
{
     params = GetParam();
     std::ostringstream os;
     os << params;
     EXPECT_FALSE(os.str().empty());
 }
TEST_P() [2/3]
TEST_P (DiffusionParamsValidTest , ParameterizedConstructor)
Test for the parameterized constructor of DiffusionParams.
{
     params = GetParam();
     EXPECT_GT(params.getA(), 0);
     EXPECT_GT(params.getB(), 0);
     EXPECT_GT(params.getM(), 0);
     EXPECT_GT(params.getN(), 0);
     EXPECT_GT(params.getDelta(), 0);
     EXPECT_GT(params.getGamma(), 0);
     EXPECT_GT(params.getDiffusionCoefficient(), 0);
     EXPECT_GT(params.getMacroscopicRemovalCrossSection(), 0);
     EXPECT_EQ(params.getSources().getRows(), params.getM());
     EXPECT_EQ(params.getSources().getCols(), params.getN());
 }
TEST_P() [3/3]
TEST_P (DiffusionParamsValidTest , SettersAndGetters)
Test for the setters and getters of DiffusionParams.
{
     params = GetParam();
     params.setA(2.0f).setB(3.0f).setM(2).setN(2).setDiffusionCoefficient(0.5f).setMacroscopicRemovalCrossSection(0.6f);
     EXPECT_EQ(params.getA(), 2.0f);
     EXPECT_EQ(params.getB(), 3.0f);
     EXPECT_EQ(params.getM(), 2);
     EXPECT_EQ(params.getN(), 2);
 //    EXPECT_EQ(params.getDelta(), 2.0 / 3.0);
     EXPECT_EQ(params.getGamma(), 3.0 / 3.0);
     EXPECT_TRUE(isClose(params.getDelta(), 2.0f / 3.0f, 1e-6));
 //    EXPECT_TRUE(isClose(params.getGamma(), 2.0f / 3.0f));
     EXPECT_EQ(params.getDiffusionCoefficient(), 0.5f);
     EXPECT_EQ(params.getMacroscopicRemovalCrossSection(), 0.6f);
 }
References isClose().
Variable Documentation
sources_
MyBLAS::Matrix<FLOAT_TYPE> sources_
Initial value:
= {{1.0, 2.0, 3.0, 4.0, 5.0},
                                       {2.0, 3.0, 4.0, 5.0, 1.0},
                                       {3.0, 4.0, 5.0, 1.0, 2.0},
                                       {4.0, 5.0, 1.0, 2.0, 3.0},
                                       {5.0, 1.0, 2.0, 3.0, 4.0}}