NE591-008 C++17 Codebase: src/labs/outlab3/Compute.h File Reference
Compute.h File Reference
Compute methods for OutLab3 in NE591-008.
#include <algorithm>
#include <cmath>
#include <iostream>
#include "InputsOutputs.h"
#include "CommandLine.h"
#include "Stopwatch.h"
#include "extern/function.h"
#include "math/RootFinder.h"
Functions
static long double fillUsingTrapezoidal (NewtonCotesOutputs &outputs, const NewtonCotesInputs &inputs)
This function computes the integral of a user-defined function using the trapezoidal rule.
static long double fillUsingSimpsons (NewtonCotesOutputs &outputs, const NewtonCotesInputs &inputs)
This function computes the integral of a user-defined function using Simpson's rule.
template<typename T >
static T getLegendrePolynomial (const size_t n, const T point)
Computes the value of the Legendre polynomial of degree n at a given point.
template<typename T >
static T getLegendrePolynomialDerivative (const size_t n, const T point)
Computes the derivative of the Legendre polynomial of degree n at a given point.
template<typename T >
static T getGaussLegendreWeight (const size_t n, const T node)
Calculates the Gauss-Legendre weight for a given node and polynomial degree.
template<typename T >
static void fillGaussLegendreWeights (std::vector< T > &weights, const std::vector< T > &nodes, const size_t n)
Fills the provided weights vector with the Gauss-Legendre weights corresponding to the given nodes.
template<typename T >
static T getGaussLegendreNode (const size_t index, const size_t n)
Computes the Gauss-Legendre node for a given index and polynomial degree.
template<typename T >
static void fillGaussLegendreNodes (std::vector< T > &nodes, const size_t n)
Fills a vector with the Gauss-Legendre nodes for a given number of nodes.
static long double fillUsingGaussianQuadratures (GaussLegendreOutputs &outputs, const NewtonCotesInputs &inputs)
Computes the integral of a user-defined function using Gauss-Legendre quadrature.
Detailed Description
Compute methods for OutLab3 in NE591-008.
Author
Arjun Earthperson
Date
09/15/2023
Definition in file Compute.h.
Function Documentation
fillGaussLegendreNodes()
template<typename T > static void fillGaussLegendreNodes (std::vector< T > & nodes, const size_t n) static
Fills a vector with the Gauss-Legendre nodes for a given number of nodes.
This function calculates the Gauss-Legendre nodes for a given number of nodes and stores them in a vector. The Gauss-Legendre nodes are the roots of the Legendre polynomials and are used in numerical integration.
Template Parameters
T The data type of the nodes (e.g., double, float).
Parameters
[out] nodes A vector to store the calculated Gauss-Legendre nodes.
[in] n The number of Gauss-Legendre nodes to calculate.
Note
The function clears and resizes the input vector before filling it with the calculated nodes.
The function uses the getGaussLegendreNode() function to calculate each individual node.
{
     nodes.clear();
     nodes.resize(n);
     for (size_t i = 1; i <= n; i++) {
         nodes[i - 1] = getGaussLegendreNode<T>(i, n);
     }
 }
References i, and n.
Referenced by fillUsingGaussianQuadratures().
fillGaussLegendreWeights()
template<typename T > static void fillGaussLegendreWeights (std::vector< T > & weights, const std::vector< T > & nodes, const size_t n) static
Fills the provided weights vector with the Gauss-Legendre weights corresponding to the given nodes.
This function calculates the Gauss-Legendre weights for the given nodes using the getGaussLegendreWeight function and stores the results in the provided weights vector. The weights vector is resized to match the size of the nodes vector.
Template Parameters
T The data type of the nodes and weights (e.g., double, float).
Parameters
[out] weights A std::vector<T> to store the calculated Gauss-Legendre weights.
[in] nodes A const std::vector<T> containing the Gauss-Legendre nodes for which the weights are calculated.
[in] n The size_t representing the number of nodes and weights.
{
     std::transform(nodes.begin(), nodes.end(), weights.begin(),
                    [n](const T &node) { return getGaussLegendreWeight(n, node); });
 }
References n.
Referenced by fillUsingGaussianQuadratures().
fillUsingGaussianQuadratures()
static long double fillUsingGaussianQuadratures (GaussLegendreOutputs & outputs, const NewtonCotesInputs & inputs) static
Computes the integral of a user-defined function using Gauss-Legendre quadrature.
This function calculates the integral of a user-defined function over the interval [a, b] using Gauss-Legendre quadrature with n quadrature points. The quadrature points and weights are calculated using fillGaussLegendreNodes() and fillGaussLegendreWeights() functions.
Parameters
[out] outputs A reference to a GaussLegendreOutputs structure that will store the computed integral, quadrature points, and weights.
[in] inputs A constant reference to a NewtonCotesInputs structure containing the input parameters for the quadrature, such as the number of quadrature points (n), the interval [a, b], and a flag to flip the integral sign.
Returns
The computed integral value as a long double.
Note
The user-defined function to be integrated should be defined as user_defined_fx().
The Stopwatch<Nanoseconds> timer is used to measure the time taken for the computation.
{
     const auto n = inputs.n;
     const auto a = inputs.a;
     const auto b = inputs.b;
     long double totalTime = 0.0f;
     for (size_t runs = 0; runs < 1000; runs++) {
         Stopwatch<Nanoseconds> timer;
         timer.restart();
         auto nodes = std::vector<long double>(n);
         fillGaussLegendreNodes(nodes, n);
         auto weights = std::vector<long double>(n);
         fillGaussLegendreWeights(weights, nodes, n);
         long double integral = 0.0f;
         for (size_t i = 0; i < n; i++) {
             const long double x_i = 0.5f * ((b - a) * nodes[i] + a + b);
             integral += weights[i] * user_defined_fx(x_i);
         }
         integral *= 0.5f * (b - a);
         timer.click();
         outputs.integral = integral;
         outputs.weights = weights;
         outputs.quadrature_points = nodes;
         totalTime += static_cast<long double>(timer.duration().count());
     }
     std::cout << "Computing 1000 integrals using Gauss-Legendre Quadrature for n=(" << n << "), degree-" << (n - 1)
               << " took " << (totalTime) << " ns, avg: " << (totalTime) / 1000.f << std::endl;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References Stopwatch< D >::click(), Stopwatch< D >::duration(), fillGaussLegendreNodes(), fillGaussLegendreWeights(), i, process::inputs, integral(), Outputs::integral, n, Outputs::quadrature_points, Stopwatch< D >::restart(), user_defined_fx(), and Outputs::weights.
fillUsingSimpsons()
static long double fillUsingSimpsons (NewtonCotesOutputs & outputs, const NewtonCotesInputs & inputs) static
This function computes the integral of a user-defined function using Simpson's rule.
Parameters
outputs A reference to a NewtonCotesOutputs object to store the computed integral and step size.
inputs A constant reference to a NewtonCotesInputs object containing the input parameters for Simpson's rule.
Returns
The computed integral value as a long double.
Note
The function also prints the time taken to compute the integral.
{
     const size_t m = inputs.m;
     const long double b = inputs.b;
     const long double a = inputs.a;
     const long double h = (b - a) / m;
     long double totalTime = 0.0f;
     for (size_t runs = 0; runs < 1000; runs++) {
         Stopwatch<Nanoseconds> timer;
         timer.restart();
         long double sum = user_defined_fx(a) + user_defined_fx(b);
         for (size_t i = 1; i < m; i += 2) {
             sum += 4.0f * user_defined_fx(a + i * h);
         }
         for (size_t i = 2; i < m - 1; i += 2) {
             sum += 2.0f * user_defined_fx(a + i * h);
         }
         const long double integral = h * sum / 3.0f;
         timer.click();
         outputs.h = h;
         outputs.integral = integral;
         totalTime += static_cast<long double>(timer.duration().count());
     }
     std::cout << "Computing 1000 integrals using Simpson's rule for m=(" << m << ") intervals took " << (totalTime)
               << " ns, avg: " << (totalTime) / 1000.f << std::endl;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References Stopwatch< D >::click(), Stopwatch< D >::duration(), Output::h, i, process::inputs, Output::integral, integral(), m, Stopwatch< D >::restart(), MyBLAS::Stats::sum(), and user_defined_fx().
fillUsingTrapezoidal()
static long double fillUsingTrapezoidal (NewtonCotesOutputs & outputs, const NewtonCotesInputs & inputs) static
This function computes the integral of a user-defined function using the trapezoidal rule.
Parameters
outputs A reference to a NewtonCotesOutputs object to store the computed integral and step size.
inputs A constant reference to a NewtonCotesInputs object containing the input parameters for the trapezoidal rule.
Returns
The computed integral value as a long double.
Note
The function also prints the time taken to compute the integral.
{
     // setup
     const size_t m = inputs.m;
     const long double b = inputs.b;
     const long double a = inputs.a;
     const long double h = (b - a) / m;
     long double totalTime = 0.0f;
     for (size_t runs = 0; runs < 1000; runs++) {
         Stopwatch<Nanoseconds> timer;
         timer.restart();
         // long double h = (b - a) / (n);
         long double compositeIntegral = user_defined_fx(a) + user_defined_fx(b);
         for (size_t i = 1; i < m; i++) {
             compositeIntegral += 2.0f * user_defined_fx(a + i * h);
         }
         const long double integral = (h / 2.0f) * compositeIntegral;
         timer.click();
         // finally, update the output values
         outputs.h = h;
         outputs.integral = integral;
         totalTime += static_cast<long double>(timer.duration().count());
     }
     std::cout << "Computing 1000 integrals using trapezoidal rule for m=(" << m << ") intervals took " << (totalTime)
               << " ns, avg: " << (totalTime) / 1000.f << std::endl;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References Stopwatch< D >::click(), Stopwatch< D >::duration(), Output::h, i, process::inputs, Output::integral, integral(), m, Stopwatch< D >::restart(), and user_defined_fx().
getGaussLegendreNode()
template<typename T > static T getGaussLegendreNode (const size_t index, const size_t n) static
Computes the Gauss-Legendre node for a given index and polynomial degree.
The roots of the Legendre polynomial of degree n are symmetric around the origin and are located in the interval [-1, 1]. They are also close to the zeros of the Chebyshev polynomials of the first kind, which are given by:
x_i = cos((2i - 1) * / (2n))
However, the roots of the Legendre polynomial are slightly shifted towards the center compared to the zeros of the Chebyshev polynomial. To account for this shift, we can use the following formula as the initial guess for the Newton-Raphson method:
x_i = cos(* (i - 0.25) / (n + 0.5))
This function will fill with Chebyshev polynomial guesses and iterate towards finding the roots using the Newton-Raphson method.
Template Parameters
T The numeric type of the Gauss-Legendre node.
Parameters
index The index of the Gauss-Legendre node.
n The degree of the Legendre polynomial.
Returns
The Gauss-Legendre node for the given index and polynomial degree.
{
     const T x_guess = std::cos(M_PI * (static_cast<T>(index) - 0.25f) / (static_cast<T>(n) + 0.5f));
     const std::function<T(T)> f = [n](T x) { return getLegendrePolynomial(n, x); };
     std::function<T(T)> df = [n](T x) { return getLegendrePolynomialDerivative(n, x); };
     return RootFinder::usingNewtonRaphson(f, df, x_guess);
 }
References df, f, function, getLegendrePolynomial(), getLegendrePolynomialDerivative(), n, RootFinder::usingNewtonRaphson(), and x.
getGaussLegendreWeight()
template<typename T > static T getGaussLegendreWeight (const size_t n, const T node) inline static
Calculates the Gauss-Legendre weight for a given node and polynomial degree.
This function computes the weight associated with a Gauss-Legendre quadrature node for a given Legendre polynomial degree. The weight is used in numerical integration to approximate the definite integral of a function.
Template Parameters
T The data type of the node and weight, typically float or double.
Parameters
n The degree of the Legendre polynomial.
node The Gauss-Legendre quadrature node for which the weight is to be calculated.
Returns
The Gauss-Legendre weight for the given node and polynomial degree.
Note
The function assumes that the input node is a valid Gauss-Legendre quadrature node for the given polynomial degree. It does not perform any checks for the validity of the input node.
See also
getLegendrePolynomialDerivative() for the calculation of the Legendre polynomial derivative.
{
     const T derivative = getLegendrePolynomialDerivative(n, node);
     const T weightDenominator = (1.0f - std::pow(node, 2.0f)) * std::pow(derivative, 2.0f);
     const T weight = 2.0f / weightDenominator;
     return weight;
 }
References getLegendrePolynomialDerivative(), and n.
getLegendrePolynomial()
template<typename T > static T getLegendrePolynomial (const size_t n, const T point) static
Computes the value of the Legendre polynomial of degree n at a given point.
This function uses a recursive approach to compute the value of the Legendre polynomial of degree n at a given point.
Template Parameters
T The data type of the input point and the output value.
Parameters
n The degree of the Legendre polynomial. This should be a non-negative integer.
point The point at which the Legendre polynomial is to be evaluated.
Returns
The value of the Legendre polynomial of degree n at the given point.
Note
The function uses a recursive approach, which may not be the most efficient method for large values of n. For better performance, consider using an iterative approach or a precomputed table of Legendre polynomial values.
{
     if (n <= 0) {
         return 1.0f;
     }
     if (n == 1) {
         return point;
     }
     const T P1 = getLegendrePolynomial(n - 1, point);
     const T P0 = getLegendrePolynomial(n - 2, point);
     const T Pnx1 = ((2 * n) - 1) * point * P1;
     const T Pnx0 = (n - 1) * P0;
     return (Pnx1 - Pnx0) / n;
 }
References n.
Referenced by getGaussLegendreNode(), and getLegendrePolynomialDerivative().
getLegendrePolynomialDerivative()
template<typename T > static T getLegendrePolynomialDerivative (const size_t n, const T point) static
Computes the derivative of the Legendre polynomial of degree n at a given point.
This function calculates the derivative of the Legendre polynomial of degree n at a given point using the recurrence relation:
P'n(x) = n * (x * P_n(x) - P{n-1}(x)) / (x^2 - 1)
Template Parameters
T The data type of the input point and the output derivative value.
Parameters
n The degree of the Legendre polynomial.
point The point at which the derivative of the Legendre polynomial is to be evaluated.
Returns
The derivative of the Legendre polynomial of degree n at the given point.
{
     const T D1 = point * getLegendrePolynomial(n, point);
     const T D0 = getLegendrePolynomial(n - 1, point);
     return (n * (D1 - D0)) / (std::pow(point, 2.0f) - 1.0f);
 }
References getLegendrePolynomial(), and n.
Referenced by getGaussLegendreNode(), and getGaussLegendreWeight().