NE591-008 C++17 Codebase: InLab04 Namespace Reference
InLab04 Namespace Reference
Functions
template<typename T >
MyBLAS::Vector< T > doForwardSubstitution (const MyBLAS::Matrix< T > &L, const MyBLAS::Vector< T > &b)
Perform forward substitution.
template<typename T >
MyBLAS::Vector< T > doBackwardSubstitution (const MyBLAS::Matrix< T > &U, const MyBLAS::Vector< T > &y)
Perform backward substitution.
Function Documentation
doBackwardSubstitution()
template<typename T > MyBLAS::Vector<T> InLab04::doBackwardSubstitution (const MyBLAS::Matrix< T > & U, const MyBLAS::Vector< T > & y)
Perform backward substitution.
Function to perform backward substitution, which is used in solving a system of linear equations after the system matrix has been decomposed into a lower triangular matrix and an upper triangular matrix, and forward substitution has been performed.
Template Parameters
T Using templates for data type consistency in computation.
Parameters
U An upper triangular matrix.
y The result vector after performing forward substitution.
Returns
The solution vector after performing backward substitution.
{
     return MyBLAS::backwardSubstitution(U, y);
 }
References MyBLAS::backwardSubstitution(), and y.
doForwardSubstitution()
template<typename T > MyBLAS::Vector<T> InLab04::doForwardSubstitution (const MyBLAS::Matrix< T > & L, const MyBLAS::Vector< T > & b)
Perform forward substitution.
Function to perform forward substitution, which is used in solving a system of linear equations after the system matrix has been decomposed into a lower triangular matrix and an upper triangular matrix.
Template Parameters
T Using templates for data type consistency in computation.
Parameters
L A lower triangular matrix.
b A vector in the system of linear equations Ax = b.
Returns
The result vector after performing forward substitution.
{
     return MyBLAS::forwardSubstitution(L, b);
 }
References MyBLAS::forwardSubstitution(), and L().