NE591-008 C++17 Codebase: src/project/project1/Compute.h File Reference
Compute.h File Reference
Compute methods for project milestone 1 in NE591-008.
#include <cmath>
#include <iostream>
#include "math/blas/Matrix.h"
#include "math/factorization/LU.h"
#include "math/factorization/LUP.h"
Functions
void calculate_mesh_spacings (SolverInputs &inputs)
template<typename T >
static IntermediateResults initialize_diffusion_matrix_and_vector (size_t m, size_t n)
Initializes the diffusion matrix and vector.
static void naive_fill_diffusion_matrix_and_vector (SolverInputs &inputs, IntermediateResults &intermediates)
Fills the diffusion matrix and vector.
static void naive_solve_linear_system (IntermediateResults &intermediates)
Solves the linear system.
static void fill_fluxes (MyBLAS::Vector< long double > phi, SolverInputs &inputs, SolverOutputs &outputs)
Fills the fluxes.
Detailed Description
Compute methods for project milestone 1 in NE591-008.
Author
Arjun Earthperson
Date
09/29/2023
Definition in file Compute.h.
Function Documentation
calculate_mesh_spacings()
void calculate_mesh_spacings (SolverInputs & inputs)
{
     // Compute the mesh spacing in the x-direction using the formula: delta = a
     // / (m + 1)
     inputs.delta = inputs.a / (inputs.m + 1);
     // Compute the mesh spacing in the y-direction using the formula: gamma = b
     // / (n + 1)
     inputs.gamma = inputs.b / (inputs.n + 1);
 }
Referenced by Parser::buildInputs().
fill_fluxes()
static void fill_fluxes (MyBLAS::Vector< long double > phi, SolverInputs & inputs, SolverOutputs & outputs) static
Fills the fluxes.
This function fills the fluxes based on the given phi vector. The fluxes are stored in a matrix with m+2 rows and n+2 columns.
Parameters
phi The phi vector.
inputs The inputs for the solver.
outputs The outputs of the solver including the fluxes.
{
     const size_t m = inputs.m;
     const size_t n = inputs.n;
     outputs.fluxes = MyBLAS::Matrix<long double>(m + 2, n + 2, 0);
     for (size_t i = 1; i <= m; i++) {
         for (size_t j = 1; j <= n; j++) {
             const size_t idx = (i - 1) * n + (j - 1);
             outputs.fluxes[i][j] = phi[idx];
         }
     }
 }
References Output::fluxes, i, m, and n.
Referenced by Project1::run().
initialize_diffusion_matrix_and_vector()
template<typename T > static IntermediateResults initialize_diffusion_matrix_and_vector (size_t m, size_t n) static
Initializes the diffusion matrix and vector.
This function initializes the diffusion matrix A and the right-hand-side vector B. The matrix and vector are resized to m x n and all elements are initialized to zero.
Template Parameters
T The type of the elements in the matrix and vector.
Parameters
m The number of rows in the matrix and vector.
n The number of columns in the matrix and vector.
Returns
IntermediateResults The initialized diffusion matrix A and right-hand-side vector B.
{
     IntermediateResults intermediates;
     // Resize the matrix A to m x n and initialize all elements to zero
     intermediates.diffusion_matrix_A = MyBLAS::Matrix<T>(
         std::vector<std::vector<T>>(m * n, std::vector<T>(m * n, 0)));
     // Resize the right-hand-side vector B to m x n and initialize all elements
     // to zero
     intermediates.right_hand_side_vector_B =
         MyBLAS::Vector<T>(std::vector<T>(m * n, 0));
     return intermediates;
 }
References Map::diffusion_matrix_A, m, n, and Map::right_hand_side_vector_B.
naive_fill_diffusion_matrix_and_vector()
static void naive_fill_diffusion_matrix_and_vector (SolverInputs & inputs, IntermediateResults & intermediates) static
Fills the diffusion matrix and vector.
This function fills the diffusion matrix A and the right-hand-side vector B based on the given inputs. The diagonal and off-diagonal elements of the matrix A are calculated using the given equations. The right-hand-side vector B is filled using the fixed source q(i, j).
Parameters
inputs The inputs for the solver.
intermediates The intermediate results including the diffusion matrix A and right-hand-side vector B.
{
     const size_t m = inputs.m;
     const size_t n = inputs.n;
     const long double D = inputs.diffusion_coefficient;
     const long double D_over_delta_squared = D / (inputs.delta * inputs.delta);
     const long double minus_D_over_delta_squared = -D_over_delta_squared;
     const long double D_over_gamma_squared = D / (inputs.gamma * inputs.gamma);
     const long double minus_D_over_gamma_squared = -D_over_gamma_squared;
     const long double cross_section = inputs.macroscopic_removal_cross_section;
     const long double diagonal =
         2.0 * (D_over_delta_squared + D_over_gamma_squared) + cross_section;
     // Loop through all the nodes i = 1, ..., m and j = 1, ..., n
     for (size_t i = 1; i <= m; ++i) {
         for (size_t j = 1; j <= n; ++j) {
             // Calculate the index of the current node in the matrix A and
             // vector B
             int idx = (i - 1) * n + (j - 1);
             // Fill the diagonal element of the matrix A using the given
             // equation
             intermediates.diffusion_matrix_A[idx][idx] = diagonal;
             // Fill the off-diagonal elements of the matrix A using the given
             // equation
             if (i > 1) {
                 intermediates.diffusion_matrix_A[idx][idx - n] =
                     minus_D_over_delta_squared;
             }
             if (i < m) {
                 intermediates.diffusion_matrix_A[idx][idx + n] =
                     minus_D_over_delta_squared;
             }
             if (j > 1) {
                 intermediates.diffusion_matrix_A[idx][idx - 1] =
                     minus_D_over_gamma_squared;
             }
             if (j < n) {
                 intermediates.diffusion_matrix_A[idx][idx + 1] =
                     minus_D_over_gamma_squared;
             }
             // Fill the right-hand-side vector B using the fixed source q(i, j)
             intermediates.right_hand_side_vector_B[idx] =
                 inputs.sources[i - 1][j - 1];
         }
     }
 }
References Map::diffusion_matrix_A, i, m, n, and Map::right_hand_side_vector_B.
Referenced by Project1::run().
naive_solve_linear_system()
static void naive_solve_linear_system (IntermediateResults & intermediates) static
Solves the linear system.
This function solves the linear system by factorizing the diffusion matrix A into L, U, and P matrices. It also checks if the factorized matrices L and U are unit lower triangular and upper triangular respectively, and if the generated matrix P is a permutation matrix.
Parameters
intermediates The intermediate results including the diffusion matrix A and the factorized matrices L, U, and P.
{
     const auto rows = intermediates.diffusion_matrix_A.getRows();
     const auto cols = intermediates.diffusion_matrix_A.getCols();
     intermediates.L = MyBLAS::Matrix(rows, cols, static_cast<long double>(0));
     intermediates.U = MyBLAS::Matrix(rows, cols, static_cast<long double>(0));
     intermediates.P = MyBLAS::LUP::factorize(intermediates.L, intermediates.U,
                                              intermediates.diffusion_matrix_A);
     if (!MyBLAS::isUnitLowerTriangularMatrix(intermediates.L)) {
         std::cerr << "Warning: Factorized matrix L is not unit lower "
                      "triangular, expect undefined behavior.\n";
     }
     if (!MyBLAS::isUpperTriangularMatrix(intermediates.U)) {
         std::cerr << "Warning: Factorized matrix U is not upper triangular, "
                      "expect undefined behavior.\n";
     }
     if (!MyBLAS::isPermutationMatrix(intermediates.P)) {
         std::cerr << "Warning: Generated matrix P is not a permutation matrix, "
                      "expect undefined behavior.\n";
     }
 }
References Map::diffusion_matrix_A, MyBLAS::LUP::factorize(), MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isPermutationMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), Map::L, Map::P, and Map::U.
Referenced by Project1::run().