NE591-008 C++17 Codebase: Profiler< FunctionType > Class Template Reference
Profiler< FunctionType > Class Template Reference
A template class to profile the execution time of a function.
#include <Profiler.h>
Public Member Functions
Profiler (FunctionType function, size_t runs=1, long double timeout=0, std::string description="")
Constructor for the Profiler class.
Profiler ()=default
Default constructor for the Profiler class.
size_t getTotalRuns () const
Gets the total number of runs for profiling.
Profiler & run ()
Runs the function for profiling and summarizes the results.
Profiler & operator= (const std::function< void()> &function)
Overloads the assignment operator to set the function to be profiled.
const MyBLAS::Stats::Summary< long double > & getSummary ()
Gets the summary of the profiling.
Private Member Functions
void runNoTimeout ()
Runs the function for profiling without a timeout.
bool runWithTimeout ()
Runs the function for profiling with a timeout.
void resetRuns ()
Resets the runs for profiling.
Static Private Member Functions
static void summarize (MyBLAS::Stats::Summary< long double > &summary, const std::vector< Stopwatch< Nanoseconds >> &stopwatches)
Summarizes the results of the profiling.
Private Attributes
FunctionType _function
The function to be profiled.
size_t _totalRuns
The number of times the function should be run for profiling.
long double _timeout
The maximum time allowed for the function to run.
bool _timedOut
Whether the function timed out during profiling.
std::string _description
A description of the function being profiled.
std::vector< Stopwatch< Nanoseconds > > _stopwatches
A vector of stopwatches to time each run of the function.
MyBLAS::Stats::Summary< long double > _summary
The summary of the profiling.
Friends
std::ostream & operator<< (std::ostream &os, const Profiler &m)
Overloads the << operator to print the summary of the profiling.
Detailed Description
template<typename FunctionType>
class Profiler< FunctionType >
A template class to profile the execution time of a function.
Template Parameters
FunctionType The type of the function to be profiled.
Constructor & Destructor Documentation
Profiler() [1/2]
template<typename FunctionType > Profiler< FunctionType >::Profiler (FunctionType function, size_t runs = 1, long double timeout = 0, std::string description = "") inline explicit
Constructor for the Profiler class.
Parameters
function The function to be profiled.
runs The number of times the function should be run for profiling.
timeout The maximum time allowed for the function to run.
description A description of the function being profiled.
                                                                                                                  : _function(function) {
        _timedOut = false;
        _totalRuns = runs > 0 ? runs : 1;
        _timeout = timeout > 0 ? timeout : 0;
        _stopwatches = std::vector<Stopwatch<Nanoseconds>>(0);
        _description = std::move(description);
        _summary = MyBLAS::Stats::Summary<long double>();
    }
References Profiler< FunctionType >::_description, Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_summary, Profiler< FunctionType >::_timedOut, Profiler< FunctionType >::_timeout, and Profiler< FunctionType >::_totalRuns.
Profiler() [2/2]
template<typename FunctionType > Profiler< FunctionType >::Profiler () default
Default constructor for the Profiler class.
This constructor initializes a Profiler object without any function to profile. The function to profile can be set later using the assignment operator.
Member Function Documentation
getSummary()
template<typename FunctionType > const MyBLAS::Stats::Summary<long double>& Profiler< FunctionType >::getSummary () inline
Gets the summary of the profiling.
Returns
The summary of the profiling.
{
        _summary.runs = _stopwatches.size();
        return _summary;
    }
References Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_summary, and MyBLAS::Stats::Summary< T >::runs.
getTotalRuns()
template<typename FunctionType > size_t Profiler< FunctionType >::getTotalRuns () const inline
Gets the total number of runs for profiling.
Returns
The total number of runs for profiling.
 { return _totalRuns; }
References Profiler< FunctionType >::_totalRuns.
operator=()
template<typename FunctionType > Profiler& Profiler< FunctionType >::operator= (const std::function< void()> & function) inline
Overloads the assignment operator to set the function to be profiled.
Parameters
function The function to be profiled.
Returns
A reference to this Profiler object.
{
        this->_function = function;
        return *this;
    }
References Profiler< FunctionType >::_function.
resetRuns()
template<typename FunctionType > void Profiler< FunctionType >::resetRuns () inline private
Resets the runs for profiling.
                     {
        _timedOut = false;
        _stopwatches.clear();
        _stopwatches.resize(0);
        _summary = MyBLAS::Stats::Summary<long double>();
    }
References Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_summary, and Profiler< FunctionType >::_timedOut.
Referenced by Profiler< FunctionType >::run().
run()
template<typename FunctionType > Profiler& Profiler< FunctionType >::run () inline
Runs the function for profiling and summarizes the results.
Returns
A reference to this Profiler object.
                    {
        resetRuns();
        if (_timeout > 0) {
            _timedOut = runWithTimeout();
        } else {
            runNoTimeout();
            _timedOut = false;
        }
        summarize(_summary, _stopwatches);
        return *this;
    }
References Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_summary, Profiler< FunctionType >::_timedOut, Profiler< FunctionType >::_timeout, Profiler< FunctionType >::resetRuns(), Profiler< FunctionType >::runNoTimeout(), Profiler< FunctionType >::runWithTimeout(), and Profiler< FunctionType >::summarize().
runNoTimeout()
template<typename FunctionType > void Profiler< FunctionType >::runNoTimeout () inline private
Runs the function for profiling without a timeout.
{
        for(size_t i = 0; i < _totalRuns; i++) {
            auto stopwatch = Stopwatch<Nanoseconds>().restart();
            _function();
            stopwatch.click();
            _stopwatches.emplace_back(stopwatch);
        }
    }
References Profiler< FunctionType >::_function, Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_totalRuns, i, and Stopwatch< D >::restart().
Referenced by Profiler< FunctionType >::run().
runWithTimeout()
template<typename FunctionType > bool Profiler< FunctionType >::runWithTimeout () inline private
Runs the function for profiling with a timeout.
Returns
Whether the function timed out during profiling.
{
        auto timeoutWatch = Stopwatch<Nanoseconds>();
        timeoutWatch.restart();
        for(size_t i = 0; i < _totalRuns; i++) {
            // timed out
            if(timeoutWatch.peek_elapsed_time().count() > _timeout) {
                _timedOut = true;
                break;
            }
            // run the calculation
            auto stopwatch = Stopwatch<Nanoseconds>().restart();
            _function();
            stopwatch.click();
            _stopwatches.emplace_back(stopwatch);
        }
        return _timedOut;
    }
References Profiler< FunctionType >::_function, Profiler< FunctionType >::_stopwatches, Profiler< FunctionType >::_timedOut, Profiler< FunctionType >::_timeout, Profiler< FunctionType >::_totalRuns, i, and Stopwatch< D >::restart().
Referenced by Profiler< FunctionType >::run().
summarize()
template<typename FunctionType > static void Profiler< FunctionType >::summarize (MyBLAS::Stats::Summary< long double > & summary, const std::vector< Stopwatch< Nanoseconds >> & stopwatches) inline static private
Summarizes the results of the profiling.
Parameters
summary The summary to store the results in.
stopwatches The stopwatches used to time each run of the function.
{
        // Create an array of durations
        MyBLAS::Vector<long double> durations(stopwatches.size());
        std::transform(stopwatches.begin(), stopwatches.end(), durations.getData().begin(), [](const Stopwatch<Nanoseconds>& stopwatch) { return stopwatch.duration().count(); });
        // Calculate statistics
        summary.min = MyBLAS::Stats::min(durations);
        summary.max = MyBLAS::Stats::max(durations);
        summary.sum = MyBLAS::Stats::sum(durations);
        summary.mean = MyBLAS::Stats::mean(durations);
        summary.variance = MyBLAS::Stats::variance(durations);
        summary.stddev = MyBLAS::Stats::std(durations);
        summary.median = MyBLAS::Stats::median(durations);
        summary.p5th = MyBLAS::Stats::percentile(durations, 5);
        summary.p95th = MyBLAS::Stats::percentile(durations, 95);
    }
References MyBLAS::Vector< T >::getData(), MyBLAS::Stats::Summary< T >::max, MyBLAS::Stats::max(), MyBLAS::Stats::Summary< T >::mean, MyBLAS::Stats::mean(), MyBLAS::Stats::Summary< T >::median, MyBLAS::Stats::median(), MyBLAS::Stats::Summary< T >::min, MyBLAS::Stats::min(), MyBLAS::Stats::Summary< T >::p5th, MyBLAS::Stats::Summary< T >::p95th, MyBLAS::Stats::percentile(), MyBLAS::Stats::std(), MyBLAS::Stats::Summary< T >::stddev, MyBLAS::Stats::Summary< T >::sum, MyBLAS::Stats::sum(), MyBLAS::Stats::Summary< T >::variance, and MyBLAS::Stats::variance().
Referenced by Profiler< FunctionType >::run().
Friends And Related Function Documentation
operator<<
template<typename FunctionType > std::ostream& operator<< (std::ostream & os, const Profiler< FunctionType > & m) friend
Overloads the << operator to print the summary of the profiling.
Parameters
os The output stream to print to.
m The Profiler object to print.
Returns
The output stream.
{
        os << R"(::::::::::::::::::::::::::::::: PROFILE SUMMARY ::::::::::::::::::::::::::::::::)"<<std::endl;
        os << "["<<m._stopwatches.size()<<"/"<<m._totalRuns<<"] : "<<m._description<<std::endl;
        os << R"(::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::)"<<std::endl;
        os << m._summary << std::endl;
        os << R"(::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::)"<<std::endl;
        return os;
    }
Field Documentation
_description
template<typename FunctionType > std::string Profiler< FunctionType >::_description private
A description of the function being profiled.
Referenced by Profiler< FunctionType >::Profiler().
_function
template<typename FunctionType > FunctionType Profiler< FunctionType >::_function private
The function to be profiled.
Referenced by Profiler< FunctionType >::operator=(), Profiler< FunctionType >::runNoTimeout(), and Profiler< FunctionType >::runWithTimeout().
_stopwatches
template<typename FunctionType > std::vector<Stopwatch<Nanoseconds> > Profiler< FunctionType >::_stopwatches private
A vector of stopwatches to time each run of the function.
Referenced by Profiler< FunctionType >::getSummary(), Profiler< FunctionType >::Profiler(), Profiler< FunctionType >::resetRuns(), Profiler< FunctionType >::run(), Profiler< FunctionType >::runNoTimeout(), and Profiler< FunctionType >::runWithTimeout().
_summary
template<typename FunctionType > MyBLAS::Stats::Summary<long double> Profiler< FunctionType >::_summary private
The summary of the profiling.
Referenced by Profiler< FunctionType >::getSummary(), Profiler< FunctionType >::Profiler(), Profiler< FunctionType >::resetRuns(), and Profiler< FunctionType >::run().
_timedOut
template<typename FunctionType > bool Profiler< FunctionType >::_timedOut private
Whether the function timed out during profiling.
Referenced by Profiler< FunctionType >::Profiler(), Profiler< FunctionType >::resetRuns(), Profiler< FunctionType >::run(), and Profiler< FunctionType >::runWithTimeout().
_timeout
template<typename FunctionType > long double Profiler< FunctionType >::_timeout private
The maximum time allowed for the function to run.
Referenced by Profiler< FunctionType >::Profiler(), Profiler< FunctionType >::run(), and Profiler< FunctionType >::runWithTimeout().
_totalRuns
template<typename FunctionType > size_t Profiler< FunctionType >::_totalRuns private
The number of times the function should be run for profiling.
Referenced by Profiler< FunctionType >::getTotalRuns(), Profiler< FunctionType >::Profiler(), Profiler< FunctionType >::runNoTimeout(), and Profiler< FunctionType >::runWithTimeout().
The documentation for this class was generated from the following file:
src/utils/profiler/Profiler.h