NE591-008 C++17 Codebase: MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T > Struct Template Reference
MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T > Struct Template Reference
Template struct to hold parameters for a solver with templated matrix and vector types.
#include <LinearSolverParams.h>
Public Member Functions
TemplatedParameters ()=default
Default constructor for TemplatedParameters.
TemplatedParameters (size_t _n, T _threshold, T _relaxation_factor, size_t _max_iterations, const MatrixType< T > &_coefficients, const VectorType< T > &_constants, VectorType< T > &_initial_guess)
Constructor with initialization of parameters.
TemplatedParameters & setSize (size_t _n)
Set the size of the matrix/vector.
TemplatedParameters & setConvergenceThreshold (T _threshold)
Set the convergence threshold.
TemplatedParameters & setRelaxationFactor (T _relaxation_factor)
Set the relaxation factor.
TemplatedParameters & setMaxIterations (size_t _max_iterations)
Set the maximum number of iterations to perform.
TemplatedParameters & setCoefficients (const MatrixType< T > &_coefficients)
Set the coefficient matrix.
TemplatedParameters & setConstants (const VectorType< T > &_constants)
Set the vector of constants.
TemplatedParameters & setInitialGuess (const VectorType< T > &_initial_guess)
Set the initial guess vector.
size_t getSize () const
Get the size of the matrix/vector.
T getThreshold () const
Get the convergence threshold.
T getRelaxationFactor () const
Get the relaxation factor.
size_t getMaxIterations () const
Get the maximum number of iterations to perform.
const MatrixType< T > & getCoefficients () const
Get the coefficient matrix.
const VectorType< T > & getConstants () const
Get the vector of constants.
const VectorType< T > & getInitialGuess () const
Get the initial guess vector.
Data Fields
size_t n = std::numeric_limits<size_t>::quiet_NaN()
Size of the matrix/vector.
T convergence_threshold = std::numeric_limits<T>::quiet_NaN()
The convergence threshold.
T relaxation_factor = std::numeric_limits<T>::quiet_NaN()
The relaxation factor.
size_t max_iterations = std::numeric_limits<size_t>::quiet_NaN()
Maximum number of iterations to perform.
MatrixType< T > coefficients
Coefficient matrix A.
VectorType< T > constants
Vector of constants b.
VectorType< T > initial_guess
Vector of initial guess for x.
Friends
std::ostream & operator<< (std::ostream &os, const TemplatedParameters< MatrixType, VectorType, T > &params)
Detailed Description
template<template< typename > class MatrixType, template< typename > class VectorType, typename T>
struct MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >
Template struct to hold parameters for a solver with templated matrix and vector types.
This struct contains parameters necessary for solving problems with templated matrix and vector types.
Template Parameters
MatrixType The matrix type used for storing coefficients.
VectorType The vector type used for storing constants.
T The data type used for storing parameters.
Constructor & Destructor Documentation
TemplatedParameters() [1/2]
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::TemplatedParameters () default
Default constructor for TemplatedParameters.
TemplatedParameters() [2/2]
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::TemplatedParameters (size_t _n, T _threshold, T _relaxation_factor, size_t _max_iterations, const MatrixType< T > & _coefficients, const VectorType< T > & _constants, VectorType< T > & _initial_guess) inline
Constructor with initialization of parameters.
Parameters
_n The size of the matrix/vector.
_threshold The convergence threshold.
_relaxation_factor The relaxation factor.
_max_iterations The maximum number of iterations to perform.
_coefficients The coefficient matrix.
_constants The vector of constants.
_initial_guess The initial guess for the solution vector x.
         : n(_n), convergence_threshold(_threshold), relaxation_factor(_relaxation_factor),
           max_iterations(_max_iterations), coefficients(_coefficients), constants(_constants), initial_guess(_initial_guess) {}
Member Function Documentation
getCoefficients()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > const MatrixType<T>& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getCoefficients () const inline
Get the coefficient matrix.
Returns
The coefficient matrix.
 { return coefficients; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients.
getConstants()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > const VectorType<T>& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getConstants () const inline
Get the vector of constants.
Returns
The vector of constants.
 { return constants; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants.
getInitialGuess()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > const VectorType<T>& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getInitialGuess () const inline
Get the initial guess vector.
Returns
The initial guess vector.
 { return initial_guess; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::initial_guess.
getMaxIterations()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > size_t MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getMaxIterations () const inline
Get the maximum number of iterations to perform.
Returns
The maximum number of iterations to perform.
 { return max_iterations; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations.
Referenced by Output::toJSON().
getRelaxationFactor()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > T MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getRelaxationFactor () const inline
Get the relaxation factor.
Returns
The relaxation factor.
 { return relaxation_factor; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::relaxation_factor.
getSize()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > size_t MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getSize () const inline
Get the size of the matrix/vector.
Returns
The size of the matrix/vector.
 { return n; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n.
getThreshold()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > T MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getThreshold () const inline
Get the convergence threshold.
Returns
The convergence threshold.
 { return convergence_threshold; }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold.
Referenced by Output::toJSON().
setCoefficients()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setCoefficients (const MatrixType< T > & _coefficients) inline
Set the coefficient matrix.
Parameters
coefficients The coefficient matrix.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the dimensions of the coefficients matrix do not match with the size.
{
         if (_coefficients.getRows() != n || _coefficients.getCols() != n) {
             throw std::invalid_argument("Invalid dimensions for the coefficients matrix. It should be square and match with the size.");
         }
         coefficients = _coefficients;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n.
setConstants()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setConstants (const VectorType< T > & _constants) inline
Set the vector of constants.
Parameters
constants The vector of constants.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the size of the constants vector does not match with the size.
{
         if (_constants.getSize() != n) {
             throw std::invalid_argument("Invalid size for the constants vector. It should match with the size.");
         }
         constants = _constants;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n.
setConvergenceThreshold()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setConvergenceThreshold (T _threshold) inline
Set the convergence threshold.
Parameters
threshold The convergence threshold.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
         if (_threshold <= 0 || !std::isfinite(_threshold)) {
             throw std::invalid_argument("Invalid value for convergence threshold. It should be a positive finite number.");
         }
         convergence_threshold = _threshold;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, and MyMath::isfinite().
setInitialGuess()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setInitialGuess (const VectorType< T > & _initial_guess) inline
Set the initial guess vector.
Parameters
_initial_guess The initial guess vector.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the size of the initial guess vector does not match with the size n.
{
         if (_initial_guess.getSize() != n) {
             throw std::invalid_argument("Invalid size for the constants vector. It should match with the size n.");
         }
         initial_guess = _initial_guess;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::initial_guess, and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n.
setMaxIterations()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setMaxIterations (size_t _max_iterations) inline
Set the maximum number of iterations to perform.
Parameters
max_iterations The maximum number of iterations to perform.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the provided value is zero.
{
         if (_max_iterations == 0) {
             throw std::invalid_argument("Invalid value for max_iterations. It should be a positive number.");
         }
         max_iterations = _max_iterations;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations.
setRelaxationFactor()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setRelaxationFactor (T _relaxation_factor) inline
Set the relaxation factor.
Parameters
relaxation_factor The relaxation factor.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
         if (_relaxation_factor <= 0 || !std::isfinite(_relaxation_factor)) {
             throw std::invalid_argument("Invalid value for relaxation factor. It should be a positive finite number.");
         }
         relaxation_factor = _relaxation_factor;
         return *this;
     }
References MyMath::isfinite(), and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::relaxation_factor.
setSize()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > TemplatedParameters& MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setSize (size_t _n) inline
Set the size of the matrix/vector.
Parameters
n The size of the matrix/vector.
Returns
A reference to the TemplatedParameters struct.
Exceptions
std::invalid_argument if the provided value is zero.
{
         if (_n == 0) {
             throw std::invalid_argument("Invalid value for n. It should be a positive number.");
         }
         n = _n;
         return *this;
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n.
Friends And Related Function Documentation
operator<<
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > std::ostream& operator<< (std::ostream & os, const TemplatedParameters< MatrixType, VectorType, T > & params) friend
{
         os << std::left; // Align text to the left
         os << "::::::::::::::::::::::::::::::: Solver Parameters ::::::::::::::::::::::::::::::" << std::endl;
         os << "--------------------------------------------------------------------------------"<<std::endl;
 //        try {
 //            if (params.coefficients.getRows()) {
 //                os << "Coefficient Matrix (A)" << std::endl;
 //                os << "--------------------------------------------------------------------------------" << std::endl;
 //                os << params.coefficients;
 //                os << "--------------------------------------------------------------------------------" << std::endl;
 //            }
 //        } catch (...) {}
 //        try {
 //            if (params.constants.size()) {
 //                os << "Constants Vector (b)" << std::endl;
 //                os << "--------------------------------------------------------------------------------" << std::endl;
 //                os << params.constants;
 //                os << "--------------------------------------------------------------------------------" << std::endl;
 //            }
 //        } catch (...) {}
         try {
             if (params.initial_guess.size()) {
                 os << "Initial Guess" << std::endl;
                 os << "--------------------------------------------------------------------------------" << std::endl;
                 os << params.initial_guess;
                 os << "--------------------------------------------------------------------------------" << std::endl;
             }
         } catch (...) {}
         os << std::setw(25) << "Size (n): " << params.n << std::endl;
         os << std::setw(25) << "Convergence Threshold: " << params.convergence_threshold << std::endl;
         os << std::setw(25) << "Relaxation Factor: " << params.relaxation_factor << std::endl;
         os << std::setw(25) << "Max Iterations: " << params.max_iterations;
         return os;
     }
Field Documentation
coefficients
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MatrixType<T> MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients
Coefficient matrix A.
This matrix holds the coefficients for the problem.
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getCoefficients(), OutLab6::printResults(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setCoefficients(), Input::toJSON(), and Output::toJSON().
constants
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > VectorType<T> MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants
Vector of constants b.
This vector holds the constants for the problem.
Referenced by Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getConstants(), OutLab6::printResults(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setConstants(), Input::toJSON(), and Output::toJSON().
convergence_threshold
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > T MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold = std::numeric_limits<T>::quiet_NaN()
The convergence threshold.
This value represents the convergence threshold for the solver.
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getThreshold(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setConvergenceThreshold(), Input::toJSON(), and Output::toJSON().
initial_guess
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > VectorType<T> MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::initial_guess
Vector of initial guess for x.
This vector holds the initial guess for x for the solution.
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getInitialGuess(), and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setInitialGuess().
max_iterations
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > size_t MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations = std::numeric_limits<size_t>::quiet_NaN()
Maximum number of iterations to perform.
This value represents the maximum number of iterations to perform.
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getMaxIterations(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setMaxIterations(), Input::toJSON(), and Output::toJSON().
n
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > size_t MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n = std::numeric_limits<size_t>::quiet_NaN()
Size of the matrix/vector.
This value represents the size of the matrix/vector.
Referenced by Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getSize(), OutLab6::printResults(), Project2::printResults(), Project3::printResults(), Project4::printResults(), Project5::printResults(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setCoefficients(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setConstants(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setInitialGuess(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setSize(), and Input::toJSON().
relaxation_factor
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > T MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::relaxation_factor = std::numeric_limits<T>::quiet_NaN()
The relaxation factor.
This value represents the relaxation factor for the solver.
Referenced by Parser::buildInputs(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::getRelaxationFactor(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setRelaxationFactor(), and Input::toJSON().
The documentation for this struct was generated from the following file:
src/utils/math/blas/solver/LinearSolverParams.h