NE591-008 C++17 Codebase: OutLab4 Class Reference
OutLab4 Class Reference
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
#include <outlab4.h>
Public Member Functions
OutLab4 (CommandLineArgs args)
Constructor for the outlab4 class.
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
MyBLAS::InputMatrices & getInputs ()
Returns the input data.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (MyBLAS::OutputVector &outputs, MyBLAS::InputMatrices &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (MyBLAS::OutputVector &output, MyBLAS::InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (MyBLAS::OutputVector &output, MyBLAS::InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Holds the command line arguments.
Parser terminal
An instance of CommandLineParserType which is used to parse command line arguments.
MyBLAS::OutputVector _outputs
Holds the output data of the project.
Detailed Description
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
OutLab4()
OutLab4::OutLab4 (CommandLineArgs args) inline explicit
Constructor for the outlab4 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab4::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >.
{
         Canvas canvas;
         auto x = -0.9;
         auto y = 0.26;
         size_t iterations = 50;
         canvas.tone_map.growth_rate = 0.15;
         printJuliaSet<__float128>(canvas, x, y, iterations);
         return {
             .ProjectName = "NE591: OutLab 04",
             .ProjectDescription = "Solving a system of linear equations using LU factorization",
             .SubmissionDate = "09/22/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
References postprocess::iterations, CanvasType< T >::tone_map, x, and y.
execute()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::finalize () inline protected virtual inherited
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
getInputs()
MyBLAS::InputMatrices & Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getInputs () inline inherited
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
getProfiler() [1/3]
auto Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
postRun()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::postRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::preRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void OutLab4::run (MyBLAS::OutputVector & outputs, MyBLAS::InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution.
Parameters
outputs The output vector
inputs The input matrices
values The variable map
Given the matrix A = LU and vector b, solve Ax = b, which is LUx = b.
Let y = Ux. Now, we have two systems of linear equations: Ly = b and Ux = y.
Solve the first system Ly = b using forward substitution.
Solve the second system Ux = y using backward substitution.
Reimplemented from Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >.
{
         /**
             1. Given the matrix A = LU and vector b, solve Ax = b, which is LUx = b.
             2. Let y = Ux. Now, we have two systems of linear equations: Ly = b and Ux = y.
             3. Solve the first system Ly = b using forward substitution.
             4. Solve the second system Ux = y using backward substitution.
         **/
         const auto A = inputs.coefficients;
         auto L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
         auto U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
         MyBLAS::LU::factorize(L, U, A);
         if (!MyBLAS::isUnitLowerTriangularMatrix(L)) {
             std::cerr << "Warning: Factorized matrix L is not unit lower triangular, expect undefined behavior.\n";
         }
         if (!MyBLAS::isUpperTriangularMatrix(U)) {
             std::cerr << "Warning: Factorized matrix U is not upper triangular, expect undefined behavior.\n";
         }
         const auto b = inputs.constants;
         const MyBLAS::Vector y = MyBLAS::forwardSubstitution(L, b);
         const MyBLAS::Vector x = MyBLAS::backwardSubstitution(U, y);
         nlohmann::json results;
         outputs.solution = x;
         const auto b_prime = A * x;
         const auto r = MyBLAS::Stats::abs(b - b_prime);
         outputs.residual = r;
         outputs.toJSON(results["outputs"]);
         if (!values.count("quiet")) {
             const auto precision = getTerminal().getCurrentPrecision();
             Parser::printLine();
             std::cout << "Lower Triangular Matrix (L):\n";
             Parser::printLine();
             std::cout << std::scientific << std::setprecision(static_cast<int>(precision)) << L;
             Parser::printLine();
             std::cout << "Upper Triangular Matrix (U):\n";
             Parser::printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << U;
             Parser::printLine();
             std::cout << "Factorized Matrix LU: \n";
             Parser::printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << L + U - MyBLAS::Matrix<long double>::eye(A.getCols());
             Parser::printLine();
             std::cout << "Intermediate vector y = inv(L) * b:\n";
             Parser::printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << y;
             Parser::printLine();
             std::cout << "Solution vector (x):\n";
             Parser::printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << x;
             Parser::printLine();
             std::cout << "Residual vector r=|b' - b| :\n";
             Parser::printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << r;
             Parser::printLine();
         }
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References MyBLAS::Stats::abs(), MyBLAS::backwardSubstitution(), MyBLAS::LU::factorize(), MyBLAS::forwardSubstitution(), CommandLine< InputType >::getCurrentPrecision(), Project< MyBLAS::InputMatrices, Parser, MyBLAS::OutputVector >::getTerminal(), process::inputs, MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), L(), postprocess::outputs, CommandLine< InLab6Inputs >::printLine(), writeJSON(), x, and y.
timedRun()
virtual void Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
_outputs
MyBLAS::OutputVector Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::_outputs protected inherited
Holds the output data of the project.
cmdArgs
CommandLineArgs Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::cmdArgs protected inherited
Holds the command line arguments.
terminal
Parser Project< MyBLAS::InputMatrices , Parser , MyBLAS::OutputVector >::terminal protected inherited
An instance of CommandLineParserType which is used to parse command line arguments.
The documentation for this class was generated from the following file:
src/labs/outlab4/outlab4.h