NE591-008 C++17 Codebase: Parser Class Reference
Parser Class Reference
This class is responsible for parsing command line arguments and validating user inputs.
#include <Parser.h>
Public Member Functions
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Constructor that initializes the Parser object with header information and command line arguments.
Parser ()=default
Default constructor for the Parser class.
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
Parser (const HeaderInfo &headerInfo, const CommandLineArgs &args)
Parser ()=default
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
TaylorSeriesInputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InLab10Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InLab11Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InLab12Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
LagrangePolynomialInputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
NewtonCotesInputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InputMatrices & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
MyBLAS::InputMatrices & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InLab6Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
OutLab7Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
MatrixConstructParams & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
OutLab10Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
OutLab11Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
OutLab12Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
OutLab6Inputs & getInputs ()
Method to get the inputs.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
SolverInputs & getInputs ()
Method to get the inputs.
Static Public Member Functions
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
Protected Member Functions
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void performInputArgumentsCheck (boost::program_options::variables_map &values) override
Performs input checks on the input variables.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void buildInputs (TaylorSeriesInputs &input, boost::program_options::variables_map &values) override
Method to fill the inputs object based on the parsed command line arguments.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InLab10Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InLab11Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InLab12Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (Input &input, boost::program_options::variables_map &values) override
Method to fill the inputs object based on the parsed command line arguments.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (NewtonCotesInputs &inputs, boost::program_options::variables_map &values) override
Builds the NewtonCotesInputs object with the provided values from the command line.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InputMatrices &inputs, boost::program_options::variables_map &values) override
Builds the output object with the provided values from the command line.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (MyBLAS::InputMatrices &inputs, boost::program_options::variables_map &values) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InLab6Inputs &inputs, boost::program_options::variables_map &values) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab7Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &arguments) override
This function builds the input options for the program.
void performInputArgumentsCheck (boost::program_options::variables_map &values) override
Performs input checks on the input variables.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void buildInputs (MatrixConstructParams &ToFill, boost::program_options::variables_map &values) override
Method to fill the inputs object based on the parsed command line arguments.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab10Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab11Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab12Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (Input &inputs, boost::program_options::variables_map &values) override
Method to fill the inputs object based on the parsed command line arguments.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (NewtonCotesInputs &inputs, boost::program_options::variables_map &values) override
Builds the NewtonCotesInputs object with the provided values from the command line.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (MyBLAS::InputMatrices &inputs, boost::program_options::variables_map &values) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (InputMatrices &inputs, boost::program_options::variables_map &values) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab6Inputs &input, boost::program_options::variables_map &values) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (OutLab7Inputs &input, boost::program_options::variables_map &values) override
Builds the inputs.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (SolverInputs &input, boost::program_options::variables_map &map) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (SolverInputs &input, boost::program_options::variables_map &map) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (SolverInputs &input, boost::program_options::variables_map &map) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (SolverInputs &input, boost::program_options::variables_map &map) override
Builds the input matrices for the MyBLAS library from a JSON file.
void buildInputArguments (boost::program_options::options_description &values) override
This function builds the input options for the program.
void printInputArguments (boost::program_options::variables_map &vm) override
This function prints the input values.
void performInputArgumentsCheck (boost::program_options::variables_map &map) override
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
void buildInputs (SolverInputs &input, boost::program_options::variables_map &map) override
Builds the input matrices for the MyBLAS library from a JSON file.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
Static Protected Member Functions
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
Protected Attributes
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
TaylorSeriesInputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InLab10Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InLab11Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InLab12Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
LagrangePolynomialInputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
NewtonCotesInputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InputMatrices _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
MyBLAS::InputMatrices _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InLab6Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
OutLab7Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
MatrixConstructParams _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
OutLab10Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
OutLab11Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
OutLab12Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
OutLab6Inputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
SolverInputs _inputs
HeaderInfo header
A HeaderInfo object to store information about the project.
Detailed Description
This class is responsible for parsing command line arguments and validating user inputs.
The Parser class extends the CommandLine class template with InLab10Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with InLab11Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with InLab12Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with OutLab7Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with OutLab10Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with OutLab11Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
The Parser class extends the CommandLine class template with OutLab12Inputs as the template argument. It provides methods to build input arguments, print input arguments, perform checks on input arguments, and build inputs based on the parsed arguments.
Constructor & Destructor Documentation
Parser() [1/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [2/50]
Parser::Parser () explicit default
Parser() [3/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<InLab10Inputs>(headerInfo, args) {}
Parser() [4/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [5/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<InLab11Inputs>(headerInfo, args) {}
Parser() [6/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [7/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<InLab12Inputs>(headerInfo, args) {}
Parser() [8/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [9/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [10/50]
Parser::Parser () explicit default
Parser() [11/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [12/50]
Parser::Parser () explicit default
Parser() [13/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [14/50]
Parser::Parser () explicit default
Parser() [15/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [16/50]
Parser::Parser () explicit default
Parser() [17/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [18/50]
Parser::Parser () explicit default
Parser() [19/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<OutLab7Inputs>(headerInfo, args) {}
Parser() [20/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [21/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [22/50]
Parser::Parser () explicit default
Parser() [23/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<OutLab10Inputs>(headerInfo, args) {}
Parser() [24/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [25/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<OutLab11Inputs>(headerInfo, args) {}
Parser() [26/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [27/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<OutLab12Inputs>(headerInfo, args) {}
Parser() [28/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [29/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [30/50]
Parser::Parser () explicit default
Parser() [31/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [32/50]
Parser::Parser () explicit default
Parser() [33/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [34/50]
Parser::Parser () explicit default
Parser() [35/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [36/50]
Parser::Parser () explicit default
Parser() [37/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [38/50]
Parser::Parser () explicit default
Parser() [39/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
Constructor that initializes the Parser object with header information and command line arguments.
Parameters
headerInfo A constant reference to a HeaderInfo object containing the header information.
args A constant reference to a CommandLineArgs object containing the command line arguments.
 : CommandLine<OutLab7Inputs>(headerInfo, args) {}
Parser() [40/50]
Parser::Parser () explicit default
Default constructor for the Parser class.
This constructor is explicitly defined to allow creating Parser objects without any initialization.
Parser() [41/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [42/50]
Parser::Parser () explicit default
Parser() [43/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [44/50]
Parser::Parser () explicit default
Parser() [45/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [46/50]
Parser::Parser () explicit default
Parser() [47/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [48/50]
Parser::Parser () explicit default
Parser() [49/50]
Parser::Parser (const HeaderInfo & headerInfo, const CommandLineArgs & args) inline explicit
 : CommandLine(headerInfo, args) {}
Parser() [50/50]
Parser::Parser () explicit default
Member Function Documentation
buildGenerics() [1/16]
static boost::program_options::options_description CommandLine< TaylorSeriesInputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [2/16]
static boost::program_options::options_description CommandLine< InLab11Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [3/16]
static boost::program_options::options_description CommandLine< InLab12Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [4/16]
static boost::program_options::options_description CommandLine< OutLab12Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [5/16]
static boost::program_options::options_description CommandLine< OutLab6Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [6/16]
static boost::program_options::options_description CommandLine< LagrangePolynomialInputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [7/16]
static boost::program_options::options_description CommandLine< SolverInputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [8/16]
static boost::program_options::options_description CommandLine< NewtonCotesInputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [9/16]
static boost::program_options::options_description CommandLine< InputMatrices >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [10/16]
static boost::program_options::options_description CommandLine< InLab10Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [11/16]
static boost::program_options::options_description CommandLine< MyBLAS::InputMatrices >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [12/16]
static boost::program_options::options_description CommandLine< InLab6Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [13/16]
static boost::program_options::options_description CommandLine< OutLab7Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [14/16]
static boost::program_options::options_description CommandLine< MatrixConstructParams >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [15/16]
static boost::program_options::options_description CommandLine< OutLab10Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildGenerics() [16/16]
static boost::program_options::options_description CommandLine< OutLab11Inputs >::buildGenerics () inline static protected inherited
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
buildInputArguments() [1/25]
void Parser::buildInputArguments (boost::program_options::options_description & arguments) inline override protected virtual
This function builds the input options for the program.
Implements CommandLine< OutLab12Inputs >.
{
         arguments.add_options()("scalar,k", boost::program_options::value<long double>(),
                                 "= scalar multiplier for [A]")("m-rank,M", boost::program_options::value<long double>(),
                                                                "= row rank for [A], row rank for [B]")(
             "n-rank,N", boost::program_options::value<long double>(), "= column rank for [B], row rank for [F]")(
             "j-rank,J", boost::program_options::value<long double>(), "= column rank for [F]");
     }
buildInputArguments() [2/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A description of the input options.
It defines the options for angle, convergence threshold and iterations, and adds them to the options description.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("angle,x", boost::program_options::value<long double>(),
                              "= angle in radians [abs(x) < 1.0]")("convergence-threshold,t",
                                                                   boost::program_options::value<long double>(),
                                                                   "= iterative convergence threshold [e > 0]")(
             "iterations,n", boost::program_options::value<long double>(), "= total number of iterations");
     }
buildInputArguments() [3/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("stopping-criterion,e", "= stopping criterion [+ve R]")
             ("max-iterations,k", "= maximum iterations [k  ]");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing n")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [4/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("threshold,t", boost::program_options::value<long double>(), "= convergence threshold [ > 0]")(
                 "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
                 "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A, and b")(
             "generate,g", "= Generate A,b ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [5/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("threshold,t", boost::program_options::value<long double>(), "= convergence threshold [ > 0]")(
                 "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
                 "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]")(
                 "use-direct", "= use the direct PI method")(
                 "use-rayleigh", "= use the Rayleigh Quotient PI method");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A")(
             "generate,g", "= Generate A ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [6/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("num-points,n", boost::program_options::value<long double>(),
                              "= (optional) number of interpolation points n")(
             "num-samples,m", boost::program_options::value<long double>(),
             "= number of Lagrange interpolation evaluation points")(
             "x-points,x",
             boost::program_options::value<std::vector<long double>>()->multitoken()->default_value(
                 std::vector<long double>(), ""),
             "= distinct and sorted (x) interpolation points if --input-csv is unset")(
             "fx-points,f",
             boost::program_options::value<std::vector<long double>>()->multitoken()->default_value(
                 std::vector<long double>(), ""),
             "= f(x=n) points if --use-fx-function and --input-csv are unset")(
             "input-csv,i", boost::program_options::value<std::string>(),
             "= path for input CSV file with two columns [x, f(x)]")(
             "output-csv,o", boost::program_options::value<std::string>(),
             "= path for output CSV file with five columns [i, x, f(x), L(x), E(x)]")("use-fx-function,F",
                                                                                      "= use bundled f(x=n) function");
     }
buildInputArguments() [7/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("start,a", boost::program_options::value<long double>(),
                              "= Starting value a for the integration interval [a,b]")(
             "stop,b", boost::program_options::value<long double>(),
             "= Stopping value b for the integration interval [a,b]")(
             "num-intervals,m", boost::program_options::value<long double>(), "= Number of equal intervals from [a,b]")(
             "use-trapezoidal,t", boost::program_options::value<bool>()->default_value(true),
             "= Set quadrature rule to the composite trapezoidal method")(
             "use-simpsons,s", boost::program_options::value<bool>()->default_value(true),
             "= Set quadrature rule to the composite Simpson's method")(
             "use-gaussian-quadratures,g", boost::program_options::value<bool>()->default_value(true),
             "= Use Gaussian quadratures for as the quadrature rule")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON file");
     }
buildInputArguments() [8/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("order,n", boost::program_options::value<long double>()->default_value(0),
                              "= order of the square matrix (natural number)")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing L, U, and b")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
     }
buildInputArguments() [9/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("order,n", boost::program_options::value<long double>()->default_value(0),
                              "= order of the square matrix (natural number)")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing L, U, and b")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
     }
buildInputArguments() [10/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("threshold,t", boost::program_options::value<long double>(),
                              "= iterative convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<long double>(), "= maximum number of iterations [n  ]")(
             "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A, and b")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
         boost::program_options::options_description methods("Solver Methods");
         methods.add_options()("use-point-jacobi", "= Use the Point-Jacobi method")(
             "use-gauss-seidel", "= [DISABLED] Use the Gauss-Seidel method")(
             "use-SOR", "= [DISABLED] Use the SOR method")("use-SSOR", "= [DISABLED] Use the symmetric SOR method");
         values.add(methods);
     }
References postprocess::methods.
buildInputArguments() [11/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("stopping-criterion,e", "= stopping criterion [+ve R]")
             ("max-iterations,k", "= maximum iterations [k  ]");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing n")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
 //        "source-terms-csv,s", boost::program_options::value<std::string>, "= Path to source-terms (,) CSV")(
 //"output-results-json,o", boost::program_options::value<std::string>(), "= Path to output results JSON")(
 //"output-flux-csv,f", boost::program_options::value<std::string>(), "= Path to computed flux (,) CSV");
         values.add_options()
            ("slab-width,L", boost::program_options::value<long double>(), "= slab width [+ve R]")(
             "num-angles,N", boost::program_options::value<long double>(), "= number of angles [N  ]")(
             "num-cells,I", boost::program_options::value<long double>(), "= number of cells [I  ]")(
             "total-cross-section,T", boost::program_options::value<long double>(), "= macroscopic total cross-section [+ve R]")(
             "scattering-cross-section,S", boost::program_options::value<long double>(), "= scattering macroscopic cross-section [+ve R]")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= path to source-terms (,) CSV");
     }
buildInputArguments() [12/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("threshold,t", boost::program_options::value<long double>(), "= convergence threshold [ > 0]")(
                 "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
                 "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A, and b")(
             "generate,g", "= Generate A,b ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [13/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("threshold,t", boost::program_options::value<long double>(), "= convergence threshold [ > 0]")(
                 "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
                 "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]")(
                 "use-direct", "= use the direct PI method")(
                 "use-rayleigh", "= use the Rayleigh Quotient PI method");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A")(
             "generate,g", "= Generate A ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [14/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         boost::program_options::options_description solverOptions("Solver Options");
         solverOptions.add_options()
             ("threshold,t", boost::program_options::value<long double>(), "= convergence threshold [ > 0]")(
                 "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
                 "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]")(
                 "lambda", boost::program_options::value<long double>(), "= guess for eigenvalue")(
                 "use-direct", "= use the direct PI method")(
                 "use-rayleigh", "= use the Rayleigh Quotient PI method")
                 ("use-inverse", "= use the inverse PI method");
         boost::program_options::options_description fileOptions("File I/O Options");
         fileOptions.add_options()(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing A")(
             "generate,g", "= Generate A ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= path for the output JSON");
         values.add(solverOptions);
         values.add(fileOptions);
     }
buildInputArguments() [15/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("num-points,n", boost::program_options::value<long double>(),
                              "= (optional) number of interpolation points n")(
             "num-samples,m", boost::program_options::value<long double>(),
             "= number of Lagrange interpolation evaluation points")(
             "x-points,x",
             boost::program_options::value<std::vector<long double>>()->multitoken()->default_value(
                 std::vector<long double>(), ""),
             "= distinct and sorted (x) interpolation points if --input-csv is unset")(
             "fx-points,f",
             boost::program_options::value<std::vector<long double>>()->multitoken()->default_value(
                 std::vector<long double>(), ""),
             "= f(x=n) points if --use-fx-function and --input-csv are unset")(
             "input-csv,i", boost::program_options::value<std::string>(),
             "= path for input CSV file with two columns [x, f(x)]")(
             "output-csv,o", boost::program_options::value<std::string>(),
             "= path for output CSV file with five columns [i, x, f(x), L(x), E(x)]")("use-fx-function,F",
                                                                                      "= use bundled f(x=n) function");
     }
buildInputArguments() [16/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("start,a", boost::program_options::value<long double>(),
                              "= Starting value (a) for the integration interval [a,b]")(
             "stop,b", boost::program_options::value<long double>(),
             "= Stopping value (b) for the integration interval [a,b]")("num-intervals,m",
                                                                        boost::program_options::value<long double>(),
                                                                        "= Number of equal intervals (m) from [a,b]")(
             "use-trapezoidal,t", boost::program_options::value<bool>()->default_value(true),
             "= Set quadrature rule to the composite trapezoidal method")(
             "use-simpsons,s", boost::program_options::value<bool>()->default_value(true),
             "= Set quadrature rule to the composite Simpson's method")(
             "use-gaussian-quadratures,g", boost::program_options::value<bool>()->default_value(true),
             "= Set quadrature rule to Gauss-Legendre Quadrature method")(
             "num-quadrature-points,n", boost::program_options::value<long double>(),
             "= Number of (n) Gauss-Legendre Quadrature points")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON file");
     }
buildInputArguments() [17/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("order,n", boost::program_options::value<long double>()->default_value(0),
                              "= order of the square matrix (natural number)")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing L, U, and b")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
     }
buildInputArguments() [18/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("no-pivoting", "Do not perform partial pivoting")("alternate-method",
                                                                                "Use alternate factorization method")(
             "order,n", boost::program_options::value<long double>()->default_value(0),
             "= order of the square matrix (natural number)")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing L, U, and b")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
     }
buildInputArguments() [19/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()("threshold,t", boost::program_options::value<long double>(),
                              "= convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<long double>(), "= maximum iterations [n  ]")(
             "relaxation-factor,w", boost::program_options::value<long double>(), "= SOR weight, typical   [0,2]")(
             "order,n", boost::program_options::value<long double>(), "= order of the square matrix [n  ]")(
             "input-json,i", boost::program_options::value<std::string>(),
             "= input JSON containing A, and b")("generate,g", "= Generate A,b ignoring input-json")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
         boost::program_options::options_description methods("Solver Methods");
         methods.add_options()("use-LUP", "= Use LUP factorization")("use-point-jacobi",
                                                                     "= Use the Point-Jacobi method")(
             "use-gauss-seidel", "= Use the Gauss-Seidel method")("use-SOR", "= Use the SOR method")(
             "use-SORJ", "= Use the SOR Jacobi method")("use-SSOR", "= Use the symmetric SOR method");
         values.add(methods);
     }
References postprocess::methods.
buildInputArguments() [20/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()
             (",n", boost::program_options::value<long double>(), "= sum upper limit [n  ]")(
             "input-json,i", boost::program_options::value<std::string>(), "= input JSON containing n")(
             "output-json,o", boost::program_options::value<std::string>(), "= path for the output JSON");
     }
buildInputArguments() [21/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()(",a", boost::program_options::value<long double>(),
                              "= Length of 1st dimension (+ve real)")(",b", boost::program_options::value<long double>(),
                                                                      "= Length of 2nd dimension (+ve real)")(
             ",m", boost::program_options::value<long double>(), "= Number of mesh-points in 1st dimension")(
             ",n", boost::program_options::value<long double>(), "= Number of mesh-points in 2nd dimension")(
             ",D", boost::program_options::value<long double>(), "= Diffusion coefficient D (+ve real)")(
             "cross-section", boost::program_options::value<long double>(), "= Removal cross-section  (+ve real)")(
             "input-parameter-json,i", boost::program_options::value<std::string>(), "= Path to input parameter JSON")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= Path to source-terms (,) CSV")(
             "output-results-json,o", boost::program_options::value<std::string>(), "= Path to output results JSON")(
             "output-flux-csv,f", boost::program_options::value<std::string>(), "= Path to computed flux (,) CSV");
         boost::program_options::options_description methods("Solver Methods");
         methods.add_options()("use-LUP", "= Use the LUP method")("use-point-jacobi",
                                                                  "= [DISABLED] Use the Point-Jacobi method")(
             "use-gauss-seidel", "= [DISABLED] Use the Gauss-Seidel method")("use-SOR",
                                                                             "= [DISABLED] Use the SOR method");
         values.add(methods);
     }
References postprocess::methods.
buildInputArguments() [22/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()(
             ",a", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 1st dimension (+ve real)")(
             ",b", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 2nd dimension (+ve real)")(
             ",m", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 1st dimension")(
             ",n", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 2nd dimension")(
             ",D", boost::program_options::value<MyBLAS::NumericType>(), "= Diffusion coefficient D (+ve real)")(
             "cross-section", boost::program_options::value<MyBLAS::NumericType>(), "= Removal cross-section  (+ve real)");
         boost::program_options::options_description files("Inputs/Outputs");
         files.add_options()(
             "input-parameter-json,i", boost::program_options::value<std::string>(), "= Path to input parameter JSON")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= Path to source-terms (,) CSV")(
             "output-results-json,o", boost::program_options::value<std::string>(), "= Path to output results JSON")(
             "flux-output-dir,f", boost::program_options::value<std::string>(), "= Path to computed flux (,)");
         boost::program_options::options_description methods("Solver Options");
         methods.add_options()
             ("use-LUP", "= Use LUP factorization")
             ("use-point-jacobi","= Use the Point-Jacobi method")
             ("use-SORJ", "= Use the SOR Jacobi method")
             ("use-gauss-seidel", "= Use the Gauss-Seidel method")
             ("use-SOR", "= Use the SOR method")
             ("use-SSOR", "= Use the symmetric SOR method")(
             "threshold,t", boost::program_options::value<MyBLAS::NumericType>(),"= convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<MyBLAS::NumericType>(), "= maximum iterations [n  ]")(
             "relaxation-factor,w", boost::program_options::value<MyBLAS::NumericType>(), "= SOR weight, typical   [0,2]");
         values.add(methods);
         values.add(files);
     }
References postprocess::methods.
buildInputArguments() [23/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()(
             ",a", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 1st dimension (+ve real)")(
             ",b", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 2nd dimension (+ve real)")(
             ",m", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 1st dimension")(
             ",n", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 2nd dimension")(
             ",D", boost::program_options::value<MyBLAS::NumericType>(), "= Diffusion coefficient D (+ve real)")(
             "cross-section", boost::program_options::value<MyBLAS::NumericType>(), "= Removal cross-section  (+ve real)");
         boost::program_options::options_description files("Inputs/Outputs");
         files.add_options()(
             "input-parameter-json,i", boost::program_options::value<std::string>(), "= Path to input parameter JSON")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= Path to source-terms (,) CSV")(
             "output-results-json,o", boost::program_options::value<std::string>(), "= Path to output results JSON")(
             "flux-output-dir,f", boost::program_options::value<std::string>(), "= Path to computed flux (,)");
         boost::program_options::options_description methods("Solver Options");
         methods.add_options()
             ("use-LUP", "= Use LUP factorization")
             ("use-point-jacobi","= Use the Point-Jacobi method")
             ("use-SORPJ", "= Use the SOR Jacobi method")
             ("use-symmetric-gauss-seidel", "= Use the symmetric Gauss-Seidel method")
             ("use-gauss-seidel", "= Use the Gauss-Seidel method")
             ("use-SOR", "= Use the SOR method")
             ("use-SSOR", "= Use the symmetric SOR method")(
             "threshold,t", boost::program_options::value<MyBLAS::NumericType>(),"= convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<MyBLAS::NumericType>(), "= maximum iterations [n  ]")(
             "relaxation-factor,w", boost::program_options::value<MyBLAS::NumericType>(), "= SOR weight, typical   [0,2]");
         values.add(methods);
         values.add(files);
     }
References postprocess::methods.
buildInputArguments() [24/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()(
             ",a", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 1st dimension (+ve real)")(
             ",b", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 2nd dimension (+ve real)")(
             ",m", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 1st dimension")(
             ",n", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 2nd dimension")(
             ",D", boost::program_options::value<MyBLAS::NumericType>(), "= Diffusion coefficient D (+ve real)")(
             "cross-section", boost::program_options::value<MyBLAS::NumericType>(), "= Removal cross-section  (+ve real)");
         boost::program_options::options_description files("Inputs/Outputs");
         files.add_options()(
             "input-parameter-json,i", boost::program_options::value<std::string>(), "= Path to input parameter JSON")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= Path to source-terms (,) CSV")(
             "output-results-json,o", boost::program_options::value<std::string>(), "= Path to output results JSON")(
             "flux-output-dir,f", boost::program_options::value<std::string>(), "= Path to computed flux (,)");
         boost::program_options::options_description methods("Solver Options");
         methods.add_options()
             ("use-LUP", "= Use LUP factorization")
             ("use-point-jacobi","= Use the Point-Jacobi method")
             ("use-SORJ", "= Use the SOR Jacobi method")
             ("use-gauss-seidel", "= Use the Gauss-Seidel method")
             ("use-SOR", "= Use the SOR method")
             ("use-SSOR", "= Use the symmetric SOR method")(
             "threshold,t", boost::program_options::value<MyBLAS::NumericType>(),"= convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<MyBLAS::NumericType>(), "= maximum iterations [n  ]")(
             "relaxation-factor,w", boost::program_options::value<MyBLAS::NumericType>(), "= SOR weight, typical   [0,2]");
         values.add(methods);
         values.add(files);
     }
References postprocess::methods.
buildInputArguments() [25/25]
void Parser::buildInputArguments (boost::program_options::options_description & values) inline override protected virtual
This function builds the input options for the program.
Returns
A boost::program_options::options_description object containing the description of the input options.
Implements CommandLine< OutLab12Inputs >.
{
         values.add_options()(
             ",a", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 1st dimension (+ve real)")(
             ",b", boost::program_options::value<MyBLAS::NumericType>(),"= Length of 2nd dimension (+ve real)")(
             ",m", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 1st dimension")(
             ",n", boost::program_options::value<MyBLAS::NumericType>(), "= Number of mesh-points in 2nd dimension")(
             ",D", boost::program_options::value<MyBLAS::NumericType>(), "= Diffusion coefficient D (+ve real)")(
             "cross-section", boost::program_options::value<MyBLAS::NumericType>(), "= Removal cross-section  (+ve real)");
         boost::program_options::options_description files("Inputs/Outputs");
         files.add_options()(
             "input-parameter-json,i", boost::program_options::value<std::string>(), "= Path to input parameter JSON")(
             "source-terms-csv,s", boost::program_options::value<std::string>(), "= Path to source-terms (,) CSV")(
             "output-results-json,o", boost::program_options::value<std::string>()->default_value("/dev/stdout"), "= Path to output results JSON")(
             "flux-output-dir,f", boost::program_options::value<std::string>(), "= Path to computed flux (,)");
         boost::program_options::options_description methods("Solver Options");
         methods.add_options()
             ("use-LUP", "= Use LUP factorization")
             ("use-point-jacobi","= Use the Point-Jacobi method")
             ("use-SORJ", "= Use the SOR Jacobi method")
             ("use-gauss-seidel", "= Use the Gauss-Seidel method")
             ("use-SOR", "= Use the SOR method")
             ("use-SSOR", "= Use the symmetric SOR method")(
             "threshold,t", boost::program_options::value<MyBLAS::NumericType>(),"= convergence threshold [ > 0]")(
             "max-iterations,k", boost::program_options::value<MyBLAS::NumericType>(), "= maximum iterations [n  ]")(
             "relaxation-factor,w", boost::program_options::value<MyBLAS::NumericType>(), "= SOR weight, typical   [0,2]");
         values.add(methods);
         values.add(files);
     }
References postprocess::methods.
buildInputs() [1/25]
void Parser::buildInputs (InLab10Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the output json path
         // TODO:: this should be wrapped in some path validated file write checker
         input.outputJSON = values["output-json"].as<std::string>();
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         input.constants = MyBLAS::Vector(constants);
         // read the coefficient matrix
         input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         if (!MyBLAS::isSquareMatrix(input.coefficients)) {
             std::cerr << "Error: Input coefficients matrix A not square, aborting.\n";
             exit(-1);
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         if (input.coefficients.getRows() != input.constants.size()) {
             std::cerr << "Error: Input constants vector 'b' not order n, aborting.\n";
             exit(-1);
         }
         input.n = input.coefficients.getRows();
         input.threshold = values["stopping-criterion"].as<long double>();
         input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.coefficients;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.constants;
         }
     }
References Input::coefficients, Input::constants, CommandLine< OutLab12Inputs >::getCurrentPrecision(), MyBLAS::Matrix< T >::getRows(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::max_iterations, Input::n, Input::outputJSON, CommandLine< OutLab12Inputs >::printLine(), readJSON(), MyBLAS::Vector< T >::size(), and Input::threshold.
buildInputs() [2/25]
void Parser::buildInputs (InLab11Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::System::Circuit(n, input.input.coefficients, input.input.constants, input.known_solution);
         } else {
             // read the constants
             input.input.constants = MyBLAS::Vector(MyBLAS::Vector(std::vector<long double>(inputMap["constants"])));
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Error: Input coefficients matrix A not square, aborting.\n";
             exit(-1);
         }
         if (input.input.coefficients.getRows() != input.input.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isDiagonallyDominant(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not diagonally dominant.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is diagonally dominant.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         if (input.input.coefficients.getRows() != input.input.constants.size()) {
             std::cerr << "Error: Input constants vector 'b' not order n, aborting.\n";
             exit(-1);
         }
         input.input.n = input.input.coefficients.getRows();
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, Input::input, MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, and readJSON().
buildInputs() [3/25]
void Parser::buildInputs (InLab12Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::Vector<MyBLAS::NumericType> b = Random::generate_vector<MyBLAS::NumericType>(input.input.coefficients.getRows());
             MyBLAS::System::Circuit(n, input.input.coefficients, b, input.known_solution);
         } else {
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square, aborting.\n";
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isDiagonallyDominant(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not diagonally dominant.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is diagonally dominant.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         input.input.n = input.input.coefficients.getRows();
         if (values["use-direct"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION);
         }
         if (values["use-rayleigh"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION);
         }
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.input.coefficients;
             printLine();
         }
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, CommandLine< OutLab12Inputs >::getCurrentPrecision(), Input::input, MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION, MyRelaxationMethod::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION, Input::methods, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [4/25]
void Parser::buildInputs (InLab6Inputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
values Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         inputs.constants = MyBLAS::Vector(constants);
         // read the coefficient matrix
         inputs.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         if (!MyBLAS::isSquareMatrix(inputs.coefficients)) {
             std::cerr << "Error: Input coefficients matrix A not square, aborting.\n";
             exit(-1);
         }
         if (inputs.coefficients.getRows() != inputs.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         // set input order n
         const auto orderFromInputMatrixDimensions = inputs.coefficients.getRows();
         if (!values.count("order")) {
             std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                       << "\n";
             inputs.n = orderFromInputMatrixDimensions;
         } else { // user provided some value for n, validate against input dimensions
             const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
             inputs.n = orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
             if (orderFromUser > orderFromInputMatrixDimensions) {
                 std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
             }
         }
         inputs.threshold = values["threshold"].as<long double>();
         inputs.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (values["use-point-jacobi"].as<bool>()) {
             inputs.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (values["use-gauss-seidel"].as<bool>()) {
             inputs.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
         if (values["use-SOR"].as<bool>()) {
             inputs.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
         }
         if (values["use-SSOR"].as<bool>()) {
             inputs.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
         }
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.coefficients;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.constants;
         }
     }
References CommandLine< OutLab12Inputs >::getCurrentPrecision(), process::inputs, MyBLAS::isSquareMatrix(), METHOD_GAUSS_SEIDEL, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SSOR, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [5/25]
void Parser::buildInputs (Input & ToFill, boost::program_options::variables_map & values) inline override protected virtual
Method to fill the inputs object based on the parsed command line arguments.
Parameters
ToFill A reference to the inputs object that will be filled.
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to fill the inputs object based on the parsed command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         input.n = static_cast<size_t>(values["num-points"].as<long double>());
         input.m = static_cast<size_t>(values["num-samples"].as<long double>());
         input.xData = values["x-points"].as<std::vector<long double>>();
         input.fxData = values["fx-points"].as<std::vector<long double>>();
     }
References Input::fxData, Input::m, Input::n, and Input::xData.
buildInputs() [6/25]
void Parser::buildInputs (Input & ToFill, boost::program_options::variables_map & values) inline override protected virtual
Method to fill the inputs object based on the parsed command line arguments.
Parameters
ToFill A reference to the inputs object that will be filled.
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to fill the inputs object based on the parsed command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         inputs.n = static_cast<size_t>(values["num-points"].as<long double>());
         inputs.m = static_cast<size_t>(values["num-samples"].as<long double>());
         inputs.xData = values["x-points"].as<std::vector<long double>>();
         inputs.fxData = values["fx-points"].as<std::vector<long double>>();
     }
References process::inputs.
buildInputs() [7/25]
void Parser::buildInputs (InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the output object with the provided values from the command line.
Parameters
inputs Reference to the object to be populated
values Reference to the boost::program_options::variables_map containing the command line values
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         inputs.constants = MyBLAS::Vector(constants);
         // read the upper matrix, add it to LU, and subtract identity matrix to remove double counting
         const auto lower = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["lower"]));
         const auto upper = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["upper"]));
         if (lower.getCols() != upper.getCols() || lower.getRows() != upper.getRows()) {
             std::cerr
                 << "Error: Input lower and upper triangular matrices do not have the same dimensions, aborting.\n";
             exit(-1);
         }
         if (lower.getCols() != upper.getRows()) {
             std::cerr << "Error: Input matrices not square, aborting.\n";
             exit(-1);
         }
         if (lower.getRows() != inputs.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         // set input order n
         const auto orderFromInputMatrixDimensions = lower.getRows();
         if (values["order"].defaulted()) {
             std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                       << "\n";
             inputs.n = orderFromInputMatrixDimensions;
         } else { // user provided some value for n, validate against input dimensions
             const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
             inputs.n = orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
             if (orderFromUser > orderFromInputMatrixDimensions) {
                 std::cerr << "Warning: Matrix order (n) is larger than input matrices, defaulting to lower value\n";
             }
         }
         const auto identity = MyBLAS::Matrix<long double>::eye(inputs.n);
         inputs.LU = lower + upper - identity;
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Lower Triangular Matrix (L):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << lower;
             printLine();
             std::cout << "Upper Triangular Matrix (U):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << upper;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.constants;
             printLine();
             printLine();
             std::cout << "LU Matrix:\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.LU;
         }
     }
References MyBLAS::Matrix< T >::eye(), CommandLine< OutLab12Inputs >::getCurrentPrecision(), process::inputs, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [8/25]
void Parser::buildInputs (InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
values Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         inputs.constants = MyBLAS::Vector(constants);
         // read the coefficient matrix
         inputs.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         if (inputs.coefficients.getRows() != inputs.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         // set input order n
         const auto orderFromInputMatrixDimensions = inputs.coefficients.getRows();
         if (values["order"].defaulted()) {
             std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                       << "\n";
             inputs.n = orderFromInputMatrixDimensions;
         } else { // user provided some value for n, validate against input dimensions
             const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
             inputs.n = orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
             if (orderFromUser > orderFromInputMatrixDimensions) {
                 std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
             }
         }
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.coefficients;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.constants;
         }
     }
References CommandLine< OutLab12Inputs >::getCurrentPrecision(), process::inputs, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [9/25]
void Parser::buildInputs (MatrixConstructParams & ToFill, boost::program_options::variables_map & values) inline override protected virtual
Method to fill the inputs object based on the parsed command line arguments.
Parameters
ToFill A reference to the inputs object that will be filled.
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to fill the inputs object based on the parsed command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         ToFill.k = values["scalar"].as<long double>();
         ToFill.M = static_cast<size_t>(values["m-rank"].as<long double>());
         ToFill.N = static_cast<size_t>(values["n-rank"].as<long double>());
         ToFill.J = static_cast<size_t>(values["j-rank"].as<long double>());
     }
References Input::J, Input::k, Input::M, and Input::N.
buildInputs() [10/25]
void Parser::buildInputs (MyBLAS::InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
values Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< MyBLAS::InputMatrices >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         inputs.constants = MyBLAS::Vector(constants);
         // read the upper matrix, add it to LU, and subtract identity matrix to remove double counting
         const auto lower = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["lower"]));
         const auto upper = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["upper"]));
         const auto permutation = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["permutation"]));
         if (!MyBLAS::isPermutationMatrix(permutation)) {
             std::cerr << "Error: Input matrix is not a valid permutation matrix, aborting.\n";
             exit(-1);
         }
         if (!MyBLAS::isUnitLowerTriangularMatrix(lower)) {
             std::cerr << "Error: Input matrix is not a valid unit lower triangular matrix, aborting.\n";
             exit(-1);
         }
         if (!MyBLAS::isUpperTriangularMatrix(upper)) {
             std::cerr << "Error: Input matrix is not a valid upper triangular matrix, aborting.\n";
             exit(-1);
         }
         if (lower.getCols() != upper.getCols() || lower.getRows() != upper.getRows()) {
             std::cerr
                 << "Error: Input lower and upper triangular matrices do not have the same dimensions, aborting.\n";
             exit(-1);
         }
         if (lower.getCols() != permutation.getCols() || lower.getRows() != permutation.getRows()) {
             std::cerr << "Error: Permutation and triangular matrices do not have the same dimensions, aborting.\n";
             exit(-1);
         }
         if (!MyBLAS::isSquareMatrix(lower) || !MyBLAS::isSquareMatrix(upper) || !MyBLAS::isSquareMatrix(permutation)) {
             std::cerr << "Error: Input matrices not square, aborting.\n";
             exit(-1);
         }
         if (lower.getRows() != inputs.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         // set input order n
         const auto orderFromInputMatrixDimensions = lower.getRows();
         if (values["order"].defaulted()) {
             std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                       << "\n";
             inputs.n = orderFromInputMatrixDimensions;
         } else { // user provided some value for n, validate against input dimensions
             const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
             inputs.n = orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
             if (orderFromUser > orderFromInputMatrixDimensions) {
                 std::cerr << "Warning: Matrix order (n) is larger than input matrices, defaulting to lower value\n";
             }
         }
         const auto identity = MyBLAS::Matrix<long double>::eye(inputs.n);
         inputs.LU = lower + upper - identity;
         inputs.permutation = permutation;
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Lower Triangular Matrix (L):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << lower;
             printLine();
             std::cout << "Upper Triangular Matrix (U):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << upper;
             printLine();
             std::cout << "Permutation Matrix (P):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.permutation;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.constants;
             printLine();
             std::cout << "LU Matrix:\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.LU;
             printLine();
         }
     }
References MyBLAS::Matrix< T >::eye(), CommandLine< OutLab12Inputs >::getCurrentPrecision(), process::inputs, MyBLAS::isPermutationMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [11/25]
void Parser::buildInputs (MyBLAS::InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
values Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< MyBLAS::InputMatrices >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         readJSON(values["input-json"].as<std::string>(), inputMap);
         // read the constants
         MyBLAS::Vector<long double> constants = MyBLAS::Vector(std::vector<long double>(inputMap["constants"]));
         inputs.constants = MyBLAS::Vector(constants);
         // read the coefficient matrix
         inputs.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         if (inputs.coefficients.getRows() != inputs.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         // set input order n
         const auto orderFromInputMatrixDimensions = inputs.coefficients.getRows();
         if (values["order"].defaulted()) {
             std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                       << "\n";
             inputs.n = orderFromInputMatrixDimensions;
         } else { // user provided some value for n, validate against input dimensions
             const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
             inputs.n = orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
             if (orderFromUser > orderFromInputMatrixDimensions) {
                 std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
             }
         }
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.coefficients;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << inputs.constants;
         }
     }
References CommandLine< OutLab12Inputs >::getCurrentPrecision(), process::inputs, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [12/25]
void Parser::buildInputs (NewtonCotesInputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the NewtonCotesInputs object with the provided values from the command line.
This function takes the values provided by the user through the command line and populates the NewtonCotesInputs object accordingly. It also handles the case where the start value is greater than the stop value by flipping the interval.
Parameters
inputs Reference to the NewtonCotesInputs object to be populated
values Reference to the boost::program_options::variables_map containing the command line values
Implements CommandLine< OutLab12Inputs >.
{
         inputs.a = static_cast<long double>(values["start"].as<long double>());
         inputs.b = static_cast<long double>(values["stop"].as<long double>());
         inputs.flip_integral = inputs.a > inputs.b;
         // flip interval if a > b
         if (inputs.flip_integral) {
             auto temp = inputs.b;
             inputs.b = inputs.a;
             inputs.a = temp;
         }
         inputs.m = static_cast<size_t>(values["num-intervals"].as<long double>());
         inputs.integral_types = {};
         if (values["use-trapezoidal"].as<bool>()) {
             inputs.integral_types.insert(RULE_COMPOSITE_TRAPEZOIDAL);
         }
         if (values["use-simpsons"].as<bool>()) {
             inputs.integral_types.insert(RULE_COMPOSITE_SIMPSONS);
         }
         if (values["use-gaussian-quadratures"].as<bool>()) {
             inputs.integral_types.insert(RULE_GAUSSIAN_QUADRATURE);
         }
     }
References process::inputs, RULE_COMPOSITE_SIMPSONS, RULE_COMPOSITE_TRAPEZOIDAL, and RULE_GAUSSIAN_QUADRATURE.
buildInputs() [13/25]
void Parser::buildInputs (NewtonCotesInputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
Builds the NewtonCotesInputs object with the provided values from the command line.
This function takes the values provided by the user through the command line and populates the NewtonCotesInputs object accordingly. It also handles the case where the start value is greater than the stop value by flipping the interval.
Parameters
inputs Reference to the NewtonCotesInputs object to be populated
values Reference to the boost::program_options::variables_map containing the command line values
Implements CommandLine< OutLab12Inputs >.
{
         inputs.a = static_cast<long double>(values["start"].as<long double>());
         inputs.b = static_cast<long double>(values["stop"].as<long double>());
         inputs.flip_integral = inputs.a > inputs.b;
         // flip interval if a > b
         if (inputs.flip_integral) {
             auto temp = inputs.b;
             inputs.b = inputs.a;
             inputs.a = temp;
         }
         inputs.m = static_cast<size_t>(values["num-intervals"].as<long double>());
         inputs.n = !values["num-quadrature-points"].empty()
                        ? static_cast<size_t>(values["num-quadrature-points"].as<long double>())
                        : 0;
         inputs.integral_types = {};
         if (values["use-trapezoidal"].as<bool>()) {
             inputs.integral_types.insert(RULE_COMPOSITE_TRAPEZOIDAL);
         }
         if (values["use-simpsons"].as<bool>()) {
             inputs.integral_types.insert(RULE_COMPOSITE_SIMPSONS);
         }
         if (values["use-gaussian-quadratures"].as<bool>()) {
             inputs.integral_types.insert(RULE_GAUSSIAN_QUADRATURE);
         }
     }
References process::inputs, RULE_COMPOSITE_SIMPSONS, RULE_COMPOSITE_TRAPEZOIDAL, and RULE_GAUSSIAN_QUADRATURE.
buildInputs() [14/25]
void Parser::buildInputs (OutLab10Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::System::Circuit(n, input.input.coefficients, input.input.constants, input.known_solution);
         } else {
             // read the constants
             input.input.constants = MyBLAS::Vector(MyBLAS::Vector(std::vector<long double>(inputMap["constants"])));
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Error: Input coefficients matrix A not square, aborting.\n";
             exit(-1);
         }
         if (input.input.coefficients.getRows() != input.input.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isDiagonallyDominant(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not diagonally dominant.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is diagonally dominant.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         if (input.input.coefficients.getRows() != input.input.constants.size()) {
             std::cerr << "Error: Input constants vector 'b' not order n, aborting.\n";
             exit(-1);
         }
         input.input.n = input.input.coefficients.getRows();
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, Input::input, MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, and readJSON().
buildInputs() [15/25]
void Parser::buildInputs (OutLab11Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::Vector<MyBLAS::NumericType> b = Random::generate_vector<MyBLAS::NumericType>(input.input.coefficients.getRows());
             MyBLAS::System::Circuit(n, input.input.coefficients, b, input.known_solution);
         } else {
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square, aborting.\n";
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isDiagonallyDominant(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not diagonally dominant.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is diagonally dominant.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         input.input.n = input.input.coefficients.getRows();
         if (values["use-direct"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION);
         }
         if (values["use-rayleigh"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION);
         }
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.input.coefficients;
             printLine();
         }
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, CommandLine< OutLab12Inputs >::getCurrentPrecision(), Input::input, MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION, MyRelaxationMethod::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION, Input::methods, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, CommandLine< OutLab12Inputs >::printLine(), and readJSON().
buildInputs() [16/25]
void Parser::buildInputs (OutLab12Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::Vector<MyBLAS::NumericType> b = Random::generate_vector<MyBLAS::NumericType>(input.input.coefficients.getRows());
             MyBLAS::System::Circuit(n, input.input.coefficients, b, input.known_solution);
         } else {
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square, aborting.\n";
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A not square.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is square.\n";
         }
         if (!MyBLAS::isSymmetricMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not symmetric.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is symmetric.\n";
         }
         if (!MyBLAS::isDiagonallyDominant(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not diagonally dominant.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is diagonally dominant.\n";
         }
         if (!MyBLAS::isPositiveDefiniteMatrix(input.input.coefficients)) {
             std::cerr << "Warning: Input coefficients matrix A is not positive definite.\n";
         } else if (!values.count("quiet")) {
             std::cout << "Input coefficients matrix A is positive definite.\n";
         }
         input.input.n = input.input.coefficients.getRows();
         if (values["use-inverse"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::METHOD_INVERSE_POWER_ITERATION);
             input.input.setEigenvalue(static_cast<MyBLAS::NumericType>(values["lambda"].as<long double>()));
         }
         if (values["use-direct"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION);
         }
         if (values["use-rayleigh"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION);
         }
         if (!values.count("quiet")) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.input.coefficients;
             printLine();
         }
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, CommandLine< OutLab12Inputs >::getCurrentPrecision(), Input::input, MyBLAS::isDiagonallyDominant(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isSymmetricMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION, MyRelaxationMethod::METHOD_INVERSE_POWER_ITERATION, MyRelaxationMethod::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION, Input::methods, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, CommandLine< OutLab12Inputs >::printLine(), readJSON(), and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setEigenvalue().
buildInputs() [17/25]
void Parser::buildInputs (OutLab6Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
values Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         const bool generate = values.count("generate");
         if (generate) {
             if (!values.count("order")) {
                 std::cerr << "Error: User did not provide matrix order n, aborting\n";
                 exit(-1);
             }
             auto n = static_cast<size_t>(values["order"].as<long double>());
             input.input.n = n;
             MyBLAS::System::Circuit(n, input.input.coefficients, input.input.constants, input.known_solution);
         } else {
             // read the constants
             input.input.constants = MyBLAS::Vector(MyBLAS::Vector(std::vector<long double>(inputMap["constants"])));
             // read the coefficient matrix
             input.input.coefficients = MyBLAS::Matrix(std::vector<std::vector<long double>>(inputMap["coefficients"]));
         }
         if (!MyBLAS::isSquareMatrix(input.input.coefficients)) {
             std::cerr << "Error: Input coefficients matrix A not square, aborting.\n";
             exit(-1);
         }
         if (input.input.coefficients.getRows() != input.input.constants.size()) {
             std::cerr << "Error: Input constants vector not order n, aborting.\n";
             exit(-1);
         }
         if (!generate) {
             // set input order n
             const auto orderFromInputMatrixDimensions = input.input.coefficients.getRows();
             if (!values.count("order")) {
                 std::cout << "Reading matrix order (n) from input matrix dimensions: " << orderFromInputMatrixDimensions
                           << "\n";
                 input.input.n = orderFromInputMatrixDimensions;
             } else { // user provided some value for n, validate against input dimensions
                 const auto orderFromUser = static_cast<size_t>(values["order"].as<long double>());
                 input.input.n =
                     orderFromUser > orderFromInputMatrixDimensions ? orderFromInputMatrixDimensions : orderFromUser;
                 if (orderFromUser > orderFromInputMatrixDimensions) {
                     std::cerr << "Warning: Matrix order (n) is larger than input matrix, defaulting to lower value\n";
                 }
             }
         }
         input.input.convergence_threshold = values["threshold"].as<long double>();
         input.input.max_iterations = static_cast<size_t>(values["max-iterations"].as<long double>());
         if (values["use-LUP"].as<bool>()) {
             input.methods.insert(MyFactorizationMethod::Type::METHOD_LUP);
         }
         if (values["use-point-jacobi"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (values["use-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
         if (values["use-SOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
         }
         if (values["use-SORJ"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SORPJ);
         }
         if (values["use-SSOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
         }
         if (values.count("relaxation-factor")) {
             input.input.relaxation_factor = values["relaxation-factor"].as<long double>();
         }
         // print the matrices since we are in verbose mode.
         if (!values.count("quiet") && input.input.n <= 16) {
             const auto precision = getCurrentPrecision();
             printLine();
             std::cout << "Coefficient Matrix (A):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.input.coefficients;
             printLine();
             std::cout << "Constants Vector (b):\n";
             printLine();
             std::cout << std::setprecision(static_cast<int>(precision)) << input.input.constants;
         }
     }
References MyBLAS::System::Circuit(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::convergence_threshold, CommandLine< OutLab12Inputs >::getCurrentPrecision(), Input::input, MyBLAS::isSquareMatrix(), Input::known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, METHOD_GAUSS_SEIDEL, METHOD_LUP, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SORPJ, MyRelaxationMethod::METHOD_SSOR, Input::methods, n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, CommandLine< OutLab12Inputs >::printLine(), readJSON(), and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::relaxation_factor.
buildInputs() [18/25]
void Parser::buildInputs (OutLab7Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         input.n = static_cast<size_t>(values["n"].as<long double>());
         input.outputJSON = values["output-json"].as<std::string>();
     }
References Input::n, Input::outputJSON, and readJSON().
buildInputs() [19/25]
void Parser::buildInputs (OutLab7Inputs & input, boost::program_options::variables_map & values) inline override protected virtual
Builds the inputs.
Implements CommandLine< OutLab12Inputs >.
{
         // first, read the input file into a json map
         nlohmann::json inputMap;
         if (values.count("input-json")) {
             readJSON(values["input-json"].as<std::string>(), inputMap);
         }
         input.n = static_cast<size_t>(values["n"].as<long double>());
         input.outputJSON = values["output-json"].as<std::string>();
     }
References Input::n, Input::outputJSON, and readJSON().
buildInputs() [20/25]
void Parser::buildInputs (SolverInputs & input, boost::program_options::variables_map & map) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
map Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< SolverInputs >.
{
         input.a = map["a"].as<long double>();
         input.b = map["b"].as<long double>();
         input.m = static_cast<size_t>(map["m"].as<long double>());
         input.n = static_cast<size_t>(map["n"].as<long double>());
         input.diffusion_coefficient = map["D"].as<long double>();
         input.macroscopic_removal_cross_section = map["cross-section"].as<long double>();
         calculate_mesh_spacings(input); // calculate delta and gamma
         const auto sourceTermsFilepath = map["source-terms-csv"].as<std::string>();
         readCSVRowWiseNoHeaders<long double>(sourceTermsFilepath, input.sources);
         if (input.sources.getRows() < 1 || input.sources.getCols() < 1) {
             std::cerr << "ERROR: No Source terms matrix dimension (rows=" << input.sources.getRows()
                       << ", columns=" << input.sources.getCols() << ")  can be less than 1!\n";
             std::cerr << "ABORTING.\n";
             exit(-1);
         }
         // 1st dimension internal nodes
         if (input.m != input.sources.getRows()) {
             input.m = input.sources.getRows();
             std::cerr << "WARNING: Source terms matrix rows != m, overriding m to " << input.m << std::endl;
         }
         // 2nd dimension internal nodes
         if (input.n != input.sources.getCols()) {
             input.n = input.sources.getCols();
             std::cerr << "WARNING: Source terms matrix columns != n, overriding n to " << input.n << std::endl;
         }
         if (!map.count("quiet")) {
             // list the parameters
             CommandLine::printLine();
             std::cout << std::setw(44) << "Intermediates\n";
             CommandLine::printLine();
             std::cout << "\tMesh spacing in the 1st dimension,     : " << input.delta << "\n";
             std::cout << "\tMesh spacing in the 2nd dimension,     : " << input.gamma << "\n";
             CommandLine::printLine();
             std::cout << "Source terms (,):\n";
             CommandLine::printLine();
             std::cout << input.sources;
             CommandLine::printLine();
         }
     }
References calculate_mesh_spacings(), and CommandLine< InputType >::printLine().
buildInputs() [21/25]
void Parser::buildInputs (SolverInputs & input, boost::program_options::variables_map & map) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
map Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< SolverInputs >.
{
         input.diffusionParams
             .setA(map["a"].as<MyBLAS::NumericType>())
             .setB(map["b"].as<MyBLAS::NumericType>())
             .setM(static_cast<size_t>(map["m"].as<MyBLAS::NumericType>()))
             .setN(static_cast<size_t>(map["n"].as<MyBLAS::NumericType>()))
             .setDiffusionCoefficient(map["D"].as<MyBLAS::NumericType>())
             .setMacroscopicRemovalCrossSection(map["cross-section"].as<MyBLAS::NumericType>());
         const auto sourceTermsFilepath = map["source-terms-csv"].as<std::string>();
         readCSVRowWiseNoHeaders<MyBLAS::NumericType>(sourceTermsFilepath, input.sources);
         input.fluxOutputDirectory = map["flux-output-dir"].as<std::string>();
         if (input.sources.getRows() < 1 || input.sources.getCols() < 1) {
             std::cerr << "ERROR: No Source terms matrix dimension (rows=" << input.sources.getRows()
                       << ", columns=" << input.sources.getCols() << ")  can be less than 1!\n";
             std::cerr << "ABORTING.\n";
             exit(-1);
         }
         // 1st dimension internal nodes
         if (input.diffusionParams.getM() != input.sources.getRows()) {
             input.diffusionParams.setM(input.sources.getRows());
             std::cerr << "WARNING: Source terms matrix rows != m, overriding m to " << input.diffusionParams.getM() << std::endl;
         }
         // 2nd dimension internal nodes
         if (input.diffusionParams.getN() != input.sources.getCols()) {
             input.diffusionParams.setN(input.sources.getCols());
             std::cerr << "WARNING: Source terms matrix columns != n, overriding n to " << input.diffusionParams.getN() << std::endl;
         }
         input.solverParams.convergence_threshold = map["threshold"].as<MyBLAS::NumericType>();
         input.solverParams.max_iterations = static_cast<size_t>(map["max-iterations"].as<MyBLAS::NumericType>());
         input.solverParams.n = input.diffusionParams.getM() * input.diffusionParams.getN();
         if (map["use-LUP"].as<bool>()) {
             input.methods.insert(MyFactorizationMethod::Type::METHOD_LUP);
         }
         if (map["use-point-jacobi"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (map["use-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
         if (map["use-SOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
         }
         if (map["use-SORJ"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SORPJ);
         }
         if (map["use-SSOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
         }
         if (map.count("relaxation-factor")) {
             input.solverParams.relaxation_factor = map["relaxation-factor"].as<MyBLAS::NumericType>();
         }
         if (map.count("bench")) {
             input.numRuns = map.count("bench-runs") ? static_cast<size_t>(map["bench-runs"].as<long double>()) : 1;
             input.timeout = map.count("bench-timeout") ? map["bench-timeout"].as<long double>() : 0;
         } else {
             input.numRuns = 1;
             input.timeout = 0;
         }
         if (!map.count("quiet")) {
             // list the parameters
             CommandLine::printLine();
             std::cout << std::setw(44) << "Intermediates\n";
             CommandLine::printLine();
             std::cout << "\tMesh spacing in the 1st dimension,     : " << input.diffusionParams.getDelta() << "\n";
             std::cout << "\tMesh spacing in the 2nd dimension,     : " << input.diffusionParams.getGamma() << "\n";
             CommandLine::printLine();
             std::cout << "Source terms (,):\n";
             CommandLine::printLine();
             std::cout << input.sources;
             CommandLine::printLine();
         }
     }
References METHOD_GAUSS_SEIDEL, METHOD_LUP, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SORPJ, MyRelaxationMethod::METHOD_SSOR, and CommandLine< InputType >::printLine().
buildInputs() [22/25]
void Parser::buildInputs (SolverInputs & input, boost::program_options::variables_map & map) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
map Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< SolverInputs >.
{
         input.diffusionParams
             .setA(map["a"].as<MyBLAS::NumericType>())
             .setB(map["b"].as<MyBLAS::NumericType>())
             .setM(static_cast<size_t>(map["m"].as<MyBLAS::NumericType>()))
             .setN(static_cast<size_t>(map["n"].as<MyBLAS::NumericType>()))
             .setDiffusionCoefficient(map["D"].as<MyBLAS::NumericType>())
             .setMacroscopicRemovalCrossSection(map["cross-section"].as<MyBLAS::NumericType>());
         const auto sourceTermsFilepath = map["source-terms-csv"].as<std::string>();
         readCSVRowWiseNoHeaders<MyBLAS::NumericType>(sourceTermsFilepath, input.sources);
         input.fluxOutputDirectory = map["flux-output-dir"].as<std::string>();
         if (input.sources.getRows() < 1 || input.sources.getCols() < 1) {
             std::cerr << "ERROR: No Source terms matrix dimension (rows=" << input.sources.getRows()
                       << ", columns=" << input.sources.getCols() << ")  can be less than 1!\n";
             std::cerr << "ABORTING.\n";
             exit(-1);
         }
         // 1st dimension internal nodes
         if (input.diffusionParams.getM() != input.sources.getRows()) {
             input.diffusionParams.setM(input.sources.getRows());
             std::cerr << "WARNING: Source terms matrix rows != m, overriding m to " << input.diffusionParams.getM() << std::endl;
         }
         // 2nd dimension internal nodes
         if (input.diffusionParams.getN() != input.sources.getCols()) {
             input.diffusionParams.setN(input.sources.getCols());
             std::cerr << "WARNING: Source terms matrix columns != n, overriding n to " << input.diffusionParams.getN() << std::endl;
         }
         input.solverParams.convergence_threshold = map["threshold"].as<MyBLAS::NumericType>();
         input.solverParams.max_iterations = static_cast<size_t>(map["max-iterations"].as<MyBLAS::NumericType>());
         input.solverParams.n = input.diffusionParams.getM() * input.diffusionParams.getN();
         if (map["use-LUP"].as<bool>()) {
             input.methods.insert(MyFactorizationMethod::Type::METHOD_LUP);
         }
         if (map["use-point-jacobi"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (map["use-SORPJ"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SORPJ);
         }
         if (map["use-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
         if (map["use-symmetric-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SYMMETRIC_GAUSS_SEIDEL);
         }
         if (map["use-SOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
         }
         if (map["use-SSOR"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
         }
         if (map.count("relaxation-factor")) {
             input.solverParams.relaxation_factor = map["relaxation-factor"].as<MyBLAS::NumericType>();
         }
         if (map.count("bench")) {
             input.numRuns = map.count("bench-runs") ? static_cast<size_t>(map["bench-runs"].as<long double>()) : 1;
             input.timeout = map.count("bench-timeout") ? map["bench-timeout"].as<long double>() : 0;
         } else {
             input.numRuns = 1;
             input.timeout = 0;
         }
         if (!map.count("quiet")) {
             // list the parameters
             CommandLine::printLine();
             std::cout << std::setw(44) << "Intermediates\n";
             CommandLine::printLine();
             std::cout << "\tMesh spacing in the 1st dimension,     : " << input.diffusionParams.getDelta() << "\n";
             std::cout << "\tMesh spacing in the 2nd dimension,     : " << input.diffusionParams.getGamma() << "\n";
             CommandLine::printLine();
             std::cout << "Source terms (,):\n";
             CommandLine::printLine();
             std::cout << input.sources;
             CommandLine::printLine();
         }
     }
References METHOD_GAUSS_SEIDEL, METHOD_LUP, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SORPJ, MyRelaxationMethod::METHOD_SSOR, MyRelaxationMethod::METHOD_SYMMETRIC_GAUSS_SEIDEL, and CommandLine< InputType >::printLine().
buildInputs() [23/25]
void Parser::buildInputs (SolverInputs & input, boost::program_options::variables_map & map) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
map Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< SolverInputs >.
{
         input.diffusionParams
             .setA(map["a"].as<MyBLAS::NumericType>())
             .setB(map["b"].as<MyBLAS::NumericType>())
             .setM(static_cast<size_t>(map["m"].as<MyBLAS::NumericType>()))
             .setN(static_cast<size_t>(map["n"].as<MyBLAS::NumericType>()))
             .setDiffusionCoefficient(map["D"].as<MyBLAS::NumericType>())
             .setMacroscopicRemovalCrossSection(map["cross-section"].as<MyBLAS::NumericType>());
         const auto sourceTermsFilepath = map["source-terms-csv"].as<std::string>();
         readCSVRowWiseNoHeaders<MyBLAS::NumericType>(sourceTermsFilepath, input.sources);
         input.fluxOutputDirectory = map["flux-output-dir"].as<std::string>();
         if (input.sources.getRows() < 1 || input.sources.getCols() < 1) {
             std::cerr << "ERROR: No Source terms matrix dimension (rows=" << input.sources.getRows()
                       << ", columns=" << input.sources.getCols() << ")  can be less than 1!\n";
             std::cerr << "ABORTING.\n";
             exit(-1);
         }
         // 1st dimension internal nodes
         if (input.diffusionParams.getM() != input.sources.getRows()) {
             input.diffusionParams.setM(input.sources.getRows());
             std::cerr << "WARNING: Source terms matrix rows != m, overriding m to " << input.diffusionParams.getM() << std::endl;
         }
         // 2nd dimension internal nodes
         if (input.diffusionParams.getN() != input.sources.getCols()) {
             input.diffusionParams.setN(input.sources.getCols());
             std::cerr << "WARNING: Source terms matrix columns != n, overriding n to " << input.diffusionParams.getN() << std::endl;
         }
         input.solverParams.convergence_threshold = map["threshold"].as<MyBLAS::NumericType>();
         input.solverParams.max_iterations = static_cast<size_t>(map["max-iterations"].as<MyBLAS::NumericType>());
         input.solverParams.n = input.diffusionParams.getM() * input.diffusionParams.getN();
 //        if (map["use-LUP"].as<bool>()) {
 //            input.methods.insert(MyFactorizationMethod::Type::METHOD_LUP);
 //        }
         if (map["use-point-jacobi"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (map["use-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
 //
 //        if (map["use-SOR"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
 //        }
 //
 //        if (map["use-SORJ"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SORPJ);
 //        }
 //
 //        if (map["use-SSOR"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
 //        }
         if (map.count("relaxation-factor")) {
             input.solverParams.relaxation_factor = map["relaxation-factor"].as<MyBLAS::NumericType>();
         }
         if (map.count("bench")) {
             input.numRuns = map.count("bench-runs") ? static_cast<size_t>(map["bench-runs"].as<long double>()) : 1;
             input.timeout = map.count("bench-timeout") ? map["bench-timeout"].as<long double>() : 0;
         } else {
             input.numRuns = 1;
             input.timeout = 0;
         }
         if (!map.count("quiet")) {
             // list the parameters
             CommandLine::printLine();
             std::cout << std::setw(44) << "Intermediates\n";
             CommandLine::printLine();
             std::cout << "\tMesh spacing in the 1st dimension,     : " << input.diffusionParams.getDelta() << "\n";
             std::cout << "\tMesh spacing in the 2nd dimension,     : " << input.diffusionParams.getGamma() << "\n";
             CommandLine::printLine();
             //std::cout << "Source terms (,):\n";
             CommandLine::printLine();
             //std::cout << input.sources;
             CommandLine::printLine();
         }
     }
References METHOD_GAUSS_SEIDEL, METHOD_POINT_JACOBI, and CommandLine< InputType >::printLine().
buildInputs() [24/25]
void Parser::buildInputs (SolverInputs & input, boost::program_options::variables_map & map) inline override protected virtual
Builds the input matrices for the MyBLAS library from a JSON file.
This function reads the input JSON file and extracts the coefficient matrix and constants vector. It also validates the dimensions of the input matrices and sets the order of the system. If the verbose mode is enabled, it prints the input matrices.
Parameters
inputs Reference to a MyBLAS::InputMatrices object to store the input matrices.
map Reference to a boost::program_options::variables_map object containing the command line arguments.
Implements CommandLine< SolverInputs >.
{
         input.diffusionParams
             .setA(map["a"].as<MyBLAS::NumericType>())
             .setB(map["b"].as<MyBLAS::NumericType>())
             .setM(static_cast<size_t>(map["m"].as<MyBLAS::NumericType>()))
             .setN(static_cast<size_t>(map["n"].as<MyBLAS::NumericType>()))
             .setDiffusionCoefficient(map["D"].as<MyBLAS::NumericType>())
             .setMacroscopicRemovalCrossSection(map["cross-section"].as<MyBLAS::NumericType>());
         const auto sourceTermsFilepath = map["source-terms-csv"].as<std::string>();
         readCSVRowWiseNoHeaders<MyBLAS::NumericType>(sourceTermsFilepath, input.sources);
         input.fluxOutputDirectory = map["flux-output-dir"].as<std::string>();
         if (input.sources.getRows() < 1 || input.sources.getCols() < 1) {
             std::cerr << "ERROR: No Source terms matrix dimension (rows=" << input.sources.getRows()
                       << ", columns=" << input.sources.getCols() << ")  can be less than 1!\n";
             std::cerr << "ABORTING.\n";
             exit(-1);
         }
         // 1st dimension internal nodes
         if (input.diffusionParams.getM() != input.sources.getRows()) {
             input.diffusionParams.setM(input.sources.getRows());
             std::cerr << "WARNING: Source terms matrix rows != m, overriding m to " << input.diffusionParams.getM() << std::endl;
         }
         // 2nd dimension internal nodes
         if (input.diffusionParams.getN() != input.sources.getCols()) {
             input.diffusionParams.setN(input.sources.getCols());
             std::cerr << "WARNING: Source terms matrix columns != n, overriding n to " << input.diffusionParams.getN() << std::endl;
         }
         input.solverParams.convergence_threshold = map["threshold"].as<MyBLAS::NumericType>();
         input.solverParams.max_iterations = static_cast<size_t>(map["max-iterations"].as<MyBLAS::NumericType>());
         input.solverParams.n = input.diffusionParams.getM() * input.diffusionParams.getN();
 //        if (map["use-LUP"].as<bool>()) {
 //            input.methods.insert(MyFactorizationMethod::Type::METHOD_LUP);
 //        }
         if (map["use-point-jacobi"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_POINT_JACOBI);
         }
         if (map["use-gauss-seidel"].as<bool>()) {
             input.methods.insert(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL);
         }
 //
 //        if (map["use-SOR"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SOR);
 //        }
 //
 //        if (map["use-SORJ"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SORPJ);
 //        }
 //
 //        if (map["use-SSOR"].as<bool>()) {
 //            input.methods.insert(MyRelaxationMethod::Type::METHOD_SSOR);
 //        }
         if (map.count("relaxation-factor")) {
             input.solverParams.relaxation_factor = map["relaxation-factor"].as<MyBLAS::NumericType>();
         }
         if (map.count("bench")) {
             input.numRuns = map.count("bench-runs") ? static_cast<size_t>(map["bench-runs"].as<long double>()) : 1;
             input.timeout = map.count("bench-timeout") ? map["bench-timeout"].as<long double>() : 0;
         } else {
             input.numRuns = 1;
             input.timeout = 0;
         }
         if (!map.count("quiet")) {
             // list the parameters
             CommandLine::printLine();
             std::cout << std::setw(44) << "Intermediates\n";
             CommandLine::printLine();
             std::cout << "\tMesh spacing in the 1st dimension,     : " << input.diffusionParams.getDelta() << "\n";
             std::cout << "\tMesh spacing in the 2nd dimension,     : " << input.diffusionParams.getGamma() << "\n";
             CommandLine::printLine();
             //std::cout << "Source terms (,):\n";
             CommandLine::printLine();
             //std::cout << input.sources;
             CommandLine::printLine();
         }
     }
References METHOD_GAUSS_SEIDEL, METHOD_POINT_JACOBI, and CommandLine< InputType >::printLine().
buildInputs() [25/25]
void Parser::buildInputs (TaylorSeriesInputs & ToFill, boost::program_options::variables_map & values) inline override protected virtual
Method to fill the inputs object based on the parsed command line arguments.
Parameters
ToFill A reference to the inputs object that will be filled.
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to fill the inputs object based on the parsed command line arguments.
Implements CommandLine< OutLab12Inputs >.
{
         input.x = values["angle"].as<long double>();
         input.target_threshold = values["convergence-threshold"].as<long double>();
         input.N = static_cast<size_t>(std::ceil(values["iterations"].as<long double>()));
     }
References Input::N, Input::target_threshold, and Input::x.
getArguments() [1/16]
boost::program_options::variables_map& CommandLine< OutLab12Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [2/16]
boost::program_options::variables_map& CommandLine< OutLab6Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [3/16]
boost::program_options::variables_map& CommandLine< InLab12Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [4/16]
boost::program_options::variables_map& CommandLine< SolverInputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [5/16]
boost::program_options::variables_map& CommandLine< LagrangePolynomialInputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [6/16]
boost::program_options::variables_map& CommandLine< NewtonCotesInputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [7/16]
boost::program_options::variables_map& CommandLine< InputMatrices >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [8/16]
boost::program_options::variables_map& CommandLine< MyBLAS::InputMatrices >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [9/16]
boost::program_options::variables_map& CommandLine< InLab6Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [10/16]
boost::program_options::variables_map& CommandLine< TaylorSeriesInputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [11/16]
boost::program_options::variables_map& CommandLine< OutLab7Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [12/16]
boost::program_options::variables_map& CommandLine< MatrixConstructParams >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [13/16]
boost::program_options::variables_map& CommandLine< InLab10Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [14/16]
boost::program_options::variables_map& CommandLine< OutLab10Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [15/16]
boost::program_options::variables_map& CommandLine< OutLab11Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArguments() [16/16]
boost::program_options::variables_map& CommandLine< InLab11Inputs >::getArguments () inline inherited
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [1/16]
boost::program_options::variables_map CommandLine< OutLab12Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [2/16]
boost::program_options::variables_map CommandLine< OutLab6Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [3/16]
boost::program_options::variables_map CommandLine< InLab12Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [4/16]
boost::program_options::variables_map CommandLine< SolverInputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [5/16]
boost::program_options::variables_map CommandLine< LagrangePolynomialInputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [6/16]
boost::program_options::variables_map CommandLine< NewtonCotesInputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [7/16]
boost::program_options::variables_map CommandLine< InputMatrices >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [8/16]
boost::program_options::variables_map CommandLine< MyBLAS::InputMatrices >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [9/16]
boost::program_options::variables_map CommandLine< InLab6Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [10/16]
boost::program_options::variables_map CommandLine< TaylorSeriesInputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [11/16]
boost::program_options::variables_map CommandLine< OutLab7Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [12/16]
boost::program_options::variables_map CommandLine< MatrixConstructParams >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [13/16]
boost::program_options::variables_map CommandLine< InLab10Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [14/16]
boost::program_options::variables_map CommandLine< OutLab10Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [15/16]
boost::program_options::variables_map CommandLine< OutLab11Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getArgumentsMap() [16/16]
boost::program_options::variables_map CommandLine< InLab11Inputs >::getArgumentsMap () inline inherited
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
getCmdArgs() [1/16]
const CommandLineArgs& CommandLine< OutLab6Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [2/16]
const CommandLineArgs& CommandLine< InLab12Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [3/16]
const CommandLineArgs& CommandLine< SolverInputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [4/16]
const CommandLineArgs& CommandLine< OutLab12Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [5/16]
const CommandLineArgs& CommandLine< LagrangePolynomialInputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [6/16]
const CommandLineArgs& CommandLine< NewtonCotesInputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [7/16]
const CommandLineArgs& CommandLine< InputMatrices >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [8/16]
const CommandLineArgs& CommandLine< MyBLAS::InputMatrices >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [9/16]
const CommandLineArgs& CommandLine< InLab6Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [10/16]
const CommandLineArgs& CommandLine< TaylorSeriesInputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [11/16]
const CommandLineArgs& CommandLine< OutLab7Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [12/16]
const CommandLineArgs& CommandLine< MatrixConstructParams >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [13/16]
const CommandLineArgs& CommandLine< InLab10Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [14/16]
const CommandLineArgs& CommandLine< OutLab10Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [15/16]
const CommandLineArgs& CommandLine< OutLab11Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCmdArgs() [16/16]
const CommandLineArgs& CommandLine< InLab11Inputs >::getCmdArgs () const inline inherited
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
getCurrentPrecision() [1/16]
int CommandLine< InLab11Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [2/16]
int CommandLine< OutLab12Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [3/16]
int CommandLine< OutLab6Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [4/16]
int CommandLine< SolverInputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [5/16]
int CommandLine< LagrangePolynomialInputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [6/16]
int CommandLine< NewtonCotesInputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [7/16]
int CommandLine< InputMatrices >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [8/16]
int CommandLine< MyBLAS::InputMatrices >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [9/16]
int CommandLine< InLab6Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [10/16]
int CommandLine< TaylorSeriesInputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [11/16]
int CommandLine< OutLab7Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [12/16]
int CommandLine< InLab12Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [13/16]
int CommandLine< MatrixConstructParams >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [14/16]
int CommandLine< InLab10Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [15/16]
int CommandLine< OutLab10Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getCurrentPrecision() [16/16]
int CommandLine< OutLab11Inputs >::getCurrentPrecision () inline inherited
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
getInputs() [1/16]
InLab11Inputs & CommandLine< InLab11Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [2/16]
OutLab12Inputs & CommandLine< OutLab12Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [3/16]
OutLab6Inputs & CommandLine< OutLab6Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [4/16]
InLab12Inputs & CommandLine< InLab12Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [5/16]
SolverInputs & CommandLine< SolverInputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [6/16]
LagrangePolynomialInputs & CommandLine< LagrangePolynomialInputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [7/16]
NewtonCotesInputs & CommandLine< NewtonCotesInputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [8/16]
InputMatrices & CommandLine< InputMatrices >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [9/16]
MyBLAS::InputMatrices & CommandLine< MyBLAS::InputMatrices >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [10/16]
InLab6Inputs & CommandLine< InLab6Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [11/16]
TaylorSeriesInputs & CommandLine< TaylorSeriesInputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [12/16]
OutLab7Inputs & CommandLine< OutLab7Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [13/16]
MatrixConstructParams & CommandLine< MatrixConstructParams >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [14/16]
InLab10Inputs & CommandLine< InLab10Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [15/16]
OutLab10Inputs & CommandLine< OutLab10Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
getInputs() [16/16]
OutLab11Inputs & CommandLine< OutLab11Inputs >::getInputs () inline inherited
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
initialize() [1/16]
virtual void CommandLine< OutLab12Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [2/16]
virtual void CommandLine< InLab11Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [3/16]
virtual void CommandLine< SolverInputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [4/16]
virtual void CommandLine< InLab12Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [5/16]
virtual void CommandLine< LagrangePolynomialInputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [6/16]
virtual void CommandLine< OutLab11Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [7/16]
virtual void CommandLine< NewtonCotesInputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [8/16]
virtual void CommandLine< InputMatrices >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [9/16]
virtual void CommandLine< MyBLAS::InputMatrices >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [10/16]
virtual void CommandLine< InLab6Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [11/16]
virtual void CommandLine< OutLab7Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [12/16]
virtual void CommandLine< TaylorSeriesInputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [13/16]
virtual void CommandLine< OutLab6Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [14/16]
virtual void CommandLine< MatrixConstructParams >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [15/16]
virtual void CommandLine< OutLab10Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
initialize() [16/16]
virtual void CommandLine< InLab10Inputs >::initialize () inline protected virtual inherited
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
performInputArgumentsCheck() [1/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters e, k
         checks.clear();
         checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("stopping-criterion", inputMap, map, checks);
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [2/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [3/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
         promptAndSetFlags("use-direct", "the direct PI method", map);
         promptAndSetFlags("use-rayleigh", "the Rayleigh Quotient PI method", map);
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [4/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if output CSV file path is provided and writable
         if (!map.count("output-csv") || map["output-csv"].empty() ||
             !isFileWritable(map["output-csv"].as<std::string>())) {
             while (!map.count("output-csv") || map["output-csv"].empty() ||
                    !isFileWritable(map["output-csv"].as<std::string>())) {
                 std::cerr << "Error: No output CSV filepath provided." << std::endl;
                 std::cout << "Enter output file path: ";
                 std::cin >> input;
                 try {
                     replace(map, "output-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // If input-csv option is provided, read data from the file
         if (map.count("input-csv") && !map["input-csv"].empty()) {
             const std::string filename = map["input-csv"].as<std::string>();
             std::cout << "Reading from file: " << filename << std::endl;
             try {
                 // Create a data map
                 std::map<std::string, std::vector<long double>> dataMap;
                 // Fill data, mapping csv headers (keys) to csv columns (value vectors)
                 readCSV(filename, dataMap);
                 // Read column x if provided and update the number of points
                 if (dataMap.count("x")) {
                     replace(map, "x-points", dataMap["x"]);
                     replace(map, "num-points", static_cast<long double>(dataMap["x"].size()));
                 }
                 // Read column fx if provided
                 if (dataMap.count("f(x)")) {
                     replace(map, "fx-points", dataMap["f(x)"]);
                 }
             } catch (...) {
                 std::cerr << "..failed. Aborting." << std::endl;
                 exit(1);
             }
         }
         // Prompt the user to enter the number of interpolation points until a valid input is provided
         while (map["num-points"].empty() || failsNaturalNumberCheck(map["num-points"].as<long double>())) {
             std::cout << "Enter the number of interpolation points: ";
             std::cin >> input;
             try {
                 replace(map, "num-points", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         // Prompt the user to enter the number of Lagrange interpolation evaluation points until a valid input is
         // provided
         while ((map["num-samples"].empty() || failsNaturalNumberCheck(map["num-samples"].as<long double>()))) {
             std::cout << "Enter the number of Lagrange interpolation evaluation points: ";
             std::cin >> input;
             try {
                 replace(map, "num-samples", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         const auto n = static_cast<size_t>(map["num-points"].as<long double>());
         std::vector<long double> x_vec_inputs = map["x-points"].as<std::vector<long double>>();
         bool messageShown = false;
         // Prompt the user to enter the interpolation points until the required number of points is provided
         while (isUnfilledVector<long double>(map, "x-points", n)) {
             if (!messageShown) {
                 std::cout << "Enter points for the interval x, sorted, and one at a time: " << std::endl;
                 messageShown = true;
             }
             std::cin >> input;
             // attempting to insert non-increasing or non-unique value!
             if (!x_vec_inputs.empty() && asNumber(input) <= x_vec_inputs.back()) {
                 std::cerr << "Cannot accept non-increasing values for x, try again.\n";
                 continue;
             }
             try {
                 x_vec_inputs.push_back(asNumber(input));
                 replace(map, "x-points", x_vec_inputs);
             } catch (...) {
                 std::cerr << "That wasn't a number, try again.\n";
                 continue;
             }
         }
         // If the use-fx-function option is provided, fill the fx-points vector using the bundled f(x=n) function
         if (map.count("use-fx-function")) {
             const std::vector<long double> x = map["x-points"].as<std::vector<long double>>();
             try {
                 std::vector<long double> fx_vec_inputs(x.size(), 0.0f);
                 fill_fx(x, fx_vec_inputs);
                 replace(map, "fx-points", fx_vec_inputs);
             } catch (...) {
                 std::cerr << "Error: Executing external method 'fill_fx' failed. Aborting\n";
                 exit(1);
             }
         }
         std::vector<long double> fx_vec_inputs;
         messageShown = false;
         // Prompt the user to enter the f(x) values until the required number of values is provided
         while (isUnfilledVector<long double>(map, "fx-points", n)) {
             if (!messageShown) {
                 std::cout << "Enter " << n << " points for f(x) for every x, one at a time: " << std::endl;
                 messageShown = true;
             }
             std::cin >> input;
             try {
                 fx_vec_inputs.push_back(asNumber(input));
                 replace(map, "fx-points", fx_vec_inputs);
             } catch (...) {
                 std::cerr << "That wasn't a number, try again.\n";
                 continue;
             }
         }
     }
References asNumber(), failsNaturalNumberCheck(), filename, fill_fx(), isFileWritable(), n, readCSV(), replace(), and x.
performInputArgumentsCheck() [5/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Prompt the user to enter the interval starting point a
         while (map["start"].empty()) {
             std::cout << "Enter the starting value (a) for the integration interval [a,b]: ";
             std::cin >> input;
             try {
                 replace(map, "start", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         const auto a = map["start"].as<long double>();
         // Prompt the user to enter the interval end point b
         while (map["stop"].empty()) {
             std::cout << "Enter the stopping value (b) for the integration interval [a,b]: ";
             std::cin >> input;
             if (a == asNumber(input)) {
                 std::cout << "Warning: Integral for f(x) over [a,a] is trivially 0.\n";
             }
             if (a > asNumber(input)) {
                 std::cout << "Warning: Since (a > b), integral will be performed for -f(x) over [b, a]\n";
             }
             try {
                 replace(map, "stop", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while (map["num-intervals"].empty() || failsNaturalNumberCheck(map["num-intervals"].as<long double>())) {
             std::cout << "Enter the number of integration intervals (m): ";
             std::cin >> input;
             try {
                 replace(map, "num-intervals", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool trapezoidal_set = !map["use-trapezoidal"].defaulted();
         while (!trapezoidal_set) {
             try {
                 std::cout << "Would you like to use the trapezoidal rule? [YES/no]: ";
                 std::cin >> input;
                 replace(map, "use-trapezoidal", asYesOrNo(input));
                 trapezoidal_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool simpsons_set = !map["use-simpsons"].defaulted();
         while (!simpsons_set) {
             try {
                 std::cout << "Would you like to use Simpson's rule? [YES/no]: ";
                 std::cin >> input;
                 replace(map, "use-simpsons", asYesOrNo(input));
                 simpsons_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool gaussian_set = !map["use-gaussian-quadratures"].defaulted();
         while (!gaussian_set) {
             try {
                 std::cout << "Would you like to use Gaussian quadratures? [YES/no]: ";
                 std::cin >> input;
                 replace(map, "use-gaussian-quadratures", asYesOrNo(input));
                 gaussian_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
     }
References asNumber(), asYesOrNo(), failsNaturalNumberCheck(), isFileWritable(), and replace().
performInputArgumentsCheck() [6/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
     }
References doesFileExist(), isFileWritable(), and replace().
performInputArgumentsCheck() [7/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // set precision to 4 if not set.
         if (map["precision"].defaulted()) {
             replace(map, "precision", 6);
         }
     }
References doesFileExist(), isFileWritable(), and replace().
performInputArgumentsCheck() [8/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
         promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         promptAndSetFlags("use-SOR", "SOR method", map);
         promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
     }
References doesFileExist(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [9/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameter n
         checks.clear();
         checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<long double>("n", inputMap, map, checks);
     }
References doesFileExist(), failsNaturalNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [10/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [11/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
         promptAndSetFlags("use-direct", "Use the direct PI method", map);
         promptAndSetFlags("use-rayleigh", "Use the Rayleigh Quotient PI method", map);
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [12/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
         promptAndSetFlags("use-inverse", "Use the inverse PI method", map);
         if (map["use-inverse"].as<bool>()) {
             checks.clear();
             performChecksAndUpdateInput<long double>("lambda", inputMap, map, checks);
         }
         promptAndSetFlags("use-direct", "the direct PI method", map);
         promptAndSetFlags("use-rayleigh", "the Rayleigh Quotient PI method", map);
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [13/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if output CSV file path is provided and writable
         if (!map.count("output-csv") || map["output-csv"].empty() ||
             !isFileWritable(map["output-csv"].as<std::string>())) {
             while (!map.count("output-csv") || map["output-csv"].empty() ||
                    !isFileWritable(map["output-csv"].as<std::string>())) {
                 std::cerr << "Error: No output CSV filepath provided." << std::endl;
                 std::cout << "Enter output file path: ";
                 std::cin >> input;
                 try {
                     replace(map, "output-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // If input-csv option is provided, read data from the file
         if (map.count("input-csv") && !map["input-csv"].empty()) {
             const std::string filename = map["input-csv"].as<std::string>();
             std::cout << "Reading from file: " << filename << std::endl;
             try {
                 // Create a data map
                 std::map<std::string, std::vector<long double>> dataMap;
                 // Fill data, mapping csv headers (keys) to csv columns (value vectors)
                 readCSV(filename, dataMap);
                 // Read column x if provided and update the number of points
                 if (dataMap.count("x")) {
                     std::vector<long double> x_vec_inputs = dataMap["x"];
                     replace(map, "x-points", x_vec_inputs);
                     replace(map, "num-points", static_cast<long double>(dataMap["x"].size()));
                 }
                 // Read column fx if provided
                 if (dataMap.count("f(x)")) {
                     replace(map, "fx-points", dataMap["f(x)"]);
                 }
             } catch (...) {
                 std::cerr << "..failed. Aborting." << std::endl;
                 exit(1);
             }
         }
         // Prompt the user to enter the number of interpolation points until a valid input is provided
         while (map["num-points"].empty() || failsNaturalNumberCheck(map["num-points"].as<long double>())) {
             std::cout << "Enter the number of interpolation points: ";
             std::cin >> input;
             try {
                 replace(map, "num-points", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         // Prompt the user to enter the number of Lagrange interpolation evaluation points until a valid input is
         // provided
         while ((map["num-samples"].empty() || failsNaturalNumberCheck(map["num-samples"].as<long double>()))) {
             std::cout << "Enter the number of Lagrange interpolation evaluation points: ";
             std::cin >> input;
             try {
                 replace(map, "num-samples", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         const auto n = static_cast<size_t>(map["num-points"].as<long double>());
         std::vector<long double> x_vec_inputs = map["x-points"].as<std::vector<long double>>();
         bool messageShown = false;
         // Prompt the user to enter the interpolation points until the required number of points is provided
         while (isUnfilledVector<long double>(map, "x-points", n)) {
             if (!messageShown) {
                 std::cout << "Enter points for the interval x, sorted, and one at a time: " << std::endl;
                 messageShown = true;
             }
             std::cin >> input;
             // attempting to insert non-increasing or non-unique value!
             if (!x_vec_inputs.empty() && asNumber(input) <= x_vec_inputs.back()) {
                 std::cerr << "Cannot accept non-increasing values for x, try again.\n";
                 continue;
             }
             try {
                 x_vec_inputs.push_back(asNumber(input));
                 replace(map, "x-points", x_vec_inputs);
             } catch (...) {
                 std::cerr << "That wasn't a number, try again.\n";
                 continue;
             }
         }
         // If the use-fx-function option is provided, fill the fx-points vector using the bundled f(x=n) function
         if (map.count("use-fx-function")) {
             try {
                 std::vector<long double> x = map["x-points"].as<std::vector<long double>>();
                 std::vector<long double> fx_vec_inputs(x.size(), 0.0f);
                 fill_fx(x, fx_vec_inputs);
                 replace(map, "fx-points", fx_vec_inputs);
                 replace(map, "x-points", x);
             } catch (...) {
                 std::cerr << "Error: Executing external method 'fill_fx' failed. Aborting\n";
                 exit(1);
             }
         }
         std::vector<long double> fx_vec_inputs;
         messageShown = false;
         // Prompt the user to enter the f(x) values until the required number of values is provided
         while (isUnfilledVector<long double>(map, "fx-points", n)) {
             if (!messageShown) {
                 std::cout << "Enter " << n << " points for f(x) for every x, one at a time: " << std::endl;
                 messageShown = true;
             }
             std::cin >> input;
             try {
                 fx_vec_inputs.push_back(asNumber(input));
                 replace(map, "fx-points", fx_vec_inputs);
             } catch (...) {
                 std::cerr << "That wasn't a number, try again.\n";
                 continue;
             }
         }
     }
References asNumber(), failsNaturalNumberCheck(), filename, fill_fx(), isFileWritable(), n, readCSV(), replace(), and x.
performInputArgumentsCheck() [14/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Prompt the user to enter the interval starting point a
         while (map["start"].empty()) {
             std::cout << "Enter the starting value (a) for the integration interval [a,b]: ";
             std::cin >> input;
             try {
                 replace(map, "start", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         const auto a = map["start"].as<long double>();
         // Prompt the user to enter the interval end point b
         while (map["stop"].empty()) {
             std::cout << "Enter the stopping value (b) for the integration interval [a,b]: ";
             std::cin >> input;
             if (a == asNumber(input)) {
                 std::cout << "Warning: Integral for f(x) over [a,a] is trivially 0.\n";
             }
             if (a > asNumber(input)) {
                 std::cout << "Warning: Since (a > b), integral will be performed for -f(x) over [b, a]\n";
             }
             try {
                 replace(map, "stop", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while (map["num-intervals"].empty() || failsNaturalNumberCheck(map["num-intervals"].as<long double>())) {
             std::cout << "Enter the number of integration intervals (m): ";
             std::cin >> input;
             try {
                 replace(map, "num-intervals", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool trapezoidal_set = !map["use-trapezoidal"].defaulted();
         while (!trapezoidal_set) {
             try {
                 std::cout << "Would you like to use the trapezoidal rule? [YES/no]: ";
                 std::cin >> input;
                 replace(map, "use-trapezoidal", asYesOrNo(input));
                 trapezoidal_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool simpsons_set = !map["use-simpsons"].defaulted();
         while (!simpsons_set) {
             try {
                 std::cout << "Would you like to use Simpson's rule? [YES/no]: ";
                 std::cin >> input;
                 replace(map, "use-simpsons", asYesOrNo(input));
                 simpsons_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
         bool gaussian_set = !map["use-gaussian-quadratures"].defaulted();
         while (!gaussian_set) {
             try {
                 std::cout << "Would you like to use Gauss-Legendre Quadrature? [YES/no]: ";
                 std::cin >> input;
                 const bool useGaussian = asYesOrNo(input);
                 replace(map, "use-gaussian-quadratures", useGaussian);
                 gaussian_set = true;
             } catch (const std::exception &) {
                 continue;
             }
         }
         if (map["use-gaussian-quadratures"].as<bool>()) {
             while (map["num-quadrature-points"].empty() ||
                    failsNaturalNumberCheck(map["num-quadrature-points"].as<long double>())) {
                 std::cout << "Enter the number of Gauss-Legendre Quadrature points: ";
                 std::cin >> input;
                 try {
                     replace(map, "num-quadrature-points", asNumber(input));
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
     }
References asNumber(), asYesOrNo(), failsNaturalNumberCheck(), isFileWritable(), and replace().
performInputArgumentsCheck() [15/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
     }
References doesFileExist(), isFileWritable(), and replace().
performInputArgumentsCheck() [16/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
     }
References doesFileExist(), isFileWritable(), and replace().
performInputArgumentsCheck() [17/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // only if not generating already
         if (!map.count("generate")) {
             // Check if input file path is provided
             if (!map.count("input-json") || map["input-json"].empty() ||
                 !doesFileExist(map["input-json"].as<std::string>())) {
                 while (!map.count("input-json") || map["input-json"].empty() ||
                        !doesFileExist(map["input-json"].as<std::string>())) {
                     std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                     std::cout << "Enter input file path (file extension is .json): ";
                     std::cin >> input;
                     try {
                         replace(map, "input-json", input);
                     } catch (const std::exception &) {
                         continue;
                     }
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("threshold", inputMap, map, checks);
         checks.emplace_back([](long double value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("max-iterations", inputMap, map, checks);
         if (map.count("order")) {
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         } else if (map.count("generate")) {
             checks.clear();
             checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
             performChecksAndUpdateInput<long double>("order", inputMap, map, checks);
         }
         promptAndSetFlags("use-LUP", "LUP factorization method", map);
         promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         promptAndSetFlags("use-SOR", "SOR method", map);
         promptAndSetFlags("use-SORJ", "Point-Jacobi with SOR method", map);
         promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
         if (map["use-SOR"].as<bool>() || map["use-SORJ"].as<bool>() || map["use-SSOR"].as<bool>()) {
             checks.clear();
             performChecksAndUpdateInput<long double>("relaxation-factor", inputMap, map, checks);
         }
     }
References doesFileExist(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isFileWritable(), promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [18/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         // Check if input file path is provided
         if (!map.count("input-json") || map["input-json"].empty() ||
             !doesFileExist(map["input-json"].as<std::string>())) {
             while (!map.count("input-json") || map["input-json"].empty() ||
                    !doesFileExist(map["input-json"].as<std::string>())) {
                 std::cerr << "Error: No input JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter input file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // Check if output file path is provided and writable
         if (!map.count("output-json") || map["output-json"].empty() ||
             !isFileWritable(map["output-json"].as<std::string>())) {
             while (!map.count("output-json") || map["output-json"].empty() ||
                    !isFileWritable(map["output-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameter n
         checks.clear();
         checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<long double>("n", inputMap, map, checks);
     }
References doesFileExist(), failsNaturalNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [19/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         const bool quietMode = map.count("quiet");
         std::string input;
         // FILE OPTIONAL
         // if a filepath for an input parameter json is not provided, parameters will be read from the terminal
         // interactively.
         if (!map.count("input-parameter-json") && !quietMode) {
             std::cout
                 << "INFO: Input parameter JSON filepath not provided. Parameters will be specified interactively\n";
         }
         // else:
         // if a filepath of an input parameter json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["input-parameter-json"].empty() || !doesFileExist(map["input-parameter-json"].as<std::string>())) {
             while (map["input-parameter-json"].empty() ||
                    !doesFileExist(map["input-parameter-json"].as<std::string>())) {
                 std::cerr << "ERROR: Filepath for input parameter JSON is invalid.\n" << std::endl;
                 std::cout << "Enter input parameter filepath (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-parameter-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE REQUIRED
         // if a filepath of the source-terms CSV matrix is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         if (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
             !doesFileExist(map["source-terms-csv"].as<std::string>())) {
             std::cerr << "INFO: Source-terms matrix cannot be read interactively.\n" << std::endl;
             while (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
                    !doesFileExist(map["source-terms-csv"].as<std::string>())) {
                 std::cerr << "ERROR: Provided filepath for the source-terms matrix is invalid.\n" << std::endl;
                 std::cout << "Enter a filepath for the source-terms matrix (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "source-terms-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-results-json") && !quietMode) {
             std::cout << "WARNING: Output results JSON filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-results-json"].empty() || !isFileWritable(map["output-results-json"].as<std::string>())) {
             while (!map.count("output-results-json") || map["output-results-json"].empty() ||
                    !isFileWritable(map["output-results-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-results-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-flux-csv") && !quietMode) {
             std::cout << "WARNING: Compute flux matrix CSV filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-flux-csv"].empty() || !isFileWritable(map["output-flux-csv"].as<std::string>())) {
             while (!map.count("output-flux-csv") || map["output-flux-csv"].empty() ||
                    !isFileWritable(map["output-flux-csv"].as<std::string>())) {
                 std::cerr << "Error: No output CSV filepath provided.\n" << std::endl;
                 std::cout << "Enter calculated flux matrix file path (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-flux-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-parameter-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
             inputMap["dimensions"] = {};
             inputMap["mesh"] = {};
         }
         std::vector<std::function<bool(long double)>> checks;
         // add checks for parameters a & b
         checks.clear();
         checks.emplace_back([](long double value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<long double>("a", inputMap["dimensions"], map, checks);
         performChecksAndUpdateInput<long double>("b", inputMap["dimensions"], map, checks);
         // add checks for parameters m & n
         checks.clear();
         checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<long double>("m", inputMap["mesh"], map, checks);
         performChecksAndUpdateInput<long double>("n", inputMap["mesh"], map, checks);
         // add checks for parameters D and
         checks.clear();
         checks.emplace_back([](long double value) { return failsNonNegativeNumberCheck(value); });
         performChecksAndUpdateInput<long double>("D", inputMap, map, checks);
         performChecksAndUpdateInput<long double>("cross-section", inputMap, map, checks);
     }
References doesFileExist(), failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), failsPositiveNumberCheck(), function, isFileWritable(), readJSON(), and replace().
performInputArgumentsCheck() [20/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         const bool quietMode = map.count("quiet");
         std::string input;
         // FILE OPTIONAL
         // if a filepath for an input parameter json is not provided, parameters will be read from the terminal
         // interactively.
         if (!map.count("input-parameter-json") && !quietMode) {
             std::cout
                 << "INFO: Input parameter JSON filepath not provided. Parameters will be specified interactively\n";
         }
         // else:
         // if a filepath of an input parameter json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["input-parameter-json"].empty() || !doesFileExist(map["input-parameter-json"].as<std::string>())) {
             while (map["input-parameter-json"].empty() ||
                    !doesFileExist(map["input-parameter-json"].as<std::string>())) {
                 std::cerr << "ERROR: Filepath for input parameter JSON is invalid.\n" << std::endl;
                 std::cout << "Enter input parameter filepath (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-parameter-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE REQUIRED
         // if a filepath of the source-terms CSV matrix is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         if (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
             !doesFileExist(map["source-terms-csv"].as<std::string>())) {
             std::cerr << "INFO: Source-terms matrix cannot be read interactively.\n" << std::endl;
             while (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
                    !doesFileExist(map["source-terms-csv"].as<std::string>())) {
                 std::cerr << "ERROR: Provided filepath for the source-terms matrix is invalid.\n" << std::endl;
                 std::cout << "Enter a filepath for the source-terms matrix (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "source-terms-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-results-json") && !quietMode) {
             std::cout << "WARNING: Output results JSON filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-results-json"].empty() || !isFileWritable(map["output-results-json"].as<std::string>())) {
             while (!map.count("output-results-json") || map["output-results-json"].empty() ||
                    !isFileWritable(map["output-results-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-results-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("flux-output-dir") && !quietMode) {
             std::cout << "WARNING: Flux matrix CSV folder path not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["flux-output-dir"].empty() || !isFileWritable(map["flux-output-dir"].as<std::string>())) {
             while (!map.count("flux-output-dir") || map["flux-output-dir"].empty() ||
                    !isDirectoryWritable(map["flux-output-dir"].as<std::string>())) {
                 std::cerr << "Error: No output folder provided.\n" << std::endl;
                 std::cout << "Enter a folder name to store the computed fluxes: ";
                 std::cin >> input;
                 try {
                     replace(map, "flux-output-dir", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-parameter-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
             inputMap["dimensions"] = nlohmann::json::object();
             inputMap["mesh"] = nlohmann::json::object();
             inputMap["methods"] = nlohmann::json::array();
         }
         std::vector<std::function<bool(MyBLAS::NumericType)>> checks;
         // add checks for parameters a & b
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("a", inputMap["dimensions"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("b", inputMap["dimensions"], map, checks);
         // add checks for parameters m & n
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("m", inputMap["mesh"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("n", inputMap["mesh"], map, checks);
         // add checks for parameters D and
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNonNegativeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("D", inputMap, map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("cross-section", inputMap, map, checks);
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("threshold", inputMap, map, checks);
         checks.emplace_back([](MyBLAS::NumericType value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("max-iterations", inputMap, map, checks);
         auto methods = std::vector<std::string>(inputMap["methods"]);
         if(contains(methods, "LUP")) {
             replace(map, "use-LUP", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-LUP", "LUP factorization method", map);
         }
         if(contains(methods, "point-jacobi")) {
             replace(map, "use-point-jacobi", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         }
         if(contains(methods, "SORJ")) {
             replace(map, "use-SORJ", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SORJ", "SOR Jacobi method", map);
         }
         if(contains(methods, "gauss-seidel")) {
             replace(map, "use-gauss-seidel", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         }
         if(contains(methods, "SOR")) {
             replace(map, "use-SOR", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SOR", "SOR method", map);
         }
         if(contains(methods, "SSOR")) {
             replace(map, "use-SSOR", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
         }
         if (map["use-SOR"].as<bool>() || map["use-SORJ"].as<bool>() || map["use-SSOR"].as<bool>()) {
             checks.clear();
             performChecksAndUpdateInput<MyBLAS::NumericType>("relaxation-factor", inputMap, map, checks);
         }
     }
References asYesOrNo(), contains(), doesFileExist(), failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isDirectoryWritable(), isFileWritable(), postprocess::methods, promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [21/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         const bool quietMode = map.count("quiet");
         std::string input;
         // FILE OPTIONAL
         // if a filepath for an input parameter json is not provided, parameters will be read from the terminal
         // interactively.
         if (!map.count("input-parameter-json") && !quietMode) {
             std::cout
                 << "INFO: Input parameter JSON filepath not provided. Parameters will be specified interactively\n";
         }
         // else:
         // if a filepath of an input parameter json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["input-parameter-json"].empty() || !doesFileExist(map["input-parameter-json"].as<std::string>())) {
             while (map["input-parameter-json"].empty() ||
                    !doesFileExist(map["input-parameter-json"].as<std::string>())) {
                 std::cerr << "ERROR: Filepath for input parameter JSON is invalid.\n" << std::endl;
                 std::cout << "Enter input parameter filepath (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-parameter-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE REQUIRED
         // if a filepath of the source-terms CSV matrix is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         if (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
             !doesFileExist(map["source-terms-csv"].as<std::string>())) {
             std::cerr << "INFO: Source-terms matrix cannot be read interactively.\n" << std::endl;
             while (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
                    !doesFileExist(map["source-terms-csv"].as<std::string>())) {
                 std::cerr << "ERROR: Provided filepath for the source-terms matrix is invalid.\n" << std::endl;
                 std::cout << "Enter a filepath for the source-terms matrix (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "source-terms-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-results-json") && !quietMode) {
             std::cout << "WARNING: Output results JSON filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-results-json"].empty() || !isFileWritable(map["output-results-json"].as<std::string>())) {
             while (!map.count("output-results-json") || map["output-results-json"].empty() ||
                    !isFileWritable(map["output-results-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-results-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("flux-output-dir") && !quietMode) {
             std::cout << "WARNING: Flux matrix CSV folder path not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["flux-output-dir"].empty() || !isFileWritable(map["flux-output-dir"].as<std::string>())) {
             while (!map.count("flux-output-dir") || map["flux-output-dir"].empty() ||
                    !isDirectoryWritable(map["flux-output-dir"].as<std::string>())) {
                 std::cerr << "Error: No output folder provided.\n" << std::endl;
                 std::cout << "Enter a folder name to store the computed fluxes: ";
                 std::cin >> input;
                 try {
                     replace(map, "flux-output-dir", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-parameter-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
             inputMap["dimensions"] = nlohmann::json::object();
             inputMap["mesh"] = nlohmann::json::object();
             inputMap["methods"] = nlohmann::json::array();
         }
         std::vector<std::function<bool(MyBLAS::NumericType)>> checks;
         // add checks for parameters a & b
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("a", inputMap["dimensions"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("b", inputMap["dimensions"], map, checks);
         // add checks for parameters m & n
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("m", inputMap["mesh"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("n", inputMap["mesh"], map, checks);
         // add checks for parameters D and
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNonNegativeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("D", inputMap, map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("cross-section", inputMap, map, checks);
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("threshold", inputMap, map, checks);
         checks.emplace_back([](MyBLAS::NumericType value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("max-iterations", inputMap, map, checks);
         auto methods = std::vector<std::string>(inputMap["methods"]);
         if(contains(methods, "LUP")) {
             replace(map, "use-LUP", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-LUP", "LUP factorization method", map);
         }
         if(contains(methods, "point-jacobi")) {
             replace(map, "use-point-jacobi", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         }
         if(contains(methods, "SORPJ")) {
             replace(map, "use-SORPJ", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SORPJ", "SOR Jacobi method", map);
         }
         if(contains(methods, "gauss-seidel")) {
             replace(map, "use-gauss-seidel", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         }
         if(contains(methods, "symmetric-gauss-seidel")) {
             replace(map, "use-symmetric-gauss-seidel", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-symmetric-gauss-seidel", "symmetric Gauss-Seidel method", map);
         }
         if(contains(methods, "SOR")) {
             replace(map, "use-SOR", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SOR", "SOR method", map);
         }
         if(contains(methods, "SSOR")) {
             replace(map, "use-SSOR", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
         }
         if (map["use-SORPJ"].as<bool>()  ||
             map["use-SOR"].as<bool>()    ||
             map["use-SSOR"].as<bool>()) {
             checks.clear();
             performChecksAndUpdateInput<MyBLAS::NumericType>("relaxation-factor", inputMap, map, checks);
         }
     }
References asYesOrNo(), contains(), doesFileExist(), failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isDirectoryWritable(), isFileWritable(), postprocess::methods, promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [22/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         const bool quietMode = map.count("quiet");
         std::string input;
         // FILE OPTIONAL
         // if a filepath for an input parameter json is not provided, parameters will be read from the terminal
         // interactively.
         if (!map.count("input-parameter-json") && !quietMode) {
             std::cout
                 << "INFO: Input parameter JSON filepath not provided. Parameters will be specified interactively\n";
         }
         // else:
         // if a filepath of an input parameter json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["input-parameter-json"].empty() || !doesFileExist(map["input-parameter-json"].as<std::string>())) {
             while (map["input-parameter-json"].empty() ||
                    !doesFileExist(map["input-parameter-json"].as<std::string>())) {
                 std::cerr << "ERROR: Filepath for input parameter JSON is invalid.\n" << std::endl;
                 std::cout << "Enter input parameter filepath (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-parameter-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE REQUIRED
         // if a filepath of the source-terms CSV matrix is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         if (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
             !doesFileExist(map["source-terms-csv"].as<std::string>())) {
             std::cerr << "INFO: Source-terms matrix cannot be read interactively.\n" << std::endl;
             while (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
                    !doesFileExist(map["source-terms-csv"].as<std::string>())) {
                 std::cerr << "ERROR: Provided filepath for the source-terms matrix is invalid.\n" << std::endl;
                 std::cout << "Enter a filepath for the source-terms matrix (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "source-terms-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-results-json") && !quietMode) {
             std::cout << "WARNING: Output results JSON filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-results-json"].empty() || !isFileWritable(map["output-results-json"].as<std::string>())) {
             while (!map.count("output-results-json") || map["output-results-json"].empty() ||
                    !isFileWritable(map["output-results-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-results-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("flux-output-dir") && !quietMode) {
             std::cout << "WARNING: Flux matrix CSV folder path not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["flux-output-dir"].empty() || !isFileWritable(map["flux-output-dir"].as<std::string>())) {
             while (!map.count("flux-output-dir") || map["flux-output-dir"].empty() ||
                    !isDirectoryWritable(map["flux-output-dir"].as<std::string>())) {
                 std::cerr << "Error: No output folder provided.\n" << std::endl;
                 std::cout << "Enter a folder name to store the computed fluxes: ";
                 std::cin >> input;
                 try {
                     replace(map, "flux-output-dir", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-parameter-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
             inputMap["dimensions"] = nlohmann::json::object();
             inputMap["mesh"] = nlohmann::json::object();
             inputMap["methods"] = nlohmann::json::array();
         }
         std::vector<std::function<bool(MyBLAS::NumericType)>> checks;
         // add checks for parameters a & b
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("a", inputMap["dimensions"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("b", inputMap["dimensions"], map, checks);
         // add checks for parameters m & n
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("m", inputMap["mesh"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("n", inputMap["mesh"], map, checks);
         // add checks for parameters D and
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNonNegativeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("D", inputMap, map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("cross-section", inputMap, map, checks);
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("threshold", inputMap, map, checks);
         checks.emplace_back([](MyBLAS::NumericType value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("max-iterations", inputMap, map, checks);
         auto methods = std::vector<std::string>(inputMap["methods"]);
 //        if(contains(methods, "LUP")) {
 //            replace(map, "use-LUP", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-LUP", "LUP factorization method", map);
 //        }
 //
         if(contains(methods, "point-jacobi")) {
             replace(map, "use-point-jacobi", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         }
 //
 //        if(contains(methods, "SORJ")) {
 //            replace(map, "use-SORJ", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SORJ", "SOR Jacobi method", map);
 //        }
 //
         if(contains(methods, "gauss-seidel")) {
             replace(map, "use-gauss-seidel", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         }
 //
 //        if(contains(methods, "SOR")) {
 //            replace(map, "use-SOR", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SOR", "SOR method", map);
 //        }
 //
 //        if(contains(methods, "SSOR")) {
 //            replace(map, "use-SSOR", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
 //        }
 //
 //        if (map["use-SOR"].as<bool>() || map["use-SORJ"].as<bool>() || map["use-SSOR"].as<bool>()) {
 //            checks.clear();
 //            performChecksAndUpdateInput<MyBLAS::NumericType>("relaxation-factor", inputMap, map, checks);
 //        }
     }
References asYesOrNo(), contains(), doesFileExist(), failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isDirectoryWritable(), isFileWritable(), postprocess::methods, promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [23/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & map) inline override protected virtual
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
This function performs checks on the input parameters and prompts the user to enter valid inputs if the current inputs are invalid.
Parameters
map A boost::program_options::variables_map object containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         const bool quietMode = map.count("quiet");
         std::string input;
         // FILE OPTIONAL
         // if a filepath for an input parameter json is not provided, parameters will be read from the terminal
         // interactively.
         if (!map.count("input-parameter-json") && !quietMode) {
             std::cout
                 << "INFO: Input parameter JSON filepath not provided. Parameters will be specified interactively\n";
         }
         // else:
         // if a filepath of an input parameter json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["input-parameter-json"].empty() || !doesFileExist(map["input-parameter-json"].as<std::string>())) {
             while (map["input-parameter-json"].empty() ||
                    !doesFileExist(map["input-parameter-json"].as<std::string>())) {
                 std::cerr << "ERROR: Filepath for input parameter JSON is invalid.\n" << std::endl;
                 std::cout << "Enter input parameter filepath (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "input-parameter-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE REQUIRED
         // if a filepath of the source-terms CSV matrix is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         if (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
             !doesFileExist(map["source-terms-csv"].as<std::string>())) {
             std::cerr << "INFO: Source-terms matrix cannot be read interactively.\n" << std::endl;
             while (!map.count("source-terms-csv") || map["source-terms-csv"].empty() ||
                    !doesFileExist(map["source-terms-csv"].as<std::string>())) {
                 std::cerr << "ERROR: Provided filepath for the source-terms matrix is invalid.\n" << std::endl;
                 std::cout << "Enter a filepath for the source-terms matrix (file extension is .csv): ";
                 std::cin >> input;
                 try {
                     replace(map, "source-terms-csv", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("output-results-json") && !quietMode) {
             std::cout << "WARNING: Output results JSON filepath not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["output-results-json"].empty() || !isFileWritable(map["output-results-json"].as<std::string>())) {
             while (!map.count("output-results-json") || map["output-results-json"].empty() ||
                    !isFileWritable(map["output-results-json"].as<std::string>())) {
                 std::cerr << "Error: No output JSON filepath provided.\n" << std::endl;
                 std::cout << "Enter output file path (file extension is .json): ";
                 std::cin >> input;
                 try {
                     replace(map, "output-results-json", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // FILE OPTIONAL
         // if a filepath for output json is not provided, outputs will be written to the terminal only.
         if (!map.count("flux-output-dir") && !quietMode) {
             std::cout << "WARNING: Flux matrix CSV folder path not provided. Writing results to console only.\n";
         }
         // else:
         // if filepath for output json is provided, it will be validated.
         // If the path is invalid, a new path will be accepted interactively
         else if (map["flux-output-dir"].empty() || !isFileWritable(map["flux-output-dir"].as<std::string>())) {
             while (!map.count("flux-output-dir") || map["flux-output-dir"].empty() ||
                    !isDirectoryWritable(map["flux-output-dir"].as<std::string>())) {
                 std::cerr << "Error: No output folder provided.\n" << std::endl;
                 std::cout << "Enter a folder name to store the computed fluxes: ";
                 std::cin >> input;
                 try {
                     replace(map, "flux-output-dir", input);
                 } catch (const std::exception &) {
                     continue;
                 }
             }
         }
         // read the input json and populate the variables_map
         nlohmann::json inputMap;
         try {
             readJSON(map["input-parameter-json"].as<std::string>(), inputMap);
         } catch (...) {
             // initialize input map if no file was read
             inputMap["dimensions"] = nlohmann::json::object();
             inputMap["mesh"] = nlohmann::json::object();
             inputMap["methods"] = nlohmann::json::array();
         }
         std::vector<std::function<bool(MyBLAS::NumericType)>> checks;
         // add checks for parameters a & b
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("a", inputMap["dimensions"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("b", inputMap["dimensions"], map, checks);
         // add checks for parameters m & n
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNaturalNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("m", inputMap["mesh"], map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("n", inputMap["mesh"], map, checks);
         // add checks for parameters D and
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsNonNegativeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("D", inputMap, map, checks);
         performChecksAndUpdateInput<MyBLAS::NumericType>("cross-section", inputMap, map, checks);
         // add checks for parameters  and k
         checks.clear();
         checks.emplace_back([](MyBLAS::NumericType value) { return failsPositiveNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("threshold", inputMap, map, checks);
         checks.emplace_back([](MyBLAS::NumericType value) { return failsWholeNumberCheck(value); });
         performChecksAndUpdateInput<MyBLAS::NumericType>("max-iterations", inputMap, map, checks);
         auto methods = std::vector<std::string>(inputMap["methods"]);
 //        if(contains(methods, "LUP")) {
 //            replace(map, "use-LUP", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-LUP", "LUP factorization method", map);
 //        }
 //
         if(contains(methods, "point-jacobi")) {
             replace(map, "use-point-jacobi", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-point-jacobi", "Point Jacobi method", map);
         }
 //
 //        if(contains(methods, "SORJ")) {
 //            replace(map, "use-SORJ", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SORJ", "SOR Jacobi method", map);
 //        }
 //
         if(contains(methods, "gauss-seidel")) {
             replace(map, "use-gauss-seidel", asYesOrNo("yes"));
         } else {
             promptAndSetFlags("use-gauss-seidel", "Gauss-Seidel method", map);
         }
 //
 //        if(contains(methods, "SOR")) {
 //            replace(map, "use-SOR", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SOR", "SOR method", map);
 //        }
 //
 //        if(contains(methods, "SSOR")) {
 //            replace(map, "use-SSOR", asYesOrNo("yes"));
 //        } else {
 //            promptAndSetFlags("use-SSOR", "symmetric SOR method", map);
 //        }
 //
 //        if (map["use-SOR"].as<bool>() || map["use-SORJ"].as<bool>() || map["use-SSOR"].as<bool>()) {
 //            checks.clear();
 //            performChecksAndUpdateInput<MyBLAS::NumericType>("relaxation-factor", inputMap, map, checks);
 //        }
     }
References asYesOrNo(), contains(), doesFileExist(), failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), failsPositiveNumberCheck(), failsWholeNumberCheck(), function, isDirectoryWritable(), isFileWritable(), postprocess::methods, promptAndSetFlags(), readJSON(), and replace().
performInputArgumentsCheck() [24/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & values) inline override protected virtual
Performs input checks on the input variables.
If the input value fails the check, the function will prompt the user to enter a new value. The function will continue to prompt the user until a valid value is entered.
Parameters
values A map containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         while (values["angle"].empty() || absoluteValueFailsGreaterThan1Check(values["angle"].as<long double>())) {
             std::cout << "Enter a value for the angle x [radian]: ";
             std::cin >> input;
             try {
                 replace(values, "angle", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while (values["convergence-threshold"].empty() ||
                failsPositiveNumberCheck(values["convergence-threshold"].as<long double>())) {
             std::cout << "Enter a value for the stopping criterion e [e > 0]: ";
             std::cin >> input;
             try {
                 replace(values, "convergence-threshold", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while (values["iterations"].empty() || failsNaturalNumberCheck(values["iterations"].as<long double>())) {
             std::cout << "Enter maximum number of iterations (natural number): ";
             std::cin >> input;
             try {
                 replace(values, "iterations", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
     }
References absoluteValueFailsGreaterThan1Check(), asNumber(), failsNaturalNumberCheck(), failsPositiveNumberCheck(), and replace().
performInputArgumentsCheck() [25/25]
void Parser::performInputArgumentsCheck (boost::program_options::variables_map & values) inline override protected virtual
Performs input checks on the input variables.
If the input value fails the check, the function will prompt the user to enter a new value. The function will continue to prompt the user until a valid value is entered.
Parameters
values A map containing the input values to be checked.
Implements CommandLine< OutLab12Inputs >.
{
         std::string input;
         while (values["scalar"].empty()) {
             std::cout << "Enter a value for k, which is the scalar multiplier for [A]: ";
             std::cin >> input;
             try {
                 replace(values, "scalar", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while ((values["m-rank"].empty() || failsNaturalNumberCheck(values["m-rank"].as<long double>()))) {
             std::cout << "Enter a value for M, which is the rank for [A], and row rank for [B]: ";
             std::cin >> input;
             try {
                 replace(values, "m-rank", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while ((values["n-rank"].empty() || failsNaturalNumberCheck(values["n-rank"].as<long double>()))) {
             std::cout << "Enter a value for N, which is the column rank for [B], and row rank for [F]: ";
             std::cin >> input;
             try {
                 replace(values, "n-rank", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
         while ((values["j-rank"].empty() || failsNaturalNumberCheck(values["j-rank"].as<long double>()))) {
             std::cout << "Enter a value for J, which is the column rank for [F]: ";
             std::cin >> input;
             try {
                 replace(values, "j-rank", asNumber(input));
             } catch (const std::exception &) {
                 continue;
             }
         }
     }
References asNumber(), failsNaturalNumberCheck(), and replace().
printCompileConfigs() [1/16]
static void CommandLine< TaylorSeriesInputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [2/16]
static void CommandLine< SolverInputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [3/16]
static void CommandLine< InLab11Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [4/16]
static void CommandLine< InLab12Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [5/16]
static void CommandLine< InLab10Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [6/16]
static void CommandLine< LagrangePolynomialInputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [7/16]
static void CommandLine< OutLab10Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [8/16]
static void CommandLine< NewtonCotesInputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [9/16]
static void CommandLine< OutLab7Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [10/16]
static void CommandLine< OutLab11Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [11/16]
static void CommandLine< MyBLAS::InputMatrices >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [12/16]
static void CommandLine< InputMatrices >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [13/16]
static void CommandLine< InLab6Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [14/16]
static void CommandLine< OutLab12Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [15/16]
static void CommandLine< MatrixConstructParams >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printCompileConfigs() [16/16]
static void CommandLine< OutLab6Inputs >::printCompileConfigs () inline static protected inherited
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printHeader() [1/16]
static void CommandLine< InLab12Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [2/16]
static void CommandLine< InLab11Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [3/16]
static void CommandLine< SolverInputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [4/16]
static void CommandLine< LagrangePolynomialInputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [5/16]
static void CommandLine< OutLab6Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [6/16]
static void CommandLine< InLab6Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [7/16]
static void CommandLine< NewtonCotesInputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [8/16]
static void CommandLine< MyBLAS::InputMatrices >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [9/16]
static void CommandLine< OutLab11Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [10/16]
static void CommandLine< MatrixConstructParams >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [11/16]
static void CommandLine< OutLab7Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [12/16]
static void CommandLine< TaylorSeriesInputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [13/16]
static void CommandLine< OutLab12Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [14/16]
static void CommandLine< InputMatrices >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [15/16]
static void CommandLine< OutLab10Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printHeader() [16/16]
static void CommandLine< InLab10Inputs >::printHeader (HeaderInfo & headerInfo) inline static protected inherited
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
printInputArguments() [1/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A map of variable names to their values.
It retrieves the precision, angle, convergence threshold and iterations from the variable map and prints them.
Implements CommandLine< OutLab12Inputs >.
{
         const auto precision = vm["precision"].as<int>();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tangle, x: " << std::setprecision(static_cast<int>(precision)) << vm["angle"].as<long double>() << "\n";
         std::cout << "\tconvergence-threshold, t: " << std::setprecision(static_cast<int>(precision))
                   << vm["convergence-threshold"].as<long double>() << "\n";
         std::cout << "\titerations, n: " << std::setprecision(static_cast<int>(default_precision)) << vm["iterations"].as<long double>()
                   << "\n";
         CommandLine::printLine();
     }
References default_precision, and CommandLine< InputType >::printLine().
printInputArguments() [2/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON,              i: " << vm["input-json"].as<std::string>() << std::endl;
         std::cout << "\tOutput JSON,             o: " << vm["output-json"].as<std::string>() << std::endl;
         std::cout << "\tStopping Criterion,      e: " << vm["stopping-criterion"].as<long double>() << std::endl;
         std::cout << "\tMaximum Iterations,      k: " << vm["max-iterations"].as<long double>() << std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [3/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tGenerate A,b,            g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A, b),   i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")<<std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [4/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tGenerate A               g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A),      i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")<<std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [5/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto precision = vm["precision"].as<int>();
         const auto n = static_cast<size_t>(vm["num-points"].as<long double>());
         const auto m = static_cast<size_t>(vm["num-samples"].as<long double>());
         const auto x = vm["x-points"].as<std::vector<long double>>();
         const auto fx = vm["fx-points"].as<std::vector<long double>>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << std::setw(16) << "x" << std::setw(34) << "f(x)\n" << std::scientific;
         for (size_t i = 0; i < x.size(); i++) {
             const auto x_sign = (x[i] >= 0) ? "+" : "";
             const auto fx_sign = (fx[i] >= 0) ? "+" : "";
             std::cout << "\t" << x_sign << std::setprecision(static_cast<int>(precision)) << x[i];
             std::cout << "\t\t\t" << fx_sign << std::setprecision(static_cast<int>(precision)) << fx[i] << std::endl;
         }
         CommandLine::printLine();
         std::cout << "\tnum-points,     n: " << n << "\n";
         std::cout << "\tnum-samples,    m: " << m << "\n";
         if (vm.count("input-csv") && !vm["input-csv"].empty()) {
             std::cout << "\tinput-csv,      i: " << vm["input-csv"].as<std::string>() << "\n";
         }
         std::cout << "\toutput-csv,     o: " << vm["output-csv"].as<std::string>() << "\n";
         CommandLine::printLine();
     }
References i, m, n, CommandLine< InputType >::printLine(), and x.
printInputArguments() [6/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto precision = vm["precision"].as<int>();
         const auto a = vm["start"].as<long double>();
         const auto b = vm["stop"].as<long double>();
         const auto m = static_cast<size_t>(vm["num-intervals"].as<long double>());
         const auto use_trapezoidal = vm["use-trapezoidal"].as<bool>();
         const auto use_simpson = vm["use-simpsons"].as<bool>();
         const auto use_gaussian = vm["use-gaussian-quadratures"].as<bool>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInterval Count,            m: " << m << "\n";
         std::cout << "\tInterval Start,            a: " << std::setprecision(static_cast<int>(precision)) << a << "\n";
         std::cout << "\tInterval Stop,             b: " << std::setprecision(static_cast<int>(precision)) << b << "\n";
         std::cout << "\tOutput JSON,               o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tUse Trapezoidal Rule,      t: " << (use_trapezoidal ? "yes" : "no") << "\n";
         std::cout << "\tUse Simpson's Rule,        s: " << (use_simpson ? "yes" : "no") << "\n";
         std::cout << "\tUse Gaussian Quadratures,  g: " << (use_gaussian ? "yes" : "no") << "\n";
         CommandLine::printLine();
     }
References m, and CommandLine< InputType >::printLine().
printInputArguments() [7/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto n = static_cast<size_t>(vm["order"].as<long double>());
         const auto inputFilepath = vm["input-json"].as<std::string>();
         const auto outputFilepath = vm["output-json"].as<std::string>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tMatrix order,  n: " << n << "\n";
         std::cout << "\tInput JSON,    i: " << inputFilepath << "\n";
         std::cout << "\tOutput JSON,   o: " << outputFilepath << "\n";
         CommandLine::printLine();
     }
References n, and CommandLine< InputType >::printLine().
printInputArguments() [8/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto n = static_cast<size_t>(vm["order"].as<long double>());
         const auto inputFilepath = vm["input-json"].as<std::string>();
         const auto outputFilepath = vm["output-json"].as<std::string>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tMatrix order,  n: " << n << "\n";
         std::cout << "\tInput JSON,    i: " << inputFilepath << "\n";
         std::cout << "\tOutput JSON,   o: " << outputFilepath << "\n";
         CommandLine::printLine();
     }
References n, and CommandLine< InputType >::printLine().
printInputArguments() [9/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON (for A, b),  i: " << vm["input-json"].as<std::string>() << "\n";
         std::cout << "\tOutput JSON (for x),    o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,  : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,         k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,           n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")
                   << "\n";
         std::cout << "\tUse Gauss-Siedel         : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi         : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse SOR                  : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse SSOR                 : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [10/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tInput JSON,              i: " << inputJson << "\n";
         std::cout << "\tOutput JSON,             o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tSum Upper Limit,         n: " << std::to_string(static_cast<size_t>(vm["n"].as<long double>())) << "\n";
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [11/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A map of variable names to their values.
It retrieves the precision, angle, convergence threshold and iterations from the variable map and prints them.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto precision = vm["precision"].as<int>();
         const auto k = vm["scalar"].as<long double>();
         const auto M = static_cast<size_t>(vm["m-rank"].as<long double>());
         const auto N = static_cast<size_t>(vm["n-rank"].as<long double>());
         const auto J = static_cast<size_t>(vm["j-rank"].as<long double>());
         // list the parameters
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tscalar, k: " << std::setprecision(static_cast<int>(precision)) << k << "\n";
         std::cout << "\tm-rank, M: " << M << "\n";
         std::cout << "\tn-rank, N: " << N << "\n";
         std::cout << "\tj-rank, J: " << J << "\n";
         CommandLine::printLine();
     }
References k, and CommandLine< InputType >::printLine().
printInputArguments() [12/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tGenerate A               g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A),      i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")<<std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [13/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tGenerate A               g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A),      i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")<<std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [14/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         const bool inverse = vm.count("use-inverse");
         const bool direct = vm.count("use-direct");
         const bool rayleigh = vm.count("use-rayleigh");
         std::cout << "\tUse inverse PI method     : " << (inverse ? "Yes" : "No") << "\n";
         std::cout << "\tUse direct PI method      : " << (direct ? "Yes" : "No") << "\n";
         std::cout << "\tUse Rayleigh PI method    : " << (rayleigh ? "Yes" : "No") << "\n";
         std::cout << "\tGenerate A               g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A),      i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")<<std::endl;
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [15/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto precision = vm["precision"].as<int>();
         const auto n = static_cast<size_t>(vm["num-points"].as<long double>());
         const auto m = static_cast<size_t>(vm["num-samples"].as<long double>());
         const auto x = vm["x-points"].as<std::vector<long double>>();
         const auto fx = vm["fx-points"].as<std::vector<long double>>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << std::setw(16) << "x" << std::setw(34) << "f(x)\n" << std::scientific;
         for (size_t i = 0; i < x.size(); i++) {
             const auto x_sign = (x[i] >= 0) ? "+" : "";
             const auto fx_sign = (fx[i] >= 0) ? "+" : "";
             std::cout << "\t" << x_sign << std::setprecision(static_cast<int>(precision)) << x[i];
             std::cout << "\t\t\t" << fx_sign << std::setprecision(static_cast<int>(precision)) << fx[i] << std::endl;
         }
         CommandLine::printLine();
         std::cout << "\tnum-points,     n: " << n << "\n";
         std::cout << "\tnum-samples,    m: " << m << "\n";
         if (vm.count("input-csv") && !vm["input-csv"].empty()) {
             std::cout << "\tinput-csv,      i: " << vm["input-csv"].as<std::string>() << "\n";
         }
         std::cout << "\toutput-csv,     o: " << vm["output-csv"].as<std::string>() << "\n";
         CommandLine::printLine();
     }
References i, m, n, CommandLine< InputType >::printLine(), and x.
printInputArguments() [16/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto precision = vm["precision"].as<int>();
         const auto a = vm["start"].as<long double>();
         const auto b = vm["stop"].as<long double>();
         const auto m = static_cast<size_t>(vm["num-intervals"].as<long double>());
         const auto use_trapezoidal = vm["use-trapezoidal"].as<bool>();
         const auto use_simpson = vm["use-simpsons"].as<bool>();
         const auto use_gaussian = vm["use-gaussian-quadratures"].as<bool>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInterval Count,            m: " << m << "\n";
         std::cout << "\tInterval Start,            a: " << std::setprecision(static_cast<int>(precision)) << a << "\n";
         std::cout << "\tInterval Stop,             b: " << std::setprecision(static_cast<int>(precision)) << b << "\n";
         std::cout << "\tOutput JSON,               o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tUse Trapezoidal Rule,      t: " << (use_trapezoidal ? "yes" : "no") << "\n";
         std::cout << "\tUse Simpson's Rule,        s: " << (use_simpson ? "yes" : "no") << "\n";
         std::cout << "\tUse Gaussian Quadratures,  g: " << (use_gaussian ? "yes" : "no") << "\n";
         CommandLine::printLine();
     }
References m, and CommandLine< InputType >::printLine().
printInputArguments() [17/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto n = static_cast<size_t>(vm["order"].as<long double>());
         const auto inputFilepath = vm["input-json"].as<std::string>();
         const auto outputFilepath = vm["output-json"].as<std::string>();
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tMatrix order,  n: " << n << "\n";
         std::cout << "\tInput JSON,    i: " << inputFilepath << "\n";
         std::cout << "\tOutput JSON,   o: " << outputFilepath << "\n";
         CommandLine::printLine();
     }
References n, and CommandLine< InputType >::printLine().
printInputArguments() [18/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // retrieve the inputs
         const auto n = static_cast<size_t>(vm["order"].as<long double>());
         const auto inputFilepath = vm["input-json"].as<std::string>();
         const auto outputFilepath = vm["output-json"].as<std::string>();
         const bool noPivoting = vm.count("no-pivoting") != 0;
         const bool alternateMethod = vm.count("alternate-method") != 0;
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tMatrix order,        n: " << n << "\n";
         std::cout << "\tInput JSON,          i: " << inputFilepath << "\n";
         std::cout << "\tOutput JSON,         o: " << outputFilepath << "\n";
         std::cout << "\tUse Pivoting          : " << (noPivoting ? "No" : "Yes") << "\n";
         std::cout << "\tUse Alternate Method  : " << (alternateMethod ? "Yes" : "No") << "\n";
         CommandLine::printLine();
     }
References n, and CommandLine< InputType >::printLine().
printInputArguments() [19/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const bool gen = vm.count("generate");
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tGenerate A,b,            g: " << (gen ? "Yes" : "No") << "\n";
         std::cout << "\tInput JSON (for A, b),   i: " << (gen ? "[IGNORED] " : " ") << inputJson << "\n";
         std::cout << "\tOutput JSON (for x),     o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tConvergence Threshold,   : " << vm["threshold"].as<long double>() << "\n";
         std::cout << "\tMax iterations,          k: " << static_cast<size_t>(vm["max-iterations"].as<long double>())
                   << "\n";
         std::cout << "\tMatrix order,            n: "
                   << (vm.count("order") ? std::to_string(static_cast<size_t>(vm["order"].as<long double>()))
                                         : "None provided, will be inferred from input JSON")
                   << "\n";
         std::cout << "\tSOR weight,              : "
                   << (vm.count("relaxation-factor") ? std::to_string(vm["relaxation-factor"].as<long double>()) : "N/A")
                   << "\n";
         std::cout << "\tUse LUP factorization     : " << (vm["use-LUP"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Gauss-Seidel          : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi          : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse SOR                   : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi with SOR : " << (vm["use-SORJ"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse symmetric SOR         : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [20/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         const auto inputJson = vm.count("input-json") ? vm["input-json"].as<std::string>() : "None provided";
         std::cout << "\tInput JSON,              i: " << inputJson << "\n";
         std::cout << "\tOutput JSON,             o: " << vm["output-json"].as<std::string>() << "\n";
         std::cout << "\tSum Upper Limit,         n: " << std::to_string(static_cast<size_t>(vm["n"].as<long double>())) << "\n";
         CommandLine::printLine();
     }
References CommandLine< InputType >::printLine().
printInputArguments() [21/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         std::cout << std::setprecision(static_cast<int>(default_precision));
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON                              i: "
                   << (vm.count("input-parameter-json") ? vm["input-parameter-json"].as<std::string>() : "None") << "\n";
         std::cout << "\tOutput JSON                             o: "
                   << (vm.count("output-results-json") ? vm["output-results-json"].as<std::string>() : "None") << "\n";
         std::cout << "\t----\n";
         std::cout << "\tUse LUP method                           : " << (vm.count("use-LUP") ? "Yes" : "yes") << "\n";
         std::cout << "\tUse Point-Jacobi method                  : " << (vm.count("use-point-jacobi") ? "Yes" : "No")
                   << "\n";
         std::cout << "\tUse Gauss-Seidel method                  : " << (vm.count("use-gauss-seidel") ? "Yes" : "No")
                   << "\n";
         std::cout << "\tUse SOR method                           : " << (vm.count("use-SOR") ? "Yes" : "No") << "\n";
         std::cout << "\t----\n";
         std::cout << "\t1st dimension length,                   a: " << vm["a"].as<long double>() << "\n";
         std::cout << "\t2nd dimension length,                   b: " << vm["b"].as<long double>() << "\n";
         std::cout << "\t1st dimension mesh-points,              m: " << static_cast<size_t>(vm["m"].as<long double>())
                   << "\n";
         std::cout << "\t2nd dimension mesh-points,              n: " << static_cast<size_t>(vm["n"].as<long double>())
                   << "\n";
         std::cout << "\tDiffusion coefficient,                  D: " << (vm["D"].as<long double>()) << "\n";
         std::cout << "\tMacroscopic removal cross-section,     : " << (vm["cross-section"].as<long double>()) << "\n";
         CommandLine::printLine();
         std::cout << std::setprecision(vm["precision"].as<int>());
     }
References default_precision, and CommandLine< InputType >::printLine().
printInputArguments() [22/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         if (vm.count("quiet")) {
             return;
         }
         std::cout << std::setprecision(static_cast<int>(default_precision));
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON,     i: " << (vm.count("input-parameter-json") ? vm["input-parameter-json"].as<std::string>() : "None") << "\n";
         std::cout << "\tOutput JSON,    o: " << (vm.count("output-results-json") ? vm["output-results-json"].as<std::string>() : "None") << "\n";
         std::cout << "\t----\n";
         std::cout << "\tConvergence Threshold,                  : " << vm["threshold"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\tMax iterations,                         k: " << static_cast<size_t>(vm["max-iterations"].as<MyBLAS::NumericType>())<< "\n";
         std::cout << "\tSOR weight,                             : "<< (vm.count("relaxation-factor") ? std::to_string(vm["relaxation-factor"].as<MyBLAS::NumericType>()) : "N/A") << "\n";
         std::cout << "\tUse LUP factorization                    : " << (vm["use-LUP"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Gauss-Seidel                         : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi                         : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse SOR                                  : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi with SOR                : " << (vm["use-SORJ"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse symmetric SOR                        : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\t----\n";
         std::cout << "\t1st dimension length,                   a: " << vm["a"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t2nd dimension length,                   b: " << vm["b"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t1st dimension mesh-points,              m: " << static_cast<size_t>(vm["m"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\t2nd dimension mesh-points,              n: " << static_cast<size_t>(vm["n"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tDiffusion coefficient,                  D: " << (vm["D"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tMacroscopic removal cross-section,     : " << (vm["cross-section"].as<MyBLAS::NumericType>()) << "\n";
         CommandLine::printLine();
         std::cout << std::setprecision(vm["precision"].as<int>());
     }
References default_precision, and CommandLine< InputType >::printLine().
printInputArguments() [23/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         if (vm.count("quiet")) {
             return;
         }
         std::cout << std::setprecision(static_cast<int>(default_precision));
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON,     i: " << (vm.count("input-parameter-json") ? vm["input-parameter-json"].as<std::string>() : "None") << "\n";
         std::cout << "\tOutput JSON,    o: " << (vm.count("output-results-json") ? vm["output-results-json"].as<std::string>() : "None") << "\n";
         std::cout << "\t----\n";
         std::cout << "\tConvergence Threshold,                  : " << vm["threshold"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\tMax iterations,                         k: " << static_cast<size_t>(vm["max-iterations"].as<MyBLAS::NumericType>())<< "\n";
         std::cout << "\tSOR weight,                             : "<< (vm.count("relaxation-factor") ? std::to_string(vm["relaxation-factor"].as<MyBLAS::NumericType>()) : "N/A") << "\n";
         std::cout << "\tUse LUP factorization                    : " << (vm["use-LUP"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi                         : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi with SOR                : " << (vm["use-SORPJ"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Gauss-Seidel                         : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse symmetric Gauss-Seidel               : " << (vm["use-symmetric-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse SOR                                  : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse symmetric SOR                        : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\t----\n";
         std::cout << "\t1st dimension length,                   a: " << vm["a"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t2nd dimension length,                   b: " << vm["b"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t1st dimension mesh-points,              m: " << static_cast<size_t>(vm["m"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\t2nd dimension mesh-points,              n: " << static_cast<size_t>(vm["n"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tDiffusion coefficient,                  D: " << (vm["D"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tMacroscopic removal cross-section,     : " << (vm["cross-section"].as<MyBLAS::NumericType>()) << "\n";
         CommandLine::printLine();
         std::cout << std::setprecision(vm["precision"].as<int>());
     }
References default_precision, and CommandLine< InputType >::printLine().
printInputArguments() [24/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         if (vm.count("quiet")) {
             return;
         }
         std::cout << std::setprecision(static_cast<int>(default_precision));
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON,     i: " << (vm.count("input-parameter-json") ? vm["input-parameter-json"].as<std::string>() : "None") << "\n";
         std::cout << "\tOutput JSON,    o: " << (vm.count("output-results-json") ? vm["output-results-json"].as<std::string>() : "None") << "\n";
         std::cout << "\t----\n";
         std::cout << "\tConvergence Threshold,                  : " << vm["threshold"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\tMax iterations,                         k: " << static_cast<size_t>(vm["max-iterations"].as<MyBLAS::NumericType>())<< "\n";
         std::cout << "\tSOR weight,                             : "<< (vm.count("relaxation-factor") ? std::to_string(vm["relaxation-factor"].as<MyBLAS::NumericType>()) : "N/A") << "\n";
 //        std::cout << "\tUse LUP factorization                    : " << (vm["use-LUP"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Gauss-Seidel                         : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi                         : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse SOR                                  : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse Point-Jacobi with SOR                : " << (vm["use-SORJ"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse symmetric SOR                        : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\t----\n";
         std::cout << "\t1st dimension length,                   a: " << vm["a"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t2nd dimension length,                   b: " << vm["b"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t1st dimension mesh-points,              m: " << static_cast<size_t>(vm["m"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\t2nd dimension mesh-points,              n: " << static_cast<size_t>(vm["n"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tDiffusion coefficient,                  D: " << (vm["D"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tMacroscopic removal cross-section,     : " << (vm["cross-section"].as<MyBLAS::NumericType>()) << "\n";
         CommandLine::printLine();
         std::cout << std::setprecision(vm["precision"].as<int>());
     }
References default_precision, and CommandLine< InputType >::printLine().
printInputArguments() [25/25]
void Parser::printInputArguments (boost::program_options::variables_map & vm) inline override protected virtual
This function prints the input values.
Parameters
vm A boost::program_options::variables_map object containing the input values to be printed.
Implements CommandLine< OutLab12Inputs >.
{
         if (vm.count("quiet")) {
             return;
         }
         std::cout << std::setprecision(static_cast<int>(default_precision));
         // list the parameters
         CommandLine::printLine();
         std::cout << std::setw(44) << "Inputs\n";
         CommandLine::printLine();
         std::cout << "\tInput JSON,     i: " << (vm.count("input-parameter-json") ? vm["input-parameter-json"].as<std::string>() : "None") << "\n";
         std::cout << "\tOutput JSON,    o: " << (vm.count("output-results-json") ? vm["output-results-json"].as<std::string>() : "None") << "\n";
         std::cout << "\t----\n";
         std::cout << "\tConvergence Threshold,                  : " << vm["threshold"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\tMax iterations,                         k: " << static_cast<size_t>(vm["max-iterations"].as<MyBLAS::NumericType>())<< "\n";
         std::cout << "\tSOR weight,                             : "<< (vm.count("relaxation-factor") ? std::to_string(vm["relaxation-factor"].as<MyBLAS::NumericType>()) : "N/A") << "\n";
 //        std::cout << "\tUse LUP factorization                    : " << (vm["use-LUP"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Gauss-Seidel                         : " << (vm["use-gauss-seidel"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\tUse Point-Jacobi                         : " << (vm["use-point-jacobi"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse SOR                                  : " << (vm["use-SOR"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse Point-Jacobi with SOR                : " << (vm["use-SORJ"].as<bool>() ? "Yes" : "No") << "\n";
 //        std::cout << "\tUse symmetric SOR                        : " << (vm["use-SSOR"].as<bool>() ? "Yes" : "No") << "\n";
         std::cout << "\t----\n";
         std::cout << "\t1st dimension length,                   a: " << vm["a"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t2nd dimension length,                   b: " << vm["b"].as<MyBLAS::NumericType>() << "\n";
         std::cout << "\t1st dimension mesh-points,              m: " << static_cast<size_t>(vm["m"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\t2nd dimension mesh-points,              n: " << static_cast<size_t>(vm["n"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tDiffusion coefficient,                  D: " << (vm["D"].as<MyBLAS::NumericType>()) << "\n";
         std::cout << "\tMacroscopic removal cross-section,     : " << (vm["cross-section"].as<MyBLAS::NumericType>()) << "\n";
         CommandLine::printLine();
         std::cout << std::setprecision(vm["precision"].as<int>());
     }
References default_precision, and CommandLine< InputType >::printLine().
printLine() [1/16]
static void CommandLine< NewtonCotesInputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [2/16]
static void CommandLine< OutLab7Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [3/16]
static void CommandLine< InLab10Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [4/16]
static void CommandLine< InLab11Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [5/16]
static void CommandLine< LagrangePolynomialInputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [6/16]
static void CommandLine< InLab6Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [7/16]
static void CommandLine< OutLab6Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [8/16]
static void CommandLine< OutLab10Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [9/16]
static void CommandLine< OutLab12Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [10/16]
static void CommandLine< MyBLAS::InputMatrices >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [11/16]
static void CommandLine< InputMatrices >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [12/16]
static void CommandLine< OutLab11Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [13/16]
static void CommandLine< MatrixConstructParams >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [14/16]
static void CommandLine< InLab12Inputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [15/16]
static void CommandLine< TaylorSeriesInputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printLine() [16/16]
static void CommandLine< SolverInputs >::printLine () inline static inherited
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
printPrecisionInformation() [1/16]
void CommandLine< MatrixConstructParams >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [2/16]
void CommandLine< SolverInputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [3/16]
void CommandLine< InLab10Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [4/16]
void CommandLine< OutLab10Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [5/16]
void CommandLine< TaylorSeriesInputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [6/16]
void CommandLine< InLab12Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [7/16]
void CommandLine< InLab11Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [8/16]
void CommandLine< InLab6Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [9/16]
void CommandLine< OutLab11Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [10/16]
void CommandLine< OutLab7Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [11/16]
void CommandLine< LagrangePolynomialInputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [12/16]
void CommandLine< NewtonCotesInputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [13/16]
void CommandLine< OutLab6Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [14/16]
void CommandLine< InputMatrices >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [15/16]
void CommandLine< OutLab12Inputs >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
printPrecisionInformation() [16/16]
void CommandLine< MyBLAS::InputMatrices >::printPrecisionInformation () inline protected inherited
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
setPrecision() [1/16]
void CommandLine< MyBLAS::InputMatrices >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [2/16]
void CommandLine< OutLab11Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [3/16]
void CommandLine< TaylorSeriesInputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [4/16]
void CommandLine< NewtonCotesInputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [5/16]
void CommandLine< LagrangePolynomialInputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [6/16]
void CommandLine< InputMatrices >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [7/16]
void CommandLine< OutLab12Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [8/16]
void CommandLine< InLab12Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [9/16]
void CommandLine< InLab10Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [10/16]
void CommandLine< InLab11Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [11/16]
void CommandLine< OutLab10Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [12/16]
void CommandLine< OutLab6Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [13/16]
void CommandLine< MatrixConstructParams >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [14/16]
void CommandLine< SolverInputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [15/16]
void CommandLine< InLab6Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
setPrecision() [16/16]
void CommandLine< OutLab7Inputs >::setPrecision (int precisionToSet = 5) inline inherited
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
Field Documentation
_inputs [1/16]
TaylorSeriesInputs CommandLine< TaylorSeriesInputs >::_inputs protected inherited
_inputs [2/16]
InLab10Inputs CommandLine< InLab10Inputs >::_inputs protected inherited
_inputs [3/16]
InLab12Inputs CommandLine< InLab12Inputs >::_inputs protected inherited
_inputs [4/16]
InputMatrices CommandLine< InputMatrices >::_inputs protected inherited
_inputs [5/16]
OutLab11Inputs CommandLine< OutLab11Inputs >::_inputs protected inherited
_inputs [6/16]
OutLab12Inputs CommandLine< OutLab12Inputs >::_inputs protected inherited
_inputs [7/16]
MyBLAS::InputMatrices CommandLine< MyBLAS::InputMatrices >::_inputs protected inherited
_inputs [8/16]
OutLab6Inputs CommandLine< OutLab6Inputs >::_inputs protected inherited
_inputs [9/16]
SolverInputs CommandLine< SolverInputs >::_inputs protected inherited
_inputs [10/16]
InLab6Inputs CommandLine< InLab6Inputs >::_inputs protected inherited
_inputs [11/16]
InLab11Inputs CommandLine< InLab11Inputs >::_inputs protected inherited
_inputs [12/16]
LagrangePolynomialInputs CommandLine< LagrangePolynomialInputs >::_inputs protected inherited
_inputs [13/16]
OutLab7Inputs CommandLine< OutLab7Inputs >::_inputs protected inherited
_inputs [14/16]
MatrixConstructParams CommandLine< MatrixConstructParams >::_inputs protected inherited
_inputs [15/16]
NewtonCotesInputs CommandLine< NewtonCotesInputs >::_inputs protected inherited
_inputs [16/16]
OutLab10Inputs CommandLine< OutLab10Inputs >::_inputs protected inherited
cmdArgs [1/16]
CommandLine< SolverInputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [2/16]
CommandLine< InLab10Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [3/16]
CommandLine< InputMatrices >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [4/16]
CommandLine< OutLab12Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [5/16]
CommandLine< OutLab6Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [6/16]
CommandLine< InLab12Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [7/16]
CommandLine< MyBLAS::InputMatrices >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [8/16]
CommandLine< TaylorSeriesInputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [9/16]
CommandLine< InLab6Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [10/16]
CommandLine< LagrangePolynomialInputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [11/16]
CommandLine< OutLab7Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [12/16]
CommandLine< MatrixConstructParams >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [13/16]
CommandLine< InLab11Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [14/16]
CommandLine< OutLab10Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [15/16]
CommandLine< NewtonCotesInputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
cmdArgs [16/16]
CommandLine< OutLab11Inputs >::cmdArgs protected inherited
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
header [1/16]
CommandLine< SolverInputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [2/16]
CommandLine< OutLab11Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [3/16]
CommandLine< InputMatrices >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [4/16]
CommandLine< OutLab10Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [5/16]
CommandLine< OutLab6Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [6/16]
CommandLine< InLab12Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [7/16]
CommandLine< MyBLAS::InputMatrices >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [8/16]
CommandLine< InLab10Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [9/16]
CommandLine< TaylorSeriesInputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [10/16]
CommandLine< InLab6Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [11/16]
CommandLine< LagrangePolynomialInputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [12/16]
CommandLine< OutLab7Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [13/16]
CommandLine< OutLab12Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [14/16]
CommandLine< MatrixConstructParams >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [15/16]
CommandLine< NewtonCotesInputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
header [16/16]
CommandLine< InLab11Inputs >::header protected inherited
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
initialized [1/16]
CommandLine< OutLab12Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [2/16]
CommandLine< InputMatrices >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [3/16]
CommandLine< MyBLAS::InputMatrices >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [4/16]
CommandLine< InLab12Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [5/16]
CommandLine< NewtonCotesInputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [6/16]
CommandLine< OutLab7Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [7/16]
CommandLine< SolverInputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [8/16]
CommandLine< OutLab10Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [9/16]
CommandLine< OutLab6Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [10/16]
CommandLine< InLab6Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [11/16]
CommandLine< LagrangePolynomialInputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [12/16]
CommandLine< OutLab11Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [13/16]
CommandLine< TaylorSeriesInputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [14/16]
CommandLine< InLab11Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [15/16]
CommandLine< MatrixConstructParams >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
initialized [16/16]
CommandLine< InLab10Inputs >::initialized protected inherited
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
variablesMap [1/16]
CommandLine< OutLab6Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [2/16]
CommandLine< OutLab7Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [3/16]
CommandLine< InLab10Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [4/16]
CommandLine< InLab6Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [5/16]
CommandLine< TaylorSeriesInputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [6/16]
CommandLine< OutLab10Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [7/16]
CommandLine< OutLab12Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [8/16]
CommandLine< SolverInputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [9/16]
CommandLine< NewtonCotesInputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [10/16]
CommandLine< InLab12Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [11/16]
CommandLine< OutLab11Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [12/16]
CommandLine< InputMatrices >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [13/16]
CommandLine< MyBLAS::InputMatrices >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [14/16]
CommandLine< InLab11Inputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [15/16]
CommandLine< MatrixConstructParams >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
variablesMap [16/16]
CommandLine< LagrangePolynomialInputs >::variablesMap protected inherited
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
The documentation for this class was generated from the following file:
src/labs/inlab1/Parser.h