NE591-008 C++17 Codebase: MyBLAS Namespace Reference
MyBLAS Namespace Reference
Namespace containing linear algebra functions and classes.
Namespaces
LU
LUP
Solver
Namespace containing the definition of the LinearSolver class and its associated methods.
Stats
A namespace for statistical functions and structures.
System
This namespace contains system-related functions in the MyBLAS library.
Data Structures
struct Input
Struct representing the input matrices for the BLAS library.
struct Output
Struct representing the output vector for the BLAS library.
class ContainerExpression
A class to perform operations on two containers of data.
class ElementwiseExpression
A class for performing element-wise operations on two containers.
class LazyMatrix
A matrix that lazily computes its values.
class Matrix
Class representing a matrix of T type values.
class Vector
Class representing a vector of T values. This class represents a vector of elements of type T. It provides various operations for working with vectors.
class MatrixExpressionTests
class VectorExpressionTests
class LazyMatrixTests
class LazyVectorTests
class BaseMatrixTests
class MatrixMemoryAllocationTests
class PerformanceMatrixTests
class MatrixUtilityTests
class VectorTests
class VectorMemoryAllocationTests
class PerformanceVectorTests
class VectorUtilityTests
class LazyVector
A vector that lazily computes its values.
class VectorExpression
Represents an expression for element-wise vector operations.
Typedefs
typedef struct MyBLAS::Input InputMatrices
typedef struct MyBLAS::Output OutputVector
using NumericType = long double
typedef ::testing::Types< int, long, float, double, long double > FloatTypes
typedef ::testing::Types< int, float, double, long double > NumericTypes
Functions
template<typename T >
static void doolittleFactorizeLU (MyBLAS::Matrix< T > &L, MyBLAS::Matrix< T > &U, const MyBLAS::Matrix< T > &A)
Factorizes a given matrix A into lower and upper triangular matrices L,U using Doolittle's method.
template<typename T >
static void factorizeLU (MyBLAS::Matrix< T > &L, MyBLAS::Matrix< T > &U, const MyBLAS::Matrix< T > &A)
Factorizes a given matrix A into lower and upper triangular matrices L,U.
template<typename T >
static bool isValidUpperTriangularMatrix (const MyBLAS::Matrix< T > &U)
Checks if the given matrix is a valid upper triangular matrix.
template<typename T >
static bool isValidUnitLowerTriangularMatrix (const MyBLAS::Matrix< T > &L)
Checks if the given matrix is a valid unit lower triangular matrix.
template<typename MatrixType >
bool isSquareMatrix (const MatrixType &M)
Checks if the given matrix is a square matrix.
template<typename MatrixType >
bool isEmptyMatrix (const MatrixType &M)
Checks if the given matrix is empty.
template<typename VectorType >
bool isEmptyVector (const VectorType &V)
Checks if the given vector is empty.
template<template< typename > class U, typename T >
bool isBinaryVector (const U< T > &V)
Checks if the given vector is purely a zero vector.
template<template< typename > class U, typename T >
bool isBinaryMatrix (const U< T > &M)
Checks if the given matrix is a binary matrix.
template<template< typename > class U, typename T >
bool isZeroVector (const U< T > &V)
Checks if the given vector is a zero vector.
template<template< typename > class U, typename T >
bool isUnitVector (const U< T > &V)
Checks if the given vector is a unit vector.
template<template< typename > class U, typename T >
bool isUpperTriangularMatrix (const U< T > &M)
Checks if the given matrix is a valid upper triangular matrix.
template<template< typename > class U, typename T >
bool isUnitLowerTriangularMatrix (const U< T > &L)
Checks if the given matrix is a valid unit lower triangular matrix.
template<template< typename > class U, typename T >
bool isPermutationMatrix (const U< T > &P)
Checks if the given matrix is a valid permutation matrix.
template<template< typename > class M, typename T >
bool isSymmetricMatrix (const M< T > &A, const T tolerance=0)
Checks if the given matrix is symmetric.
template<template< typename > class M, typename T >
bool isPositiveDefiniteMatrix (const M< T > &A)
Checks if the given matrix is positive definite using Cholesky decomposition.
template<template< typename > class U, typename T >
bool allDiagonalElementsBelowThreshold (const U< T > &A, const T &threshold=0)
Checks if all diagonal elements of a matrix are below a certain threshold.
template<template< typename > class U, typename T >
bool noZerosInDiagonal (const U< T > &A)
Checks if there are no zeros in the diagonal of a matrix.
template<template< typename > class U, typename T >
bool isDiagonallyDominant (const U< T > &A)
Checks if the given matrix is diagonally dominant.
template<typename MatrixType , typename VectorType >
bool haveEqualRank (const MatrixType &A, const VectorType &b)
Checks if two matrices have the same rank.
template<typename T >
MyBLAS::Vector< T > operator* (const T &scalar, const MyBLAS::Vector< T > &vector)
‍**
template<typename T >
MyBLAS::Vector< T > operator+ (const T &scalar, const MyBLAS::Vector< T > &vector)
Global function to add a scalar to a vector.
template<template< typename > class U, typename T >
U< T > innerProduct (const U< T > &A, const U< T > &B)
Computes the inner product of two matrices.
template<template< typename > class M, template< typename > class V, typename T >
T matrixWeightedInnerProduct (const V< T > &y, const V< T > &z, const M< T > &A)
template<typename DataType >
MyBLAS::Vector< DataType > operator* (MyBLAS::Vector< DataType > const &a, LazyMatrix< DataType > const &b)=delete
This function template is a placeholder for vector-matrix multiplication in the MyBLAS library.
template<template< typename > class M, template< typename > class V, typename T >
V< T > forwardSubstitution (const M< T > &L, const V< T > &b)
Perform forward substitution.
template<template< typename > class M, template< typename > class V, typename T >
V< T > backwardSubstitution (const M< T > &U, const V< T > &y)
Perform backward substitution.
template<typename T , typename T2 >
static MyBLAS::Matrix< T > cast (const MyBLAS::Matrix< T2 > &input)
Casts the elements of a given matrix to a specified type.
template<typename T , typename T2 >
static MyBLAS::Vector< T > cast (const MyBLAS::Vector< T2 > &input)
Casts the elements of a given vector to a specified type.
template<template< typename > class VectorType, typename T >
T L2 (const VectorType< T > &a, const VectorType< T > &b, const size_t n)
Calculates the L2 norm of the distance (Euclidean distance) between two containers.
template<typename T >
T L2 (const MyBLAS::Vector< T > &a, const MyBLAS::Vector< T > &b)
Overloaded function that calculates the L2 norm (Euclidean distance) between two MyBLAS::Vector objects.
template<typename T >
T norm (const MyBLAS::Vector< T > &v)
A template function to calculate the norm of a vector.
template<typename ContainerType , typename DataType >
DataType AbsoluteMaxResidual (const ContainerType &a, const ContainerType &b, const size_t n)
Calculates the absolute maximum residual between two containers.
template<typename T >
T AbsoluteMaxResidual (const MyBLAS::Vector< T > &a, const MyBLAS::Vector< T > &b)
Overloaded function that calculates the absolute maximum residual between two MyBLAS::Vector objects.
template<typename T >
void makeDiagonallyDominant (MyBLAS::Matrix< T > &A, const T dominance_offset=1)
Makes the given matrix diagonally dominant.
TEST_F (MatrixExpressionTests, TestMatrixExpression)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithDifferentBinaryOp)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithMultiplication)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithDivision)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithModulo)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithPower)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithMax)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithMin)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithSqrt)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithLog)
TEST_F (MatrixExpressionTests, TestMatrixExpressionWithExp)
TEST_F (VectorExpressionTests, TestVectorExpression)
TEST_F (VectorExpressionTests, TestVectorExpressionWithDifferentBinaryOp)
TEST_F (VectorExpressionTests, TestVectorExpressionMultiplication)
TEST_F (VectorExpressionTests, TestVectorExpressionAddition)
TEST_F (VectorExpressionTests, TestVectorExpressionSubtraction)
TEST_F (VectorExpressionTests, TestVectorExpressionDivision)
TEST_F (VectorExpressionTests, TestVectorExpressionWithDifferentVectorTypes)
TEST_F (VectorExpressionTests, TestVectorExpressionWithEmptyVectors)
TYPED_TEST_SUITE (LazyMatrixTests, FloatTypes)
TYPED_TEST (LazyMatrixTests, SizeTest)
TYPED_TEST (LazyMatrixTests, ElementAccessTest)
TYPED_TEST (LazyMatrixTests, AdditionTest)
TYPED_TEST (LazyMatrixTests, SubtractionTest)
TYPED_TEST (LazyMatrixTests, MatrixMultiplicationTest)
TYPED_TEST (LazyMatrixTests, BLASMatrixAdditionTest)
TYPED_TEST (LazyMatrixTests, BLASMatrixSubtractionTest)
TYPED_TEST (LazyMatrixTests, EqualityTest)
TYPED_TEST (LazyMatrixTests, InequalityTest)
TYPED_TEST (LazyMatrixTests, ScalarAdditionTest)
TYPED_TEST (LazyMatrixTests, ScalarSubtractionTest)
TYPED_TEST (LazyMatrixTests, ScalarMultiplicationTest)
TYPED_TEST (LazyMatrixTests, ScalarDivisionTest)
TYPED_TEST (LazyMatrixTests, AsRowVectorTest)
TYPED_TEST (LazyMatrixTests, AsColumnVectorTest)
TYPED_TEST (LazyMatrixTests, MatrixVectorMultiplicationTest)
TYPED_TEST (LazyMatrixTests, LazyMatrixLazyVectorMultiplicationTest)
TYPED_TEST (LazyMatrixTests, MatrixVectorMultiplicationTest_ScalarMultiplication)
TYPED_TEST (LazyMatrixTests, MatrixVectorMultiplicationTest_ZeroVector)
TYPED_TEST (LazyMatrixTests, MatrixVectorMultiplicationTest_IdentityMatrix)
TEST_F (LazyVectorTests, SizeTest)
TEST_F (LazyVectorTests, ElementAccessTest)
TEST_F (LazyVectorTests, AdditionTest)
TEST_F (LazyVectorTests, SubtractionTest)
TEST_F (LazyVectorTests, DotProductTest)
TEST_F (LazyVectorTests, ScalarAdditionTest)
TEST_F (LazyVectorTests, ScalarSubtractionTest)
TEST_F (LazyVectorTests, ScalarMultiplicationTest)
TEST_F (LazyVectorTests, ScalarDivisionTest)
TEST_F (LazyVectorTests, ScalarDivisionByZeroTest)
TEST_F (LazyVectorTests, SubtractionAdditionNegationTest)
TEST_F (LazyVectorTests, UnaryNegationTest)
TEST_F (LazyVectorTests, InPlaceAdditionTest)
TEST_F (LazyVectorTests, InPlaceSubtractionTest)
TEST_F (LazyVectorTests, ElementWiseAdditionAssignmentTest)
TEST_F (LazyVectorTests, ElementWiseSubtractionAssignmentTest)
TEST_F (LazyVectorTests, EqualityInequalityTest)
TEST_F (LazyVectorTests, AssignmentTest)
TEST_F (LazyVectorTests, ElementWiseScalarAdditionAssignmentTest)
TEST_F (LazyVectorTests, ElementWiseScalarSubtractionAssignmentTest)
TEST_F (LazyVectorTests, ElementWiseScalarMultiplicationAssignmentTest)
TEST_F (LazyVectorTests, ElementWiseScalarDivisionAssignmentTest)
TYPED_TEST_SUITE (BaseMatrixTests, NumericTypes)
TYPED_TEST (BaseMatrixTests, CopyAssignmentToNewObject)
TYPED_TEST (BaseMatrixTests, CopyAssignmentToExistingObject)
TYPED_TEST (BaseMatrixTests, SelfAssignment)
TYPED_TEST (BaseMatrixTests, ChainedAssignment)
TYPED_TEST (BaseMatrixTests, MoveAssignmentToNewObject)
TYPED_TEST (BaseMatrixTests, MoveAssignmentToExistingObject)
TYPED_TEST (BaseMatrixTests, SelfMoveAssignment)
TYPED_TEST (BaseMatrixTests, ChainedMoveAssignment)
TYPED_TEST (BaseMatrixTests, ConstructorTest)
TYPED_TEST (BaseMatrixTests, DefaultConstructorTest)
TYPED_TEST (BaseMatrixTests, SizeInitialValueConstructorTest)
TYPED_TEST (BaseMatrixTests, Vector2DConstructorTest)
TYPED_TEST (BaseMatrixTests, CopyConstructorTest)
TYPED_TEST (BaseMatrixTests, MoveConstructorTest)
TYPED_TEST (BaseMatrixTests, InitializerListConstructorTest)
TYPED_TEST (BaseMatrixTests, LambdaFunctionConstructorTest)
TYPED_TEST (BaseMatrixTests, CopyAssignmentOperatorTest)
TYPED_TEST (BaseMatrixTests, MoveAssignmentOperatorTest)
TYPED_TEST (BaseMatrixTests, AdditionTest)
TYPED_TEST (BaseMatrixTests, SubtractionTest)
TYPED_TEST (BaseMatrixTests, MultiplicationTest)
TYPED_TEST (BaseMatrixTests, RightSideScalarMultiplicationTest)
TYPED_TEST (BaseMatrixTests, LeftSideScalarMultiplicationTest)
TYPED_TEST (BaseMatrixTests, ScalarMultiplicationSymmetryTest)
TYPED_TEST (BaseMatrixTests, EqualityTest)
TYPED_TEST (BaseMatrixTests, InequalityTest)
TYPED_TEST (BaseMatrixTests, ZeroSizeMatrixTest)
TYPED_TEST (BaseMatrixTests, IdentityMatrixTest)
TYPED_TEST (BaseMatrixTests, MatrixVectorMultiplicationTest)
TYPED_TEST (BaseMatrixTests, SubMatrixTest)
TYPED_TEST (BaseMatrixTests, SetSubMatrixTest)
TYPED_TEST (BaseMatrixTests, SwapRowsTest)
TYPED_TEST (BaseMatrixTests, ScalarDivisionTest)
TYPED_TEST (BaseMatrixTests, ScalarAdditionTest)
TYPED_TEST (BaseMatrixTests, ScalarSubtractionTest)
TYPED_TEST (BaseMatrixTests, EmptyMatrixTest)
TYPED_TEST (BaseMatrixTests, NonSquareMatrixTest)
TYPED_TEST (BaseMatrixTests, InstanceTrackingOnConstruction)
TYPED_TEST (BaseMatrixTests, InstanceTrackingOnCopyConstruction)
TYPED_TEST (BaseMatrixTests, InstanceTrackingOnMoveConstruction)
TYPED_TEST (BaseMatrixTests, InstanceTrackingOnCopyAssignment)
TYPED_TEST (BaseMatrixTests, InstanceTrackingOnMoveAssignment)
TYPED_TEST_SUITE (MatrixMemoryAllocationTests, NumericTypes)
TYPED_TEST (MatrixMemoryAllocationTests, ConstructorTest)
TYPED_TEST_SUITE (PerformanceMatrixTests, NumericTypes)
TYPED_TEST (PerformanceMatrixTests, MatrixMultiplicationPerformanceTest)
TYPED_TEST (PerformanceMatrixTests, MatrixAdditionPerformanceTest)
TYPED_TEST (PerformanceMatrixTests, VectorAdditionOpenMPCPUTest)
TYPED_TEST_SUITE (MatrixUtilityTests, NumericTypes)
TYPED_TEST (MatrixUtilityTests, IsSquareMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsEmptyMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsBinaryMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsUpperTriangularMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsUnitLowerTriangularMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsPermutationMatrixTest)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixTest)
TYPED_TEST (MatrixUtilityTests, NoZerosInDiagonalTest)
TYPED_TEST (MatrixUtilityTests, IsDiagonallyDominantTest)
TYPED_TEST (MatrixUtilityTests, HaveEqualRankTest)
TYPED_TEST (MatrixUtilityTests, InnerProductTest)
TYPED_TEST (MatrixUtilityTests, MatrixWeightedInnerProductTest)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixEmptyMatrix)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixSymmetric)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixSymmetricNegativeValues)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixNonSquare)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixOneByOne)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixFloatingPoint)
TYPED_TEST (MatrixUtilityTests, IsSymmetricMatrixFloatingPointPrecision)
TYPED_TEST (MatrixUtilityTests, IsPositiveDefiniteMatrixTest)
TYPED_TEST_SUITE (VectorTests, NumericTypes)
TYPED_TEST (VectorTests, ConstructorTest)
TYPED_TEST (VectorTests, EqualityTest)
TYPED_TEST (VectorTests, AdditionTest)
TYPED_TEST (VectorTests, SubtractionTest)
TYPED_TEST (VectorTests, DotProductTest)
TYPED_TEST (VectorTests, ScalarMultiplicationTest)
TYPED_TEST (VectorTests, ScalarDivisionTest)
TYPED_TEST (VectorTests, ScalarAdditionTest)
TYPED_TEST (VectorTests, ScalarSubtractionTest)
TYPED_TEST (VectorTests, EmptyVectorTest)
TYPED_TEST (VectorTests, LambdaConstructorTest)
TYPED_TEST (VectorTests, InequalityTest)
TYPED_TEST (VectorTests, VectorAdditionSizeMismatchTest)
TYPED_TEST (VectorTests, VectorSubtractionSizeMismatchTest)
TYPED_TEST (VectorTests, VectorDotProductSizeMismatchTest)
TYPED_TEST (VectorTests, VectorScalarDivisionByZeroTest)
TYPED_TEST (VectorTests, InitializerListConstructorTest)
TYPED_TEST (VectorTests, InitializerListConstructorWithRowVectorTest)
TYPED_TEST (VectorTests, InitializerListConstructorWithEmptyListTest)
TYPED_TEST (VectorTests, InitializerListConstructorWithSingleElementTest)
TYPED_TEST (VectorTests, InitializerListConstructorWithDifferentValuesTest)
TYPED_TEST_SUITE (VectorMemoryAllocationTests, NumericTypes)
TYPED_TEST (VectorMemoryAllocationTests, ConstructorTest)
TYPED_TEST_SUITE (PerformanceVectorTests, NumericTypes)
TYPED_TEST (PerformanceVectorTests, VectorAdditionPerformanceTest)
TYPED_TEST (PerformanceVectorTests, VectorScalarMultiplicationPerformanceTest)
TYPED_TEST (PerformanceVectorTests, VectorMultiplicationPerformanceTest)
TYPED_TEST (PerformanceVectorTests, VectorL2NormPerformanceTest)
TYPED_TEST_SUITE (VectorUtilityTests, NumericTypes)
TYPED_TEST (VectorUtilityTests, IsZeroVectorTest)
TYPED_TEST (VectorUtilityTests, IsUnitVectorTest)
TYPED_TEST (VectorUtilityTests, VectorNormTest)
TYPED_TEST (VectorUtilityTests, DotProductTest)
template<template< typename > class ContainerType1, template< typename > class ContainerType2, typename T >
ContainerType1< T > operator/ (ContainerType1< T > const &a, ContainerType2< T > const &b)=delete
This function template is a placeholder for vector-vector division in the MyBLAS library.
Detailed Description
Namespace containing linear algebra functions and classes.
This namespace contains classes and functions for basic linear algebra operations.
Namespace for the Basic Linear Algebra Subprograms (BLAS) operations.
Namespace for the Basic Linear Algebra Subprograms (BLAS) library.
Typedef Documentation
FloatTypes
typedef ::testing::Types<int, long, float, double, long double> MyBLAS::FloatTypes
InputMatrices
typedef struct MyBLAS::Input MyBLAS::InputMatrices
NumericType
using MyBLAS::NumericType = typedef long double
NumericTypes
typedef::testing::Types< float, double, long double > MyBLAS::NumericTypes
OutputVector
typedef struct MyBLAS::Output MyBLAS::OutputVector
Function Documentation
AbsoluteMaxResidual() [1/2]
template<typename ContainerType , typename DataType > DataType MyBLAS::AbsoluteMaxResidual (const ContainerType & a, const ContainerType & b, const size_t n) inline
Calculates the absolute maximum residual between two containers.
The absolute maximum residual is the maximum absolute difference between the corresponding elements of the two containers.
Template Parameters
ContainerType The type of the containers. This should be a container type that supports indexing with the [] operator.
DataType The type of the data contained in the containers. This should be a type that supports subtraction and the std::abs function.
Parameters
a The first container.
b The second container.
n The size of the containers. This function assumes that both containers have the same size.
Returns
The absolute maximum residual between the two containers.
{
     DataType max_residual = 0;
     for (size_t i = 0; i < n; i++) {
         DataType residual = std::abs(a[i] - b[i]);
         max_residual = std::max(max_residual, residual);
     }
     return max_residual;
 }
References MyMath::abs(), i, MyBLAS::Stats::max(), postprocess::max_residual, n, and postprocess::residual.
AbsoluteMaxResidual() [2/2]
template<typename T > T MyBLAS::AbsoluteMaxResidual (const MyBLAS::Vector< T > & a, const MyBLAS::Vector< T > & b)
Overloaded function that calculates the absolute maximum residual between two MyBLAS::Vector objects.
This function uses the AbsoluteMaxResidual function defined above to calculate the absolute maximum residual. The size of the vectors is determined by the smaller of the two vectors.
Template Parameters
T The type of the data contained in the vectors. This should be a type that supports subtraction and the std::abs function.
Parameters
a The first vector.
b The second vector.
Returns
The absolute maximum residual between the two vectors.
{
     const size_t n = std::min(a.size(), b.size());
     return MyBLAS::AbsoluteMaxResidual<MyBLAS::Vector<T>, T>(a, b, n);
 }
References MyBLAS::Stats::min(), n, and MyBLAS::Vector< T >::size().
allDiagonalElementsBelowThreshold()
template<template< typename > class U, typename T > bool MyBLAS::allDiagonalElementsBelowThreshold (const U< T > & A, const T & threshold = 0)
Checks if all diagonal elements of a matrix are below a certain threshold.
This function iterates over the diagonal elements of the input matrix A and checks if their absolute values are below a given threshold.If any diagonal element is not below the threshold, the function returns false. The function also checks for invalid values (NANs and infinities).
Template Parameters
T The data type of the matrix elements.
Parameters
A The input matrix to be checked.
threshold The threshold value to compare against. Default is 0.
Returns
true if all diagonal elements are below the threshold, false otherwise.
{
     const size_t n = A.getRows(); // or A.getCols(), since A is a square matrix
     const T absolute_threshold = std::abs(threshold);
     // Iterate over the diagonal elements of the input matrix A
     for (size_t i = 0; i < n; i++) {
         // Check if the diagonal element is zero
         // NANs and +inf, -inf make the matrix invalid
         if (std::isinf(A[i][i]) || std::isnan(A[i][i])) {
             return false;
         }
         if (std::abs(A[i][i]) > absolute_threshold) {
             return false;
         }
     }
     return true;
 }
References MyMath::abs(), i, and n.
Referenced by noZerosInDiagonal(), and MyFactorizationMethod::passesPostChecks().
backwardSubstitution()
template<template< typename > class M, template< typename > class V, typename T > V<T> MyBLAS::backwardSubstitution (const M< T > & U, const V< T > & y)
Perform backward substitution.
This function performs backward substitution, which is used in solving a system of linear equations after the system matrix has been decomposed into a lower triangular matrix (L) and an upper triangular matrix (U), and forward substitution has been performed. The backward substitution algorithm iterates through each row of the upper triangular matrix (U) in reverse order and computes the corresponding element in the solution vector (x) by subtracting the sum of the product of the current row elements and the corresponding elements in the solution vector (x) from the corresponding element in the intermediate result vector (y) and then dividing by the diagonal element of the current row in the upper triangular matrix (U).
Template Parameters
T Using templates for data type consistency in computation.
Parameters
U An upper triangular matrix.
y The result vector after performing forward substitution.
Returns
The solution vector after performing backward substitution.
{
     static_assert(std::is_same<M<T>, MyBLAS::Matrix<T>>::value, "M must be a MyBLAS::Matrix type");
     static_assert(std::is_same<V<T>, MyBLAS::Vector<T>>::value, "M must be a MyBLAS::Matrix type");
     const auto n = y.size();
     auto x = V<T>(n, static_cast<T>(0));
     for (int64_t i = n - 1; i >= 0; i--) {
         T sum = 0;
         for (auto j = static_cast<size_t>(i + 1); j < n; j++) {
             sum += U[i][j] * x[j];
         }
         x[i] = (y[i] - sum) / U[i][i];
     }
     return x;
 }
References i, n, MyBLAS::Stats::sum(), x, and y.
Referenced by MyBLAS::LUP::applyLUP(), InLab04::doBackwardSubstitution(), InLab5::run(), OutLab4::run(), OutLab5::run(), and Project1::run().
cast() [1/2]
template<typename T , typename T2 > static MyBLAS::Matrix<T> MyBLAS::cast (const MyBLAS::Matrix< T2 > & input) static
Casts the elements of a given matrix to a specified type.
This function creates a new matrix with the same dimensions as the input matrix and fills it with the elements of the input matrix cast to the specified type.
Template Parameters
T The data type to cast the elements to.
T2 The original data type of the elements in the input matrix.
Parameters
input The input matrix whose elements are to be cast.
Returns
A new matrix with the elements of the input matrix cast to the specified type.
{
     MyBLAS::Matrix<T> output = Matrix<T>(input.getRows(), input.getCols(), 0);
     for (size_t row = 0; row < output.getRows(); row++) {
         for (size_t col = 0; col < output.getCols(); col++) {
             output[row][col] = static_cast<T>(input[row][col]);
         }
     }
     return output;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and process::row.
cast() [2/2]
template<typename T , typename T2 > static MyBLAS::Vector<T> MyBLAS::cast (const MyBLAS::Vector< T2 > & input) static
Casts the elements of a given vector to a specified type.
This function creates a new vector with the same size as the input vector and fills it with the elements of the input vector cast to the specified type.
Template Parameters
T The data type to cast the elements to.
T2 The original data type of the elements in the input vector.
Parameters
input The input vector whose elements are to be cast.
Returns
A new vector with the elements of the input vector cast to the specified type.
{
     MyBLAS::Vector<T> output = Vector<T>(input.size(), 0);
     for (size_t idx = 0; idx < output.size(); idx++) {
         output[idx] = static_cast<T>(input[idx]);
     }
     return output;
 }
References MyBLAS::Vector< T >::size().
doolittleFactorizeLU()
template<typename T > static void MyBLAS::doolittleFactorizeLU (MyBLAS::Matrix< T > & L, MyBLAS::Matrix< T > & U, const MyBLAS::Matrix< T > & A) static
Factorizes a given matrix A into lower and upper triangular matrices L,U using Doolittle's method.
Template Parameters
T The data type of the matrix elements.
Parameters
[out] L The lower triangular matrix.
[out] U The upper triangular matrix.
[in] A The input matrix to be factorized.
This function implements the LU factorization algorithm using Doolittle's method, which decomposes a given matrix A into a lower triangular matrix L and an upper triangular matrix U such that A = L * U. The algorithm computes the elements of L and U iteratively by eliminating elements in the lower triangle of the matrix A to form L and elements in the upper triangle to form U. The main loop iterates over the columns of the input matrix A, and for each column i, it computes the elements of the i-th row of U and the i-th column of L.
{
     const size_t n = A.getCols();
     // Iterate over the columns of the input matrix A
     for (size_t i = 0; i < n; i++) {
         // Compute the elements of the i-th row of U
         for (size_t k = i; k < n; k++) {
             T sum = 0.0f;
             // Calculate the sum of the product of the corresponding elements of L and U
             for (size_t j = 0; j < i; j++) {
                 sum += (L[i][j] * U[j][k]);
             }
             // Update the element of U by subtracting the sum from the corresponding element of A
             U[i][k] = A[i][k] - sum;
         }
         // Set the diagonal element of L to 1
         L[i][i] = 1;
         // Compute the elements of the i-th column of L
         for (size_t k = i + 1; k < n; k++) {
             T sum = 0.0f;
             // Calculate the sum of the product of the corresponding elements of L and U
             for (size_t j = 0; j < i; j++) {
                 sum += (L[k][j] * U[j][i]);
             }
             // Update the element of L by dividing the difference between the corresponding element of A
             // and the sum by the diagonal element of U
             L[k][i] = (A[k][i] - sum) / U[i][i];
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), i, k, L(), n, and MyBLAS::Stats::sum().
factorizeLU()
template<typename T > static void MyBLAS::factorizeLU (MyBLAS::Matrix< T > & L, MyBLAS::Matrix< T > & U, const MyBLAS::Matrix< T > & A) static
Factorizes a given matrix A into lower and upper triangular matrices L,U.
Template Parameters
T The data type of the matrix elements.
Parameters
[out] L The lower triangular matrix.
[out] U The upper triangular matrix.
[in] A The input matrix to be factorized.
{
     doolittleFactorizeLU<T>(L, U, A);
 }
References L().
forwardSubstitution()
template<template< typename > class M, template< typename > class V, typename T > V<T> MyBLAS::forwardSubstitution (const M< T > & L, const V< T > & b)
Perform forward substitution.
This function performs forward substitution, which is used in solving a system of linear equations after the system matrix has been decomposed into a lower triangular matrix (L) and an upper triangular matrix (U). The forward substitution algorithm iterates through each row of the lower triangular matrix (L) and computes the corresponding element in the intermediate result vector (y) by subtracting the sum of the product of the current row elements and the corresponding elements in the intermediate result vector (y) from the corresponding element in the input vector (b).
Template Parameters
T Using templates for data type consistency in computation.
Parameters
L A lower triangular matrix.
b A vector in the system of linear equations Ax = b.
Returns
The result vector after performing forward substitution.
{
     static_assert(std::is_same<V<T>, MyBLAS::Vector<T>>::value, "M must be a MyBLAS::Matrix type");
     const auto n = b.size();
     auto y = V<T>(n);
     for (size_t row = 0; row < n; row++) {
         T sum = 0;
         for (size_t col = 0; col < row; col++) {
             sum += L[row][col] * y[col];
         }
         y[row] = (b[row] - sum);
     }
     return y;
 }
References L(), n, process::row, MyBLAS::Stats::sum(), and y.
Referenced by MyBLAS::LUP::applyLUP(), InLab04::doForwardSubstitution(), InLab5::run(), OutLab4::run(), OutLab5::run(), and Project1::run().
haveEqualRank()
template<typename MatrixType , typename VectorType > bool MyBLAS::haveEqualRank (const MatrixType & A, const VectorType & b)
Checks if two matrices have the same rank.
This function compares the number of rows in matrix A with the size of vector b to determine if they have the same rank.
Template Parameters
T The data type of the matrix and vector elements.
Parameters
A The input matrix to be checked.
b The input vector to be checked.
Returns
true if the matrix and vector have the same rank, false otherwise.
{
     return A.getRows() == b.size();
 }
References MyBLAS::Matrix< T >::getRows().
Referenced by MyFactorizationMethod::passesPreChecks(), and TYPED_TEST().
innerProduct()
template<template< typename > class U, typename T > U<T> MyBLAS::innerProduct (const U< T > & A, const U< T > & B)
Computes the inner product of two matrices.
Parameters
rhs Matrix to compute the inner product with.
Returns
The inner product of the two matrices.
{
     static_assert(std::is_same<U<T>, MyBLAS::Matrix<T>>::value, "T must be a MyBLAS::Matrix type");
     assert(A.getRows() == B.getRows());
     assert(A.getCols() == B.getCols());
     const size_t a_rows = A.getRows(), b_cols = B.getCols();
     MyBLAS::Matrix<T> result(a_rows, b_cols);
     for (size_t row = 0; row < a_rows; row++) {
         for (size_t col = 0; col < b_cols; col++) {
             result[row][col] = A[row][col] * B[row][col];
         }
     }
     return result;
 }
References process::row.
Referenced by MyBLAS::System::Circuit(), and TYPED_TEST().
isBinaryMatrix()
template<template< typename > class U, typename T > bool MyBLAS::isBinaryMatrix (const U< T > & M)
Checks if the given matrix is a binary matrix.
This function checks if all elements of the input matrix are either 0 or 1.
Parameters
M The input matrix to be checked.
Returns
true if the input matrix is a binary matrix, false otherwise.
{
     const size_t rows = M.getRows();
     const size_t cols = M.getCols();
     for (size_t i = 0; i < rows; i++) {
         for (size_t j = 0; j < cols; j++) {
             if (M[i][j] != 0 && M[i][j] != 1) {
                 return false;
             }
         }
     }
     return true;
 }
References i.
Referenced by isPermutationMatrix(), and TYPED_TEST().
isBinaryVector()
template<template< typename > class U, typename T > bool MyBLAS::isBinaryVector (const U< T > & V)
Checks if the given vector is purely a zero vector.
Parameters
V The input vector to be checked.
Returns
true if the input vector has only zero values, false otherwise.
{
     const size_t items = V.size();
     for (size_t i = 0; i < items; i++) {
         if (V[i] != 0 && V[i] != 1) {
             return false;
         }
     }
     return true;
 }
References i.
isDiagonallyDominant()
template<template< typename > class U, typename T > bool MyBLAS::isDiagonallyDominant (const U< T > & A)
Checks if the given matrix is diagonally dominant.
This function checks if the input matrix is square, and if the absolute value of each diagonal element is greater than the sum of the absolute values of the other elements in the same row. If these conditions are met, the matrix is considered diagonally dominant.
Parameters
A The input matrix to be checked.
Returns
true if the matrix is diagonally dominant, false otherwise.
{
     if (!MyBLAS::isSquareMatrix(A)) {
         return false;
     }
     const size_t n = A.getRows(); // or A.getCols(), since A is a square matrix
     // Iterate over the rows of the input matrix A
     for (size_t i = 0; i < n; i++) {
         T sum = 0;
         // Iterate over the columns of the input matrix A
         for (size_t j = 0; j < n; j++) {
             // Skip the diagonal element
             if (i != j) {
                 sum += std::abs(A[i][j]);
             }
         }
         // Check if the absolute value of the diagonal element is less than or equal to the sum
         if (std::abs(A[i][i]) <= sum) {
             return false;
         }
     }
     return true;
 }
References MyMath::abs(), i, isSquareMatrix(), n, and MyBLAS::Stats::sum().
Referenced by MyBLAS::System::Circuit(), MyRelaxationMethod::passesPreChecks(), and TYPED_TEST().
isEmptyMatrix()
template<typename MatrixType > bool MyBLAS::isEmptyMatrix (const MatrixType & M) inline
Checks if the given matrix is empty.
This function checks if the input matrix has empty rows or columns.
Parameters
M The input matrix to be checked.
Returns
true if the input matrix is empty, false otherwise.
{
     return M.getRows() == 0 || M.getCols() == 0;
 }
References MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
Referenced by MyFactorizationMethod::passesPreChecks(), MyRelaxationMethod::passesPreChecks(), and TYPED_TEST().
isEmptyVector()
template<typename VectorType > bool MyBLAS::isEmptyVector (const VectorType & V) inline
Checks if the given vector is empty.
This function checks if the input vector has no items.
Parameters
V The input vector to be checked.
Returns
true if the input vector is empty, false otherwise.
{
     return V.size() == 0;
 }
isPermutationMatrix()
template<template< typename > class U, typename T > bool MyBLAS::isPermutationMatrix (const U< T > & P)
Checks if the given matrix is a valid permutation matrix.
This function checks if the input matrix is square, binary, and if each row and each column has exactly one element equal to 1.
Parameters
P The input matrix to be checked.
Returns
true if the input matrix is a valid permutation matrix, false otherwise.
{
     static_assert(std::is_same<U<T>, MyBLAS::Matrix<T>>::value, "U must be a MyBLAS::Matrix type");
     if (!MyBLAS::isSquareMatrix(P)) {
         return false;
     }
     if (!MyBLAS::isBinaryMatrix(P)) {
         return false;
     }
     const size_t rows = P.getRows();
     const size_t cols = P.getCols();
     // Initialize row and column counters
     std::vector<size_t> rowOnesCount(rows, 0);
     std::vector<size_t> colOnesCount(cols, 0);
     // Iterate over the matrix and update the counters
     for (size_t i = 0; i < rows; i++) {
         for (size_t j = 0; j < cols; j++) {
             // NANs and +inf, -inf make the matrix invalid
             if (std::isinf(P[i][j]) || std::isnan(P[i][j])) {
                 return false;
             }
             if (P[i][j] == 1) {
                 rowOnesCount[i]++;
                 colOnesCount[j]++;
             }
         }
     }
     // Check if each row and each column has exactly one element equal to 1
     for (size_t i = 0; i < rows; i++) {
         if (rowOnesCount[i] != 1 || colOnesCount[i] != 1) {
             return false;
         }
     }
     return true;
 }
References i, isBinaryMatrix(), and isSquareMatrix().
Referenced by Parser::buildInputs(), naive_solve_linear_system(), MyFactorizationMethod::passesPostChecks(), OutLab5::run(), and TYPED_TEST().
isPositiveDefiniteMatrix()
template<template< typename > class M, typename T > bool MyBLAS::isPositiveDefiniteMatrix (const M< T > & A)
Checks if the given matrix is positive definite using Cholesky decomposition.
This function attempts to perform Cholesky decomposition on the input matrix. If the decomposition can be completed without encountering any non-positive elements on the diagonal, the matrix is considered positive definite.
Template Parameters
T The data type of the matrix elements.
Parameters
A The input matrix to be checked.
Returns
true if the input matrix is positive definite, false otherwise.
{
     // Check if the matrix is square
     if (!MyBLAS::isSquareMatrix(A)) {
         return false;
     }
     const size_t n = A.getRows();
     M<T> L(n, n, static_cast<T>(0)); // Initialize lower triangular matrix
     for (size_t i = 0; i < n; ++i) {
         for (size_t j = 0; j <= i; ++j) {
             T sum = 0;
             if (j == i) { // Diagonal elements
                 for (size_t k = 0; k < j; k++) {
                     sum += L[j][k] * L[j][k];
                 }
                 L[j][j] = A[j][j] - sum;
                 // If the diagonal element is not positive, the matrix is not positive definite
                 if (L[j][j] <= static_cast<T>(0)) {
                     return false;
                 }
                 L[j][j] = std::sqrt(L[j][j]);
             } else { // Off-diagonal elements
                 for (size_t k = 0; k < j; ++k) {
                     sum += L[i][k] * L[j][k];
                 }
                 if (L[j][j] == static_cast<T>(0)) {
                     return false; // This would imply division by zero
                 }
                 L[i][j] = (A[i][j] - sum) / L[j][j];
             }
         }
     }
     return true; // The matrix is positive definite if Cholesky decomposition is successful
 }
References i, isSquareMatrix(), k, L(), n, and MyBLAS::Stats::sum().
Referenced by Parser::buildInputs(), and TYPED_TEST().
isSquareMatrix()
template<typename MatrixType > bool MyBLAS::isSquareMatrix (const MatrixType & M) inline
Checks if the given matrix is a square matrix.
This function checks if the input matrix has an equal number of rows and columns.
Parameters
M The input matrix to be checked.
Returns
true if the input matrix is a square matrix, false otherwise.
{
     return M.getRows() > 0 && M.getCols() == M.getRows();
 }
References MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
Referenced by Parser::buildInputs(), isDiagonallyDominant(), isPermutationMatrix(), isPositiveDefiniteMatrix(), isSymmetricMatrix(), isUnitLowerTriangularMatrix(), isUpperTriangularMatrix(), MyFactorizationMethod::passesPreChecks(), MyRelaxationMethod::passesPreChecks(), and TYPED_TEST().
isSymmetricMatrix()
template<template< typename > class M, typename T > bool MyBLAS::isSymmetricMatrix (const M< T > & A, const T tolerance = 0)
Checks if the given matrix is symmetric.
This function checks if the input matrix is equal to its transpose.
Parameters
A The input matrix to be checked.
A For floating-point values, check within a given tolerance
Returns
true if the input matrix is symmetric, false otherwise.
{
     // Check if the matrix is square
     if (!MyBLAS::isSquareMatrix(A)) {
         return false;
     }
     const size_t n = A.getRows();
     if (tolerance == 0) {
         // Check if the matrix is equal to its transpose
         for (size_t i = 0; i < n; i++) {
             for (size_t j = i + 1 ; j < n; j++) {
                 if (A[i][j] != A[j][i]) {
                     return false;
                 }
             }
         }
     } else {
         const T threshold = std::numeric_limits<T>::epsilon() * tolerance;
         // Check if the matrix is equal to its transpose, within a margin
         for (size_t i = 0; i < n; i++) {
             for (size_t j = i + 1; j < n; j++) {
                 if (std::abs(A[i][j] - A[j][i]) > threshold) {
                     return false;
                 }
             }
         }
     }
     return true;
 }
References MyMath::abs(), i, isSquareMatrix(), and n.
Referenced by Parser::buildInputs(), and TYPED_TEST().
isUnitLowerTriangularMatrix()
template<template< typename > class U, typename T > bool MyBLAS::isUnitLowerTriangularMatrix (const U< T > & L)
Checks if the given matrix is a valid unit lower triangular matrix.
This function checks if the input matrix is square, if all elements above the main diagonal are zero, and if all elements on the main diagonal are one. If these conditions are met, the matrix is considered a valid unit lower triangular matrix.
Parameters
L The input matrix to be checked.
Returns
true if the input matrix is a valid unit lower triangular matrix, false otherwise.
{
     static_assert(std::is_same<U<T>, MyBLAS::Matrix<T>>::value, "U must be a MyBLAS::Matrix type");
     if (!MyBLAS::isSquareMatrix(L)) {
         return false;
     }
     const size_t cols = L.getCols();
     const size_t rows = L.getRows();
     // Iterate over the rows of the input matrix L
     for (size_t i = 0; i < rows; i++) {
         // Iterate over the cols of the input matrix L
         for (size_t j = 0; j < cols; j++) {
             // NANs and +inf, -inf make the matrix invalid
             if (std::isinf(L[i][j]) || std::isnan(L[i][j])) {
                 return false;
             }
             // leading diagonal is always 1
             if (i == j && L[i][j] != 1) {
                 return false;
             }
             // upper triangular is always 0
             if (i < j && L[i][j] != 0) {
                 return false;
             }
         }
     }
     return true;
 }
References i, isSquareMatrix(), and L().
Referenced by Parser::buildInputs(), naive_solve_linear_system(), MyFactorizationMethod::passesPostChecks(), OutLab4::run(), OutLab5::run(), TEST_P(), and TYPED_TEST().
isUnitVector()
template<template< typename > class U, typename T > bool MyBLAS::isUnitVector (const U< T > & V)
Checks if the given vector is a unit vector.
This function checks if all elements of the input vector are 1.
Parameters
V The input vector to be checked.
Returns
true if the input vector is a unit vector, false otherwise.
{
     return norm(V) == norm(V/norm(V));
 }
References norm().
Referenced by TYPED_TEST().
isUpperTriangularMatrix()
template<template< typename > class U, typename T > bool MyBLAS::isUpperTriangularMatrix (const U< T > & M)
Checks if the given matrix is a valid upper triangular matrix.
This function checks if the input matrix is square and if all elements below the main diagonal are zero. If these conditions are met, the matrix is considered a valid upper triangular matrix.
Parameters
U The input matrix to be checked.
Returns
true if the input matrix is a valid upper triangular matrix, false otherwise.
{
     static_assert(std::is_same<U<T>, MyBLAS::Matrix<T>>::value, "U must be a MyBLAS::Matrix type");
     if (!MyBLAS::isSquareMatrix(M)) {
         return false;
     }
     const size_t cols = M.getCols();
     const size_t rows = M.getRows();
     // Iterate over the rows of the input matrix U
     for (size_t i = 0; i < rows; i++) {
         // Iterate over the cols of the input matrix U
         for (size_t j = 0; j < cols; j++) {
             // NANs and +inf, -inf make the matrix invalid
             if (std::isinf(M[i][j]) || std::isnan(M[i][j])) {
                 return false;
             }
             // Lower triangular is always 0
             if (i > j && M[i][j] != 0) {
                 return false;
             }
         }
     }
     return true;
 }
References i, and isSquareMatrix().
Referenced by Parser::buildInputs(), naive_solve_linear_system(), MyFactorizationMethod::passesPostChecks(), OutLab4::run(), OutLab5::run(), TEST_P(), and TYPED_TEST().
isValidUnitLowerTriangularMatrix()
template<typename T > static bool MyBLAS::isValidUnitLowerTriangularMatrix (const MyBLAS::Matrix< T > & L) static
Checks if the given matrix is a valid unit lower triangular matrix.
This function checks if the input matrix is square, if all elements above the main diagonal are zero, and if all elements on the main diagonal are one. If these conditions are met, the matrix is considered a valid unit lower triangular matrix.
Parameters
L The input matrix to be checked.
Returns
true if the input matrix is a valid unit lower triangular matrix, false otherwise.
{
     const size_t cols = L.getCols();
     const size_t rows = L.getRows();
     // Check if the matrix is square
     if (cols != rows) {
         return false;
     }
     // Iterate over the rows of the input matrix L
     for (size_t i = 0; i < rows; i++) {
         // Iterate over the cols of the input matrix L
         for (size_t j = 0; j < cols; j++) {
             // leading diagonal is always 1
             if (i == j && L[i][j] != 1) {
                 return false;
             }
             // upper triangular is always 0
             if (i < j && L[i][j] != 0) {
                 return false;
             }
         }
     }
     return true;
 }
References i, and L().
isValidUpperTriangularMatrix()
template<typename T > static bool MyBLAS::isValidUpperTriangularMatrix (const MyBLAS::Matrix< T > & U) static
Checks if the given matrix is a valid upper triangular matrix.
This function checks if the input matrix is square and if all elements below the main diagonal are zero. If these conditions are met, the matrix is considered a valid upper triangular matrix.
Parameters
U The input matrix to be checked.
Returns
true if the input matrix is a valid upper triangular matrix, false otherwise.
{
     const size_t cols = U.getCols();
     const size_t rows = U.getRows();
     // Check if the matrix is square
     if (cols != rows) {
         return false;
     }
     // Iterate over the rows of the input matrix U
     for (size_t i = 0; i < rows; i++) {
         // Iterate over the cols of the input matrix U
         for (size_t j = 0; j < cols; j++) {
             // Lower triangular is always 0
             if (i > j && U[i][j] != 0) {
                 return false;
             }
         }
     }
     return true;
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
isZeroVector()
template<template< typename > class U, typename T > bool MyBLAS::isZeroVector (const U< T > & V)
Checks if the given vector is a zero vector.
This function checks if all elements of the input vector are 0.
Parameters
V The input vector to be checked.
Returns
true if the input vector is a zero vector, false otherwise.
{
     const size_t items = V.size();
     for (size_t i = 0; i < items; i++) {
         if (V[i] != 0) {
             return false;
         }
     }
     return true;
 }
References i.
Referenced by TYPED_TEST().
L2() [1/2]
template<typename T > T MyBLAS::L2 (const MyBLAS::Vector< T > & a, const MyBLAS::Vector< T > & b)
Overloaded function that calculates the L2 norm (Euclidean distance) between two MyBLAS::Vector objects.
This function uses the L2Norm function defined above to calculate the L2 norm. The size of the vectors is determined by the smaller of the two vectors.
Template Parameters
T The type of the data contained in the vectors. This should be a type that supports subtraction and multiplication.
Parameters
a The first vector.
b The second vector.
Returns
The L2 norm (Euclidean distance) between the two vectors.
{
     const size_t n = std::min(a.size(), b.size());
     return MyBLAS::L2(a, b, n);
 }
References L2(), MyBLAS::Stats::min(), n, and MyBLAS::Vector< T >::size().
L2() [2/2]
template<template< typename > class VectorType, typename T > T MyBLAS::L2 (const VectorType< T > & a, const VectorType< T > & b, const size_t n) inline
Calculates the L2 norm of the distance (Euclidean distance) between two containers.
For real numbers, the L2 norm is defined as sqrt(sum(v[i] * v[i])). For complex numbers, the L2 norm is defined as sqrt(sum(v[i] * conj(v[i]))).
Template Parameters
ContainerType The type of the containers. This should be a container type that supports indexing with the [] operator.
DataType The type of the data contained in the containers. This should be a type that supports subtraction and multiplication.
Parameters
a The first container.
b The second container.
n The size of the containers. This function assumes that both containers have the same size.
Returns
The L2 norm of the distance (Euclidean distance) between the two containers.
{
     T norm = 0;
     const T two = static_cast<T>(2);
 //    #pragma omp parallel for reduction(+:norm)
     for (size_t i = 0; i < n; i++) {
         const auto difference = a[i] - b[i];
         const auto squared = std::pow(difference, two);
         norm += squared;
     }
     return norm;
 }
References i, n, norm(), and MyMath::pow().
Referenced by MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), Output::getSolutionError(), L2(), and TYPED_TEST().
makeDiagonallyDominant()
template<typename T > void MyBLAS::makeDiagonallyDominant (MyBLAS::Matrix< T > & A, const T dominance_offset = 1)
Makes the given matrix diagonally dominant.
This function modifies the input matrix such that the absolute value of each diagonal element is greater than the sum of the absolute values of the other elements in the same row.
Parameters
A The input matrix to be modified.
dominance_offset The offset to be added to the diagonal elements to make the matrix diagonally dominant.
{
     const size_t n = A.getRows(); // or A.getCols(), since A is a square matrix
     // Iterate over the rows of the input matrix A
     for (size_t row = 0; row < n; row++) {
         T nonDiagonalSum = 0;
         // Iterate over the columns of the input matrix A
         for (size_t col = 0; col < n; col++) {
             nonDiagonalSum += std::abs(A[row][col]);
         }
         // get the diagonal value
         const T leadingDiagonalMagnitude = std::abs(A[row][row]);
         nonDiagonalSum -= leadingDiagonalMagnitude; // Subtract the diagonal element
         if (leadingDiagonalMagnitude < nonDiagonalSum) {
             const T sign = (leadingDiagonalMagnitude == A[row][row]) ? 1 : -1; // retain the sign
             A[row][row] = sign * (nonDiagonalSum + dominance_offset);
         }
     }
 }
References MyMath::abs(), MyBLAS::Matrix< T >::getRows(), n, and process::row.
Referenced by MyBLAS::System::Circuit().
matrixWeightedInnerProduct()
template<template< typename > class M, template< typename > class V, typename T > T MyBLAS::matrixWeightedInnerProduct (const V< T > & y, const V< T > & z, const M< T > & A)
{
     assert(y.size() == A.getRows() && z.size() == A.getCols());
     return y * (A * z);
 }
References y, and z.
Referenced by TYPED_TEST().
norm()
template<typename T > T MyBLAS::norm (const MyBLAS::Vector< T > & v)
A template function to calculate the norm of a vector.
The norm is calculated as the square root of the sum of the squares of the vector elements.
Template Parameters
T The type of the vector elements.
Parameters
v The vector whose norm is to be calculated.
Returns
The norm of the vector.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     T sum = 0;
     for (size_t i = 0; i < v.size(); ++i) {
         sum += std::pow(v[i], static_cast<T>(2));
     }
     return std::sqrt(sum);
 }
References i, MyMath::pow(), MyBLAS::Vector< T >::size(), and MyBLAS::Stats::sum().
Referenced by isUnitVector(), juliaSetIterations(), L2(), InLab4::printMandelbrotSet(), and TYPED_TEST().
noZerosInDiagonal()
template<template< typename > class U, typename T > bool MyBLAS::noZerosInDiagonal (const U< T > & A)
Checks if there are no zeros in the diagonal of a matrix.
This function uses the allDiagonalElementsBelowThreshold function to check if there are no zeros in the diagonal of the input matrix A.
Template Parameters
T The data type of the matrix elements.
Parameters
A The input matrix to be checked.
Returns
true if there are no zeros in the diagonal, false otherwise.
{
     return !MyBLAS::allDiagonalElementsBelowThreshold(A, static_cast<T>(0));
 }
References allDiagonalElementsBelowThreshold().
Referenced by MyRelaxationMethod::passesPreChecks(), and TYPED_TEST().
operator*() [1/2]
template<typename T > MyBLAS::Vector<T> MyBLAS::operator* (const T & scalar, const MyBLAS::Vector< T > & vector)
‍**
‍**
Global function to multiply a scalar with a vector.
Parameters
scalar Scalar to multiply the matrix with.
matrix Vector to be multiplied.
Returns
Resultant matrix after multiplication.
{
     return vector * scalar;
 }
operator*() [2/2]
template<typename DataType > MyBLAS::Vector<DataType> MyBLAS::operator* (MyBLAS::Vector< DataType > const & a, LazyMatrix< DataType > const & b) delete
This function template is a placeholder for vector-matrix multiplication in the MyBLAS library.
This function is currently not implemented and is marked for deletion. It is intended to perform multiplication of a vector and a lazy matrix.
Template Parameters
DataType The type of data contained in the vector and the lazy matrix.
Parameters
a A constant reference to the vector.
b A constant reference to the lazy matrix.
Returns
This function does not return a value as it is marked for deletion.
Note
This function is marked as deleted and will cause a compile error if used.
operator+()
template<typename T > MyBLAS::Vector<T> MyBLAS::operator+ (const T & scalar, const MyBLAS::Vector< T > & vector)
Global function to add a scalar to a vector.
Parameters
scalar Scalar to add to the matrix.
matrix Vector to be added to.
Returns
Resultant matrix after addition.
{
     return vector + scalar;
 }
operator/()
template<template< typename > class ContainerType1, template< typename > class ContainerType2, typename T > ContainerType1<T> MyBLAS::operator/ (ContainerType1< T > const & a, ContainerType2< T > const & b) delete
This function template is a placeholder for vector-vector division in the MyBLAS library.
This function is currently not implemented and is marked for deletion. It is intended to perform division of a vector with another.
Template Parameters
DataType The type of data contained in the vectors
Parameters
a A constant reference to the vector.
b A constant reference to the other vector
Returns
This function does not return a value as it is marked for deletion.
Note
This function is marked as deleted and will cause a compile error if used.
TEST_F() [1/41]
MyBLAS::TEST_F (LazyVectorTests , AdditionTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     auto v3 = v1 + v2;
     for (size_t i = 0; i < v3.size(); ++i) {
         EXPECT_TRUE(IsClose(v3[i], static_cast<FLOAT_TYPE>(i + i * i)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [2/41]
MyBLAS::TEST_F (LazyVectorTests , AssignmentTest)
{
     MyBLAS::LazyVector<float> v1(10, [](size_t i) { return static_cast<float>(i); });
     MyBLAS::LazyVector<float> v2(10, [](size_t i) { return static_cast<float>(i) * static_cast<float>(i); });
     // Check that v1 and v2 are different
     EXPECT_NE(v1, v2);
     // Assign v2 to v1
     v1 = v2;
     // Now v1 and v2 should be equal
     EXPECT_EQ(v1, v2);
 }
References i.
TEST_F() [3/41]
MyBLAS::TEST_F (LazyVectorTests , DotProductTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     auto accumulated = v1 * v2;
     FLOAT_TYPE result = 0;
     for (size_t i = 0; i < v1.size(); i++) {
         result += v1[i] * v2[i];
     }
     EXPECT_EQ(accumulated, result);
 }
References FLOAT_TYPE, and i.
TEST_F() [4/41]
MyBLAS::TEST_F (LazyVectorTests , ElementAccessTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     for (size_t i = 0; i < v.size(); ++i) {
         EXPECT_TRUE(IsClose(v[i], static_cast<FLOAT_TYPE>(i * i)));
     }
 }
References FLOAT_TYPE, and i.
TEST_F() [5/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseAdditionAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i){ return static_cast<FLOAT_TYPE>(i) * static_cast<FLOAT_TYPE>(i); });
     v1 += v2;
     for (size_t i = 0; i < v1.size(); ++i) {
         const auto fi = static_cast<FLOAT_TYPE>(i);
         EXPECT_TRUE(IsClose(v1[i], static_cast<FLOAT_TYPE>(fi + fi * fi)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [6/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseScalarAdditionAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     v += static_cast<FLOAT_TYPE>(5);
     for (size_t i = 0; i < v.size(); ++i) {
         EXPECT_TRUE(IsClose(v[i], static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(5)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [7/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseScalarDivisionAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1); });
     v /= static_cast<FLOAT_TYPE>(5);
     for (size_t i = 0; i < v.size(); ++i) {
         EXPECT_TRUE(IsClose(v[i], static_cast<FLOAT_TYPE>((static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1)) / static_cast<FLOAT_TYPE>(5))));
     }
 }
References FLOAT_TYPE, and i.
TEST_F() [8/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseScalarMultiplicationAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     v *= static_cast<FLOAT_TYPE>(5);
     for (size_t i = 0; i < v.size(); ++i) {
         EXPECT_TRUE(IsClose(v[i], static_cast<FLOAT_TYPE>(i) * static_cast<FLOAT_TYPE>(5)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [9/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseScalarSubtractionAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     v -= static_cast<FLOAT_TYPE>(5);
     for (size_t i = 0; i < v.size(); ++i) {
         EXPECT_TRUE(IsClose(v[i], static_cast<FLOAT_TYPE>(i) - static_cast<FLOAT_TYPE>(5)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [10/41]
MyBLAS::TEST_F (LazyVectorTests , ElementWiseSubtractionAssignmentTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) * static_cast<FLOAT_TYPE>(i); });
     v1 -= v2;
     for (size_t i = 0; i < v1.size(); ++i) {
         const auto fi = static_cast<FLOAT_TYPE>(i);
         EXPECT_TRUE(IsClose(v1[i], static_cast<FLOAT_TYPE>(fi - fi * fi)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [11/41]
MyBLAS::TEST_F (LazyVectorTests , EqualityInequalityTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v3(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) * static_cast<FLOAT_TYPE>(i); });
     EXPECT_EQ(v1, v2);
     EXPECT_NE(v1, v3);
 }
References FLOAT_TYPE, and i.
TEST_F() [12/41]
MyBLAS::TEST_F (LazyVectorTests , InPlaceAdditionTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     v1 += v2;
     for (size_t i = 0; i < v1.size(); ++i) {
         EXPECT_TRUE(IsClose(v1[i], static_cast<FLOAT_TYPE>(i + i * i)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [13/41]
MyBLAS::TEST_F (LazyVectorTests , InPlaceSubtractionTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     v1 -= v2;
     for (size_t i = 0; i < v1.size(); ++i) {
         const auto fi = static_cast<FLOAT_TYPE>(i);
         const auto value = fi - fi * fi;
         EXPECT_TRUE(IsClose(v1[i], value));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [14/41]
MyBLAS::TEST_F (LazyVectorTests , ScalarAdditionTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     auto v2 = v + 5.0;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(IsClose(v2[i], static_cast<FLOAT_TYPE>(i) + 5.0));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [15/41]
MyBLAS::TEST_F (LazyVectorTests , ScalarDivisionByZeroTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) {
         return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1);
     });
     auto v2 = v / 0.0;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(std::isinf(v2[i]));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [16/41]
MyBLAS::TEST_F (LazyVectorTests , ScalarDivisionTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1); });
     auto v2 = v / 5.0;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(IsClose(v2[i], static_cast<FLOAT_TYPE>((static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1)) / 5.0)));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [17/41]
MyBLAS::TEST_F (LazyVectorTests , ScalarMultiplicationTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     auto v2 = v * 5.0;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(IsClose(v2[i], static_cast<FLOAT_TYPE>(i) * 5.0));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [18/41]
MyBLAS::TEST_F (LazyVectorTests , ScalarSubtractionTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     auto v2 = v - 5.0;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(IsClose(v2[i], static_cast<FLOAT_TYPE>(i) - 5.0));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [19/41]
MyBLAS::TEST_F (LazyVectorTests , SizeTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     EXPECT_EQ(v.size(), 10);
 }
References FLOAT_TYPE, and i.
TEST_F() [20/41]
MyBLAS::TEST_F (LazyVectorTests , SubtractionAdditionNegationTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1); });
     auto v3 = v1 - v2;
     auto v4 = v1 + (-v2);
     for (size_t i = 0; i < v3.size(); ++i) {
         EXPECT_TRUE(IsClose(v3[i], v4[i]));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [21/41]
MyBLAS::TEST_F (LazyVectorTests , SubtractionTest)
{
     LazyVector<FLOAT_TYPE> v1(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i); });
     LazyVector<FLOAT_TYPE> v2(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i * i); });
     auto v3 = v1 - v2;
     for (size_t i = 0; i < v3.size(); ++i) {
         const auto fi = static_cast<FLOAT_TYPE>(i);
         const auto value = fi - fi * fi;
         SCOPED_TRACE("i = " + std::to_string(i) + ",v3[i] = "+std::to_string(v3[i])+", value = "+std::to_string(value));
         EXPECT_TRUE(IsClose(v3[i], value));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [22/41]
MyBLAS::TEST_F (LazyVectorTests , UnaryNegationTest)
{
     LazyVector<FLOAT_TYPE> v(10, [](size_t i) { return static_cast<FLOAT_TYPE>(i) + static_cast<FLOAT_TYPE>(1); });
     auto v2 = -v;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_TRUE(IsClose(v2[i], -v[i]));
     }
 }
References FLOAT_TYPE, i, and MyBLAS::LazyVector< DataType >::size().
TEST_F() [23/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpression)
{
     // Define two simple lambda functions as operands
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i + j; };
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a * b; };
     // Create a ElementwiseExpression
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator()
     EXPECT_EQ(expr(1, 2), 9);  // (1+2) * (1+2) = 9
     EXPECT_EQ(expr(3, 4), 49);  // (3+4) * (3+4) = 49
 }
References i.
TEST_F() [24/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithDifferentBinaryOp)
{
     // Define two simple lambda functions as operands
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i - j; };
     // Define a different binary operation
     auto binary_op = [](auto a, auto b) { return a + b; };
     // Create a ElementwiseExpression
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator()
     EXPECT_EQ(expr(1, 2), 2);  // (1+2) + (1-2) = 2
     EXPECT_EQ(expr(3, 4), 6);  // (3+4) + (3-4) = 6
 }
References i.
TEST_F() [25/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithDivision)
{
     auto op1 = [](size_t i, size_t j) { return static_cast<double>(i + j); };
     auto op2 = [](size_t i, size_t j) { return static_cast<double>(i * j); };
     auto binary_op = [](auto a, auto b) { return a / b; };
     ElementwiseExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_NEAR(expr(2, 3), 5.0/6.0, TOLERANCE);  // (2+3) / (2*3) = 5/6
     EXPECT_NEAR(expr(4, 5), 9.0/20.0, TOLERANCE);  // (4+5) / (4*5) = 9/20
 }
References i, and TOLERANCE.
TEST_F() [26/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithExp)
{
     auto op1 = [](size_t i, size_t j) { return static_cast<double>(i + j) / 10.0; };
     auto op2 = [](size_t i, size_t j) { return static_cast<double>(i * j) / 10.0; };
     auto binary_op = [](auto a, auto b) { return std::exp(a - b); };
     ElementwiseExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_DOUBLE_EQ(expr(2, 3), std::exp((2.0 + 3.0) / 10.0 - (2.0 * 3.0) / 10.0));  // exp((2+3)/10 - (2*3)/10)
     EXPECT_DOUBLE_EQ(expr(4, 5), std::exp((4.0 + 5.0) / 10.0 - (4.0 * 5.0) / 10.0));  // exp((4+5)/10 - (4*5)/10)
 }
References i.
TEST_F() [27/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithLog)
{
     auto op1 = [](size_t i, size_t j) { return i * i + j * j; };
     auto op2 = [](size_t i, size_t j) { return i * j + 1; };
     auto binary_op = [](auto a, auto b) { return std::log(a + b); };
     ElementwiseExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_DOUBLE_EQ(expr(2, 3), 2.9957322735539909);  // log((2*2 + 3*3) + (2*3 + 1)) = 2.9957322735539909
     EXPECT_DOUBLE_EQ(expr(4, 5), 4.1271343850450917);  // log((4*4 + 5*5) + (4*5 + 1)) = 4.1271343850450917
 }
References i.
TEST_F() [28/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithMax)
{
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i * j; };
     auto binary_op = [](auto a, auto b) { return std::max(a, b); };
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_EQ(expr(2, 3), 6);  // max(2+3, 2*3) = 6
     EXPECT_EQ(expr(4, 5), 20);  // max(4+5, 4*5) = 20
 }
References i, and MyBLAS::Stats::max().
TEST_F() [29/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithMin)
{
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i * j; };
     auto binary_op = [](auto a, auto b) { return std::min(a, b); };
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_EQ(expr(2, 3), 5);  // min(2+3, 2*3) = 5
     EXPECT_EQ(expr(4, 5), 9);  // min(4+5, 4*5) = 9
 }
References i, and MyBLAS::Stats::min().
TEST_F() [30/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithModulo)
{
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i * j; };
     auto binary_op = [](auto a, auto b) { return a % b; };
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_EQ(expr(2, 3), 5);  // (2+3) % (2*3) = 5
     EXPECT_EQ(expr(4, 5), 9);  // (4+5) % (4*5) = 9
 }
References i.
TEST_F() [31/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithMultiplication)
{
     auto op1 = [](size_t i, size_t j) { return i * j; };
     auto op2 = [](size_t i, size_t j) { return i + j; };
     auto binary_op = [](auto a, auto b) { return a * b; };
     ElementwiseExpression<size_t, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_EQ(expr(2, 3), 30);  // (2*3) * (2+3) = 30
     EXPECT_EQ(expr(4, 5), 180);  // (4*5) * (4+5) = 180
 }
References i.
TEST_F() [32/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithPower)
{
     auto op1 = [](size_t i, size_t j) { return i + j; };
     auto op2 = [](size_t i, size_t j) { return i * j; };
     auto binary_op = [](auto a, auto b) { return std::pow(a, b); };
     ElementwiseExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_DOUBLE_EQ(expr(2, 3), 15625);  // (2+3) ^ (2*3) = 15625
     EXPECT_DOUBLE_EQ(expr(4, 5), 1.2157665459056929e+19);  // (4+5) ^ (4*5) = 1.2157665459056929e+19
 }
References i, and MyMath::pow().
TEST_F() [33/41]
MyBLAS::TEST_F (MatrixExpressionTests , TestMatrixExpressionWithSqrt)
{
     auto op1 = [](size_t i, size_t j) { return i * i + j * j; };
     auto op2 = [](size_t i, size_t j) { return i * j; };
     auto binary_op = [](auto a, auto b) { return std::sqrt(a + b); };
     ElementwiseExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     EXPECT_DOUBLE_EQ(expr(2, 3), 4.358898943540674);  // sqrt((2*2 + 3*3) + (2*3)) = 4.358898943540674
     EXPECT_DOUBLE_EQ(expr(4, 5), 7.810249675906654);  // sqrt((4*4 + 5*5) + (4*5)) = 7.810249675906654
 }
References i.
TEST_F() [34/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpression)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::vector<int> op2 = {5, 4, 3, 2, 1};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a * b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[1], 8);  // 2 * 4 = 8
     EXPECT_EQ(expr[3], 8);  // 4 * 2 = 8
 }
TEST_F() [35/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionAddition)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::vector<int> op2 = {5, 4, 3, 2, 1};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a + b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[0], 6);  // 1 + 5 = 6
     EXPECT_EQ(expr[1], 6);  // 2 + 4 = 6
     EXPECT_EQ(expr[2], 6);  // 3 + 3 = 6
     EXPECT_EQ(expr[3], 6);  // 4 + 2 = 6
     EXPECT_EQ(expr[4], 6);  // 5 + 1 = 6
 }
TEST_F() [36/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionDivision)
{
     // Define two vectors as operands
     std::vector<double> op1 = {1.0, 2.0, 3.0, 4.0, 5.0};
     std::vector<double> op2 = {5.0, 4.0, 3.0, 2.0, 1.0};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a / b; };
     // Create a VectorExpression
     VectorExpression<double, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_NEAR(expr[0], 0.2, TOLERANCE);  // 1.0 / 5.0 = 0.2
     EXPECT_NEAR(expr[1], 0.5, TOLERANCE);  // 2.0 / 4.0 = 0.5
     EXPECT_NEAR(expr[2], 1.0, TOLERANCE);  // 3.0 / 3.0 = 1.0
     EXPECT_NEAR(expr[3], 2.0, TOLERANCE);  // 4.0 / 2.0 = 2.0
     EXPECT_NEAR(expr[4], 5.0, TOLERANCE);  // 5.0 / 1.0 = 5.0
 }
References TOLERANCE.
TEST_F() [37/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionMultiplication)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::vector<int> op2 = {5, 4, 3, 2, 1};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a * b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[0], 5);  // 1 * 5 = 5
     EXPECT_EQ(expr[1], 8);  // 2 * 4 = 8
     EXPECT_EQ(expr[2], 9);  // 3 * 3 = 9
     EXPECT_EQ(expr[3], 8);  // 4 * 2 = 8
     EXPECT_EQ(expr[4], 5);  // 5 * 1 = 5
 }
TEST_F() [38/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionSubtraction)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::vector<int> op2 = {5, 4, 3, 2, 1};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a - b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[0], -4);  // 1 - 5 = -4
     EXPECT_EQ(expr[1], -2);  // 2 - 4 = -2
     EXPECT_EQ(expr[2], 0);   // 3 - 3 = 0
     EXPECT_EQ(expr[3], 2);   // 4 - 2 = 2
     EXPECT_EQ(expr[4], 4);   // 5 - 1 = 4
 }
TEST_F() [39/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionWithDifferentBinaryOp)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::vector<int> op2 = {5, 4, 3, 2, 1};
     // Define a different binary operation
     auto binary_op = [](auto a, auto b) { return a + b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[1], 6);  // 2 + 4 = 6
     EXPECT_EQ(expr[3], 6);  // 4 + 2 = 6
 }
TEST_F() [40/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionWithDifferentVectorTypes)
{
     // Define two vectors as operands
     std::vector<int> op1 = {1, 2, 3, 4, 5};
     std::array<int, 5> op2 = {5, 4, 3, 2, 1};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a * b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the operator[]
     EXPECT_EQ(expr[0], 5);  // 1 * 5 = 5
     EXPECT_EQ(expr[1], 8);  // 2 * 4 = 8
     EXPECT_EQ(expr[2], 9);  // 3 * 3 = 9
     EXPECT_EQ(expr[3], 8);  // 4 * 2 = 8
     EXPECT_EQ(expr[4], 5);  // 5 * 1 = 5
 }
TEST_F() [41/41]
MyBLAS::TEST_F (VectorExpressionTests , TestVectorExpressionWithEmptyVectors)
{
     // Define two empty vectors as operands
     std::vector<int> op1 = {};
     std::vector<int> op2 = {};
     // Define a binary operation
     auto binary_op = [](auto a, auto b) { return a * b; };
     // Create a VectorExpression
     VectorExpression<int, decltype(op1), decltype(op2), decltype(binary_op)> expr(op1, op2, binary_op);
     // Test the size
     EXPECT_EQ(expr.size(), 0);
 }
References MyBLAS::VectorExpression< DataType, Op1, Op2, BinaryOp >::size().
TYPED_TEST() [1/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , AdditionTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2(2, 2, 2);
     Matrix<TypeParam> m3 = m1 + m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             EXPECT_EQ(m3[i][j], 3);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [2/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ChainedAssignment)
                                                {\
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2; // Default constructor
     Matrix<TypeParam> mat3; // Default constructor
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = mat3 = mat1; // Chained copy-assignment
     // Both mat2 and mat3 should now contain copies of mat1's data
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], mat1[i][j]);
             EXPECT_EQ(mat3[i][j], mat1[i][j]);
         }
     }
     // The instances set should not change in size because mat2 and mat3 already exist
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [3/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ChainedMoveAssignment)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2; // Default constructor
     Matrix<TypeParam> mat3; // Default constructor
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = mat3 = std::move(mat1); // Chained move-assignment
     // mat2 should now contain the data originally in mat1
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], 1);
         }
     }
     // mat3 should be in a valid but unspecified state
     // The instances set should not change in size because mat1, mat2, and mat3 already exist
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [4/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ConstructorTest)
{
     Matrix<TypeParam> m1(3, 3, 1);
     EXPECT_EQ(m1.getRows(), 3);
     EXPECT_EQ(m1.getCols(), 3);
     for (size_t i = 0; i < m1.getRows(); ++i) {
         for (size_t j = 0; j < m1.getCols(); ++j) {
             EXPECT_EQ(m1[i][j], 1);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [5/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , CopyAssignmentOperatorTest)
{
     // Create a matrix and fill it with some values
     Matrix<TypeParam> m1(3, 3, 1);
     for (size_t i = 0; i < m1.getRows(); ++i) {
         for (size_t j = 0; j < m1.getCols(); ++j) {
             m1[i][j] = static_cast<TypeParam>(i * m1.getCols() + j);
         }
     }
     // Use the copy assignment operator
     Matrix<TypeParam> m2;
     m2 = m1;
     // Check if the copy was successful
     EXPECT_EQ(m2.getRows(), m1.getRows());
     EXPECT_EQ(m2.getCols(), m1.getCols());
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], m1[i][j]);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [6/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , CopyAssignmentToExistingObject)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2(3, 3, 2); // mat2 owns some resources
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = mat1; // Copy-assignment operator is called
     EXPECT_EQ(mat2.getRows(), mat1.getRows());
     EXPECT_EQ(mat2.getCols(), mat1.getCols());
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], mat1[i][j]);
         }
     }
     // The instances set should not change in size because mat2 already exists
     EXPECT_EQ(initialCount, this->map->getCurrentInstanceCount());
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [7/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , CopyAssignmentToNewObject)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2; // Default constructor
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = mat1; // Copy-assignment operator is called
     EXPECT_EQ(mat2.getRows(), mat1.getRows());
     EXPECT_EQ(mat2.getCols(), mat1.getCols());
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], mat1[i][j]);
         }
     }
     // The instances set should not change in size because mat2 already exists
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [8/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , CopyConstructorTest)
{
     Matrix<TypeParam> m1(2, 2, static_cast<TypeParam>(5));
     Matrix<TypeParam> m2(m1);
     EXPECT_EQ(m2.getRows(), 2);
     EXPECT_EQ(m2.getCols(), 2);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], static_cast<TypeParam>(5));
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [9/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , DefaultConstructorTest)
{
     Matrix<TypeParam> m;
     EXPECT_EQ(m.getRows(), 0);
     EXPECT_EQ(m.getCols(), 0);
 }
References m.
TYPED_TEST() [10/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , EmptyMatrixTest)
{
     Matrix<TypeParam> m1;
     EXPECT_EQ(m1.getRows(), 0);
     EXPECT_EQ(m1.getCols(), 0);
 }
References MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
TYPED_TEST() [11/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , EqualityTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2(2, 2, 1);
     EXPECT_TRUE(m1 == m2);
 }
TYPED_TEST() [12/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , IdentityMatrixTest)
{
     Matrix<TypeParam> m1 = Matrix<TypeParam>::eye(3);
     for (size_t i = 0; i < m1.getRows(); ++i) {
         for (size_t j = 0; j < m1.getCols(); ++j) {
             if (i == j) {
                 EXPECT_EQ(m1[i][j], 1);
             } else {
                 EXPECT_EQ(m1[i][j], 0);
             }
         }
     }
 }
References MyBLAS::Matrix< T >::eye(), MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [13/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InequalityTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2(2, 2, 2);
     EXPECT_FALSE(m1 == m2);
 }
TYPED_TEST() [14/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InitializerListConstructorTest)
{
     Matrix<TypeParam> m({
         {static_cast<TypeParam>(1), static_cast<TypeParam>(2)},
         {static_cast<TypeParam>(3), static_cast<TypeParam>(4)}
     });
     EXPECT_EQ(m.getRows(), 2);
     EXPECT_EQ(m.getCols(), 2);
     EXPECT_EQ(m[0][0], static_cast<TypeParam>(1));
     EXPECT_EQ(m[0][1], static_cast<TypeParam>(2));
     EXPECT_EQ(m[1][0], static_cast<TypeParam>(3));
     EXPECT_EQ(m[1][1], static_cast<TypeParam>(4));
 }
References m.
TYPED_TEST() [15/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InstanceTrackingOnConstruction)
{
     this->map->clear();
 //    size_t initialCount = this->map->getCurrentInstanceCount();
     {
         Matrix<TypeParam> m(2, 2, 1);
  //       EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount + 1);
     }
     // After destruction, the instance should not be removed
 //    EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount + 1);
 }
References m.
TYPED_TEST() [16/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InstanceTrackingOnCopyAssignment)
{
     this->map->clear();
     Matrix<TypeParam> m1(2, 2, 1);
 //    size_t initialCount = this->map->getCurrentInstanceCount();
     Matrix<TypeParam> m2 = m1;
 //    EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount + 1);
 }
TYPED_TEST() [17/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InstanceTrackingOnCopyConstruction)
{
     this->map->clear();
     Matrix<TypeParam> m1(2, 2, 1);
 //    size_t initialCount = this->map->getCurrentInstanceCount();
     Matrix<TypeParam> m2(m1);
 //    EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount + 1);
 }
TYPED_TEST() [18/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InstanceTrackingOnMoveAssignment)
{
     this->map->clear();
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2;
     size_t initialCount = this->map->getCurrentInstanceCount();
     m2 = std::move(m1);
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
TYPED_TEST() [19/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , InstanceTrackingOnMoveConstruction)
{
     this->map->clear();
     Matrix<TypeParam> m1(2, 2, 1);
 //    size_t initialCount = this->map->getCurrentInstanceCount();
     Matrix<TypeParam> m2(std::move(m1));
 //    EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount + 1);
 }
TYPED_TEST() [20/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , LambdaFunctionConstructorTest)
{
     Matrix<TypeParam> m(2, 2, [](size_t i, size_t j) { return static_cast<TypeParam>(i + j); });
     EXPECT_EQ(m.getRows(), 2);
     EXPECT_EQ(m.getCols(), 2);
     EXPECT_EQ(m[0][0], static_cast<TypeParam>(0));
     EXPECT_EQ(m[0][1], static_cast<TypeParam>(1));
     EXPECT_EQ(m[1][0], static_cast<TypeParam>(1));
     EXPECT_EQ(m[1][1], static_cast<TypeParam>(2));
 }
References i, and m.
TYPED_TEST() [21/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , LeftSideScalarMultiplicationTest)
{
     Matrix<TypeParam> m1(2, 2, 2);
     Matrix<TypeParam> m2 = 2 * m1;
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 4);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [22/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MatrixVectorMultiplicationTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Vector<TypeParam> v1(2, 2);
     Vector<TypeParam> v2 = m1 * v1;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_EQ(v2[i], 4);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [23/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MoveAssignmentOperatorTest)
{
     // Create a matrix and fill it with some values
     Matrix<TypeParam> m1(3, 3, 1);
     for (size_t i = 0; i < m1.getRows(); ++i) {
         for (size_t j = 0; j < m1.getCols(); ++j) {
             m1[i][j] = static_cast<TypeParam>(i * m1.getCols() + j);
         }
     }
     // Keep a copy of the original data for comparison
     Matrix<TypeParam> original = m1;
     // Use the move assignment operator
     Matrix<TypeParam> m2;
     m2 = std::move(m1);
     // Check if the move was successful
     EXPECT_EQ(m2.getRows(), original.getRows());
     EXPECT_EQ(m2.getCols(), original.getCols());
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], original[i][j]);
         }
     }
     // The moved-from matrix (m1) should be in a valid but unspecified state
     // It's not safe to make assumptions about its content, but it should be safe to use
     // For example, we can check if it's empty or we can assign a new value to it
     m1 = Matrix<TypeParam>(2, 2, 2); // This should not throw or cause undefined behavior
     EXPECT_EQ(m1.getRows(), 2);
     EXPECT_EQ(m1.getCols(), 2);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [24/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MoveAssignmentToExistingObject)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2(3, 3, 2); // mat2 owns some resources
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = std::move(mat1); // Move-assignment operator is called
     EXPECT_EQ(mat2.getRows(), 2);
     EXPECT_EQ(mat2.getCols(), 2);
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], 1);
         }
     }
     // The instances set should not change in size because mat1 and mat2 already exist
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [25/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MoveAssignmentToNewObject)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     Matrix<TypeParam> mat2; // Default constructor
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat2 = std::move(mat1); // Move-assignment operator is called
     EXPECT_EQ(mat2.getRows(), 2);
     EXPECT_EQ(mat2.getCols(), 2);
     for (size_t i = 0; i < mat2.getRows(); ++i) {
         for (size_t j = 0; j < mat2.getCols(); ++j) {
             EXPECT_EQ(mat2[i][j], 1);
         }
     }
     // The instances set should not change in size because mat1 and mat2 already exist
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [26/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MoveConstructorTest)
{
     Matrix<TypeParam> m1(2, 2, static_cast<TypeParam>(5));
     Matrix<TypeParam> m2(std::move(m1));
     EXPECT_EQ(m2.getRows(), 2);
     EXPECT_EQ(m2.getCols(), 2);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], static_cast<TypeParam>(5));
         }
     }
     // After move, m1 should be empty
     EXPECT_EQ(m1.getRows(), 0);
     EXPECT_EQ(m1.getCols(), 0);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [27/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , MultiplicationTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2(2, 2, 2);
     Matrix<TypeParam> m3 = m1 * m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             EXPECT_EQ(m3[i][j], 4);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [28/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , NonSquareMatrixTest)
{
     Matrix<TypeParam> m1(2, 3, 1);
     EXPECT_EQ(m1.getRows(), 2);
     EXPECT_EQ(m1.getCols(), 3);
 }
References MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
TYPED_TEST() [29/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , RightSideScalarMultiplicationTest)
{
     Matrix<TypeParam> m1(2, 2, 2);
     Matrix<TypeParam> m2 = m1 * 2;
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 4);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [30/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ScalarAdditionTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     Matrix<TypeParam> m2 = m1 + 1;
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 2);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [31/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ScalarDivisionTest)
{
     Matrix<TypeParam> m1(2, 2, 2);
     Matrix<TypeParam> m2 = m1 / 2;
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 1);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [32/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ScalarMultiplicationSymmetryTest)
{
     Matrix<TypeParam> m1(2, 2, 2);
     Matrix<TypeParam> m2 = 2 * m1;
     Matrix<TypeParam> m3 = m1 * 2;
     // EXPECT_TRUE(m2 == m3);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_TRUE(m2[i][j] == m3[i][j]);
             EXPECT_EQ(m2[i][j], m3[i][j]);
             EXPECT_EQ(m2[i][j], 4);
             EXPECT_EQ(m3[i][j], 4);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [33/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ScalarSubtractionTest)
{
     Matrix<TypeParam> m1(2, 2, 2);
     Matrix<TypeParam> m2 = m1 - 1;
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 1);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [34/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SelfAssignment)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat1 = mat1; // Self-assignment
     // The matrix should remain unchanged after self-assignment
     for (size_t i = 0; i < mat1.getRows(); ++i) {
         for (size_t j = 0; j < mat1.getCols(); ++j) {
             EXPECT_EQ(mat1[i][j], 1);
         }
     }
     // The instances set should not change in size because it's a self-assignment
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [35/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SelfMoveAssignment)
{
     this->map->clear();
     Matrix<TypeParam> mat1(2, 2, 1);
     size_t initialCount = this->map->getCurrentInstanceCount();
     mat1 = std::move(mat1); // Self-assignment with move
     // The matrix should remain unchanged after self-assignment
     for (size_t i = 0; i < mat1.getRows(); ++i) {
         for (size_t j = 0; j < mat1.getCols(); ++j) {
             EXPECT_EQ(mat1[i][j], 1);
         }
     }
     // The instances set should not change in size because it's a self-assignment
     EXPECT_EQ(this->map->getCurrentInstanceCount(), initialCount);
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [36/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SetSubMatrixTest)
{
     Matrix<TypeParam> m1(3, 3, 1);
     Matrix<TypeParam> m2(2, 2, 2);
     m1.setSubMatrix(1, 1, m2);
     Matrix<TypeParam> m3 = m1.subMatrix(1, 1, 2, 2);
     EXPECT_TRUE(m2 == m3);
 }
References MyBLAS::Matrix< T >::setSubMatrix(), and MyBLAS::Matrix< T >::subMatrix().
TYPED_TEST() [37/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SizeInitialValueConstructorTest)
{
     Matrix<TypeParam> m(3, 3, static_cast<TypeParam>(1));
     EXPECT_EQ(m.getRows(), 3);
     EXPECT_EQ(m.getCols(), 3);
     for (size_t i = 0; i < m.getRows(); ++i) {
         for (size_t j = 0; j < m.getCols(); ++j) {
             EXPECT_EQ(m[i][j], static_cast<TypeParam>(1));
         }
     }
 }
References i, and m.
TYPED_TEST() [38/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SubMatrixTest)
{
     Matrix<TypeParam> m1(3, 3, 1);
     Matrix<TypeParam> m2 = m1.subMatrix(1, 1, 2, 2);
     EXPECT_EQ(m2.getRows(), 2);
     EXPECT_EQ(m2.getCols(), 2);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_EQ(m2[i][j], 1);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and MyBLAS::Matrix< T >::subMatrix().
TYPED_TEST() [39/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SubtractionTest)
{
     Matrix<TypeParam> m1(2, 2, 3);
     Matrix<TypeParam> m2(2, 2, 2);
     Matrix<TypeParam> m3 = m1 - m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             EXPECT_EQ(m3[i][j], 1);
         }
     }
 }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
TYPED_TEST() [40/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , SwapRowsTest)
{
     Matrix<TypeParam> m1(2, 2, 1);
     m1[0][0] = 2;
     m1.swapRows(0, 1);
     EXPECT_EQ(m1[0][0], 1);
     EXPECT_EQ(m1[1][0], 2);
 }
References MyBLAS::Matrix< T >::swapRows().
TYPED_TEST() [41/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , Vector2DConstructorTest)
{
     std::vector<std::vector<TypeParam>> vec2d = {
         {static_cast<TypeParam>(1), static_cast<TypeParam>(2)},
         {static_cast<TypeParam>(3), static_cast<TypeParam>(4)}
     };
     Matrix<TypeParam> m(vec2d);
     EXPECT_EQ(m.getRows(), 2);
     EXPECT_EQ(m.getCols(), 2);
     for (size_t i = 0; i < m.getRows(); ++i) {
         for (size_t j = 0; j < m.getCols(); ++j) {
             EXPECT_EQ(m[i][j], vec2d[i][j]);
         }
     }
 }
References i, and m.
TYPED_TEST() [42/116]
MyBLAS::TYPED_TEST (BaseMatrixTests , ZeroSizeMatrixTest)
{
     Matrix<TypeParam> m1(0, 0);
     Matrix<TypeParam> m2 = m1 / 2;
     EXPECT_EQ(m2.getCols(), 0);
     EXPECT_EQ(m1.getCols(), 0);
     EXPECT_EQ(m2.getRows(), 0);
     EXPECT_EQ(m1.getRows(), 0);
 }
References MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
TYPED_TEST() [43/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , AdditionTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     LazyMatrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     LazyMatrix<TypeParam> m3 = m1 + m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m3(i, j), static_cast<TypeParam>(i) + static_cast<TypeParam>(j) + static_cast<TypeParam>(i) * static_cast<TypeParam>(j)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), and i.
TYPED_TEST() [44/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , AsColumnVectorTest)
{
     LazyMatrix<TypeParam> m(3, 8, [](size_t i, size_t j) { return static_cast<TypeParam>(i * 3 + j); });
     auto colVector = m.asColumnVector();
     for (size_t i = 0; i < m.getRows(); ++i) {
         for (size_t j = 0; j < m.getCols(); ++j) {
             size_t idx = j * m.getRows() + i;
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(colVector[idx], static_cast<TypeParam>(i * 3 + j)));
         }
     }
 }
References i, and m.
TYPED_TEST() [45/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , AsRowVectorTest)
{
     LazyMatrix<TypeParam> m(3, 8, [](size_t i, size_t j) { return static_cast<TypeParam>(i * 3 + j); });
     auto rowVector = m.asRowVector();
     for (size_t i = 0; i < m.getRows(); ++i) {
         for (size_t j = 0; j < m.getCols(); ++j) {
             size_t idx = i * m.getCols() + j;
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(rowVector[idx], static_cast<TypeParam>(i * 3 + j)));
         }
     }
 }
References i, and m.
TYPED_TEST() [46/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , BLASMatrixAdditionTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     MyBLAS::Matrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     auto m12 = m1 + m2;
     auto m21 = m2 + m1;
     EXPECT_EQ(m12.getCols(), m21.getCols());
     EXPECT_EQ(m12.getRows(), m21.getRows());
     for (size_t i = 0; i < m12.getRows(); ++i) {
         for (size_t j = 0; j < m12.getCols(); ++j) {
             const auto actual = (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) + (static_cast<TypeParam>(i) * static_cast<TypeParam>(j));
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m12(i, j), actual));
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m21(i, j), actual));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), and i.
TYPED_TEST() [47/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , BLASMatrixSubtractionTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     MyBLAS::Matrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     auto m12 = m1 - m2;
     auto m21 = m2 - m1;
     for (size_t i = 0; i < m12.getRows(); ++i) {
         for (size_t j = 0; j < m12.getCols(); ++j) {
             const auto actual = (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) - (static_cast<TypeParam>(i) * static_cast<TypeParam>(j));
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m12(i, j), actual));
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m21(i, j), -actual));
             // Note the negative sign here, as m2 - m1 is not the same as m1 - m2
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), and i.
TYPED_TEST() [48/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , ElementAccessTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     for (size_t i = 0; i < m.getRows(); ++i) {
         for (size_t j = 0; j < m.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m(i, j), static_cast<TypeParam>(i) * static_cast<TypeParam>(j)));
         }
     }
 }
References i, and m.
TYPED_TEST() [49/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , EqualityTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     LazyMatrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     EXPECT_TRUE(allElementsEqual(m2, m1));
 }
References i.
TYPED_TEST() [50/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , InequalityTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     LazyMatrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     EXPECT_TRUE(!allElementsEqual(m1, m2));
 }
References i.
TYPED_TEST() [51/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , LazyMatrixLazyVectorMultiplicationTest)
{
     MyBLAS::LazyVector<TypeParam> v(10, [](size_t i) { return static_cast<TypeParam>(i); });
     MyBLAS::LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto result = m * v;
     for (size_t i = 0; i < result.size(); ++i) {
         TypeParam expected = 0;
         for (size_t j = 0; j < 10; ++j) {
             expected += (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) * static_cast<TypeParam>(j);
         }
         EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(result[i], expected));
     }
 }
References i, m, and MyBLAS::LazyVector< DataType >::size().
TYPED_TEST() [52/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , MatrixMultiplicationTest)
{
     LazyMatrix<TypeParam> m1(10, 5, [](size_t i, size_t j) { return static_cast<TypeParam>(i + j); });
     LazyMatrix<TypeParam> m2(5, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i * j); });
     auto m3 = m1 * m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             TypeParam expected = 0;
             for (size_t k = 0; k < m1.getCols(); ++k) {
                 expected += m1(i, k) * m2(k, j);
             }
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m3(i, j), expected));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and k.
TYPED_TEST() [53/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , MatrixVectorMultiplicationTest)
{
     MyBLAS::Vector<TypeParam> v(10, [](size_t i) { return static_cast<TypeParam>(i); });
     MyBLAS::LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto result = m * v;
     for (size_t i = 0; i < result.size(); ++i) {
         TypeParam expected = 0;
         for (size_t j = 0; j < 10; ++j) {
             expected += (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) * static_cast<TypeParam>(j);
         }
         EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(result[i], expected));
     }
 }
References i, m, and MyBLAS::Vector< T >::size().
TYPED_TEST() [54/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , MatrixVectorMultiplicationTest_IdentityMatrix)
{
     MyBLAS::Vector<TypeParam> v(10, [](size_t i) { return static_cast<TypeParam>(i); });
     MyBLAS::LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return i == j ? 1 : 0; });
     auto result = m * v;
     for (size_t i = 0; i < result.size(); ++i) {
         EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(result[i], static_cast<TypeParam>(i)));
     }
 }
References i, m, and MyBLAS::Vector< T >::size().
TYPED_TEST() [55/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , MatrixVectorMultiplicationTest_ScalarMultiplication)
{
     MyBLAS::Vector<TypeParam> v(10, 2);
     MyBLAS::LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i + j); });
     auto result = m * v;
     for (size_t i = 0; i < result.size(); ++i) {
         TypeParam expected = 0;
         for (size_t j = 0; j < 10; ++j) {
             expected += (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) * 2;
         }
         EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(result[i], expected));
     }
 }
References i, and m.
TYPED_TEST() [56/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , MatrixVectorMultiplicationTest_ZeroVector)
{
     MyBLAS::Vector<TypeParam> v(10, 0.0f);
     MyBLAS::LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i + j); });
     auto result = m * v;
     for (size_t i = 0; i < result.size(); ++i) {
         EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(result[i], 0));
     }
 }
References i, and m.
TYPED_TEST() [57/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , ScalarAdditionTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto m2 = m + static_cast<TypeParam>(10);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m2(i, j), static_cast<TypeParam>(i) + static_cast<TypeParam>(j) + static_cast<TypeParam>(10)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and m.
TYPED_TEST() [58/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , ScalarDivisionTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto m2 = m / static_cast<TypeParam>(2);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m2(i, j), (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) / static_cast<TypeParam>(2)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and m.
TYPED_TEST() [59/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , ScalarMultiplicationTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto m2 = m * static_cast<TypeParam>(2);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m2(i, j), (static_cast<TypeParam>(i) + static_cast<TypeParam>(j)) * static_cast<TypeParam>(2)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and m.
TYPED_TEST() [60/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , ScalarSubtractionTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     auto m2 = m - static_cast<TypeParam>(5);
     for (size_t i = 0; i < m2.getRows(); ++i) {
         for (size_t j = 0; j < m2.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m2(i, j), static_cast<TypeParam>(i) + static_cast<TypeParam>(j) - static_cast<TypeParam>(5)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), i, and m.
TYPED_TEST() [61/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , SizeTest)
{
     LazyMatrix<TypeParam> m(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     EXPECT_EQ(m.getRows(), 10);
     EXPECT_EQ(m.getCols(), 10);
 }
References i, and m.
TYPED_TEST() [62/116]
MyBLAS::TYPED_TEST (LazyMatrixTests , SubtractionTest)
{
     LazyMatrix<TypeParam> m1(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) + static_cast<TypeParam>(j); });
     LazyMatrix<TypeParam> m2(10, 10, [](size_t i, size_t j) { return static_cast<TypeParam>(i) * static_cast<TypeParam>(j); });
     auto m3 = m1 - m2;
     for (size_t i = 0; i < m3.getRows(); ++i) {
         for (size_t j = 0; j < m3.getCols(); ++j) {
             EXPECT_TRUE(LazyMatrixTests<TypeParam>::IsClose(m3(i, j), static_cast<TypeParam>(i) + static_cast<TypeParam>(j) - static_cast<TypeParam>(i) * static_cast<TypeParam>(j)));
         }
     }
 }
References MyBLAS::LazyMatrix< DataType >::getCols(), MyBLAS::LazyMatrix< DataType >::getRows(), and i.
TYPED_TEST() [63/116]
MyBLAS::TYPED_TEST (MatrixMemoryAllocationTests , ConstructorTest)
{
     using MatrixType = Matrix<TypeParam>;
     const size_t rows = 36;
     const size_t cols = 42;
 //    const size_t matrixMemory = this->estimateMatrixMemoryUsage(rows, cols);
     // Create a matrix and check memory usage
     {
         this->_resources->clear();
         MatrixType matrix(rows, cols);
  //       size_t memoryUsage = this->_resources->getMaxBytesEver();
 //        EXPECT_GT(memoryUsage, 0u);//      EXPECT_NEAR(static_cast<double>(memoryUsage), static_cast<double>(matrixMemory), static_cast<double>(matrixMemory) * 0.1f); // Allow 10% tolerance
     }
     // After matrix goes out of scope, memory usage should decrease
     {
         this->_resources->clear();
         size_t memoryUsage = this->_resources->getMaxBytesEver();
         EXPECT_EQ(memoryUsage, 0u);
     }
     // Create multiple matrices and check memory usage
     {
         this->_resources->clear();
         MatrixType matrix1(rows, cols);
         MatrixType matrix2(rows, cols);
 //        size_t memoryUsage = this->_resources->getMaxBytesEver();
 //        EXPECT_GT(memoryUsage, 0u);
 //        EXPECT_NEAR(static_cast<double>(memoryUsage), static_cast<double>(2 * matrixMemory), 2 * static_cast<double>(matrixMemory) * 0.1f); // Allow 10% tolerance
     }
     // After matrices go out of scope, memory usage should be zero
     {
         this->_resources->clear();
         size_t memoryUsage = this->_resources->getMaxBytesEver();
         EXPECT_EQ(memoryUsage, 0u);
     }
 }
TYPED_TEST() [64/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , HaveEqualRankTest)
{
     Matrix<TypeParam> matrix(3, 3, 1);
     Vector<TypeParam> vector(3, 1);
     Vector<TypeParam> nonEqualRankVector(4, 1);
     EXPECT_TRUE(haveEqualRank(matrix, vector));
     EXPECT_FALSE(haveEqualRank(matrix, nonEqualRankVector));
 }
References haveEqualRank().
TYPED_TEST() [65/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , InnerProductTest)
{
     Matrix<TypeParam> matrixA({{1, 2}, {3, 4}});
     Matrix<TypeParam> matrixB({{5, 6}, {7, 8}});
     Matrix<TypeParam> expectedInnerProduct({{5, 12}, {21, 32}});
     EXPECT_EQ(innerProduct(matrixA, matrixB), expectedInnerProduct);
 }
References innerProduct().
TYPED_TEST() [66/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsBinaryMatrixTest)
{
     Matrix<TypeParam> binaryMatrix({{1, 0, 1}, {0, 1, 0}, {1, 0, 1}});
     Matrix<TypeParam> nonBinaryMatrix({{1, 2, 1}, {0, 1, 0}, {1, 0, 1}});
     EXPECT_TRUE(isBinaryMatrix(binaryMatrix));
     EXPECT_FALSE(isBinaryMatrix(nonBinaryMatrix));
 }
References isBinaryMatrix().
TYPED_TEST() [67/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsDiagonallyDominantTest)
{
     Matrix<TypeParam> diagonallyDominantMatrix({{3, -1, -1}, {-1, 3, -1}, {-1, -1, 3}});
     Matrix<TypeParam> nonDiagonallyDominantMatrix({{1, 2, 3}, {4, 5, 6}, {7, 8, 9}});
     EXPECT_TRUE(isDiagonallyDominant(diagonallyDominantMatrix));
     EXPECT_FALSE(isDiagonallyDominant(nonDiagonallyDominantMatrix));
 }
References isDiagonallyDominant().
TYPED_TEST() [68/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsEmptyMatrixTest)
{
     Matrix<TypeParam> emptyMatrix;
     Matrix<TypeParam> nonEmptyMatrix(3, 3, 1);
     EXPECT_TRUE(isEmptyMatrix(emptyMatrix));
     EXPECT_FALSE(isEmptyMatrix(nonEmptyMatrix));
 }
References isEmptyMatrix().
TYPED_TEST() [69/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsPermutationMatrixTest)
{
     Matrix<TypeParam> permutationMatrix({{0, 1, 0}, {1, 0, 0}, {0, 0, 1}});
     Matrix<TypeParam> nonPermutationMatrix({{1, 1, 0}, {0, 1, 0}, {0, 0, 1}});
     EXPECT_TRUE(isPermutationMatrix(permutationMatrix));
     EXPECT_FALSE(isPermutationMatrix(nonPermutationMatrix));
 }
References isPermutationMatrix().
TYPED_TEST() [70/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsPositiveDefiniteMatrixTest)
{
     // Positive definite matrix (all eigenvalues are positive)
     Matrix<float> positiveDefiniteMatrix({
         {4, 12, -16},
         {12, 37, -43},
         {-16, -43, 98}
     });
     // Not positive definite (negative eigenvalue)
     Matrix<float> nonPositiveDefiniteMatrix({
         {1, 2, 3},
         {2, 0, 5},
         {3, 5, 6}
     });
     // Not positive definite (not symmetric)
     Matrix<float> nonSymmetricMatrix({
         {1, 2, 3},
         {2, 3, 4},
         {3, 4, 5}
     });
     // Not positive definite (zero on diagonal)
     Matrix<float> zeroDiagonalMatrix({
         {0, 0, 0},
         {0, 0, 0},
         {0, 0, 0}
     });
     // Positive definite matrix (identity matrix)
     Matrix identityMatrix = Matrix<float>::eye(3);
     // Check if the matrices are positive definite
     EXPECT_TRUE(MyBLAS::isPositiveDefiniteMatrix(positiveDefiniteMatrix));
     EXPECT_FALSE(MyBLAS::isPositiveDefiniteMatrix(nonPositiveDefiniteMatrix));
     EXPECT_FALSE(MyBLAS::isPositiveDefiniteMatrix(nonSymmetricMatrix));
     EXPECT_FALSE(MyBLAS::isPositiveDefiniteMatrix(zeroDiagonalMatrix));
     EXPECT_TRUE(MyBLAS::isPositiveDefiniteMatrix(identityMatrix));
 }
References MyBLAS::Matrix< T >::eye(), and isPositiveDefiniteMatrix().
TYPED_TEST() [71/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSquareMatrixTest)
{
     Matrix<TypeParam> squareMatrix(3, 3, 1);
     Matrix<TypeParam> nonSquareMatrix(3, 2, 1);
     EXPECT_TRUE(isSquareMatrix(squareMatrix));
     EXPECT_FALSE(isSquareMatrix(nonSquareMatrix));
 }
References isSquareMatrix().
TYPED_TEST() [72/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixEmptyMatrix)
{
     Matrix<TypeParam> emptyMatrix;
     EXPECT_FALSE(MyBLAS::isSymmetricMatrix(emptyMatrix));
 }
References isSymmetricMatrix().
TYPED_TEST() [73/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixFloatingPoint)
{
     MyBLAS::Matrix<long double> symmetricMatrix({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5, 6.0}});
     MyBLAS::Matrix<double> symmetricMatrix1({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5, 6.0}});
     MyBLAS::Matrix<float> symmetricMatrix2({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5, 6.0}});
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(symmetricMatrix));
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(symmetricMatrix1));
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(symmetricMatrix2));
 }
References isSymmetricMatrix().
TYPED_TEST() [74/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixFloatingPointPrecision)
{
     MyBLAS::Matrix<long double> nonSymmetricMatrix({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5000001, 6.0}});
     MyBLAS::Matrix<double> nonSymmetricMatrix1({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5000001, 6.0}});
     MyBLAS::Matrix<double> nonSymmetricMatrix2({{1.0, 2.5, 3.5}, {2.5, 4.0, 5.5}, {3.5, 5.5000001, 6.0}});
     EXPECT_FALSE(MyBLAS::isSymmetricMatrix(nonSymmetricMatrix));
     EXPECT_FALSE(MyBLAS::isSymmetricMatrix(nonSymmetricMatrix1));
     EXPECT_FALSE(MyBLAS::isSymmetricMatrix(nonSymmetricMatrix2));
 }
References isSymmetricMatrix().
TYPED_TEST() [75/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixNonSquare)
{
     MyBLAS::Matrix<TypeParam> nonSquareMatrix({{1, 2, 3}, {4, 5, 6}});
     EXPECT_FALSE(MyBLAS::isSymmetricMatrix(nonSquareMatrix));
 }
References isSymmetricMatrix().
TYPED_TEST() [76/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixOneByOne)
{
     MyBLAS::Matrix<TypeParam> oneByOneMatrix({{1}});
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(oneByOneMatrix));
 }
References isSymmetricMatrix().
TYPED_TEST() [77/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixSymmetric)
{
     Matrix<TypeParam> symmetricMatrix({{1, 2, 3}, {2, 4, 5}, {3, 5, 6}});
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(symmetricMatrix));
 }
References isSymmetricMatrix().
TYPED_TEST() [78/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixSymmetricNegativeValues)
{
     MyBLAS::Matrix<TypeParam> symmetricMatrix({{-1, -2, -3}, {-2, -4, -5}, {-3, -5, -6}});
     EXPECT_TRUE(MyBLAS::isSymmetricMatrix(symmetricMatrix));
 }
References isSymmetricMatrix().
TYPED_TEST() [79/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsSymmetricMatrixTest)
{
     Matrix<TypeParam> symmetricMatrix({
         {1, 2, 3},
         {2, 4, 5},
         {3, 5, 6}
     });
     Matrix<TypeParam> nonSymmetricMatrix({
         {1, 2, 3},
         {2, 4, 6},
         {3, 5, 9}
     }); // Last element changed to ensure non-symmetry
     EXPECT_TRUE(isSymmetricMatrix(symmetricMatrix));
     EXPECT_FALSE(isSymmetricMatrix(nonSymmetricMatrix)); // This should now pass
 }
References isSymmetricMatrix().
TYPED_TEST() [80/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsUnitLowerTriangularMatrixTest)
{
     Matrix<TypeParam> unitLowerTriangularMatrix({{1, 0, 0}, {2, 1, 0}, {3, 4, 1}});
     Matrix<TypeParam> nonUnitLowerTriangularMatrix({{1, 0, 0}, {2, 2, 0}, {3, 4, 3}});
     EXPECT_TRUE(isUnitLowerTriangularMatrix(unitLowerTriangularMatrix));
     EXPECT_FALSE(isUnitLowerTriangularMatrix(nonUnitLowerTriangularMatrix));
 }
References isUnitLowerTriangularMatrix().
TYPED_TEST() [81/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , IsUpperTriangularMatrixTest)
{
     Matrix<TypeParam> upperTriangularMatrix({{1, 2, 3}, {0, 4, 5}, {0, 0, 6}});
     Matrix<TypeParam> nonUpperTriangularMatrix({{1, 2, 3}, {4, 5, 6}, {7, 8, 9}});
     EXPECT_TRUE(isUpperTriangularMatrix(upperTriangularMatrix));
     EXPECT_FALSE(isUpperTriangularMatrix(nonUpperTriangularMatrix));
 }
References isUpperTriangularMatrix().
TYPED_TEST() [82/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , MatrixWeightedInnerProductTest)
{
     Vector<TypeParam> vectorY({1, 2});
     Vector<TypeParam> vectorZ({3, 4});
     Matrix<TypeParam> matrixA({{5, 6}, {7, 8}});
     TypeParam expectedWeightedInnerProduct = 145; // Corrected expected result
     EXPECT_EQ(matrixWeightedInnerProduct(vectorY, vectorZ, matrixA), expectedWeightedInnerProduct); // This should now pass
 }
References matrixWeightedInnerProduct().
TYPED_TEST() [83/116]
MyBLAS::TYPED_TEST (MatrixUtilityTests , NoZerosInDiagonalTest)
{
     Matrix<TypeParam> matrixWithNoZerosInDiagonal({{1, 2, 3}, {4, 5, 6}, {7, 8, 9}});
     Matrix<TypeParam> matrixWithZerosInDiagonal({{0, 2, 3}, {4, 0, 6}, {7, 8, 0}});
     EXPECT_TRUE(noZerosInDiagonal(matrixWithNoZerosInDiagonal));
     EXPECT_FALSE(noZerosInDiagonal(matrixWithZerosInDiagonal));
 }
References noZerosInDiagonal().
TYPED_TEST() [84/116]
MyBLAS::TYPED_TEST (PerformanceMatrixTests , MatrixAdditionPerformanceTest)
{
     size_t seed = 281;
     const size_t BASE = 2, MIN_POWER = 0, MAX_POWER = 14, STEP = 1;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         auto m1 = Random::generate_matrix<TypeParam>(size, size, -100, 100, ++seed);
         auto m2 = Random::generate_matrix<TypeParam>(size, size, -20, 20, ++seed);
         auto start = std::chrono::high_resolution_clock::now();
         Matrix<TypeParam> m3 = m1 + m2;
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<long double> elapsed = end - start;
         std::cout<<"["<<sizeof(m2[0][0])<<"]b: ";
         std::cout << "Time taken for matrix addition of size " << size << "x" << size << ": " << elapsed.count() << "s\n";
         Matrix<TypeParam> m4(size, size, 0);
         start = std::chrono::high_resolution_clock::now();
         #pragma omp parallel for default(none) shared(m4, m2, m1, size)
         for (size_t i = 0; i < size; ++i) {
             for (size_t j = 0; j < size; ++j) {
                 m4[i][j] = m1[i][j] + m2[i][j];
             }
         }
         end = std::chrono::high_resolution_clock::now();
         elapsed = end - start;
         std::cout << "Time taken for openmp matrix addition of size " << size << "x" << size << ": " << elapsed.count() << "s\n";
         for (size_t i = 0; i < size; ++i) {
             for (size_t j = 0; j < size; ++j) {
                 ASSERT_NEAR(static_cast<double>(m4[i][j]), static_cast<double>(m3[i][j]), static_cast<double>(1e-6));
             }
         }
     }
 }
References i, MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [85/116]
MyBLAS::TYPED_TEST (PerformanceMatrixTests , MatrixMultiplicationPerformanceTest)
{
     size_t seed = 372;
     const size_t BASE = 2, MIN_POWER = 0, MAX_POWER = 10, STEP = 1;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         auto m1 = Random::generate_matrix<TypeParam>(size, size, -100, 100, ++seed);
         auto m2 = Random::generate_matrix<TypeParam>(size, size, -20, 20, ++seed);
         auto start = std::chrono::high_resolution_clock::now();
         Matrix<TypeParam> m3 = m1 * m2;
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<long double> elapsed = end - start;
         std::cout<<"["<<sizeof(m2[0][0])<<"]b: ";
         std::cout << "Time taken for matrix multiplication of size " << size << "x" << size << ": " << elapsed.count() << "s\n";
         Matrix<TypeParam> m4(size, size, 0);
         start = std::chrono::high_resolution_clock::now();
         #pragma omp parallel for default(none) shared(m4, m2, m1, size)
         for (size_t i = 0; i < size; ++i) {
             for (size_t j = 0; j < size; ++j) {
                 for (size_t k = 0; k < size; ++k) {
                     m4[i][j] += m1[i][k] * m2[k][j];
                 }
             }
         }
         end = std::chrono::high_resolution_clock::now();
         elapsed = end - start;
         std::cout << "Time taken for openmp matrix multiplication of size " << size << "x" << size << ": " << elapsed.count() << "s\n";
         for (size_t i = 0; i < size; ++i) {
             for (size_t j = 0; j < size; ++j) {
                 ASSERT_NEAR(static_cast<double>(m4[i][j]), static_cast<double>(m3[i][j]), static_cast<double>(1e-6));
             }
         }
     }
 }
References i, k, MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [86/116]
MyBLAS::TYPED_TEST (PerformanceMatrixTests , VectorAdditionOpenMPCPUTest)
{
         const size_t vector_size = 1000000; // Size of the vectors
         std::vector<float> a(vector_size, 1.0f); // Initialize vector 'a' with 1s
         std::vector<float> b(vector_size, 2.0f); // Initialize vector 'b' with 2s
         std::vector<float> c(vector_size, 0.0f); // Initialize result vector 'c' with 0s
         // Perform the vector addition using OpenMP for parallelization on the CPU
         #pragma omp parallel for
         for (size_t i = 0; i < vector_size; ++i) {
             c[i] = a[i] + b[i];
         }
         // Check the results
         for (size_t i = 0; i < vector_size; ++i) {
             ASSERT_EQ(c[i], a[i] + b[i]) << "Vectors a and b were not added correctly at index " << i;
         }
 }
References i.
TYPED_TEST() [87/116]
MyBLAS::TYPED_TEST (PerformanceVectorTests , VectorAdditionPerformanceTest)
{
     const size_t BASE = 2, MIN_POWER = 10, MAX_POWER = 26, STEP = 2;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         Vector<TypeParam> v1(size, 1);
         Vector<TypeParam> v2(size, 2);
         auto start = std::chrono::high_resolution_clock::now();
         Vector<TypeParam> v3 = v1 + v2;
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<double> elapsed = end - start;
         std::cout << "Time taken for vector addition of size " << size << ": " << elapsed.count() << "s\n";
     }
 }
References MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [88/116]
MyBLAS::TYPED_TEST (PerformanceVectorTests , VectorL2NormPerformanceTest)
{
     const size_t BASE = 2, MIN_POWER = 10, MAX_POWER = 26, STEP = 2;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         Vector<TypeParam> v1(size, -32.102f);
         Vector<TypeParam> v2(size, 33.0201f);
         auto start = std::chrono::high_resolution_clock::now();
         auto result = L2(v1, v2);
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<double> elapsed = end - start;
         std::cout << "Time taken for L2 norm of two vectors of size " << size << ": " << elapsed.count() << "s: "<<(result!=0)<<"\n";
     }
 }
References L2(), MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [89/116]
MyBLAS::TYPED_TEST (PerformanceVectorTests , VectorMultiplicationPerformanceTest)
{
     const size_t BASE = 2, MIN_POWER = 10, MAX_POWER = 26, STEP = 2;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         Vector<TypeParam> v1(size, -3.1290f);
         Vector<TypeParam> v2(size, 3.4920f);
         auto start = std::chrono::high_resolution_clock::now();
         auto result = v1 * v2;
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<double> elapsed = end - start;
         std::cout << "Time taken for vector multiplication of size " << size << ": " << elapsed.count() << "s: "<<(result!=0)<<"\n";
     }
 }
References MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [90/116]
MyBLAS::TYPED_TEST (PerformanceVectorTests , VectorScalarMultiplicationPerformanceTest)
{
     const size_t BASE = 2, MIN_POWER = 10, MAX_POWER = 26, STEP = 2;
     const auto min = static_cast<size_t>(std::pow(BASE, MIN_POWER));
     const auto max = static_cast<size_t>(std::pow(BASE, MAX_POWER));
     for (auto size = min; size <= max; size *= (BASE * STEP)) {
         Vector<TypeParam> v(size, -2);
         auto scalar = static_cast<TypeParam>(-9);
         auto start = std::chrono::high_resolution_clock::now();
         Vector<TypeParam> result = v * scalar;
         auto end = std::chrono::high_resolution_clock::now();
         std::chrono::duration<double> elapsed = end - start;
         std::cout << "Time taken for vector-scalar multiplication of size " << size << ": " << elapsed.count() << "s\n";
     }
 }
References MyBLAS::Stats::max(), MyBLAS::Stats::min(), and MyMath::pow().
TYPED_TEST() [91/116]
MyBLAS::TYPED_TEST (VectorMemoryAllocationTests , ConstructorTest)
{
     using VectorType = Vector<TypeParam>;
     const size_t size = 100;
    // const size_t vectorMemory = this->estimateVectorMemoryUsage(size);
     // Create a vector and check memory usage
     {
         this->_resources->clear();
         VectorType vector(size);
  //       size_t memoryUsage = this->_resources->getMaxBytesEver();
  //       EXPECT_GT(memoryUsage, 0u);
  //       EXPECT_NEAR(static_cast<double>(memoryUsage), static_cast<double>(vectorMemory), static_cast<double>(vectorMemory) * 0.1f); // Allow 10% tolerance
     }
     // After vector goes out of scope, memory usage should decrease
     {
         this->_resources->clear();
         size_t memoryUsage = this->_resources->getMaxBytesEver();
         EXPECT_EQ(memoryUsage, 0u);
     }
     // Create multiple vectors and check memory usage
     {
         this->_resources->clear();
         VectorType vector1(size);
         VectorType vector2(size);
 //        size_t memoryUsage = this->_resources->getMaxBytesEver();
 //        EXPECT_GT(memoryUsage, 0u);
 //        EXPECT_NEAR(static_cast<double>(memoryUsage), static_cast<double>(2 * vectorMemory), 2 * static_cast<double>(vectorMemory) * 0.1f); // Allow 10% tolerance
     }
     // After vector goes out of scope, memory usage should decrease
     {
         this->_resources->clear();
         size_t memoryUsage = this->_resources->getMaxBytesEver();
         EXPECT_EQ(memoryUsage, 0u);
     }
 }
TYPED_TEST() [92/116]
MyBLAS::TYPED_TEST (VectorTests , AdditionTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(3, 2);
     Vector<TypeParam> v3 = v1 + v2;
     for (size_t i = 0; i < v3.size(); ++i) {
         EXPECT_EQ(v3[i], 3);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [93/116]
MyBLAS::TYPED_TEST (VectorTests , ConstructorTest)
{
     Vector<TypeParam> v1(3, 1);
     EXPECT_EQ(v1.size(), 3);
     for (size_t i = 0; i < v1.size(); ++i) {
         EXPECT_EQ(v1[i], 1);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [94/116]
MyBLAS::TYPED_TEST (VectorTests , DotProductTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2(3, 3);
     TypeParam result = v1 * v2;
     EXPECT_EQ(result, 18);
 }
TYPED_TEST() [95/116]
MyBLAS::TYPED_TEST (VectorTests , EmptyVectorTest)
{
     Vector<TypeParam> v1;
     EXPECT_EQ(v1.size(), 0);
 }
References MyBLAS::Vector< T >::size().
TYPED_TEST() [96/116]
MyBLAS::TYPED_TEST (VectorTests , EqualityTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(3, 1);
     EXPECT_TRUE(v1 == v2);
 }
TYPED_TEST() [97/116]
MyBLAS::TYPED_TEST (VectorTests , InequalityTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(3, 2);
     EXPECT_NE(v1, v2);
 }
TYPED_TEST() [98/116]
MyBLAS::TYPED_TEST (VectorTests , InitializerListConstructorTest)
{
     Vector<TypeParam> v1({1, 2, 3});
     EXPECT_EQ(v1.size(), 3);
     EXPECT_EQ(v1[0], 1);
     EXPECT_EQ(v1[1], 2);
     EXPECT_EQ(v1[2], 3);
 }
TYPED_TEST() [99/116]
MyBLAS::TYPED_TEST (VectorTests , InitializerListConstructorWithDifferentValuesTest)
{
     Vector<TypeParam> v1({1, 2, 3, 4, 5});
     EXPECT_EQ(v1.size(), 5);
     for (size_t i = 0; i < v1.size(); ++i) {
         EXPECT_EQ(v1[i], i + 1);
     }
 }
References i.
TYPED_TEST() [100/116]
MyBLAS::TYPED_TEST (VectorTests , InitializerListConstructorWithEmptyListTest)
{
     Vector<TypeParam> v1({});
     EXPECT_EQ(v1.size(), 0);
 }
TYPED_TEST() [101/116]
MyBLAS::TYPED_TEST (VectorTests , InitializerListConstructorWithRowVectorTest)
{
     Vector<TypeParam> v1({1, 2, 3}, true); // true indicates a row vector
     EXPECT_EQ(v1.size(), 3);
     EXPECT_TRUE(v1.isRowVector()); // Assuming isRowVector() is a method that checks if the vector is a row vector
     EXPECT_EQ(v1[0], 1);
     EXPECT_EQ(v1[1], 2);
     EXPECT_EQ(v1[2], 3);
 }
TYPED_TEST() [102/116]
MyBLAS::TYPED_TEST (VectorTests , InitializerListConstructorWithSingleElementTest)
{
     Vector<TypeParam> v1({42});
     EXPECT_EQ(v1.size(), 1);
     EXPECT_EQ(v1[0], 42);
 }
TYPED_TEST() [103/116]
MyBLAS::TYPED_TEST (VectorTests , LambdaConstructorTest)
{
     Vector<TypeParam> v1(5, [](size_t i) { return i * 2; });
     for (size_t i = 0; i < v1.size(); ++i) {
         EXPECT_EQ(v1[i], i * 2);
     }
 }
References i.
TYPED_TEST() [104/116]
MyBLAS::TYPED_TEST (VectorTests , ScalarAdditionTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2 = v1 + 2;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_EQ(v2[i], 4);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [105/116]
MyBLAS::TYPED_TEST (VectorTests , ScalarDivisionTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2 = v1 / 2;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_EQ(v2[i], 1);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [106/116]
MyBLAS::TYPED_TEST (VectorTests , ScalarMultiplicationTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2 = v1 * 2;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_EQ(v2[i], 4);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [107/116]
MyBLAS::TYPED_TEST (VectorTests , ScalarSubtractionTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2 = v1 - 1;
     for (size_t i = 0; i < v2.size(); ++i) {
         EXPECT_EQ(v2[i], 1);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [108/116]
MyBLAS::TYPED_TEST (VectorTests , SubtractionTest)
{
     Vector<TypeParam> v1(3, 2);
     Vector<TypeParam> v2(3, 1);
     Vector<TypeParam> v3 = v1 - v2;
     for (size_t i = 0; i < v3.size(); ++i) {
         EXPECT_EQ(v3[i], 1);
     }
 }
References i, and MyBLAS::Vector< T >::size().
TYPED_TEST() [109/116]
MyBLAS::TYPED_TEST (VectorTests , VectorAdditionSizeMismatchTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(4, 2);
    // EXPECT_THROW(v1 + v2, std::exception);
 }
TYPED_TEST() [110/116]
MyBLAS::TYPED_TEST (VectorTests , VectorDotProductSizeMismatchTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(4, 2);
     Vector<TypeParam> v3(6, 2);
     //EXPECT_THROW(v1 * v2, std::exception);
 }
TYPED_TEST() [111/116]
MyBLAS::TYPED_TEST (VectorTests , VectorScalarDivisionByZeroTest)
{
     Vector<TypeParam> v1(3, 1);
    // EXPECT_THROW(v1 / 0, std::exception);
 }
TYPED_TEST() [112/116]
MyBLAS::TYPED_TEST (VectorTests , VectorSubtractionSizeMismatchTest)
{
     Vector<TypeParam> v1(3, 1);
     Vector<TypeParam> v2(4, 2);
     //EXPECT_DEATH(v1 - v2, ".*");
 }
TYPED_TEST() [113/116]
MyBLAS::TYPED_TEST (VectorUtilityTests , DotProductTest)
{
     Vector<TypeParam> vectorA({1, 2, 3});
     Vector<TypeParam> vectorB({4, 5, 6});
     auto expectedDotProduct = static_cast<double>(32);
     EXPECT_EQ(vectorA * vectorB, expectedDotProduct);
 }
TYPED_TEST() [114/116]
MyBLAS::TYPED_TEST (VectorUtilityTests , IsUnitVectorTest)
{
     Vector<TypeParam> unitVector({0, 1, 0});
     Vector<TypeParam> nonUnitVector({1, 2, 3});
     EXPECT_TRUE(isUnitVector(unitVector));
     EXPECT_FALSE(isUnitVector(nonUnitVector));
 }
References isUnitVector().
TYPED_TEST() [115/116]
MyBLAS::TYPED_TEST (VectorUtilityTests , IsZeroVectorTest)
{
     Vector<TypeParam> zeroVector(3, 0);
     Vector<TypeParam> nonZeroVector({1, 2, 3});
     EXPECT_TRUE(isZeroVector(zeroVector));
     EXPECT_FALSE(isZeroVector(nonZeroVector));
 }
References isZeroVector().
TYPED_TEST() [116/116]
MyBLAS::TYPED_TEST (VectorUtilityTests , VectorNormTest)
{
     Vector<TypeParam> vector({1, 2, 3});
     auto expectedNorm = static_cast<double>(std::sqrt(14));
     EXPECT_NEAR(static_cast<double>(norm(vector)), expectedNorm, TOLERANCE);
 }
References norm(), and TOLERANCE.
TYPED_TEST_SUITE() [1/9]
MyBLAS::TYPED_TEST_SUITE (BaseMatrixTests , NumericTypes)
TYPED_TEST_SUITE() [2/9]
MyBLAS::TYPED_TEST_SUITE (LazyMatrixTests , FloatTypes)
TYPED_TEST_SUITE() [3/9]
MyBLAS::TYPED_TEST_SUITE (MatrixMemoryAllocationTests , NumericTypes)
TYPED_TEST_SUITE() [4/9]
MyBLAS::TYPED_TEST_SUITE (MatrixUtilityTests , NumericTypes)
TYPED_TEST_SUITE() [5/9]
MyBLAS::TYPED_TEST_SUITE (PerformanceMatrixTests , NumericTypes)
TYPED_TEST_SUITE() [6/9]
MyBLAS::TYPED_TEST_SUITE (PerformanceVectorTests , NumericTypes)
TYPED_TEST_SUITE() [7/9]
MyBLAS::TYPED_TEST_SUITE (VectorMemoryAllocationTests , NumericTypes)
TYPED_TEST_SUITE() [8/9]
MyBLAS::TYPED_TEST_SUITE (VectorTests , NumericTypes)
TYPED_TEST_SUITE() [9/9]
MyBLAS::TYPED_TEST_SUITE (VectorUtilityTests , NumericTypes)