NE591-008 C++17 Codebase: InLab4 Class Reference
InLab4 Class Reference
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
#include <inlab4.h>
Public Member Functions
InLab4 (CommandLineArgs args)
Constructor for the inlab4 class.
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
InputMatrices & getInputs ()
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (OutputVector &outputs, InputMatrices &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (OutputVector &output, InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (OutputVector &output, InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Static Protected Member Functions
template<typename T >
static void printMandelbrotSet ()
This function prints the Mandelbrot set.
Protected Attributes
CommandLineArgs cmdArgs
Parser terminal
OutputVector outputs
Detailed Description
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
InLab4()
InLab4::InLab4 (CommandLineArgs args) inline explicit
Constructor for the inlab4 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab4::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< InputMatrices, Parser, OutputVector >.
{
         printMandelbrotSet<long double>();
         return {
             .ProjectName = "InLab 04",
             .ProjectDescription = "Solving a system of linear equations using forward, back substitution",
             .SubmissionDate = "09/15/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
execute()
virtual void Project< InputMatrices , Parser , OutputVector >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< InputMatrices , Parser , OutputVector >::finalize () inline protected virtual inherited
{
     }
getInputs()
InputMatrices & Project< InputMatrices , Parser , OutputVector >::getInputs () inline inherited
{
         return this->inputs;
     }
getProfiler() [1/3]
auto Project< InputMatrices , Parser , OutputVector >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< InputMatrices , Parser , OutputVector >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< InputMatrices , Parser , OutputVector >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< InputMatrices , Parser , OutputVector >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< InputMatrices , Parser , OutputVector >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< InputMatrices , Parser , OutputVector >::postRun (OutputVector & output, InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< InputMatrices , Parser , OutputVector >::preRun (OutputVector & output, InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
printMandelbrotSet()
template<typename T > static void InLab4::printMandelbrotSet () inline static protected
This function prints the Mandelbrot set.
The function was converted from Python to C++ and reformatted for the ANSI character-set with 80 columns.
Note
Credit to eyemvh from https://www.reddit.com/r/asciiart/comments/eyemvh/asciibrot/
{
         std::vector<std::string> colors;
         for (int i = 16; i <= 232; i++) {
             colors.push_back("\033[38;5;" + std::to_string(i) + "m");
         }
         double xs = -2.25, ys = -1.5, dx = 0.044, dy = 0.12;
         for (int y = 0; y < 25; ++y) {
             for (int x = 0; x < 80; ++x) {
                 std::complex<T> z1 = std::complex<T>(xs + x * dx, ys + y * dy);
                 std::complex<T> zn = z1;
                 size_t c = 0;
                 for (; c < 1000; c++) {
                     zn = zn * zn + z1;
                     if (std::norm(zn) > 8)
                         break;
                 }
                 std::cout << colors[c % colors.size()] << "o"; //"";
             }
             std::cout << '\n';
         }
         std::cout << "\033[0m";
     }
References i, MyBLAS::norm(), x, and y.
run()
void InLab4::run (OutputVector & outputs, InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution.
Parameters
outputs The output vector
inputs The input matrices
values The variable map
Reimplemented from Project< InputMatrices, Parser, OutputVector >.
{
         // Given the matrix A = LU and vector b
         // solve Ax = b, which is LUx = b
         // x = inv(LU)b
         const auto b = inputs.constants;
         const auto LU = inputs.LU;
         const MyBLAS::Vector y = InLab04::doForwardSubstitution<long double>(LU, b);
         const MyBLAS::Vector x = InLab04::doBackwardSubstitution<long double>(LU, y);
         nlohmann::json results;
         outputs.solution = x;
         outputs.toJSON(results["outputs"]);
         if (!values.count("quiet")) {
             const auto precision = getTerminal().getCurrentPrecision();
             Parser::printLine();
             std::cout << "Intermediate vector y = inv(L) * b:\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << y;
             Parser::printLine();
             std::cout << "Solution vector (x):\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << x;
             Parser::printLine();
         }
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References CommandLine< InputType >::getCurrentPrecision(), Project< InputMatrices, Parser, OutputVector >::getTerminal(), process::inputs, Project< InputMatrices, Parser, OutputVector >::outputs, CommandLine< InLab6Inputs >::printLine(), Output::solution, Output::toJSON(), writeJSON(), x, and y.
timedRun()
virtual void Project< InputMatrices , Parser , OutputVector >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(outputs, terminal.getInputs(), terminal.getArguments());
         run(outputs, terminal.getInputs(), terminal.getArguments());
         postRun(outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
cmdArgs
CommandLineArgs Project< InputMatrices , Parser , OutputVector >::cmdArgs protected inherited
outputs
OutputVector Project< InputMatrices , Parser , OutputVector >::outputs protected inherited
terminal
Parser Project< InputMatrices , Parser , OutputVector >::terminal protected inherited
The documentation for this class was generated from the following file:
src/labs/inlab4/inlab4.h