NE591-008 C++17 Codebase: OutLab7 Class Reference
OutLab7 Class Reference abstract
This class is a child of the MPI Project class.
#include <outlab7.h>
Public Member Functions
OutLab7 (CommandLineArgs args)
Constructor for the outlab7 class.
void execute () override
Executes the project.
Parser getTerminal () const override
Returns the terminal.
Static Public Member Functions
static std::string getHostName ()
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (OutLab7Outputs &outputs, OutLab7Inputs &inputs, boost::program_options::variables_map &values) override
This function runs the computation.
void initialize () override
Initializes the project.
void finalize () override
void timedRun () override
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
void preRun (OutLab7Outputs &output, OutLab7Inputs &input, boost::program_options::variables_map &values) override
A hook for performing actions before the run.
virtual void preRun (OutputType &output, InputType &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void run (OutputType &output, InputType &input, boost::program_options::variables_map &values)=0
Executes the project.
void postRun (OutLab7Outputs &output, OutLab7Inputs &input, boost::program_options::variables_map &values) override
A hook for performing actions after the run.
virtual void postRun (OutputType &output, InputType &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
template<typename Func >
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
template<typename Func >
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
template<typename Func >
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
int rank
int size
std::string uuid
bool mpi_initialized
CommandLineArgs cmdArgs {}
CommandLineParserType terminal
OutputType outputs
Static Private Member Functions
static void sendInputs (const OutLab7Inputs &inputs, const int rank)
static OutLab7Inputs receiveInputs ()
Detailed Description
This class is a child of the MPI Project class.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
OutLab7()
OutLab7::OutLab7 (CommandLineArgs args) inline explicit
Constructor for the outlab7 class.
Parameters
args Command line arguments
 : MPIProject<OutLab7Inputs, Parser, OutLab7Outputs>(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab7::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< InputType, CommandLineParserType, OutputType >.
{
         Canvas canvas;
         __float128 x = 0.13;
         __float128 y = -0.66;
         auto iterations = 80;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         canvas.tone_map.growth_rate = 0.25;
         return {
             .ProjectName = "NE591: OutLab 07",
             .ProjectDescription = "",
             .SubmissionDate = "10/13/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = drawJuliaSet(canvas, x, y, iterations),
         };
     }
References drawJuliaSet(), CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::execute () inline override virtual inherited
Executes the project.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         initialize();
         finalize();
     }
finalize()
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::finalize () inline override protected virtual inherited
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         std::cout<<uuid<<"finalizing\n";
         MPI_Finalize();
         mpi_initialized = false;
     }
getHostName()
static std::string MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::getHostName () inline static inherited
{
         char hostname[MPI_MAX_PROCESSOR_NAME];
         int resultlen;
         MPI_Get_processor_name(hostname, &resultlen);
         return std::string{hostname, static_cast<size_t>(resultlen)};
     }
getProfiler() [1/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
References Project< InputType, CommandLineParserType, OutputType >::getTerminal(), and ProfilerHelper::InitProfiler().
getTerminal()
Parser MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::getTerminal () const inline override virtual inherited
Returns the terminal.
Returns
The terminal.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         return Project<InputType, CommandLineParserType, OutputType>::getTerminal();
     }
initialize()
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::initialize () inline override protected virtual inherited
Initializes the project.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         InputType inputs;
         // if rank leader, collect all inputs, and then broadcast and sync variables with all ranks.
         if(this->rank == 0) {
             Project<InputType, CommandLineParserType, OutputType>::initialize();
             inputs = getTerminal().getInputs();
             for(int i = 1; i < size; i++) {
                 inputs.n = i;
                 sendInputs(inputs, i);
             }
             inputs.n = 0;
         } else {
             inputs = receiveInputs();
         }
         std::cout<<uuid<<"inputs: "<<inputs<<"\n";
     }
postRun() [1/2]
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::postRun (OutLab7Outputs & output, OutLab7Inputs & input, boost::program_options::variables_map & values) inline override protected inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
{
     }
postRun() [2/2]
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::postRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
Reimplemented in MPIProject< InputType, CommandLineParserType, OutputType >.
 {}
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
preRun() [1/2]
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::preRun (OutLab7Outputs & output, OutLab7Inputs & input, boost::program_options::variables_map & values) inline override protected inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
{
     }
preRun() [2/2]
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::preRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
Reimplemented in MPIProject< InputType, CommandLineParserType, OutputType >.
 {}
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
receiveInputs()
static OutLab7Inputs MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::receiveInputs () inline static private inherited
{
         MPI_Status status;
         int length;
         MPI_Probe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &status);
         MPI_Get_count(&status, MPI_CHAR, &length);
         char* buffer = new char[length];
         MPI_Recv(buffer, length, MPI_CHAR, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
         std::string received_str(buffer);
         delete[] buffer;
         std::istringstream iss(received_str);
         boost::archive::text_iarchive ia(iss);
         InputType received_input;
         ia >> received_input;
         return received_input;
     }
run() [1/2]
void OutLab7::run (OutLab7Outputs & outputs, OutLab7Inputs & inputs, boost::program_options::variables_map & values) inline override protected
This function runs the computation.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
values The values used in the computation.
{
         nlohmann::json results;
         inputs.toJSON(results["inputs"]);
 //        int numprocs, rank_id;
 //        MPI_Status stat;
 //
 //        auto args = getTerminal().getCmdArgs();
 //        MPI_Init(&args.argc, &args.argv);
 //        MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
 //        MPI_Comm_rank(MPI_COMM_WORLD, &rank_id);
 ////
 //        auto n = 1000;
 //        MPI_Bcast(&n, 1, MPI_UNSIGNED_LONG_LONG, 0, MPI_COMM_WORLD);
 //
 //        if ((numprocs & (numprocs - 1)) != 0) {
 //            if (rank_id == 0) {
 //                std::cout << "Number of processes is not a power of 2";
 //            }
 //            MPI_Finalize();
 //            exit(1);
 //        }
 //
 //        size_t i1 = n / numprocs * rank_id;
 //        size_t i2 = rank_id == numprocs - 1 ? n : n / numprocs * (rank_id + 1);
 //
 //        MyBLAS::NumericType partial_sum = 0;
 //        for (size_t i = i1; i < i2; i++) {
 //            partial_sum += (1 + log10(i)) / pow(i + log10(i + 1), 2);
 //        }
 //
 //        int dest = rank_id % 2 == 0 ? rank_id + 1 : rank_id - 1;
 //        MPI_Send(&partial_sum, 1, MPI_DOUBLE, dest, 0, MPI_COMM_WORLD);
 //
 //        if (rank_id == 0) {
 //            double total_sum;
 //            MPI_Recv(&total_sum, 1, MPI_DOUBLE, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &stat);
 //            std::cout << "The value of the series is: " << total_sum << std::endl;
 //        }
         Parser::printLine();
         outputs.toJSON(results["outputs"]);
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References process::inputs, Project< InputType, CommandLineParserType, OutputType >::outputs, CommandLine< InLab6Inputs >::printLine(), and writeJSON().
run() [2/2]
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::run (OutputType & output, InputType & input, boost::program_options::variables_map & values) protected pure virtual inherited
Executes the project.
Parameters
output The output data.
input The input data.
values The variable map.
Implemented in InLab1, Project2, Project1, OutLab5, InLab4, MPIProject< InputType, CommandLineParserType, OutputType >, OutLab6, OutLab1, OutLab4, InLab5, InLab6, OutLab3, InLab3, and InLab2.
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
sendInputs()
static void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::sendInputs (const OutLab7Inputs & inputs, const int rank) inline static private inherited
{
         std::ostringstream oss;
         boost::archive::text_oarchive oa(oss);
         oa << inputs;
         std::string serialized_str = oss.str();
         MPI_Send(serialized_str.c_str(), serialized_str.size() + 1, MPI_CHAR, rank, 0, MPI_COMM_WORLD);
     }
timedRun()
void MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::timedRun () inline override protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
     }
Field Documentation
cmdArgs
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineArgs Project< InputType, CommandLineParserType, OutputType >::cmdArgs {} protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::Project().
mpi_initialized
bool MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::mpi_initialized protected inherited
outputs
template<typename InputType , typename CommandLineParserType , typename OutputType > OutputType Project< InputType, CommandLineParserType, OutputType >::outputs protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), run(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
rank
int MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::rank protected inherited
size
int MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::size protected inherited
terminal
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineParserType Project< InputType, CommandLineParserType, OutputType >::terminal protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::getTerminal(), Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
uuid
std::string MPIProject< OutLab7Inputs , Parser , OutLab7Outputs >::uuid protected inherited
The documentation for this class was generated from the following file:
src/labs/outlab7/outlab7.h