NE591-008 C++17 Codebase: Random Namespace Reference
Random Namespace Reference
This namespace provides functions for generating random vectors and matrices.
Functions
template<typename T >
T generate_one (T min=0, T max=1, const size_t seed=372)
Generates a single random number.
template<typename T >
MyBLAS::Vector< T > generate_vector (const size_t n, T min=0, T max=1, const size_t seed=372)
Generates a vector of random numbers.
template<typename T >
MyBLAS::Matrix< T > generate_matrix (const size_t rows, const size_t cols, T min=0, T max=1, const size_t seed=372)
Generates a matrix of random numbers.
template<typename T >
MyBLAS::Matrix< T > binary (const size_t rows, const size_t cols, const size_t seed=372)
Generates a binary matrix.
Detailed Description
This namespace provides functions for generating random vectors and matrices.
Function Documentation
binary()
template<typename T > MyBLAS::Matrix<T> Random::binary (const size_t rows, const size_t cols, const size_t seed = 372)
Generates a binary matrix.
Template Parameters
T The type of the elements in the matrix.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
seed The seed for the random number generator.
Returns
A binary matrix.
{
     std::random_device rd;
     std::mt19937 stream(seed);
     std::uniform_real_distribution<T> uniform(static_cast<T>(0), static_cast<T>(1));
     MyBLAS::Matrix<T> samples(rows, cols);
     for (size_t row = 0; row < rows; row++) {
         for (size_t col = 0; col < cols; col++) {
             const auto sample = uniform(stream);
             samples[row][col] = (1 - sample) < (sample - 0) ? 1 : 0;
         }
     }
     return samples;
 }
References process::row.
generate_matrix()
template<typename T > MyBLAS::Matrix<T> Random::generate_matrix (const size_t rows, const size_t cols, T min = 0, T max = 1, const size_t seed = 372)
Generates a matrix of random numbers.
Template Parameters
T The type of the elements in the matrix.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
min The minimum value for the random numbers.
max The maximum value for the random numbers.
seed The seed for the random number generator.
Returns
A matrix of random numbers.
{
     if (max < min) {
         auto temp = max;
         max = min;
         min = temp;
     }
     std::random_device rd;
     std::mt19937 stream(seed);
     std::uniform_real_distribution<T> uniform(min, max);
     MyBLAS::Matrix<T> samples(rows, cols);
     for (size_t row = 0; row < rows; row++) {
         for (size_t col = 0; col < cols; col++) {
             samples[row][col] = uniform(stream);
         }
     }
     return samples;
 }
References MyBLAS::Stats::max(), MyBLAS::Stats::min(), and process::row.
Referenced by MyBLAS::System::Circuit().
generate_one()
template<typename T > T Random::generate_one (T min = 0, T max = 1, const size_t seed = 372)
Generates a single random number.
Template Parameters
T The type of the random number.
Parameters
min The minimum value for the random number.
max The maximum value for the random number.
seed The seed for the random number generator.
Returns
A random number.
{
     if (max < min) {
         auto temp = max;
         max = min;
         min = temp;
     }
     std::random_device rd;
     std::mt19937 stream(seed);
     std::uniform_real_distribution<T> uniform(min, max);
     return uniform(stream);
 }
References MyBLAS::Stats::max(), and MyBLAS::Stats::min().
generate_vector()
template<typename T > MyBLAS::Vector<T> Random::generate_vector (const size_t n, T min = 0, T max = 1, const size_t seed = 372)
Generates a vector of random numbers.
Template Parameters
T The type of the elements in the vector.
Parameters
n The size of the vector.
min The minimum value for the random numbers.
max The maximum value for the random numbers.
seed The seed for the random number generator.
Returns
A vector of random numbers.
{
     if (max < min) {
         auto temp = max;
         max = min;
         min = temp;
     }
     std::random_device rd;
     std::mt19937 stream(seed);
     std::uniform_real_distribution<T> uniform(min, max);
     MyBLAS::Vector<T> samples(n);
     for (size_t idx = 0; idx < n; idx++) {
         samples[idx] = uniform(stream);
     }
     return samples;
 }
References MyBLAS::Stats::max(), MyBLAS::Stats::min(), and n.
Referenced by MyBLAS::System::Circuit().