NE591-008 C++17 Codebase: MyRelaxationMethod Namespace Reference
MyRelaxationMethod Namespace Reference
This namespace contains implementations of various relaxation methods for solving systems of linear equations.
Enumerations
enum Type {
METHOD_POINT_JACOBI , METHOD_SORPJ , METHOD_GAUSS_SEIDEL , METHOD_SYMMETRIC_GAUSS_SEIDEL ,
METHOD_SOR , METHOD_SSOR , METHOD_CONJUGATE_GRADIENT
}
Enum for different types of relaxation methods.
Functions
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applyConjugateGradient (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance)
template<typename T >
T dot_product (const std::vector< T > &v1, const std::vector< T > &v2)
template<typename T >
std::vector< T > matrix_vector_multiply (const std::vector< std::vector< T >> &A, const std::vector< T > &v)
template<typename T >
std::vector< T > vector_add (const std::vector< T > &v1, const std::vector< T > &v2, T alpha)
template<typename T >
std::vector< T > vector_subtract (const std::vector< T > &v1, const std::vector< T > &v2)
template<typename T >
std::vector< T > scalar_vector_multiply (const std::vector< T > &v, T alpha)
const char * TypeKey (MyRelaxationMethod::Type value)
Function to get the key of a relaxation method type.
template<typename T >
T approximateOptimalRelaxationFactor (const size_t meshX, const size_t meshY)
Function to approximate the optimal relaxation factor for a given mesh size.
template<typename T >
T approximateOptimalRelaxationFactor (const size_t meshXY)
Function to approximate the optimal relaxation factor for a square mesh.
template<typename MatrixType , typename VectorType >
bool passesPreChecks (const MatrixType &A, const VectorType &b)
Function to perform pre-checks on the coefficient matrix and the right-hand side vector.
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applySORSerial (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1, const size_t threads=1)
This function applies the Successive Over-Relaxation (SOR) method to solve a system of linear equations.
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applySOR (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1, const size_t threads=1)
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applySORBlockParallel (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1, const size_t threads=1)
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applyPSOR (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1)
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applyP2SOR (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1)
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applyPointJacobi (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1, const size_t threads=1)
This function applies the Point Jacobi method to solve a system of linear equations.
template<template< typename > class MatrixType, template< typename > class VectorType, typename T >
MyBLAS::Solver::Solution< T > applySSOR (const MatrixType< T > &A, const VectorType< T > &b, const size_t max_iterations, const T tolerance, const T relaxation_factor=1)
Applies the Symmetric Successive Over-Relaxation (SSOR) method to solve a system of linear equations.
Detailed Description
This namespace contains implementations of various relaxation methods for solving systems of linear equations.
Enumeration Type Documentation
Type
enum MyRelaxationMethod::Type
Enum for different types of relaxation methods.
This enum represents the different types of relaxation methods that can be used in the program. The methods include Point Jacobi, Gauss Seidel, SOR, and SSOR.
Enumerator
METHOD_POINT_JACOBI
METHOD_SORPJ
METHOD_GAUSS_SEIDEL
METHOD_SYMMETRIC_GAUSS_SEIDEL
METHOD_SOR
METHOD_SSOR
METHOD_CONJUGATE_GRADIENT
           {
     METHOD_POINT_JACOBI,
     METHOD_SORPJ,
     METHOD_GAUSS_SEIDEL,
     METHOD_SYMMETRIC_GAUSS_SEIDEL,
     METHOD_SOR,
     METHOD_SSOR,
     METHOD_CONJUGATE_GRADIENT,
 };
Function Documentation
applyConjugateGradient()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applyConjugateGradient (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance)
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     T iterative_error = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     VectorType<T> x(n, -10);                         // Initialize guess
     VectorType<T> b_prime = (A * results.x);
     VectorType<T> r = b - b_prime;                 // Initial residual
     VectorType<T> p = r;                          // Initial search direction
     // these are all loop local
     size_t iterations;
     T r_dot, pAp, alpha, r_dot_1, betaK;
     VectorType<T> Ap, alphaP, betaKp, alphaAp;
     for (iterations = 0; iterations < max_iterations; iterations++) {
         r_dot = r * r;
         Ap = A * p;
         pAp = p * Ap;
         alpha = r_dot / pAp;
         alphaP = alpha * p;
         x = x + alphaP;
         alphaAp = alpha * Ap;
         iterative_error = MyBLAS::L2(r, alphaAp);
         if(iterative_error < tolerance) {
             results.converged = true;
             break;
         }
         r = r - alphaAp;
         r_dot_1 = r * r;
         betaK = r_dot_1 / r_dot;
         betaKp = betaK * p;
         p = r + betaKp;
     }
     results.iterative_error = iterative_error;
     results.iterations = iterations;
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), postprocess::iterations, MyBLAS::Solver::Solution< T >::iterations, postprocess::iterative_error, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, x, and MyBLAS::Solver::Solution< T >::x.
Referenced by TYPED_TEST(), and Compute::usingConjugateGradient().
applyP2SOR()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applyP2SOR (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1)
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; (results.iterations)++) {
         VectorType<T> old_x = results.x; // Save the old solution vector
 // Update the "red" points
 #pragma omp parallel for
         for (size_t row = 0; row < n; row += 2) { // Assuming red points are even-indexed
             T sum = 0;
             for (size_t col = 0; col < n; col++) {
                 if (col != row) {
                     sum += A[row][col] * old_x[col];
                 }
             }
             results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
 // Synchronize after updating red points
 #pragma omp barrier
 // Update the "black" points
 #pragma omp parallel for
         for (size_t row = 1; row < n; row += 2) { // Assuming black points are odd-indexed
             T sum = 0;
             for (size_t col = 0; col < n; col++) {
                 if (col != row) {
                     sum += A[row][col] * results.x[col]; // Use the updated red values
                 }
             }
             results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
applyPointJacobi()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applyPointJacobi (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1, const size_t threads = 1)
This function applies the Point Jacobi method to solve a system of linear equations.
The Jacobi method requires the matrix A to be diagonally dominant, or else it may not converge to the correct solution. A diagonally dominant matrix is one where the absolute value of each diagonal element is greater than the sum of the absolute values of the other elements in the same row.
Template Parameters
T The data type of the matrix and vectors (usually float or double).
Parameters
A The matrix in the system of equations.
b The right-hand side vector in the system of equations.
max_iterations The maximum number of iterations to perform.
tolerance The tolerance for convergence. The method stops if the L2 norm of the difference between two successive solutions is less than this value.
relaxation_factor The purpose of the relaxation factor in the Jacobi method is the same as in the SOR method: it can potentially accelerate the convergence of the method. The relaxation factor is a weight that is applied to the new estimate of the solution at each iteration. If the relaxation factor is less than 1, the new estimate is "dampened", or reduced, which can improve stability but may slow convergence. If the relaxation factor is greater than 1, the new estimate is "amplified", or increased, which can speed up convergence but may also cause the method to diverge if the factor is too large.
Returns
A Solution object containing the solution vector, the number of iterations performed, whether the method converged, and the final error.
Note
This function only works with square matrices. If a non-square matrix is provided, the function will return immediately with an empty solution.
The function uses the L2 norm to check for convergence. If the system does not converge within the specified number of iterations, the function will return the current solution and set the 'converged' flag to false.
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     VectorType<T> new_x(n, 0); // Initialize a new vector for the updated solution
     // Start the Point-Jacobi iteration
     for (results.iterations = 0; results.iterations < max_iterations; (results.iterations)++) {
 //        std::cout<<results.iterations<<" of "<<max_iterations<<" :: "<<iterative_error_squared<<" : "<<tolerance_squared<<std::endl;
         // Update the solution vector with the new values for this iteration step
         results.x = new_x;
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
         #pragma omp parallel for num_threads(threads) default(none) shared(results, new_x, A, b)
         for (size_t row = 0; row < n; row++) {
             // subtract the contribution from the diagonal term, since it should not be counted.
             T sum = -(A[row][row] * results.x[row]);
             // For each column in the matrix, add the product of the matrix element and corresponding element in the
             // solution vector to the sum
             for (size_t col = 0; col < n; col++) {
                 sum += A[row][col] * results.x[col];
             }
             // Update the solution vector with the new value
             new_x[row] = (static_cast<T>(1) - relaxation_factor) * results.x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
         iterative_error_squared = MyBLAS::L2(new_x, results.x, n);
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
Referenced by Compute::usingJacobiSOR(), and Compute::usingPointJacobi().
applyPSOR()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applyPSOR (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1)
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; (results.iterations)++) {
         VectorType<T> old_x = results.x; // Save the old solution vector
 // Update red points
 #pragma omp parallel for schedule(static)
         for (size_t row = 0; row < n; row++) {
             if ((row % 2) == 0) { // Red points: row index is even
                 T sum = -(A[row][row] * results.x[row]);
                 for (size_t col = 0; col < n; col++) {
                     sum += A[row][col] * results.x[col];
                 }
                 results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
             }
         }
 #pragma omp barrier
 // Update black points
 #pragma omp parallel for schedule(static)
         for (size_t row = 0; row < n; row++) {
             if ((row % 2) == 1) { // Black points: row index is odd
                 T sum = -(A[row][row] * results.x[row]);
                 for (size_t col = 0; col < n; col++) {
                     sum += A[row][col] * results.x[col];
                 }
                 results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
             }
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
applySOR()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applySOR (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1, const size_t threads = 1)
{
     const size_t n = A.getRows(); // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; ++(results.iterations)) {
         VectorType<T> old_x = results.x; // Save the old solution vector
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
         // Update red elements
         #pragma omp parallel for num_threads(threads) default(none) shared(results, A, b, old_x)
         for (size_t row = 0; row < n; row++) {
             T sum = T();
             for (size_t col = 0; col < n; col++) {
                 if ((row + col) % 2 == 0) { // Red elements when row+col is even
                     sum += A[row][col] * old_x[col];
                 }
             }
             if ((row + row) % 2 == 0) { // Update only red elements
                 results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] +
                                  (relaxation_factor / A[row][row]) * (b[row] - sum + A[row][row] * old_x[row]);
             }
         }
         // Update black elements
         #pragma omp parallel for num_threads(threads) default(none) shared(results, A, b, old_x)
         for (size_t row = 0; row < n; row++) {
             T sum = T();
             for (size_t col = 0; col < n; col++) {
                 if ((row + col) % 2 == 1) { // Black elements when row+col is odd
                     sum += A[row][col] * results.x[col]; // Use updated red elements
                 }
             }
             if ((row + row) % 2 == 1) { // Update only black elements
                 results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] +
                                  (relaxation_factor / A[row][row]) * (b[row] - sum + A[row][row] * old_x[row]);
             }
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
Referenced by Compute::usingGaussSeidel(), and Compute::usingSOR().
applySORBlockParallel()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applySORBlockParallel (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1, const size_t threads = 1)
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n);        // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max();          // Initialize the squared error as the maximum
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; ++(results.iterations)) {
         //std::cout<<results.iterations<<" of "<<max_iterations<<" :: "<<iterative_error_squared<<" : "<<tolerance_squared<<std::endl;
         VectorType<T> old_x = results.x; // Save the old solution vector
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
         // Parallel block-wise update
         #pragma omp parallel num_threads(threads) default(none) shared(A, b, results, old_x)
         {
             #pragma omp for schedule(static)
             for (size_t row = 0; row < n; row++) {
                 // subtract the contribution from the diagonal term, since it should not be counted.
                 T sum = -(A[row][row] * results.x[row]);
                 // For each column in the matrix, add the product of the matrix element and corresponding element in the
                 // solution vector to the sum
                 for (size_t col = 0; col < n; col++) {
                     sum += A[row][col] * results.x[col];
                 }
                 // Update the solution vector with the new value, including the relaxation factor
                 results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
             }
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
Referenced by Compute::usingGaussSeidel().
applySORSerial()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applySORSerial (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1, const size_t threads = 1)
This function applies the Successive Over-Relaxation (SOR) method to solve a system of linear equations.
Template Parameters
T The data type of the elements in the matrix and vectors (e.g., double, float).
Parameters
A The matrix of coefficients in the system of equations.
b The vector of constants in the system of equations.
max_iterations The maximum number of iterations to perform.
tolerance The tolerance for convergence. The method stops when the error is less than this value.
relaxation_factor The relaxation factor to use in the SOR method. This value is typically between 0 and 2.
Returns
A Solution object containing the solution vector, the number of iterations performed, whether the method converged, and the final error.
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; (results.iterations)++) {
         VectorType<T> old_x = results.x; // Save the old solution vector
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
         // For each row in the matrix
         for (size_t row = 0; row < n; row++) {
             // subtract the contribution from the diagonal term, since it should not be counted.
             T sum = -(A[row][row] * results.x[row]);
             // For each column in the matrix, add the product of the matrix element and corresponding element in the
             // solution vector to the sum
             for (size_t col = 0; col < n; col++) {
                 sum += A[row][col] * results.x[col];
             }
             // Update the solution vector with the new value, including the relaxation factor
             results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
applySSOR()
template<template< typename > class MatrixType, template< typename > class VectorType, typename T > MyBLAS::Solver::Solution<T> MyRelaxationMethod::applySSOR (const MatrixType< T > & A, const VectorType< T > & b, const size_t max_iterations, const T tolerance, const T relaxation_factor = 1)
Applies the Symmetric Successive Over-Relaxation (SSOR) method to solve a system of linear equations.
Template Parameters
T The data type of the elements in the matrix and vectors (e.g., double, float).
Parameters
A The matrix of coefficients in the system of linear equations.
b The vector of constants in the system of linear equations.
max_iterations The maximum number of iterations to perform.
tolerance The tolerance for convergence. If the L2 norm of the difference between the new and old solution vectors is less than this value, the method is considered to have converged.
relaxation_factor The relaxation factor to use in the method. This is a value between 0 and 2 that determines the rate of convergence. A value of 1 corresponds to the Gauss-Seidel method, while a value of 2 corresponds to the Jacobi method.
Returns
A Solution object containing the solution vector, the number of iterations performed, whether the method converged, and the final error.
{
     const size_t n = A.getRows();                  // Get the number of rows in the matrix A
     MyBLAS::Solver::Solution<T> results(n); // Initialize the results object with the size of the matrix
     const T tolerance_squared = std::pow(tolerance, static_cast<T>(2)); // Calculate the square of the tolerance
     T iterative_error_squared = std::numeric_limits<T>::max(); // Initialize the squared error as the maximum possible value
     // Start the iteration
     for (results.iterations = 0; results.iterations < max_iterations; ++(results.iterations)) {
         VectorType<T> old_x = results.x; // Save the old solution vector
         // Forward sweep (like weighted Gauss-Seidel)
         for (size_t row = 0; row < n; row++) {
             // subtract the contribution from the diagonal term, since it should not be counted.
             T sum = -(A[row][row] * results.x[row]);
             // For each column in the matrix, add the product of the matrix element and corresponding element in the
             // solution vector to the sum
             for (size_t col = 0; col < n; col++) {
                 sum += A[row][col] * results.x[col];
             }
             results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
         // Backward sweep (like weighted Gauss-Seidel, but in reverse order)
         for (size_t rowPlusOne = n; rowPlusOne > 0; rowPlusOne--) {
             const size_t row = rowPlusOne - 1;
             // subtract the contribution from the diagonal term, since it should not be counted.
             T sum = -(A[row][row] * results.x[row]);
             // For each column in the matrix, add the product of the matrix element and corresponding element in the
             // solution vector to the sum
             for (size_t col = 0; col < n; col++) {
                 sum += A[row][col] * results.x[col];
             }
             results.x[row] = (static_cast<T>(1) - relaxation_factor) * old_x[row] + (relaxation_factor / A[row][row]) * (b[row] - sum);
         }
         // Calculate the L2 norm of the difference between the new and old solution vectors
         iterative_error_squared = MyBLAS::L2(results.x, old_x, n);
         // If the squared error is less than the squared tolerance, set the convergence flag to true and break the loop
         if (iterative_error_squared < tolerance_squared) {
             results.converged = true;
             break;
         }
     }
     // Calculate the final error as the square root of the squared error
     results.iterative_error = std::sqrt(iterative_error_squared);
     return results;
 }
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Matrix< T >::getRows(), MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, MyBLAS::L2(), MyBLAS::Stats::max(), n, MyMath::pow(), process::row, MyBLAS::Stats::sum(), and MyBLAS::Solver::Solution< T >::x.
Referenced by Compute::usingSymmetricGaussSeidel(), and Compute::usingSymmetricSOR().
approximateOptimalRelaxationFactor() [1/2]
template<typename T > T MyRelaxationMethod::approximateOptimalRelaxationFactor (const size_t meshX, const size_t meshY) inline
Function to approximate the optimal relaxation factor for a given mesh size.
This function calculates the optimal relaxation factor for a given mesh size in the x and y directions. The relaxation factor is used in the Successive Over-Relaxation (SOR) method to speed up the convergence of the solution.
Template Parameters
T The data type of the mesh size and the relaxation factor.
Parameters
meshX The size of the mesh in the x direction.
meshY The size of the mesh in the y direction.
Returns
The approximate optimal relaxation factor.
{
     const T dx = 1 / (static_cast<T>(meshX) - 1);
     const T dy = 1 / (static_cast<T>(meshY) - 1);
     const T rho = std::cos(M_PIl * dx) + std::cos(M_PIl * dy);
     const T factor = 2 / (1 + std::sqrt(1 - std::pow(rho, 2)));
     return factor;
 }
References MyMath::pow().
approximateOptimalRelaxationFactor() [2/2]
template<typename T > T MyRelaxationMethod::approximateOptimalRelaxationFactor (const size_t meshXY) inline
Function to approximate the optimal relaxation factor for a square mesh.
This function calculates the optimal relaxation factor for a square mesh of a given size. The relaxation factor is used in the Successive Over-Relaxation (SOR) method to speed up the convergence of the solution.
Template Parameters
T The data type of the mesh size and the relaxation factor.
Parameters
meshXY The size of the square mesh.
Returns
The approximate optimal relaxation factor.
{
     return approximateOptimalRelaxationFactor<T>(meshXY, meshXY);
 }
dot_product()
template<typename T > T MyRelaxationMethod::dot_product (const std::vector< T > & v1, const std::vector< T > & v2)
{
     return std::inner_product(v1.begin(), v1.end(), v2.begin(), T(0));
 }
matrix_vector_multiply()
template<typename T > std::vector<T> MyRelaxationMethod::matrix_vector_multiply (const std::vector< std::vector< T >> & A, const std::vector< T > & v)
{
     std::size_t n = A.size();
     std::vector<T> result(n, T(0));
     for (std::size_t i = 0; i < n; ++i) {
         for (std::size_t j = 0; j < n; ++j) {
             result[i] += A[i][j] * v[j];
         }
     }
     return result;
 }
References i, and n.
passesPreChecks()
template<typename MatrixType , typename VectorType > bool MyRelaxationMethod::passesPreChecks (const MatrixType & A, const VectorType & b)
Function to perform pre-checks on the coefficient matrix and the right-hand side vector.
This function performs several pre-checks on the coefficient matrix and the right-hand side vector before solving the system of linear equations. The checks include verifying that the coefficient matrix is square, that its diagonal does not contain zeros, and that it is diagonally dominant.
Template Parameters
T The data type of the elements in the coefficient matrix and the right-hand side vector.
Parameters
A The coefficient matrix.
b The right-hand side vector.
Returns
True if all pre-checks pass, false otherwise.
{
     if (MyBLAS::isEmptyMatrix(A)) {
         std::cerr << "Error: Failed pre-check: coefficient matrix is empty.\n";
         return false;
     }
     if (!MyBLAS::isSquareMatrix(A)) {
         std::cerr << "Error: Failed pre-check: coefficient matrix is non-square.\n";
         return false;
     }
     if (!MyBLAS::noZerosInDiagonal(A)) {
         std::cerr << "Error: Failed pre-check: coefficient matrix diagonal contains 0.\n";
         return false;
     }
     if (!MyBLAS::isDiagonallyDominant(A)) {
         std::cout << "Warning: coefficient matrix is not diagonally dominant, may not converge\n";
     }
     return true;
 }
References MyBLAS::isDiagonallyDominant(), MyBLAS::isEmptyMatrix(), MyBLAS::isSquareMatrix(), and MyBLAS::noZerosInDiagonal().
Referenced by Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingPointJacobi(), Compute::usingSOR(), Compute::usingSymmetricGaussSeidel(), and Compute::usingSymmetricSOR().
scalar_vector_multiply()
template<typename T > std::vector<T> MyRelaxationMethod::scalar_vector_multiply (const std::vector< T > & v, T alpha)
{
     std::size_t n = v.size();
     std::vector<T> result(n);
     for (std::size_t i = 0; i < n; ++i) {
         result[i] = v[i] * alpha;
     }
     return result;
 }
References i, and n.
TypeKey()
const char* MyRelaxationMethod::TypeKey (MyRelaxationMethod::Type value)
Function to get the key of a relaxation method type.
This function takes a value of the Type enum and returns the corresponding key as a string.
Parameters
value The value of the Type enum.
Returns
The key of the relaxation method type as a string.
{
     static const char *relaxationMethodTypeKeys[] = {"point-jacobi", "SORPJ", "gauss-seidel", "symmetric-gauss-seidel", "SOR", "SSOR", "CG"};
     return relaxationMethodTypeKeys[static_cast<int>(value)];
 }
Referenced by InLab6::run(), OutLab6::run(), Project2::run(), Project3::run(), Project4::run(), Project5::run(), and MyBLAS::Solver::Solution< T >::Solution().
vector_add()
template<typename T > std::vector<T> MyRelaxationMethod::vector_add (const std::vector< T > & v1, const std::vector< T > & v2, T alpha)
{
     std::size_t n = v1.size();
     std::vector<T> result(n);
     for (std::size_t i = 0; i < n; ++i) {
         result[i] = v1[i] + alpha * v2[i];
     }
     return result;
 }
References i, and n.
vector_subtract()
template<typename T > std::vector<T> MyRelaxationMethod::vector_subtract (const std::vector< T > & v1, const std::vector< T > & v2)
{
     std::size_t n = v1.size();
     std::vector<T> result(n);
     for (std::size_t i = 0; i < n; ++i) {
         result[i] = v1[i] - v2[i];
     }
     return result;
 }
References i, and n.