NE591-008 C++17 Codebase: src/labs/outlab3/analysis/readfile.m File Reference
readfile.m File Reference
Functions
integral (:, 1)
integral (:, 2)
integral (:, 3)
runtime (:, 1)
runtime (:, 2)
runtime (:, 3)
set (gca, 'Fontsize', [18])
set (gca, 'FontName', 'cmr12')
set (gca, "TickLabelInterpreter", "latex")
set (gca, 'Xscale', 'log')
set (gca, 'Yscale', 'log')
grid on grid minor box on Plot f (x) as a smooth line plot(points
set (gca, 'ColorOrderIndex', 1) scatter(points
legend ('Trapezoidal Rule', "Simpson's Rule", 'Gauss-Legendre Quadrature', 'Interpreter', 'latex', 'Location', 'northeast')
xticks ((points))
title ("Absolute error vs sampling intervals", 'Interpreter', 'latex')
xlabel (' $m$, $m=2^{n}$ for Gauss-Legendre Quadrature', 'Interpreter', 'latex')
ylabel ('Absolute Error', 'Interpreter', 'latex')
xlim ([1, 2048]) pos
pos (3)
pos (4)
set (gcf, 'Position', pos)
Variables
clear all
format longEng Specify the file name filename = 'discontinous.csv'
myfunction = @(x) x - x + 3.60734
Read the table from the CSV file data = readtable(filename)
Extract the required columns m = data.m
points = data.m
runtime = runtime./ 1e3
error = abs(myfunction(1) - integral)
F = figure
hold on
LineWidth
Function Documentation
f()
grid on grid minor box on Plot f (x)
integral() [1/3]
integral (: , 1)
Referenced by fillUsingGaussianQuadratures(), fillUsingSimpsons(), and fillUsingTrapezoidal().
integral() [2/3]
integral (: , 2)
integral() [3/3]
integral (: , 3)
legend()
legend ('Trapezoidal Rule' , "Simpson's Rule" , 'Gauss-Legendre Quadrature' , 'Interpreter' , 'latex' , 'Location' , 'northeast')
pos() [1/2]
pos (3)
pos() [2/2]
pos (4)
runtime() [1/3]
runtime (: , 1)
runtime() [2/3]
runtime (: , 2)
runtime() [3/3]
runtime (: , 3)
set() [1/7]
set (gca , "TickLabelInterpreter" , "latex")
set() [2/7]
set (gca , 'ColorOrderIndex' , 1)
set() [3/7]
set (gca , 'FontName' , 'cmr12')
set() [4/7]
set (gca , 'Fontsize')
set() [5/7]
set (gca , 'Xscale' , 'log')
set() [6/7]
set (gca , 'Yscale' , 'log')
set() [7/7]
set (gcf , 'Position' , pos)
References n.
title()
title ("Absolute error vs sampling intervals" , 'Interpreter' , 'latex')
xlabel()
xlabel (' $m$, $m = 2^{n}$ for Gauss-Legendre Quadrature', 'Interpreter' , 'latex')
xlim()
xlim ()
xticks()
xticks ((points))
ylabel()
ylabel ('Absolute Error' , 'Interpreter' , 'latex')
Variable Documentation
all
close all
data
Read the table from the CSV file data = readtable(filename)
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::blockingSend(), MyBLAS::Stats::max(), MyBLAS::Stats::min(), MyBLAS::Stats::percentile(), readCSV(), readCSVRowWiseNoHeaders(), MyBLAS::Stats::sum(), MyBLAS::Stats::variance(), writeCSV(), writeCSVMatrixNoHeaders(), and writeJSON().
error
grid on grid minor box on Plot error = abs(myfunction(1) - integral)
Referenced by failsNaturalNumberCheck(), and failsWholeNumberCheck().
F
F = figure
filename
format longEng Specify the file name filename = 'discontinous.csv'
Referenced by Parser::performInputArgumentsCheck().
LineWidth
LineWidth
m
Extract the required columns m = data.m
myfunction
myfunction = @(x) x - x + 3.60734
on
hold on
points
points = data.m
Referenced by MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing(), and printMatrix().
runtime
runtime = runtime./ 1e3