NE591-008 C++17 Codebase: MPIProject< InputType, CommandLineParserType, OutputType > Class Template Reference
MPIProject< InputType, CommandLineParserType, OutputType > Class Template Reference abstract
TODO:: DOCUMENT.
#include <MPIProject.h>
Public Member Functions
MPIProject (CommandLineArgs args)
void execute () override
Executes the project.
CommandLineParserType getTerminal () const override
Returns the terminal.
~MPIProject () override
Static Public Member Functions
static std::string getHostName ()
Protected Member Functions
void initialize () override
Initializes the project.
void finalize () override
void timedRun () override
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
void preRun (OutputType &output, InputType &input, boost::program_options::variables_map &values) override
A hook for performing actions before the run.
void run (OutputType &output, InputType &input, boost::program_options::variables_map &values) override
Executes the project.
void postRun (OutputType &output, InputType &input, boost::program_options::variables_map &values) override
A hook for performing actions after the run.
virtual HeaderInfo buildHeaderInfo ()=0
Builds the header information.
template<typename Func >
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
template<typename Func >
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
template<typename Func >
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
int rank = -1
int size = 1
std::string uuid
bool mpi_initialized = false
CommandLineArgs cmdArgs {}
CommandLineParserType terminal
OutputType outputs
Static Private Member Functions
static void sendInputs (const InputType &inputs, const int rank)
static InputType receiveInputs ()
Detailed Description
template<typename InputType, typename CommandLineParserType, typename OutputType>
class MPIProject< InputType, CommandLineParserType, OutputType >
TODO:: DOCUMENT.
Template Parameters
InputType The type of the input data.
CommandLineParserType The type of the command line parser.
OutputType The type of the output data.
Constructor & Destructor Documentation
MPIProject()
template<typename InputType , typename CommandLineParserType , typename OutputType > MPIProject< InputType, CommandLineParserType, OutputType >::MPIProject (CommandLineArgs args) inline explicit
                                               : Project<InputType, CommandLineParserType, OutputType>(args) {
         std::cout<<"running constructor now: "<<this->rank<<"\n";
         MPI_Init(&args.argc, &args.argv);
         MPI_Comm_size(MPI_COMM_WORLD, &this->size);
         MPI_Comm_rank(MPI_COMM_WORLD, &this->rank);
         uuid = "["+getHostName()+"]["+std::to_string(this->rank)+"]: ";
     }
References CommandLineArgs::argc, CommandLineArgs::argv, MPIProject< InputType, CommandLineParserType, OutputType >::getHostName(), MPIProject< InputType, CommandLineParserType, OutputType >::rank, MPIProject< InputType, CommandLineParserType, OutputType >::size, and MPIProject< InputType, CommandLineParserType, OutputType >::uuid.
~MPIProject()
template<typename InputType , typename CommandLineParserType , typename OutputType > MPIProject< InputType, CommandLineParserType, OutputType >::~MPIProject () inline override
{
         std::cout<<uuid<<"running destructor\n";
     }
References MPIProject< InputType, CommandLineParserType, OutputType >::uuid.
Member Function Documentation
buildHeaderInfo()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual HeaderInfo Project< InputType, CommandLineParserType, OutputType >::buildHeaderInfo () protected pure virtual inherited
Builds the header information.
Returns
The header information.
Implemented in Project2, Project1, OutLab7, OutLab6, OutLab5, OutLab4, OutLab3, OutLab1, InLab6, InLab5, InLab4, InLab3, InLab2, and InLab1.
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize().
execute()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::execute () inline override virtual
Executes the project.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         initialize();
         finalize();
     }
References MPIProject< InputType, CommandLineParserType, OutputType >::finalize(), and MPIProject< InputType, CommandLineParserType, OutputType >::initialize().
finalize()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::finalize () inline override protected virtual
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         std::cout<<uuid<<"finalizing\n";
         MPI_Finalize();
         mpi_initialized = false;
     }
References MPIProject< InputType, CommandLineParserType, OutputType >::mpi_initialized, and MPIProject< InputType, CommandLineParserType, OutputType >::uuid.
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::execute().
getHostName()
template<typename InputType , typename CommandLineParserType , typename OutputType > static std::string MPIProject< InputType, CommandLineParserType, OutputType >::getHostName () inline static
{
         char hostname[MPI_MAX_PROCESSOR_NAME];
         int resultlen;
         MPI_Get_processor_name(hostname, &resultlen);
         return std::string{hostname, static_cast<size_t>(resultlen)};
     }
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::MPIProject().
getProfiler() [1/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
References Project< InputType, CommandLineParserType, OutputType >::getTerminal(), and ProfilerHelper::InitProfiler().
getTerminal()
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineParserType MPIProject< InputType, CommandLineParserType, OutputType >::getTerminal () const inline override virtual
Returns the terminal.
Returns
The terminal.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         return Project<InputType, CommandLineParserType, OutputType>::getTerminal();
     }
References Project< InputType, CommandLineParserType, OutputType >::getTerminal().
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::initialize().
initialize()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::initialize () inline override protected virtual
Initializes the project.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
         InputType inputs;
         // if rank leader, collect all inputs, and then broadcast and sync variables with all ranks.
         if(this->rank == 0) {
             Project<InputType, CommandLineParserType, OutputType>::initialize();
             inputs = getTerminal().getInputs();
             for(int i = 1; i < size; i++) {
                 inputs.n = i;
                 sendInputs(inputs, i);
             }
             inputs.n = 0;
         } else {
             inputs = receiveInputs();
         }
         std::cout<<uuid<<"inputs: "<<inputs<<"\n";
     }
References MPIProject< InputType, CommandLineParserType, OutputType >::getTerminal(), i, Project< InputType, CommandLineParserType, OutputType >::initialize(), process::inputs, MPIProject< InputType, CommandLineParserType, OutputType >::receiveInputs(), MPIProject< InputType, CommandLineParserType, OutputType >::sendInputs(), MPIProject< InputType, CommandLineParserType, OutputType >::size, and MPIProject< InputType, CommandLineParserType, OutputType >::uuid.
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::execute().
postRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::postRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline override protected virtual
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
     }
preRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::preRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline override protected virtual
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
     }
receiveInputs()
template<typename InputType , typename CommandLineParserType , typename OutputType > static InputType MPIProject< InputType, CommandLineParserType, OutputType >::receiveInputs () inline static private
{
         MPI_Status status;
         int length;
         MPI_Probe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &status);
         MPI_Get_count(&status, MPI_CHAR, &length);
         char* buffer = new char[length];
         MPI_Recv(buffer, length, MPI_CHAR, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
         std::string received_str(buffer);
         delete[] buffer;
         std::istringstream iss(received_str);
         boost::archive::text_iarchive ia(iss);
         InputType received_input;
         ia >> received_input;
         return received_input;
     }
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::initialize().
run()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::run (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline override protected virtual
Executes the project.
Parameters
output The output data.
input The input data.
values The variable map.
Implements Project< InputType, CommandLineParserType, OutputType >.
{
     }
sendInputs()
template<typename InputType , typename CommandLineParserType , typename OutputType > static void MPIProject< InputType, CommandLineParserType, OutputType >::sendInputs (const InputType & inputs, const int rank) inline static private
{
         std::ostringstream oss;
         boost::archive::text_oarchive oa(oss);
         oa << inputs;
         std::string serialized_str = oss.str();
         MPI_Send(serialized_str.c_str(), serialized_str.size() + 1, MPI_CHAR, rank, 0, MPI_COMM_WORLD);
     }
References process::inputs, and MPIProject< InputType, CommandLineParserType, OutputType >::rank.
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::initialize().
timedRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > void MPIProject< InputType, CommandLineParserType, OutputType >::timedRun () inline override protected virtual
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
Reimplemented from Project< InputType, CommandLineParserType, OutputType >.
{
     }
Field Documentation
cmdArgs
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineArgs Project< InputType, CommandLineParserType, OutputType >::cmdArgs {} protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::Project().
mpi_initialized
template<typename InputType , typename CommandLineParserType , typename OutputType > bool MPIProject< InputType, CommandLineParserType, OutputType >::mpi_initialized = false protected
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::finalize().
outputs
template<typename InputType , typename CommandLineParserType , typename OutputType > OutputType Project< InputType, CommandLineParserType, OutputType >::outputs protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), OutLab7::run(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
rank
template<typename InputType , typename CommandLineParserType , typename OutputType > int MPIProject< InputType, CommandLineParserType, OutputType >::rank = -1 protected
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::MPIProject(), and MPIProject< InputType, CommandLineParserType, OutputType >::sendInputs().
size
template<typename InputType , typename CommandLineParserType , typename OutputType > int MPIProject< InputType, CommandLineParserType, OutputType >::size = 1 protected
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::initialize(), and MPIProject< InputType, CommandLineParserType, OutputType >::MPIProject().
terminal
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineParserType Project< InputType, CommandLineParserType, OutputType >::terminal protected inherited
Referenced by Project< InputType, CommandLineParserType, OutputType >::getTerminal(), Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
uuid
template<typename InputType , typename CommandLineParserType , typename OutputType > std::string MPIProject< InputType, CommandLineParserType, OutputType >::uuid protected
Referenced by MPIProject< InputType, CommandLineParserType, OutputType >::finalize(), MPIProject< InputType, CommandLineParserType, OutputType >::initialize(), MPIProject< InputType, CommandLineParserType, OutputType >::MPIProject(), and MPIProject< InputType, CommandLineParserType, OutputType >::~MPIProject().
The documentation for this class was generated from the following file:
src/utils/MPIProject.h