NE591-008 C++17 Codebase: Stopwatch< D > Class Template Reference
Stopwatch< D > Class Template Reference
Stopwatch class template for measuring time durations.
#include <Stopwatch.h>
Public Types
using ResolutionType = std::chrono::high_resolution_clock
using TimePointType = std::chrono::time_point< ResolutionType >
Public Member Functions
Stopwatch ()
Constructor that also restarts the stopwatch.
D duration () const
Get the duration in the given type.
D peek_elapsed_time () const
Get the elapsed time from the initial time point to the current time, without affecting the clicked time point.
long double elapsed_seconds () const
Get the duration in seconds, in double precision.
Stopwatch & restart ()
Restart the stopwatch by setting the initial and clicked time points to the current time.
Stopwatch & click ()
Save the current time as the clicked time point.
Static Public Member Functions
static D duration (const TimePointType &stop, const TimePointType &start)
Static method to calculate the duration between two time points.
Private Attributes
TimePointType _initial
The initial time point when the stopwatch was last restarted.
TimePointType _clicked
The last clicked time point, used to measure durations.
Detailed Description
template<class D>
class Stopwatch< D >
Stopwatch class template for measuring time durations.
Template Parameters
D The duration type (e.g., Seconds, Milliseconds, Microseconds).
Member Typedef Documentation
ResolutionType
template<class D > using Stopwatch< D >::ResolutionType = std::chrono::high_resolution_clock
TimePointType
template<class D > using Stopwatch< D >::TimePointType = std::chrono::time_point<ResolutionType>
Constructor & Destructor Documentation
Stopwatch()
template<class D > Stopwatch< D >::Stopwatch () inline
Constructor that also restarts the stopwatch.
 { restart(); }
References Stopwatch< D >::restart().
Member Function Documentation
click()
template<class D > Stopwatch& Stopwatch< D >::click () inline
Save the current time as the clicked time point.
Returns
A reference to the stopwatch object, allowing for method chaining.
{
         _clicked = ResolutionType::now();
         return *this;
     }
References Stopwatch< D >::_clicked.
Referenced by fillLagrangePolys(), fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), InLab1::run(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
duration() [1/2]
template<class D > D Stopwatch< D >::duration () const inline
Get the duration in the given type.
Returns
The duration from the initial time point to the last clicked time point, cast to the template duration type.
 { return Stopwatch::duration(_clicked, _initial); }
References Stopwatch< D >::_clicked, and Stopwatch< D >::_initial.
Referenced by Stopwatch< D >::elapsed_seconds(), and Stopwatch< D >::peek_elapsed_time().
duration() [2/2]
template<class D > static D Stopwatch< D >::duration (const TimePointType & stop, const TimePointType & start) inline static
Static method to calculate the duration between two time points.
Parameters
stop The end time point.
start The start time point.
Returns
The duration between the start and stop time points, cast to the template duration type.
 { return std::chrono::duration_cast<D>(stop - start); }
Referenced by fillLagrangePolys(), fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), InLab1::run(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
elapsed_seconds()
template<class D > long double Stopwatch< D >::elapsed_seconds () const inline
Get the duration in seconds, in double precision.
Returns
The duration from the initial time point to the last clicked time point, cast to double precision seconds.
{
         return std::chrono::duration_cast<std::chrono::duration<long double>>(duration()).count();
     }
References Stopwatch< D >::duration().
peek_elapsed_time()
template<class D > D Stopwatch< D >::peek_elapsed_time () const inline
Get the elapsed time from the initial time point to the current time, without affecting the clicked time point.
Returns
The elapsed time from the initial time point to the current time, cast to the template duration type.
 { return Stopwatch::duration(ResolutionType::now(), _initial); }
References Stopwatch< D >::_initial, and Stopwatch< D >::duration().
restart()
template<class D > Stopwatch& Stopwatch< D >::restart () inline
Restart the stopwatch by setting the initial and clicked time points to the current time.
Returns
A reference to the stopwatch object, allowing for method chaining.
{
         _initial = ResolutionType::now();
         _clicked = _initial;
         return *this;
     }
References Stopwatch< D >::_clicked, and Stopwatch< D >::_initial.
Referenced by fillLagrangePolys(), fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), InLab1::run(), Profiler< FunctionType >::runNoTimeout(), Profiler< FunctionType >::runWithTimeout(), Stopwatch< D >::Stopwatch(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
Field Documentation
_clicked
template<class D > TimePointType Stopwatch< D >::_clicked private
The last clicked time point, used to measure durations.
Referenced by Stopwatch< D >::click(), Stopwatch< D >::duration(), and Stopwatch< D >::restart().
_initial
template<class D > TimePointType Stopwatch< D >::_initial private
The initial time point when the stopwatch was last restarted.
Referenced by Stopwatch< D >::duration(), Stopwatch< D >::peek_elapsed_time(), and Stopwatch< D >::restart().
The documentation for this class was generated from the following file:
src/utils/Stopwatch.h