NE591-008 C++17 Codebase: InLab1 Class Reference
InLab1 Class Reference
#include <inlab1.h>
Public Member Functions
InLab1 (CommandLineArgs args)
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
Builds the header information.
void run (TaylorSeriesVariables &output, TaylorSeriesInputs &input, boost::program_options::variables_map &values) override
Executes the project.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (TaylorSeriesVariables &output, TaylorSeriesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (TaylorSeriesVariables &output, TaylorSeriesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Parser terminal
TaylorSeriesVariables outputs
Detailed Description
Constructor & Destructor Documentation
InLab1()
InLab1::InLab1 (CommandLineArgs args) inline explicit
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo InLab1::buildHeaderInfo () inline override protected virtual
Builds the header information.
Returns
The header information.
Implements Project< TaylorSeriesInputs, Parser, TaylorSeriesVariables >.
{
         return HeaderInfo{
             .ProjectName = "InLab 01",
             .ProjectDescription = "Iterative Taylor series approximation of sin(x)",
             .SubmissionDate = "08/30/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = R"(
                                        .-'~~~-.
                                      .'o  oOOOo`.
                                     :~~~-.oOo   o`.
                                      `. \ ~-.  oOOo.
                                        `.; / ~.  OO:
                                        .'  ;-- `.o.'
                                       ,'  ; ~~--'~
                                       ;  ;
 _____________________\|/__________\\;_\\//___\|/_______________________________)",
         };
     }
References HeaderInfo::ProjectName.
execute()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::finalize () inline protected virtual inherited
{
     }
getProfiler() [1/3]
auto Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::postRun (TaylorSeriesVariables & output, TaylorSeriesInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::preRun (TaylorSeriesVariables & output, TaylorSeriesInputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void InLab1::run (TaylorSeriesVariables & output, TaylorSeriesInputs & input, boost::program_options::variables_map & values) inline override protected virtual
Executes the project.
Parameters
output The output data.
input The input data.
values The variable map.
Implements Project< TaylorSeriesInputs, Parser, TaylorSeriesVariables >.
{
         std::cout << std::setw(40) << "Profile\n";
         Parser::printLine();
         Stopwatch<Microseconds> clock;
         // my_sin(x)
         long double my_sin_val;
         clock.restart();
         for (int i = 0; i < 1000; i++) {
             my_sin_val = my_sin(static_cast<long double>(i) / 1000.0f, input.N, input.target_threshold);
         }
         clock.click();
         std::cout << " my_sin(x) completed in: " << static_cast<long double>(clock.duration().count() * 1.0f) << "ns"
                   << std::endl;
         auto my_sin_val2 = my_sin(input.x, input.N, input.target_threshold);
         // sin(x)
         long double math_sin_val;
         Stopwatch<Microseconds> clock2;
         clock2.restart();
         for (int i = 0; i < 1000; i++) {
             math_sin_val = sin(static_cast<long double>(i) / 1000.0f);
         }
         clock2.click();
         std::cout << " sin(x) completed in: " << static_cast<long double>(clock2.duration().count() * 1.0f) << "ns"
                   << std::endl;
         auto math_sin_val2 = sin(input.x);
         // truncation error
         const long double truncation_error = abs(math_sin_val2 - my_sin_val2);
         Parser::printLine();
         const auto precision = values["precision"].as<int>();
         std::cout << std::setw(44) << "Outputs\n";
         Parser::printLine();
         std::cout << "\tConverged at n=" << mySineVars.n
                   << " at convergence threshold: " << mySineVars.current_threshold << "\n\t...\n";
         std::cout << "\tmy_sin(x):" << std::setw(37) << std::setprecision(precision) << my_sin_val2 << "\n";
         std::cout << "\tsin(x) from math.h:" << std::setw(28) << std::setprecision(precision) << math_sin_val2 << "\n";
         std::cout << "\ttruncation error: " << std::setw(30) << std::setprecision(precision) << truncation_error
                   << "\n";
         Parser::printLine();
         my_sin_val += my_sin_val;
         math_sin_val += math_sin_val;
     }
References MyBLAS::Stats::abs(), Stopwatch< D >::click(), Output::current_threshold, Stopwatch< D >::duration(), i, my_sin(), mySineVars, Output::n, Input::N, CommandLine< InLab6Inputs >::printLine(), Stopwatch< D >::restart(), Input::target_threshold, and Input::x.
timedRun()
virtual void Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(outputs, terminal.getInputs(), terminal.getArguments());
         run(outputs, terminal.getInputs(), terminal.getArguments());
         postRun(outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
cmdArgs
CommandLineArgs Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::cmdArgs protected inherited
outputs
TaylorSeriesVariables Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::outputs protected inherited
terminal
Parser Project< TaylorSeriesInputs , Parser , TaylorSeriesVariables >::terminal protected inherited
The documentation for this class was generated from the following file:
src/labs/inlab1/inlab1.h