NE591-008 C++17 Codebase: ProfilerHelper Namespace Reference
ProfilerHelper Namespace Reference
This namespace contains helper functions for handling command line options and initializing the profiler.
Functions
static boost::program_options::options_description buildCommandlineOptions ()
This function builds the command line options for the profiler.
static void validateOptions (boost::program_options::variables_map &map)
This function validates the input options, prompting the user if they need to be fixed.
template<typename Func >
auto InitProfiler (Func func, boost::program_options::variables_map &map, std::string description)
This function initializes the profiler with the given function, command line options, and description.
Detailed Description
This namespace contains helper functions for handling command line options and initializing the profiler.
Function Documentation
buildCommandlineOptions()
static boost::program_options::options_description ProfilerHelper::buildCommandlineOptions () static
This function builds the command line options for the profiler.
The function uses the boost::program_options library to define the command line options. The options include the number of runs to perform and the timeout duration.
Returns
Returns a boost::program_options::options_description object containing the command line options.
{
     boost::program_options::options_description profiler("Performance Benchmarking");
     profiler.add_options()
     ("bench-runs,R", boost::program_options::value<long double>()->default_value(1), "= <R> runs to perform")
     ("bench-timeout,T", boost::program_options::value<long double>()->default_value(0), "= Timeout after <T> seconds [0=never]");
     return profiler;
 }
Referenced by CommandLine< InputType >::buildGenerics().
InitProfiler()
template<typename Func > auto ProfilerHelper::InitProfiler (Func func, boost::program_options::variables_map & map, std::string description)
This function initializes the profiler with the given function, command line options, and description.
The function creates a Profiler object with the given function, number of runs, timeout duration, and description. The number of runs and timeout duration are retrieved from the command line options.
Parameters
func The function to be profiled.
map A boost::program_options::variables_map object containing the command line options.
description A string containing the description of the profiler.
Returns
Returns a Profiler object.
{
     auto runs = static_cast<size_t>(map["bench-runs"].as<long double>());
     auto timeout = map["bench-timeout"].as<long double>();
     return Profiler(func, runs, timeout, description);
 }
Referenced by Project< InputType, CommandLineParserType, OutputType >::getProfiler().
validateOptions()
static void ProfilerHelper::validateOptions (boost::program_options::variables_map & map) static
This function validates the input options, prompting the user if they need to be fixed.
The function reads the input json and populates the variables_map. It then performs checks on the parameters to ensure they meet the required conditions. If the parameters do not meet the conditions, the user is prompted to fix them.
Parameters
map A boost::program_options::variables_map object containing the command line options.
{
     // read the input json and populate the variables_map
     nlohmann::json inputMap;
     std::vector<std::function<bool(long double)>> checks;
     // add checks for parameters a & b
     checks.clear();
     checks.emplace_back([](long double value) { return failsNaturalNumberCheck(value); });
     performChecksAndUpdateInput<long double>("bench-runs", inputMap, map, checks);
     checks.clear();
     checks.emplace_back([](long double value) { return failsNonNegativeNumberCheck(value); });
     performChecksAndUpdateInput<long double>("bench-timeout", inputMap, map, checks);
 }
References failsNaturalNumberCheck(), failsNonNegativeNumberCheck(), and function.