NE591-008 C++17 Codebase: src/labs/outlab2/analysis/analysis.m File Reference
analysis.m File Reference
Functions
plot_points (n, m, x, xi, L_xi, f_xi, E_xi)
Variables
read_output_columns
read_input_columns = @(pathname) deal(readtable(pathname).('x'))
n = 3 [x] = read_input_columns('n3.csv')
m = size(xi, 1)
Function Documentation
plot_points()
plot_points (n , m , x , xi , L_xi , f_xi , E_xi)
Variable Documentation
m
m = size(xi, 1)
Referenced by fill_fluxes(), Compute::fill_fluxes(), fillLagrangePolys(), fillUsingSimpsons(), fillUsingTrapezoidal(), initialize_diffusion_matrix_and_vector(), naive_fill_diffusion_matrix_and_vector(), Compute::naive_fill_diffusion_vector(), MyPhysics::Diffusion::Params< FloatType >::Params(), Parser::printInputArguments(), MyPhysics::Diffusion::Params< FloatType >::setM(), TYPED_TEST(), MyBLAS::TYPED_TEST(), and MyBLAS::Stats::variance().
n
n = 3 [x] = read_input_columns('n3.csv')
read_input_columns
read_input_columns = @(pathname) deal(readtable(pathname).('x'))
read_output_columns
read_output_columns
Initial value:
= @(pathname) deal(readtable(pathname).('xi'), readtable(pathname).('Lxi'),
                                       readtable(pathname).('fxi'), readtable(pathname).('Exi'))