NE591-008 C++17 Codebase: src/labs/inlab3/Compute.h File Reference
Compute.h File Reference
Compute methods for inlab3 in NE591-008.
#include <cmath>
#include <iostream>
#include "CommandLine.h"
#include "InputsOutputs.h"
#include "Stopwatch.h"
Functions
template<typename T >
static T getLagrangePoly (const T xi, const std::vector< T > &x, const std::vector< T > &fx)
Computes the Lagrange polynomial for a given interpolation point xi.
template<typename T >
static void fillLagrangePolys (std::vector< T > &Lxi, const std::vector< T > &xi, const std::vector< T > &x, const std::vector< T > &fx)
This function computes the Lagrange polynomials for a given set of data points.
template<typename T >
static void fillInterpolationError (std::vector< T > &IEx, const std::vector< T > &Lxi, const std::vector< T > &fxi)
This function computes the interpolation error for a given set of data points and their corresponding Lagrange polynomials.
static long double fillUsingTrapezoidal (NewtonCotesOutputs &outputs, const NewtonCotesInputs &inputs)
This function computes the integral of a user-defined function using the trapezoidal rule.
static long double fillUsingSimpsons (NewtonCotesOutputs &outputs, const NewtonCotesInputs &inputs)
This function computes the integral of a user-defined function using Simpson's rule.
static long double fillUsingGaussianQuadratures (NewtonCotesOutputs &outputs, const NewtonCotesInputs &inputs)
This function computes the integral of a user-defined function using Gaussian quadrature.
Detailed Description
Compute methods for inlab3 in NE591-008.
Author
Arjun Earthperson
Date
09/08/2023
Definition in file Compute.h.
Function Documentation
fillInterpolationError()
template<typename T > static void fillInterpolationError (std::vector< T > & IEx, const std::vector< T > & Lxi, const std::vector< T > & fxi) static
This function computes the interpolation error for a given set of data points and their corresponding Lagrange polynomials.
Template Parameters
T The data type of the elements in the vectors.
Parameters
IEx A vector to store the computed interpolation errors.
Lxi A vector containing the computed Lagrange polynomials.
fxi A vector containing the function values at the interpolation points.
Note
The function will print an error message and return if the sizes of Lxi and fxi are not equal.
{
     // Check if the input vectors have the same size
     if (Lxi.size() != fxi.size()) {
         std::cerr << "Error: L(xi), f(xi) must have the same size." << std::endl;
         return;
     }
     IEx.clear();
     IEx.resize(Lxi.size());
     // Use std::transform with a lambda function to calculate absolute errors
     std::transform(Lxi.begin(), Lxi.end(), fxi.begin(), IEx.begin(), [](T x, T y) { return std::abs(x - y); });
 }
References x, and y.
fillLagrangePolys()
template<typename T > static void fillLagrangePolys (std::vector< T > & Lxi, const std::vector< T > & xi, const std::vector< T > & x, const std::vector< T > & fx) static
This function computes the Lagrange polynomials for a given set of data points.
Template Parameters
T The data type of the elements in the vectors.
Parameters
Lxi A vector to store the computed Lagrange polynomials.
xi A vector containing the x-coordinates of the interpolation points.
x A vector containing the x-coordinates of the data points.
fx A vector containing the y-coordinates (function values) of the data points.
Note
The function also prints the time taken to compute the Lagrange polynomials.
{
     const size_t m = std::min(xi.size(), Lxi.size());
     Lxi.reserve(m);
     for (size_t i = 0; i < m; i++) {
         Lxi[i] = getLagrangePoly(xi[i], x, fx);
     }
 }
References getLagrangePoly(), i, m, MyBLAS::Stats::min(), and x.
fillUsingGaussianQuadratures()
static long double fillUsingGaussianQuadratures (NewtonCotesOutputs & outputs, const NewtonCotesInputs & inputs) static
This function computes the integral of a user-defined function using Gaussian quadrature.
Parameters
outputs A reference to a NewtonCotesOutputs object to store the computed integral and step size.
inputs A constant reference to a NewtonCotesInputs object containing the input parameters for Gaussian quadrature.
Returns
The computed integral value as a long double.
Note
The function is not implemented yet and will print a message indicating that it is not available.
{
     std::cout << "\tGauss-Legendre Quadrature not available yet." << std::endl;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References process::inputs, and Output::integral.
Referenced by InLab3::run(), and OutLab3::run().
fillUsingSimpsons()
static long double fillUsingSimpsons (NewtonCotesOutputs & outputs, const NewtonCotesInputs & inputs) static
This function computes the integral of a user-defined function using Simpson's rule.
Parameters
outputs A reference to a NewtonCotesOutputs object to store the computed integral and step size.
inputs A constant reference to a NewtonCotesInputs object containing the input parameters for Simpson's rule.
Returns
The computed integral value as a long double.
Note
The function also prints the time taken to compute the integral.
{
     const size_t m = inputs.m;
     const long double b = inputs.b;
     const long double a = inputs.a;
     const long double h = (b - a) / m;
     Stopwatch<Nanoseconds> timer;
     timer.restart();
     long double sum = user_defined_fx(a) + user_defined_fx(b);
     for (size_t i = 1; i < m; i += 2) {
         sum += 4.0f * user_defined_fx(a + i * h);
     }
     for (size_t i = 2; i < m - 1; i += 2) {
         sum += 2.0f * user_defined_fx(a + i * h);
     }
     timer.click();
     std::cout << "Computing integral using Simpson's rule for m=(" << m << ") intervals took "
               << (static_cast<long double>(timer.duration().count())) << " ns" << std::endl;
     outputs.h = h;
     outputs.integral = h * sum / 3.0f;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References Stopwatch< D >::click(), Stopwatch< D >::duration(), Output::h, i, process::inputs, Output::integral, m, Stopwatch< D >::restart(), MyBLAS::Stats::sum(), and user_defined_fx().
Referenced by InLab3::run(), and OutLab3::run().
fillUsingTrapezoidal()
static long double fillUsingTrapezoidal (NewtonCotesOutputs & outputs, const NewtonCotesInputs & inputs) static
This function computes the integral of a user-defined function using the trapezoidal rule.
Parameters
outputs A reference to a NewtonCotesOutputs object to store the computed integral and step size.
inputs A constant reference to a NewtonCotesInputs object containing the input parameters for the trapezoidal rule.
Returns
The computed integral value as a long double.
Note
The function also prints the time taken to compute the integral.
{
     // setup
     const size_t m = inputs.m;
     const long double b = inputs.b;
     const long double a = inputs.a;
     const long double h = (b - a) / m;
     Stopwatch<Nanoseconds> timer;
     timer.restart();
     // long double h = (b - a) / (n);
     long double compositeIntegral = user_defined_fx(a) + user_defined_fx(b);
     for (size_t i = 1; i < m; i++) {
         compositeIntegral += 2 * user_defined_fx(a + i * h);
     }
     timer.click();
     std::cout << "Computing integral using trapezoidal rule for m=(" << m << ") intervals took "
               << (static_cast<long double>(timer.duration().count())) << " ns" << std::endl;
     // finally, update the output values
     outputs.h = h;
     outputs.integral = (h / 2.0) * compositeIntegral;
     if (inputs.flip_integral) {
         outputs.integral = -outputs.integral;
     }
     return outputs.integral;
 }
References Stopwatch< D >::click(), Stopwatch< D >::duration(), Output::h, i, process::inputs, Output::integral, m, Stopwatch< D >::restart(), and user_defined_fx().
Referenced by InLab3::run(), and OutLab3::run().
getLagrangePoly()
template<typename T > static T getLagrangePoly (const T xi, const std::vector< T > & x, const std::vector< T > & fx) static
Computes the Lagrange polynomial for a given interpolation point xi.
Template Parameters
T The data type of the elements in the vectors.
Parameters
xi The interpolation point.
x A vector containing the x-coordinates of the data points.
fx A vector containing the y-coordinates (function values) of the data points.
Returns
The value of the Lagrange polynomial at the interpolation point xi.
{
     T Px = 0.0f;
     const size_t n = std::min(x.size(), fx.size());
     for (size_t j = 0; j < n; j++) {
         T Pjx = fx[j];
         // go from k -> j-1
         T Pjx_product1 = 1.0f;
         for (size_t k = 0; k < j; k++) {
             T Pjxk = (xi - x[k]) / (x[j] - x[k]);
             Pjx_product1 *= Pjxk;
         }
         // skip k == j;
         // then, from k+1 -> n
         T Pjx_product2 = 1.0f;
         for (size_t k = j + 1; k < n; k++) {
             T Pjxk = (xi - x[k]) / (x[j] - x[k]);
             Pjx_product2 *= Pjxk;
         }
         Px += (Pjx * Pjx_product1 * Pjx_product2);
     }
     return Px;
 }
References k, MyBLAS::Stats::min(), n, and x.
Referenced by fillLagrangePolys().