NE591-008 C++17 Codebase: OutLab3 Class Reference
OutLab3 Class Reference
A class for performing numerical integration using Composite Newton-Cotes Formulas.
#include <outlab3.h>
Public Member Functions
OutLab3 (CommandLineArgs args)
Constructor for the InLab3 class.
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
NewtonCotesInputs & getInputs ()
Returns the input data.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
Builds the header information for the project.
void run (Dictionary &outputs, NewtonCotesInputs &inputs, boost::program_options::variables_map &values) override
Runs the numerical integration using Composite Newton-Cotes Formulas.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (Dictionary &output, NewtonCotesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (Dictionary &output, NewtonCotesInputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Holds the command line arguments.
Parser terminal
An instance of CommandLineParserType which is used to parse command line arguments.
Dictionary _outputs
Holds the output data of the project.
Detailed Description
A class for performing numerical integration using Composite Newton-Cotes Formulas.
This class is derived from the Project class and implements the numerical integration using Composite Newton-Cotes Formulas. It takes command line arguments, parses the inputs, performs the integration, and outputs the results.
Constructor & Destructor Documentation
OutLab3()
OutLab3::OutLab3 (CommandLineArgs args) inline explicit
Constructor for the InLab3 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab3::buildHeaderInfo () inline override protected virtual
Builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< NewtonCotesInputs, Parser, Dictionary >.
{
         return {
             .ProjectName = "OutLab 03",
             .ProjectDescription = "Numerical Integration using Newton-Cotes & Gauss-Legendre",
             .SubmissionDate = "09/15/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = R"(
              .              +   .                .   . .     .  .       .
                                .                    .       .     *
      .        .       *                        . . . .  .   .  + .             .
                         "You Are Here"            .   .  +  . . .
             .                 |             .  .   .    .    . .     .
                               |           .     .     . +.    +  .
 .                            \|/            .       .   . .             .
          .          . .       V          .    * . . .  .  +   .
      .                 +      .           .   .      +                      .
                                         .       . +  .+. .
     .         .                      .     . + .  . .     .      .
                        .      .    .     . .   . . .        ! /                   .
       .           *             .    . .  +    .  .       - O -      .
               .       .     .    .  +   . .  *  .       . / |
 .                          . + .  .  .  .. +  .                 .               .
             .      .  .  .  *   .  *  . +..  .            *
              .      .   . .   .   .   . .  +   .    .            +        .
 )",
         };
     }
References HeaderInfo::ProjectName.
execute()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::finalize () inline protected virtual inherited
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
getInputs()
NewtonCotesInputs & Project< NewtonCotesInputs , Parser , Dictionary >::getInputs () inline inherited
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
getProfiler() [1/3]
auto Project< NewtonCotesInputs , Parser , Dictionary >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< NewtonCotesInputs , Parser , Dictionary >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< NewtonCotesInputs , Parser , Dictionary >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< NewtonCotesInputs , Parser , Dictionary >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
postRun()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::postRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::preRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void OutLab3::run (Dictionary & outputs, NewtonCotesInputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
Runs the numerical integration using Composite Newton-Cotes Formulas.
Parameters
outputs Dictionary object to store the outputs
inputs NewtonCotesInputs object containing the parsed inputs
values Boost program_options variables_map containing command line arguments
Reimplemented from Project< NewtonCotesInputs, Parser, Dictionary >.
{
         // declare the JSON object and file
         nlohmann::json JSONFile;
         // write the inputs to file
         nlohmann::json inputsJSON;
         inputs.toJSON(inputsJSON);
         JSONFile["inputs"] = inputsJSON;
         nlohmann::json outputsJSON;
         const auto precision = values["precision"].as<int>();
         std::cout << std::setw(40) << "Outputs\n";
         Parser::printLine();
         if (inputs.integral_types.count(RULE_COMPOSITE_TRAPEZOIDAL)) {
             NewtonCotesOutputs output1;
             fillUsingTrapezoidal(output1, inputs);
             nlohmann::json json1;
             output1.toJSON(json1);
             outputsJSON[ruleKey(RULE_COMPOSITE_TRAPEZOIDAL)] = json1;
             std::cout << "Integral over [a,b] using trapezoidal rule: " << std::setprecision(static_cast<int>(precision))
                       << output1.integral << std::endl;
             Parser::printLine();
         }
         if (inputs.integral_types.count(RULE_COMPOSITE_SIMPSONS)) {
             NewtonCotesOutputs output2;
             fillUsingSimpsons(output2, inputs);
             nlohmann::json json2;
             output2.toJSON(json2);
             outputsJSON[ruleKey(RULE_COMPOSITE_SIMPSONS)] = json2;
             std::cout << "Integral over [a,b] using Simpson's rule:   " << std::setprecision(static_cast<int>(precision))
                       << output2.integral << std::endl;
             Parser::printLine();
         }
         if (inputs.integral_types.count(RULE_GAUSSIAN_QUADRATURE)) {
             GaussLegendreOutputs output3;
             fillUsingGaussianQuadratures(output3, inputs);
             nlohmann::json json3;
             output3.toJSON(json3);
             outputsJSON[ruleKey(RULE_GAUSSIAN_QUADRATURE)] = json3;
             std::cout << "Integral over [a,b] using Gauss-Legendre Quadrature:   " << std::setprecision(static_cast<int>(precision))
                       << output3.integral << std::endl;
             Parser::printLine();
         }
         // create the outputs object
         JSONFile["outputs"] = outputsJSON;
         writeJSON(values["output-json"].as<std::string>(), JSONFile);
     }
References fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), process::inputs, Output::integral, Outputs::integral, CommandLine< InLab6Inputs >::printLine(), RULE_COMPOSITE_SIMPSONS, RULE_COMPOSITE_TRAPEZOIDAL, RULE_GAUSSIAN_QUADRATURE, ruleKey(), Output::toJSON(), Outputs::toJSON(), and writeJSON().
timedRun()
virtual void Project< NewtonCotesInputs , Parser , Dictionary >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
_outputs
Dictionary Project< NewtonCotesInputs , Parser , Dictionary >::_outputs protected inherited
Holds the output data of the project.
cmdArgs
CommandLineArgs Project< NewtonCotesInputs , Parser , Dictionary >::cmdArgs protected inherited
Holds the command line arguments.
terminal
Parser Project< NewtonCotesInputs , Parser , Dictionary >::terminal protected inherited
An instance of CommandLineParserType which is used to parse command line arguments.
The documentation for this class was generated from the following file:
src/labs/outlab3/outlab3.h