NE591-008 C++17 Codebase: src/utils/FileParser.h File Reference
FileParser.h File Reference
This file contains the definitions for functions that handle file parsing operations.
#include <boost/tokenizer.hpp>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <chrono>
#include <memory>
#include <mutex>
#include <thread>
#include "math/blas/matrix/Matrix.h"
#include "json.hpp"
Functions
static bool isFileWritable (const std::string &filepath)
Checks if a file is writable.
static bool isDirectoryWritable (const std::string &directoryPath)
Checks if a directory exists. If it doesn't exist, it is created.
static bool doesFileExist (const std::string &filepath)
Checks if a file exists and is not a directory.
template<typename T >
void readCSV (const std::string &filepath, std::map< std::string, std::vector< T >> &data)
Reads a CSV file and stores the data in a map.
template<typename T >
void readCSVRowWiseNoHeaders (const std::string &filepath, MyBLAS::Matrix< T > &data)
Reads a CSV file without headers and stores the data in a 2D vector.
template<typename T >
static std::vector< std::string > asStringVector (const std::vector< T > &inputVector, const int precision=19)
Converts a vector of any type to a vector of strings.
static void writeCSV (const std::string &filepath, std::map< std::string, std::vector< std::string >> &data, const std::vector< std::string > &columns)
Writes data to a CSV file.
template<typename T >
static void writeCSVMatrixNoHeaders (const std::string &filepath, MyBLAS::Matrix< T > &data)
A template function to write a matrix to a CSV file without headers.
template<typename T >
static void writeCSVMatrixNoHeaders (const std::string &directory, const std::string &file, MyBLAS::Matrix< T > &data)
static void readJSON (const std::string &filepath, nlohmann::json &map)
Reads a JSON file and stores the data in a JSON object.
static void writeJSON (const std::string &filepath, nlohmann::json &data)
Writes the given JSON data to a file at the specified file path.
Detailed Description
This file contains the definitions for functions that handle file parsing operations.
Author
Arjun Earthperson
Date
09/01/2023
Definition in file FileParser.h.
Function Documentation
asStringVector()
template<typename T > static std::vector<std::string> asStringVector (const std::vector< T > & inputVector, const int precision = 19) static
Converts a vector of any type to a vector of strings.
This function template takes a vector of any type and converts each element to a string. The conversion is done using a stringstream and the scientific notation is used for the conversion. The precision of the conversion can be specified as an optional parameter.
Template Parameters
T The type of the elements in the input vector. This can be any type that can be streamed into a stringstream.
Parameters
inputVector The vector of elements to be converted to strings.
precision The precision to be used for the conversion. This is optional and defaults to 19.
Returns
A vector of strings where each string is the string representation of the corresponding element in the input vector.
Example usage:
std::vector<int> intVector = {1, 2, 3};
std::vector<std::string> stringVector = asStringVector(intVector);
{
     std::vector<std::string> stringVector;
     stringVector.reserve(inputVector.size()); // Reserve space for efficiency
     for (const T &value : inputVector) {
         std::stringstream ss;
         ss << std::scientific << std::setprecision(static_cast<int>(precision)) << value;
         stringVector.push_back(ss.str());
     }
     return stringVector;
 }
Referenced by InLab2::run().
doesFileExist()
static bool doesFileExist (const std::string & filepath) static
Checks if a file exists and is not a directory.
This function checks if a file exists at the given file path and if it is not a directory. If the file does not exist or if it is a directory, an error message is displayed and the function returns false. If the file exists and is not a directory, the function returns true.
Parameters
filepath The path to the file.
Returns
True if the file exists and is not a directory, false otherwise.
{
     const std::filesystem::path path(filepath);
     std::error_code ec; // For using the non-throwing overloads of functions below.
     if (!exists(path, ec)) {
         return false;
     }
     if (std::filesystem::is_directory(path, ec)) {
         std::cerr << "Error: Provided path is a directory. " << std::endl;
         return false;
     }
     return true;
 }
Referenced by Parser::performInputArgumentsCheck().
isDirectoryWritable()
static bool isDirectoryWritable (const std::string & directoryPath) static
Checks if a directory exists. If it doesn't exist, it is created.
Parameters
filepath The path to the directory.
Returns
True if the directory is writable, false otherwise.
{
     const std::filesystem::path path(directoryPath);
     std::error_code ec; // For using the non-throwing overloads of functions below.
     if (exists(path, ec)) {
         if (!std::filesystem::is_directory(path, ec)) {
             std::cerr << "Error: Provided path is a not directory: " << directoryPath << std::endl;
             return false;
         }
         return true;
     } else {
         // Create the directory and all necessary parent directories, similar to "mkdir -p"
         if (!std::filesystem::create_directories(path, ec)) {
             std::cerr << "Error: Unable to create directory: " << directoryPath<<std::endl;
             return false;
         }
     }
     return true;
 }
Referenced by Parser::performInputArgumentsCheck(), and writeCSVMatrixNoHeaders().
isFileWritable()
static bool isFileWritable (const std::string & filepath) static
Checks if a file is writable.
Parameters
filepath The path to the file.
Returns
True if the file is writable, false otherwise.
{
     const std::filesystem::path path(filepath);
     std::error_code ec; // For using the non-throwing overloads of functions below.
     if (exists(path, ec)) {
         if (std::filesystem::is_directory(path, ec)) {
             std::cerr << "Provided path is a directory: " << filepath << std::endl;
             return false;
         }
         return true;
     }
     return true;
 }
Referenced by Parser::performInputArgumentsCheck(), writeCSV(), writeCSVMatrixNoHeaders(), and writeJSON().
readCSV()
template<typename T > void readCSV (const std::string & filepath, std::map< std::string, std::vector< T >> & data)
Reads a CSV file and stores the data in a map.
Template Parameters
T The type of the data to be read.
Parameters
filepath The path to the CSV file.
data A reference to a map where the data will be stored.
{
     // Open the CSV file
     std::ifstream inputFile(filepath);
     if (!inputFile.is_open()) {
         std::cerr << "Error: Unable to open the input CSV: " << filepath << std::endl;
         exit(1);
     }
     std::vector<std::string> columnIndices;
     // Read the header row to get column names
     std::string header;
     if (std::getline(inputFile, header)) {
         // Tokenize the header row using boost::tokenizer
         boost::char_separator<char> separator(",");
         boost::tokenizer<boost::char_separator<char>> headerTokens(header, separator);
         // Initialize the map with column names as keys
         for (const auto &columnName : headerTokens) {
             data[columnName].clear(); // Clear any existing data for this column
             columnIndices.push_back(columnName);
         }
         // Read and parse the data rows
         std::string line;
         while (std::getline(inputFile, line)) {
             // Tokenize the line using boost::tokenizer
             boost::tokenizer<boost::char_separator<char>> tokens(line, separator);
             size_t idx = 0;
             for (const auto &token : tokens) {
                 try {
                     (data[columnIndices[idx++]]).push_back(boost::lexical_cast<long double>(token));
                 } catch (const boost::bad_lexical_cast &ex) {
                     std::cerr << "Error: Failed to convert to long double: " << ex.what() << std::endl;
                 }
             }
         }
     } else {
         std::cerr << "Error: CSV file is empty." << std::endl;
     }
     // Close the file
     inputFile.close();
 }
References data, and process::line.
Referenced by Parser::performInputArgumentsCheck().
readCSVRowWiseNoHeaders()
template<typename T > void readCSVRowWiseNoHeaders (const std::string & filepath, MyBLAS::Matrix< T > & data)
Reads a CSV file without headers and stores the data in a 2D vector.
Template Parameters
T The type of the data to be read.
Parameters
filepath The path to the CSV file.
data A reference to a 2D vector where the data will be stored.
{
     // Open the CSV file
     std::ifstream inputFile(filepath);
     if (!inputFile.is_open()) {
         std::cerr << "Error: Unable to open the input CSV: " << filepath << std::endl;
         exit(1);
     }
     // Read and parse the data rows
     std::string line;
     while (std::getline(inputFile, line)) {
         // Tokenize the line using boost::tokenizer
         boost::char_separator<char> separator(",");
         boost::tokenizer<boost::char_separator<char>> tokens(line, separator);
         std::vector<T> row;
         for (const auto &token : tokens) {
             try {
                 row.push_back(boost::lexical_cast<T>(token));
             } catch (const boost::bad_lexical_cast &ex) {
                 std::cerr << "Error: Failed to convert to type T: " << ex.what() << std::endl;
             }
         }
         data.push_back(row);
     }
     // Close the file
     inputFile.close();
 }
References data, process::line, and process::row.
readJSON()
static void readJSON (const std::string & filepath, nlohmann::json & map) static
Reads a JSON file and stores the data in a JSON object.
This function opens a JSON file at the given file path for reading. If the file cannot be opened, an error message is displayed and the program exits. The JSON data is then read from the file and stored in the provided JSON object.
Parameters
filepath The path to the JSON file.
map A reference to a JSON object where the data will be stored.
{
     // Open the JSON file
     std::ifstream inputFile(filepath);
     if (!inputFile.is_open()) {
         std::cerr << "Error: Unable to open the input JSON: " << filepath << std::endl;
         exit(1);
     }
     // read the file
     map = nlohmann::json::parse(inputFile);
 }
Referenced by Parser::buildInputs(), and Parser::performInputArgumentsCheck().
writeCSV()
static void writeCSV (const std::string & filepath, std::map< std::string, std::vector< std::string >> & data, const std::vector< std::string > & columns) static
Writes data to a CSV file.
Parameters
filepath The path to the CSV file.
data A reference to a map containing the data to be written.
columns A vector containing the names of the columns.
{
     if (!isFileWritable(filepath)) {
         std::cerr << "Error: Unable to write output CSV to path: " << filepath << std::endl;
         return;
     }
     // Open the CSV file for writing
     std::ofstream csvFile(filepath);
     // Check if the file was opened successfully
     if (!csvFile.is_open()) {
         std::cerr << "Error opening the output CSV file" << filepath << std::endl;
         return;
     }
     // Write the header row
     for (const auto &column : columns) {
         if (data.count(column)) {
             csvFile << column << ",";
         }
     }
     csvFile << "\n";
     // Find the maximum size among all value vectors to determine the number of rows
     size_t numRows = 0;
     for (const auto &pair : data) {
         size_t currentSize = pair.second.size();
         if (currentSize > numRows) {
             numRows = currentSize;
         }
     }
     // Write the data rows
     for (size_t i = 0; i < numRows; i++) {
         for (const auto &column : columns) {
             if (data.count(column)) {
                 if (i < data[column].size()) {
                     csvFile << data[column][i];
                 }
                 csvFile << ",";
             }
         }
         csvFile << "\n";
     }
     // Close the CSV file
     csvFile.close();
 }
References data, i, and isFileWritable().
Referenced by InLab2::run().
writeCSVMatrixNoHeaders() [1/2]
template<typename T > static void writeCSVMatrixNoHeaders (const std::string & directory, const std::string & file, MyBLAS::Matrix< T > & data) static
{
     if (!isDirectoryWritable(directory)) {
         return;
     }
     writeCSVMatrixNoHeaders(directory+"/"+file, data);
 }
References data, isDirectoryWritable(), and writeCSVMatrixNoHeaders().
writeCSVMatrixNoHeaders() [2/2]
template<typename T > static void writeCSVMatrixNoHeaders (const std::string & filepath, MyBLAS::Matrix< T > & data) static
A template function to write a matrix to a CSV file without headers.
This function writes a matrix to a CSV file. If the file is not writable, an error message is printed.
Template Parameters
T The type of the matrix elements.
Parameters
filepath The path to the CSV file.
data The matrix to be written to the CSV file.
{
     if (!isFileWritable(filepath)) {
         std::cerr << "Error: Unable to write output CSV to path: " << filepath << std::endl;
         return;
     }
     // Open the CSV file for writing
     std::ofstream csvFile(filepath);
     // Check if the file was opened successfully
     if (!csvFile.is_open()) {
         std::cerr << "Error opening the output CSV file" << filepath << std::endl;
         return;
     }
     for (size_t i = 0; i < data.getRows(); i++) {
         for (size_t j = 0; j < data.getCols(); j++) {
             csvFile << data[i][j] << ((j == data.getCols() - 1) ? "\n" : ",");
         }
     }
     // Close the CSV file
     csvFile.close();
 }
References data, i, and isFileWritable().
Referenced by Project1::run(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), Compute::usingSymmetricGaussSeidel(), Compute::usingSymmetricSOR(), and writeCSVMatrixNoHeaders().
writeJSON()
static void writeJSON (const std::string & filepath, nlohmann::json & data) static
Writes the given JSON data to a file at the specified file path.
This function checks if the file is writable and opens it for writing. If the file cannot be opened, an error message is displayed. The JSON data is then written to the file with pretty formatting (indented with 4 spaces). A success message is displayed upon successful writing of the JSON data.
Parameters
filepath The path of the file to write the JSON data to.
data The JSON data to be written to the file.
{
     if (!isFileWritable(filepath)) {
         std::cerr << "Error: Unable to write output JSON to path: " << filepath << std::endl;
         return;
     }
     // Open the CSV file for writing
     std::ofstream jsonFile(filepath);
     // Check if the file was opened successfully
     if (!jsonFile.is_open()) {
         std::cerr << "Error opening the output JSON file" << filepath << std::endl;
         return;
     }
     // Write the JSON data to the file
     jsonFile << data.dump(4); // The '4' argument is for pretty formatting with 4 spaces
     std::cout << "JSON data has been written to " << filepath << std::endl;
 }
References data, and isFileWritable().
Referenced by InLab10::postRun(), OutLab7::postRun(), InLab3::run(), OutLab3::run(), InLab6::run(), InLab5::run(), OutLab4::run(), OutLab6::run(), InLab4::run(), OutLab5::run(), Project1::run(), Project2::run(), and Project3::run().