NE591-008 C++17 Codebase: InLab10 Class Reference
InLab10 Class Reference
This class is a child of the MPI Project class.
#include <inlab10.h>
Public Member Functions
InLab10 (InLab10 const &)=delete
This function is used to delete the copy constructor.
void operator= (InLab10 const &)=delete
This function is used to delete the assignment operator.
void execute ()
Executes the project. It calls the preRun, run, and postRun methods, and then finalizes MPI.
Static Public Member Functions
static InLab10 & getInstance (CommandLineArgs args)
This function is used to get the instance of the InLab10 class.
static std::string hostname ()
Gets the name of the processor that the current process is running on.
Protected Member Functions
InLab10 (CommandLineArgs args)
Constructor for the inlab10 class.
bool preRun (InLab10Outputs &outputs, InLab10Inputs &inputs, const int rank, const int size) override
Used to check if the number of processes is a power of 2 before running the main computation.
bool run (InLab10Outputs &outputs, InLab10Inputs &inputs, const int rank, const int size) override
This function is used to perform the main computation.
bool postRun (InLab10Outputs &outputs, InLab10Inputs &inputs, const int rank, const int size) override
This function is used to perform operations after the main computation.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
void finalize ()
Finalizes MPI.
Static Protected Member Functions
static HeaderInfo buildHeaderInfo ()
This function builds the header information for the project.
static InLab10Inputs getInputs (HeaderInfo header, CommandLineArgs args, const int rank, const int size)
Gets the inputs for the project. If the rank is not 0, it receives the inputs from the main process. If the rank is 0, it sends the inputs to all other processes.
Protected Attributes
int _rank
The rank of the current process in the MPI_COMM_WORLD communicator.
int _size
The total number of processes in the MPI_COMM_WORLD communicator.
std::string _uuid
A unique identifier for the current process.
InLab10Inputs _inputs
The inputs for the project.
InLab10Outputs _outputs
The outputs of the project.
Static Private Member Functions
static void blockingSend (const DataType &data, const int rank)
Sends data to a process with a given rank.
static DataType blockingReceive ()
Receives data from any process.
Detailed Description
This class is a child of the MPI Project class.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
InLab10() [1/2]
InLab10::InLab10 (InLab10 const &) delete
This function is used to delete the copy constructor.
This function ensures that the InLab10 class cannot be copied. This is necessary because we are following the Singleton design pattern.
Parameters
InLab10 const& The reference to the InLab10 object to be copied.
InLab10() [2/2]
InLab10::InLab10 (CommandLineArgs args) inline explicit protected
Constructor for the inlab10 class.
Parameters
args Command line arguments
 : MPIProject<InLab10Inputs, Parser, InLab10Outputs>(buildHeaderInfo(), args) {}
Member Function Documentation
blockingReceive()
static DataType MPIProject< InLab10Inputs , Parser , InLab10Outputs >::blockingReceive () inline static private inherited
Receives data from any process.
Template Parameters
DataType The type of the data to be received.
Returns
The received data.
{
         MPI_Status status;
         int length;
         MPI_Probe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &status);
         MPI_Get_count(&status, MPI_CHAR, &length);
         char* buffer = new char[static_cast<size_t>(length)];
         MPI_Recv(buffer, length, MPI_CHAR, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
         std::string received_str(buffer);
         delete[] buffer;
         std::istringstream iss(received_str);
         boost::archive::text_iarchive ia(iss);
         DataType received;
         ia >> received;
         return received;
     }
blockingSend()
static void MPIProject< InLab10Inputs , Parser , InLab10Outputs >::blockingSend (const DataType & data, const int rank) inline static private inherited
Sends data to a process with a given rank.
Template Parameters
DataType The type of the data to be sent.
Parameters
data The data to be sent.
rank The rank of the process to send the data to.
{
         std::ostringstream oss;
         boost::archive::text_oarchive oa(oss);
         oa << data;
         std::string serialized = oss.str();
         const int length = static_cast<int>(serialized.size()) + 1;
         MPI_Send(serialized.c_str(), length, MPI_CHAR, rank, 0, MPI_COMM_WORLD);
     }
buildHeaderInfo()
static HeaderInfo InLab10::buildHeaderInfo () inline static protected
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
{
         Canvas canvas;
         const __float128 x = 0.13;
         const __float128 y = -0.66;
         const size_t iterations = 80;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         canvas.tone_map.growth_rate = 0.25;
         return {
             .ProjectName = "NE591: InLab 10",
             .ProjectDescription = "Matrix-Vector Operations Setup",
             .SubmissionDate = "10/27/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = drawJuliaSet<__float128>(canvas, x, y, iterations),
         };
     }
References postprocess::iterations, CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
void MPIProject< InLab10Inputs , Parser , InLab10Outputs >::execute () inline inherited
Executes the project. It calls the preRun, run, and postRun methods, and then finalizes MPI.
                    {
         if (preRun(this->_outputs, this->_inputs, this->_rank, this->_size)) {
             goto quit;
         }
         if (run(this->_outputs, this->_inputs, this->_rank, this->_size)) {
             goto quit;
         }
         if (postRun(this->_outputs, this->_inputs, this->_rank, this->_size)) {
             goto quit;
         }
     quit:
         finalize();
     }
finalize()
void MPIProject< InLab10Inputs , Parser , InLab10Outputs >::finalize () inline protected inherited
Finalizes MPI.
                     {
         MPI_Finalize();
     }
getInputs()
static InLab10Inputs MPIProject< InLab10Inputs , Parser , InLab10Outputs >::getInputs (HeaderInfo header, CommandLineArgs args, const int rank, const int size) inline static protected inherited
Gets the inputs for the project. If the rank is not 0, it receives the inputs from the main process. If the rank is 0, it sends the inputs to all other processes.
Parameters
header The header information for the project.
args The command line arguments.
rank The rank of the current process.
size The total number of processes.
Returns
The inputs for the project.
{
         // receive from main
         if (rank != 0) {
             return blockingReceive<InputType>();
         }
         // send to all but main
         InputType inputs;
         auto terminal = CommandLineParserType(header, args);
         inputs = terminal.getInputs();
         for(int i = 1; i < size; i++) {
             blockingSend(inputs, i);
         }
         return inputs;
     }
getInstance()
static InLab10& InLab10::getInstance (CommandLineArgs args) inline static
This function is used to get the instance of the InLab10 class.
This function follows the Singleton design pattern. It ensures that only one instance of the InLab10 class is created.
Parameters
args Command line arguments
Returns
Returns the instance of the InLab10 class.
{
         static InLab10 instance(args);
         return instance;
     }
Referenced by main().
getProfiler()
auto MPIProject< InLab10Inputs , Parser , InLab10Outputs >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
hostname()
static std::string MPIProject< InLab10Inputs , Parser , InLab10Outputs >::hostname () inline static inherited
Gets the name of the processor that the current process is running on.
Returns
The name of the processor.
{
         char hostname[MPI_MAX_PROCESSOR_NAME];
         int resultlen;
         MPI_Get_processor_name(hostname, &resultlen);
         return std::string{hostname, static_cast<size_t>(resultlen)};
     }
operator=()
void InLab10::operator= (InLab10 const &) delete
This function is used to delete the assignment operator.
This function ensures that the InLab10 class cannot be assigned. This is necessary because we are following the Singleton design pattern.
Parameters
InLab10 const& The reference to the InLab10 object to be assigned.
postRun()
bool InLab10::postRun (InLab10Outputs & outputs, InLab10Inputs & inputs, const int rank, const int size) inline override protected virtual
This function is used to perform operations after the main computation.
The final sum is printed in the root process and the inputs and outputs are written to a JSON file.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
rank The rank of the current process.
size The total number of processes.
Returns
Returns false to indicate that the post-run operations were successful.
Reimplemented from MPIProject< InLab10Inputs, Parser, InLab10Outputs >.
{
         if (rank != 0) {
             return false;
         }
         std::cout << outputs << std::endl;
         nlohmann::json results;
         inputs.toJSON(results["inputs"]);
         outputs.toJSON(results["outputs"]);
         writeJSON(inputs.outputJSON, results);
         return false;
     }
References process::inputs, postprocess::outputs, and writeJSON().
preRun()
bool InLab10::preRun (InLab10Outputs & outputs, InLab10Inputs & inputs, const int rank, const int size) inline override protected virtual
Used to check if the number of processes is a power of 2 before running the main computation.
If the number of processes is not a power of 2, an error message is printed and the function returns true to indicate an error.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
rank The rank of the current process.
size The total number of processes.
Returns
Returns true if the number of processes is not a power of 2, false otherwise.
Reimplemented from MPIProject< InLab10Inputs, Parser, InLab10Outputs >.
{
         if (failsPowerOf2Check(size)) {
             if (rank == 0) {
                 std::cerr << "Number of processes is not a power of 2";
             }
             return true;
         }
         return false;
     }
References failsPowerOf2Check().
run()
bool InLab10::run (InLab10Outputs & outputs, InLab10Inputs & inputs, const int rank, const int size) inline override protected virtual
This function is used to perform the main computation.
The computation is divided among the processes. Each process computes a partial sum and then the partial sums are combined using a binary tree communication logic.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
rank The rank of the current process.
size The total number of processes.
Returns
Returns false to indicate that the computation was successful.
Reimplemented from MPIProject< InLab10Inputs, Parser, InLab10Outputs >.
{
         auto profiler = getProfiler([&rank, &inputs, &size, &outputs]{
             // A, y
             auto A = inputs.coefficients;
             auto y = inputs.constants;
             // z = Cy
             auto z = static_cast<MyBLAS::NumericType>(2.0) * y;
             // sum = y + z
             auto sum = y + z;
             // product = y^T  z
             auto product = y * z;
             // matrix weighted inner product = y^T  Az
             auto matrix_weighted_inner_product = y * (A * z);
             outputs.scaled_vector = z;
             outputs.vector_sum = sum;
             outputs.scalar_product = product;
             outputs.matrix_inner_product = matrix_weighted_inner_product;
         }, 10000, 0, "Matrix-Vector Operations").run();
         if (rank == 0) {
             outputs.summary = profiler.getSummary();
             std::cout<<profiler<<std::endl;
         }
         return false;
     }
References MPIProject< InLab10Inputs, Parser, InLab10Outputs >::getProfiler(), process::inputs, postprocess::outputs, MyBLAS::Stats::sum(), y, and z.
Field Documentation
_inputs
InLab10Inputs MPIProject< InLab10Inputs , Parser , InLab10Outputs >::_inputs protected inherited
The inputs for the project.
_outputs
InLab10Outputs MPIProject< InLab10Inputs , Parser , InLab10Outputs >::_outputs protected inherited
The outputs of the project.
_rank
int MPIProject< InLab10Inputs , Parser , InLab10Outputs >::_rank protected inherited
The rank of the current process in the MPI_COMM_WORLD communicator.
_size
int MPIProject< InLab10Inputs , Parser , InLab10Outputs >::_size protected inherited
The total number of processes in the MPI_COMM_WORLD communicator.
_uuid
std::string MPIProject< InLab10Inputs , Parser , InLab10Outputs >::_uuid protected inherited
A unique identifier for the current process.
The documentation for this class was generated from the following file:
src/labs/inlab10/inlab10.h