NE591-008 C++17 Codebase: MyFactorizationMethod Namespace Reference
MyFactorizationMethod Namespace Reference
This namespace contains methods and structures for matrix factorization.
Data Structures
struct Parameters
Structure to hold the parameters for the factorization methods.
Enumerations
enum Type { METHOD_LU , METHOD_LUP }
Enumeration of the types of factorization methods.
Functions
const char * TypeKey (MyFactorizationMethod::Type value)
Function to get the string representation of the factorization method type.
template<typename MatrixType , typename VectorType >
bool passesPreChecks (const MatrixType &A, const VectorType &b)
template<typename T >
bool passesPostChecks (const MyBLAS::Matrix< T > &L, const MyBLAS::Matrix< T > &U, const MyBLAS::Matrix< T > &P)
Function to check if the factorized matrices pass the post-checks for the factorization methods.
Detailed Description
This namespace contains methods and structures for matrix factorization.
Enumeration Type Documentation
Type
enum MyFactorizationMethod::Type
Enumeration of the types of factorization methods.
Enumerator
METHOD_LU
METHOD_LUP
           {
     METHOD_LU,  ////< LU factorization
     METHOD_LUP, ////< LU factorization with pivoting
 };
Function Documentation
passesPostChecks()
template<typename T > bool MyFactorizationMethod::passesPostChecks (const MyBLAS::Matrix< T > & L, const MyBLAS::Matrix< T > & U, const MyBLAS::Matrix< T > & P)
Function to check if the factorized matrices pass the post-checks for the factorization methods.
Template Parameters
T The data type of the matrix elements.
Parameters
A The original matrix.
L The lower triangular matrix.
U The upper triangular matrix.
P The permutation matrix.
Returns
True if the matrices pass the post-checks, false otherwise.
{
     bool passes = true;
     if (!MyBLAS::allDiagonalElementsBelowThreshold(U, 1e-20)) {
         std::cerr << "Warning: upper triangular matrix leading diagonal contains values very close to 0, matrix maybe "
                      "non-singular.\n";
         passes = false;
     }
     if (!MyBLAS::isUpperTriangularMatrix(U)) {
         std::cerr << "Error: Failed post-check: upper triangular matrix not really upper triangular.\n";
         passes = false;
     }
     if (!MyBLAS::isUnitLowerTriangularMatrix(L)) {
         std::cerr << "Error: Failed post-check: lower triangular matrix not really unit lower triangular.\n";
         passes = false;
     }
     if (!MyBLAS::isPermutationMatrix(P)) {
         std::cerr << "Error: Failed post-check: assumed permutation matrix not really a permuted.\n";
         passes = false;
     }
     return passes;
 }
References MyBLAS::allDiagonalElementsBelowThreshold(), MyBLAS::isPermutationMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), and L().
passesPreChecks()
template<typename MatrixType , typename VectorType > bool MyFactorizationMethod::passesPreChecks (const MatrixType & A, const VectorType & b)
{
     bool passes = true;
     if (MyBLAS::isEmptyMatrix(A)) {
         std::cerr << "Error: Failed pre-check: coefficient matrix is empty.\n";
         return false;
     }
     if (!MyBLAS::isSquareMatrix(A)) {
         std::cerr << "Error: Failed pre-check: coefficient matrix is non-square.\n";
         passes = false;
     }
     if (!MyBLAS::haveEqualRank(A, b)) {
         std::cerr << "Error: Failed pre-check: coefficient and constant matrix not equal rank.\n";
         passes = false;
     }
     return passes;
 }
References MyBLAS::haveEqualRank(), MyBLAS::isEmptyMatrix(), and MyBLAS::isSquareMatrix().
Referenced by Compute::usingLUP().
TypeKey()
const char* MyFactorizationMethod::TypeKey (MyFactorizationMethod::Type value)
Function to get the string representation of the factorization method type.
Parameters
value The factorization method type.
Returns
The string representation of the factorization method type.
{
     static const char *methodTypeKeys[] = {
         "LU",
         "LUP",
     };
     return methodTypeKeys[static_cast<int>(value)];
 }
Referenced by OutLab6::run(), Project2::run(), and MyLinearSolvingMethod::TypeKey().