NE591-008 C++17 Codebase: OutLab6 Class Reference
OutLab6 Class Reference
This class is a child of the Project class.
#include <outlab6.h>
Public Member Functions
OutLab6 (CommandLineArgs args)
Constructor for the outlab6 class.
void execute ()
Executes the project.
Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (OutLab6Outputs &outputs, OutLab6Inputs &inputs, boost::program_options::variables_map &values) override
This function runs the computation.
virtual void preRun (OutLab6Outputs &output, OutLab6Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (OutLab6Outputs &output, OutLab6Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
Static Protected Member Functions
static void printResults (OutLab6Outputs &results)
This function prints the results of the computation.
Private Member Functions
void initialize ()
Initializes the project.
void timedRun ()
Executes the project and measures the execution time.
Private Attributes
CommandLineArgs cmdArgs
Parser terminal
OutLab6Outputs outputs
Detailed Description
This class is a child of the Project class.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
OutLab6()
OutLab6::OutLab6 (CommandLineArgs args) inline explicit
Constructor for the outlab6 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab6::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< OutLab6Inputs, Parser, OutLab6Outputs >.
{
         Canvas canvas;
         auto x = 0.13;
         auto y = -0.66;
         auto iterations = 80;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         canvas.tone_map.growth_rate = 0.25;
         printJuliaSet<__float128>(canvas, x, y, iterations); //"o█■"
         std::cout << "Julia set at (" << x << "," << y << "), " << iterations << " iterations\n";
         return {
             .ProjectName = "NE591: OutLab 06",
             .ProjectDescription = "Solving a system of linear equations using iterative methods",
             .SubmissionDate = "10/06/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
References CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
void Project< OutLab6Inputs , Parser , OutLab6Outputs >::execute () inline inherited
Executes the project.
                    {
         initialize();
         timedRun();
     }
getTerminal()
Parser Project< OutLab6Inputs , Parser , OutLab6Outputs >::getTerminal () const inline inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
void Project< OutLab6Inputs , Parser , OutLab6Outputs >::initialize () inline private inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< OutLab6Inputs , Parser , OutLab6Outputs >::postRun (OutLab6Outputs & output, OutLab6Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< OutLab6Inputs , Parser , OutLab6Outputs >::preRun (OutLab6Outputs & output, OutLab6Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
printResults()
static void OutLab6::printResults (OutLab6Outputs & results) inline static protected
This function prints the results of the computation.
Parameters
results The results of the computation.
{
         std::cout << "\torder                     : " << (results.inputs.input.n) << std::endl;
         std::cout << "\ttotal iterations          : " << (results.solution.iterations) << std::endl;
         std::cout << "\tconverged                 : " << (results.solution.converged ? "Yes" : "No") << std::endl;
         std::cout << "\titerative error           : " << (results.solution.iterative_error) << std::endl;
         std::cout << "\trelative error            : " << (results.getSolutionError()) << std::endl;
         std::cout << "\tabsolute maximum residual : "
                   << (results.solution.getMaxResidual(results.inputs.input.coefficients,
                                                       results.inputs.input.constants))
                   << std::endl;
 //        std::cout << "\texecution time [ns]       : " << formatMeanStd(results.mean_execution_time, results.stddev_execution_time) << std::endl;
         std::cout << "\texecution time [ms]       : " << formatMeanStd(results.mean_execution_time/1.0e6, results.stddev_execution_time/1.0e6) << std::endl;
 //        std::cout << "\texecution time [s]        : " << formatMeanStd(results.mean_execution_time/1.0e9, results.stddev_execution_time/1.0e9) << std::endl;
     }
References MyLinearSolvingMethod::Input< T >::coefficients, MyLinearSolvingMethod::Input< T >::constants, formatMeanStd(), Output::getSolutionError(), Input::input, Output::inputs, Output::mean_execution_time, MyLinearSolvingMethod::Input< T >::n, Output::solution, and Output::stddev_execution_time.
Referenced by run().
run()
void OutLab6::run (OutLab6Outputs & outputs, OutLab6Inputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the computation.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
values The values used in the computation.
This section of the function handles the computation using different methods.
The methods include LUP Factorization, Point Jacobi, Gauss-Seidel, SOR, SOR Point Jacobi, and SSOR.
Implements Project< OutLab6Inputs, Parser, OutLab6Outputs >.
{
         /**
          * @brief This section of the function handles the computation using different methods.
          * @details The methods include LUP Factorization, Point Jacobi, Gauss-Seidel, SOR, SOR Point Jacobi, and SSOR.
          */
         nlohmann::json results;
         inputs.toJSON(results["inputs"]);
         if (inputs.methods.count(MyFactorizationMethod::Type::METHOD_LUP)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingLUP(runResults, inputs);
             runResults.toJSON(results["outputs"][MyFactorizationMethod::TypeKey(MyFactorizationMethod::Type::METHOD_LUP)]);
             Parser::printLine();
             std::cout << "LUP Factorization Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_POINT_JACOBI)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingPointJacobi(runResults, inputs);
             runResults.toJSON(results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_POINT_JACOBI)]);
             Parser::printLine();
             std::cout << "Point Jacobi Method Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_SORJ)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingJacobiSOR(runResults, inputs);
             runResults.toJSON(results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_SORJ)]);
             Parser::printLine();
             std::cout << "SOR Point Jacobi Method Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingGaussSeidel(runResults, inputs);
             runResults.toJSON(
                 results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_GAUSS_SEIDEL)]);
             Parser::printLine();
             std::cout << "Gauss-Seidel Method Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_SOR)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingSOR(runResults, inputs);
             runResults.toJSON(results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_SOR)]);
             Parser::printLine();
             std::cout << "SOR Method Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_SSOR)) {
             OutLab6Outputs runResults(inputs);
             Compute::usingSymmetricSOR(runResults, inputs);
             runResults.toJSON(results["outputs"][MyRelaxationMethod::TypeKey(MyRelaxationMethod::Type::METHOD_SSOR)]);
             Parser::printLine();
             std::cout << "Symmetric SOR Method Results" << std::endl;
             Parser::printLine();
             printResults(runResults);
         }
         Parser::printLine();
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References process::inputs, METHOD_GAUSS_SEIDEL, METHOD_LUP, METHOD_POINT_JACOBI, METHOD_SOR, MyRelaxationMethod::METHOD_SORJ, MyRelaxationMethod::METHOD_SSOR, CommandLine< InLab6Inputs >::printLine(), printResults(), Output::toJSON(), MyFactorizationMethod::TypeKey(), MyRelaxationMethod::TypeKey(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), Compute::usingSymmetricSOR(), and writeJSON().
timedRun()
void Project< OutLab6Inputs , Parser , OutLab6Outputs >::timedRun () inline private inherited
Executes the project and measures the execution time.
 { run(outputs, terminal.getInputs(), terminal.getArguments()); }
Field Documentation
cmdArgs
CommandLineArgs Project< OutLab6Inputs , Parser , OutLab6Outputs >::cmdArgs private inherited
outputs
OutLab6Outputs Project< OutLab6Inputs , Parser , OutLab6Outputs >::outputs private inherited
terminal
Parser Project< OutLab6Inputs , Parser , OutLab6Outputs >::terminal private inherited
The documentation for this class was generated from the following file:
src/labs/outlab6/outlab6.h