NE591-008 C++17 Codebase: OutLab12 Class Reference
OutLab12 Class Reference
This class is a child of the MPI Project class.
#include <outlab12.h>
Public Member Functions
OutLab12 (OutLab12 const &)=delete
This function is used to delete the copy constructor.
void operator= (OutLab12 const &)=delete
This function is used to delete the assignment operator.
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
OutLab12Inputs & getInputs ()
Returns the input data.
Static Public Member Functions
static OutLab12 & getInstance (CommandLineArgs args)
This function is used to get the instance of the OutLab12 class.
Protected Member Functions
OutLab12 (CommandLineArgs args)
Constructor for the outlab12 class.
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (OutLab12Outputs &outputs, OutLab12Inputs &inputs, boost::program_options::variables_map &values) override
This function is used to perform the main computation.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (OutLab12Outputs &output, OutLab12Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (OutLab12Outputs &output, OutLab12Inputs &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Static Protected Member Functions
static void printResults (OutLab12Outputs &results)
This function prints the results of the computation.
Protected Attributes
CommandLineArgs cmdArgs
Holds the command line arguments.
Parser terminal
An instance of CommandLineParserType which is used to parse command line arguments.
OutLab12Outputs _outputs
Holds the output data of the project.
Detailed Description
This class is a child of the MPI Project class.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
OutLab12() [1/2]
OutLab12::OutLab12 (OutLab12 const &) delete
This function is used to delete the copy constructor.
This function ensures that the OutLab12 class cannot be copied. This is necessary because we are following the Singleton design pattern.
Parameters
OutLab12 const& The reference to the OutLab12 object to be copied.
OutLab12() [2/2]
OutLab12::OutLab12 (CommandLineArgs args) inline explicit protected
Constructor for the outlab12 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab12::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< OutLab12Inputs, Parser, OutLab12Outputs >.
{
         Canvas canvas;
         const __float128 x = 0.13;
         const __float128 y = -0.66;
         const size_t iterations = 80;
         canvas.x_start = -0.007514104707;
         canvas.x_stop = 0.075446744304;
         canvas.y_start = 0.825578589953;
         canvas.y_stop = 0.883651184261;
         canvas.tone_map.growth_rate = 0.25;
         return {
             .ProjectName = "NE591: OutLab 12",
             .ProjectDescription = "Inverse Power Iteration Method",
             .SubmissionDate = "11/10/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = drawJuliaSet<__float128>(canvas, x, y, iterations),
         };
     }
References postprocess::iterations, CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::finalize () inline protected virtual inherited
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
getInputs()
OutLab12Inputs & Project< OutLab12Inputs , Parser , OutLab12Outputs >::getInputs () inline inherited
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
getInstance()
static OutLab12& OutLab12::getInstance (CommandLineArgs args) inline static
This function is used to get the instance of the OutLab12 class.
This function follows the Singleton design pattern. It ensures that only one instance of the OutLab12 class is created.
Parameters
args Command line arguments
Returns
Returns the instance of the OutLab12 class.
{
         static OutLab12 instance(args);
         return instance;
     }
Referenced by main().
getProfiler() [1/3]
auto Project< OutLab12Inputs , Parser , OutLab12Outputs >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< OutLab12Inputs , Parser , OutLab12Outputs >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< OutLab12Inputs , Parser , OutLab12Outputs >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< OutLab12Inputs , Parser , OutLab12Outputs >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
operator=()
void OutLab12::operator= (OutLab12 const &) delete
This function is used to delete the assignment operator.
This function ensures that the OutLab12 class cannot be assigned. This is necessary because we are following the Singleton design pattern.
Parameters
OutLab12 const& The reference to the OutLab12 object to be assigned.
postRun()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::postRun (OutLab12Outputs & output, OutLab12Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::preRun (OutLab12Outputs & output, OutLab12Inputs & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
printResults()
static void OutLab12::printResults (OutLab12Outputs & results) inline static protected
This function prints the results of the computation.
Parameters
results The results of the computation.
{
         std::cout << "\ttotal iterations          : " << (results.solution.iterations) << std::endl;
         std::cout << "\tconverged                 : " << (results.solution.converged ? "Yes" : "No") << std::endl;
         std::cout << "\titerative error           : " << (results.solution.iterative_error) << std::endl;}
References MyBLAS::Solver::Solution< T >::converged, MyBLAS::Solver::Solution< T >::iterations, MyBLAS::Solver::Solution< T >::iterative_error, and Output::solution.
run()
void OutLab12::run (OutLab12Outputs & outputs, OutLab12Inputs & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function is used to perform the main computation.
The computation is divided among the processes. Each process computes a partial sum and then the partial sums are combined using a binary tree communication logic.
Parameters
outputs The outputs of the computation.
inputs The inputs to the computation.
rank The rank of the current process.
size The total number of processes.
Returns
Returns false to indicate that the computation was successful.
Reimplemented from Project< OutLab12Inputs, Parser, OutLab12Outputs >.
{
         nlohmann::json results;
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_DIRECT_POWER_ITERATION)) {
             OutLab12Outputs dPowerIterationResults;
             Compute::usingDirectPowerIteration(dPowerIterationResults, inputs);
             dPowerIterationResults.toJSON(results["outputs"]["direct-power-iteration"]);
             Parser::printLine();
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION)) {
             OutLab12Outputs rPowerIterationResults;
             Compute::usingRayleighQuotientPowerIteration(rPowerIterationResults, inputs);
             rPowerIterationResults.toJSON(results["outputs"]["rayleigh-quotient-power-iteration"]);
             Parser::printLine();
         }
         if (inputs.methods.count(MyRelaxationMethod::Type::METHOD_INVERSE_POWER_ITERATION)) {
             OutLab12Outputs iPowerIterationResults;
             Compute::usingRayleighQuotientPowerIteration(iPowerIterationResults, inputs);
             iPowerIterationResults.toJSON(results["outputs"]["inverse-power-iteration"]);
             Parser::printLine();
         }
         inputs.toJSON(results["inputs"]);
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References process::inputs, MyRelaxationMethod::METHOD_DIRECT_POWER_ITERATION, MyRelaxationMethod::METHOD_INVERSE_POWER_ITERATION, MyRelaxationMethod::METHOD_RAYLEIGH_QUOTIENT_POWER_ITERATION, CommandLine< OutLab12Inputs >::printLine(), Output::toJSON(), Compute::usingDirectPowerIteration(), Compute::usingRayleighQuotientPowerIteration(), and writeJSON().
timedRun()
virtual void Project< OutLab12Inputs , Parser , OutLab12Outputs >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
_outputs
OutLab12Outputs Project< OutLab12Inputs , Parser , OutLab12Outputs >::_outputs protected inherited
Holds the output data of the project.
cmdArgs
CommandLineArgs Project< OutLab12Inputs , Parser , OutLab12Outputs >::cmdArgs protected inherited
Holds the command line arguments.
terminal
Parser Project< OutLab12Inputs , Parser , OutLab12Outputs >::terminal protected inherited
An instance of CommandLineParserType which is used to parse command line arguments.
The documentation for this class was generated from the following file:
src/labs/outlab12/outlab12.h