NE591-008 C++17 Codebase: Input Struct Reference
Input Struct Reference
A structure to hold the input parameters for the relaxation method.
#include <Parser.h>
Public Member Functions
Input ()=default
The default constructor for the Input struct.
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Function to serialize the Input structure.
void toJSON (nlohmann::json &jsonMap)
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
The default constructor for the Input struct.
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Function to serialize the Input structure.
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
void toJSON (nlohmann::json &jsonMap)
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
The default constructor for the Input struct.
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Function to serialize the Input structure.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Data Fields
long double x
The x value.
long double target_threshold
The target threshold.
size_t N
The maximum number of iterations.
size_t n = 0
The size of the input vector and matrix.
size_t max_iterations = 0
The maximum number of iterations to perform, 0 by default.
long double threshold = 1e-4
The stopping criterion, i.e. threshold, 1e-4 by default.
MyBLAS::Matrix< MyBLAS::NumericType > coefficients {}
The constants matrix A.
MyBLAS::Vector< MyBLAS::NumericType > constants {}
The coefficients vector b.
std::string outputJSON
The output file name in JSON format.
size_t m {}
The number of sub-intervals to divide the integration interval into.
std::vector< long double > xData
std::vector< long double > fxData
long double a = 0
The lower limit of integration.
long double b = 0
The upper limit of integration.
bool flip_integral = false
If true, the integral will be evaluated in reverse order (from b to a).
std::set< IntegrationRule > integral_types = {RULE_NONE}
A set of integration rules to be applied.
MyBLAS::Matrix< long double > LU
LU matrix.
MyBLAS::Vector< long double > constants {}
Vector of constants.
MyBLAS::Matrix< long double > coefficients {}
Coefficient matrix A.
std::set< MyRelaxationMethod::Type > methods = {}
long double k
size_t M
size_t J
std::set< MyBLAS::Solver::Type > methods = {}
MyBLAS::Solver::Parameters< long double > input
MyBLAS::Vector< long double > known_solution
std::set< SolverMethod > solver_methods = {METHOD_LUP}
long double delta = 1
long double gamma = 1
long double diffusion_coefficient = 0.0f
long double macroscopic_removal_cross_section = 0.0f
MyBLAS::Matrix< long double > sources = MyBLAS::Matrix<long double>()
MyBLAS::Solver::Parameters< MyBLAS::NumericType > solverParams
MyBLAS::Matrix< MyBLAS::NumericType > sources = MyBLAS::Matrix<MyBLAS::NumericType>()
MyPhysics::Diffusion::Params< MyBLAS::NumericType > diffusionParams
MyPhysics::Diffusion::Matrix< MyBLAS::NumericType > diffusionCoefficients
MyBLAS::Vector< MyBLAS::NumericType > diffusionConstants
std::string fluxOutputDirectory
size_t numRuns
long double timeout
Friends
std::ostream & operator<< (std::ostream &os, const Input &input)
Overloaded stream insertion operator for the Input structure.
std::ostream & operator<< (std::ostream &os, const Input &input)
Overloaded stream insertion operator for the Input structure.
std::ostream & operator<< (std::ostream &os, const Input &input)
Overloaded stream insertion operator for the Input structure.
Detailed Description
A structure to hold the input parameters for the relaxation method.
Struct representing the input matrices for the BLAS library.
A structure to hold the input parameters.
Struct representing the input parameters for the Newton-Cotes integration methods.
This structure contains a size_t variable 'n' and a string 'outputJSON'.
This structure contains the convergence threshold, maximum number of iterations, size of the matrices, coefficient matrix, vector of constants, and the set of methods.
Parameters
k A long double representing the scalar multiplier for [A].
M A size_t representing the row rank for [A] and [B].
N A size_t representing the column rank for [B] and row rank for [F].
J A size_t representing the column rank for [F].
Constructor & Destructor Documentation
Input() [1/12]
Input::Input () default
The default constructor for the Input struct.
Input() [2/12]
Input::Input () default
Input() [3/12]
Input::Input () default
Input() [4/12]
Input::Input () default
The default constructor for the Input struct.
Input() [5/12]
Input::Input () default
Input() [6/12]
Input::Input () default
Input() [7/12]
Input::Input () default
The default constructor for the Input struct.
Input() [8/12]
Input::Input () default
Input() [9/12]
Input::Input () default
Input() [10/12]
Input::Input () default
Input() [11/12]
Input::Input () default
Input() [12/12]
Input::Input () default
Member Function Documentation
serialize() [1/3]
template<class Archive > void Input::serialize (Archive & ar, const unsigned int version) inline
Function to serialize the Input structure.
This function uses the Boost library to serialize the Input structure, allowing it to be saved to a file or sent over a network.
Parameters
ar The archive where the serialized data will be stored.
version The version of the serialization library.
{
         ar & BOOST_SERIALIZATION_NVP(threshold);
         ar & BOOST_SERIALIZATION_NVP(max_iterations);
         ar & BOOST_SERIALIZATION_NVP(coefficients.getData());
         ar & BOOST_SERIALIZATION_NVP(constants.getData());
     }
References coefficients, constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), max_iterations, and threshold.
serialize() [2/3]
template<class Archive > void Input::serialize (Archive & ar, const unsigned int version) inline
Function to serialize the Input structure.
This function uses the Boost library to serialize the Input structure, allowing it to be saved to a file or sent over a network.
Parameters
ar The archive where the serialized data will be stored.
version The version of the serialization library.
{
         ar & BOOST_SERIALIZATION_NVP(n);
     }
References n.
serialize() [3/3]
template<class Archive > void Input::serialize (Archive & ar, const unsigned int version) inline
Function to serialize the Input structure.
This function uses the Boost library to serialize the Input structure, allowing it to be saved to a file or sent over a network.
Parameters
ar The archive where the serialized data will be stored.
version The version of the serialization library.
{
         ar & BOOST_SERIALIZATION_NVP(n);
     }
References n.
toJSON() [1/15]
void Input::toJSON (nlohmann::json & jsonMap) inline
{
         jsonMap["a"] = a;
         jsonMap["b"] = b;
         jsonMap["m"] = m;
         jsonMap["rules"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(integral_types.begin(), integral_types.end(), std::back_inserter(result),
                            [](IntegrationRule rule) { return ruleKey(rule); });
             return result;
         }();
     }
References a, b, integral_types, and m.
toJSON() [2/15]
void Input::toJSON (nlohmann::json & jsonMap) inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["a"] = a;
         jsonMap["b"] = b;
         jsonMap["m"] = m;
         jsonMap["rules"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(integral_types.begin(), integral_types.end(), std::back_inserter(result),
                            [](IntegrationRule rule) { return ruleKey(rule); });
             return result;
         }();
         if (integral_types.count(RULE_GAUSSIAN_QUADRATURE)) {
             jsonMap["n"] = n;
         }
     }
References a, b, integral_types, m, n, and RULE_GAUSSIAN_QUADRATURE.
toJSON() [3/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["n"] = n;
         jsonMap["stopping-criterion"] = threshold;
         jsonMap["max-iterations"] = max_iterations;
         jsonMap["coefficients"] = coefficients.getData();
         jsonMap["constants"] = constants.getData();
     }
References coefficients, constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), max_iterations, n, and threshold.
toJSON() [4/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["n"] = n;
         jsonMap["LU"] = LU.getData();
         jsonMap["constants"] = constants.getData();
     }
References constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), LU, and n.
toJSON() [5/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["threshold"] = threshold;
         jsonMap["order"] = n;
         jsonMap["max-iterations"] = max_iterations;
         jsonMap["coefficients"] = coefficients.getData();
         jsonMap["constants"] = constants.getData();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyRelaxationMethod::Type method) { return MyRelaxationMethod::TypeKey(method); });
             return result;
         }();
     }
References coefficients, constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), max_iterations, methods, n, and threshold.
toJSON() [6/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["n"] = n;
     }
References n.
toJSON() [7/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["threshold"] = input.threshold;
         jsonMap["order"] = input.n;
         jsonMap["max-iterations"] = input.max_iterations;
         jsonMap["coefficients"] = input.coefficients.getData();
         jsonMap["constants"] = input.constants.getData();
         jsonMap["known-solution"] = known_solution.getData();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, MyBLAS::Vector< T >::getData(), input, known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, methods, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::threshold.
toJSON() [8/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["n"] = n;
         jsonMap["coefficients"] = coefficients.getData();
         jsonMap["constants"] = constants.getData();
     }
References coefficients, constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), and n.
toJSON() [9/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["threshold"] = input.threshold;
         jsonMap["order"] = input.n;
         jsonMap["max-iterations"] = input.max_iterations;
         jsonMap["coefficients"] = input.coefficients.getData();
         jsonMap["constants"] = input.constants.getData();
         jsonMap["known-solution"] = known_solution.getData();
         jsonMap["relaxation-factor"] = input.relaxation_factor;
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::coefficients, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::constants, MyBLAS::Vector< T >::getData(), input, known_solution, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::max_iterations, methods, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::n, MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::relaxation_factor, and MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::threshold.
toJSON() [10/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap The JSON object to which the input parameters are added.
{
         jsonMap["n"] = n;
     }
References n.
toJSON() [11/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["D"] = diffusion_coefficient;
         jsonMap["cross-section"] = macroscopic_removal_cross_section;
         jsonMap["dimensions"]["a"] = a;
         jsonMap["dimensions"]["b"] = b;
         jsonMap["mesh"]["m"] = m;
         jsonMap["mesh"]["n"] = n;
         jsonMap["mesh"][""] = delta;
         jsonMap["mesh"][""] = gamma;
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(solver_methods.begin(), solver_methods.end(), std::back_inserter(result),
                            [](SolverMethod method) { return methodKey(method); });
             return result;
         }();
     }
References a, b, delta, diffusion_coefficient, gamma, m, macroscopic_removal_cross_section, n, and solver_methods.
toJSON() [12/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["D"] = diffusionParams.getDiffusionCoefficient();
         jsonMap["cross-section"] = diffusionParams.getMacroscopicRemovalCrossSection();
         jsonMap["dimensions"]["a"] = diffusionParams.getA();
         jsonMap["dimensions"]["b"] = diffusionParams.getB();
         jsonMap["mesh"]["m"] = diffusionParams.getM();
         jsonMap["mesh"]["n"] = diffusionParams.getN();
         jsonMap["mesh"][""] = diffusionParams.getDelta();
         jsonMap["mesh"][""] = diffusionParams.getGamma();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References diffusionParams, MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::getN(), and methods.
toJSON() [13/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["D"] = diffusionParams.getDiffusionCoefficient();
         jsonMap["cross-section"] = diffusionParams.getMacroscopicRemovalCrossSection();
         jsonMap["dimensions"]["a"] = diffusionParams.getA();
         jsonMap["dimensions"]["b"] = diffusionParams.getB();
         jsonMap["mesh"]["m"] = diffusionParams.getM();
         jsonMap["mesh"]["n"] = diffusionParams.getN();
         jsonMap["mesh"][""] = diffusionParams.getDelta();
         jsonMap["mesh"][""] = diffusionParams.getGamma();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References diffusionParams, MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::getN(), and methods.
toJSON() [14/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["D"] = diffusionParams.getDiffusionCoefficient();
         jsonMap["cross-section"] = diffusionParams.getMacroscopicRemovalCrossSection();
         jsonMap["dimensions"]["a"] = diffusionParams.getA();
         jsonMap["dimensions"]["b"] = diffusionParams.getB();
         jsonMap["mesh"]["m"] = diffusionParams.getM();
         jsonMap["mesh"]["n"] = diffusionParams.getN();
         jsonMap["mesh"][""] = diffusionParams.getDelta();
         jsonMap["mesh"][""] = diffusionParams.getGamma();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References diffusionParams, MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::getN(), and methods.
toJSON() [15/15]
void Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["D"] = diffusionParams.getDiffusionCoefficient();
         jsonMap["cross-section"] = diffusionParams.getMacroscopicRemovalCrossSection();
         jsonMap["dimensions"]["a"] = diffusionParams.getA();
         jsonMap["dimensions"]["b"] = diffusionParams.getB();
         jsonMap["mesh"]["m"] = diffusionParams.getM();
         jsonMap["mesh"]["n"] = diffusionParams.getN();
         jsonMap["mesh"][""] = diffusionParams.getDelta();
         jsonMap["mesh"][""] = diffusionParams.getGamma();
         jsonMap["methods"] = [this]() -> std::vector<std::string> {
             std::vector<std::string> result;
             std::transform(methods.begin(), methods.end(), std::back_inserter(result),
                            [](MyBLAS::Solver::Type method) { return MyBLAS::Solver::TypeKey(method); });
             return result;
         }();
     }
References diffusionParams, MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::getN(), and methods.
Friends And Related Function Documentation
operator<< [1/3]
std::ostream& operator<< (std::ostream & os, const Input & input) friend
Overloaded stream insertion operator for the Input structure.
This function allows the Input structure to be outputted to an ostream object in a formatted manner.
Parameters
os The ostream object where the Input structure will be outputted.
input The Input structure that will be outputted.
Returns
The ostream object with the Input structure outputted to it.
{
         os << "n: " << input.n
            << "k: " << input.max_iterations
            << "e: " << input.threshold
            << ", outputJSON: " << input.outputJSON;
         return os;
     }
operator<< [2/3]
std::ostream& operator<< (std::ostream & os, const Input & input) friend
Overloaded stream insertion operator for the Input structure.
This function allows the Input structure to be outputted to an ostream object in a formatted manner.
Parameters
os The ostream object where the Input structure will be outputted.
input The Input structure that will be outputted.
Returns
The ostream object with the Input structure outputted to it.
{
         os << "n: " << input.n<< ", outputJSON: " << input.outputJSON;
         return os;
     }
operator<< [3/3]
std::ostream& operator<< (std::ostream & os, const Input & input) friend
Overloaded stream insertion operator for the Input structure.
This function allows the Input structure to be outputted to an ostream object in a formatted manner.
Parameters
os The ostream object where the Input structure will be outputted.
input The Input structure that will be outputted.
Returns
The ostream object with the Input structure outputted to it.
{
         os << "n: " << input.n<< ", outputJSON: " << input.outputJSON;
         return os;
     }
Field Documentation
a
long double Input::a = 0
The lower limit of integration.
Referenced by toJSON().
b
long double Input::b = 0
The upper limit of integration.
Referenced by toJSON().
coefficients [1/2]
MyBLAS::Matrix< long double > Input::coefficients {}
The constants matrix A.
LU matrix.
Referenced by Parser::buildInputs(), Output::getMaxResidual(), serialize(), and toJSON().
coefficients [2/2]
MyBLAS::Matrix<long double> Input::coefficients {}
Coefficient matrix A.
LU matrix.
constants [1/2]
MyBLAS::Vector< long double > Input::constants {}
The coefficients vector b.
Vector of constants.
Vector of constants b.
Referenced by Parser::buildInputs(), Output::getMaxResidual(), serialize(), and toJSON().
constants [2/2]
MyBLAS::Vector<long double> Input::constants {}
Vector of constants.
Vector of constants b.
delta
long double Input::delta = 1
Referenced by toJSON().
diffusion_coefficient
long double Input::diffusion_coefficient = 0.0f
Referenced by toJSON().
diffusionCoefficients
MyPhysics::Diffusion::Matrix< MyBLAS::NumericType > Input::diffusionCoefficients
diffusionConstants
MyBLAS::Vector< MyBLAS::NumericType > Input::diffusionConstants
diffusionParams
MyPhysics::Diffusion::Params< MyBLAS::NumericType > Input::diffusionParams
Referenced by toJSON().
flip_integral
bool Input::flip_integral = false
If true, the integral will be evaluated in reverse order (from b to a).
fluxOutputDirectory
std::string Input::fluxOutputDirectory
fxData
std::vector< long double > Input::fxData
Referenced by Parser::buildInputs().
gamma
long double Input::gamma = 1
Referenced by toJSON().
input
MyBLAS::Solver::Parameters< long double > Input::input
Referenced by Parser::buildInputs(), OutLab6::printResults(), toJSON(), and Output::toJSON().
integral_types
std::set< IntegrationRule > Input::integral_types = {RULE_NONE}
A set of integration rules to be applied.
Referenced by toJSON().
J
size_t Input::J
Referenced by Parser::buildInputs(), and OutLab1::run().
k
long double Input::k
Referenced by Parser::buildInputs(), and elementFromD().
known_solution
MyBLAS::Vector< long double > Input::known_solution
Referenced by Parser::buildInputs(), Output::getSolutionError(), and toJSON().
LU
MyBLAS::Matrix<long double> Input::LU
LU matrix.
Referenced by toJSON().
m
size_t Input::m {}
The number of sub-intervals to divide the integration interval into.
Referenced by Parser::buildInputs(), and toJSON().
M
size_t Input::M
Referenced by Parser::buildInputs(), and OutLab1::run().
macroscopic_removal_cross_section
long double Input::macroscopic_removal_cross_section = 0.0f
Referenced by toJSON().
max_iterations
size_t Input::max_iterations = 0
The maximum number of iterations to perform, 0 by default.
Referenced by Parser::buildInputs(), serialize(), toJSON(), and Output::toJSON().
methods [1/2]
std::set< MyBLAS::Solver::Type > Input::methods = {}
Referenced by Parser::buildInputs(), and toJSON().
methods [2/2]
std::set<MyBLAS::Solver::Type> Input::methods = {}
N
size_t Input::N
The maximum number of iterations.
Referenced by Parser::buildInputs(), elementFromE(), OutLab1::run(), and InLab1::run().
n
size_t Input::n = 0
The size of the input vector and matrix.
The number of quadrature points if Gauss-Legendre Quadrature will be used.
The number of iterations for the relaxation method.
Size of the matrices.
This variable is initialized to 1 by default.
Referenced by Parser::buildInputs(), serialize(), and toJSON().
numRuns
size_t Input::numRuns
outputJSON
std::string Input::outputJSON
The output file name in JSON format.
This string variable holds the name of the output file where the results will be stored in JSON format.
Referenced by Parser::buildInputs().
solver_methods
std::set<SolverMethod> Input::solver_methods = {METHOD_LUP}
Referenced by toJSON().
solverParams
MyBLAS::Solver::Parameters< MyBLAS::NumericType > Input::solverParams
Referenced by Project2::printResults(), Project3::printResults(), Project4::printResults(), Project5::printResults(), and Output::toJSON().
sources [1/2]
MyBLAS::Matrix< MyBLAS::NumericType > Input::sources = MyBLAS::Matrix<long double>()
sources [2/2]
MyBLAS::Matrix<MyBLAS::NumericType> Input::sources = MyBLAS::Matrix<MyBLAS::NumericType>()
target_threshold
long double Input::target_threshold
The target threshold.
Referenced by Parser::buildInputs(), and InLab1::run().
threshold
long double Input::threshold = 1e-4
The stopping criterion, i.e. threshold, 1e-4 by default.
Referenced by Parser::buildInputs(), serialize(), toJSON(), and Output::toJSON().
timeout
long double Input::timeout
x
long double Input::x
The x value.
Referenced by Parser::buildInputs(), and InLab1::run().
xData
std::vector< long double > Input::xData
Referenced by Parser::buildInputs().
The documentation for this struct was generated from the following files:
src/labs/inlab1/Parser.h
src/labs/inlab10/InputsOutputs.h