NE591-008 C++17 Codebase: src/labs/outlab2/analysis/plot_points.m File Reference
plot_points.m File Reference
Functions
set (gca, 'Fontsize', [18])
set (gca, 'FontName', 'cmr12')
set (gca, "TickLabelInterpreter", "latex")
set (gca, 'Xscale', xscale)
grid on grid minor box on Plot f (x) as a smooth line plot(xi
grid on grid minor box on Plot Plot L (x) as points with E(x) as the error bars errorbar(xi
scatter (xi, L_xi, 50, 'red')
fourth derivative of e x is e x for (i=0;i<=n;i++) % Define the nodes x_nodes
linspace (-1, 1, m)
plot (xi, L_xi+error_bound, '--')
plot (xi, L_xi - error_bound, '--')
disp (['The estimated error bound for the Lagrange interpolation is ', num2str(error_bound)])
Add labels and title xlabel (' $x_i$', 'Interpreter', 'latex')
ylabel (' $f(x_i)$, $L(x_i)$', 'Interpreter', 'latex')
Set the title title (title_str, 'Interpreter', 'latex')
title ('n, m, $f(x)=e^{x}$', 'Interpreter', 'latex')
Add a legend legend (' $f(x_i)$', ' $E(x_i)=|L(x_i) -f(x_i)|$', ' $L(x_i)$', error_str, 'Interpreter', 'latex', 'Location', 'northwest')
pos (3)
pos (4)
set (gcf, 'Position', pos) % title(strcat('Figure '
int2str (fig_count)))
print (gcf, strcat('F', strcat(int2str(n), '.png')),'-dpng','-r600')
Variables
function [F] = plot_points(n, m, x, xi, L_xi, f_xi, E_xi) F = figure
hold on
grid on grid minor box on Plot f_xi
grid on grid minor box on Plot LineWidth
grid on grid minor box on Plot Plot L_xi
grid on grid minor box on Plot Plot E_xi
grid on grid minor box on Plot Plot Color
grid on grid minor box on Plot Plot k
Define the function f = @(x) exp(x)
Define the x values x = linspace(-1, 1, m)
Calculate the function values y = f(x)
Calculate the nth derivative for i
df = @(x) exp(x)
derivative of e x is e x ddf = @(x) exp(x)
second derivative of e x is e x dddf = @(x) exp(x)
third derivative of e x is e x ddddf = @(x) exp(x)
change this to your actual nodes Compute the maximum of the fourth derivative in the interval[-1, 1] z
max_ddddf = max(y)
Compute the product term product_term = prod(repmat(z', 1, length(x_nodes)) - repmat(x_nodes, length(z), 1), 2)
Compute the error bound error_bound = abs(max_ddddf / factorial(n)) * max(abs(product_term))
Create the title title_str = ['n = ', num2str(n), ', m = ',num2str(m),', $f(x) = e^{x}$']
error_str = ['Error Bound = ', num2str(error_bound)]
pos = get(gcf, 'Position')
Hold off the plot hold off
Function Documentation
disp()
disp ()
f()
grid on grid minor box on Plot f (x)
for()
fourth derivative of e x is e x for (i = 0;i<=n;i++)
int2str()
int2str (fig_count)
L()
grid on grid minor box on Plot Plot L (x)
Referenced by InLab04::doForwardSubstitution(), MyBLAS::LU::doolittleFactorize(), MyBLAS::doolittleFactorizeLU(), MyBLAS::LUP::dooLittleFactorizeLUP(), dooLittleFactorizeLUP(), MyBLAS::LUP::factorize(), MyBLAS::LU::factorize(), MyBLAS::factorizeLU(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), factorizeLUwithPartialPivoting(), MyBLAS::forwardSubstitution(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isValidUnitLowerTriangularMatrix(), MyFactorizationMethod::passesPostChecks(), MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), MyBLAS::LU::recursiveLUFactorize(), OutLab4::run(), OutLab5::run(), and TEST_P().
legend()
Add a legend legend (' $f(x_i)$' , ' $ Ex_i = |L(x_i) -f(x_i)|$', ' $L(x_i)$' , error_str , 'Interpreter' , 'latex' , 'Location' , 'northwest')
linspace()
linspace (- 1, 1 , m)
plot() [1/2]
plot (xi , L_xi - error_bound, '--')
plot() [2/2]
plot (xi , L_xi+ error_bound, '--')
pos() [1/2]
pos (3)
pos() [2/2]
pos (4)
print()
print (gcf , strcat('F', strcat(int2str(n), '.png')) , '-dpng' , '-r600')
scatter()
scatter (xi , L_xi , 50 , 'red')
set() [1/5]
set (gca , "TickLabelInterpreter" , "latex")
set() [2/5]
set (gca , 'FontName' , 'cmr12')
set() [3/5]
set (gca , 'Fontsize')
set() [4/5]
set (gca , 'Xscale' , xscale)
set() [5/5]
set (gcf , 'Position' , pos)
References n.
title() [1/2]
title (' n, m , $ fx = e^{x}$', 'Interpreter' , 'latex')
References x.
title() [2/2]
Set the title title (title_str , 'Interpreter' , 'latex')
xlabel()
Add labels and title xlabel (' $x_i$' , 'Interpreter' , 'latex')
ylabel()
ylabel (' $f(x_i) $, $L(x_i)$', 'Interpreter' , 'latex')
Variable Documentation
Color
grid on grid minor box on Plot Plot Color
ddddf
third derivative of e x is e x ddddf = @(x) exp(x)
dddf
second derivative of e x is e x dddf = @(x) exp(x)
ddf
derivative of e x is e x ddf = @(x) exp(x)
df
df = @(x) exp(x)
Referenced by getGaussLegendreNode(), and RootFinder::usingNewtonRaphson().
E_xi
grid on grid minor box on Plot Plot E_xi
error_bound
Compute the error bound error_bound = abs(max_ddddf / factorial(n)) * max(abs(product_term))
error_str
error_str = ['Error Bound = ', num2str(error_bound)]
f
adjust the x values end Define the function and its derivatives f = @(x) exp(x)
Referenced by getGaussLegendreNode(), and RootFinder::usingNewtonRaphson().
f_xi
grid on grid minor box on Plot f_xi
function
function[F] = plot_points(n, m, x, xi, L_xi, f_xi, E_xi) F = figure
Referenced by getGaussLegendreNode(), Parser::performInputArgumentsCheck(), and ProfilerHelper::validateOptions().
i
Calculate the nth derivative for i
Initial value:
= 1:n
    y = diff(y) ./ diff(x)
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Referenced by MyBLAS::Stats::abs(), MyBLAS::abs(), MyBLAS::AbsoluteMaxResidual(), MyBLAS::allDiagonalElementsBelowThreshold(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyBLAS::backwardSubstitution(), MyBLAS::LU::doolittleFactorize(), MyBLAS::doolittleFactorizeLU(), MyBLAS::LUP::dooLittleFactorizeLUP(), dooLittleFactorizeLUP(), MyBLAS::Vector< T >::elementwiseProduct(), MyBLAS::Matrix< T >::eye(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), factorizeLUwithPartialPivoting(), fill_fluxes(), Compute::fill_fluxes(), fillGaussLegendreNodes(), fillLagrangePolys(), fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), MyPhysics::Diffusion::Matrix< T >::generate(), getGrays256bitANSI(), getHSV256bitANSI(), MPIProject< InputType, CommandLineParserType, OutputType >::getInputs(), MyBLAS::isBinaryMatrix(), MyBLAS::isBinaryVector(), MyBLAS::isDiagonallyDominant(), MyBLAS::isPermutationMatrix(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::isSymmetricMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), MyBLAS::isValidUnitLowerTriangularMatrix(), MyBLAS::isValidUpperTriangularMatrix(), MyBLAS::isZeroVector(), MyBLAS::L2(), MyBLAS::LazyMatrix< DataType >::LazyMatrix(), MyBLAS::LazyVector< DataType >::LazyVector(), MyBLAS::makePositiveDefinite(), MyBLAS::ElementwiseExpression< DataType, ContainerType1, ContainerType2, BinaryOp >::matrix(), MyBLAS::Matrix< T >::Matrix(), MyPhysics::Diffusion::Matrix< T >::Matrix(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::multiplyMatrixMatrixType1(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::multiplyMatrixMatrixType2(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::multiplyMatrixVector(), MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), naive_fill_diffusion_matrix_and_vector(), Compute::naive_fill_diffusion_vector(), MyBLAS::norm(), MyBLAS::ElementwiseExpression< DataType, ContainerType1, ContainerType2, BinaryOp >::operator()(), MatrixVectorExpression< MatrixType, VectorType, T >::operator()(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::operator()(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Vector< T >::operator*(), MyBLAS::LazyMatrix< DataType >::operator*(), MyBLAS::LazyVector< DataType >::operator*(), MyBLAS::LazyVector< DataType >::operator*=(), MyBLAS::LazyMatrix< DataType >::operator*=(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Vector< T >::operator+(), MyBLAS::LazyMatrix< DataType >::operator+(), MyBLAS::LazyVector< DataType >::operator+(), MyBLAS::LazyMatrix< DataType >::operator+=(), MyBLAS::LazyVector< DataType >::operator+=(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Vector< T >::operator-(), MyBLAS::LazyMatrix< DataType >::operator-(), MyBLAS::LazyVector< DataType >::operator-(), MyBLAS::LazyMatrix< DataType >::operator-=(), MyBLAS::LazyVector< DataType >::operator-=(), MyBLAS::Matrix< T >::operator/(), MyBLAS::Vector< T >::operator/(), MyBLAS::LazyMatrix< DataType >::operator/(), MyBLAS::LazyVector< DataType >::operator/(), MyBLAS::Vector< T >::operator/=(), MyBLAS::LazyVector< DataType >::operator/=(), MyBLAS::LazyMatrix< DataType >::operator/=(), MyPhysics::Diffusion::Matrix< T >::operator=(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Vector< T >::operator==(), MyBLAS::VectorExpression< DataType, Op1, Op2, BinaryOp >::operator[](), Parser::printInputArguments(), InLab4::printMandelbrotSet(), MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), Project1::run(), InLab1::run(), Profiler< FunctionType >::runNoTimeout(), Profiler< FunctionType >::runWithTimeout(), Compute::seriesSum(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), MyBLAS::TEST_F(), Outputs::toJSON(), TYPED_TEST(), MyBLAS::TYPED_TEST(), MyBLAS::ElementwiseExpression< DataType, ContainerType1, ContainerType2, BinaryOp >::vector(), MyBLAS::Vector< T >::Vector(), writeCSV(), and writeCSVMatrixNoHeaders().
k
grid on grid minor box on Plot Plot k
Referenced by MyBLAS::LU::doolittleFactorize(), MyBLAS::doolittleFactorizeLU(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), factorizeLUwithPartialPivoting(), fillLagrangePolys(), getLagrangePoly(), MyBLAS::isPositiveDefiniteMatrix(), MyBLAS::makePositiveDefinite(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::multiplyMatrixMatrixType1(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::multiplyMatrixMatrixType2(), MyBLAS::ContainerExpression< ContainerType1, ContainerType2, T >::operator()(), MyBLAS::Matrix< T >::operator*(), Parser::printInputArguments(), and MyBLAS::TYPED_TEST().
L_xi
grid on grid minor box on Plot Plot L_xi
LineWidth
grid on grid minor box on Plot Plot LineWidth
max_ddddf
max_ddddf = max(y)
off
Hold off the plot hold off
on
hold on
pos
pos = get(gcf, 'Position')
product_term
Compute the product term product_term = prod(repmat(z', 1, length(x_nodes)) - repmat(x_nodes, length(z), 1), 2)
title_str
Create the title title_str = ['n = ', num2str(n), ', m = ',num2str(m),', $f(x) = e^{x}$']
x
x = linspace(-1, 1, m)
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Referenced by MyMath::abs(), MyRelaxationMethod::applyConjugateGradient(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyBLAS::LUP::applyLUP(), MyBLAS::backwardSubstitution(), OutLab7::buildHeaderInfo(), InLab10::buildHeaderInfo(), InLab11::buildHeaderInfo(), InLab12::buildHeaderInfo(), InLab5::buildHeaderInfo(), InLab6::buildHeaderInfo(), OutLab10::buildHeaderInfo(), OutLab11::buildHeaderInfo(), OutLab12::buildHeaderInfo(), OutLab4::buildHeaderInfo(), OutLab5::buildHeaderInfo(), OutLab6::buildHeaderInfo(), Project1::buildHeaderInfo(), Project2::buildHeaderInfo(), Project3::buildHeaderInfo(), Project4::buildHeaderInfo(), Project5::buildHeaderInfo(), MyBLAS::System::Circuit(), fill_fx(), fillInterpolationError(), fillLagrangePolys(), getGaussLegendreNode(), getGrays256bitANSI(), getLagrangePoly(), MyBLAS::Solver::Solution< T >::getResidual(), my_naive_sin(), Parser::performInputArgumentsCheck(), Parser::printInputArguments(), printJuliaSet(), InLab4::printMandelbrotSet(), InLab5::run(), OutLab4::run(), InLab4::run(), OutLab5::run(), title(), MyBLAS::Solver::Solution< T >::toJSON(), user_defined_fx(), RootFinder::usingNewtonRaphson(), and MyBLAS::Stats::variance().
y
Calculate the function values y = f(x)
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), MyBLAS::LUP::applyLUP(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyBLAS::backwardSubstitution(), OutLab7::buildHeaderInfo(), InLab10::buildHeaderInfo(), InLab11::buildHeaderInfo(), InLab12::buildHeaderInfo(), InLab5::buildHeaderInfo(), InLab6::buildHeaderInfo(), OutLab10::buildHeaderInfo(), OutLab11::buildHeaderInfo(), OutLab12::buildHeaderInfo(), OutLab4::buildHeaderInfo(), OutLab5::buildHeaderInfo(), OutLab6::buildHeaderInfo(), Project1::buildHeaderInfo(), Project2::buildHeaderInfo(), Project3::buildHeaderInfo(), Project4::buildHeaderInfo(), Project5::buildHeaderInfo(), InLab04::doBackwardSubstitution(), fillInterpolationError(), MyBLAS::forwardSubstitution(), getGrays256bitANSI(), MyBLAS::matrixWeightedInnerProduct(), printJuliaSet(), InLab4::printMandelbrotSet(), InLab10::run(), InLab5::run(), OutLab4::run(), InLab4::run(), OutLab5::run(), Project1::run(), and TYPED_TEST().
z
change this to your actual nodes Compute the maximum of the fourth derivative in the interval [-1, 1] z
Initial value:
=
    xi'
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Referenced by MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), juliaSetIterations(), MyBLAS::matrixWeightedInnerProduct(), printJuliaSet(), InLab10::run(), and TYPED_TEST().