NE591-008 C++17 Codebase: MyPhysics::Diffusion::Matrix< T > Class Template Reference
MyPhysics::Diffusion::Matrix< T > Class Template Reference
This class represents a diffusion matrix. It extends the MyBLAS::LazyMatrix class.
#include <DiffusionMatrix.h>
Public Types
using Generator = std::function< T(size_t, size_t)>
A function that generates a matrix element given its row and column indices.
Public Member Functions
Matrix ()=default
Default constructor.
Matrix (const Params< T > params)
Constructor that takes diffusion parameters.
Matrix (const Matrix< T > &matrix)
Copy constructor.
Matrix & operator= (const Matrix &other)
Copy assignment operator.
Matrix (const Params< T > &params, Generator generator)
Constructor that takes diffusion parameters and a generator function.
const Params< T > & getParams () const
Returns the diffusion parameters.
const Constants< T > & getConstants () const
Returns the diffusion constants.
size_t getRows () const
Returns the number of rows in the matrix.
size_t getCols () const
Returns the number of columns in the matrix.
virtual T operator() (size_t row, size_t col) const
Computes and returns the value at the specified row and column.
LazyMatrix operator* (T scalar) const
LazyMatrix operator+ (T scalar) const
LazyMatrix operator- (T scalar) const
LazyMatrix operator- () const
LazyMatrix operator/ (T scalar) const
LazyMatrix & operator+= (LazyMatrix const &b)
LazyMatrix & operator+= (T scalar)
LazyMatrix & operator-= (LazyMatrix const &b)
LazyMatrix & operator-= (T scalar)
LazyMatrix & operator*= (LazyMatrix const &b)
LazyMatrix & operator*= (T scalar)
LazyMatrix & operator/= (LazyMatrix const &b)
LazyMatrix & operator/= (T scalar)
Proxy operator[] (size_t row)
ConstProxy operator[] (size_t row) const
Static Public Member Functions
static T generate (size_t idx, size_t idy, const Constants< T > &c)
Generates a matrix element.
Protected Member Functions
void setRows (size_t rows)
void setCols (size_t cols)
void setGenerator (const Generator &generator)
Private Attributes
Params< T > _params {}
The parameters of the diffusion process.
size_t _size = 0
The size of the matrix.
Constants< T > _constants {}
The constants used in the diffusion process.
size_t rows_
size_t cols_
Generator generator_
Detailed Description
template<typename T>
class MyPhysics::Diffusion::Matrix< T >
This class represents a diffusion matrix. It extends the MyBLAS::LazyMatrix class.
Template Parameters
T The type of the elements in the matrix.
Member Typedef Documentation
Generator
template<typename T > MyPhysics::Diffusion::Matrix< T >::Generator
A function that generates a matrix element given its row and column indices.
Constructor & Destructor Documentation
Matrix() [1/4]
template<typename T > MyPhysics::Diffusion::Matrix< T >::Matrix () explicit default
Default constructor.
Matrix() [2/4]
template<typename T > MyPhysics::Diffusion::Matrix< T >::Matrix (const Params< T > params) inline explicit
Constructor that takes diffusion parameters.
Parameters
params The diffusion parameters.
                                            : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator([this](size_t i, size_t j) {
             return generate(i, j, _constants);
         });
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getN(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Matrix() [3/4]
template<typename T > MyPhysics::Diffusion::Matrix< T >::Matrix (const Matrix< T > & matrix) inline
Copy constructor.
Parameters
matrix The matrix to copy.
                                    : MyBLAS::LazyMatrix<T>(matrix), _params(matrix._params), _constants(Constants<T>::compute(matrix._params)) {
         _size = matrix._size;
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator([this](size_t i, size_t j) {
             return generate(i, j, _constants);
         });
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Matrix() [4/4]
template<typename T > MyPhysics::Diffusion::Matrix< T >::Matrix (const Params< T > & params, Generator generator) inline
Constructor that takes diffusion parameters and a generator function.
Parameters
params The diffusion parameters.
generator The generator function.
                                                         : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator(generator);
     }
References MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getN(), MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Member Function Documentation
generate()
template<typename T > static T MyPhysics::Diffusion::Matrix< T >::generate (size_t idx, size_t idy, const Constants< T > & c) inline static
Generates a matrix element.
Parameters
idx The row index.
idy The column index.
c The diffusion constants.
Returns
The generated matrix element.
{
         if (idx == idy) {
             return c.diagonal;
         }
         const size_t i = (idx / c.n), p = (idy / c.n);
         if ((i == p) && (idx == idy + 1 || idx == idy - 1)) {
             return c.minus_D_over_gamma_squared;
         }
         const size_t j = (idx % c.n), q = (idy % c.n);
         if ((j == q) && (idx == idy + c.n || idx == idy - c.n)) {
             return c.minus_D_over_delta_squared;
         }
         return 0;
     }
References MyPhysics::Diffusion::Constants< T >::diagonal, i, MyPhysics::Diffusion::Constants< T >::minus_D_over_delta_squared, MyPhysics::Diffusion::Constants< T >::minus_D_over_gamma_squared, MyPhysics::Diffusion::Constants< T >::n, and generate_source_multi_lobe::q.
Referenced by MyPhysics::Diffusion::Matrix< T >::Matrix(), and MyPhysics::Diffusion::Matrix< T >::operator=().
getCols()
template<typename T > size_t MyPhysics::Diffusion::Matrix< T >::getCols () const inline virtual
Returns the number of columns in the matrix.
Returns
The number of columns in the matrix.
Reimplemented from MyBLAS::LazyMatrix< T >.
{
         return _size;
     }
References MyPhysics::Diffusion::Matrix< T >::_size.
Referenced by TYPED_TEST().
getConstants()
template<typename T > const Constants<T>& MyPhysics::Diffusion::Matrix< T >::getConstants () const inline
Returns the diffusion constants.
Returns
The diffusion constants.
 { return _constants; }
References MyPhysics::Diffusion::Matrix< T >::_constants.
getParams()
template<typename T > const Params<T>& MyPhysics::Diffusion::Matrix< T >::getParams () const inline
Returns the diffusion parameters.
Returns
The diffusion parameters.
 { return _params; }
References MyPhysics::Diffusion::Matrix< T >::_params.
Referenced by TYPED_TEST().
getRows()
template<typename T > size_t MyPhysics::Diffusion::Matrix< T >::getRows () const inline virtual
Returns the number of rows in the matrix.
Returns
The number of rows in the matrix.
Reimplemented from MyBLAS::LazyMatrix< T >.
{
         return _size;
     }
References MyPhysics::Diffusion::Matrix< T >::_size.
Referenced by TYPED_TEST().
operator()()
virtual T MyBLAS::LazyMatrix< T >::operator() (size_t row, size_t col) const inline virtual inherited
Computes and returns the value at the specified row and column.
Parameters
row The row index.
col The column index.
Returns
The computed value at the specified row and column.
{
         return generator_(row, col);
     }
operator*()
LazyMatrix MyBLAS::LazyMatrix< T >::operator* (T scalar) const inline inherited
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) * scalar; });
     }
operator*=() [1/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator*= (LazyMatrix< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) * b(i, j); };
         return *this;
     }
operator*=() [2/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator*= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) * scalar; };
         return *this;
     }
operator+()
LazyMatrix MyBLAS::LazyMatrix< T >::operator+ (T scalar) const inline inherited
Matrix-Scalar Operations
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) + scalar; });
     }
operator+=() [1/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator+= (LazyMatrix< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) + b(i, j); };
         return *this;
     }
operator+=() [2/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator+= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) + scalar; };
         return *this;
     }
operator-() [1/2]
LazyMatrix MyBLAS::LazyMatrix< T >::operator- () const inline inherited
{
         return LazyMatrix(getRows(), getCols(), [this](size_t i, size_t j) { return -(*this)(i, j); });
     }
operator-() [2/2]
LazyMatrix MyBLAS::LazyMatrix< T >::operator- (T scalar) const inline inherited
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) - scalar; });
     }
operator-=() [1/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator-= (LazyMatrix< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) - b(i, j); };
         return *this;
     }
operator-=() [2/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator-= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) - scalar; };
         return *this;
     }
operator/()
LazyMatrix MyBLAS::LazyMatrix< T >::operator/ (T scalar) const inline inherited
{
         return LazyMatrix(getRows(), getCols(), [this, scalar](size_t i, size_t j) { return (*this)(i, j) / scalar; });
     }
operator/=() [1/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator/= (LazyMatrix< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i, size_t j) { return old_gen(i, j) / b(i, j); };
         return *this;
     }
operator/=() [2/2]
LazyMatrix& MyBLAS::LazyMatrix< T >::operator/= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i, size_t j) { return old_gen(i, j) / scalar; };
         return *this;
     }
operator=()
template<typename T > Matrix& MyPhysics::Diffusion::Matrix< T >::operator= (const Matrix< T > & other) inline
Copy assignment operator.
Parameters
other The matrix to copy.
Returns
A reference to this matrix.
{
         if (this != &other) {
             _params = other._params;
             _size = other._size;
             _constants = other._constants;
             this->setRows(_size);
             this->setCols(_size);
             this->setGenerator([this](size_t i, size_t j) {
                 return generate(i, j, _constants);
             });
         }
         return *this;
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
operator[]() [1/2]
Proxy MyBLAS::LazyMatrix< T >::operator[] (size_t row) inline inherited
{
         return Proxy(*this, row);
     }
operator[]() [2/2]
ConstProxy MyBLAS::LazyMatrix< T >::operator[] (size_t row) const inline inherited
{
         return ConstProxy(*this, row);
     }
setCols()
void MyBLAS::LazyMatrix< T >::setCols (size_t cols) inline protected inherited
 { cols_ = cols; }
setGenerator()
void MyBLAS::LazyMatrix< T >::setGenerator (const Generator & generator) inline protected inherited
 { generator_ = generator; }
setRows()
void MyBLAS::LazyMatrix< T >::setRows (size_t rows) inline protected inherited
 { rows_ = rows; }
Field Documentation
_constants
template<typename T > Constants<T> MyPhysics::Diffusion::Matrix< T >::_constants {} private
The constants used in the diffusion process.
Referenced by MyPhysics::Diffusion::Matrix< T >::getConstants(), MyPhysics::Diffusion::Matrix< T >::Matrix(), and MyPhysics::Diffusion::Matrix< T >::operator=().
_params
template<typename T > Params<T> MyPhysics::Diffusion::Matrix< T >::_params {} private
The parameters of the diffusion process.
Referenced by MyPhysics::Diffusion::Matrix< T >::getParams(), MyPhysics::Diffusion::Matrix< T >::Matrix(), and MyPhysics::Diffusion::Matrix< T >::operator=().
_size
template<typename T > size_t MyPhysics::Diffusion::Matrix< T >::_size = 0 private
The size of the matrix.
Referenced by MyPhysics::Diffusion::Matrix< T >::getCols(), MyPhysics::Diffusion::Matrix< T >::getRows(), MyPhysics::Diffusion::Matrix< T >::Matrix(), and MyPhysics::Diffusion::Matrix< T >::operator=().
cols_
size_t MyBLAS::LazyMatrix< T >::cols_ private inherited
generator_
Generator MyBLAS::LazyMatrix< T >::generator_ private inherited
rows_
size_t MyBLAS::LazyMatrix< T >::rows_ private inherited
The documentation for this class was generated from the following file:
src/utils/physics/diffusion/DiffusionMatrix.h