NE591-008 C++17 Codebase: MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > > Class Template Reference
MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > > Class Template Reference
#include <DiffusionMatrix.h>
Public Types
using Generator = std::function< T(size_t, size_t)>
Public Member Functions
Matrix ()=default
Matrix (const Params< T > params)
Matrix (const Matrix< T > &matrix)
Matrix & operator= (const Matrix &other)
Matrix (const Params< T > &params, Generator generator)
const Params< T > & getParams () const
const Constants< T > & getConstants () const
size_t getRows () const
Getter for the number of rows in the matrix.
size_t getCols () const
Getter for the number of columns in the matrix.
virtual std::vector< T > & operator[] (const size_t rowNum)
Overloaded operator[] to access individual rows of the matrix.
virtual const std::vector< T > & operator[] (const size_t rowNum) const
Overloaded operator[] to access individual rows of the matrix (const version).
const std::vector< std::vector< T > > & getData () const
Getter for the matrix data.
std::vector< std::vector< T > > & getData ()
Getter for the vector data.
void push_back (const std::vector< T > &row)
Adds a new row to the end of the matrix.
Matrix operator+ (const Matrix &rhs) const
Overloaded operator+ to add two matrices.
Matrix operator+ (const T &scalar) const
Overloaded operator+ to add a scalar to the matrix.
Matrix operator- (const Matrix &rhs) const
Overloaded operator- to subtract two matrices.
Matrix operator- (const T &scalar) const
Overloaded operator- to subtract a scalar from the matrix.
Matrix operator* (const Matrix &rhs) const
Overloaded operator* to multiply two matrices.
Vector< T > operator* (const Vector< T > &rhs) const
Overloaded operator* to multiply a matrix with a vector.
Matrix operator* (const T &scalar) const
Overloaded operator* to multiply the matrix by a scalar.
void setSubMatrix (size_t rowStart, size_t colStart, const Matrix< T > &subMatrix)
Sets a submatrix within the current matrix.
Matrix< T > subMatrix (size_t rowStart, size_t colStart, size_t subRows, size_t subCols) const
Extracts a submatrix from the current matrix.
bool operator== (const Matrix &rhs) const
Overloaded operator== to check for equality between two matrices.
Matrix operator/ (const T &scalar) const
Overloaded operator/ to divide the matrix by a scalar.
void swapRows (size_t row1, size_t row2)
Swaps two rows in the matrix.
Static Public Member Functions
static T generate (size_t idx, size_t idy, const Constants< T > &c)
static Matrix eye (size_t size)
Static function to get the identity matrix of a given size.
Protected Attributes
std::vector< std::vector< T > > data
2D vector representing the matrix data.
size_t rows
size_t cols
Number of rows and columns in the matrix.
Private Attributes
Params< T > _params {}
size_t _size = 0
Constants< T > _constants {}
Detailed Description
template<typename T>
class MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >
Member Typedef Documentation
Generator
template<typename T > using MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::Generator = std::function<T(size_t, size_t)>
Constructor & Destructor Documentation
Matrix() [1/4]
template<typename T > MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::Matrix () explicit default
Matrix() [2/4]
template<typename T > MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::Matrix (const Params< T > params) inline explicit
                                            : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator([this](size_t i, size_t j) {
             return generate(i, j, _constants);
         });
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getN(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Matrix() [3/4]
template<typename T > MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::Matrix (const Matrix< T > & matrix) inline
                                    : _params(matrix.params), _constants(Constants<T>::compute(matrix.params)) {
         _size = matrix._size;
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator([this](size_t i, size_t j) {
             return generate(i, j, _constants);
         });
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Matrix() [4/4]
template<typename T > MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::Matrix (const Params< T > & params, Generator generator) inline
                                                         : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setRows(_size);
         this->setCols(_size);
         this->setGenerator(generator);
     }
References MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getN(), MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
Member Function Documentation
eye()
template<typename T > static Matrix MyBLAS::Matrix< T >::eye (size_t size) inline static inherited
Static function to get the identity matrix of a given size.
Parameters
size Size of the identity matrix.
Returns
Identity matrix of the given size.
{
         Matrix eye(size, size, 0);
         for (size_t i = 0; i < size; ++i) {
             eye[i][i] = 1;
         }
         return eye;
     }
References i.
Referenced by Parser::buildInputs(), dooLittleFactorizeLUP(), MyBLAS::LUP::dooLittleFactorizeLUP(), factorizeLUwithPartialPivoting(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), recursiveFactorizeLUP(), MyBLAS::LUP::recursiveFactorizeLUP(), and OutLab4::run().
generate()
template<typename T > static T MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::generate (size_t idx, size_t idy, const Constants< T > & c) inline static
{
         if (idx == idy) {
             return c.diagonal;
         }
         const size_t i = (idx / c.n), p = (idy / c.n);
         if ((i == p) && (idx == idy + 1 || idx == idy - 1)) {
             return c.minus_D_over_gamma_squared;
         }
         const size_t j = (idx % c.n), q = (idy % c.n);
         if ((j == q) && (idx == idy + c.n || idx == idy - c.n)) {
             return c.minus_D_over_delta_squared;
         }
         return 0;
     }
References MyPhysics::Diffusion::Constants< T >::diagonal, i, MyPhysics::Diffusion::Constants< T >::minus_D_over_delta_squared, MyPhysics::Diffusion::Constants< T >::minus_D_over_gamma_squared, MyPhysics::Diffusion::Constants< T >::n, and generate_source_multi_lobe::q.
getCols()
template<typename T > size_t MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::getCols () const inline virtual
Getter for the number of columns in the matrix.
Returns
Number of columns in the matrix.
Reimplemented from MyBLAS::Matrix< T >.
{
         return _size;
     }
References MyPhysics::Diffusion::Matrix< T >::_size.
getConstants()
template<typename T > const Constants<T>& MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::getConstants () const inline
 { return _constants; }
References MyPhysics::Diffusion::Matrix< T >::_constants.
getData() [1/2]
template<typename T > std::vector<std::vector<T> >& MyBLAS::Matrix< T >::getData () inline inherited
Getter for the vector data.
Returns
reference to the vector data.
 { return data; }
References MyBLAS::Matrix< T >::data.
getData() [2/2]
template<typename T > const std::vector<std::vector<T> >& MyBLAS::Matrix< T >::getData () const inline inherited
Getter for the matrix data.
Returns
Const reference to the matrix data.
 { return data; }
References MyBLAS::Matrix< T >::data.
Referenced by Input::toJSON(), MyBLAS::Input::toJSON(), and Map::toJSON().
getParams()
template<typename T > const Params<T>& MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::getParams () const inline
 { return _params; }
References MyPhysics::Diffusion::Matrix< T >::_params.
getRows()
template<typename T > size_t MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::getRows () const inline virtual
Getter for the number of rows in the matrix.
Returns
Number of rows in the matrix.
Reimplemented from MyBLAS::Matrix< T >.
{
         return _size;
     }
References MyPhysics::Diffusion::Matrix< T >::_size.
operator*() [1/3]
template<typename T > Matrix MyBLAS::Matrix< T >::operator* (const Matrix< T > & rhs) const inline inherited
Overloaded operator* to multiply two matrices.
Parameters
rhs Matrix to multiply with the current matrix.
Returns
Resultant matrix after multiplication.
{
         if (cols != rhs.rows) {
             throw std::exception();
         }
         Matrix result(rows, rhs.cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < rhs.cols; ++j) {
                 for (size_t k = 0; k < cols; ++k) {
                     result[i][j] += this->data[i][k] * rhs.data[k][j];
                 }
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, k, and MyBLAS::Matrix< T >::rows.
operator*() [2/3]
template<typename T > Matrix MyBLAS::Matrix< T >::operator* (const T & scalar) const inline inherited
Overloaded operator* to multiply the matrix by a scalar.
Parameters
scalar Scalar to multiply the matrix with.
Returns
Resultant matrix after multiplication.
{
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] * scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, i, and MyBLAS::Matrix< T >::rows.
operator*() [3/3]
template<typename T > Vector<T> MyBLAS::Matrix< T >::operator* (const Vector< T > & rhs) const inline inherited
Overloaded operator* to multiply a matrix with a vector.
Parameters
rhs Vector to multiply with the current matrix.
Returns
Resultant vector after multiplication.
{
         if (cols != rhs.size()) {
             throw std::exception();
         }
         Vector<T> result(rows, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i] += this->data[i][j] * rhs[j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, i, MyBLAS::Matrix< T >::rows, and MyBLAS::Vector< T >::size().
operator+() [1/2]
template<typename T > Matrix MyBLAS::Matrix< T >::operator+ (const Matrix< T > & rhs) const inline inherited
Overloaded operator+ to add two matrices.
Parameters
rhs Matrix to add to the current matrix.
Returns
Resultant matrix after addition.
{
         if (rows != rhs.rows || cols != rhs.cols) {
             throw std::exception();
         }
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] + rhs.data[i][j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, and MyBLAS::Matrix< T >::rows.
operator+() [2/2]
template<typename T > Matrix MyBLAS::Matrix< T >::operator+ (const T & scalar) const inline inherited
Overloaded operator+ to add a scalar to the matrix.
Parameters
scalar Scalar to add to the matrix.
Returns
Resultant matrix after addition.
{
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] + scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, i, and MyBLAS::Matrix< T >::rows.
operator-() [1/2]
template<typename T > Matrix MyBLAS::Matrix< T >::operator- (const Matrix< T > & rhs) const inline inherited
Overloaded operator- to subtract two matrices.
Parameters
rhs Matrix to subtract from the current matrix.
Returns
Resultant matrix after subtraction.
{
         if (rows != rhs.rows || cols != rhs.cols) {
             throw std::exception();
         }
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] - rhs.data[i][j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, and MyBLAS::Matrix< T >::rows.
operator-() [2/2]
template<typename T > Matrix MyBLAS::Matrix< T >::operator- (const T & scalar) const inline inherited
Overloaded operator- to subtract a scalar from the matrix.
Parameters
scalar Scalar to subtract from the matrix.
Returns
Resultant matrix after subtraction.
{
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] - scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, i, and MyBLAS::Matrix< T >::rows.
operator/()
template<typename T > Matrix MyBLAS::Matrix< T >::operator/ (const T & scalar) const inline inherited
Overloaded operator/ to divide the matrix by a scalar.
Parameters
scalar Scalar to divide the matrix by.
Returns
Resultant matrix after division.
{
         const T divisor = scalar == 0 ? NAN : scalar;
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] / divisor;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::cols, i, and MyBLAS::Matrix< T >::rows.
operator=()
template<typename T > Matrix& MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::operator= (const Matrix< MyBLAS::Matrix< T > > & other) inline
{
         if (this != &other) {
             _params = other._params;
             _size = other._size;
             _constants = other._constants;
             this->setRows(_size);
             this->setCols(_size);
             this->setGenerator([this](size_t i, size_t j) {
                 return generate(i, j, _constants);
             });
         }
         return *this;
     }
References MyPhysics::Diffusion::Matrix< T >::_constants, MyPhysics::Diffusion::Matrix< T >::_params, MyPhysics::Diffusion::Matrix< T >::_size, MyPhysics::Diffusion::Matrix< T >::generate(), i, MyBLAS::LazyMatrix< T >::setCols(), MyBLAS::LazyMatrix< T >::setGenerator(), and MyBLAS::LazyMatrix< T >::setRows().
operator==()
template<typename T > bool MyBLAS::Matrix< T >::operator== (const Matrix< T > & rhs) const inline inherited
Overloaded operator== to check for equality between two matrices.
Parameters
rhs Matrix to compare with the current matrix.
Returns
True if the matrices are equal, false otherwise.
Note
This operator checks for exact equality of each element in the matrices. However, when dealing with floating-point numbers, due to the way they are represented in computers, two numbers that are theoretically equal may not be exactly equal when represented in a computer. Therefore, when dealing with floating-point numbers, it might be more appropriate to check if the difference between the matrices is below a certain tolerance, rather than checking for exact equality.
{
         if (rows != rhs.rows || cols != rhs.cols) {
             return false;
         }
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 if (this->data[i][j] != rhs.data[i][j]) {
                     return false;
                 }
             }
         }
         return true;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, and MyBLAS::Matrix< T >::rows.
operator[]() [1/2]
template<typename T > virtual std::vector<T>& MyBLAS::Matrix< T >::operator[] (const size_t rowNum) inline virtual inherited
Overloaded operator[] to access individual rows of the matrix.
Parameters
rowNum Index of the row to access.
Returns
Reference to the row at the given index.
 { return data[rowNum]; }
References MyBLAS::Matrix< T >::data.
operator[]() [2/2]
template<typename T > virtual const std::vector<T>& MyBLAS::Matrix< T >::operator[] (const size_t rowNum) const inline virtual inherited
Overloaded operator[] to access individual rows of the matrix (const version).
Parameters
rowNum Index of the row to access.
Returns
Const reference to the row at the given index.
 { return data[rowNum]; }
References MyBLAS::Matrix< T >::data.
push_back()
template<typename T > void MyBLAS::Matrix< T >::push_back (const std::vector< T > & row) inline inherited
Adds a new row to the end of the matrix.
Parameters
row Vector representing the new row to be added.
{
         if (data.empty()) {
             cols = row.size();
         } else if (cols != row.size()) {
             throw std::invalid_argument("Error: Row size does not match the matrix column size.");
         }
         data.push_back(row);
         ++rows;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, process::row, and MyBLAS::Matrix< T >::rows.
setSubMatrix()
template<typename T > void MyBLAS::Matrix< T >::setSubMatrix (size_t rowStart, size_t colStart, const Matrix< T > & subMatrix) inline inherited
Sets a submatrix within the current matrix.
Parameters
rowStart Starting row index for the submatrix.
colStart Starting column index for the submatrix.
subMatrix The submatrix to set.
{
         size_t subRows = subMatrix.getRows();
         size_t subCols = subMatrix.getCols();
         if (rowStart + subRows > rows || colStart + subCols > cols) {
             throw std::exception();
         }
         for (size_t i = 0; i < subRows; ++i) {
             for (size_t j = 0; j < subCols; ++j) {
                 data[rowStart + i][colStart + j] = subMatrix[i][j];
             }
         }
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, MyBLAS::Matrix< T >::rows, and MyBLAS::Matrix< T >::subMatrix().
Referenced by recursiveFactorizeLUP(), MyBLAS::LUP::recursiveFactorizeLUP(), and MyBLAS::LU::recursiveLUFactorize().
subMatrix()
template<typename T > Matrix<T> MyBLAS::Matrix< T >::subMatrix (size_t rowStart, size_t colStart, size_t subRows, size_t subCols) const inline inherited
Extracts a submatrix from the current matrix.
Parameters
rowStart Starting row index for the submatrix.
colStart Starting column index for the submatrix.
subRows Number of rows in the submatrix.
subCols Number of columns in the submatrix.
Returns
The extracted submatrix.
{
         if (rowStart + subRows > rows || colStart + subCols > cols) {
             throw std::exception();
         }
         Matrix<T> subMatrix(subRows, subCols, 0);
         for (size_t i = 0; i < subRows; ++i) {
             for (size_t j = 0; j < subCols; ++j) {
                 subMatrix[i][j] = data[rowStart + i][colStart + j];
             }
         }
         return subMatrix;
     }
References MyBLAS::Matrix< T >::cols, MyBLAS::Matrix< T >::data, i, and MyBLAS::Matrix< T >::rows.
Referenced by recursiveFactorizeLUP(), MyBLAS::LUP::recursiveFactorizeLUP(), MyBLAS::LU::recursiveLUFactorize(), and MyBLAS::Matrix< T >::setSubMatrix().
swapRows()
template<typename T > void MyBLAS::Matrix< T >::swapRows (size_t row1, size_t row2) inline inherited
Swaps two rows in the matrix.
Parameters
row1 Index of the first row to swap.
row2 Index of the second row to swap.
{
         if (row1 >= rows || row2 >= rows) {
             return;
         }
         std::swap(data[row1], data[row2]);
     }
References MyBLAS::Matrix< T >::data, and MyBLAS::Matrix< T >::rows.
Referenced by dooLittleFactorizeLUP(), MyBLAS::LUP::dooLittleFactorizeLUP(), factorizeLUwithPartialPivoting(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), recursiveFactorizeLUP(), and MyBLAS::LUP::recursiveFactorizeLUP().
Field Documentation
_constants
template<typename T > Constants<T> MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::_constants {} private
_params
template<typename T > Params<T> MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::_params {} private
_size
template<typename T > size_t MyPhysics::Diffusion::Matrix< MyBLAS::Matrix< T > >::_size = 0 private
cols
template<typename T > size_t MyBLAS::Matrix< T >::cols protected inherited
Number of rows and columns in the matrix.
Referenced by MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::Matrix(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator/(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Matrix< T >::push_back(), MyBLAS::Matrix< T >::setSubMatrix(), and MyBLAS::Matrix< T >::subMatrix().
data
template<typename T > std::vector<std::vector<T> > MyBLAS::Matrix< T >::data protected inherited
2D vector representing the matrix data.
Referenced by MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getData(), MyBLAS::Matrix< T >::getRows(), MyBLAS::Matrix< T >::Matrix(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Matrix< T >::operator[](), MyBLAS::Matrix< T >::push_back(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), and MyBLAS::Matrix< T >::swapRows().
rows
template<typename T > size_t MyBLAS::Matrix< T >::rows protected inherited
Referenced by MyBLAS::Matrix< T >::getRows(), MyBLAS::Matrix< T >::Matrix(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator/(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Matrix< T >::push_back(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), and MyBLAS::Matrix< T >::swapRows().
The documentation for this class was generated from the following file:
src/utils/physics/diffusion/DiffusionMatrix.h