NE591-008 C++17 Codebase: Project< InputType, CommandLineParserType, OutputType > Class Template Reference
Project< InputType, CommandLineParserType, OutputType > Class Template Reference abstract
A generic class that represents a project that can be executed.
#include <Project.h>
Public Member Functions
Project (CommandLineArgs args)
A static assertion to ensure that CommandLineParserType is a derived class of CommandLine.
virtual ~Project ()=default
Default virtual destructor.
virtual void execute ()
Executes the project.
virtual CommandLineParserType getTerminal () const
Returns the terminal.
InputType & getInputs ()
Returns the input data.
Protected Member Functions
virtual void initialize ()
Initializes the project.
virtual void finalize ()
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual HeaderInfo buildHeaderInfo ()=0
Builds the header information.
virtual void preRun (OutputType &output, InputType &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void run (OutputType &output, InputType &input, boost::program_options::variables_map &values)
Executes the project.
virtual void postRun (OutputType &output, InputType &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
template<typename Func >
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
template<typename Func >
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
template<typename Func >
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs {}
Holds the command line arguments.
CommandLineParserType terminal
An instance of CommandLineParserType which is used to parse command line arguments.
OutputType _outputs
Holds the output data of the project.
Detailed Description
template<typename InputType, typename CommandLineParserType, typename OutputType>
class Project< InputType, CommandLineParserType, OutputType >
A generic class that represents a project that can be executed.
Template Parameters
InputType The type of the input data.
CommandLineParserType The type of the command line parser.
OutputType The type of the output data.
Constructor & Destructor Documentation
Project()
template<typename InputType , typename CommandLineParserType , typename OutputType > Project< InputType, CommandLineParserType, OutputType >::Project (CommandLineArgs args) inline explicit
A static assertion to ensure that CommandLineParserType is a derived class of CommandLine.
Constructor that initializes the command line arguments.
Parameters
args The command line arguments.
 { cmdArgs = args; }
References Project< InputType, CommandLineParserType, OutputType >::cmdArgs.
~Project()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual Project< InputType, CommandLineParserType, OutputType >::~Project () virtual default
Default virtual destructor.
Member Function Documentation
buildHeaderInfo()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual HeaderInfo Project< InputType, CommandLineParserType, OutputType >::buildHeaderInfo () protected pure virtual
Builds the header information.
Returns
The header information.
Implemented in Project5, Project4, Project3, Project2, Project1, OutLab6, OutLab5, OutLab4, OutLab3, OutLab1, InLab6, InLab5, InLab4, InLab3, InLab2, InLab10, and InLab1.
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize().
execute()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::execute () inline virtual
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
References Project< InputType, CommandLineParserType, OutputType >::finalize(), Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
finalize()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::finalize () inline protected virtual
Finalizes the project. This is a virtual function and can be overridden by derived classes to provide specific finalization steps.
{
     }
Referenced by Project< InputType, CommandLineParserType, OutputType >::execute().
getInputs()
template<typename InputType , typename CommandLineParserType , typename OutputType > InputType& Project< InputType, CommandLineParserType, OutputType >::getInputs () inline
Returns the input data.
Returns
A reference to the input data.
{
         return this->inputs;
     }
References process::inputs.
getProfiler() [1/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, size_t samples, std::string description = "") inline protected
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
template<typename InputType , typename CommandLineParserType , typename OutputType > template<typename Func > auto Project< InputType, CommandLineParserType, OutputType >::getProfiler (Func func, std::string description = "") inline protected
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
References Project< InputType, CommandLineParserType, OutputType >::getTerminal(), and ProfilerHelper::InitProfiler().
getTerminal()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual CommandLineParserType Project< InputType, CommandLineParserType, OutputType >::getTerminal () const inline virtual
Returns the terminal.
Returns
The terminal.
 { return terminal; }
References Project< InputType, CommandLineParserType, OutputType >::terminal.
Referenced by Project< InputType, CommandLineParserType, OutputType >::getProfiler().
initialize()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::initialize () inline protected virtual
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         _outputs = OutputType();
     }
References Project< InputType, CommandLineParserType, OutputType >::_outputs, Project< InputType, CommandLineParserType, OutputType >::buildHeaderInfo(), Project< InputType, CommandLineParserType, OutputType >::cmdArgs, and Project< InputType, CommandLineParserType, OutputType >::terminal.
Referenced by Project< InputType, CommandLineParserType, OutputType >::execute().
postRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::postRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
preRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::preRun (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
run()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::run (OutputType & output, InputType & input, boost::program_options::variables_map & values) inline protected virtual
Executes the project.
Parameters
output The output data.
input The input data.
values The variable map.
Reimplemented in InLab1, Project5, Project4, Project3, Project2, Project1, OutLab5, InLab4, OutLab6, OutLab1, OutLab4, InLab5, InLab6, InLab10, OutLab3, InLab3, and InLab2.
 {}
Referenced by Project< InputType, CommandLineParserType, OutputType >::timedRun().
timedRun()
template<typename InputType , typename CommandLineParserType , typename OutputType > virtual void Project< InputType, CommandLineParserType, OutputType >::timedRun () inline protected virtual
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(_outputs, terminal.getInputs(), terminal.getArguments());
         run(_outputs, terminal.getInputs(), terminal.getArguments());
         postRun(_outputs, terminal.getInputs(), terminal.getArguments());
     }
References Project< InputType, CommandLineParserType, OutputType >::_outputs, Project< InputType, CommandLineParserType, OutputType >::postRun(), Project< InputType, CommandLineParserType, OutputType >::preRun(), Project< InputType, CommandLineParserType, OutputType >::run(), and Project< InputType, CommandLineParserType, OutputType >::terminal.
Referenced by Project< InputType, CommandLineParserType, OutputType >::execute().
Field Documentation
_outputs
template<typename InputType , typename CommandLineParserType , typename OutputType > OutputType Project< InputType, CommandLineParserType, OutputType >::_outputs protected
Holds the output data of the project.
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
cmdArgs
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineArgs Project< InputType, CommandLineParserType, OutputType >::cmdArgs {} protected
Holds the command line arguments.
Referenced by Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::Project().
terminal
template<typename InputType , typename CommandLineParserType , typename OutputType > CommandLineParserType Project< InputType, CommandLineParserType, OutputType >::terminal protected
An instance of CommandLineParserType which is used to parse command line arguments.
Referenced by Project< InputType, CommandLineParserType, OutputType >::getTerminal(), Project< InputType, CommandLineParserType, OutputType >::initialize(), and Project< InputType, CommandLineParserType, OutputType >::timedRun().
The documentation for this class was generated from the following file:
src/utils/Project.h