NE591-008 C++17 Codebase: MyBLAS::Solver::Solution< T > Struct Template Reference
MyBLAS::Solver::Solution< T > Struct Template Reference
Structure that represents the solution of the linear solver.
#include <LinearSolver.h>
Public Member Functions
Solution (MyBLAS::Vector< T > &initial)
Solution (size_t size)
Solution ()=default
MyBLAS::Vector< T > getResidual (MyBLAS::Matrix< T > a) const
T getMaxResidual (MyBLAS::Matrix< T > a, MyBLAS::Vector< T > b) const
void toJSON (nlohmann::json &jsonMap) const
Converts the output parameters to a JSON object.
Data Fields
MyBLAS::Solver::Type method
bool converged = false
size_t iterations = std::numeric_limits<size_t>::quiet_NaN()
T iterative_error = std::numeric_limits<T>::quiet_NaN()
MyBLAS::Vector< T > x {}
T eigenvalue = std::numeric_limits<T>::quiet_NaN()
T eigenvalue_iterative_error = std::numeric_limits<T>::quiet_NaN()
MyBLAS::Vector< T > residual {}
T residual_infinite_norm = std::numeric_limits<T>::quiet_NaN()
Friends
std::ostream & operator<< (std::ostream &os, const Solution &solution)
Overloaded stream insertion operator to print the summary statistics.
Detailed Description
template<typename T>
struct MyBLAS::Solver::Solution< T >
Structure that represents the solution of the linear solver.
Template Parameters
T The type of the elements in the matrix/vector.
Constructor & Destructor Documentation
Solution() [1/3]
template<typename T > MyBLAS::Solver::Solution< T >::Solution (MyBLAS::Vector< T > & initial) inline explicit
 { x = initial; }
References MyFactorizationMethod::TypeKey(), and MyRelaxationMethod::TypeKey().
Solution() [2/3]
template<typename T > MyBLAS::Solver::Solution< T >::Solution (size_t size) inline explicit
 { x = MyBLAS::Vector<T>(size, 0); }
Solution() [3/3]
template<typename T > MyBLAS::Solver::Solution< T >::Solution () default
Member Function Documentation
getMaxResidual()
template<typename T > T MyBLAS::Solver::Solution< T >::getMaxResidual (MyBLAS::Matrix< T > a, MyBLAS::Vector< T > b) const inline
{
         return MyBLAS::Stats::max<T>(MyBLAS::Stats::abs(b - getResidual(a)));
     }
References MyBLAS::Stats::abs().
Referenced by OutLab6::printResults(), and Output::toJSON().
getResidual()
template<typename T > MyBLAS::Vector<T> MyBLAS::Solver::Solution< T >::getResidual (MyBLAS::Matrix< T > a) const inline
 { return a * x; }
References x.
toJSON()
template<typename T > void MyBLAS::Solver::Solution< T >::toJSON (nlohmann::json & jsonMap) const inline
Converts the output parameters to a JSON object.
Parameters
jsonMap The JSON object to which the output parameters are added.
{
         jsonMap["converged"] = converged;
         jsonMap["iterations"] = iterations;
         jsonMap["iterative-error"]["x"] = iterative_error;
         jsonMap["x"] = x.getData();
         if (!std::isnan(eigenvalue)) {
             jsonMap["eigenvalue"] = eigenvalue;
         }
         if (!std::isnan(eigenvalue_iterative_error)) {
             jsonMap["iterative-error"]["eigenvalue"] = eigenvalue_iterative_error;
         }
         if (!std::isnan(residual_infinite_norm)) {
             jsonMap["residual-∞-norm"] = residual_infinite_norm;
         }
         if (residual.size() > 0) {
             jsonMap["residual"] = residual.getData();
         }
     }
References postprocess::converged, postprocess::iterations, postprocess::iterative_error, postprocess::residual, and x.
Referenced by Output::toJSON().
Friends And Related Function Documentation
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const Solution< T > & solution) friend
Overloaded stream insertion operator to print the summary statistics.
Parameters
os The output stream.
summary The summary statistics to print.
Returns
The output stream.
{
         auto precision = std::cout.precision() ;
         const std::string key = Solver::TypeKey(solution.method);
         const auto width = static_cast<int>(2 + static_cast<std::streamsize>(10));
         os << std::setprecision(2) << std::setw(width) << std::setfill(' ') << std::scientific;
         os << ":::::: Converged        :     " << (solution.converged ? "Yes" : "No")<<std::endl;
         os << ":::::: Iterations       :     " << solution.iterations << std::endl;
         os << ":::::: Iterative Error  :     " << solution.iterative_error << std::endl;
         os << ":::::: Iterate Vector x : " << solution.x;
         if (!std::isnan(solution.eigenvalue)) {
             os << ":::::: Eigenvalue       :     " << solution.eigenvalue << std::endl;
         }
         if (!std::isnan(solution.eigenvalue_iterative_error)) {
             os << ":::::: Eigenvalue Error :     " << solution.eigenvalue_iterative_error << std::endl;
         }
         if (!std::isnan(solution.residual_infinite_norm)) {
             os << ":::::: Residual ∞-Norm  :     " << solution.residual_infinite_norm << std::endl;
         }
         if (solution.residual.size() > 0) {
             os << ":::::: Residual         : " << solution.residual << std::endl;
         }
         os << std::setprecision(static_cast<int>(precision));
         return os;
     }
Field Documentation
converged
template<typename T > bool MyBLAS::Solver::Solution< T >::converged = false
Referenced by MyRelaxationMethod::applyConjugateGradient(), MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPowerIteration(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), InLab11::printResults(), InLab12::printResults(), InLab6::printResults(), OutLab10::printResults(), OutLab11::printResults(), OutLab12::printResults(), OutLab6::printResults(), Project2::printResults(), Project3::printResults(), Project4::printResults(), Project5::printResults(), and Output::toJSON().
eigenvalue
template<typename T > T MyBLAS::Solver::Solution< T >::eigenvalue = std::numeric_limits<T>::quiet_NaN()
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), MyRelaxationMethod::applyPowerIteration(), and MyRelaxationMethod::applyRayleighQuotientPowerIteration().
eigenvalue_iterative_error
template<typename T > T MyBLAS::Solver::Solution< T >::eigenvalue_iterative_error = std::numeric_limits<T>::quiet_NaN()
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), and MyRelaxationMethod::applyRayleighQuotientPowerIteration().
iterations
template<typename T > size_t MyBLAS::Solver::Solution< T >::iterations = std::numeric_limits<size_t>::quiet_NaN()
Referenced by MyRelaxationMethod::applyConjugateGradient(), MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPowerIteration(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), InLab11::printResults(), InLab12::printResults(), InLab6::printResults(), OutLab10::printResults(), OutLab11::printResults(), OutLab12::printResults(), OutLab6::printResults(), Project2::printResults(), Project3::printResults(), Project4::printResults(), Project5::printResults(), and Output::toJSON().
iterative_error
template<typename T > T MyBLAS::Solver::Solution< T >::iterative_error = std::numeric_limits<T>::quiet_NaN()
Referenced by MyRelaxationMethod::applyConjugateGradient(), MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPowerIteration(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), InLab11::printResults(), InLab12::printResults(), InLab6::printResults(), OutLab10::printResults(), OutLab11::printResults(), OutLab12::printResults(), OutLab6::printResults(), Project2::printResults(), Project3::printResults(), Project4::printResults(), Project5::printResults(), and Output::toJSON().
method
template<typename T > MyBLAS::Solver::Type MyBLAS::Solver::Solution< T >::method
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), and MyRelaxationMethod::applyRayleighQuotientPowerIteration().
residual
template<typename T > MyBLAS::Vector<T> MyBLAS::Solver::Solution< T >::residual {}
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), and MyRelaxationMethod::applyRayleighQuotientPowerIteration().
residual_infinite_norm
template<typename T > T MyBLAS::Solver::Solution< T >::residual_infinite_norm = std::numeric_limits<T>::quiet_NaN()
Referenced by MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), and MyRelaxationMethod::applyRayleighQuotientPowerIteration().
x
template<typename T > MyBLAS::Vector<T> MyBLAS::Solver::Solution< T >::x {}
Referenced by MyRelaxationMethod::applyConjugateGradient(), MyRelaxationMethod::applyDirectPowerIteration(), MyRelaxationMethod::applyInversePowerIteration(), MyRelaxationMethod::applyJacobiPreconditionedConjugateGradient(), MyBLAS::LUP::applyLUP(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPowerIteration(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applyRayleighQuotientPowerIteration(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), Output::getMaxResidual(), Output::getSolutionError(), and Output::toJSON().
The documentation for this struct was generated from the following file:
src/utils/math/blas/solver/LinearSolver.h