NE591-008 C++17 Codebase: MyPhysics::Diffusion::Params< FloatType > Struct Template Reference
MyPhysics::Diffusion::Params< FloatType > Struct Template Reference
Template struct to hold parameters for the diffusion solver.
#include <DiffusionParams.h>
Public Member Functions
Params ()=default
Default constructor for Params.
Params (FloatType a, FloatType b, size_t m, size_t n, FloatType coefficient, FloatType crossSection, MyBLAS::Matrix< FloatType > &sources)
Constructor with initialization of parameters.
Params & setA (FloatType a)
Set the length of the rectangular region in the x-direction.
Params & setB (FloatType b)
Set the length of the rectangular region in the y-direction.
Params & setM (size_t m)
Set the number of mesh points in the x-direction.
Params & setN (size_t n)
Set the number of mesh points in the y-direction.
Params & setDiffusionCoefficient (FloatType coefficient)
Set the diffusion coefficient for the diffusion equation.
Params & setMacroscopicRemovalCrossSection (FloatType crossSection)
Set the macroscopic removal cross-section.
Params & setSources (const MyBLAS::Matrix< FloatType > &sources)
Set the matrix of sources for the diffusion problem.
FloatType getA () const
Get the length of the rectangular region in the x-direction.
FloatType getB () const
Get the length of the rectangular region in the y-direction.
size_t getM () const
Get the number of mesh points in the x-direction.
size_t getN () const
Get the number of mesh points in the y-direction.
FloatType getDelta () const
Get the mesh spacing in the x-direction.
FloatType getGamma () const
Get the mesh spacing in the y-direction.
FloatType getDiffusionCoefficient () const
Get the diffusion coefficient for the diffusion equation.
FloatType getMacroscopicRemovalCrossSection () const
Get the macroscopic removal cross-section.
const MyBLAS::Matrix< FloatType > & getSources () const
Get the matrix of sources for the diffusion problem.
Static Private Member Functions
static FloatType compute_mesh_spacing (const FloatType length, const size_t points)
Calculates the mesh spacings in the given direction.
Private Attributes
FloatType _a = 1
Length of the rectangular region in the x-direction.
FloatType _b = 1
Length of the rectangular region in the y-direction.
size_t _m = 1
Number of mesh points in the x-direction, excluding boundary points.
size_t _n = 1
Number of mesh points in the y-direction, excluding boundary points.
FloatType _delta = 1
Mesh spacing in the x-direction.
FloatType _gamma = 1
Mesh spacing in the y-direction.
FloatType _diff_coeff = 0.0f
Diffusion coefficient for the diffusion equation.
FloatType _cross_section = 0.0f
Macroscopic removal cross-section.
MyBLAS::Matrix< FloatType > _sources = MyBLAS::Matrix<FloatType>()
Matrix of sources for the diffusion problem.
Friends
std::ostream & operator<< (std::ostream &os, const Params &params)
Overloaded output stream operator for displaying the contents of Params.
Detailed Description
template<typename FloatType>
struct MyPhysics::Diffusion::Params< FloatType >
Template struct to hold parameters for the diffusion solver.
This struct contains parameters necessary for solving diffusion problems.
Template Parameters
FloatType The data type used for storing parameters.
Constructor & Destructor Documentation
Params() [1/2]
template<typename FloatType > MyPhysics::Diffusion::Params< FloatType >::Params () default
Default constructor for Params.
Params() [2/2]
template<typename FloatType > MyPhysics::Diffusion::Params< FloatType >::Params (FloatType a, FloatType b, size_t m, size_t n, FloatType coefficient, FloatType crossSection, MyBLAS::Matrix< FloatType > & sources) inline
Constructor with initialization of parameters.
Parameters
a The length of the rectangular region in the x-direction.
b The length of the rectangular region in the y-direction.
m The number of mesh points in the x-direction.
n The number of mesh points in the y-direction.
coefficient Diffusion coefficient for the diffusion equation.
crossSection Macroscopic removal cross-section.
sources Matrix of sources for the diffusion problem.
{
         setA(a);
         setB(b);
         setM(m);
         setN(n);
         setDiffusionCoefficient(coefficient);
         setMacroscopicRemovalCrossSection(crossSection);
         setSources(sources);
     }
References m, n, MyPhysics::Diffusion::Params< FloatType >::setA(), MyPhysics::Diffusion::Params< FloatType >::setB(), MyPhysics::Diffusion::Params< FloatType >::setDiffusionCoefficient(), MyPhysics::Diffusion::Params< FloatType >::setM(), MyPhysics::Diffusion::Params< FloatType >::setMacroscopicRemovalCrossSection(), MyPhysics::Diffusion::Params< FloatType >::setN(), and MyPhysics::Diffusion::Params< FloatType >::setSources().
Member Function Documentation
compute_mesh_spacing()
template<typename FloatType > static FloatType MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing (const FloatType length, const size_t points) inline static private
Calculates the mesh spacings in the given direction.
Computes the mesh spacings using the equation: spacing = length / (points + 1). These spacings are used to discretize the diffusion operator in the given equation.
Parameters
length The length of the rectangular region in the given direction.
points The number of mesh points in the given direction, excluding the boundary points.
[out] delta The mesh spacing in the given direction.
{
         const FloatType spacing = length / (static_cast<FloatType>(points) + static_cast<FloatType>(1));
         return spacing;
     }
References points.
Referenced by MyPhysics::Diffusion::Params< FloatType >::setA(), MyPhysics::Diffusion::Params< FloatType >::setB(), MyPhysics::Diffusion::Params< FloatType >::setM(), and MyPhysics::Diffusion::Params< FloatType >::setN().
getA()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getA () const inline
Get the length of the rectangular region in the x-direction.
Returns
The length of the rectangular region in the x-direction.
 { return _a; }
References MyPhysics::Diffusion::Params< FloatType >::_a.
Referenced by TEST_F(), Input::toJSON(), and TYPED_TEST().
getB()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getB () const inline
Get the length of the rectangular region in the y-direction.
Returns
The length of the rectangular region in the y-direction.
 { return _b; }
References MyPhysics::Diffusion::Params< FloatType >::_b.
Referenced by TEST_F(), Input::toJSON(), and TYPED_TEST().
getDelta()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getDelta () const inline
Get the mesh spacing in the x-direction.
Returns
The mesh spacing in the x-direction.
 { return _delta; }
References MyPhysics::Diffusion::Params< FloatType >::_delta.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Constants< T >::compute(), TEST_F(), and Input::toJSON().
getDiffusionCoefficient()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient () const inline
Get the diffusion coefficient for the diffusion equation.
Returns
The diffusion coefficient for the diffusion equation.
 { return _diff_coeff; }
References MyPhysics::Diffusion::Params< FloatType >::_diff_coeff.
Referenced by MyPhysics::Diffusion::Constants< T >::compute(), TEST_F(), and Input::toJSON().
getGamma()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getGamma () const inline
Get the mesh spacing in the y-direction.
Returns
The mesh spacing in the y-direction.
 { return _gamma; }
References MyPhysics::Diffusion::Params< FloatType >::_gamma.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Constants< T >::compute(), TEST_F(), and Input::toJSON().
getM()
template<typename FloatType > size_t MyPhysics::Diffusion::Params< FloatType >::getM () const inline
Get the number of mesh points in the x-direction.
Returns
The number of mesh points in the x-direction.
 { return _m; }
References MyPhysics::Diffusion::Params< FloatType >::_m.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Constants< T >::compute(), Compute::fill_fluxes(), MyPhysics::Diffusion::Matrix< T >::Matrix(), TEST_F(), Input::toJSON(), and TYPED_TEST().
getMacroscopicRemovalCrossSection()
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection () const inline
Get the macroscopic removal cross-section.
Returns
The macroscopic removal cross-section.
 { return _cross_section; }
References MyPhysics::Diffusion::Params< FloatType >::_cross_section.
Referenced by MyPhysics::Diffusion::Constants< T >::compute(), TEST_F(), and Input::toJSON().
getN()
template<typename FloatType > size_t MyPhysics::Diffusion::Params< FloatType >::getN () const inline
Get the number of mesh points in the y-direction.
Returns
The number of mesh points in the y-direction.
 { return _n; }
References MyPhysics::Diffusion::Params< FloatType >::_n.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Constants< T >::compute(), Compute::fill_fluxes(), MyPhysics::Diffusion::Matrix< T >::Matrix(), TEST_F(), Input::toJSON(), and TYPED_TEST().
getSources()
template<typename FloatType > const MyBLAS::Matrix<FloatType>& MyPhysics::Diffusion::Params< FloatType >::getSources () const inline
Get the matrix of sources for the diffusion problem.
Returns
The matrix of sources for the diffusion problem.
 { return _sources; }
References MyPhysics::Diffusion::Params< FloatType >::_sources.
Referenced by TEST_F().
setA()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setA (FloatType a) inline
Set the length of the rectangular region in the x-direction.
Parameters
a The length of the rectangular region in the x-direction.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
         if (a <= 0 || !std::isfinite(a)) {
             throw std::invalid_argument("Invalid value for a. It should be a positive finite number.");
         }
         _a = a;
         _delta = compute_mesh_spacing(a, _m);
         return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_a, MyPhysics::Diffusion::Params< FloatType >::_delta, MyPhysics::Diffusion::Params< FloatType >::_m, MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing(), and MyMath::isfinite().
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setB()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setB (FloatType b) inline
Set the length of the rectangular region in the y-direction.
Parameters
b The length of the rectangular region in the y-direction.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
         if (b <= 0 || !std::isfinite(b)) {
             throw std::invalid_argument("Invalid value for b. It should be a positive finite number.");
         }
         _b = b;
         _gamma = compute_mesh_spacing(b, _n);
         return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_b, MyPhysics::Diffusion::Params< FloatType >::_gamma, MyPhysics::Diffusion::Params< FloatType >::_n, MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing(), and MyMath::isfinite().
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setDiffusionCoefficient()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setDiffusionCoefficient (FloatType coefficient) inline
Set the diffusion coefficient for the diffusion equation.
Parameters
coefficient Diffusion coefficient for the diffusion equation.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
        if (coefficient <= 0 || !std::isfinite(coefficient)) {
            throw std::invalid_argument("Invalid value for diffusion coefficient. It should be a positive finite number.");
        }
        _diff_coeff = coefficient;
        return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_diff_coeff, and MyMath::isfinite().
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setM()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setM (size_t m) inline
Set the number of mesh points in the x-direction.
Parameters
m The number of mesh points in the x-direction.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is zero.
{
         if (m == 0) {
             throw std::invalid_argument("Invalid value for m. It should be a positive number.");
         }
         _m = m;
         _delta = compute_mesh_spacing(_a, m);
         return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_a, MyPhysics::Diffusion::Params< FloatType >::_delta, MyPhysics::Diffusion::Params< FloatType >::_m, MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing(), and m.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setMacroscopicRemovalCrossSection()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setMacroscopicRemovalCrossSection (FloatType crossSection) inline
Set the macroscopic removal cross-section.
Parameters
crossSection Macroscopic removal cross-section.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is non-positive or not finite.
{
        if (crossSection <= 0 || !std::isfinite(crossSection)) {
            throw std::invalid_argument("Invalid value for macroscopic removal cross-section. It should be a positive finite number.");
        }
        _cross_section = crossSection;
        return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_cross_section, and MyMath::isfinite().
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setN()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setN (size_t n) inline
Set the number of mesh points in the y-direction.
Parameters
n The number of mesh points in the y-direction.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the provided value is zero.
{
         if (n == 0) {
             throw std::invalid_argument("Invalid value for n. It should be a positive number.");
         }
         _n = n;
         _gamma = compute_mesh_spacing(_b, n);
         return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_b, MyPhysics::Diffusion::Params< FloatType >::_gamma, MyPhysics::Diffusion::Params< FloatType >::_n, MyPhysics::Diffusion::Params< FloatType >::compute_mesh_spacing(), and n.
Referenced by Parser::buildInputs(), MyPhysics::Diffusion::Params< FloatType >::Params(), and TYPED_TEST().
setSources()
template<typename FloatType > Params& MyPhysics::Diffusion::Params< FloatType >::setSources (const MyBLAS::Matrix< FloatType > & sources) inline
Set the matrix of sources for the diffusion problem.
Parameters
sources Matrix of sources for the diffusion problem.
Returns
A reference to the Params struct.
Exceptions
std::invalid_argument if the dimensions of the sources matrix do not match with the number of mesh points.
{
        if (sources.getRows() != _m || sources.getCols() != _n) {
            throw std::invalid_argument("Invalid dimensions for the sources matrix. It should match with the number of mesh points.");
        }
        _sources = sources;
        return *this;
     }
References MyPhysics::Diffusion::Params< FloatType >::_m, MyPhysics::Diffusion::Params< FloatType >::_n, MyPhysics::Diffusion::Params< FloatType >::_sources, MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
Referenced by MyPhysics::Diffusion::Params< FloatType >::Params().
Friends And Related Function Documentation
operator<<
template<typename FloatType > std::ostream& operator<< (std::ostream & os, const Params< FloatType > & params) friend
Overloaded output stream operator for displaying the contents of Params.
This operator allows you to stream the contents of a Params object to an output stream, typically for debugging or logging purposes.
Parameters
os The output stream to which the Params content will be written.
params The Params object to display.
Returns
The updated output stream after writing the Params content.
{
        os << "a: " << params._a << " b: " << params._b << " m: " << params._m << " n: " << params._n
           << " delta: " << params._delta << " gamma: " << params._gamma << " diff_coeff: " << params._diff_coeff
           << " cross_section: " << params._cross_section;
        return os;
     }
Field Documentation
_a
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_a = 1 private
Length of the rectangular region in the x-direction.
This value represents the extent of the rectangular region in the x-direction.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getA(), MyPhysics::Diffusion::Params< FloatType >::setA(), and MyPhysics::Diffusion::Params< FloatType >::setM().
_b
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_b = 1 private
Length of the rectangular region in the y-direction.
This value represents the extent of the rectangular region in the y-direction.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getB(), MyPhysics::Diffusion::Params< FloatType >::setB(), and MyPhysics::Diffusion::Params< FloatType >::setN().
_cross_section
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_cross_section = 0.0f private
Macroscopic removal cross-section.
This value represents the macroscopic removal cross-section, which is a parameter in the diffusion equation.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getMacroscopicRemovalCrossSection(), and MyPhysics::Diffusion::Params< FloatType >::setMacroscopicRemovalCrossSection().
_delta
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_delta = 1 private
Mesh spacing in the x-direction.
This value represents the spacing between mesh points in the x-direction.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getDelta(), MyPhysics::Diffusion::Params< FloatType >::setA(), and MyPhysics::Diffusion::Params< FloatType >::setM().
_diff_coeff
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_diff_coeff = 0.0f private
Diffusion coefficient for the diffusion equation.
This coefficient represents the diffusion property in the diffusion equation.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getDiffusionCoefficient(), and MyPhysics::Diffusion::Params< FloatType >::setDiffusionCoefficient().
_gamma
template<typename FloatType > FloatType MyPhysics::Diffusion::Params< FloatType >::_gamma = 1 private
Mesh spacing in the y-direction.
This value represents the spacing between mesh points in the y-direction.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getGamma(), MyPhysics::Diffusion::Params< FloatType >::setB(), and MyPhysics::Diffusion::Params< FloatType >::setN().
_m
template<typename FloatType > size_t MyPhysics::Diffusion::Params< FloatType >::_m = 1 private
Number of mesh points in the x-direction, excluding boundary points.
This value determines the number of mesh points in the x-direction, excluding the boundary points.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::setA(), MyPhysics::Diffusion::Params< FloatType >::setM(), and MyPhysics::Diffusion::Params< FloatType >::setSources().
_n
template<typename FloatType > size_t MyPhysics::Diffusion::Params< FloatType >::_n = 1 private
Number of mesh points in the y-direction, excluding boundary points.
This value determines the number of mesh points in the y-direction, excluding the boundary points.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getN(), MyPhysics::Diffusion::Params< FloatType >::setB(), MyPhysics::Diffusion::Params< FloatType >::setN(), and MyPhysics::Diffusion::Params< FloatType >::setSources().
_sources
template<typename FloatType > MyBLAS::Matrix<FloatType> MyPhysics::Diffusion::Params< FloatType >::_sources = MyBLAS::Matrix<FloatType>() private
Matrix of sources for the diffusion problem.
This matrix holds source terms for the diffusion problem.
Referenced by MyPhysics::Diffusion::Params< FloatType >::getSources(), and MyPhysics::Diffusion::Params< FloatType >::setSources().
The documentation for this struct was generated from the following file:
src/utils/physics/diffusion/DiffusionParams.h