NE591-008 C++17 Codebase: MyBLAS::Matrix< T > Class Template Reference
MyBLAS::Matrix< T > Class Template Reference
Class representing a matrix of T type values.
#include <Matrix.h>
Public Member Functions
size_t getAllocatedBytes (bool actual=false) const
Matrix ()
Default constructor. Initializes an empty matrix.
~Matrix ()
Default destructor.
Matrix (std::vector< std::vector< T >> &_data)
Constructor that initializes the matrix with a given 2D vector.
Matrix (const std::vector< std::vector< T >> &_data)
Const Constructor that initializes the matrix with a given 2D vector.
Matrix (std::vector< std::vector< T >> &&_data)
Constructor that initializes the matrix with a given 2D vector.
Matrix (Matrix &&other) noexcept
Move constructor.
Matrix (const Matrix &other)
Copy constructor.
template<typename U >
Matrix (const Matrix< U > &other)
Constructor that initializes the matrix with another matrix of a different type.
template<class MatrixType >
Matrix (MatrixType matrix)
Constructor that initializes the matrix with another matrix.
Matrix (size_t _rows, size_t _cols, const T _initial=0)
Parameterized constructor that initializes the matrix with a given size and initial value.
Matrix (std::initializer_list< std::initializer_list< T >> initList)
Constructor that initializes the matrix with a given initializer list.
Matrix (size_t rows, size_t cols, std::function< T(size_t, size_t)> func)
Constructor that initializes the matrix with a given size and a lambda function.
Matrix & operator= (const Matrix &other)
Copy assignment operator. Used to assign one Matrix to another after their initial construction.
Matrix & operator= (Matrix &&other) noexcept
Move assignment operator. This operator is used to transfer the ownership of resources from one Matrix to another without copying the data.
T & operator() (size_t row, size_t col)
Overloaded operator() to access individual elements of the matrix.
const T & operator() (size_t row, size_t col) const
Overloaded operator() const to access individual elements of the matrix.
std::vector< T > & operator[] (const size_t rowNum)
Overloaded operator[] to access individual rows of the matrix.
const std::vector< T > & operator[] (const size_t rowNum) const
Overloaded operator[] to access individual rows of the matrix (const version).
const std::vector< std::vector< T > > & getData () const
Getter for the matrix data.
std::vector< std::vector< T > > & getData ()
Getter for the vector data.
void push_back (const std::vector< T > &row)
Adds a new row to the end of the matrix.
size_t getRows () const
Getter for the number of rows in the matrix.
size_t getCols () const
Getter for the number of columns in the matrix.
Matrix operator+ (const Matrix &rhs) const
Overloaded operator+ to add two matrices.
Matrix operator- (const Matrix &rhs) const
Overloaded operator- to subtract two matrices.
Matrix operator* (const Matrix &rhs) const
Overloaded operator* to multiply two matrices.
template<typename MatrixType1 , typename MatrixType2 >
MatrixType1 operator* (const MatrixType2 &rhs) const
Overloaded operator* to multiply two matrices, where one is of type MatrixType.
template<typename MatrixType1 , typename MatrixType2 >
MatrixType1 operator* (const MatrixType1 &rhs) const
Overloaded operator* to multiply two matrices, where one is of type MatrixType.
Vector< T > operator* (const Vector< T > &rhs) const
Overloaded operator* to multiply a matrix with a vector.
void setSubMatrix (size_t rowStart, size_t colStart, const Matrix< T > &subMatrix)
Sets a submatrix within the current matrix.
Matrix< T > subMatrix (size_t rowStart, size_t colStart, size_t subRows, size_t subCols) const
Extracts a submatrix from the current matrix.
bool operator== (const Matrix &rhs) const
Overloaded operator== to check for equality between two matrices.
Matrix operator* (const T &scalar) const
Overloaded operator* to multiply the matrix by a scalar.
Matrix operator/ (const T &scalar) const
Overloaded operator/ to divide the matrix by a scalar.
Matrix operator+ (const T &scalar) const
Overloaded operator+ to add a scalar to the matrix.
Matrix operator- (const T &scalar) const
Overloaded operator- to subtract a scalar from the matrix.
void swapRows (size_t row1, size_t row2)
Swaps two rows in the matrix.
Static Public Member Functions
static Matrix eye (size_t size)
Static function to get the identity matrix of a given size.
Protected Attributes
std::vector< std::vector< T > > data
2D vector representing the matrix data.
Friends
Matrix operator* (const T &scalar, const Matrix &m)
Friend function to overload the operator* for scalar * matrix.
std::ostream & operator<< (std::ostream &os, const Matrix &m)
Overloaded operator<< to print the matrix to an output stream.
Detailed Description
template<typename T = MyBLAS::NumericType>
class MyBLAS::Matrix< T >
Class representing a matrix of T type values.
Constructor & Destructor Documentation
Matrix() [1/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix () inline
Default constructor. Initializes an empty matrix.
              {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
~Matrix()
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::~Matrix () inline
Default destructor.
               {
         ResourceMonitor<Matrix<T>>::unregisterInstance(this);
     }
Matrix() [2/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (std::vector< std::vector< T >> & _data) inline explicit
Constructor that initializes the matrix with a given 2D vector.
Parameters
_data 2D vector to initialize the matrix with.
                                                     : data(_data) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
Matrix() [3/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (const std::vector< std::vector< T >> & _data) inline explicit
Const Constructor that initializes the matrix with a given 2D vector.
Parameters
_data 2D vector to initialize the matrix with.
                                                           : data(_data) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
Matrix() [4/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (std::vector< std::vector< T >> && _data) inline explicit
Constructor that initializes the matrix with a given 2D vector.
Parameters
_data 2D vector to initialize the matrix with.
                                                      : data(std::move(_data)) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
Matrix() [5/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (Matrix< T > && other) inline noexcept
Move constructor.
Parameters
other The matrix to move from.
                                     : data(std::move(other.data)) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
         // Remove the moved-from instance from the tracking set.
     }
Matrix() [6/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (const Matrix< T > & other) inline
Copy constructor.
Parameters
other The matrix to copy from.
                                 : data(other.data) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
Matrix() [7/11]
template<typename T = MyBLAS::NumericType> template<typename U > MyBLAS::Matrix< T >::Matrix (const Matrix< U > & other) inline explicit
Constructor that initializes the matrix with another matrix of a different type.
Parameters
other The matrix to initialize from.
{
         const size_t rows = other.getRows(), cols = other.getCols();
         data = std::vector<std::vector<T>>(rows, std::vector<T>(cols));
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 data[i][j] = static_cast<T>(other[i][j]);
             }
         }
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
Matrix() [8/11]
template<typename T = MyBLAS::NumericType> template<class MatrixType > MyBLAS::Matrix< T >::Matrix (MatrixType matrix) inline explicit
Constructor that initializes the matrix with another matrix.
Parameters
matrix The matrix to initialize from.
This constructor allows for initializing a Matrix from another Matrix or a compatible type.
{
         const size_t rows = matrix.getRows(), cols = matrix.getCols();
         data = std::vector<std::vector<T>>(rows, std::vector<T>(cols, 0));
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 data[i][j] = matrix[i][j];
             }
         }
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
Matrix() [9/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (size_t _rows, size_t _cols, const T _initial = 0) inline
Parameterized constructor that initializes the matrix with a given size and initial value.
Parameters
_rows Number of rows in the matrix.
_cols Number of columns in the matrix.
_initial Initial value for all elements in the matrix.
         : data(_rows, std::vector<T>(_cols, _initial)) {
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
Matrix() [10/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (std::initializer_list< std::initializer_list< T >> initList) inline
Constructor that initializes the matrix with a given initializer list.
Parameters
initList Initializer list to initialize the matrix with.
{
         data.resize(initList.size());
         size_t i = 0;
         for (const auto &row : initList) {
             data[i].resize(initList.begin()->size());
             size_t j = 0;
             for (const auto &elem : row) {
                 data[i][j] = elem;
                 ++j;
             }
             ++i;
         }
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
References MyBLAS::Matrix< T >::data, i, and process::row.
Matrix() [11/11]
template<typename T = MyBLAS::NumericType> MyBLAS::Matrix< T >::Matrix (size_t rows, size_t cols, std::function< T(size_t, size_t)> func) inline explicit
Constructor that initializes the matrix with a given size and a lambda function.
Parameters
rows Number of rows in the matrix.
cols Number of columns in the matrix.
func Lambda function to generate the elements of the matrix.
                                                                                    : data(rows, std::vector<T>(cols)) {
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 data[i][j] = func(i, j);
             }
         }
         ResourceMonitor<Matrix<T>>::registerInstance(this);
     }
References MyBLAS::Matrix< T >::data, and i.
Member Function Documentation
eye()
template<typename T = MyBLAS::NumericType> static Matrix MyBLAS::Matrix< T >::eye (size_t size) inline static
Static function to get the identity matrix of a given size.
Parameters
size Size of the identity matrix.
Returns
Identity matrix of the given size.
{
         Matrix eye(size, size, 0);
         for (size_t i = 0; i < size; ++i) {
             eye[i][i] = 1;
         }
         return eye;
     }
References i.
Referenced by Parser::buildInputs(), dooLittleFactorizeLUP(), factorizeLUwithPartialPivoting(), recursiveFactorizeLUP(), and MyBLAS::TYPED_TEST().
getAllocatedBytes()
template<typename T = MyBLAS::NumericType> size_t MyBLAS::Matrix< T >::getAllocatedBytes (bool actual = false) const inline
{
         auto nRows = actual ? data.size() : data.capacity();
         if (data.empty()) {
             return 0;
         }
         auto nCols = actual ? data[0].size() : data[0].capacity();
         assert(nRows >= getRows());
         assert(nCols >= getCols());
         size_t byteCount = 0;
         // count all the elements
         byteCount += (nRows * nCols) * (sizeof(T) > 0.0 ? sizeof(T) : 1);
         // count all the row containers
         byteCount += nRows * sizeof(std::vector<T>);
         // Memory used by this object itself.
         byteCount += sizeof(*this);
         return byteCount;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), and MyBLAS::Matrix< T >::getRows().
getCols()
template<typename T = MyBLAS::NumericType> size_t MyBLAS::Matrix< T >::getCols () const inline
Getter for the number of columns in the matrix.
Returns
Number of columns in the matrix.
{
         return data.empty() ? 0 : data[0].size();
     }
References MyBLAS::Matrix< T >::data.
Referenced by MyBLAS::Stats::abs(), MyBLAS::cast(), MyBLAS::LU::doolittleFactorize(), MyBLAS::doolittleFactorizeLU(), MyBLAS::LUP::dooLittleFactorizeLUP(), dooLittleFactorizeLUP(), MyBLAS::Matrix< T >::getAllocatedBytes(), MyBLAS::isEmptyMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isValidUpperTriangularMatrix(), MyBLAS::Matrix< T >::Matrix(), naive_solve_linear_system(), MyBLAS::Matrix< T >::operator()(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator/(), MyBLAS::Matrix< T >::operator==(), MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), MyBLAS::LU::recursiveLUFactorize(), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setCoefficients(), MyPhysics::Diffusion::Params< FloatType >::setSources(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), TEST_P(), and MyBLAS::TYPED_TEST().
getData() [1/2]
template<typename T = MyBLAS::NumericType> std::vector<std::vector<T> >& MyBLAS::Matrix< T >::getData () inline
Getter for the vector data.
Returns
reference to the vector data.
 { return data; }
References MyBLAS::Matrix< T >::data.
getData() [2/2]
template<typename T = MyBLAS::NumericType> const std::vector<std::vector<T> >& MyBLAS::Matrix< T >::getData () const inline
Getter for the matrix data.
Returns
Const reference to the matrix data.
 { return data; }
References MyBLAS::Matrix< T >::data.
Referenced by Input::serialize(), Input::toJSON(), MyBLAS::Input::toJSON(), and Map::toJSON().
getRows()
template<typename T = MyBLAS::NumericType> size_t MyBLAS::Matrix< T >::getRows () const inline
Getter for the number of rows in the matrix.
Returns
Number of rows in the matrix.
{
         return data.size();
     }
References MyBLAS::Matrix< T >::data.
Referenced by MyBLAS::Stats::abs(), MyBLAS::LUP::applyLUP(), MyRelaxationMethod::applyP2SOR(), MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applyPSOR(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySORBlockParallel(), MyRelaxationMethod::applySORSerial(), MyRelaxationMethod::applySSOR(), Parser::buildInputs(), MyBLAS::cast(), MyBLAS::LUP::factorize(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), factorizeLUwithPartialPivoting(), MyBLAS::Matrix< T >::getAllocatedBytes(), MyBLAS::haveEqualRank(), MyBLAS::isEmptyMatrix(), MyBLAS::isSquareMatrix(), MyBLAS::isValidUpperTriangularMatrix(), MyBLAS::makeDiagonallyDominant(), MyBLAS::Matrix< T >::Matrix(), MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), naive_solve_linear_system(), MyBLAS::Matrix< T >::operator()(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator/(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Matrix< T >::operator[](), MyBLAS::Solver::TemplatedParameters< MatrixType, VectorType, T >::setCoefficients(), MyPhysics::Diffusion::Params< FloatType >::setSources(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), MyBLAS::Matrix< T >::swapRows(), TEST_P(), and MyBLAS::TYPED_TEST().
operator()() [1/2]
template<typename T = MyBLAS::NumericType> T& MyBLAS::Matrix< T >::operator() (size_t row, size_t col) inline
Overloaded operator() to access individual elements of the matrix.
Parameters
row Row index of the element to access.
col Column index of the element to access.
Returns
Reference to the element at the given row and column.
{
         assert(row < getRows() && col < getCols());
         return data[row][col];
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and process::row.
operator()() [2/2]
template<typename T = MyBLAS::NumericType> const T& MyBLAS::Matrix< T >::operator() (size_t row, size_t col) const inline
Overloaded operator() const to access individual elements of the matrix.
Parameters
row Row index of the element to access.
col Column index of the element to access.
Returns
Reference to the element at the given row and column.
{
         assert(row < getRows() && col < getCols());
         return data[row][col];
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and process::row.
operator*() [1/5]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator* (const Matrix< T > & rhs) const inline
Overloaded operator* to multiply two matrices.
Parameters
rhs Matrix to multiply with the current matrix.
Returns
Resultant matrix after multiplication.
{
         assert(getCols() == rhs.getRows());
         const size_t my_rows = getRows(), my_cols = getCols();
         const size_t rhs_cols = rhs.getCols();
         Matrix result(my_rows, rhs_cols, 0);
         for (size_t i = 0; i < my_rows; ++i) {
             for (size_t j = 0; j < rhs_cols; ++j) {
                 for (size_t k = 0; k < my_cols; ++k) {
                     result[i][j] += this->data[i][k] * rhs.data[k][j];
                 }
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and k.
operator*() [2/5]
template<typename T = MyBLAS::NumericType> template<typename MatrixType1 , typename MatrixType2 > MatrixType1 MyBLAS::Matrix< T >::operator* (const MatrixType1 & rhs) const inline
Overloaded operator* to multiply two matrices, where one is of type MatrixType.
Parameters
rhs Matrix to multiply with the current matrix.
Returns
Resultant matrix after multiplication.
{
         assert(getCols() == rhs.getRows());
         const size_t my_rows = getRows(), my_cols = getCols();
         const size_t rhs_cols = rhs.getCols();
         MatrixType1 result(my_rows, rhs_cols, 0);
         for (size_t i = 0; i < my_rows; ++i) {
             for (size_t j = 0; j < rhs_cols; ++j) {
                 for (size_t k = 0; k < my_cols; ++k) {
                     result[i][j] += this->data[i][k] * rhs.data[k][j];
                 }
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and k.
operator*() [3/5]
template<typename T = MyBLAS::NumericType> template<typename MatrixType1 , typename MatrixType2 > MatrixType1 MyBLAS::Matrix< T >::operator* (const MatrixType2 & rhs) const inline
Overloaded operator* to multiply two matrices, where one is of type MatrixType.
Parameters
rhs Matrix to multiply with the current matrix.
Returns
Resultant matrix after multiplication.
{
         assert(getCols() == rhs.getRows());
         const size_t my_rows = getRows(), my_cols = getCols();
         const size_t rhs_cols = rhs.getCols();
         MatrixType1 result(my_rows, rhs_cols, 0);
         for (size_t i = 0; i < my_rows; ++i) {
             for (size_t j = 0; j < rhs_cols; ++j) {
                 for (size_t k = 0; k < my_cols; ++k) {
                     result[i][j] += this->data[i][k] * rhs.data[k][j];
                 }
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and k.
operator*() [4/5]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator* (const T & scalar) const inline
Overloaded operator* to multiply the matrix by a scalar.
Parameters
scalar Scalar to multiply the matrix with.
Returns
Resultant matrix after multiplication.
{
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] * scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator*() [5/5]
template<typename T = MyBLAS::NumericType> Vector<T> MyBLAS::Matrix< T >::operator* (const Vector< T > & rhs) const inline
Overloaded operator* to multiply a matrix with a vector.
Parameters
rhs Vector to multiply with the current matrix.
Returns
Resultant vector after multiplication.
{
         assert(getCols() == rhs.size());
         const size_t my_rows = getRows(), my_cols = getCols();
         Vector<T> result(my_rows, 0);
         for (size_t i = 0; i < my_rows; ++i) {
             for (size_t j = 0; j < my_cols; ++j) {
                 result[i] += this->data[i][j] * rhs[j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and MyBLAS::Vector< T >::size().
operator+() [1/2]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator+ (const Matrix< T > & rhs) const inline
Overloaded operator+ to add two matrices.
Parameters
rhs Matrix to add to the current matrix.
Returns
Resultant matrix after addition.
{
         assert(getRows() == rhs.getRows());
         assert(getCols() == rhs.getCols());
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] + rhs.data[i][j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator+() [2/2]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator+ (const T & scalar) const inline
Overloaded operator+ to add a scalar to the matrix.
Parameters
scalar Scalar to add to the matrix.
Returns
Resultant matrix after addition.
{
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] + scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator-() [1/2]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator- (const Matrix< T > & rhs) const inline
Overloaded operator- to subtract two matrices.
Parameters
rhs Matrix to subtract from the current matrix.
Returns
Resultant matrix after subtraction.
{
         assert(getRows() == rhs.getRows());
         assert(getCols() == rhs.getCols());
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] - rhs.data[i][j];
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator-() [2/2]
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator- (const T & scalar) const inline
Overloaded operator- to subtract a scalar from the matrix.
Parameters
scalar Scalar to subtract from the matrix.
Returns
Resultant matrix after subtraction.
{
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] - scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator/()
template<typename T = MyBLAS::NumericType> Matrix MyBLAS::Matrix< T >::operator/ (const T & scalar) const inline
Overloaded operator/ to divide the matrix by a scalar.
Parameters
scalar Scalar to divide the matrix by.
Returns
Resultant matrix after division.
{
         assert(scalar != 0);
         const size_t rows = getRows(), cols = getCols();
         Matrix result(rows, cols, 0);
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 result[i][j] = this->data[i][j] / scalar;
             }
         }
         return result;
     }
References MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator=() [1/2]
template<typename T = MyBLAS::NumericType> Matrix& MyBLAS::Matrix< T >::operator= (const Matrix< T > & other) inline
Copy assignment operator. Used to assign one Matrix to another after their initial construction.
Parameters
other The matrix to copy from.
{
         if (this != &other) {
             data = other.data;
             // Update the instances set
             // No need to update the instances set because 'this' already exists
         }
         return *this;
     }
References MyBLAS::Matrix< T >::data.
operator=() [2/2]
template<typename T = MyBLAS::NumericType> Matrix& MyBLAS::Matrix< T >::operator= (Matrix< T > && other) inline noexcept
Move assignment operator. This operator is used to transfer the ownership of resources from one Matrix to another without copying the data.
Parameters
other The matrix to copy from.
{
         if (this != &other) {
             data = std::move(other.data);
             // No need to update the instances set because 'this' already exists
             // don't erase the moved-from object from the instances set since we are only moving the content, not the
             // instance. Clear the data since we use instance.data to compute allocated memory
             other.data.clear();
         }
         return *this;
     }
References MyBLAS::Matrix< T >::data.
operator==()
template<typename T = MyBLAS::NumericType> bool MyBLAS::Matrix< T >::operator== (const Matrix< T > & rhs) const inline
Overloaded operator== to check for equality between two matrices.
Parameters
rhs Matrix to compare with the current matrix.
Returns
True if the matrices are equal, false otherwise.
Note
This operator checks for exact equality of each element in the matrices. However, when dealing with floating-point numbers, due to the way they are represented in computers, two numbers that are theoretically equal may not be exactly equal when represented in a computer. Therefore, when dealing with floating-point numbers, it might be more appropriate to check if the difference between the matrices is below a certain tolerance, rather than checking for exact equality.
{
         const size_t my_rows = getRows(), my_cols = getCols(), rhs_rows = rhs.getRows(), rhs_cols = rhs.getCols();
         if (my_rows != rhs_rows || my_cols != rhs_cols) {
             return false;
         }
         for (size_t i = 0; i < my_rows; ++i) {
             for (size_t j = 0; j < my_cols; ++j) {
                 if (this->data[i][j] != rhs.data[i][j]) {
                     return false;
                 }
             }
         }
         return true;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
operator[]() [1/2]
template<typename T = MyBLAS::NumericType> std::vector<T>& MyBLAS::Matrix< T >::operator[] (const size_t rowNum) inline
Overloaded operator[] to access individual rows of the matrix.
Parameters
rowNum Index of the row to access.
Returns
Reference to the row at the given index.
{
         assert(rowNum < getRows());
         return data[rowNum];
     }
References MyBLAS::Matrix< T >::data, and MyBLAS::Matrix< T >::getRows().
operator[]() [2/2]
template<typename T = MyBLAS::NumericType> const std::vector<T>& MyBLAS::Matrix< T >::operator[] (const size_t rowNum) const inline
Overloaded operator[] to access individual rows of the matrix (const version).
Parameters
rowNum Index of the row to access.
Returns
Const reference to the row at the given index.
{
         assert(rowNum < getRows());
         return data[rowNum];
     }
References MyBLAS::Matrix< T >::data, and MyBLAS::Matrix< T >::getRows().
push_back()
template<typename T = MyBLAS::NumericType> void MyBLAS::Matrix< T >::push_back (const std::vector< T > & row) inline
Adds a new row to the end of the matrix.
Parameters
row Vector representing the new row to be added.
{
         data.push_back(row);
     }
References MyBLAS::Matrix< T >::data, and process::row.
setSubMatrix()
template<typename T = MyBLAS::NumericType> void MyBLAS::Matrix< T >::setSubMatrix (size_t rowStart, size_t colStart, const Matrix< T > & subMatrix) inline
Sets a submatrix within the current matrix.
Parameters
rowStart Starting row index for the submatrix.
colStart Starting column index for the submatrix.
subMatrix The submatrix to set.
{
         const size_t subRows = subMatrix.getRows(), subCols = subMatrix.getCols();
         assert(rowStart + subRows <= getRows());
         assert(colStart + subCols <= getCols());
         for (size_t i = 0; i < subRows; ++i) {
             for (size_t j = 0; j < subCols; ++j) {
                 data[rowStart + i][colStart + j] = subMatrix[i][j];
             }
         }
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), i, and MyBLAS::Matrix< T >::subMatrix().
Referenced by MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), MyBLAS::LU::recursiveLUFactorize(), and MyBLAS::TYPED_TEST().
subMatrix()
template<typename T = MyBLAS::NumericType> Matrix<T> MyBLAS::Matrix< T >::subMatrix (size_t rowStart, size_t colStart, size_t subRows, size_t subCols) const inline
Extracts a submatrix from the current matrix.
Parameters
rowStart Starting row index for the submatrix.
colStart Starting column index for the submatrix.
subRows Number of rows in the submatrix.
subCols Number of columns in the submatrix.
Returns
The extracted submatrix.
{
         assert(rowStart + subRows <= getRows());
         assert(colStart + subCols <= getCols());
         Matrix<T> subMatrix(subRows, subCols, 0);
         for (size_t i = 0; i < subRows; ++i) {
             for (size_t j = 0; j < subCols; ++j) {
                 subMatrix[i][j] = data[rowStart + i][colStart + j];
             }
         }
         return subMatrix;
     }
References MyBLAS::Matrix< T >::data, MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getRows(), and i.
Referenced by MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), MyBLAS::LU::recursiveLUFactorize(), MyBLAS::Matrix< T >::setSubMatrix(), and MyBLAS::TYPED_TEST().
swapRows()
template<typename T = MyBLAS::NumericType> void MyBLAS::Matrix< T >::swapRows (size_t row1, size_t row2) inline
Swaps two rows in the matrix.
Parameters
row1 Index of the first row to swap.
row2 Index of the second row to swap.
{
         assert(row1 < getRows() && row2 < getRows());
         std::swap(data[row1], data[row2]);
     }
References MyBLAS::Matrix< T >::data, and MyBLAS::Matrix< T >::getRows().
Referenced by MyBLAS::LUP::dooLittleFactorizeLUP(), dooLittleFactorizeLUP(), MyBLAS::LUP::factorizeLUwithPartialPivoting(), factorizeLUwithPartialPivoting(), MyBLAS::LUP::recursiveFactorizeLUP(), recursiveFactorizeLUP(), and MyBLAS::TYPED_TEST().
Friends And Related Function Documentation
operator*
template<typename T = MyBLAS::NumericType> Matrix operator* (const T & scalar, const Matrix< T > & m) friend
Friend function to overload the operator* for scalar * matrix.
Parameters
scalar Scalar to multiply the matrix with.
m Matrix to be multiplied.
Returns
Resultant matrix after multiplication.
{
         return m * scalar;
     }
operator<<
template<typename T = MyBLAS::NumericType> std::ostream& operator<< (std::ostream & os, const Matrix< T > & m) friend
Overloaded operator<< to print the matrix to an output stream.
Parameters
os Output stream to print the matrix to.
m Matrix to print.
Returns
Reference to the output stream.
{
         const auto width = static_cast<int>(std::cout.precision() + static_cast<std::streamsize>(10));
         const size_t rows = m.getRows(), cols = m.getCols();
         for (size_t i = 0; i < rows; ++i) {
             for (size_t j = 0; j < cols; ++j) {
                 os << std::setw(width) << std::setfill(' ') << std::scientific << static_cast<long double>(m[i][j]);
             }
             os << '\n';
         }
         return os;
     }
Field Documentation
data
template<typename T = MyBLAS::NumericType> std::vector<std::vector<T> > MyBLAS::Matrix< T >::data protected
2D vector representing the matrix data.
Referenced by MyBLAS::Matrix< T >::getAllocatedBytes(), MyBLAS::Matrix< T >::getCols(), MyBLAS::Matrix< T >::getData(), MyBLAS::Matrix< T >::getRows(), MyBLAS::Matrix< T >::Matrix(), MyBLAS::Matrix< T >::operator()(), MyBLAS::Matrix< T >::operator*(), MyBLAS::Matrix< T >::operator+(), MyBLAS::Matrix< T >::operator-(), MyBLAS::Matrix< T >::operator=(), MyBLAS::Matrix< T >::operator==(), MyBLAS::Matrix< T >::operator[](), MyBLAS::Matrix< T >::push_back(), MyBLAS::Matrix< T >::setSubMatrix(), MyBLAS::Matrix< T >::subMatrix(), and MyBLAS::Matrix< T >::swapRows().
The documentation for this class was generated from the following file:
src/utils/math/blas/matrix/Matrix.h