NE591-008 C++17 Codebase: MyMath Namespace Reference
MyMath Namespace Reference
Functions
template<typename T >
bool isfinite (T value)
Check if a numeric value is finite.
template<>
bool isfinite (__float128 value)
Specialization for the __float128 type.
template<typename T >
T pow (T base, int exponent)
A template function to calculate the power of a base number.
template<>
__float128 pow (__float128 base, int exponent)
A template specialization function to calculate the power of a __float128 base number.
template<typename T >
T abs (T x)
A template function to calculate the absolute value of a number.
Function Documentation
abs()
template<typename T > T MyMath::abs (T x)
A template function to calculate the absolute value of a number.
Template Parameters
T The type of the number.
Parameters
x The number whose absolute value is to be calculated.
Returns
The absolute value of the number.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
            {
     return x < 0 ? -x : x;
 }
References x.
Referenced by printJuliaSet().
isfinite() [1/2]
template<> bool MyMath::isfinite (__float128 value)
Specialization for the __float128 type.
This specialization of the isfinite function is specifically designed to handle the __float128 type. It checks whether the given __float128 value is within the range of finite values for this type.
Parameters
value The __float128 value to check for finiteness.
Returns
true if the value is finite, false otherwise.
{
     // Check if value is within the range of finite values for __float128
     return (value > -__float128(INFINITY) && value < __float128(INFINITY));
 }
Referenced by isfinite().
isfinite() [2/2]
template<typename T > bool MyMath::isfinite (T value)
Check if a numeric value is finite.
This function checks whether a given numeric value is finite. For most numeric types, it delegates to the standard library's std::isfinite function. However, it has a specialization for the __float128 type to handle its specific finiteness criteria.
Template Parameters
T The type of the numeric value to check for finiteness.
Parameters
value The numeric value to check.
Returns
true if the value is finite, false otherwise.
{
     return std::isfinite(value);
 }
References isfinite().
Referenced by MyPhysics::Diffusion::Params< FloatType >::setA(), MyPhysics::Diffusion::Params< FloatType >::setB(), MyPhysics::Diffusion::Params< FloatType >::setDiffusionCoefficient(), and MyPhysics::Diffusion::Params< FloatType >::setMacroscopicRemovalCrossSection().
pow() [1/2]
template<> __float128 MyMath::pow (__float128 base, int exponent)
A template specialization function to calculate the power of a __float128 base number.
This function uses a custom algorithm to calculate the power of a __float128 base number.
Parameters
base The base number.
exponent The exponent to which the base number is raised.
Returns
The result of the base number raised to the exponent.
{
     if (exponent == 0)
         return 1.0;
     if (exponent == 1)
         return base;
     __float128 result = 1.0;
     bool isNegativeExponent = exponent < 0;
     exponent = isNegativeExponent ? -exponent : exponent;
     __float128 current = base;
     while (exponent > 0) {
         if (exponent % 2 == 1) {
             result *= current;
         }
         current = current * current;
         exponent /= 2;
     }
     return isNegativeExponent ? 1.0 / result : result;
 }
Referenced by pow().
pow() [2/2]
template<typename T > T MyMath::pow (T base, int exponent)
A template function to calculate the power of a base number.
This function uses the std::pow function to calculate the power of a base number.
Template Parameters
T The type of the base number.
Parameters
base The base number.
exponent The exponent to which the base number is raised.
Returns
The result of the base number raised to the exponent.
{
     return std::pow(base, exponent);
 }
References pow().
Referenced by MyRelaxationMethod::applyPointJacobi(), MyRelaxationMethod::applySOR(), MyRelaxationMethod::applySSOR(), MyRelaxationMethod::approximateOptimalRelaxationFactor(), MyPhysics::Diffusion::Constants< T >::compute(), getGaussLegendreWeight(), getLegendrePolynomialDerivative(), MyBLAS::L2(), my_naive_sin(), my_sisd_sin(), MyBLAS::norm(), Compute::seriesSum(), MyBLAS::TEST_F(), and MyBLAS::TYPED_TEST().