NE591-008 C++17 Codebase: process Namespace Reference
process Namespace Reference
Functions
def read_json_files (directory="../results/circuit_matrix")
Variables
def data = read_json_files()
dataframe = pd.DataFrame()
inputs = item['inputs']
order = item['inputs']['order']
lup_error = item['outputs']['LUP']['l2-error']
lup_residual = item['outputs']['LUP']['max-residual']
row = dict()
line = pd.Series(row)
grouped = dataframe.groupby('method')
LUP = grouped.get_group('LUP')
PJ = grouped.get_group('point-jacobi')
SORJ = grouped.get_group('SORJ')
GS = grouped.get_group('gauss-seidel')
SOR = grouped.get_group('SOR')
SSOR = grouped.get_group('SSOR')
Function Documentation
read_json_files()
def process.read_json_files (directory = "../results/circuit_matrix")
 def read_json_files(directory="../results/circuit_matrix"):
     json_files = [pos_json for pos_json in os.listdir(directory) if pos_json.endswith('.json')]
     json_data = []
     for index, js in enumerate(json_files):
         with open(os.path.join(directory, js)) as json_file:
             json_data.append(json.load(json_file))
     return json_data
Variable Documentation
data
def process.data = read_json_files()
dataframe
process.dataframe = pd.DataFrame()
grouped
process.grouped = dataframe.groupby('method')
GS
process.GS = grouped.get_group('gauss-seidel')
inputs
process.inputs = item['inputs']
Referenced by calculate_mesh_spacings(), fill_fluxes(), fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), MPIProject< InputType, CommandLineParserType, OutputType >.initialize(), naive_fill_diffusion_matrix_and_vector(), Compute.naive_fill_diffusion_vector(), InLab2.run(), InLab3.run(), OutLab3.run(), InLab6.run(), InLab5.run(), OutLab4.run(), OutLab6.run(), OutLab7.run(), InLab4.run(), OutLab5.run(), Project1.run(), Project2.run(), MPIProject< InputType, CommandLineParserType, OutputType >.sendInputs(), Compute.usingGaussSeidel(), Compute.usingJacobiSOR(), Compute.usingLUP(), Compute.usingPointJacobi(), Compute.usingSOR(), and Compute.usingSymmetricSOR().
line
process.line = pd.Series(row)
Referenced by readCSV(), and readCSVRowWiseNoHeaders().
LUP
process.LUP = grouped.get_group('LUP')
lup_error
process.lup_error = item['outputs']['LUP']['l2-error']
lup_residual
process.lup_residual = item['outputs']['LUP']['max-residual']
order
process.order = item['inputs']['order']
PJ
process.PJ = grouped.get_group('point-jacobi')
row
process.row = dict()
Referenced by MyRelaxationMethod.applyPointJacobi(), MyRelaxationMethod.applySOR(), MyRelaxationMethod.applySSOR(), Random.binary(), MyBLAS.cast(), MyBLAS.forwardSubstitution(), Random.generate(), MyBLAS.innerProduct(), MyBLAS.makeDiagonallyDominant(), MyBLAS::Matrix< T >.Matrix(), MyBLAS::Matrix< T >.operator()(), MyBLAS::LazyMatrix< DataType >.operator()(), MyBLAS::LazyMatrix< DataType >.operator[](), MyBLAS::Matrix< T >.push_back(), readCSVRowWiseNoHeaders(), and TYPED_TEST().
SOR
process.SOR = grouped.get_group('SOR')
SORJ
process.SORJ = grouped.get_group('SORJ')
SSOR
process.SSOR = grouped.get_group('SSOR')