NE591-008 C++17 Codebase: OutLab5 Class Reference
OutLab5 Class Reference
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
#include <outlab5.h>
Public Member Functions
OutLab5 (CommandLineArgs args)
Constructor for the outlab5 class.
void execute ()
Executes the project.
Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
This function builds the header information for the project.
void run (Results &outputs, InputMatrices &inputs, boost::program_options::variables_map &values) override
This function runs the project.
virtual void preRun (Results &output, InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (Results &output, InputMatrices &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
Private Member Functions
void initialize ()
Initializes the project.
void timedRun ()
Executes the project and measures the execution time.
Private Attributes
CommandLineArgs cmdArgs
Parser terminal
Results outputs
Detailed Description
This class is a child of the Project class and is used to solve a system of linear equations using forward and back substitution.
The class takes in command line arguments and uses them to solve the system of equations.
Constructor & Destructor Documentation
OutLab5()
OutLab5::OutLab5 (CommandLineArgs args) inline explicit
Constructor for the outlab5 class.
Parameters
args Command line arguments
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab5::buildHeaderInfo () inline override protected virtual
This function builds the header information for the project.
Returns
HeaderInfo object containing project information
Implements Project< InputMatrices, Parser, Results >.
{
         Canvas canvas;
         auto x = -0.03;
         auto y = 0.77;
         auto iterations = 337;
         canvas.x_start = -0.396934597844;
         canvas.x_stop = -0.085211129213;
         canvas.y_start = 0.414181225609;
         canvas.y_stop = 0.632387653651;
         canvas.tone_map.growth_rate = 0.25;
         printJuliaSet<__float128>(canvas, x, y, iterations); //"o█■"
         std::cout << "Julia set at (" << x << "," << y << "), " << iterations << " iterations\n";
         return {
             .ProjectName = "NE591: OutLab 05",
             .ProjectDescription = "Solving a system of linear equations using LUP factorization",
             .SubmissionDate = "09/29/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = " ",
         };
     }
References CanvasType< T >::tone_map, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, and CanvasType< T >::y_stop.
execute()
void Project< InputMatrices , Parser , Results >::execute () inline inherited
Executes the project.
                    {
         initialize();
         timedRun();
     }
getTerminal()
Parser Project< InputMatrices , Parser , Results >::getTerminal () const inline inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
void Project< InputMatrices , Parser , Results >::initialize () inline private inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< InputMatrices , Parser , Results >::postRun (Results & output, InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< InputMatrices , Parser , Results >::preRun (Results & output, InputMatrices & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void OutLab5::run (Results & outputs, InputMatrices & inputs, boost::program_options::variables_map & values) inline override protected virtual
This function runs the project.
It solves the system of linear equations using forward and back substitution.
Parameters
outputs The output vector
inputs The input matrices
values The variable map
Given the matrix A = LU and vector b, solve Ax = b, which is LUx = b.
Perform row pivoting on A to obtain a permuted matrix PA = LU, where P is a permutation matrix.
Let y = Ux. Now, we have two systems of linear equations: Ly = Pb and Ux = y.
Solve the first system Ly = Pb using forward substitution.
Solve the second system Ux = y using backward substitution.
Implements Project< InputMatrices, Parser, Results >.
{
         /**
             1. Given the matrix A = LU and vector b, solve Ax = b, which is LUx = b.
             2. Perform row pivoting on A to obtain a permuted matrix PA = LU, where P is a permutation matrix.
             3. Let y = Ux. Now, we have two systems of linear equations: Ly = Pb and Ux = y.
             4. Solve the first system Ly = Pb using forward substitution.
             5. Solve the second system Ux = y using backward substitution.
         **/
         nlohmann::json results;
         inputs.toJSON(results["inputs"]);
         const auto A = inputs.coefficients;
         auto L = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
         auto U = MyBLAS::Matrix(A.getRows(), A.getCols(), static_cast<long double>(0));
         const auto pivot = !values.count("no-pivoting");
         const bool alternateMethod = values.count("alternate-method") != 0;
         MyBLAS::Matrix<long double> P;
         if (pivot) {
             if (alternateMethod) {
                 P = MyBLAS::cast<long double, bool>(MyBLAS::cast<bool, long double>(dooLittleFactorizeLUP(L, U, A)));
             } else {
                 P = MyBLAS::cast<long double, bool>(
                     MyBLAS::cast<bool, long double>(factorizeLUwithPartialPivoting(L, U, A)));
             }
         } else {
             MyBLAS::LU::factorize(L, U, A);
         }
         if (!MyBLAS::isUnitLowerTriangularMatrix(L)) {
             std::cerr << "Warning: Factorized matrix L is not unit lower triangular, expect undefined behavior.\n";
         }
         if (!MyBLAS::isUpperTriangularMatrix(U)) {
             std::cerr << "Warning: Factorized matrix U is not upper triangular, expect undefined behavior.\n";
         }
         if (pivot) {
             if (!MyBLAS::isPermutationMatrix(P)) {
                 std::cerr << "Warning: Generated matrix P is not a permutation matrix, expect undefined behavior.\n";
             }
         }
         IntermediateResults intermediates;
         intermediates.L = L;
         intermediates.U = U;
         if (pivot) {
             intermediates.P = P;
         }
         intermediates.toJSON(results["intermediates"]);
         const auto b = inputs.constants;
         const auto Pb = pivot ? (P * b) : b;
         const MyBLAS::Vector y = MyBLAS::forwardSubstitution<long double>(L, Pb);
         const MyBLAS::Vector x = MyBLAS::backwardSubstitution<long double>(U, y);
         outputs.solution = x;
         const auto b_prime = A * x;
         const auto r = b - b_prime;
         outputs.residual = r;
         const auto maxResidual = MyBLAS::max<long double>(MyBLAS::abs(r));
         outputs.max_residual = maxResidual;
         outputs.toJSON(results["outputs"]);
         if (!values.count("quiet")) {
             const auto precision = getTerminal().getCurrentPrecision();
             Parser::printLine();
             std::cout << "Lower Triangular Matrix (L):\n";
             Parser::printLine();
             std::cout << std::scientific << std::setprecision(precision) << L;
             Parser::printLine();
             std::cout << "Upper Triangular Matrix (U):\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << U;
             Parser::printLine();
             if (pivot) {
                 std::cout << "Permutation Matrix (P):\n";
                 Parser::printLine();
                 std::cout << std::setprecision(precision) << P;
                 Parser::printLine();
                 std::cout << "Permuted constants (Pb = P * b):\n";
                 Parser::printLine();
                 std::cout << std::setprecision(precision) << Pb;
                 Parser::printLine();
             }
             std::cout << "Intermediate vector (y), where (Ly = " << (pivot ? "Pb" : "b") << "):\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << y;
             Parser::printLine();
             std::cout << "Solution vector (x), where (Ux = y):\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << x;
             Parser::printLine();
             std::cout << "Residual vector (r = b - Ax) :\n";
             Parser::printLine();
             std::cout << std::setprecision(precision) << r;
             Parser::printLine();
             std::cout << "Max Residual abs(r): ";
             std::cout << std::setprecision(max_precision) << maxResidual << std::endl;
             Parser::printLine();
         }
         writeJSON(values["output-json"].as<std::string>(), results);
     }
References MyBLAS::abs(), dooLittleFactorizeLUP(), MyBLAS::LU::factorize(), factorizeLUwithPartialPivoting(), CommandLine< InputType >::getCurrentPrecision(), Project< InputMatrices, Parser, Results >::getTerminal(), process::inputs, MyBLAS::isPermutationMatrix(), MyBLAS::isUnitLowerTriangularMatrix(), MyBLAS::isUpperTriangularMatrix(), L(), Map::L, max_precision, Output::max_residual, Project< InputMatrices, Parser, Results >::outputs, Map::P, CommandLine< InLab6Inputs >::printLine(), Output::residual, Output::solution, Output::toJSON(), Map::toJSON(), Map::U, writeJSON(), x, and y.
timedRun()
void Project< InputMatrices , Parser , Results >::timedRun () inline private inherited
Executes the project and measures the execution time.
 { run(outputs, terminal.getInputs(), terminal.getArguments()); }
Field Documentation
cmdArgs
CommandLineArgs Project< InputMatrices , Parser , Results >::cmdArgs private inherited
outputs
Results Project< InputMatrices , Parser , Results >::outputs private inherited
terminal
Parser Project< InputMatrices , Parser , Results >::terminal private inherited
The documentation for this class was generated from the following file:
src/labs/outlab5/outlab5.h