NE591-008 C++17 Codebase: Output Struct Reference
Output Struct Reference
Struct to hold variables for Taylor Series.
#include <Compute.h>
Public Member Functions
void toJSON (nlohmann::json &jsonMap)
Output ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the output vector to a JSON object.
Output (InLab6Inputs inputMatrices)
Output ()=default
long double getMaxResidual () const
Calculates the maximum residual of the solution.
void toJSON (nlohmann::json &jsonMap) const
Converts the output parameters to a JSON object.
void toJSON (nlohmann::json &jsonMap)
Output ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the output vector to a JSON object.
Output (OutLab6Inputs inputMatrices)
Output ()=default
long double getSolutionError () const
Calculates and returns the error of the solution.
void toJSON (nlohmann::json &jsonMap) const
Converts the output parameters to a JSON object.
Output ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the output vector to a JSON object.
Output ()=default
Output (SolverInputs inputMatrices)
long double max_residual () const
void toJSON (nlohmann::json &jsonMap) const
Converts the output parameters to a JSON object.
Data Fields
long double running_sum
The running sum of the series.
Factorial computed_factorial
The computed factorial.
long double previous_factorial
The previous factorial.
long double current_threshold
The current threshold.
long double target_threshold
The target threshold.
long double x
The x value.
size_t n
The current iteration.
size_t N
The maximum number of iterations.
long double h
long double integral
MyBLAS::Vector< long double > solution
Output vector.
InLab6Inputs inputs
MyLinearSolvingMethod::Solution< long double > solution
long double execution_time = 0
MyBLAS::Vector< long double > residual
long double max_residual = 0
OutLab6Inputs inputs
long double mean_execution_time = std::numeric_limits<long double>::quiet_NaN()
long double stddev_execution_time = std::numeric_limits<long double>::quiet_NaN()
size_t runs = 0
MyBLAS::Matrix< long double > fluxes
SolverInputs inputs
Detailed Description
Struct to hold variables for Taylor Series.
Struct representing the output vector for the BLAS library.
A structure to hold the output of the relaxation method.
Struct representing the output parameters for the Newton-Cotes integration methods.
This structure contains the input parameters, the solution, and the execution time.
Constructor & Destructor Documentation
Output() [1/9]
Output::Output () default
Output() [2/9]
Output::Output (InLab6Inputs inputMatrices) inline explicit
 { inputs = inputMatrices; };
References inputs.
Output() [3/9]
Output::Output () default
Output() [4/9]
Output::Output () default
Output() [5/9]
Output::Output (OutLab6Inputs inputMatrices) inline explicit
 { inputs = inputMatrices; };
References inputs.
Output() [6/9]
Output::Output () default
Output() [7/9]
Output::Output () default
Output() [8/9]
Output::Output () default
Output() [9/9]
Output::Output (SolverInputs inputMatrices) inline explicit
 { inputs = std::move(inputMatrices); };
References inputs.
Member Function Documentation
getMaxResidual()
long double Output::getMaxResidual () const inline
Calculates the maximum residual of the solution.
Returns
The maximum residual of the solution.
{
         const auto b_prime = inputs.coefficients * solution.x;
         return MyBLAS::Stats::max<long double>(MyBLAS::Stats::abs(inputs.constants - b_prime));
     }
References MyBLAS::Stats::abs(), Input::coefficients, Input::constants, inputs, and solution.
Referenced by InLab6::printResults(), and toJSON().
getSolutionError()
long double Output::getSolutionError () const inline
Calculates and returns the error of the solution.
This function calculates the error of the solution by comparing it with the known solution. The error is calculated using the L2 Norm (Euclidean Norm) and then taking the square root of the result.
Returns
The error of the solution as a long double.
{
         return std::sqrt(MyBLAS::L2Norm(solution.x, inputs.known_solution));
     }
References inputs, Input::known_solution, MyBLAS::L2Norm(), and solution.
Referenced by OutLab6::printResults(), and toJSON().
max_residual()
long double Output::max_residual () const inline
{
         return MyBLAS::Stats::max<long double>(MyBLAS::Stats::abs(residual));
     }
References MyBLAS::Stats::abs(), and residual.
toJSON() [1/8]
void Output::toJSON (nlohmann::json & jsonMap) inline
{
         jsonMap["h"] = h;
         jsonMap["integral"] = integral;
     }
References h, and integral.
Referenced by InLab3::run(), OutLab3::run(), InLab6::run(), OutLab6::run(), InLab4::run(), OutLab5::run(), Project1::run(), and Project2::run().
toJSON() [2/8]
void Output::toJSON (nlohmann::json & jsonMap) inline
{
         jsonMap["h"] = h;
         jsonMap["integral"] = integral;
     }
References h, and integral.
toJSON() [3/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output vector to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the output vector.
 { jsonMap["solution"] = solution.getData(); }
References MyBLAS::Vector< T >::getData(), and solution.
toJSON() [4/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output parameters to a JSON object.
Parameters
jsonMap The JSON object to which the output parameters are added.
{
         jsonMap["converged"] = solution.converged;
         jsonMap["iterations"]["maximum"] = inputs.max_iterations;
         jsonMap["iterations"]["actual"] = solution.iterations;
         jsonMap["iterative-error"]["maximum"] = inputs.threshold;
         jsonMap["iterative-error"]["actual"] = solution.iterative_error;
         jsonMap["solution"] = solution.x.getData();
         jsonMap["max-residual"] = getMaxResidual();
         jsonMap["execution-time-ns"] = execution_time;
     }
References execution_time, MyBLAS::Vector< T >::getData(), getMaxResidual(), inputs, Input::max_iterations, solution, and Input::threshold.
toJSON() [5/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output vector to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the output vector.
{
         jsonMap["solution"] = solution.getData();
         jsonMap["residual"] = residual.getData();
         jsonMap["max-residual"] = MyBLAS::Stats::max<long double>(MyBLAS::Stats::abs(residual));
     }
References MyBLAS::Stats::abs(), MyBLAS::Vector< T >::getData(), residual, and solution.
toJSON() [6/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output parameters to a JSON object.
Parameters
jsonMap The JSON object to which the output parameters are added.
{
         jsonMap["converged"] = solution.converged;
         jsonMap["iterations"]["maximum"] = inputs.input.max_iterations;
         jsonMap["iterations"]["actual"] = solution.iterations;
         jsonMap["iterative-error"]["maximum"] = inputs.input.threshold;
         jsonMap["iterative-error"]["actual"] = solution.iterative_error;
         jsonMap["solution"] = solution.x.getData();
         jsonMap["max-residual"] = solution.getMaxResidual(inputs.input.coefficients, inputs.input.constants);
         jsonMap["l2-error"] = getSolutionError();
         jsonMap["wall-time-ns"]["mean"] = mean_execution_time;
         jsonMap["wall-time-ns"]["std"] = stddev_execution_time;
         jsonMap["wall-time-ns"]["samples"] = 10;
     }
References MyLinearSolvingMethod::Parameters< T >::coefficients, MyLinearSolvingMethod::Parameters< T >::constants, MyBLAS::Vector< T >::getData(), getSolutionError(), Input::input, inputs, MyLinearSolvingMethod::Parameters< T >::max_iterations, mean_execution_time, solution, stddev_execution_time, and MyLinearSolvingMethod::Parameters< T >::threshold.
toJSON() [7/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output vector to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the output vector.
{
         jsonMap["solution"] = solution.getData();
         jsonMap["residual"] = residual.getData();
         jsonMap["max-residual"] = MyBLAS::Stats::max<long double>(MyBLAS::Stats::abs(residual));
     }
References MyBLAS::Stats::abs(), MyBLAS::Vector< T >::getData(), residual, and solution.
toJSON() [8/8]
void Output::toJSON (nlohmann::json & jsonMap) const inline
Converts the output parameters to a JSON object.
Parameters
jsonMap The JSON object to which the output parameters are added.
{
         jsonMap["converged"] = solution.converged;
         jsonMap["iterations"]["maximum"] = inputs.solverParams.max_iterations;
         jsonMap["iterations"]["actual"] = solution.iterations;
         jsonMap["iterative-error"]["maximum"] = inputs.solverParams.threshold;
         jsonMap["iterative-error"]["actual"] = solution.iterative_error;
         jsonMap["solution"] = solution.x.getData();
         jsonMap["residual"] = residual.getData();
         jsonMap["max-residual"] = max_residual();
         // if LUP is used
         // jsonMap["l2-error"] = getSolutionError();
         jsonMap["wall-time-ns"]["mean"] = mean_execution_time;
         jsonMap["wall-time-ns"]["std"] = stddev_execution_time;
         jsonMap["wall-time-ns"]["samples"] = 10;
     }
References MyBLAS::Vector< T >::getData(), inputs, MyLinearSolvingMethod::Parameters< T >::max_iterations, max_residual, mean_execution_time, residual, solution, Input::solverParams, stddev_execution_time, and MyLinearSolvingMethod::Parameters< T >::threshold.
Field Documentation
computed_factorial
Factorial Output::computed_factorial
The computed factorial.
current_threshold
long double Output::current_threshold
The current threshold.
Referenced by my_sin(), my_sisd_sin(), and InLab1::run().
execution_time
long double Output::execution_time = 0
Referenced by InLab6::printResults(), toJSON(), and Compute::usingPointJacobi().
fluxes
MyBLAS::Matrix< long double > Output::fluxes
Referenced by fill_fluxes(), Compute::fill_fluxes(), Project1::run(), Project2::run(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
h
long double Output::h
Referenced by fillUsingSimpsons(), fillUsingTrapezoidal(), and toJSON().
inputs [1/3]
InLab6Inputs Output::inputs
Referenced by Compute::fill_fluxes(), getMaxResidual(), getSolutionError(), Output(), OutLab6::printResults(), Project2::printResults(), and toJSON().
inputs [2/3]
OutLab6Inputs Output::inputs
inputs [3/3]
SolverInputs Output::inputs
integral
long double Output::integral
Referenced by fillUsingGaussianQuadratures(), fillUsingSimpsons(), fillUsingTrapezoidal(), InLab3::run(), OutLab3::run(), and toJSON().
max_residual
long double Output::max_residual = 0
Referenced by Project2::printResults(), OutLab5::run(), and toJSON().
mean_execution_time
long double Output::mean_execution_time = std::numeric_limits<long double>::quiet_NaN()
Referenced by OutLab6::printResults(), Project2::printResults(), toJSON(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
n
size_t Output::n
The current iteration.
Referenced by my_sin(), my_sisd_sin(), and InLab1::run().
N
size_t Output::N
The maximum number of iterations.
Referenced by my_sin(), and my_sisd_sin().
previous_factorial
long double Output::previous_factorial
The previous factorial.
Referenced by my_sin().
residual
MyBLAS::Vector< long double > Output::residual
Referenced by max_residual(), OutLab5::run(), Project1::run(), toJSON(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
running_sum
long double Output::running_sum
The running sum of the series.
Referenced by my_sin(), and my_sisd_sin().
runs
size_t Output::runs = 0
Referenced by Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
solution [1/2]
MyLinearSolvingMethod::Solution< long double > Output::solution
Output vector.
Referenced by Compute::fill_fluxes(), getMaxResidual(), getSolutionError(), InLab6::printResults(), OutLab6::printResults(), Project2::printResults(), InLab4::run(), OutLab5::run(), Project1::run(), toJSON(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
solution [2/2]
MyLinearSolvingMethod::Solution<long double> Output::solution
stddev_execution_time
long double Output::stddev_execution_time = std::numeric_limits<long double>::quiet_NaN()
Referenced by OutLab6::printResults(), Project2::printResults(), toJSON(), Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingPointJacobi(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
target_threshold
long double Output::target_threshold
The target threshold.
Referenced by my_sin(), and my_sisd_sin().
x
long double Output::x
The x value.
Referenced by my_sin(), and my_sisd_sin().
The documentation for this struct was generated from the following files:
src/labs/inlab1/Compute.h
src/labs/inlab3/InputsOutputs.h