NE591-008 C++17 Codebase: src/utils/Helpers.h File Reference
Helpers.h File Reference
This file contains helper functions and structures used throughout the program.
#include <iomanip>
#include <iostream>
#include <limits>
#include "json.hpp"
#include <boost/program_options.hpp>
#include <boost/accumulators/accumulators.hpp>
#include <boost/accumulators/statistics.hpp>
Data Structures
struct ToneMap< T >
A template structure for ToneMap.
struct CanvasType< T >
A struct representing the properties of a canvas for rendering ANSI characters.
Typedefs
typedef CanvasType< __float128 > Canvas
typedef boost::accumulators::tag::mean mean
typedef boost::accumulators::tag::variance variance
Functions
template<class T >
void replace (std::map< std::string, boost::program_options::variable_value > &vm, const std::string &opt, const T &val)
This function replaces the value of a specified option in a map with a new value.
template<typename T >
void syncMapKeys (std::string &key, nlohmann::json &inputMap, boost::program_options::variables_map &map)
Synchronizes the values of a given key between a JSON object and a Boost variables_map object.
template<typename T >
void fill_linspace (std::vector< T > &result, T start, T end, size_t count)
This function fills a vector with evenly spaced values between a start and end value.
template<typename T >
static T scale (T value, T old_min, T old_max, T new_min, T new_max)
Scales a value from one range to another.
template<typename T >
size_t juliaSetIterations (const std::complex< T > &z0, const std::complex< T > &c, size_t max_iterations)
Calculates the number of iterations for a given point in the Julia set.
static std::vector< std::string > getGrays256bitANSI (double scaling_factor=1e-7, double growth_rate=0.3)
Generates a vector of 256-bit ANSI gray shades.
static std::vector< std::string > getHSV256bitANSI ()
Generates a vector of 256-bit ANSI HSV colors.
template<typename T >
void printJuliaSet (const Canvas &canvas, const T x0, const T y0, const size_t max_iterations=120)
Prints the Julia set to the console using the specified canvas properties.
template<typename T >
boost::accumulators::accumulator_set< T, boost::accumulators::features< mean, variance > > computeMeanStd (const std::vector< T > &numbers)
Computes the mean and variance of a numeric vector using Boost Accumulators.
template<typename T >
std::string formatMeanStd (T mean, T std)
template<typename Container >
bool contains (const Container &container, const typename Container::value_type &value)
Detailed Description
This file contains helper functions and structures used throughout the program.
Author
Arjun Earthperson
Date
08/30/2023
Definition in file Helpers.h.
Data Structure Documentation
ToneMap
struct ToneMap
template<typename T>
struct ToneMap< T >
A template structure for ToneMap.
This structure is used to map tones using a scaling factor and a growth rate. It is a template structure, so it can be used with any data type.
Template Parameters
T This is the type of the scaling factor and the growth rate. It can be any type that supports assignment and arithmetic operations.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Data Fields
T growth_rate The growth rate for the tone map.
This is the rate at which the tone map grows. It is initialized to a moderate value (0.3) to allow for a reasonable growth rate.
T scaling_factor The scaling factor for the tone map.
This is the factor by which the input tone will be scaled. It is initialized to a very small value (1e-7) to prevent large initial tones.
CanvasType
struct CanvasType
template<typename T>
struct CanvasType< T >
A struct representing the properties of a canvas for rendering ANSI characters.
Template Parameters
T The type of the numbers used for the canvas dimensions and properties.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Data Fields
string character
T contrast
size_t height
ToneMap< T > tone_map
size_t width
T x_start
T x_stop
T y_start
T y_stop
Typedef Documentation
Canvas
typedef CanvasType<__float128> Canvas
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
mean
typedef boost::accumulators::tag::mean mean
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
variance
typedef boost::accumulators::tag::variance variance
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
Function Documentation
computeMeanStd()
template<typename T > boost::accumulators::accumulator_set<T, boost::accumulators::features<mean, variance> > computeMeanStd (const std::vector< T > & numbers)
Computes the mean and variance of a numeric vector using Boost Accumulators.
This function calculates the mean and variance of a given numeric vector using Boost Accumulators library. It returns an accumulator set pre-configured with mean and variance tags.
Template Parameters
T The data type of the numeric vector elements.
Parameters
numbers The input numeric vector for which to compute the mean and variance.
Returns
An accumulator set containing computed mean and variance.
Note
To obtain the actual mean and variance values, you can use the boost::accumulators::mean and boost::accumulators::variance functions on the returned accumulator set, respectively. For example:
boost::accumulators::accumulator_set<T, boost::accumulators::features<mean, variance>> acc = computeMeanStd(numbers);
double mean = boost::accumulators::mean(acc);
double variance = boost::accumulators::variance(acc);
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     boost::accumulators::accumulator_set<T, boost::accumulators::features<mean, variance>> accumulator;
     // Iterate through the elements of the input vector and add them to the accumulator.
     for (T number : numbers) {
         accumulator(number);
     }
     return accumulator;
 }
Referenced by Compute::usingGaussSeidel(), Compute::usingJacobiSOR(), Compute::usingLUP(), Compute::usingSOR(), and Compute::usingSymmetricSOR().
contains()
template<typename Container > bool contains (const Container & container, const typename Container::value_type & value)
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     return std::find(container.begin(), container.end(), value) != container.end();
 }
Referenced by Parser::performInputArgumentsCheck().
fill_linspace()
template<typename T > void fill_linspace (std::vector< T > & result, T start, T end, size_t count)
This function fills a vector with evenly spaced values between a start and end value.
Template Parameters
T The type of the values to be generated.
Parameters
result The vector to be filled with the generated values.
start The start value of the range.
end The end value of the range.
count The number of values to be generated.
Note
This function uses the std::generate function to generate the values.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     result.reserve(count);
     if (count <= 1) {
         result.clear();
         result[0] = start;
         return;
     }
     T step = (end - start) / static_cast<T>(count - 1);
     std::generate(result.begin(), result.end(), [&start, step]() mutable {
         T value = start;
         start += step;
         return value;
     });
 }
References Random::generate().
Referenced by getGrays256bitANSI(), and InLab2::run().
formatMeanStd()
template<typename T > std::string formatMeanStd (T mean, T std) inline
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     return std::to_string(mean) + " ± " + std::to_string(std);
 }
References MyBLAS::Stats::std().
Referenced by OutLab6::printResults(), and Project2::printResults().
getGrays256bitANSI()
static std::vector<std::string> getGrays256bitANSI (double scaling_factor = 1e-7, double growth_rate = 0.3) static
Generates a vector of 256-bit ANSI gray shades.
Returns
A vector of ANSI escape codes representing gray shades.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     const long double x_min = 232;
     const long double x_max = 255;
     auto x = std::vector<long double>(26);
     fill_linspace(x, x_min, x_max, 26);
     auto y = std::vector<long double>(26);
     auto y_min = std::numeric_limits<long double>::max();
     auto y_max = std::numeric_limits<long double>::min();
     for (size_t i = 0; i < x.size(); i++) {
         y[i] = scaling_factor * std::exp(growth_rate * x[i]);
         if (y[i] > y_max) {
             y_max = y[i];
         }
         if (y[i] < y_min) {
             y_min = y[i];
         }
     }
     // 26 shades of gray
     std::vector<std::string> grayShades;
     grayShades.emplace_back("\033[38;5;016m"); // black
     for (size_t i = 0; i < 24; ++i) {
         int colorCode = 232 + i;
         grayShades.push_back("\033[38;5;" + std::to_string(colorCode) + "m");
     }
     grayShades.emplace_back("\033[38;5;231m"); // white
     std::vector<std::string> toneMap;
     for (size_t i = 0; i <= 25; ++i) {
         auto yi = 0 + (y[i] - y_min) * (25 - 0) / (y_max - y_min);
         auto idx = static_cast<int>(std::floor(yi));
         toneMap.push_back(grayShades[idx]);
     }
     return toneMap;
 }
References fill_linspace(), i, MyBLAS::Stats::max(), MyBLAS::Stats::min(), x, and y.
Referenced by printJuliaSet().
getHSV256bitANSI()
static std::vector<std::string> getHSV256bitANSI () static
Generates a vector of 256-bit ANSI HSV colors.
Returns
A vector of ANSI escape codes representing HSV colors.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     std::vector<std::string> colors;
     // 1
     colors.emplace_back("\033[38;5;016m"); // black
     // 1 + 24
     for (int i = 232; i < 256; i++) {
         colors.push_back("\033[38;5;" + std::to_string(i) + "m");
     }
     // 1 + 24 + 1
     colors.emplace_back("\033[38;5;231m"); // white
     //
     std::vector<std::string> hues = {
         "225", "219", "218", "211", "212", "213", "207", "206", "200", "201", "165", "129", "093",
         "057", "021", "027", "033", "039", "045", "051", "087", "050", "049", "086", "085", "048",
         "047", "084", "083", "046", "082", "119", "155", "118", "154", "191", "190", "226", "227",
         "221", "220", "214", "208", "202", "160", "196", "197", "198", "197",
     };
     for (auto &hue : hues) {
         colors.push_back("\033[38;5;" + hue + "m");
     }
     return colors;
 }
References i.
juliaSetIterations()
template<typename T > size_t juliaSetIterations (const std::complex< T > & z0, const std::complex< T > & c, size_t max_iterations)
Calculates the number of iterations for a given point in the Julia set.
Template Parameters
T The type of the complex numbers.
Parameters
z0 The initial complex number.
c The constant complex number.
max_iterations The maximum number of iterations.
Returns
The number of iterations before the point escapes the Julia set.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     std::complex<T> z = z0;
     size_t iter = 0;
     for (; iter < max_iterations; iter++) {
         z = z * z + c;
         if (std::norm(z) > 4.0)
             break;
     }
     return iter;
 }
References MyBLAS::norm(), and z.
Referenced by printJuliaSet().
printJuliaSet()
template<typename T > void printJuliaSet (const Canvas & canvas, const T x0, const T y0, const size_t max_iterations = 120)
Prints the Julia set to the console using the specified canvas properties.
Template Parameters
T The type of the numbers used for the complex numbers.
Parameters
canvas The canvas properties for rendering the Julia set.
x0 The real part of the constant complex number.
y0 The imaginary part of the constant complex number.
max_iterations The maximum number of iterations (default is 120).
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     const T x_range = fabsl(canvas.x_stop - canvas.x_start);
     const T y_range = fabsl(canvas.y_stop - canvas.y_start);
     T x_step = x_range / static_cast<T>(canvas.width);
     T y_step = y_range / static_cast<T>(canvas.height);
     const std::complex<T> c(x0, y0);
     T min = std::numeric_limits<T>::max();
     T max = std::numeric_limits<T>::min();
     T avg = 0.0;
     for (size_t y = 0; y < canvas.height; ++y) {
         for (size_t x = 0; x < canvas.width; ++x) {
             std::complex<T> z = std::complex<T>(canvas.x_start + x * x_step, canvas.y_start + y * y_step);
             size_t iter = juliaSetIterations(z, c, max_iterations);
             const T log_iter = std::log2(iter);
             if (log_iter == NAN || std::isinf(static_cast<long double>(log_iter))) {
                 continue;
             }
             min = std::min(min, log_iter);
             max = std::max(max, log_iter);
             avg += log_iter;
         }
     }
     avg = avg / (canvas.width * canvas.height);
     std::vector<std::string> colors = getGrays256bitANSI(canvas.tone_map.scaling_factor, canvas.tone_map.growth_rate);
     for (size_t y = 0; y < canvas.height; ++y) {
         for (size_t x = 0; x < canvas.width; ++x) {
             std::complex<T> z = std::complex<T>(canvas.x_start + x * x_step, canvas.y_start + y * y_step);
             size_t iter = juliaSetIterations(z, c, max_iterations);
             T log_iter = std::log2(iter);
             T enhanced_value = (log_iter - avg) * canvas.contrast + avg;
             T color_index = scale<T>(enhanced_value, min, max, 0, colors.size());
             size_t clamped_index = std::clamp<size_t>(static_cast<size_t>(color_index), 0, colors.size() - 1);
             std::cout << colors[clamped_index] << canvas.character;
         }
         std::cout << '\n';
     }
     std::cout << "\033[0m";
 }
References CanvasType< T >::character, CanvasType< T >::contrast, getGrays256bitANSI(), CanvasType< T >::height, juliaSetIterations(), MyBLAS::Stats::max(), MyBLAS::Stats::min(), CanvasType< T >::tone_map, CanvasType< T >::width, x, CanvasType< T >::x_start, CanvasType< T >::x_stop, y, CanvasType< T >::y_start, CanvasType< T >::y_stop, and z.
replace()
template<class T > void replace (std::map< std::string, boost::program_options::variable_value > & vm, const std::string & opt, const T & val)
This function replaces the value of a specified option in a map with a new value.
Template Parameters
T The type of the value to be replaced.
Parameters
vm A map containing program options and their values.
opt The option whose value is to be replaced.
val The new value to replace the old value with.
Note
This function uses the boost library's any class to allow for type erasure, meaning the function can accept any type for the new value.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     vm[opt].value() = boost::any(val);
 }
Referenced by performChecksAndUpdateInput(), Parser::performInputArgumentsCheck(), promptAndSetFlags(), CommandLine< InputType >::setPrecision(), and syncMapKeys().
scale()
template<typename T > static T scale (T value, T old_min, T old_max, T new_min, T new_max) static
Scales a value from one range to another.
Template Parameters
T The data type of the value and range limits
Parameters
value The value to be scaled
old_min The lower limit of the original range
old_max The upper limit of the original range
new_min The lower limit of the new range
new_max The upper limit of the new range
Returns
The scaled value in the new range
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     return (value - old_min) * (new_max - new_min) / (old_max - old_min) + new_min;
 }
syncMapKeys()
template<typename T > void syncMapKeys (std::string & key, nlohmann::json & inputMap, boost::program_options::variables_map & map)
Synchronizes the values of a given key between a JSON object and a Boost variables_map object.
This function first checks if the key exists in the variables_map. If it does, the value is updated in the JSON object. Then, if the key exists in the JSON object, the value is read from the JSON object and updated in the variables_map.
Template Parameters
T The type of the value associated with the key.
Parameters
key The key to synchronize between the JSON object and the variables_map.
inputMap The JSON object containing the key-value pairs.
map The Boost variables_map object containing the key-value pairs.
Examples
/home/runner/work/NE591-008-Monorepo/NE591-008-Monorepo/src/utils/Helpers.h.
{
     // first, check if key is in the variables_map
     if (map.count(key)) {
         // if yes, update it in the JSON map.
         inputMap[key] = map[key].as<T>();
     }
     // then, if key is in the JSON map, read value from the JSON map into the variables_map.
     if (inputMap.contains(key)) {
         replace(map, key, static_cast<T>(inputMap[key]));
     }
 }
References replace().