NE591-008 C++17 Codebase: MyBLAS::Stats::Summary< T > Struct Template Reference
MyBLAS::Stats::Summary< T > Struct Template Reference
A structure to hold the summary statistics of a vector or matrix.
#include <Stats.h>
Public Member Functions
void toJSON (nlohmann::json &jsonMap) const
Data Fields
T min = std::numeric_limits<T>::quiet_NaN()
The minimum value.
T max = std::numeric_limits<T>::quiet_NaN()
The maximum value.
T sum = std::numeric_limits<T>::quiet_NaN()
The sum of all values.
T mean = std::numeric_limits<T>::quiet_NaN()
The mean value.
T variance = std::numeric_limits<T>::quiet_NaN()
The variance.
T stddev = std::numeric_limits<T>::quiet_NaN()
The standard deviation.
T median = std::numeric_limits<T>::quiet_NaN()
The median value.
T p5th = std::numeric_limits<T>::quiet_NaN()
The 5th percentile.
T p95th = std::numeric_limits<T>::quiet_NaN()
The 95th percentile.
size_t runs {}
Friends
std::ostream & operator<< (std::ostream &os, const Summary &summary)
Overloaded stream insertion operator to print the summary statistics.
Detailed Description
template<typename T>
struct MyBLAS::Stats::Summary< T >
A structure to hold the summary statistics of a vector or matrix.
Template Parameters
T The type of the elements in the vector or matrix.
Member Function Documentation
toJSON()
template<typename T > void MyBLAS::Stats::Summary< T >::toJSON (nlohmann::json & jsonMap) const inline
{
         jsonMap["min"] = min;
         jsonMap["max"] = max;
         jsonMap["sum"] = sum;
         jsonMap["mean"] = mean;
         jsonMap["variance"] = variance;
         jsonMap["stddev"] = stddev;
         jsonMap["p5th"] = p5th;
         jsonMap["p95th"] = p95th;
         jsonMap["samples"] = runs;
     }
References MyBLAS::Stats::Summary< T >::max, MyBLAS::Stats::Summary< T >::mean, MyBLAS::Stats::Summary< T >::min, MyBLAS::Stats::Summary< T >::p5th, MyBLAS::Stats::Summary< T >::p95th, MyBLAS::Stats::Summary< T >::runs, MyBLAS::Stats::Summary< T >::stddev, MyBLAS::Stats::Summary< T >::sum, and MyBLAS::Stats::Summary< T >::variance.
Referenced by Output::toJSON().
Friends And Related Function Documentation
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const Summary< T > & summary) friend
Overloaded stream insertion operator to print the summary statistics.
Parameters
os The output stream.
summary The summary statistics to print.
Returns
The output stream.
{
         auto precision = std::cout.precision() ;
         const auto width = static_cast<int>(2 + static_cast<std::streamsize>(10));
         os << std::setprecision(2) << std::setw(width) << std::setfill(' ') << std::scientific;
         os << ":::::: SUM: "<<summary.sum<<" :::::::: VARIANCE: "<<summary.variance<<" :::::::: MEDIAN: "<<summary.median<<" :::::\n";
         os << ":::::: {     MIN,      MAX} : (AVERAGE  ± STD.DEV.) : [PCT_05th, PCT_95th] :::::\n";
         os << ":::::: {" << summary.min << ", " << summary.max << "} ";
         os << ": (" << summary.mean << " ± " << summary.stddev << ") : [";
         os << summary.p5th << ", "<< summary.p95th << "] :::::";
         os << std::setprecision(static_cast<int>(precision));
         return os;
     }
Field Documentation
max
template<typename T > T MyBLAS::Stats::Summary< T >::max = std::numeric_limits<T>::quiet_NaN()
The maximum value.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
mean
template<typename T > T MyBLAS::Stats::Summary< T >::mean = std::numeric_limits<T>::quiet_NaN()
The mean value.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
median
template<typename T > T MyBLAS::Stats::Summary< T >::median = std::numeric_limits<T>::quiet_NaN()
The median value.
Referenced by Profiler< FunctionType >::summarize().
min
template<typename T > T MyBLAS::Stats::Summary< T >::min = std::numeric_limits<T>::quiet_NaN()
The minimum value.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
p5th
template<typename T > T MyBLAS::Stats::Summary< T >::p5th = std::numeric_limits<T>::quiet_NaN()
The 5th percentile.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
p95th
template<typename T > T MyBLAS::Stats::Summary< T >::p95th = std::numeric_limits<T>::quiet_NaN()
The 95th percentile.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
runs
template<typename T > size_t MyBLAS::Stats::Summary< T >::runs {}
Referenced by Profiler< FunctionType >::getSummary(), and MyBLAS::Stats::Summary< T >::toJSON().
stddev
template<typename T > T MyBLAS::Stats::Summary< T >::stddev = std::numeric_limits<T>::quiet_NaN()
The standard deviation.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
sum
template<typename T > T MyBLAS::Stats::Summary< T >::sum = std::numeric_limits<T>::quiet_NaN()
The sum of all values.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
variance
template<typename T > T MyBLAS::Stats::Summary< T >::variance = std::numeric_limits<T>::quiet_NaN()
The variance.
Referenced by Profiler< FunctionType >::summarize(), and MyBLAS::Stats::Summary< T >::toJSON().
The documentation for this struct was generated from the following file:
src/utils/math/blas/Stats.h