NE591-008 C++17 Codebase: Compute Namespace Reference
Compute Namespace Reference
This namespace provides a function to compute the sum of a series.
Functions
MyBLAS::NumericType seriesSum (size_t start, size_t stop)
Computes the sum of a series from a start to a stop index.
static void usingPointJacobi (InLab6Outputs &outputs, InLab6Inputs &inputs)
This method applies the Point Jacobi relaxation method to the given input matrices.
static void usingGaussSeidel (InLab6Outputs &outputs)
This method is a placeholder for the Gauss-Seidel relaxation method.
static void usingSOR (InLab6Outputs &outputs)
This method is a placeholder for the Successive Over-Relaxation (SOR) method.
static void usingSymmetricSOR (InLab6Outputs &outputs)
This method is a placeholder for the Symmetric Successive Over-Relaxation (SSOR) method.
void usingLUP (OutLab6Outputs &outputs, OutLab6Inputs &inputs)
Solves a linear system using LUP decomposition.
void usingGaussSeidel (OutLab6Outputs &outputs, OutLab6Inputs &inputs)
Solves a linear system using the Gauss-Seidel method.
void usingSOR (OutLab6Outputs &outputs, OutLab6Inputs &inputs)
Solves a linear system using the Successive Over-Relaxation (SOR) method.
void usingJacobiSOR (OutLab6Outputs &outputs, OutLab6Inputs &inputs)
Solves a linear system using the Jacobi SOR method.
void usingSymmetricSOR (OutLab6Outputs &outputs, OutLab6Inputs &inputs)
Solves a linear system using the Symmetric SOR method.
template<typename T >
MyBLAS::Vector< T > & naive_fill_diffusion_vector (SolverInputs &inputs)
A template function to fill a diffusion vector.
template<typename MatrixType >
static MatrixType & fill_fluxes (SolverOutputs &outputs)
Fills the fluxes.
void usingLUP (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using LUP decomposition.
void usingPointJacobi (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using the Point Jacobi method.
void usingGaussSeidel (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using the Gauss-Seidel method.
void usingSOR (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using the Successive Over-Relaxation (SOR) method.
void usingJacobiSOR (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using the Jacobi SOR method.
void usingSymmetricSOR (SolverOutputs &outputs, SolverInputs &inputs)
Solves a linear system using the Symmetric SOR method.
Detailed Description
This namespace provides a function to compute the sum of a series.
Namespace containing methods for solving linear systems using various methods.
This namespace contains methods for performing various computations.
Function Documentation
fill_fluxes()
template<typename MatrixType > static MatrixType& Compute::fill_fluxes (SolverOutputs & outputs) static
Fills the fluxes.
This function fills the fluxes based on the given phi vector. The fluxes are stored in a matrix with m+2 rows and n+2 columns.
Parameters
inputs The inputs for the solver.
outputs The outputs of the solver including the fluxes.
{
     const size_t m = outputs.inputs.diffusionParams.getM();
     const size_t n = outputs.inputs.diffusionParams.getN();
     outputs.fluxes = MyBLAS::Matrix<MyBLAS::NumericType>(m + 2, n + 2, 0);
     for (size_t i = 1; i <= m; i++) {
         for (size_t j = 1; j <= n; j++) {
             const size_t idx = (i - 1) * n + (j - 1);
             outputs.fluxes[i][j] = outputs.solution.x[idx];
         }
     }
     return outputs.fluxes;
 }
References i, m, n, and postprocess::outputs.
naive_fill_diffusion_vector()
template<typename T > MyBLAS::Vector<T>& Compute::naive_fill_diffusion_vector (SolverInputs & inputs)
A template function to fill a diffusion vector.
This function fills a diffusion vector using the fixed source q(i, j).
Template Parameters
T The type of the diffusion constants.
Parameters
inputs The solver inputs containing the diffusion parameters and sources.
Returns
The filled diffusion constants vector.
{
     const size_t m = inputs.diffusionParams.getM();
     const size_t n = inputs.diffusionParams.getN();
     inputs.diffusionConstants = MyBLAS::Vector<T>(std::vector<T>(m * n, 0));
     // Loop through all the nodes i = 1, ..., m and j = 1, ..., n
     for (size_t i = 1; i <= m; ++i) {
         for (size_t j = 1; j <= n; ++j) {
             // Calculate the index of the current node in the vector B
             const size_t idx = (i - 1) * n + (j - 1);
             // Fill the right-hand-side vector B using the fixed source q(i, j)
             inputs.diffusionConstants[idx] = inputs.sources[i - 1][j - 1];
         }
     }
     return inputs.diffusionConstants;
 }
References i, process::inputs, m, and n.
seriesSum()
MyBLAS::NumericType Compute::seriesSum (size_t start, size_t stop)
Computes the sum of a series from a start to a stop index.
This function computes the sum of a series from a start to a stop index. The series is defined as the square of the ratio of (1.0f + log10(i-1)) to ((i-1) + log10(i)) for each i from start to stop. If start is greater than stop, the function swaps the two values.
Parameters
start The start index of the series.
stop The stop index of the series.
Returns
The sum of the series from start to stop.
{
    if (start > stop) {
        std::swap(start, stop);
    }
    MyBLAS::NumericType partialSum = 0;
    MyBLAS::NumericType previousLog = std::log10(start);
    for (size_t i = start + 1; i < stop; i++) {
        const MyBLAS::NumericType currentLog = std::log10(i);
        const MyBLAS::NumericType denominator = (i - 1) + currentLog;
        const MyBLAS::NumericType numerator = 1.0f + previousLog;
        previousLog = currentLog;
        const MyBLAS::NumericType term = std::pow(numerator / denominator, 2);
        partialSum += term;
    }
    return partialSum;
 }
References i, and MyMath::pow().
Referenced by OutLab7::run().
usingGaussSeidel() [1/3]
static void Compute::usingGaussSeidel (InLab6Outputs & outputs) static
This method is a placeholder for the Gauss-Seidel relaxation method.
Parameters
outputs A reference to the RelaxationMethodOutputs object where the results will be stored.
 {}
Referenced by OutLab6::run(), and Project2::run().
usingGaussSeidel() [2/3]
void Compute::usingGaussSeidel (OutLab6Outputs & outputs, OutLab6Inputs & inputs)
Solves a linear system using the Gauss-Seidel method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.input.coefficients;
     MyBLAS::Vector<long double> &b = inputs.input.constants;
     const size_t max_iterations = inputs.input.max_iterations;
     const long double threshold = inputs.input.threshold;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting Gauss Seidel calculation\n";
         return;
     }
     {
         const size_t maxRuns = 10;
         auto runTimes = std::vector<long double>(maxRuns);
         Stopwatch<Nanoseconds> timer;
         for (outputs.runs = 0; outputs.runs < maxRuns; outputs.runs++) {
             timer.restart();
             {
                outputs.solution = MyRelaxationMethod::applyGaussSeidel(A, b, max_iterations, threshold);
             }
             timer.click();
             runTimes[outputs.runs] = (timer.duration().count());
         }
         auto stats = computeMeanStd(runTimes);
         outputs.mean_execution_time = boost::accumulators::mean(stats);
         outputs.stddev_execution_time = std::sqrt(boost::accumulators::variance(stats));
         outputs.runs = maxRuns;
     }
 }
References MyRelaxationMethod::applyGaussSeidel(), Stopwatch< D >::click(), computeMeanStd(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and Stopwatch< D >::restart().
usingGaussSeidel() [3/3]
void Compute::usingGaussSeidel (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using the Gauss-Seidel method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     auto A = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     const size_t max_iterations = inputs.solverParams.max_iterations;
     const MyBLAS::NumericType threshold = inputs.solverParams.threshold;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting Gauss Seidel calculation\n";
         return;
     }
     auto profiler = Profiler([&]() {
         outputs.solution = MyRelaxationMethod::applyGaussSeidel(A, b, max_iterations, threshold);
     }, inputs.numRuns, inputs.timeout, "Gauss Seidel");
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = MatrixVectorExpression<MyPhysics::Diffusion::Matrix, MyBLAS::Vector, MyBLAS::NumericType>::multiplyMatrixVector(A, outputs.solution.x);
         outputs.residual = b - b_prime;
         if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "gauss-seidel.csv", outputs.fluxes);
         }
     }
 }
References MyRelaxationMethod::applyGaussSeidel(), process::inputs, MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().
usingJacobiSOR() [1/2]
void Compute::usingJacobiSOR (OutLab6Outputs & outputs, OutLab6Inputs & inputs)
Solves a linear system using the Jacobi SOR method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.input.coefficients;
     MyBLAS::Vector<long double> &b = inputs.input.constants;
     const size_t max_iterations = inputs.input.max_iterations;
     const long double threshold = inputs.input.threshold;
     const long double omega = inputs.input.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting SOR point jacobi calculation\n";
         return;
     }
     {
         const size_t maxRuns = 10;
         auto runTimes = std::vector<long double>(maxRuns);
         Stopwatch<Nanoseconds> timer;
         for (outputs.runs = 0; outputs.runs < maxRuns; outputs.runs++) {
             timer.restart();
             {
                 outputs.solution = MyRelaxationMethod::applyPointJacobi(A, b, max_iterations, threshold, omega);
             }
             timer.click();
             runTimes[outputs.runs] = (timer.duration().count());
         }
         auto stats = computeMeanStd(runTimes);
         outputs.mean_execution_time = boost::accumulators::mean(stats);
         outputs.stddev_execution_time = std::sqrt(boost::accumulators::variance(stats));
         outputs.runs = maxRuns;
     }
 }
References MyRelaxationMethod::applyPointJacobi(), Stopwatch< D >::click(), computeMeanStd(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and Stopwatch< D >::restart().
Referenced by OutLab6::run(), and Project2::run().
usingJacobiSOR() [2/2]
void Compute::usingJacobiSOR (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using the Jacobi SOR method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     auto A = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     const size_t max_iterations = inputs.solverParams.max_iterations;
     const MyBLAS::NumericType threshold = inputs.solverParams.threshold;
     const MyBLAS::NumericType omega = inputs.solverParams.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting SOR point jacobi calculation\n";
         return;
     }
     auto profiler = Profiler([&]() {
         outputs.solution = MyRelaxationMethod::applyPointJacobi(A, b, max_iterations, threshold, 2.0f - omega);
     }, inputs.numRuns, inputs.timeout, "SORJ");
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = MatrixVectorExpression<MyPhysics::Diffusion::Matrix, MyBLAS::Vector, MyBLAS::NumericType>::multiplyMatrixVector(A, outputs.solution.x);
         outputs.residual = b - b_prime;
         if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "SORJ.csv", outputs.fluxes);
         }
     }
 }
References MyRelaxationMethod::applyPointJacobi(), process::inputs, MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().
usingLUP() [1/2]
void Compute::usingLUP (OutLab6Outputs & outputs, OutLab6Inputs & inputs)
Solves a linear system using LUP decomposition.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.input.coefficients;
     MyBLAS::Vector<long double> &b = inputs.input.constants;
     if (!MyFactorizationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting LUP calculation\n";
         return;
     }
     {
         const size_t maxRuns = 10;
         auto runTimes = std::vector<long double>(maxRuns);
         Stopwatch<Nanoseconds> timer;
         for (outputs.runs = 0; outputs.runs < maxRuns; outputs.runs++) {
             timer.restart();
             {
                 outputs.solution = MyBLAS::LUP::applyLUP(A, b);
             }
             timer.click();
             runTimes[outputs.runs] = (timer.duration().count());
         }
         auto stats = computeMeanStd(runTimes);
         outputs.mean_execution_time = boost::accumulators::mean(stats);
         outputs.stddev_execution_time = std::sqrt(boost::accumulators::variance(stats));
         outputs.runs = maxRuns;
     }
     outputs.solution.converged = true;
 }
References MyBLAS::LUP::applyLUP(), Stopwatch< D >::click(), computeMeanStd(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, MyFactorizationMethod::passesPreChecks(), and Stopwatch< D >::restart().
Referenced by OutLab6::run(), and Project2::run().
usingLUP() [2/2]
void Compute::usingLUP (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using LUP decomposition.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     inputs.diffusionCoefficients = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto A = inputs.diffusionCoefficients;
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     if (!MyFactorizationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting LUP calculation\n";
         return;
     }
     auto inMemoryA = MyBLAS::Matrix<MyBLAS::NumericType>(inputs.diffusionCoefficients);
     auto profiler = Profiler([&]() {
         outputs.solution = outputs.solution = MyBLAS::LUP::applyLUP(inMemoryA, b);
     }, inputs.numRuns, inputs.timeout, "LUP");
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.solution.converged = true;
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = A * outputs.solution.x;
         outputs.residual = b - b_prime;
             if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "LUP.csv", outputs.fluxes);
         }
     }
 }
References MyBLAS::LUP::applyLUP(), process::inputs, postprocess::outputs, MyFactorizationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().
usingPointJacobi() [1/2]
static void Compute::usingPointJacobi (InLab6Outputs & outputs, InLab6Inputs & inputs) static
This method applies the Point Jacobi relaxation method to the given input matrices.
Solves a linear system using the Point Jacobi method.
Parameters
outputs A reference to the RelaxationMethodOutputs object where the results will be stored.
inputs A reference to the InputMatrices object that contains the input matrices.
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.coefficients;
     MyBLAS::Vector<long double> &b = inputs.constants;
     const size_t max_iterations = inputs.max_iterations;
     const long double threshold = inputs.threshold;
     Stopwatch<Nanoseconds> timer;
     timer.restart();
     { outputs.solution = MyRelaxationMethod::applyPointJacobi(A, b, max_iterations, threshold); }
     timer.click();
     const auto time = static_cast<long double>(timer.duration().count());
     outputs.execution_time = time;
 }
References MyRelaxationMethod::applyPointJacobi(), Stopwatch< D >::click(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, and Stopwatch< D >::restart().
Referenced by InLab6::run(), OutLab6::run(), and Project2::run().
usingPointJacobi() [2/2]
void Compute::usingPointJacobi (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using the Point Jacobi method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     inputs.diffusionCoefficients = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto A = inputs.diffusionCoefficients;
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     const size_t max_iterations = inputs.solverParams.max_iterations;
     const MyBLAS::NumericType threshold = inputs.solverParams.threshold;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting Point jacobi calculation\n";
         return;
     }
     auto profiler = Profiler([&]() {
         outputs.solution = MyRelaxationMethod::applyPointJacobi(A, b, max_iterations, threshold);
     }, inputs.numRuns, inputs.timeout, "Point Jacobi");
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = A * outputs.solution.x;
         outputs.residual = b - b_prime;
         if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "point-jacobi.csv", outputs.fluxes);
         }
     }
 }
References MyRelaxationMethod::applyPointJacobi(), process::inputs, postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().
usingSOR() [1/3]
static void Compute::usingSOR (InLab6Outputs & outputs) static
This method is a placeholder for the Successive Over-Relaxation (SOR) method.
Parameters
outputs A reference to the RelaxationMethodOutputs object where the results will be stored.
 {}
Referenced by OutLab6::run(), and Project2::run().
usingSOR() [2/3]
void Compute::usingSOR (OutLab6Outputs & outputs, OutLab6Inputs & inputs)
Solves a linear system using the Successive Over-Relaxation (SOR) method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.input.coefficients;
     MyBLAS::Vector<long double> &b = inputs.input.constants;
     const size_t max_iterations = inputs.input.max_iterations;
     const long double threshold = inputs.input.threshold;
     const long double omega = inputs.input.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting SOR calculation\n";
         return;
     }
     {
         const size_t maxRuns = 10;
         auto runTimes = std::vector<long double>(maxRuns);
         Stopwatch<Nanoseconds> timer;
         for (outputs.runs = 0; outputs.runs < maxRuns; outputs.runs++) {
             timer.restart();
             {
                outputs.solution = MyRelaxationMethod::applySOR(A, b, max_iterations, threshold, omega);
             }
             timer.click();
             runTimes[outputs.runs] = (timer.duration().count());
         }
         auto stats = computeMeanStd(runTimes);
         outputs.mean_execution_time = boost::accumulators::mean(stats);
         outputs.stddev_execution_time = std::sqrt(boost::accumulators::variance(stats));
         outputs.runs = maxRuns;
     }
 }
References MyRelaxationMethod::applySOR(), Stopwatch< D >::click(), computeMeanStd(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and Stopwatch< D >::restart().
usingSOR() [3/3]
void Compute::usingSOR (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using the Successive Over-Relaxation (SOR) method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     auto A = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     const size_t max_iterations = inputs.solverParams.max_iterations;
     const MyBLAS::NumericType threshold = inputs.solverParams.threshold;
     const MyBLAS::NumericType omega = inputs.solverParams.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting SOR calculation\n";
         return;
     }
     auto profiler = Profiler([&]() {
         outputs.solution = MyRelaxationMethod::applySOR(A, b, max_iterations, threshold, omega);
     }, inputs.numRuns, inputs.timeout, "SOR"); // Run the block 10 times
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = MatrixVectorExpression<MyPhysics::Diffusion::Matrix, MyBLAS::Vector, MyBLAS::NumericType>::multiplyMatrixVector(A, outputs.solution.x);
         outputs.residual = b - b_prime;
         if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "SOR.csv", outputs.fluxes);
         }
     }
 }
References MyRelaxationMethod::applySOR(), process::inputs, MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().
usingSymmetricSOR() [1/3]
static void Compute::usingSymmetricSOR (InLab6Outputs & outputs) static
This method is a placeholder for the Symmetric Successive Over-Relaxation (SSOR) method.
Parameters
outputs A reference to the RelaxationMethodOutputs object where the results will be stored.
 {}
Referenced by OutLab6::run(), and Project2::run().
usingSymmetricSOR() [2/3]
void Compute::usingSymmetricSOR (OutLab6Outputs & outputs, OutLab6Inputs & inputs)
Solves a linear system using the Symmetric SOR method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     MyBLAS::Matrix<long double> &A = inputs.input.coefficients;
     MyBLAS::Vector<long double> &b = inputs.input.constants;
     const size_t max_iterations = inputs.input.max_iterations;
     const long double threshold = inputs.input.threshold;
     const long double omega = inputs.input.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting symmetric SOR calculation\n";
         return;
     }
     {
         const size_t maxRuns = 10;
         auto runTimes = std::vector<long double>(maxRuns);
         Stopwatch<Nanoseconds> timer;
         for (outputs.runs = 0; outputs.runs < maxRuns; outputs.runs++) {
             timer.restart();
             {
                 outputs.solution = MyRelaxationMethod::applySSOR(A, b, max_iterations, threshold, omega);
             }
             timer.click();
             runTimes[outputs.runs] = (timer.duration().count());
         }
         auto stats = computeMeanStd(runTimes);
         outputs.mean_execution_time = boost::accumulators::mean(stats);
         outputs.stddev_execution_time = std::sqrt(boost::accumulators::variance(stats));
         outputs.runs = maxRuns;
     }
 }
References MyRelaxationMethod::applySSOR(), Stopwatch< D >::click(), computeMeanStd(), Stopwatch< D >::duration(), process::inputs, postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and Stopwatch< D >::restart().
usingSymmetricSOR() [3/3]
void Compute::usingSymmetricSOR (SolverOutputs & outputs, SolverInputs & inputs)
Solves a linear system using the Symmetric SOR method.
Parameters
outputs The output data structure to store the solution and execution time.
inputs The input data structure containing the system to solve.
{
     auto A = MyPhysics::Diffusion::Matrix(inputs.diffusionParams);
     auto b = naive_fill_diffusion_vector<MyBLAS::NumericType>(inputs);
     const size_t max_iterations = inputs.solverParams.max_iterations;
     const MyBLAS::NumericType threshold = inputs.solverParams.threshold;
     const MyBLAS::NumericType omega = inputs.solverParams.relaxation_factor;
     if (!MyRelaxationMethod::passesPreChecks(A, b)) {
         std::cerr << "Aborting symmetric SOR calculation\n";
         return;
     }
     auto profiler = Profiler([&]() {
         outputs.solution = MyRelaxationMethod::applySSOR(A, b, max_iterations, threshold, omega);
     }, inputs.numRuns, inputs.timeout, "SSOR");
     outputs.summary = profiler.run().getSummary();
     outputs.summary.runs = profiler.getTotalRuns();
     std::cout<<std::endl<<profiler;
     // post-process
     {
         outputs.fluxes = fill_fluxes<MyBLAS::Matrix<MyBLAS::NumericType>>(outputs);
         auto b_prime = MatrixVectorExpression<MyPhysics::Diffusion::Matrix, MyBLAS::Vector, MyBLAS::NumericType>::multiplyMatrixVector(A, outputs.solution.x);
         outputs.residual = b - b_prime;
         if (!inputs.fluxOutputDirectory.empty()) {
             writeCSVMatrixNoHeaders(inputs.fluxOutputDirectory, "SSOR.csv", outputs.fluxes);
         }
     }
 }
References MyRelaxationMethod::applySSOR(), process::inputs, MatrixVectorExpression< MatrixType, VectorType, T >::multiplyMatrixVector(), postprocess::outputs, MyRelaxationMethod::passesPreChecks(), and writeCSVMatrixNoHeaders().