NE591-008 C++17 Codebase: MyBLAS::Input Struct Reference
MyBLAS::Input Struct Reference
Struct representing the input matrices for the BLAS library.
#include <InputsOutputs.h>
Public Member Functions
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Input ()=default
void toJSON (nlohmann::json &jsonMap) const
Converts the input parameters to a JSON object.
Data Fields
size_t n = 0
Size of the matrices.
MyBLAS::Matrix< long double > LU
LU matrix.
MyBLAS::Matrix< long double > permutation
LU matrix.
MyBLAS::Vector< long double > constants
Vector of constants.
MyBLAS::Matrix< long double > coefficients
LU matrix.
Detailed Description
Struct representing the input matrices for the BLAS library.
Constructor & Destructor Documentation
Input() [1/2]
MyBLAS::Input::Input () default
Input() [2/2]
MyBLAS::Input::Input () default
Member Function Documentation
toJSON() [1/2]
void MyBLAS::Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["n"] = n;
         jsonMap["LU"] = LU.getData();
         jsonMap["permutation"] = permutation.getData();
         jsonMap["constants"] = constants.getData();
     }
References constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), LU, n, and permutation.
toJSON() [2/2]
void MyBLAS::Input::toJSON (nlohmann::json & jsonMap) const inline
Converts the input parameters to a JSON object.
Parameters
jsonMap A reference to the JSON object to store the input parameters.
{
         jsonMap["n"] = n;
         jsonMap["coefficients"] = coefficients.getData();
         jsonMap["constants"] = constants.getData();
     }
References coefficients, constants, MyBLAS::Matrix< T >::getData(), MyBLAS::Vector< T >::getData(), and n.
Field Documentation
coefficients
MyBLAS::Matrix<long double> MyBLAS::Input::coefficients
LU matrix.
Referenced by toJSON().
constants
MyBLAS::Vector< long double > Input::constants
Vector of constants.
Referenced by toJSON().
LU
MyBLAS::Matrix<long double> MyBLAS::Input::LU
LU matrix.
Referenced by toJSON().
n
size_t Input::n = 0
Size of the matrices.
Referenced by toJSON().
permutation
MyBLAS::Matrix<long double> MyBLAS::Input::permutation
LU matrix.
Referenced by toJSON().
The documentation for this struct was generated from the following file:
src/labs/inlab5/InputsOutputs.h