NE591-008 C++17 Codebase: MyPhysics::Diffusion::Vector< T > Class Template Reference
MyPhysics::Diffusion::Vector< T > Class Template Reference
#include <SourceVector.h>
Public Types
using Generator = std::function< T(size_t)>
Public Member Functions
Vector ()=default
Vector (const Params< T > params)
Vector (const Vector< T > &vector)
Vector & operator= (const Vector &other)
Vector (const Params< T > &params, Generator generator)
const Params< T > & getParams () const
const Constants< T > & getConstants () const
size_t getSize () const
size_t size () const
T operator[] (size_t index) const
LazyVector operator+ (T scalar) const
LazyVector operator- (T scalar) const
LazyVector operator- () const
LazyVector operator* (T scalar) const
LazyVector operator/ (T scalar) const
LazyVector & operator+= (LazyVector const &b)
LazyVector & operator+= (T scalar)
LazyVector & operator-= (LazyVector const &b)
LazyVector & operator-= (T scalar)
LazyVector & operator*= (LazyVector const &b)
LazyVector & operator*= (T scalar)
LazyVector & operator/= (LazyVector const &b)
LazyVector & operator/= (T scalar)
Static Public Member Functions
static T generate (size_t idx, const Constants< T > &c)
Private Attributes
Params< T > _params {}
size_t _size = 0
Constants< T > _constants {}
size_t size_
Generator generator_
Detailed Description
template<typename T>
class MyPhysics::Diffusion::Vector< T >
Member Typedef Documentation
Generator
template<typename T > using MyPhysics::Diffusion::Vector< T >::Generator = std::function<T(size_t)>
Constructor & Destructor Documentation
Vector() [1/4]
template<typename T > MyPhysics::Diffusion::Vector< T >::Vector () explicit default
Vector() [2/4]
template<typename T > MyPhysics::Diffusion::Vector< T >::Vector (const Params< T > params) inline explicit
                                            : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setSize(_size);
         this->setGenerator([this](size_t i) {
             return generate(i, _constants);
         });
     }
References MyPhysics::Diffusion::Vector< T >::_constants, MyPhysics::Diffusion::Vector< T >::_params, MyPhysics::Diffusion::Vector< T >::_size, MyPhysics::Diffusion::Vector< T >::generate(), MyPhysics::Diffusion::Params< FloatType >::getM(), MyPhysics::Diffusion::Params< FloatType >::getN(), and i.
Vector() [3/4]
template<typename T > MyPhysics::Diffusion::Vector< T >::Vector (const Vector< T > & vector) inline
                                    : _params(vector.params), _constants(Constants<T>::compute(vector.params)) {
         _size = vector._size;
         this->setSize(_size);
         this->setGenerator([this](size_t i) {
             return generate(i, _constants);
         });
     }
References MyPhysics::Diffusion::Vector< T >::_constants, MyPhysics::Diffusion::Vector< T >::_size, MyPhysics::Diffusion::Vector< T >::generate(), and i.
Vector() [4/4]
template<typename T > MyPhysics::Diffusion::Vector< T >::Vector (const Params< T > & params, Generator generator) inline
                                                         : _params(params), _constants(Constants<T>::compute(params)) {
         _size = _params.getM() * _params.getN();
         this->setSize(_size);
         this->setGenerator(generator);
     }
References MyPhysics::Diffusion::Vector< T >::_params, MyPhysics::Diffusion::Vector< T >::_size, MyPhysics::Diffusion::Params< FloatType >::getM(), and MyPhysics::Diffusion::Params< FloatType >::getN().
Member Function Documentation
generate()
template<typename T > static T MyPhysics::Diffusion::Vector< T >::generate (size_t idx, const Constants< T > & c) inline static
{
         // Define your generation logic here
         // This is just a placeholder
         return static_cast<T>(idx);
     }
Referenced by MyPhysics::Diffusion::Vector< T >::operator=(), and MyPhysics::Diffusion::Vector< T >::Vector().
getConstants()
template<typename T > const Constants<T>& MyPhysics::Diffusion::Vector< T >::getConstants () const inline
 { return _constants; }
References MyPhysics::Diffusion::Vector< T >::_constants.
getParams()
template<typename T > const Params<T>& MyPhysics::Diffusion::Vector< T >::getParams () const inline
 { return _params; }
References MyPhysics::Diffusion::Vector< T >::_params.
getSize()
template<typename T > size_t MyPhysics::Diffusion::Vector< T >::getSize () const inline
{
         return _size;
     }
References MyPhysics::Diffusion::Vector< T >::_size.
operator*()
LazyVector MyBLAS::LazyVector< T >::operator* (T scalar) const inline inherited
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] * scalar; });
     }
operator*=() [1/2]
LazyVector& MyBLAS::LazyVector< T >::operator*= (LazyVector< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) * b[i]; };
         return *this;
     }
operator*=() [2/2]
LazyVector& MyBLAS::LazyVector< T >::operator*= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) * scalar; };
         return *this;
     }
operator+()
LazyVector MyBLAS::LazyVector< T >::operator+ (T scalar) const inline inherited
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] + scalar; });
     }
operator+=() [1/2]
LazyVector& MyBLAS::LazyVector< T >::operator+= (LazyVector< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) + b[i]; };
         return *this;
     }
operator+=() [2/2]
LazyVector& MyBLAS::LazyVector< T >::operator+= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) + scalar; };
         return *this;
     }
operator-() [1/2]
LazyVector MyBLAS::LazyVector< T >::operator- () const inline inherited
{
         return LazyVector(size_, [this](size_t i) { return -(*this)[i]; });
     }
operator-() [2/2]
LazyVector MyBLAS::LazyVector< T >::operator- (T scalar) const inline inherited
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] - scalar; });
     }
operator-=() [1/2]
LazyVector& MyBLAS::LazyVector< T >::operator-= (LazyVector< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) - b[i]; };
         return *this;
     }
operator-=() [2/2]
LazyVector& MyBLAS::LazyVector< T >::operator-= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) - scalar; };
         return *this;
     }
operator/()
LazyVector MyBLAS::LazyVector< T >::operator/ (T scalar) const inline inherited
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] / scalar; });
     }
operator/=() [1/2]
LazyVector& MyBLAS::LazyVector< T >::operator/= (LazyVector< T > const & b) inline inherited
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) / b[i]; };
         return *this;
     }
operator/=() [2/2]
LazyVector& MyBLAS::LazyVector< T >::operator/= (T scalar) inline inherited
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) / scalar; };
         return *this;
     }
operator=()
template<typename T > Vector& MyPhysics::Diffusion::Vector< T >::operator= (const Vector< T > & other) inline
{
         if (this != &other) {
             _params = other._params;
             _size = other._size;
             _constants = other._constants;
             this->setSize(_size);
             this->setGenerator([this](size_t i) {
                 return generate(i, _constants);
             });
         }
         return *this;
     }
References MyPhysics::Diffusion::Vector< T >::_constants, MyPhysics::Diffusion::Vector< T >::_params, MyPhysics::Diffusion::Vector< T >::_size, MyPhysics::Diffusion::Vector< T >::generate(), and i.
operator[]()
T MyBLAS::LazyVector< T >::operator[] (size_t index) const inline inherited
{
         return generator_(index);
     }
size()
size_t MyBLAS::LazyVector< T >::size () const inline inherited
 { return size_; }
Field Documentation
_constants
template<typename T > Constants<T> MyPhysics::Diffusion::Vector< T >::_constants {} private
Referenced by MyPhysics::Diffusion::Vector< T >::getConstants(), MyPhysics::Diffusion::Vector< T >::operator=(), and MyPhysics::Diffusion::Vector< T >::Vector().
_params
template<typename T > Params<T> MyPhysics::Diffusion::Vector< T >::_params {} private
Referenced by MyPhysics::Diffusion::Vector< T >::getParams(), MyPhysics::Diffusion::Vector< T >::operator=(), and MyPhysics::Diffusion::Vector< T >::Vector().
_size
template<typename T > size_t MyPhysics::Diffusion::Vector< T >::_size = 0 private
Referenced by MyPhysics::Diffusion::Vector< T >::getSize(), MyPhysics::Diffusion::Vector< T >::operator=(), and MyPhysics::Diffusion::Vector< T >::Vector().
generator_
Generator MyBLAS::LazyVector< T >::generator_ private inherited
size_
size_t MyBLAS::LazyVector< T >::size_ private inherited
The documentation for this class was generated from the following file:
src/utils/physics/diffusion/SourceVector.h