NE591-008 C++17 Codebase: CommandLine< InputType > Class Template Reference
CommandLine< InputType > Class Template Reference abstract
A class to parse command line arguments and display information about the project.
#include <CommandLine.h>
Public Member Functions
CommandLine (HeaderInfo headerInfo, CommandLineArgs args)
Constructor for the CommandLine class.
CommandLine ()
Default constructor for the CommandLine class. This constructor initializes the CommandLine object with an empty variables map.
virtual ~CommandLine ()=default
Destructor for the CommandLine class. This is a virtual destructor that does nothing.
boost::program_options::variables_map & getArguments ()
Method to get the parsed command line arguments.
boost::program_options::variables_map getArgumentsMap ()
Method to get a copy of the parsed command line arguments.
const CommandLineArgs & getCmdArgs () const
Method to get the command line argv, argc objects.
int getCurrentPrecision ()
Method to get the current precision.
void setPrecision (int precisionToSet=5)
Method to set the precision of long double values.
InputType & getInputs ()
Method to get the inputs.
Static Public Member Functions
static void printLine ()
Method to print a line to the console. This method prints a line of dashes to the console.
Protected Member Functions
virtual void buildInputArguments (boost::program_options::options_description &inputArguments)=0
Method to build a set of input arguments.
virtual void printInputArguments (boost::program_options::variables_map &values)=0
Method to print the input arguments.
virtual void performInputArgumentsCheck (boost::program_options::variables_map &values)=0
Method to perform a check on the input arguments.
virtual void buildInputs (InputType &ToFill, boost::program_options::variables_map &values)=0
Method to fill the inputs object based on the parsed command line arguments.
void printPrecisionInformation ()
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
virtual void initialize ()
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
Static Protected Member Functions
static boost::program_options::options_description buildGenerics ()
Method to build a set of generic command line options.
static void printHeader (HeaderInfo &headerInfo)
Method to print the project header to the console.
static void printCompileConfigs ()
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
Protected Attributes
boost::program_options::variables_map variablesMap
A variables_map object to store the parsed command line arguments.
bool initialized = false
A boolean flag to indicate whether the CommandLine object has been initialized.
CommandLineArgs cmdArgs
A CommandLineArgs object to store the command line arguments.
InputType _inputs = InputType()
HeaderInfo header
A HeaderInfo object to store information about the project.
Detailed Description
template<typename InputType>
class CommandLine< InputType >
A class to parse command line arguments and display information about the project.
This class contains methods to parse command line arguments using the Boost library, and to display information about the project. The constructor takes a HeaderInfo object and command line arguments, and initializes the class. The getArguments method returns the parsed command line arguments. The printLine method prints a line to the console. The buildGenerics method builds a set of generic command line options. The printHeader method prints the project header to the console. The printPrecisionInformation method prints information about the precision of long double values. The initialize method initializes the class by printing the compile configurations and precision information, and parsing the command line arguments. The printCompileConfigs method prints the compile configurations to the console.
Constructor & Destructor Documentation
CommandLine() [1/2]
template<typename InputType > CommandLine< InputType >::CommandLine (HeaderInfo headerInfo, CommandLineArgs args) inline explicit
Constructor for the CommandLine class.
Parameters
headerInfo A HeaderInfo object containing information about the project.
args Command line arguments. This constructor initializes the CommandLine object with the provided HeaderInfo object and command line arguments. It also prints the project header.
{
         cmdArgs = args;
         initialized = false;
         header = std::move(headerInfo);
     }
References CommandLine< InputType >::cmdArgs, CommandLine< InputType >::header, and CommandLine< InputType >::initialized.
CommandLine() [2/2]
template<typename InputType > CommandLine< InputType >::CommandLine () inline explicit
Default constructor for the CommandLine class. This constructor initializes the CommandLine object with an empty variables map.
 { variablesMap = boost::program_options::variables_map(); }
References CommandLine< InputType >::variablesMap.
~CommandLine()
template<typename InputType > virtual CommandLine< InputType >::~CommandLine () virtual default
Destructor for the CommandLine class. This is a virtual destructor that does nothing.
Member Function Documentation
buildGenerics()
template<typename InputType > static boost::program_options::options_description CommandLine< InputType >::buildGenerics () inline static protected
Method to build a set of generic command line options.
Returns
An options description containing the generic command line options. This method builds a set of generic command line options, such as "help", "quiet", and "precision", and returns them as an options description.
{
         auto benchmarkOptions = ProfilerHelper::buildCommandlineOptions();
         benchmarkOptions.add_options()("bench,B", "= Run performance benchmarks");
         boost::program_options::options_description generics("General options");
         generics.add_options()
             ("help,h", "= Show this help message")("quiet,q", "= Reduce verbosity")
             ("precision,p", boost::program_options::value<int>()->default_value(15), "= Number of digits to represent long double");
         benchmarkOptions.add(generics);
         return benchmarkOptions;
     }
References ProfilerHelper::buildCommandlineOptions().
buildInputArguments()
template<typename InputType > virtual void CommandLine< InputType >::buildInputArguments (boost::program_options::options_description & inputArguments) protected pure virtual
Method to build a set of input arguments.
Parameters
inputArguments A reference to an options_description object that will be filled with the input arguments. This is a pure virtual method that must be implemented by derived classes. It is used to build a set of input arguments for the command line parser.
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
buildInputs()
template<typename InputType > virtual void CommandLine< InputType >::buildInputs (InputType & ToFill, boost::program_options::variables_map & values) protected pure virtual
Method to fill the inputs object based on the parsed command line arguments.
Parameters
ToFill A reference to the inputs object that will be filled.
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to fill the inputs object based on the parsed command line arguments.
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
getArguments()
template<typename InputType > boost::program_options::variables_map& CommandLine< InputType >::getArguments () inline
Method to get the parsed command line arguments.
Returns
A reference to the variables map that contains the parsed command line arguments. This method returns the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
References CommandLine< InputType >::initialize(), CommandLine< InputType >::initialized, and CommandLine< InputType >::variablesMap.
getArgumentsMap()
template<typename InputType > boost::program_options::variables_map CommandLine< InputType >::getArgumentsMap () inline
Method to get a copy of the parsed command line arguments.
Returns
A copy of the variables map that contains the parsed command line arguments. This method returns a copy of the parsed command line arguments. If the CommandLine object is not initialized, it calls the initialize method before returning the arguments.
{
         if (!initialized) {
             initialize();
         }
         return variablesMap;
     }
References CommandLine< InputType >::initialize(), CommandLine< InputType >::initialized, and CommandLine< InputType >::variablesMap.
getCmdArgs()
template<typename InputType > const CommandLineArgs& CommandLine< InputType >::getCmdArgs () const inline
Method to get the command line argv, argc objects.
Returns
A const reference to the CommandLineArgs object that contains the command line arguments. This method returns the command line arguments that were passed to the program.
 { return cmdArgs; }
References CommandLine< InputType >::cmdArgs.
getCurrentPrecision()
template<typename InputType > int CommandLine< InputType >::getCurrentPrecision () inline
Method to get the current precision.
Returns
The current precision as an integer. This method returns the current precision of long double values.
 { return variablesMap["precision"].as<int>(); }
References CommandLine< InputType >::variablesMap.
Referenced by InLab5::run(), OutLab4::run(), InLab4::run(), and OutLab5::run().
getInputs()
template<typename InputType > InputType& CommandLine< InputType >::getInputs () inline
Method to get the inputs.
Returns
A reference to the inputs. This method returns the inputs. If the CommandLine object is not initialized, it calls the initialize method before returning the inputs.
{
         if (!initialized) {
             initialize();
         }
         return _inputs;
     }
References CommandLine< InputType >::_inputs, CommandLine< InputType >::initialize(), and CommandLine< InputType >::initialized.
initialize()
template<typename InputType > virtual void CommandLine< InputType >::initialize () inline protected virtual
Method to initialize the CommandLine object. This method initializes the CommandLine object by printing the compile configurations and precision information, and parsing the command line arguments. If the CommandLine object is already initialized, it does nothing.
                       {
         if (initialized) {
             return;
         }
         // print the header
         printHeader(header);
         initialized = true;
         boost::program_options::options_description options("Parameters");
         buildInputArguments(options);
         options.add(buildGenerics());
         boost::program_options::store(boost::program_options::parse_command_line(cmdArgs.argc, cmdArgs.argv, options),
                                       variablesMap);
         boost::program_options::notify(variablesMap);
         // if help, print options and exit
         if (variablesMap.count("help")) {
             std::cout << options << "\n";
             exit(0);
         }
         // print compiler information
         if (!variablesMap.count("quiet")) {
             printCompileConfigs();
             // print command line options
             std::cout << options << "\n";
             printLine();
             printPrecisionInformation();
         }
         // consume and correct the input arguments
         performInputArgumentsCheck(variablesMap);
         if (variablesMap.count("bench")) {
             // build the profiler now
             ProfilerHelper::validateOptions(variablesMap);
         }
         if (!variablesMap.count("quiet")) {
Referenced by CommandLine< InputType >::getArguments(), CommandLine< InputType >::getArgumentsMap(), and CommandLine< InputType >::getInputs().
performInputArgumentsCheck()
template<typename InputType > virtual void CommandLine< InputType >::performInputArgumentsCheck (boost::program_options::variables_map & values) protected pure virtual
Method to perform a check on the input arguments.
Parameters
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to perform a check on the input arguments to ensure they are valid.
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
printCompileConfigs()
template<typename InputType > static void CommandLine< InputType >::printCompileConfigs () inline static protected
Method to print the compile configurations to the console. This method prints the compiler ID, compiler version, compiler flags, and Boost version and libraries to the console.
{
printHeader()
template<typename InputType > static void CommandLine< InputType >::printHeader (HeaderInfo & headerInfo) inline static protected
Method to print the project header to the console.
Parameters
headerInfo A reference to a HeaderInfo object containing information about the project. This method prints the project name, project description, student name, and submission date to the console.
{
         if (!headerInfo.HeaderArt.empty()) {
             std::cout << headerInfo.HeaderArt << std::endl;
         } else {
             std::cout << R"(
References HeaderInfo::HeaderArt, HeaderInfo::ProjectDescription, HeaderInfo::ProjectName, HeaderInfo::StudentName, and HeaderInfo::SubmissionDate.
printInputArguments()
template<typename InputType > virtual void CommandLine< InputType >::printInputArguments (boost::program_options::variables_map & values) protected pure virtual
Method to print the input arguments.
Parameters
values A reference to a variables_map object that contains the parsed command line arguments. This is a pure virtual method that must be implemented by derived classes. It is used to print the input arguments to the console.
Implemented in Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, Parser, and Parser.
printLine()
template<typename InputType > static void CommandLine< InputType >::printLine () inline static
Method to print a line to the console. This method prints a line of dashes to the console.
{
         std::cout << R"(--------------------------------------------------------------------------------)"
                   << "\n";
     }
Referenced by Parser::buildInputs(), and Parser::printInputArguments().
printPrecisionInformation()
template<typename InputType > void CommandLine< InputType >::printPrecisionInformation () inline protected
Method to print information about the precision of long double values. This method prints the default, maximum, and current precision of long double values to the console.
{
         const auto precision = variablesMap["precision"].as<int>();
setPrecision()
template<typename InputType > void CommandLine< InputType >::setPrecision (int precisionToSet = 5) inline
Method to set the precision of long double values.
Parameters
precisionToSet The desired precision as an integer (default value is 5). This method sets the precision of long double values to the specified value. If no value is provided, the default precision is set to 5.
{
         replace(variablesMap, "precision", std::setprecision(precisionToSet)._M_n);
     }
References replace(), and CommandLine< InputType >::variablesMap.
Field Documentation
_inputs
template<typename InputType > InputType CommandLine< InputType >::_inputs = InputType() protected
Referenced by CommandLine< InputType >::getInputs().
cmdArgs
template<typename InputType > CommandLine< InputType >::cmdArgs protected
A CommandLineArgs object to store the command line arguments.
This object is used to store the command line arguments that were passed to the program.
Referenced by CommandLine< InputType >::CommandLine(), and CommandLine< InputType >::getCmdArgs().
header
template<typename InputType > CommandLine< InputType >::header protected
A HeaderInfo object to store information about the project.
This object is used to store information about the project, such as the project name, project description, submission date, and student name.
Referenced by CommandLine< InputType >::CommandLine().
initialized
template<typename InputType > CommandLine< InputType >::initialized = false protected
A boolean flag to indicate whether the CommandLine object has been initialized.
This flag is set to true when the CommandLine object is initialized, and is used to prevent the object from being initialized more than once.
Referenced by CommandLine< InputType >::CommandLine(), CommandLine< InputType >::getArguments(), CommandLine< InputType >::getArgumentsMap(), and CommandLine< InputType >::getInputs().
variablesMap
template<typename InputType > CommandLine< InputType >::variablesMap protected
A variables_map object to store the parsed command line arguments.
This object is used to store the parsed command line arguments. It is filled by the Boost library's command line parser.
Referenced by CommandLine< InputType >::CommandLine(), CommandLine< InputType >::getArguments(), CommandLine< InputType >::getArgumentsMap(), CommandLine< InputType >::getCurrentPrecision(), and CommandLine< InputType >::setPrecision().
The documentation for this class was generated from the following file:
src/utils/CommandLine.h