NE591-008 C++17 Codebase: ResourceMonitor< T > Class Template Reference
ResourceMonitor< T > Class Template Reference
Singleton class that monitors resource instances.
#include <ResourceMonitor.h>
Static Public Member Functions
static void registerInstance (T *instance)
Method to register a new instance.
static ResourceMonitor< T > & getInstance ()
static void clear ()
static void unregisterInstance (T *instance)
Method to unregister an instance.
static size_t getMaxBytesEver ()
Private Member Functions
ResourceMonitor ()
Private constructor for the Singleton pattern.
ResourceMonitor (const ResourceMonitor &)=delete
Deleted copy constructor to prevent copying.
ResourceMonitor & operator= (const ResourceMonitor &)=delete
Deleted assignment operator to prevent copying.
void checkAndUpdateMaxSize (T *instance)
Private Attributes
std::unordered_map< T *, size_t > maxInstanceSizes
Map to keep track of instances.
Static Private Attributes
static ResourceMonitor< T > * monitor = nullptr
Detailed Description
template<typename T>
class ResourceMonitor< T >
Singleton class that monitors resource instances.
This class is used to keep track of instances of type T and record the maximum number of instances that have ever been created at any point in time.
Template Parameters
T The type of resource to monitor.
Constructor & Destructor Documentation
ResourceMonitor() [1/2]
template<typename T > ResourceMonitor< T >::ResourceMonitor () inline private
Private constructor for the Singleton pattern.
                      {
    }
ResourceMonitor() [2/2]
template<typename T > ResourceMonitor< T >::ResourceMonitor (const ResourceMonitor< T > &) private delete
Deleted copy constructor to prevent copying.
Member Function Documentation
checkAndUpdateMaxSize()
template<typename T > void ResourceMonitor< T >::checkAndUpdateMaxSize (T * instance) inline private
{
        if (instance == nullptr) {
            return;
        }
        const size_t newSize = instance->getAllocatedBytes();
        auto it = maxInstanceSizes.find(instance);
        if (it != maxInstanceSizes.end()) {
            // Key exists in the map, check if the current size is greater than the stored value
            size_t currentSize = newSize;
            if (currentSize > it->second) {
                // Update the value in the map
                it->second = currentSize;
            }
        } else {
            // Key does not exist in the map, you might want to handle this case as well
            // For example, you could insert the current size of the instance into the map
            maxInstanceSizes[instance] = newSize;
        }
    }
References ResourceMonitor< T >::maxInstanceSizes.
clear()
template<typename T > static void ResourceMonitor< T >::clear () inline static
{
        getInstance().maxInstanceSizes.clear();
    }
References ResourceMonitor< T >::getInstance().
Referenced by Profiler< FunctionType >::preRunMemoryCheck().
getInstance()
template<typename T > static ResourceMonitor<T>& ResourceMonitor< T >::getInstance () inline static
{
        if (!monitor) {
            monitor = new ResourceMonitor<T>();
        }
        return *monitor;
    }
References ResourceMonitor< T >::monitor.
Referenced by ResourceMonitor< T >::clear(), ResourceMonitor< T >::getMaxBytesEver(), ResourceMonitor< T >::registerInstance(), and ResourceMonitor< T >::unregisterInstance().
getMaxBytesEver()
template<typename T > static size_t ResourceMonitor< T >::getMaxBytesEver () inline static
{
        size_t sum = 0;
        for (const auto& pair : getInstance().maxInstanceSizes) {
            sum += pair.second;
        }
        return sum;
    }
References ResourceMonitor< T >::getInstance(), ResourceMonitor< T >::maxInstanceSizes, and MyBLAS::Stats::sum().
Referenced by Profiler< FunctionType >::postRunMemoryCheck(), and Profiler< FunctionType >::preRunMemoryCheck().
operator=()
template<typename T > ResourceMonitor& ResourceMonitor< T >::operator= (const ResourceMonitor< T > &) private delete
Deleted assignment operator to prevent copying.
registerInstance()
template<typename T > static void ResourceMonitor< T >::registerInstance (T * instance) inline static
Method to register a new instance.
Inserts the instance into the set and updates the maximum instances ever if necessary.
Parameters
instance Pointer to the instance to register.
{
        getInstance().checkAndUpdateMaxSize(instance);
    }
References ResourceMonitor< T >::getInstance().
unregisterInstance()
template<typename T > static void ResourceMonitor< T >::unregisterInstance (T * instance) inline static
Method to unregister an instance.
Erases the instance from the set.
Parameters
instance Pointer to the instance to unregister.
{
        getInstance().checkAndUpdateMaxSize(instance);
    }
References ResourceMonitor< T >::getInstance().
Field Documentation
maxInstanceSizes
template<typename T > std::unordered_map<T*, size_t> ResourceMonitor< T >::maxInstanceSizes private
Map to keep track of instances.
Referenced by ResourceMonitor< T >::checkAndUpdateMaxSize(), and ResourceMonitor< T >::getMaxBytesEver().
monitor
template<typename T > ResourceMonitor< T > * ResourceMonitor< T >::monitor = nullptr static private
Referenced by ResourceMonitor< T >::getInstance().
The documentation for this class was generated from the following file:
src/utils/profiler/ResourceMonitor.h