NE591-008 C++17 Codebase: MyBLAS::LazyVector< DataType > Class Template Reference
MyBLAS::LazyVector< DataType > Class Template Reference
A vector that lazily computes its values.
#include <LazyVector.h>
Public Types
using Generator = std::function< DataType(size_t)>
A generator function type.
Public Member Functions
LazyVector (size_t size, Generator generator)
Constructs a LazyVector with a given size and generator function.
size_t size () const
Get the size of the LazyVector.
DataType operator[] (size_t index) const
Access the element at a specific index.
LazyVector (const LazyVector &other)
Copy constructor for LazyVector.
LazyVector (const MyBLAS::Vector< DataType > &vector)
Constructor for the LazyVector class that accepts a Vector object.
LazyVector (MyBLAS::Vector< DataType > &vector)
Constructor for the LazyVector class that accepts a Vector object.
LazyVector & operator= (const LazyVector &other)
Assignment operator for LazyVector.
LazyVector operator+ (DataType scalar) const
Define the scalar addition operation for LazyVector.
LazyVector operator- (DataType scalar) const
Define the scalar subtraction operation for LazyVector.
LazyVector operator* (DataType scalar) const
Define the scalar multiplication operation for LazyVector.
LazyVector operator/ (DataType scalar) const
Define the scalar division operation for LazyVector.
LazyVector operator- () const
Define the unary negation operation for LazyVector.
LazyVector & operator+= (LazyVector const &b)
Define the in-place addition operation for LazyVector.
LazyVector & operator-= (LazyVector const &b)
Define the in-place subtraction operation for LazyVector.
LazyVector & operator*= (LazyVector const &b)=delete
Define the in-place multiplication operation for LazyVector.
LazyVector & operator/= (LazyVector const &b)=delete
Define the in-place division operation for LazyVector.
LazyVector & operator+= (DataType scalar)
Define the in-place scalar addition operation for LazyVector.
LazyVector & operator-= (DataType scalar)
Define the in-place scalar subtraction operation for LazyVector.
LazyVector & operator*= (DataType scalar)
Define the in-place scalar multiplication operation for LazyVector.
LazyVector & operator/= (DataType scalar)
Define the in-place scalar division operation for LazyVector.
Private Attributes
size_t size_
The size of the LazyVector.
Generator generator_
The generator function for computing values.
std::shared_ptr< MyBLAS::Vector< DataType > > vector_
A shared pointer to the memory backed matrix.
Friends
LazyVector operator+ (LazyVector const &a, LazyVector const &b)
Define the addition operation for LazyVector.
LazyVector operator- (LazyVector const &a, LazyVector const &b)
Define the subtraction operation for LazyVector.
DataType operator* (LazyVector const &a, LazyVector const &b)
Define the inner-product/dot-product operation for LazyVector.
LazyVector< bool > equal (LazyVector const &a, LazyVector const &b)
Define the element-wise equality comparison operation for LazyVector.
bool operator== (LazyVector const &a, LazyVector const &b)
Define the equality comparison operation for LazyVector.
bool operator!= (LazyVector const &a, LazyVector const &b)
Define the inequality comparison operation for LazyVector.
Detailed Description
template<typename DataType>
class MyBLAS::LazyVector< DataType >
A vector that lazily computes its values.
This class represents a vector whose values are computed on-the-fly each time they're accessed. The computation is defined by a generator function provided at construction time.
Note: This implementation does not cache computed values. Even though we're using the lazy evaluation pattern here, we've made the choice to ignore caching of computed values for simplicity and to save memory. This could be less efficient if the computation is expensive and the same values are accessed multiple times. The choice between this approach and caching computed values depends on the specific requirements of your application.
Member Typedef Documentation
Generator
template<typename DataType > using MyBLAS::LazyVector< DataType >::Generator = std::function<DataType(size_t)>
A generator function type.
Parameters
index The index for which to generate a value.
Returns
The computed value at the given index.
Constructor & Destructor Documentation
LazyVector() [1/4]
template<typename DataType > MyBLAS::LazyVector< DataType >::LazyVector (size_t size, Generator generator) inline explicit
Constructs a LazyVector with a given size and generator function.
Parameters
size The size of the vector.
generator The generator function for computing values.
         : size_(size), generator_(std::move(generator)) {}
Referenced by MyBLAS::LazyVector< DataType >::operator*(), MyBLAS::LazyVector< DataType >::operator+(), MyBLAS::LazyVector< DataType >::operator-(), and MyBLAS::LazyVector< DataType >::operator/().
LazyVector() [2/4]
template<typename DataType > MyBLAS::LazyVector< DataType >::LazyVector (const LazyVector< DataType > & other) inline
Copy constructor for LazyVector.
Parameters
other The LazyVector to copy from.
 : size_(other.size_), generator_(other.generator_), vector_(other.vector_) {}
LazyVector() [3/4]
template<typename DataType > MyBLAS::LazyVector< DataType >::LazyVector (const MyBLAS::Vector< DataType > & vector) inline explicit
Constructor for the LazyVector class that accepts a Vector object.
Parameters
vector The Vector object to initialize the LazyVector with.
                                                               : size_(vector.size()), vector_(std::make_shared<MyBLAS::Vector<DataType>>(vector)) {
         generator_ = [this](size_t i) { return (*(this->vector_))[i]; };
     }
References MyBLAS::LazyVector< DataType >::generator_, i, and MyBLAS::LazyVector< DataType >::vector_.
LazyVector() [4/4]
template<typename DataType > MyBLAS::LazyVector< DataType >::LazyVector (MyBLAS::Vector< DataType > & vector) inline explicit
Constructor for the LazyVector class that accepts a Vector object.
Parameters
vector The Vector object to initialize the LazyVector with.
                                                         : size_(vector.size()), vector_(std::make_shared<MyBLAS::Vector<DataType>>(vector)) {
         generator_ = [this](size_t i) { return (*(this->vector_))[i]; };
     }
References MyBLAS::LazyVector< DataType >::generator_, i, and MyBLAS::LazyVector< DataType >::vector_.
Member Function Documentation
operator*()
template<typename DataType > LazyVector MyBLAS::LazyVector< DataType >::operator* (DataType scalar) const inline
Define the scalar multiplication operation for LazyVector.
Parameters
scalar The scalar value to multiply by.
Returns
The LazyVector resulting from multiplying this LazyVector by 'scalar'.
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] * scalar; });
     }
References i, MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::size_.
operator*=() [1/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator*= (DataType scalar) inline
Define the in-place scalar multiplication operation for LazyVector.
Parameters
scalar The scalar value to multiply this LazyVector by.
Returns
A reference to this LazyVector after the multiplication operation.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) * scalar; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator*=() [2/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator*= (LazyVector< DataType > const & b) delete
Define the in-place multiplication operation for LazyVector.
Parameters
b The LazyVector to multiply with this LazyVector.
Returns
A reference to this LazyVector after the multiplication operation.
operator+()
template<typename DataType > LazyVector MyBLAS::LazyVector< DataType >::operator+ (DataType scalar) const inline
Define the scalar addition operation for LazyVector.
Parameters
scalar The scalar value to add.
Returns
The LazyVector resulting from adding 'scalar' to this LazyVector.
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] + scalar; });
     }
References i, MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::size_.
operator+=() [1/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator+= (DataType scalar) inline
Define the in-place scalar addition operation for LazyVector.
Parameters
scalar The scalar value to add to this LazyVector.
Returns
A reference to this LazyVector after the addition operation.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) + scalar; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator+=() [2/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator+= (LazyVector< DataType > const & b) inline
Define the in-place addition operation for LazyVector.
Parameters
b The LazyVector to add to this LazyVector.
Returns
A reference to this LazyVector after the addition operation.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) + b[i]; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator-() [1/2]
template<typename DataType > LazyVector MyBLAS::LazyVector< DataType >::operator- () const inline
Define the unary negation operation for LazyVector.
Returns
The LazyVector resulting from negating this LazyVector.
{
         return LazyVector(size_, [this](size_t i) { return -(*this)[i]; });
     }
References i, MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::size_.
operator-() [2/2]
template<typename DataType > LazyVector MyBLAS::LazyVector< DataType >::operator- (DataType scalar) const inline
Define the scalar subtraction operation for LazyVector.
Parameters
scalar The scalar value to subtract.
Returns
The LazyVector resulting from subtracting 'scalar' from this LazyVector.
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] - scalar; });
     }
References i, MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::size_.
operator-=() [1/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator-= (DataType scalar) inline
Define the in-place scalar subtraction operation for LazyVector.
Parameters
scalar The scalar value to subtract from this LazyVector.
Returns
A reference to this LazyVector after the subtraction operation.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) - scalar; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator-=() [2/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator-= (LazyVector< DataType > const & b) inline
Define the in-place subtraction operation for LazyVector.
Parameters
b The LazyVector to subtract from this LazyVector.
Returns
A reference to this LazyVector after the subtraction operation.
{
         auto old_gen = generator_;
         generator_ = [old_gen, b](size_t i) { return old_gen(i) - b[i]; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator/()
template<typename DataType > LazyVector MyBLAS::LazyVector< DataType >::operator/ (DataType scalar) const inline
Define the scalar division operation for LazyVector.
Parameters
scalar The scalar value to divide by.
Returns
The LazyVector resulting from dividing this LazyVector by 'scalar'.
{
         return LazyVector(size_, [this, scalar](size_t i) { return (*this)[i] / scalar; });
     }
References i, MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::size_.
operator/=() [1/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator/= (DataType scalar) inline
Define the in-place scalar division operation for LazyVector.
Parameters
scalar The scalar value to divide this LazyVector by.
Returns
A reference to this LazyVector after the division operation.
{
         auto old_gen = generator_;
         generator_ = [this, old_gen, scalar](size_t i) { return old_gen(i) / scalar; };
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, and i.
operator/=() [2/2]
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator/= (LazyVector< DataType > const & b) delete
Define the in-place division operation for LazyVector.
Parameters
b The LazyVector to divide this LazyVector by.
Returns
A reference to this LazyVector after the division operation.
operator=()
template<typename DataType > LazyVector& MyBLAS::LazyVector< DataType >::operator= (const LazyVector< DataType > & other) inline
Assignment operator for LazyVector.
Parameters
other The LazyVector to assign from.
Returns
A reference to this LazyVector after assignment.
{
         if (this != &other) {
             size_ = other.size_;
             generator_ = other.generator_;
             vector_ = other.vector_;
         }
         return *this;
     }
References MyBLAS::LazyVector< DataType >::generator_, MyBLAS::LazyVector< DataType >::size_, and MyBLAS::LazyVector< DataType >::vector_.
operator[]()
template<typename DataType > DataType MyBLAS::LazyVector< DataType >::operator[] (size_t index) const inline
Access the element at a specific index.
Parameters
index The index of the element to access.
Returns
The computed value at the given index.
{
         return generator_(index);
     }
References MyBLAS::LazyVector< DataType >::generator_.
size()
template<typename DataType > size_t MyBLAS::LazyVector< DataType >::size () const inline
Get the size of the LazyVector.
Returns
The size of the vector.
 { return size_; }
References MyBLAS::LazyVector< DataType >::size_.
Referenced by MyBLAS::TEST_F(), MyBLAS::TYPED_TEST(), and MyBLAS::Vector< T >::Vector().
Friends And Related Function Documentation
equal
template<typename DataType > LazyVector<bool> equal (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the element-wise equality comparison operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
A LazyVector of bools indicating element-wise equality.
{
         auto binary_op = [](DataType const& x, DataType const& y) { return x == y; };
         VectorExpression<bool, LazyVector, LazyVector, decltype(binary_op)> expr(a, b, binary_op);
         return LazyVector<bool>(a.size(), [expr](size_t i) { return expr[i]; });
     }
operator!=
template<typename DataType > bool operator!= (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the inequality comparison operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
true if the LazyVectors are not equal, false if they are equal.
{
         return !(a == b);
     }
operator*
template<typename DataType > DataType operator* (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the inner-product/dot-product operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
The result of the inner-product/dot-product of 'a' and 'b'.
{
         assert(a.size() == b.size());
         auto binary_op = [](DataType const& x, DataType const& y) { return x * y; };
         VectorExpression<DataType, LazyVector, LazyVector, decltype(binary_op)> expr(a, b, binary_op);
         DataType result = 0;
         for (size_t i = 0; i < a.size(); ++i) {
             result += expr[i];
         }
         return result;
     }
operator+
template<typename DataType > LazyVector operator+ (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the addition operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
The LazyVector resulting from the addition of 'a' and 'b'.
{
         auto binary_op = [](DataType const& x, DataType const& y) { return x + y; };
         VectorExpression<DataType, LazyVector, LazyVector, decltype(binary_op)> expr(a, b, binary_op);
         return LazyVector(a.size(), [expr](size_t i) { return expr[i]; });
     }
operator-
template<typename DataType > LazyVector operator- (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the subtraction operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
The LazyVector resulting from the subtraction of 'a' and 'b'.
{
         auto binary_op = [](DataType const& x, DataType const& y) { return x - y; };
         VectorExpression<DataType, LazyVector, LazyVector, decltype(binary_op)> expr(a, b, binary_op);
         return LazyVector(a.size(), [expr](size_t i) { return expr[i]; });
     }
operator==
template<typename DataType > bool operator== (LazyVector< DataType > const & a, LazyVector< DataType > const & b) friend
Define the equality comparison operation for LazyVector.
Parameters
a The first LazyVector.
b The second LazyVector.
Returns
true if the LazyVectors are equal, false otherwise.
{
         if (a.size() != b.size()) {
             return false;
         }
         auto eq = equal(a, b);
         for (size_t i = 0; i < eq.size(); ++i) {
             if (!eq[i]) {
                 return false;
             }
         }
         return true;
     }
Field Documentation
generator_
template<typename DataType > Generator MyBLAS::LazyVector< DataType >::generator_ private
The generator function for computing values.
Referenced by MyBLAS::LazyVector< DataType >::LazyVector(), MyBLAS::LazyVector< DataType >::operator*=(), MyBLAS::LazyVector< DataType >::operator+=(), MyBLAS::LazyVector< DataType >::operator-=(), MyBLAS::LazyVector< DataType >::operator/=(), MyBLAS::LazyVector< DataType >::operator=(), and MyBLAS::LazyVector< DataType >::operator[]().
size_
template<typename DataType > size_t MyBLAS::LazyVector< DataType >::size_ private
The size of the LazyVector.
Referenced by MyBLAS::LazyVector< DataType >::operator*(), MyBLAS::LazyVector< DataType >::operator+(), MyBLAS::LazyVector< DataType >::operator-(), MyBLAS::LazyVector< DataType >::operator/(), MyBLAS::LazyVector< DataType >::operator=(), and MyBLAS::LazyVector< DataType >::size().
vector_
template<typename DataType > std::shared_ptr<MyBLAS::Vector<DataType> > MyBLAS::LazyVector< DataType >::vector_ private
A shared pointer to the memory backed matrix.
Referenced by MyBLAS::LazyVector< DataType >::LazyVector(), and MyBLAS::LazyVector< DataType >::operator=().
The documentation for this class was generated from the following file:
src/utils/math/blas/vector/LazyVector.h