NE591-008 C++17 Codebase: OutLab1 Class Reference
OutLab1 Class Reference
#include <outlab1.h>
Public Member Functions
OutLab1 (CommandLineArgs args)
virtual void execute ()
Executes the project.
virtual Parser getTerminal () const
Returns the terminal.
Protected Member Functions
HeaderInfo buildHeaderInfo () override
Builds the header information.
void run (NoOutput &output, MatrixConstructParams &input, boost::program_options::variables_map &values) override
This function runs the main logic of the program.
virtual void initialize ()
Initializes the project.
virtual void finalize ()
virtual void timedRun ()
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
virtual void preRun (NoOutput &output, MatrixConstructParams &input, boost::program_options::variables_map &values)
A hook for performing actions before the run.
virtual void postRun (NoOutput &output, MatrixConstructParams &input, boost::program_options::variables_map &values)
A hook for performing actions after the run.
auto getProfiler (Func func, size_t samples, long double timeout=0, std::string description="")
Creates a Profiler object with the given function, number of samples, timeout, and description.
auto getProfiler (Func func, size_t samples, std::string description="")
Creates a Profiler object with the given function, number of samples, and description.
auto getProfiler (Func func, std::string description="")
Creates a Profiler object with the given function and description.
Protected Attributes
CommandLineArgs cmdArgs
Parser terminal
NoOutput outputs
Detailed Description
Constructor & Destructor Documentation
OutLab1()
OutLab1::OutLab1 (CommandLineArgs args) inline explicit
 : Project(args) {}
Member Function Documentation
buildHeaderInfo()
HeaderInfo OutLab1::buildHeaderInfo () inline override protected virtual
Builds the header information.
Returns
The header information.
Implements Project< MatrixConstructParams, Parser, NoOutput >.
{
         return HeaderInfo{
             .ProjectName = "OutLab 01",
             .ProjectDescription = "Non-vectorized, elementwise (mul, add) operations on 2D matrices",
             .SubmissionDate = "09/01/2023",
             .StudentName = "Arjun Earthperson",
             .HeaderArt = R"(
                                                _
                  ___                          (_)
                _/XXX\
 _             /XXXXXX\_                                    __
 X\__    __   /X XXXX XX\                          _       /XX\__      ___
     \__/  \_/__       \ \                       _/X\__   /XX XXX\____/XXX\
   \  ___   \/  \_      \ \               __   _/      \_/  _/  -   __  -  \__/
  ___/   \__/   \ \__     \\__           /  \_//  _ _ \  \     __  /  \____//
 /  __    \  /     \ \_   _//_\___     _/    //           \___/  \/     __/
 __/_______\________\__\_/________\_ _/_____/_____________/_______\____/_______
                                   /|\
                                  / | \
                                 /  |  \
                                /   |   \
 )",
         };
     }
References HeaderInfo::ProjectName.
execute()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::execute () inline virtual inherited
Executes the project.
                    {
         initialize();
         timedRun();
         finalize();
     }
finalize()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::finalize () inline protected virtual inherited
{
     }
getProfiler() [1/3]
auto Project< MatrixConstructParams , Parser , NoOutput >::getProfiler (Func func, size_t samples, long double timeout = 0, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, timeout, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
timeout The maximum time for the profiling.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, timeout, description);
     }
getProfiler() [2/3]
auto Project< MatrixConstructParams , Parser , NoOutput >::getProfiler (Func func, size_t samples, std::string description = "") inline protected inherited
Creates a Profiler object with the given function, number of samples, and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
samples The number of samples to be taken.
description The description of the profiling.
Returns
A Profiler object.
{
         return Profiler(func, samples, 0, description);
     }
getProfiler() [3/3]
auto Project< MatrixConstructParams , Parser , NoOutput >::getProfiler (Func func, std::string description = "") inline protected inherited
Creates a Profiler object with the given function and description.
Template Parameters
Func The type of the function to be profiled.
Parameters
func The function to be profiled.
description The description of the profiling.
Returns
A Profiler object.
{
         return ProfilerHelper::InitProfiler(func, getTerminal().getArguments(), description);
     }
getTerminal()
virtual Parser Project< MatrixConstructParams , Parser , NoOutput >::getTerminal () const inline virtual inherited
Returns the terminal.
Returns
The terminal.
 { return terminal; }
initialize()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::initialize () inline protected virtual inherited
Initializes the project.
                       {
         terminal = CommandLineParserType(buildHeaderInfo(), cmdArgs);
         terminal.getInputs();
         outputs = OutputType();
     }
postRun()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::postRun (NoOutput & output, MatrixConstructParams & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions after the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
preRun()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::preRun (NoOutput & output, MatrixConstructParams & input, boost::program_options::variables_map & values) inline protected virtual inherited
A hook for performing actions before the run.
Parameters
output The output data.
input The input data.
values The variable map.
 {}
run()
void OutLab1::run (NoOutput & output, MatrixConstructParams & input, boost::program_options::variables_map & values) inline override protected virtual
This function runs the main logic of the program.
Parameters
values A map of variables parsed from the command line arguments.
The function first extracts the input parameters from the values map. It then builds and prints three matrices A, B, and F using the input parameters. After that, it computes and prints three more matrices C, D, and E using the previously built matrices and the scalar value from the input parameters.
Implements Project< MatrixConstructParams, Parser, NoOutput >.
{
         // build matrix
         ArgsPrintMatrix matrix{
             .start_row = 1, // spec says indexing starts from 1 not 0.
             .start_col = 1, // spec says indexing starts from 1 not 0.
             .num_rows = input.M,
             .num_cols = input.N,
             .inputParams = input,
             .evaluate = elementFromA,
         };
         printMatrix(matrix, "Matrix A: ");
         Parser::printLine();
         // build matrix B
         matrix.evaluate = elementFromB;
         printMatrix(matrix, "Matrix B: ");
         Parser::printLine();
         // build N x J matrix F
         matrix.num_rows = input.N;
         matrix.num_cols = input.J;
         matrix.evaluate = elementFromF;
         printMatrix(matrix, "Matrix F: ");
         Parser::printLine();
         // Now the computed values
         std::cout << std::setw(44) << "Outputs\n";
         Parser::printLine();
         // build M x N matrix C
         matrix.num_rows = input.M;
         matrix.num_cols = input.N;
         matrix.evaluate = elementFromC;
         printMatrix(matrix, "Matrix C = A+B");
         Parser::printLine();
         // build matrix D
         matrix.evaluate = elementFromD;
         printMatrix(matrix, "Matrix D = kA");
         Parser::printLine();
         // build matrix E
         matrix.num_rows = input.M;
         matrix.num_cols = input.J;
         matrix.evaluate = elementFromE;
         printMatrix(matrix, "Matrix E = AF");
         Parser::printLine();
     }
References elementFromA(), elementFromB(), elementFromC(), elementFromD(), elementFromE(), elementFromF(), Input::J, Input::M, Input::N, CommandLine< InLab6Inputs >::printLine(), printMatrix(), and ArgsPrintMatrix::start_row.
timedRun()
virtual void Project< MatrixConstructParams , Parser , NoOutput >::timedRun () inline protected virtual inherited
Executes the project in a timed manner. This method calls preRun, run, and postRun methods in sequence.
                     {
         preRun(outputs, terminal.getInputs(), terminal.getArguments());
         run(outputs, terminal.getInputs(), terminal.getArguments());
         postRun(outputs, terminal.getInputs(), terminal.getArguments());
     }
Field Documentation
cmdArgs
CommandLineArgs Project< MatrixConstructParams , Parser , NoOutput >::cmdArgs protected inherited
outputs
NoOutput Project< MatrixConstructParams , Parser , NoOutput >::outputs protected inherited
terminal
Parser Project< MatrixConstructParams , Parser , NoOutput >::terminal protected inherited
The documentation for this class was generated from the following file:
src/labs/outlab1/outlab1.h